### ISSUE TITLE
cider-interactive-eval not using cider-current-ns?

### ISSUE THREAD

**Issue by reedho** [clojure-emacs/cider#1002]
Previously, the behavior of C-x C-e is evaling last sexp using buffer namespace.

In current master, the cider-interactive-eval is not using (cider-current-ns) as last arg to nrepl-request:eval. 

Is this intended change?

**Comment by bbatsov** [comment]
Have you run into any problems?

See https://github.com/clojure-emacs/cider/commit/aa80e2c856bdb0c38a377d00bc5aed15105ce98c for details.

**Comment by reedho** [comment]
My problem is that C-x C-e not eval using current buffers' namespace, its eval under 'user namespace. 

Open file, M-x cider-connect, then eval a form with C-x C-e will have problem as it run with user namespace, e.g. Unable to resolve symbol ...

CompilerException java.lang.RuntimeException: Unable to resolve symbol: env in this context, compiling:(/tmp/form-init3574298399047502377.clj:1:1) 

At this point, cider--cached-ns-form value is nil.

Do C-c C-n, and now the value of cider--cached-ns-form is string of buffer ns form. 

C-x C-e now still not work, but now it give message: error in process filter: Beginning of buffer

Btw, C-c C-c still work as expected, its eval under buffers' namespace. 

Hope this clear.

**Comment by bbatsov** [comment]
Yeah, this is clear. We're not sending the `ns` indeed. I wonder how nobody noticed this for so long. //cc @cichli @vspinu

**Comment by cichli** [comment]
Sorry, when I touched this code I mistakenly thought we were still sending ns forms with interactive evals... I didn't notice because I have a habit of reloading entire namespaces rather than individual forms.
