### ISSUE TITLE
error in process filter: line-move-visual after clearing the cider buffer 

### ISSUE THREAD

**Issue by bpoweski** [clojure-emacs/cider#1006]
When I clear a repl using <kbd>C-c M-o</kbd> in a clojure buffer and then invoke <kbd>C-c C-k</kbd>, if the the evaluations yields any output I get the following errors in `*Messages*`:

```
error in process filter: line-move-visual: Beginning of buffer
error in process filter: Beginning of buffer
error in process filter: line-move-visual: Beginning of buffer
error in process filter: Beginning of buffer
error in process filter: line-move-visual: Beginning of buffer
error in process filter: Beginning of buffer
```

This doesn't happen on the initial launch when the version banner is shown. The markers `cider-repl-output-start` and `cider-repl-output-end` are both nil, though I don't know if that is relevant or not.

Also, I switch the repl buffer and hit return then repeat the <kbd>C-c C-k</kbd>, the output is displayed in the repl as expected.

Thoughts?

**Comment by bbatsov** [comment]
CIDER & Emacs version info?

**Comment by bpoweski** [comment]
My apologies!

```
; CIDER 0.9.0snapshot (package: 20150303.1353) (Java 1.7.0_07, Clojure 1.5.1, nREPL 0.2.7)
```

**Comment by bbatsov** [comment]
Thanks! I managed to reproduce this; now I just have to figure out what caused it...

**Comment by bbatsov** [comment]
The problem is definitely in `cider-repl-clear-buffer`. Perhaps the @GordonGustafson's recent changes broke it. Will need more time to investigate this...

**Comment by bpoweski** [comment]
Thank you for looking into this.

**Comment by bbatsov** [comment]
@danskarda fixed this.

**Comment by jonpither** [comment]
Ah this has killed me today. Thanks for the fix.
