### ISSUE TITLE
choice popup for completion candidates makes it nearly impossible to write method names

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1007]
I'm doing some java interop at the repl and when I'm writing something like `(.get` the completion backend will trigger the function below to choose among the various classes that have a method starting with `get`.  In this context we should probably just merge all the candidates.  It's almost impossible to type the method name because the selection popup keeps appearing.

```elisp
(defun cider--var-choice (var-info)
  "Prompt to choose from among multiple VAR-INFO candidates, if required.
This is needed only when the symbol queried is an unqualified host platform
method, and multiple classes have a so-named member.  If VAR-INFO does not
contain a `candidates' key, it is returned as is."
  (let ((candidates (nrepl-dict-get var-info "candidates")))
    (if candidates
        (let* ((classes (nrepl-dict-keys candidates))
               (choice (completing-read "Member in class: " classes nil t))
               (info (nrepl-dict-get candidates choice)))
          info)
      var-info)))
```

**Comment by bbatsov** [comment]
I don't quite get what you mean. Some animated gif illustrating the problem might be helpful.

**Comment by expez** [comment]
Just put this into the repl and you should see it:

![.](http://i.imgur.com/cnD0o7h.png)

**Comment by expez** [comment]
If you can't see this then it's probably `company-quickhelp` but it's happening WAY before the 0.5s timeout it should be waiting before trying to retrieve any docs.

**Comment by expez** [comment]
Yeah, this is `company-quickhelp` ruining my day.

**Comment by expez** [comment]
Not sure how to fix this.

The current behavior of this function is OK when called interactively (with `C-h` or `f1`) but not otherwise:

```elisp
(defun cider-var-info (var &optional all)
  "Return VAR's info as an alist with list cdrs.
When multiple matching vars are returned you'll be prompted to select one,
unless ALL is truthy."
  (when (and var (not (string= var "")))
    (let ((var-info (cider-sync-request:info var)))
      (if all var-info (cider--var-choice var-info)))))
```

The most expedient fix is to just override `cider--var-choice` to be `identity` in `company-quickhelp`.  What do you think @bbatsov?

I think we need to revisit our usage of `cider-var-info` in `clj-refactor` too.  some of the usage there is going to be annoying when ambiguities have to be resolved manually.
