### ISSUE TITLE
cider-macroexpand commands hang if macro throws exception

### ISSUE THREAD

**Issue by pgroce** [clojure-emacs/cider#1008]
When expanding a macro with ``cider-macroexpand-1`` and friends, Emacs will hang if the macro throws an exception during expansion. This is with Emacs 24.4, and the following version string in ``*cider-nrepl*``:

```
; CIDER 0.9.0snapshot (package: 20150303.1353) (Java 1.8.0_31, Clojure 1.6.0, nREPL 0.2.7)
```

To reproduce, run ``cider-macroexpand-1`` with the point at the end of the following code:

```
(with-open ["a" foo] bar)
```
(Feel free to use correct forms for ``foo`` and ``bar``, but they're irrelevant.)

When the above is expanded, ``with-open`` will throw an ``IllegalArgumentException`` during expansion because ``"a"`` is not a symbol. Emacs will hang (presumably waiting on the repl connection) until ``C-g`` is pressed.

By contrast, when the above code is executed with ``C-x C-e``, CIDER reports the error to the ``*cider-repl*`` buffer and returns control to the user.

At a minimum IMO, control should be returned to the user and there should be some indication an error occurred, preferably with the error itself output somewhere. I will leave the details for further discussion, as warranted. :)

**Comment by bbatsov** [comment]
I've added some error handling to the middleware. Test it again and let me know if there are still some issues.
