### ISSUE TITLE
Command to run (-main)

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1011]
I couldn't find anything about this in the readme or the issues list. 
Is there a command to run the project's `-main` function?

Currently what I do is write `;; (-main)` somewhere in the file, and then manually move point to it and hit `C-x C-e` whenever I want to run `-main`. Is there a built-in key for that? 
If not, consider this a feature request.

**Comment by bbatsov** [comment]
There's no such command, but we can definitely add one. Guess we'll just have to check the list of known vars for `-main` and run it. If case of ambiguities we can prompt the user for action.

**Comment by cichli** [comment]
You can use the `:init-ns` and `:init` options in `project.clj` to accomplish this (see [here](https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L342-L345)), but any printed output will end up in `*nrepl-server*` rather than the REPL buffer.

**Comment by bbatsov** [comment]
> but any printed output will end up in *nrepl-server* rather than the REPL buffer.

Our oldest most dreaded problem. :-)

**Comment by bbatsov** [comment]
@Malabarba Now that you're pretty familiar with CIDER I guess you can implement this yourself. :-)

**Comment by Malabarba** [comment]
Ironically I no longer need it. :-) But it should be simple enough now. I'll take up the torch.

**Comment by Malabarba** [comment]
Is there a way to get the `:main` entry in from `project.clj`?

**Comment by bbatsov** [comment]
You can also read the file, but I really think the better approach you be to just filter all vars for `-main` and give the user the right option to select the one they need. Using `project.clj` is lein specific and we should avoid doing tool specific things.

**Comment by Malabarba** [comment]
Good point!
