### ISSUE TITLE
CIDER-side and cljs.repl.node

### ISSUE THREAD

**Issue by aJchemist** [clojure-emacs/cider#1018]
```clojure
(defproject scratch "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/clojurescript "0.0-3058"]]
  :profiles
  {:dev {:dependencies [[com.cemerick/piggieback "0.1.5"]]
         :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}}})
```
```
; CIDER 0.8.2 (Java 1.7.0_45, Clojure 1.6.0, nREPL 0.2.6)
user> (require '[cljs.repl.node :as node])
nil
user> (cemerick.piggieback/cljs-repl :repl-env (node/repl-env)
                               :output-dir ".cljs_node_repl"
                               :cache-analysis true
                               :source-map true)
Type `:cljs/quit` to stop the ClojureScript REPL
nil
cljs.user> (.-version js/process) 
"v0.12.0"
cljs.user> a
WARNING: Use of undeclared Var /a at line 1 <cljs repl>
ExceptionInfo repl:1
try{cljs.core.pr_str.call(null,(function (){var ret__3291__auto__ = .a;
                                                                    ^
SyntaxError: Unexpected token .
    at Object.exports.runInThisContext (vm.js:73:16)
    at Domain.<anonymous> ([stdin]:41:34)
    at Domain.run (domain.js:197:16)
    at Socket.<anonymous> ([stdin]:40:25)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)  clojure.core/ex-info (core.clj:4403)
cljs.user>
```
In cljs.repl.node, once an error or exception occured, java process eat up my cpu time (like 100-200%) if repl is jack in through cider. (I'm running OS X Yosemite)

otherwise, http://swannodette.github.io/2014/12/31/the-old-way-the-new-way/
this walkthrough has no cpu usage issue. 

I think some cider-side error handling part makes the inf-loop in this case, not piggieback nor cljs.

**Comment by cichli** [comment]
This is resolved in the current snapshot, please see #1004.

**Comment by aJchemist** [comment]
hmm weird. right now I'm checking current snapshot. (0.9.0-snapshot cider, cider-nrepl)
everything ok but cpu usage.
![screen shot 2015-03-15 at 8 54 29 pm](https://cloud.githubusercontent.com/assets/1694505/6655883/abe78710-cb55-11e4-880d-25236787bfbd.png)

**Comment by cichli** [comment]
Oh, latest clojars snapshot is from March 7th but the commit was pushed more recently :-). Can you try cloning cider-nrepl and running `lein install`, or wait for the next snapshot to be pushed?
