### ISSUE TITLE
REPL Prompt Customization

### ISSUE THREAD

**Issue by timvisher** [clojure-emacs/cider#1035]
I'd like to use the following repl format:

```
*ns*
> 
```

Seems like the sort of thing that could be provided be a simple Customize variable.

**Comment by cichli** [comment]
`cider-repl-prompt-function`, which allows for exactly this, is on master :-). I think @bbatsov is planning a release soon.

**Comment by bbatsov** [comment]
Yeah, the release should happen after the legendary debugger gets merged.

**Comment by timvisher** [comment]
:+1:
