### ISSUE TITLE
Expand the commands available in cider-repl-shortcuts.

### ISSUE THREAD

**Issue by EricGebhart** [clojure-emacs/cider#1038]
I'm not sure who uses these but they are path of least resistance when helping out newbies to emacs and clojure.  It would be nice if cider-doc, jump-to, inspect, undef, browse-ns  were available here.  While everyone should learn rather quickly to 'describe-mode' or 'C-h b',   ,help is a lot friendlier and is a helpful gateway for beginners to start learning the powers of cider.

**Comment by bbatsov** [comment]
> ,help is a lot friendlier and is a helpful gateway for beginners to start learning the powers of cider.

Maybe. No idea how many people actually even know it exists. PRs welcome.

**Comment by EricGebhart** [comment]
I agree. I only know of them because I read a lot of code.
I seldom use them, but who knows.

I have a newbie that I'm helping and these came in handy.

I have PR ready. I'm just waiting for the dust to settle around the other PRs.

----- Bozhidar Batsov's Original Message -----

**Comment by bbatsov** [comment]
On a related note I've been thinking for a while to add a longer "welcome banner" with some pointers to get people started (help commands, etc). It might even make sense to inject some CIDER functions into the user namespace (e.g. some help/tutorial).

**Comment by EricGebhart** [comment]
That is a good idea.  I'll take a look around.

----- Bozhidar Batsov's Original Message -----
