### ISSUE TITLE
Debugger errors with 'recur and 'do

### ISSUE THREAD

**Issue by DesmondHayes** [clojure-emacs/cider#1048]
1.
```clojure
(defn factorial
  [n]
  (loop [cnt n acc 1]
    (if (zero? cnt)
      acc
      (recur (dec cnt) (* acc cnt)))))
```
C-u C-c C-c to debug factorial gives an error in cider buffer:
```
Failed to instrument  (recur # #)
CompilerException java.lang.UnsupportedOperationException: Can only recur from tail position, compiling:(blah-blah-blah)
```
2.
```clojure
(defn foo
  [v]
  (do v))
```
C-u C-c C-c to debug foo gives an error in cider buffer:
```
Failed to instrument  (do v)
```
and also sometimes hangs cider repl so that only C-c C-c can stop it (at which point it gives a huge error with a stacktrace).

**Comment by Malabarba** [comment]
By the way, I think this can be closed now.
