### ISSUE TITLE
Lots of version warnings from `cider-jack-in`

### ISSUE THREAD

**Issue by deflexor** [clojure-emacs/cider#1056]
Trying to get started with cider REPL using README instructions:
`$ lein version`
`Leiningen 2.5.1 on Java 1.7.0_75`
`$ lein new demo`
`$ emacs`
`M-x cider-jack-in`

```
; CIDER 0.9.0alpha (package: 20150330.1124) (Java 1.7.0_75, Clojure 1.6.0, nREPL 0.2.6)
WARNING: CIDER requires nREPL 0.2.7 (or newer) to work properly
WARNING: The following required nREPL ops are not supported: 
apropos classpath complete eldoc format-code format-edn info inspect-pop inspect-push inspect-refresh macroexpand ns-list ns-vars resource stacktrace toggle-trace-var toggle-trace-ns undef
Please, install (or update) cider-nrepl 0.9.0-SNAPSHOT and restart CIDER
WARNING: CIDER's version (0.9.0-snapshot) does not match cider-nrepl's version (not installed)
```

**Comment by mavbozo** [comment]
by default, leiningen 2.5.1 includes [nREPL](https://github.com/clojure/tools.nrepl) version 0.2.6.

You can override `nREPL` version by including
```
[org.clojure/tools.nrepl "0.2.7"]
```
In your `~/.lein/profiles.clj`  `:user`'s `:dependencies`
or
in your `project.clj`'s `:dependencies`

**Comment by bbatsov** [comment]
You also have to install `cider-nrepl` as noted in the README.
