### ISSUE TITLE
Add cider-find-ns

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1061]
Here are some very common situations for me:

1. I know some function exists, but I don't recall the exact name.
2. I think maybe some function exists in `lib` and I want to check before I write it myself

I'm solving these now by using `cider-classpath`, `C-s` down to the `lib`, open the jar, look at the list of files and then picking something that looks promising.

`cider-find-ns` would give a completing read of all the available namespaces available on classpath, not just in my own project, and jumps to the selected ns.

**Comment by bbatsov** [comment]
If memory serves there's no mapping between namespaces and source files. How would you propose to tackle this? Maybe just use the info from a random var in the ns?

**Comment by expez** [comment]
`tools.namespace` has everything we need to implement this.  Specifically we can build a `tracker` for everything on classpath.  The tracker has a `:filemap` which is a map of namespaces to files.

**Comment by bbatsov** [comment]
> tools.namespace has everything we need to implement this. Specifically we can build a tracker for everything on classpath. The tracker has a :filemap which is a map of namespaces to files.

PR welcome, then! :-)

**Comment by bbatsov** [comment]
Anyone working on this?

**Comment by expez** [comment]
Guess I'm not most likely candidate and I haven't gotten to it yet

**Comment by rundis** [comment]
@expez When/if you get to this, maybe the ns-list op could use tools.namespace as well ?!

**Comment by alexander-yakushev** [comment]
Does the ns-list returns only the list of namespaces, or their content as well?

**Comment by expez** [comment]
@alexander-yakushev what we need to implement this is a map of `ns => file` which can be created using `tools.namespace`.

**Comment by bbatsov** [comment]
Yeah, this will probably be easy. The problem is that we'll also need to check if a namespace is loaded or not when we use this in places like the namespace browser. This shouldn't be hard, but still - it's a work we have to do.
