### ISSUE TITLE
cider-jump-to doesn't respect other-window

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1063]
`cider-jump-to` uses `(pop-to-buffer buffer)` to open `buffer` whenever `other-window` is truthy.  `pop-to-buffer` has a preference for selecting another window but quite often it doesn't.  Can we change this so it's `other-window` instead of `maybe-other-window`?

Also, while messing around with this I called `pop-to-buffer` with a single window and sometimes it does vertical splits and other times horizontal splits.  Is there some setting I can tweak to let emacs know I hate horizontal splits?

**Comment by vspinu** [comment]
> has a preference for selecting another window but quite often it doesn't.

That comes down to your own configuration and size of your display. There are quite some ways to customize your setup. [Elisp info](https://www.gnu.org/software/emacs/manual/html_node/elisp/Windows.html) on window handling has it all.

>  Is there some setting I can tweak to let emacs know I hate horizontal splits?

Yes, see `split-height-threshold`, `split-width-threshold`.  Se also [this](https://www.gnu.org/software/emacs/manual/html_node/elisp/Choosing-Window-Options.html#Choosing-Window-Options) info page.

**Comment by expez** [comment]
Wading through that information was really hard work and I couldn't get it completely to my liking, but this isn't cider's fault.
