### ISSUE TITLE
More keybindings in cider-browse-ns

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1066]
I'd forgotten about `cider-browse-ns` (cider is getting large!) and when I tried it again today my expectation was that `RET` would take me to the source but it displays the docs instead.

In any event the keymap could use some more stuff like `f` for `find` and `d` for doc.

**Comment by bbatsov** [comment]
Sure, that makes a lot of sense. For some crazy reason I even thought I had actually done this already. :-)
