### ISSUE TITLE
Add some documentation about debugging CIDER

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1067]
I'm tired of explaining the same things over and over again in issues and chats.

It should go in the README or a wiki page.

**Comment by Malabarba** [comment]
The fruit might hang even lower if there's a link or quote for one of these previous explanations.

**Comment by bbatsov** [comment]
Good point - here one https://github.com/clojure-emacs/cider/issues/459

Basically we need to mention:

* An overview of the `*nrepl-events*` buffer
* `toggle-debug-on-error`
* basic edebug usage
* a few key functions that should be instrumented if one wants to examine the CIDER boot process (e.g. repl creation)
