### ISSUE TITLE
Fix all checkdoc errors

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1071]
The code is filled with `M-x checkdoc` violations. It'd be great if those were all fixed.

**Comment by vspinu** [comment]
Is there anyone already working on this one? I can definitely fix nrepl-client.el as most of the code is now mine. I can also do cider-interaction.el, cider-nrepl.el, cider.el as I am very familiar with with that code. 

@EricGebhart you were fixing `cider-interaction.el`, is that already in the master?

**Comment by cichli** [comment]
I have started to take a look at this (along with the compiler warnings + splitting of `cider-interaction.el`) but have been waiting for outstanding PRs to be merged before properly tackling it; happy for you to do it if you want to.

**Comment by vspinu** [comment]
Ok, then. I will fix what I can besides `cider-interaction.el`  as that doesn't interfere with PRs, and we see what we do with `cider-interaction.el` once all PRs are in.  

If you get down to splitting cider-interaction please keep in mind that the `nrepl-client.el` will eventually be split from cider (to be used by other projects). That basically means that `cider-client.el` is an insulation api layer between `nrepl-client.el` and all the rest of CIDER.

**Comment by bbatsov** [comment]
Happy to see someone is working on this. Btw, splitting cider-interaction and taking care of all compiler warnings is definitely the more important task.

**Comment by cichli** [comment]
@vspinu Roger that. Will `nrepl-client.el` be intended as a generic library for _any_ nREPL implementation or specifically targeted at the Clojure default implementation?

We'll definitely need to move the `pprint-eval` stuff out since that's specific to `cider-nrepl` (my bad for adding it to that file :flushed:), but I think a lot of stuff in there (sessions, interrupts, etc.) is specific to the Clojure implementation and may not make sense for other languages or even other potential users of the client. Thoughts?

**Comment by vspinu** [comment]
> Will nrepl-client.el be intended as a generic library for any nREPL implementation or specifically targeted at the Clojure default implementation?

I have a generic implementation in mind. I have already wrote [R nREPL client and server](https://github.com/vspinu/R-nREPL) bug haven't had time to put anything meaningful on emacs side as yet.

> I think a lot of stuff in there (sessions, interrupts, etc.) is specific to the Clojure implementation and may not make sense for other language

Sessions and interrupts often do make sense for other languages as well. A slight inconvenience right now is that nREPL is not yet standardized. Once the core middleware and the semantics of requests/responses is fully defined, I don't see any problem with having generic nREPL on emacs side. I guess we better ask @cemerick on his thoughts about the standardization of nREPL protocols

**Comment by cemerick** [comment]
By "protocols", I assume you mean the particulars of each operation's request and response messages. Those are [fairly well-documented](https://github.com/clojure/tools.nrepl/blob/master/doc/ops.md)…there's always more that can be done in this area, but there aren't any big holes that I'm aware of. Of course, patches welcome.

Adopting nREPL for interaction with evaluation contexts in other languages is clearly doable, and perhaps worthwhile. The semantics of of e.g. session and eval operations are pretty straightforward in this regard, and hopefully generally-applicable. I'm happy to provide any guidance I can if there are particular questions about intent, etc

**Comment by bbatsov** [comment]
Cleaning up and decoupling `nrepl-client.el` will not be easy. Guess when the R implementation is ready and @vspinu starts coding the Emacs support it will be more clear what makes sense in general and what's Clojure specific. 

Btw, with the addition of the socket repl in 1.7 I'm starting to consider supporting it in CIDER as well (at least to some extent). That's not high on the todo list, however. nREPL will remain our focus for the foreseeable future.

**Comment by EricGebhart** [comment]
@vspinu It is not yet at master. There are still a lot of checkdoc errors.

**Comment by vspinu** [comment]
> By "protocols", I assume you mean the particulars of each operation's request and response messages. 

Yes, very precise particulars up to the data structures returned. I will pop a new thread at `tools.nrepl` once I am back to R-nrepl (pretty soon now) and will spill all my comments over there.

**Comment by bbatsov** [comment]
@vspinu What's the status here?
