### ISSUE TITLE
Run checkdoc automatically for PRs

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1072]
We should invoke `checkdoc` on PRs to avoid the need for tickets like #1071.

Setting this up in travis should not be too complex.

**Comment by EricGebhart** [comment]
Do you really want to just turn it on?  If cider-interaction.el is any indication there are going to be a lot of errors everywhere. There were 50 in cider-interaction, I cleaned up dozens of them and ended up with 46.  I suppose it will at least make everyone look and not introduce new errors.

**Comment by bbatsov** [comment]
Obviously we'll have to fix #1070 first. When the project was starting out there was a time when the entire codebase was checkdoc-compliant. There was also a Travis check for the docstrings. I had to turn it off for a reason I don't recall right now and afterwards I forgot to restore it.

**Comment by bbatsov** [comment]
Reference to the old check - https://github.com/clojure-emacs/cider/pull/262/files

Probably I removed it when I migrated the project to cask.

**Comment by bbatsov** [comment]
Duplicate of #1352.
