### ISSUE TITLE
Go through SLIME contrib and geiser and look for interesting ideas we can borrow

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1073]
Potential sources of inspiration for new CIDER features or optimizations of existing features

* [SLIME contrib](https://github.com/slime/slime/tree/master/contrib)
* [geiser](https://github.com/jaor/geiser)

SLIME's semantic indent is particularly cool. As is geiser's ability to display images in the REPL.

**Comment by johnwalker** [comment]
One of the things I like about geiser is that it displays the value of symbols located at the cursor in the minibuffer.

**Comment by bbatsov** [comment]
A screenshot/animated gif would be helpful, as I'm not sure what exactly do you mean.

**Comment by johnwalker** [comment]
I could be using the wrong words, if I messed up any terminology let me know. Here is a screenshot and example. Define foo to be 3. If you place your cursor on foo, you can see it's value.

![Uploading racket.png…]()

**Comment by johnwalker** [comment]
Another example:

![racket2](https://cloud.githubusercontent.com/assets/1283229/7572754/a17709c0-f7ee-11e4-8e24-6ef34dae7d86.png)

**Comment by johnwalker** [comment]
By the way, if this is something that you think would be useful, I would be happy to work on this feature.

**Comment by bbatsov** [comment]
Yeah, something like this would be neat. I can think of only one problem - symbols in bindings that have the same names as vars. Guess this is a problem in Scheme as well; not sure how we can account for all cases when something should be treated a local.

**Comment by johnwalker** [comment]
Do you mean for situations like:

```
(def foo 3)
(let [foo 5] ) 
```

and put the cursor on foo? In geiser, the value 3 is displayed within the let. I am also not sure how to solve this, but I will think about it.

**Comment by bbatsov** [comment]
Yep, this is exactly the problem I had in mind. At the very least we need to have some list of well-known forms with local bindings, so we'd ignore them.

`compliment` does something similar [here](https://github.com/alexander-yakushev/compliment/blob/master/src/compliment/sources/local_bindings.clj).

**Comment by vspinu** [comment]
This feature would be particularly useful in the debugger. It's kinda watch-at-point functionality.  I don't see much use of it at global level though.

**Comment by johnwalker** [comment]
Yeah, it would be really slick in the debugger. Is the debugger able to keep track of local bindings, by any chance?

**Comment by johnwalker** [comment]
I tried out the debugger, so I know a little more about its current state now. Really cool!

**Comment by bbatsov** [comment]
//cc @Malabarba

**Comment by Malabarba** [comment]
## The debugger

Yes, the debugger knows about all local variables. It's also pretty good at knowing which symbols are not variables.

Right now the debugger's only mode of operation is the "step through" mode.
It would be quite simple to implement a mode where it doesn't stop anywhere, but simply gathers a list of all variables inside the given form and then sends it to cider.

## The feature

The following was suggested to me on my blog's comments. I think it works better than displaying in the echo area, but some people might find it too in-your-face.

![](http://i.imgur.com/QmIPZ5U.png)

Once we have a way of asking the nrepl for all local variables, this should be easy to do with.

**Comment by vspinu** [comment]
> The following was suggested to me on my blog's comments.

This will not work that nicely with complex data structures. Might be handy to have either a separate watch window that displays local variables, or popup-menu or electric-buffer on mouse hovering.

**Comment by bbatsov** [comment]
@Malabarba Btw, what will happen in enlighten with some huge local (e.g. map)? Is there some folding in place?

**Comment by Malabarba** [comment]
Oh, I'd forgotten about this issue. I guess enlighten mostly covers the comment I made above. 

The solution I used for complex data structures was to have a pretty short print level/length. There's no way to expand that, and I don't plan to change it. If someone needs to inspect locals more closely they can always debug/break the function (or add a pr in there).
