### ISSUE TITLE
Function selection (C-c M-f) doesn't seem to work correctly

### ISSUE THREAD

**Issue by mbuczko** [clojure-emacs/cider#1078]
steps to reproduce:

- try to change namespace (eg. in repl via C-c M-n)
- select function via C-c M-f (all functions from selected namespace are listed correctly)
- when confirmed an exception is thrown: 'Unable to resolve symbol: xxxxx in this context' and namespace gets swtiched to the initial one (boot.user in my case)

CIDER 0.9.0snapshot (package: 20150419.1202)

**Comment by expez** [comment]
I can't reproduce this.  

Is it reproduceable across repl restart?  Across projects?  Does it only happen when you use `boot` or with `lein` too?

**Comment by bbatsov** [comment]
I was thinking we should probably delete this functionality. Because of this command we keep around a lot of legacy inlined Clojure code.

**Comment by expez** [comment]
yes, it isn't very useful either.  All it does is provide a completing read of available functions.  company-mode kind of does that once you start typing anyway...

**Comment by bbatsov** [comment]
OK, let's kill it. Could you do this?
