### ISSUE TITLE
Code instrumented for debugging has compile errors

### ISSUE THREAD

**Issue by MatthewDarling** [clojure-emacs/cider#1089]
We have some code that keeps track of its running time for reporting purposes, like this:

```clojure
(defn test-fn
  []
  (let [start-time (System/currentTimeMillis)]
    (Thread/sleep 1000) ;;;do some work
    (- (System/currentTimeMillis) start-time)))
```

It compiles without error using ```C-x C-e```, but when instrumented using ```C-u C-M-x```, I get a compilation error. Specifically, it says: ```"Unable to find static field: currentTimeMillis in class java.lang.System"```.

-----

### System info

Operating system: OS X 10.9

CIDER version info: ```CIDER 0.9.0snapshot (package: 20150427.2358) (Java 1.8.0_05, Clojure 1.6.0, nREPL 0.2.7)```

  * The CIDER snapshot was installed by Leiningen this morning, CIDER in Emacs was the latest in MELPA

Emacs version info: ```GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org```

-----

### [Full stacktrace](http://pastebin.com/YcnE1rkt)

**Comment by cichli** [comment]
cc @Malabarba

**Comment by Malabarba** [comment]
Thanks for reporting. I'm looking into it.
