### ISSUE TITLE
*print-meta* in CIDER macroexpansions

### ISSUE THREAD

**Issue by tsdh** [clojure-emacs/cider#1090]
Although I have `(set! *print-meta* true)` at the REPL, when I do <kbd>C-c RET</kbd> on some macro form, the resulting `*cider-macroexpansion*`'s contents are not printed with their metadata.

This breaks debugging macroexpansion for me.  I have macros that expand to code containing other macro calls, and I pass essential data from the outer macros to the inner macros using metadata.  The expansion works correct in clojure, but I can't do it stepwise for debugging purposes in CIDER because the metadata isn't printed in the `*cider-macroexpansion*` buffer, and so expanding a macro in the expansion won't work.

Here is a minimal example that demonstrates the issue:

```clojure
(in-ns 'user)

(defmacro defun-1 [name args & code]
  (when-not (:foo (meta name))
    (throw (RuntimeException. "No metadata")))
  `(defn ~name ~args ~@code))

(defmacro defun [name args & code]
  `(defun-1 ~(with-meta name {:foo true}) ~args ~@code))

(defun plus-1 [x]
  (inc x))

(plus-1 7)
```

Compiling the buffer prints 8, so the macroexpansion in Clojure works just fine.  However, when you expand the `(defun plus-1...)` with CIDER, you cannot expand the resulting `(defun-1 plus-1...)` form anymore because the `:foo` metadata which `defun` attaches to the symbol `plus-1` is gone (not printed).

So I'd be very happy with some customization option for enabling printing of metadata with CIDER macroexpansion.  Alternatively, it could also just honor the `*print-meta*` value in the REPL.

**Comment by cichli** [comment]
Using the value set in the REPL definitely makes sense. For now, does using `alter-var-root` instead of `set!` work around the problem?

```clojure
(alter-var-root #'*print-meta* (constantly true))
```

**Comment by tsdh** [comment]
No, sadly not.

**Comment by cichli** [comment]
Thanks for testing - I'll sort this out this evening.

**Comment by cichli** [comment]
@tsdh I've added the `cider-macroexpansion-print-metadata` option; setting that to true will cause the metadata to be printed. You might need a `lein -U deps` to grab the latest `cider-nrepl` if your lein has already checked today.

**Comment by tsdh** [comment]
@cichli Thanks, works perfectly!
