### ISSUE TITLE
*cider-result* continuously prompts *"Buffer has no associated file and not saved. Save it?"*

### ISSUE THREAD

**Issue by BrunoBonacci** [clojure-emacs/cider#1091]
Hi,
I do use a lot the `C-c C-p` (eval in pop-up buffer), however when I leave emacs It prompts the following message:
*"Buffer has no associated file and not saved. Save it?"*

This appear also when trying to run Magit status, which obviously is quite annoying.
The content of the **_\*cider-result\*_** buffer can typically be discarded, Is there any way to tell Emacs to do not attempt to save this buffer? 

Bruno

**Comment by bbatsov** [comment]
> however when I leave emacs It prompts the following message:

By leave you mean quit, right?

**Comment by BrunoBonacci** [comment]
Yes sorry, I mean 'quit' emacs.

**Comment by BrunoBonacci** [comment]
Hi,

to fix this isn't, just necessary to change the mode of the `\*cider-result\*`?

https://github.com/clojure-emacs/cider/blob/master/cider-interaction.el#L1708

```el
(defun cider--pprint-eval-form (form)
  "Pretty print FORM in popup buffer."
  (let* ((result-buffer (cider-popup-buffer cider-result-buffer nil 'special-mode))
         (handler (cider-popup-eval-out-handler result-buffer))
         (right-margin (max fill-column
                            (1- (window-width (get-buffer-window result-buffer))))))
    (cider-interactive-pprint-eval form handler right-margin)))
```

thanks
Bruno

**Comment by expez** [comment]
@BrunoBonacci How are you quitting emacs?  The most common manner is to call `save-buffers-kill-emacs` or `save-buffers-kill-terminal`.  The latter delegates to the former which saves all buffers associated with a file, if it has been modified.  The \*cider-result\* buffer isn't associated with a file so I can't figure out why emacs is prompting you to take action.

>to fix this isn't, just necessary to change the mode of the \*cider-result\*?

This wouldn't affect whether or not the buffer is saved or not and we would lose any syntax highlighting, indentation support etc. in that buffer.

**Comment by BrunoBonacci** [comment]
Hi guys,

I'm not really bothered about this while quitting / leaving emacs.
I quit emacs maybe once a month, so forget about quitting emacs, it was my mistake to even mention it. 

**The very very annoying part is `magit-status` which requires the buffers to be saved. I do run magit maybe 50 times per day and each time is asking me if I want to save the `*cider-result*` buffer, which is useless.**

This is so annoying that I can accept to lose the syntax-highlighting to get it fixed.

I'm new to emacs, and my understanding is that a buffer which contains discardable stuff must have a mode which is derived from `special-mode`. So I guess that to keep the syntax-highlight the solution would be to create a new mode which is derived from `special-mode` and contains the syntax highlighting. But really even without syntax-highlight is a massive improvement for me.

thx

**Comment by expez** [comment]
I can't reproduce this behavior at all.  Both magit and emacs checks if the buffer is already associated with some file before prompting for a save and the `\*cider-result\*` buffer isn't associated with a file by default.

Can you reproduce this problem if you start emacs from `emacs -q` don't load any of your own customizations?

**Comment by BrunoBonacci** [comment]
Sorry you are right, it is a problem of my customizations.
I use **emacs-live** and it seems that it was introduced between `v1.0-BETA-24` and `v1.0-BETA25` in which they bumped the cider version, so I thought it was coming from some change in cider, but is not.

Apologies guys, my bad.
