### ISSUE TITLE
Evaluate in multiple REPLs.

### ISSUE THREAD

**Issue by kostafey** [clojure-emacs/cider#1094]
Since I can pass exact session to `nrepl-sync-request:eval`, it's still usless when
`nrepl-current-connection-buffer` simply gets first available connection-buffer:
```lisp
(car (nrepl-connection-buffers))
```

Am I right? Can I change it and push updates?

**Comment by bbatsov** [comment]
Having each REPL have a buffer-local connection is in the roadmap. It's also related to a future migration to `comint-mode`. @vspinu started some work in this direction, but it seems this work was stalled.

**Comment by vspinu** [comment]
This part (connection management) is an important piece of a bigger puzzle The issue is tightly linked to other milestones like isolating nrepl from CIDER and replanting cider-repl on comint. Thus it should be addressed as a whole. I am still swamped till 25th of May. But then I have a break which I plan to use almost exclusively for this initiative.

You can have a look at #700 to have an idea of what has been already discussed about connection management.

**Comment by kostafey** [comment]
It seems, that it's a long story to solve the problem in general :). But since I want to call `nrepl-sync-request:eval` directly (and provide session manually), can I simply pass session from request in `nrepl-send-request` to `nrepl-current-connection-buffer` function and handle it there? Would it be usefull in future development? Can I help with something else?

**Comment by vspinu** [comment]
I don't quite understand what you mean. 

Do you want to be able to set the current connection before calling `nrepl-sync-reques:eval`?

There is no UI or even a function to set the current connection but you can write it yourself taking `cider-rotate-connection` as a starting point. 

> Would it be usefull in future development?

In the future there will definitely be a way to associate current context (project, directory, buffer) with the connection. We just don't know the exact incantation of the idea as yet. The current concept of "current connection" is flawed. So further developing on top of "current connection" doesn't make much sense IMW.

**Comment by bbatsov** [comment]
> There is no UI or even a function to set the current connection but you can write it yourself taking cider-rotate-connection as a starting point.

That's not true. We've had `nrepl-connection-browser` for ages.

**Comment by bbatsov** [comment]
> In the future there will definitely be a way to associate current context (project, directory, buffer) with the connection. We just don't know the exact incantation of the idea as yet. The current concept of "current connection" is flawed. So further developing on top of "current connection" doesn't make much sense IMW.

The concept is not without it's merits - for instance how would you associate two connections with the same project otherwise? For me the biggest problems is that connections are not associated with REPL buffers. Associating source files with connections might be tricky to get right, but I don't think that's terribly important.

**Comment by vspinu** [comment]
>     In the future there will definitely be a way to associate current context
>     (project, directory, buffer) with the connection. We just don't know the
>     exact incantation of the idea as yet. The current concept of "current
>     connection" is flawed. So further developing on top of "current connection"
>     doesn't make much sense IMW.

> The concept is not without it's merits - for instance how would you
> associate two connections with the same project otherwise?

At some level there is always a current connection. I was referring to
the the current notion of the global "connection list". It must be
refined with local "current in a context" connection.

If you have a a well defined association rules between contexts and
connection you can quickly re-associate a context with another
connection. No need to rotate your connection list each time you switch
buffers and projects.


> For me the biggest problems is that connections are not associated
> with REPL buffers. 

What do you mean? Currently each connection is associated with a REPL
buffer.

**Comment by vspinu** [comment]
> We've had nrepl-connection-browser for ages.

Oops, I forgot about that. There is indeed `nrepl-make-connection-default` that you can in principle use in a program.

**Comment by bbatsov** [comment]
> What do you mean? Currently each connection is associated with a REPL
> buffer.

It used to be that each REPL buffer was using the current connection (which made the repl buffer names kind of confusing). I remember you did some changes there, not sure if this was changed or not. I rarely use more than one connection, so I keep forgetting about things like this.

**Comment by kostafey** [comment]
> I don't quite understand what you mean.
Do you want to be able to set the current connection before calling nrepl-sync-reques:eval?

I'll try to explain on the example (it's not the exact code, but the idea):

```clojure
(defun get-my-proj-session ()
  (save-excursion
    (progn
      (set-buffer (format nrepl-repl-buffer-name-template
                          (concat " " "my-project")))
      nrepl-session)))

(nrepl-sync-request:eval
 "(print \"Hellow manual session management\")"
 "my-proj.core"
 (get-my-proj-session))
```
So, I want to specify the exact session manually for my `nrepl-sync-request:eval` calls.

**Comment by vspinu** [comment]
> So, I want to specify the exact session (and thereby the exact REPL) manually for my nrepl-sync-request:eval calls.

I see. That's a bit tricky given that requests operate on current connection. So your pseudo code will send wrong session ids to current connection if current connection is not what you want.

Why do you need to operate with nrepl-sessions in the first place? Those are internal things and are likely to change in the future. We have discussed this a bit  in the past The current split into `nrepl-session` and `nrepl-tooling-session` is somewhat arbitrary nor it's very useful. `nrepl-tooliing-session` is used only in a couple of places.  In fact, the `session` argument is not even exposed in cider api (`cider-client.el`).  

The best that you can do right now is to let-bind `nrepl-connection-list` in your custom `nrepl-sync-request-eval` to `(list "con-buffer-name")`. Binding `nrepl-connection-buffer` to "con-buffer-name" will probably also work.  Then simply call `nrepl-sync-request:eval` and don't bother with `session` argument at all.

**Comment by vspinu** [comment]
> It used to be that each REPL buffer was using the current connection (which made the repl buffer names kind of confusing). I remember you did some changes there, 

Yes. I have changed precisely that. Now connection buffer and repl buffer is the same thing.

**Comment by bbatsov** [comment]
> The current split into nrepl-session and nrepl-tooling-session is somewhat arbitrary nor it's very useful. nrepl-tooliing-session is used only in a couple of places.

It's not exactly arbitrary - the tooling session is used for everything that's not eval. This served two purposes - not interfering with the eval results and not blocking the eval session. When everything (doc lookup, source lookup, etc) was relying on evaluating embedded Clojure code the tooling session was used a lot, now the middleware has rendered it redundant. Although people looking to add simple extensions might still opt to use it...

> Yes. I have changed precisely that. Now connection buffer and repl buffer is the same thing.

Yeah, I remember now.

**Comment by kostafey** [comment]
> The best that you can do right now is to let-bind nrepl-connection-list in your custom nrepl-sync-request-eval to (list "con-buffer-name").

@vspinu, thank you very much! Feel free to close the issue.
