### ISSUE TITLE
Some way to abort a test run

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1095]
I just ran a test with a buggy implementation containing an infinite loop.  It would be nice if there was some way to abort the current test run so I didn't have to restart cider.

**Comment by bbatsov** [comment]
Something like this would be nice to have, although I'm not sure how can we implement it - we'd probably need some interrupt op, but I don't know what exactly should it do. No idea if we can kill a specific Java method.

**Comment by expez** [comment]
Perhaps we can run the tests in a `future` and use `future-cancel` to abort.

**Comment by bbatsov** [comment]
You may research the viability of this approach. A related feature is https://github.com/clojure-emacs/cider/issues/696

Seeing the progress on the tests will make it apparent where we ran into an infinite loop.

**Comment by Malabarba** [comment]
What op does cider use to run the tests?
Is it the `eval` op? (or something that falls back on it?)

The eval op is already interruptible, so would just be a matter of writing a cider.el command to call that.

**Comment by bbatsov** [comment]
@Malabarba See https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/test.clj

**Comment by bbatsov** [comment]
//cc @jeffvalk

**Comment by Malabarba** [comment]
Ok, from what I can tell it doesn't use "eval".

If it helps, one way to interrupt a running eval session is to call `(.stop (:thread (meta (:session *msg*))))`. This is what the debugger does, and (I think) I borrowed this from `interruptible-eval` itself. For the `test` op it would probably be as simple as calling `.stop` on the running thread, so you'd just have to keep track of running test threads on some global variable.

Not sure if that's the simplest solution, though.

**Comment by Malabarba** [comment]
@expez Just to be sure... Calling `cider-interrupt` doesn't abort the running tests?

**Comment by expez** [comment]
@Malabarba I've no idea if `cider-interrupt` is able to kill a running test.  I thought this was only for interrupting eval request?

**Comment by Malabarba** [comment]
@expez I think so too. I was just wondering if you had tried it. :-)
In any case, if this gets implemented, I think it should be part of `cider-interrupt`.

**Comment by jcromartie** [comment]
Bumping this. I run into it frequently, especially with test.check `defspec` tests.

**Comment by Malabarba** [comment]
Looking at the code, I see that the test middleware reimplements some of the functionality from interruptible-eval. I think it might be better if the middleware just delegated the evaluation to the "eval" op. 
That should make the code a tad bit shorter, and we would get interruptions tests as a bonus.
