### ISSUE TITLE
Consider ztree-like UI for the ns browser

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1096]
Our humble ns browser might be more pleasant to work with if we used an UI like the one in ztree-dir https://github.com/fourier/ztree

**Comment by vspinu** [comment]
Would be also nice if the whole tree could be quickly refined a la Helm or ivy interface.

**Comment by bbatsov** [comment]
Yeah, having some filtering would be nice. @expez already mentioned this in #766. We already have `cider-apropos`, so this is definitely not high on the todo list.

**Comment by bbatsov** [comment]
Closing this as non-important and unlikely to happen soon.
