### ISSUE TITLE
Unable to complete from namespace alias with piggieback active

### ISSUE THREAD

**Issue by 4xrsJCr9** [clojure-emacs/cider#1097]
After evaluating `(require '[clojure.string :as s])` in the repl, cider is unable to complete after `s/`. It can however complete correctly after `clojure.string/`. This behaviour only occurs when piggieback is active.

CIDER 0.9.0snapshot (package: 20150507.1302) (Java 1.8.0_45, Clojure 1.7.0-beta2, nREPL 0.2.10)
piggieback 0.2.1
clojurescript 0-0.3269
Emacs 24.5.1

I am not sure if this is a cider/piggieback issue. I reported this issue to the piggieback project (https://github.com/cemerick/piggieback/issues/63);  it would seem that it is unlikely that it has anything to do with piggieback.

**Comment by bbatsov** [comment]
This is likely https://github.com/gtrak/cljs-tooling/pull/19. Completion is now broken for newer ClojureScript releases. Hopefully @gtrak & @cichli will fix this soon.

**Comment by 4xrsJCr9** [comment]
Thanks for the quick response. I'll close this issue for now and track the progress of https://github.com/gtrak/cljs-tooling/pull/19.
