### ISSUE TITLE
Show locals table at each step in debugger

### ISSUE THREAD

**Issue by AdamClements** [clojure-emacs/cider#1106]
Rather than simply showing the last form return value, use the contents of &env to display a table of all the local bindings at a given point, as discussed with @Malabarba in gitter.

```clojure
(defmacro locals [] (zipmap (map #(list 'quote %) (keys &env)) (keys &env)))
```

This will likely include some autogenerated locals (for destructuring, macros, etc.). These aren't likely to be too distracting, but a simple heuristic of whether a name consists of an underscore `#[_]` should filter out all of these (maybe have a toggle?)

```clojure
(defn remove-autogenerated-locals
  "Remove any locals generated by macros (heuristic - named something
  with underscores in it). When we're doing something other than
  println with the data, these could be left in but it's a bit noisy
  at the moment"
  [coll]
  (into {} (remove (fn [[k v]] (re-find  #"[_]" (name k))) coll)))
```

**Comment by Malabarba** [comment]
If anyone wants to try this the clojure side is trivial. The `breakpoint` macro already holds the list of local variables in `*locals*`. So it's just a matter of sending the contents of that variable when we send the message to Emacs.

The Emacs side is then just a matter of displaying that information somewhere.

**Comment by Malabarba** [comment]
Related: https://github.com/clojure-emacs/cider/issues/1073#issuecomment-101546552
