### ISSUE TITLE
Allow stepping back in debugger in case of overshoot

### ISSUE THREAD

**Issue by AdamClements** [clojure-emacs/cider#1107]
Store a list of states in the debugger, and in the case that you press (n) a few too many times when stepping through irrelevant states and miss the state you actually wanted to examine, allow the user a step back button which simply displays the previous states again.

In this mode, the only available actions would be to step back again, or to step forward (eval, inject etc. would be disabled until the user reaches the end state again and is back to the same state as the underlying process)

(as discussed with @Malabarba in gitter)

**Comment by bbatsov** [comment]
@Malabarba any plans to work on this in the near future?

**Comment by Malabarba** [comment]
Nope, sorry. :(
The debugger already prints everything to the `*Messages*` buffer. So whenever I overshoot I just look there.

**Comment by bbatsov** [comment]
Maybe we should just close this then, as I doubt anyone else would work on this in the foreseeable future. We should do a cleanup of the issue tracker...
