### ISSUE TITLE
CIDER nREPL "connection successful" message is not meaningful

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/cider#1113]
When I `kbd M-x cider-connect RET [host] RET [port]`, even if there isn't actually an nREPL instance on that host and port I get a "connection successful" message followed by a "nREPL server died" message which together doesn't make it obvious that there was simply never a good connection in the first place.

Just a UX note, the command works fine.

**Comment by bbatsov** [comment]
Yep, we should fix this.

**Comment by bbatsov** [comment]
Btw, when trying to connect to the port of some other service I get:

```
nREPL: Establishing direct connection to localhost:5432 ...
nREPL: Direct connection established
nREPL: Connection closed (connection broken by remote peer
)
nrepl-send-sync-request: Sync nREPL request timed out (op clone id 1)
```

While still problematic, I was wondering what did you do exactly when you ran into the problem you reported.

**Comment by bbatsov** [comment]
I guess we can close this.

**Comment by arrdem** [comment]
`¯\(°_o)/¯` sure
