### ISSUE TITLE
Feature request: host nREPL discovery

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/cider#1114]
Please add a portscanner to find all nREPL instances on a host. That'd be pretty neat.

**Comment by expez** [comment]
This should probably be a middleware in nrepl itself.  Other clients would be interested in this information too I imagine.

Thoughts, @cemerick?

**Comment by bbatsov** [comment]
@expez Your suggestion sounds pretty strange to me. Why would one nREPL server be aware of other servers? That doesn't make any sense.

@arrdem We already do some grepping through the output of `ps` to offer port auto-completion. Maybe it makes sense to add some simple UI that lists all the nREPL servers on a host. Doing a portscanner seems like an overkill, but I'd accept a PR if anyone provides one. :-)

**Comment by expez** [comment]
> Why would one nREPL server be aware of other servers? 

The feature request was for discovery of instances on the same host.  Is it so weird to able to query an nREPL server for a list of its siblings?

**Comment by bbatsov** [comment]
Yep. :-)

**Comment by expez** [comment]
Well, if we don't put it in some central place then every client will have to write their own code to offer port completion.  If we're really grepping the output of `ps` then our solution also has the disadvantage of not working on windows.

**Comment by bbatsov** [comment]
I'm not saying this can't be done better. I'm saying it's pretty uncommon for standalone services to keep track of each other. The current implementation is [here](https://github.com/clojure-emacs/cider/blob/master/cider.el#L265). Windows support is something that I don't really care for - I'm always welcoming patches, but I don't work actively to improve it.

**Comment by cemerick** [comment]
Using `jps` would be an easy first step towards making the current impl simpler and probably cross-platform. Beyond that, JMX would be to way to go; [nREPL could register a JMX bean that advertises all open nREPL ports for a given process](http://dev.clojure.org/jira/browse/NREPL-44), which would be easily accessible to a Clojure script cider could ship, etc.
