### ISSUE TITLE
latest version 20150604.1532 provides no repl

### ISSUE THREAD

**Issue by rogerallen** [clojure-emacs/cider#1117]
The melpa-stable install of cider has issues, so I'm trying to get the latest, greatest melpa working.  But, it doesn't work for me.

I'm on Mac OS 10.9.5, Emacs 24.5.1 and just installed cider 20150604.1532  from melpa.

I have [cider/cider-nrepl  "0.9.0-SNAPSHOT" :exclusions [org.clojure/clojure]] in my .lein/profiles.clj

Creating a "lein new test123", navigating to test123/src/test123/core.clj and M-x cider-jack-in says that it worked "there is no limit to what you can do with this REPL", but no new window opens up with a repl.  M-x list-buffers does not show any repl buffer.  The server buffer says:

nREPL server started on port 63597 on host 127.0.0.1 - nrepl://127.0.0.1:63597

I have no uncommented commands in my .emacs that mention "cider".

Help!

**Comment by bbatsov** [comment]
Do you see anything cider-related in the `*Messages*` buffer? You can also post here the contents of your `*nrepl-messages*` buffer.

**Comment by bbatsov** [comment]
You can find more info on how to debug this here https://github.com/clojure-emacs/cider/blob/master/README.md#troubleshooting

**Comment by rogerallen** [comment]
*Messages* doesn't have any errors--things look as if they should be working.    

```
Starting nREPL server via lein repl :headless...
You can run the command `cider-jack-in' with C-c M-j
Starting nREPL server via lein repl :headless...
nREPL server started on 53682
nREPL: Establishing direct connection to localhost:53682 ...
nREPL: Direct connection established
```

There is no *nrepl-messages* buffer.  There is a *nrepl-server test123* that has this

```
nREPL server started on port 53682 on host 127.0.0.1 - nrepl://127.0.0.1:53682
```

I did check that cider-version is "0.9.0-snapshot" and that matches cider-nrepl

**Comment by rogerallen** [comment]
Must have been some cruft in my .emacs.d directory.  (I didn't delete older versions)  Creating a new .emacs.d folder and reinstalling all my packages, I now get a nrepl.  Whew.

I'm still left with a confusing situation, though.  Bringing up the nrepl says:

```
; CIDER 0.9.0snapshot (package: 20150607.503) (Java 1.8.0_45, Clojure 1.6.0, nREPL 0.2.6)
WARNING: CIDER requires nREPL 0.2.7 (or newer) to work properly
```

I saw that it downloaded nREPL 0.2.10, so I don't know why it isn't finding it by default:

But, I guess that's a lein issue, not a CIDER issue...here's what it looked like when I did this at the terminal after updating .lein/profiles.clj to use nrepl 0.9.0-snapshot.

```
test123> lein repl
Retrieving cider/cider-nrepl/0.9.0-SNAPSHOT/cider-nrepl-0.9.0-20150604.175935-42.pom from clojars
Retrieving org/clojure/tools.nrepl/0.2.10/tools.nrepl-0.2.10.pom from central
Retrieving cider/cider-nrepl/0.9.0-SNAPSHOT/cider-nrepl-0.9.0-20150604.175935-42.jar from clojars
Retrieving org/clojure/tools.nrepl/0.2.10/tools.nrepl-0.2.10.jar from central
nREPL server started on port 63594 on host 127.0.0.1 - nrepl://127.0.0.1:63594
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
```

I'll see if I can just blow away the older nREPL...

**Comment by bbatsov** [comment]
See https://github.com/clojure-emacs/cider/issues/961

**Comment by rogerallen** [comment]
Thanks for the pointer & support.  I'm back in business.
