### ISSUE TITLE
Support for reader conditionals (CLJC)

### ISSUE THREAD

**Issue by danskarda** [clojure-emacs/cider#1120]
Hi,
I would like to ask what is recent status of support for Clojure 1.7 reader conditionals?

Result of my recent tests:
- CLJ - does not work out-of the box and I have not found a way how to do it 
- CLJS - does work OOTB both in REPL and files

As I understand it, for Clojure it an option to reader (which is different to data-readers). 

- Who has the responsibility and opportunity to turn it on and off? cider or nrepl?
- Where the configuration should be stored? project.clj? 

I glanced on tools.nrepl sources. It uses read-string, but there is no way how to  change settings.

For CIDER i think it should be ON by default, both in files and repl. From my experience, I have many files open clj, cljs and cljx (and in future cljc). If every file has different policy of handling #?, than it is confusing for the user (status is not in user's locus of attention). I do not mind occasionally leaving #? in clj/cljs files, as it will be found by next time running require.

For tools.nrepl, I do not think it should be on by default, but it should provide a way how to specify reader options.

/cc @cemerick

**Comment by cemerick** [comment]
I've been using reader conditionals in .cljc files for a few weeks now with good results. What have you found to not work?

It's true that expressions entered via the REPL do not allow reader conditionals at the moment. That only just landed in `1.7.0-beta2`; for some time, the idea was that conditionals wouldn't be available at the REPL at all. Anyway, I'll be changing nREPL to match the Clojure REPL's behaviour in the near future.

What configuration/toggling are you expecting? AFAIK, there is no configuration facility for reader conditionals in Clojure itself. There are the corresponding options to `read`, but that's for use by programs reading data explicitly, not a hook for changing how expressions coming through a REPL or via file-loading should be read.

**Comment by danskarda** [comment]
Hi Chas,
thank you for fast reply. My configuration:

- Clojure 1.7.0-RC1
- ClojureScript 0.0.3308
- tools.nrepl 0.2.10

Reader conditionals DOES work when I require a namespace from .cljc file. It does NOT work when I edit cljc file and do eval (cider-eval-last-expression). It does not work in repl either.

How do you expect to edit CLJC files without support for interactive eval? If it is not enabled, you have to strip reader conditionals, debug and do your repl stuff. Finally insert reader conditionals when you finish. Does not sound very user friendly.

As I understand it, cider sends a string to tools.nrepl. nREPL parses the string using read-string, evals and send back the reply. As nREPL uses read-string without options, there is no way how read-string can use reader conditionals. On the other hand, piggieback depends on ClojureScript, which  turns reader conditionals on by default.

Without support for reader conditionals, it is cumbersome to edit cljc files. I proposed a configuration option for tools.nrepl, because I am not convinced it should be on by default for all users of tools.repl. 

What I am expecting something like

```
  :tools.nrepl.reader/options    {:read-cond :allow}
```

in my project.clj. If you decide, that reader conditionals should be on for all nREPL users, then there is no need for such option.

**Comment by cemerick** [comment]
`cider-eval-last-expression` *should* work once nREPL is updated. That won't be an option, it'll be have as per Clojure and ClojureScript out of the box. All that's needed is the equivalent of https://github.com/clojure/clojure/commit/e251e14e2459663dbc1492aca025c7171a2e4ff0 anywhere nREPL uses `read` or its derivatives.

**Comment by cemerick** [comment]
Here's an issue for you to track: http://dev.clojure.org/jira/browse/NREPL-78

**Comment by danskarda** [comment]
Chas, once again, thank you for fast response. I was not following Clojure patches, so I missed that it is enabled by default in Clojure REPL. 

I guess I can close this issue on cider now.

**Comment by cemerick** [comment]
No worries, it was (somewhat) recent news to me when it landed, too. :-)

**Comment by ptaoussanis** [comment]
Hi all, quick question if I may?:

Do I understand correctly then that as of today Cider doesn't support evaluating reader conditional expressions?

Issue http://dev.clojure.org/jira/browse/NREPL-78 is what's holding up support? Given the lack of activity on the issue, I feel like I must be missing something? Perhaps there's some workaround that everyone's using in the meantime?

Or are folks just not evaluating individual reader conditional expressions?

For context: I'm coming from .cljx where I'm used to routinely evaluating individual conditional expressions through Emacs+Cider.

Thanks a lot, cheers! :-)

**Comment by expez** [comment]
@ptaoussanis Your understanding of the current situation is accurate.

> Or are folks just not evaluating individual reader conditional expressions?

I've been working at the function level.  That is, evaluating my functions. containing reader conditionals, and then testing the implementation in the two repls.

I also sometimes--very rarely--act at the expressions level, e.g. manually picking out the clj branch of a reader conditional.  The funny thing is that, since I do this so rarely, it never really occurred to me to try to eval the entire reader conditional, but that would indeed be more efficient.

Perhaps you can submit a patch to NREPL?  The fix seems so easy that I'm guessing the only reason this hasn't been fixed yet is lack of time.

**Comment by Naomarik** [comment]
@ptaoussanis Did you find an efficient way to evaluate the correct forms between two repls?
