### ISSUE TITLE
0.9.0-SNAPSHOT stops outputing prn statements to cider-repl

### ISSUE THREAD

**Issue by dagda1** [clojure-emacs/cider#1124]
My projects.clj looks like this;
```
{:user {
        :dependencies [[com.cemerick/piggieback "0.1.6-SNAPSHOT"]]
        :plugins [
                  [cider/cider-nrepl "0.9.0-SNAPSHOT"]]}
```

I find that after a short period of time, my ```prn``` statements stop getting logged to the cider-repl and I have to kill the process and restart via ```cider-jack-in```.

I am compiling the buffer via ```C-c C-k``` and clearing the buffer with ```C-c M-o```.

Am I missing middelware or is there a way of stopping this?

**Comment by bbatsov** [comment]
We need exact steps to reproduce this.

**Comment by bbatsov** [comment]
@dagda1 ping :-)

**Comment by dagda1** [comment]
hi,

I'm on holiday and writing this on my iPhone.  so I was able to fix the original problem by updating my emacs neroli problem but now I have a new and similar problem.

clearing the console stops working after I run the entire buffer by hitting C-c C-k.  it clears fine the first 2 times and then never works again.

**Comment by expez** [comment]
@dagda1 If the original problem is fixed, could you close this and open a new issue for your new problem?  Also, please do include the steps required to reproduce the problem :)
