### ISSUE TITLE
M-.  always prompts for symbol name

### ISSUE THREAD

**Issue by maruks** [clojure-emacs/cider#1130]
M-.  always prompts for symbol name
C-u M-.     works as expected, jumps to symbol's definition

(cider-version)
"CIDER 0.9.0snapshot (package: 20150612.315)"

**Comment by expez** [comment]
This was changed a few months back, but it's working as intended.  If you never want to see the prompt, and just jump to whatever is below point, you can set `cider-prompt-for-symbol` to `nil`.
