### ISSUE TITLE
Cider thinks refactor-nrepl middleware is missing

### ISSUE THREAD

**Issue by tdavis** [clojure-emacs/cider#1140]
Apologies if this turns out to be the wrong project to list this on...

I'm trying to get Cider to work with refactor-nrepl. I added both to my ``~/.lein/profiles.clj``:

```clojure
 :user
 {:plugins [[cider/cider-nrepl "0.9.0"] [refactor-nrepl "1.0.5"]] ...
```
Unfortunately, Cider still says "Please, install (or update) refactor-nrepl and restart CIDER." when connecting to a repl. Within the repl itself I can ``require`` everything from refactor-nrepl, so it certainly seems to be installed to me. I am using ``CIDER 0.9.0 (package: 20150617.753) (Java 1.8.0_45-internal, Clojure 1.7.0-RC1, nREPL 0.2.10)``

**Comment by expez** [comment]
Could you please try do delete `clojure-mode`, `CIDER` and `clj-refactor` from the `elpa` directory below your `.emacs.d` and just re-installing?

**Comment by tdavis** [comment]
Just tried it, still get the same warning :disappointed:

**Comment by expez** [comment]
What's the output of `M-x cljr-version`?

**Comment by tdavis** [comment]
The version is either "cljr--assert-middleware: nrepl-refactor middleware not available! Did you remember to install it?" or "cljr--assert-middleware: CIDER isn't connected!" depending on Cider state. 
```
(defvar cljr-version "1.0.5"
  "The current version of clojure-refactor")
```

**Comment by expez** [comment]
The repl you have going is a regular clojure repl and not cljs, right?

**Comment by tdavis** [comment]
Yep, just a normal repl. 

```
(defn start-nrepl
  "Start a network repl for debugging when the :repl-port is set in the environment."
  []
  (when-let [port (env :repl-port)]
    (try
      (reset! nrepl-server (nrepl/start-server :port port :handler cider-nrepl-handler))
      (timbre/info "nREPL server started on port" port)
      (catch Throwable t
        (timbre/error "failed to start nREPL" t)))))
```

**Comment by expez** [comment]
`:handler cider-nrepl-handler` what about the handler for cljr?  CIDER knows nothing about cljr ops so all those messages intended for that middleware are now unhandled.

**Comment by tdavis** [comment]
Good point! How can I have both of them?

**Comment by expez** [comment]
@seancorfield posted this on gitter yesterday:

```clj
(apply nrepl/default-handler (concat (map resolve cider/cider-middleware) [#'refactor/wrap-refactor]))
```

I think he was dealing with a similar problem.

**Comment by seancorfield** [comment]
@expez Pointed out that you probably don't want the refactor middleware active when connecting to an nREPL server in a production app so an easy way to disable the warning would be nice (since it's a very annoying warning). For now, I've gone with adding the `wrap-refactor` middleware as noted above but it's ugly and not really needed for my use case.

**Comment by expez** [comment]
The warning can be disabled by putting `(setq cljr-suppress-middleware-warnings t)` in your emacs config.

Or, if you prefer to let emacs' customize facility manage your variables the value can be changed by browsing to the settings for clj-refactor: `M-x customize-group <RET> cljr <RET>`

**Comment by bbatsov** [comment]
Can we close this?

**Comment by johanatan** [comment]
I'm experiencing this. Here's my profiles.clj:
```
{:repl {:dependencies [[org.clojure/tools.nrepl "0.2.11"]]}
 :user {:plugins [[cider/cider-nrepl "0.11.0"] [refactor-nrepl "2.2.0"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.11"]]}}
```

And I just re-installed: cider, clj-refactor and clojure-mode via elpa.
