### ISSUE TITLE
cider-debug

### ISSUE THREAD

**Issue by mishadoff** [clojure-emacs/cider#1141]
> To stop debugging your expression just re-evaluate it.

It's a bit confusing and i think worth to mention in docs for cider-debug section.
Consider the amount of people asking about this http://endlessparentheses.com/cider-debug-a-visual-interactive-debugger-for-clojure.html

**Comment by bbatsov** [comment]
Guess so. Our assumption was people would be familiar with edebug (Emacs's debugger), which behaves the same way. Clearly we were mistaken. :-)
