### ISSUE TITLE
Cider incorrectly detects nrepl version as 0.2.6

### ISSUE THREAD

**Issue by csdrane** [clojure-emacs/cider#1146]
I am running the latest version of CIDER and cider-nrepl. Both are 0.9.1-snapshot. 

Jacking in, I am told:

```
; CIDER 0.9.1snapshot (package: 20150618.2308) (Java 1.8.0_45, Clojure 1.6.0, nREPL 0.2.6)
WARNING: CIDER requires nREPL 0.2.7 (or newer) to work properly
```

True to its word, symbol lookup is not working. 

I tried deleting all instances of cider-nrepl in ~/.m2. That didn't work. I also tried deleting and reinstalling cider and clojure-mode, which also didn't work. What might I be doing incorrectly?

**Comment by arrdem** [comment]
Are you running figwheel or other tooling? Figwheel actually pins nREPL at 2.6 as reported earlier today in the clojurians slack which could cause this.

**Comment by csdrane** [comment]
Nope, cider-nrepl is the only plugin I'm running in lein.

**Comment by bbatsov** [comment]
> True to its word, symbol lookup is not working.

That's new. :-) Might be unrelated.

See https://github.com/clojure-emacs/cider#warning-saying-you-have-to-use-nrepl-027
