### ISSUE TITLE
[0.9.0]cider debugger:   Failed to instrument

### ISSUE THREAD

**Issue by weejulius** [clojure-emacs/cider#1148]
![image](https://cloud.githubusercontent.com/assets/81416/8266634/af50e556-176b-11e5-8e61-f1223905c765.png)

**Comment by Malabarba** [comment]
Sorry, that was an oversight on my part. The debugger doesn't do function literals yet (it supports anonymous functions but not function literals).
I should have made cider not ask for a bug report in this situation.

Also, feel free to ignore that message in your usage. The code inside `#(...)` will not be instrumented, but everything else should work.
