### ISSUE TITLE
Cursor jumps to the command output in the REPL

### ISSUE THREAD

**Issue by kolov** [clojure-emacs/cider#1154]
In the REPL, after some commands that print a few lines of output (like a bigger map), the cursor jumps back to somewhere in the middle of the output. M-> brings the cursor at the end, where it should be. Hitting ENTER causes it to jump back to somewhere in the middle of the previous result. I can execute a command, like (+ 1 2) - the result is printed, cursor jumps back in the previous output. After the output has scrolled out of the screen (or cleared with C-c M-o) everything is behaving normal again.

**Comment by bbatsov** [comment]
I'll add here a link to your original [SO question](http://stackoverflow.com/questions/30956029/why-is-my-cursor-jumping-in-emacs-nrepl).

**Comment by bbatsov** [comment]
I was never able to reproduce this. Does someone have reliable repro steps for the problem?

**Comment by expez** [comment]
Closing this as a likely bad interaction with another package.  Without reproduction steps and no other confirmed sightings of this problem there's nothing we can do.

**Comment by scottdw** [comment]
I have experienced odd cursor repositions when typing in a clojure-mode buffer but too rarely and randomly to pin it down to a specific mode or cause. I'll try pay more attention next time it happens.
