### ISSUE TITLE
Trouble update to cider 0.9.0

### ISSUE THREAD

**Issue by m00nlight** [clojure-emacs/cider#1157]
During the process to update to cider 0.9.0, I update to nrepl 2.1.0 as the instruction suggest, also enable nrepl-log. But when I use `cider-jack-in` in emacs, it shows that it connect to the urepl server, but there is no prompt for the repl, and although I enable `nrepl-log-message`, I still miss the `*nrepl-message*` buffer. 

The following is the output of `*Message*`

```
You can run the command `cider-jack-in' with C-c M-j
Starting nREPL server via lein repl :headless...
nREPL server started on 50157
nREPL: Establishing direct connection to localhost:50157 ...
nREPL: Direct connection established
Connected.  Your imagination is the only limit to what you can do with this REPL!
```

And here is my configuration of cider in emacs

```elisp
(add-hook 'cider-mode-hook #'eldoc-mode)
(setq nrepl-log-message t)
(setq cider-repl-tab-command #'indent-for-tab-command)
```

I am using Emacs 24.5.1 on OSX.

**Comment by bbatsov** [comment]
Delete `cider` and `clojure-mode` from your elpa folder and reinstall them.

It's `nrepl-log-messages`, not `nrepl-log-message`.

**Comment by m00nlight** [comment]
It works after reinstall, thanks :+1:
