### ISSUE TITLE
Coordinated cider / cider nrepl SNAPSHOTS

### ISSUE THREAD

**Issue by lgrapenthin** [clojure-emacs/cider#1161]
The problem I am facing is that I occasionally need to upgrade to a commit of cider that is not in a release. Then I don't wish to upgrade to a newer commit, because it breaks something or is wip. Still, I have to use the SNAPSHOT release of cider nrepl which always upgrades automatically, which could break a working cider again.

It would be great if unreleased cider-nrepl could have unstable version numbers additionally to snapshots so that won't be happening.

**Comment by bbatsov** [comment]
I'm a bit confused by the description of your problem. `cider-nrepl` and `cider`'s master branch (from which the MELPA packages are built) are always in sync. The newest snapshot from clojars is downloaded automatically once a day and you can always for `lein` (or whatever) to download the latest snapshot at any time. 

> It would be great if unreleased cider-nrepl could have unstable version numbers additionally to snapshots so that won't be happening.

We'll basically have to bump this version on every commit, which is an overkill IMO.

**Comment by lgrapenthin** [comment]
It would additionally improve the quality of ciders version control, because currently one can't check out an older cider commit and expect it to work reliably in the same way it worked for its authors. Changes to the cider-nrepl SNAPSHOT it depends on may have broken it without anyone noticing. 

I doesn't seem like there is a single reference on which exact commit in cider-nrepl a commit in cider depends on. Of course there might be a history of all SNAPSHOT releases and with timestamps one might be able to conjure such a reference but as an overall process this seems a bit medieval :) - Or am I missing something?

(I assumed automating bumping and version tagging of successful builds wouldn't be too difficult.)

**Comment by bbatsov** [comment]
I understand your concerns, but the cases when you'd like to rollback to a previous commit should be really rare - critical regressions. Those are usually fixed right away.

And there's also the problem with MELPA - as it's building releases automatically, using tags for "unstable" versions will generate MELPA releases all the time (unless we opt to use some version scheme it can't parse). Overall, doing extra work for something that's already marked as "for adventurous people only" seems like a waste of time to me. I can be convinced otherwise, but this is definitely not something I'm eager to work on.

**Comment by lgrapenthin** [comment]
I was rather thinking about versions for the nrepl middleware than for cider itself. Cider snapshots would simply depend on a concrete version which wouldn't be messing with MELPA, would it?

**Comment by bbatsov** [comment]
Yeah, that'd be much easier to do.

**Comment by bbatsov** [comment]
Going forward I plan to cut alpha/beta releases for `cider-nrepl`, instead of relying on SNAPSHOTs, and having CIDER's master depend on them, so that should solve the problem. I should have done this much much earlier. Lessons learned. :D
