### ISSUE TITLE
current-connection-info should display its current namespace, too

### ISSUE THREAD

**Issue by myguidingstar** [clojure-emacs/cider#1163]
i'm talking about this
https://github.com/clojure-emacs/cider/blob/3d67c24f7e12eab33d433d9f9c6ac0119778cdd6/test/cider-tests.el#L165
very helpful when switching between two cider connections (C-c M-r) to the same project, where one is Clojure, the other is Clojurescript. Currently it's impossible to reason which is which

**Comment by bbatsov** [comment]
The current ns is not an attribute of the connection. One can argue it's an attribute of the REPL that's doubling as a connection buffer, but usually its ns should be considered irrelevant. 

@cichli @Malabarba @expez @benedekfazekas @vspinu Any thoughts on this?

**Comment by benedekfazekas** [comment]
well based on the description i guess clj/cljs should displayed rather

**Comment by Malabarba** [comment]
Yes, I agree connections should be distinguishable, but showing the namespace would be rather tangential way of going about that. I think it'd be best to show something like `cljs`, or some other short string derived from how the connection is initiated (like `lein` vs `boot`).

**Comment by bbatsov** [comment]
I'll take a PR adding the connection type to the info (`clj` or `cljs`). Not sure if there's much use of showing what tools was used to boot the nREPL server (although showing the entire boot command might be useful).

**Comment by kleewho** [comment]
Isn't this already solved by https://github.com/clojure-emacs/cider/commit/8d79f8f0b28193d08d99a85e59a97dbc0b309282 ?

**Comment by Malabarba** [comment]
I think so. Forgot to tag the issue on the commit message.

**Comment by bbatsov** [comment]
I didn't close this, because the current situation is a bit odd. The type is showed only for sibling connections. Shouldn't we just show it for each connection?

**Comment by kleewho** [comment]
I can try to make patch for it if that's what you want. For the record it's not enough to just modify the `cider--connection-info` ;)
