### ISSUE TITLE
[FR] Append, don't preppend to history files

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/cider#1167]
This is both a performance and usability improvement. At present it's very difficult as a user to go back through a saved history file and pull out a REPL session for sharing as an example or otherwise. Storing history in first input first order should help with this. This should also make writing history files faster, improving the experience of maintaining a persistent history of all REPLs.

**Comment by bbatsov** [comment]
Another ticket related to comint https://github.com/clojure-emacs/cider/issues/709 //cc @vspinu

**Comment by bbatsov** [comment]
After a discussion with @arrdem I'm closing this in favour of #709.
