### ISSUE TITLE
[FR] After evaluation hook

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/cider#1168]
It'd be _really cool_ if there was a hook for actions to be run after a repl evaluation request has been completed. An example use case would be sending a sauron notification when a long running eval completes.

**Comment by bbatsov** [comment]
> An example use case would be sending a sauron notification when a long running eval completes.

How'd you know the eval was long running without a before-eval hook? :-)

**Comment by arrdem** [comment]
Turns out advice works pretty well :P
