### ISSUE TITLE
cider-eval to kill-ring and pre-sexp comment.

### ISSUE THREAD

**Issue by phillord** [clojure-emacs/cider#1169]
As a feature request, it would be lovely to have the ability to push the results of the last eval to the kill-ring.

I write quite a lot of tutorial material where I want to do something with the eval results of Clojure code, and currently I have to insert into buffer, then kill. Even better would be an "eval-last-sexp-and-insert-as-comment-before-the-sexp" (sorry, not a good name). So:

    (+ 2 2)

Would become...

    ;; => 4
   (+ 2 2)

I guess both of these could be layered onto `cider-eval-last-sexp` by extending the prefix argument support.

If you are interested, I can put a PR together.

**Comment by bbatsov** [comment]
Your suggestions sound reasonable. Put something together, so we can discuss some actual code.

**Comment by phillord** [comment]
Will do!

**Comment by bbatsov** [comment]
@phillord Ping :-)

**Comment by phillord** [comment]
Working on new command "M-x create-more-time" first...

Still think this is a good idea and will do it at some point. Not sure
when.

**Comment by bkruczyk** [comment]
There's already a `cider-eval-defun-to-comment`. Wouldn't it be apropriate to create custom variable like `cider-eval-push-to-kill-ring` instead of creating another eval function?

**Comment by bbatsov** [comment]
Yeah, probably this would be the best direction. I don't really want to add more prefix arguments to eval commands. But I think @phillord wanted to different things - a way to push results to the killring and a way to display results as comments.

**Comment by bkruczyk** [comment]
> a way to display results as comments. 

Isn't that what `cider-eval-defun-to-comment` does?

**Comment by bbatsov** [comment]
Just for one type of evaluation (top-level expression evaluation). Which is probably enough. But with the results to kill-ring, you'd probably want for every eval op to push its result to the the kill-ring when this is enabled. On the other hand some people might want to push there only specific results...

**Comment by bkruczyk** [comment]
I think eval to comment makes most sense for top-level expressions i.e. inserting comment "inside" sexp could be problematic/confusing.

For specific results I don't really know how to tackle it, but for every eval maybe it would be sufficent to put the kill-ring behaviour in somewhere in `cider-interactive-eval`.

**Comment by bbatsov** [comment]
Indeed.

**Comment by phillord** [comment]
@bkruczyk Yes, that's is what `cider-eval-defun-to-comment` does -- I added that command:-)

My original issue was more generic, but what we have now fulfils my use case. I am happy to close, unless @bkruczyk needs the more generic solution.

**Comment by bkruczyk** [comment]
Nope, feel free to close the issue.

**Comment by bbatsov** [comment]
@phillord so you don't want the ability to push eval results to the kill right anymore?

**Comment by phillord** [comment]
Well, I wanted this as a way to get results as comments into the buffer. As that's been implemented instead, it seems the better solution. I'll close.

**Comment by jvillste** [comment]
Here is a function that would implement the evaluation to kill ring. I keep it in my init.el for now.
```
(defun juvi-eval-last-sexp-to-kill-ring ()
  (interactive "p")
  (cider-interactive-eval (cider-last-sexp)
                          (nrepl-make-response-handler (current-buffer)
                                                       (lambda (_buffer value)
                                                         (kill-new value))
                                                       (lambda (_buffer out)
                                                         (cider-emit-interactive-eval-output out))
                                                       (lambda (_buffer err)
                                                         (cider-emit-interactive-eval-err-output err))
                                                       '())
                          nil
                          (cider--nrepl-print-request-map fill-column)))
```

**Comment by olymk2** [comment]
this would be a really nice feature, sat here evaluating html would be nice to get the result and format it in another buffer like html mode. perhaps even eval to new buffer for large results you want to format.

**Comment by matthew-piziak** [comment]
Thanks @jvillste! This is quite useful. I like putting an extra `(cider-eval-last-sexp)` as the last time of the defun so that I can see the result that gets copied to the kill ring.
