### ISSUE TITLE
Should cider sexp evaluation include meta hints and reader macros?

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1171]
When you invoke `cider-eval-last-sexp` at the end of the following snippet, only the function is sent for evaluation, not the hint.
```
^{:batman false} (inc 1)
```
However, to the clojure *reader*, that is a single expression. Now, I'm not saying that's a bug, and I realise this is in line with sexp navigation (which should **not** change), but perhaps it would be convenient for cider to send that entire thing for evaluation?

This is a bit more annoying when dealing with reader macros. i.e., `#inst "1970-01-01T00:00:09"` is pretty hard to evaluate.

**Comment by bbatsov** [comment]
Hmm, you're raising a great point. Ideally we should be evaluating them together, but for this to happen we'll need to alter quite a bit of things internally. Right now we're using the standard Emacs sexp-related commands and they obviously don't have any Clojure support. Probably we should implement such commands and stuff them in `clojure-mode`. Other ideas are welcome. As are patches! ;-)

**Comment by bbatsov** [comment]
@Malabarba Now that the new commands are available would you like to integrate them in evaluation?

**Comment by Malabarba** [comment]
I thought I had already. ☺
Will do that.

**Comment by Malabarba** [comment]
Yep, it's in eabfac8b5c2445b73b6dfbd4fa1163afe8b63978
I just forgot to reference this issue.

**Comment by Malabarba** [comment]
Btw, if anyone wants to test this, just do `(set! *print-meta* true)` in the repl, and then run `eval-last-sexp` after something like `^:private [1 2]`.
