### ISSUE TITLE
TAB and RET navigation on *cider-test-report* buffers

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1177]
In ert report buffers you can navigate with TAB and visit the specific test with RET. Would be nice to have something like that on cider as well.

**Comment by Malabarba** [comment]
TAB and RET work automatically if we different entries are buttons. I can provide the function to create the buttons, but I don't know the logic that goes on there. Clearly, though, the information is there somewhere, because we highlight the failing tests in the source buffer.

**Comment by bbatsov** [comment]
Yeah, we can definitely have something like this. If you take a look at `cider-test.el` you'll see that the code is pretty straight-forward. @jeffvalk did an outstanding job there.
