### ISSUE TITLE
cider-debug: eval expression

### ISSUE THREAD

**Issue by mishadoff** [clojure-emacs/cider#1178]
During debug is often needed to [e]valuate arbitrary expression in context.
The problem is, when expression is invalid or have unresolved symbols, whole debug fails.

I understand edebug has similar behaviour, but at the same time evaluators in other IDE like Intellij IDEA prevent incorrect expression to fail debug.
Is there a chance to get this functionality in cider-debug?

**Comment by bbatsov** [comment]
I don't recall edebug's behaviour in such cases, guess I'll have to check it out. At any rate is seems reasonable to be able to continue to debug even if you enter something invalid.  //cc @Malabarba

**Comment by Malabarba** [comment]
Oh, yes, we should do some exception handling in there.

**Comment by Malabarba** [comment]
Alright, I believe I have figured out how to do exception handling. And I can throw the exception to Emacs without aborting the eval. Will push when the other stuff is merged.
