### ISSUE TITLE
Investigate better pretty printing

### ISSUE THREAD

**Issue by AdamClements** [clojure-emacs/cider#1179]
Clojure's plain printing from the REPL becomes hard to read as soon as you get a non-trivial output and the core pprint is slow and not very pretty. 

A better alternative might be https://github.com/brandonbloom/fipp set to an appropriate width for the buffer. It's much faster than pprint (to the extent that you could potentially have it as the default printing method). It gives much better output for deeply nested maps and has a nice extension mechanism which uses hiccup style data definitions rather than side effecting print statements like core pprint. 

https://github.com/greglook/puget extends it further adding alphabetised sorting of map keys and colour highlighting, at the cost of some of the speed.

**Comment by bbatsov** [comment]
Now that we're isolating the runtime deps, doing something like this is definitely an option. I don't think there's much value in colourful presentations, but the other things sound good to me. I'll accept a PR for this, if someone decides to work on it.

**Comment by cichli** [comment]
`cider-nrepl` PR for this on the way shortly - bundling either fipp or puget might be tricky as neither supports Clojure 1.5. [aprint](https://github.com/razum2um/aprint) would also be an option if it didn't have a dependency on JLine :confused:.
