### ISSUE TITLE
No repl with 0.9.1

### ISSUE THREAD

**Issue by schaueho** [clojure-emacs/cider#1181]
I just tried to updating my Cider setup to 0.9.1, including cider-nrepl. Installed the package from melpa, ran `lein deps`, saw the new version being downloaded successfully. However, if I `cider-jack-in` to a fresh repl or `cider-connect` to an existing repl (with the new version), I don't get the REPL in Emacs. I get a connection established message in the mini buffer, \*nrepl-connection\* and \*nrepl-server\* buffers exist, but no usable REPL (i.e. no \*cider-repl <project-name>\* buffer or elsewhere). 

Also, cider-mode is not enabled within the clojure-mode buffer I'm visiting. I can enable it manually, of course, but without a usable repl, this doesn't help me much. 

I'm back to 0.8.2 now, but anybody any idea what's going on?

**Comment by bbatsov** [comment]
Delete `cider` & `clojure-mode` completely and do a clean install. This will fix your problem.

**Comment by schaueho** [comment]
This didn't work for me at first. Turns out clj-refactor 1.0.5 has a dependency on an old cider version. As soon as I deleted it, too, I got the repl back. Thanks!
