### ISSUE TITLE
When loading the `ns` before evaluation, don't print return value.

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1189]
Sometimes (or always?) we evaluate the ns form before running evaluating the actual code with interactive eval operations. The return value of the ns form (`nil`) is then displayed in the minibuffer. 

Usually, this is immediately replaced with the return value of the actual code. However, if the code takes a while to evaluate, the user will be presented with `nil` as if it were the actual return value, which can be very confusing.

**Comment by bbatsov** [comment]
> Sometimes (or always?) we evaluate the ns form before running evaluating the actual code with interactive eval operations. The return value of the ns form (nil) is then displayed in the minibuffer.

Only when it has changed. At any rate we should definitely fix this.
