### ISSUE TITLE
Getting "No reader function for tag dbg" instrumenting function.

### ISSUE THREAD

**Issue by lewang** [clojure-emacs/cider#1190]
This is the output from the cider-repl  buffer:

    ; CIDER 0.10.0-snapshot (Java 1.8.0_05, Clojure 1.7.0, nREPL 0.2.7)
    WARNING: CIDER's version (0.10.0-snapshot) does not match cider-nrepl's version (0.9.1)
    RuntimeException No reader function for tag dbg  clojure.lang.LispReader$CtorReader.readTagged (LispReader.java:1245)
    user>

I'm trying this from a new bare project.

**Comment by bbatsov** [comment]
@lewang Upgrade your middleware. This warning is displayed for a reason. :-)

**Comment by lewang** [comment]
Thanks for the pointer @bbatsov .  I had tried to specify the snapshot version of cider-repl a couple of days ago, must have made a typo  :smirk:
