### ISSUE TITLE
Wrong type argument: stringp, cider-debug-print-level

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/cider#1192]
Hi,

I am on Emacs 25.0.50.1 (build ```53cf3cf```). 
This is my CIDER version: ```; CIDER 0.10.0snapshot (package: 20150710.544) (Java 1.8.0_60-internal, Clojure 1.7.0, nREPL 0.2.10)```

When I issue ```M-x cider-jack-in``` in a .clj file this is what I get in the ```*Messages*``` buffer:

```
nREPL server started on 51494
nREPL: Establishing direct connection to localhost:51494 ...
nREPL: Direct connection established
error in process filter: nrepl-bencode: Wrong type argument: stringp, cider-debug-print-level
error in process filter: Wrong type argument: stringp, cider-debug-print-level
```

**Comment by Kungi** [comment]
I have exactly the same problem here on Emacs 24.4.50.1
Cider Version 20150710.544
I am using `cider-connect`.

**Comment by bbatsov** [comment]
Ops, this is caused by https://github.com/clojure-emacs/cider/commit/3286f0041ace37ce2336615d539132dbb61aa4c4 //cc @Malabarba 

Once again we're bitten by trying to encode nil. If Artur doesn't fix this before me I'll fix this tomorrow.

**Comment by Malabarba** [comment]
Actually, this wans't a nil problem. This was because the list was quoted, so we were passing the symbols. :$

**Comment by manuel-uberti** [comment]
Thank you, it is fixed now.
