### ISSUE TITLE
Expose an option to display interactive eval results results using an overlay

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1196]
Basically it'd be awesome if everyone could use @Malabarba's debug overlay display for regular interactive evaluation. This should be an option, alternative to the current display of results in the minibuffer.

**Comment by Malabarba** [comment]
Would these be permanent overlays? Should they have a timeout? 
Should there be at most ono per buffer or one per line?

**Comment by bbatsov** [comment]
> Would these be permanent overlays?

No.

> Should they have a timeout?

Yes. Configurable timeout, something like 3 seconds as the default. `nil` would make them stay until something else is evaluated in the same buffer.

> Should there be at most ono per buffer or one per line?

One per buffer.
