### ISSUE TITLE
The continue operation sometimes breaks the debugger

### ISSUE THREAD

**Issue by abo-abo** [clojure-emacs/cider#1203]
For example, instrument this:

```elisp
(defn square [x]
  (* x x))
```

Then evaluate this and press <kbd>c</kbd>:

    (nrepl-sync-request:eval "(map square '(3 4 5))")

After this, `square` and other functions will always behave as if they're not instrumented.

Note that it would not break for `(square 42)`, maybe because it's a single call instead of 3 as above.

**Comment by Malabarba** [comment]
That's odd. It's probably just another instance of the bindings map not reseting, but I have no idea why those two situations would be different.

Anyway, this will get fixed this week when I refactor that logic to not depend on the eval message.
