### ISSUE TITLE
cpu usage sometimes goes to 100% with zero size clojure files

### ISSUE THREAD

**Issue by conroe64** [clojure-emacs/cider#1204]
I'm not sure exactly how to trigger this, but it happens quite often. As long as my project contains a zero-length .clj file somewhere inside of it, eventually the cpu will go to 100%.

I examined what was going on with strace, and it appears that one of the processes is trying to read the zero sized clojure file and getting stuck on it:

1370  open("/tmp/language8/src/com/rareventure/ivyr5/changes.clj", O_RDONLY) = 35
1370  fstat(35, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
1370  read(35, "", 8192)                = 0
1370  read(35, "", 8192)                = 0
1370  read(35, "", 8192)                = 0
.... (repeating forever) 

changes.clj is not referenced from any clojure file currently loaded in the system.

Before this occurs, the 1370 process seems to be stat'ing every file in the project and then reading all the clj files.

If you would like the full strace, let me know. It's around 70 meg in size, though.

Here is some environment information:
; CIDER 0.10.0snapshot (package: 20150709.28) (Java 1.8.0_45, Clojure 1.7.0-alpha6, nREPL 0.2.7)
Linux silverhat 3.18.1-gentoo #1 SMP Fri Jan 9 11:49:37 JST 2015 x86_64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz GenuineIntel GNU/Linux

**Comment by Malabarba** [comment]
> If you would like the full strace, let me know. It's around 70 meg in size, though.

Could you provide just the tail of the backtrace (the beginning)? It should help figure out the source.

Also, do you use clj-refactor?

**Comment by conroe64** [comment]
I accidentally deleted the stack trace, and for some reason I can't get this to occur again. Sorry about that.

No, I don't use clj-refactor
