### ISSUE TITLE
Result overlay too prominent

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1222]
I just saw the result overlay for the first time: 

![](http://i.imgur.com/fK53KoG.png)

My first impulse was: "God damnit, something just altered my file! Rude!"

As you can see in the screenshot the result of the evaluation in the overlay looks exactly like it would if I had written those characters in manually, is there some way we could make this a bit more visually distinctive?  

I think it would be really cool to change the prefix to be `;; =>` and then use the comment face for the result.

PS. After getting over my initial reaction I thought this was really cool!

**Comment by Malabarba** [comment]
>  the overlay looks exactly like it would if I had written those characters in manually,

Yes, this is something I've been wanting to fix as well. Applying a comment face to it would be very easy (and that's how it worked initially), but then the result loses all font locking which is a loss in terms of readability.

The alternative is to only apply a background color to the overlay. That would make it more distinct from code without overriding the font-lock. The only problem with that is that it's a little troublesome to do in elisp, and I haven't gotten around to it yet.

**Comment by bbatsov** [comment]
> Yes, this is something I've been wanting to fix as well. Applying a comment face to it would be very easy (and that's how it worked initially), but then the result loses all font locking which is a loss in terms of readability.

This can simply be a config.

**Comment by Malabarba** [comment]
> This can simply be a config.

Yes. 
I'd still like to figure out something to get both benefits at once. If I haven't done that by release time, remind me and I'll finish this. :)

**Comment by expez** [comment]
The result overlay is really cool as it is when debugging.  There's more value in syntax highlighting in this situation too.  But I'd still like a slightly more subtle overlay for situations like the one in OP where you're just evaluating a form in a file.

**Comment by blueberry** [comment]
Maybe give that text a different background?

**Comment by Malabarba** [comment]
Yes, that's an option. The only problem is that there's no easy way in Emacs to apply a background to a text without overwriting the foreground too (which would make us lose font-locking).

So either someone goes through the trouble of doing this the hard way, or we'll have to lose font-locking on the results overlay.

**Comment by bbatsov** [comment]
I wouldn't go overboard with this - the results didn't have font-locking for years and frankly speaking most of them look fine without it. Let's just have some config for this, which defaults to some "overlay-result-face" or something like this. We can revisit the background + font-locking idea down the road. I've just learned that fancy solution have the tendency to backfire...

**Comment by bbatsov** [comment]
And they're usually a huge time-sink.
