### ISSUE TITLE
Extract nrepl-client into a separate package

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1225]
Other projects would like to use it, but right now it's kind of coupled with CIDER itself. Extracting it won't be hard, but it will definitely require some efforts.

@vspinu volunteered to do this originally, but he's pretty busy right now. If someone would like to tackle it, that'd be great. I might do this myself in the end, but this won't within the next 2-3 months as I'm crazy busy myself right now.

**Comment by dgutov** [comment]
Would extracting more than that be too hard? I'd be interested in being able to reuse `cider-repl`, for one thing. And the send-to-process feature, as well as the error handling/backtrace display.

**Comment by Malabarba** [comment]
@dgutov cider-repl depends on a lot of stuff (`client`, `interaction`, `doc`, `eldoc`, and `util`), so that might be trickier. 
But even if the more superficial dependencies were removed (like doc, eldoc and util), `cider-interaction` already represents more than half of cider's code base (yes, really :|), so you might as well just depend on the whole cider package.

**Comment by dgutov** [comment]
> you might as well just depend on the whole cider package

Sure, but the relevant parts would need to be able to work without Clojure, at least.

**Comment by Malabarba** [comment]
> Sure, but the relevant parts would need to be able to work without Clojure, at least.

Without `clojure-mode`?
You'd lose font-locking. But other than that, yes, it could work without clojure-mode.

**Comment by dgutov** [comment]
With a different language. I'm sure that requirement will stretch beyond the lack of dependency on clojure-mode.

**Comment by vspinu** [comment]
> Would extracting more than that be too hard?

My original intend was to extract nrepl-client and REPL (nrepl-repl.el), but I am pretty sure the interactive part that concerns evaluating defuns, regions etc is pretty straightforward  to generalize as well.

**Comment by bbatsov** [comment]
Let's not get ahead of ourselves. After extracting the client code we can see if anything else is worth extracting.

**Comment by phillord** [comment]
Interesting. It seems that there are actually two requirements: there is a generic requirement for a nrepl client, and then there is a requirement for a client that can be used to interact with Clojure. For a potential use with JDEE, if this is the way it goes, we'd actually need the latter (as we want to interact with a running JVM, and Clojure is as a good a choice as any).

@vspinu obviously won't need to evaluate Clojure at all. I guess I need to look at the code base a bit closer. Perhaps for the JDEE use we just need cider.

**Comment by bbatsov** [comment]
I don't know how far we'll go with this. Right now my plan is strip `nrepl-client` just to something which can establish nREPL connections, send requests and get responses. I'll likely move the entire connection management inside CIDER, as it's wrong for a client library to maintain a list of active connections and to be able to manipulate connections. The connection management is clearly a function of whatever package is using `nrepl-client` internally.

**Comment by phillord** [comment]
I've been making some initial experiments with this and, at the moment, for JDEE I would want to use a reasonable amount of CIDER anyway (so, thinks like "fetch the classpath" which are strictly about the JVM rather than clojure per se). I expect for my use case, if we go this route, we are likely just to end up with CIDER as a dependency anyway.

In terms of a more logical split, I guess, we'd end up with a "nrepl-client" package, and "nrepl-jvm" package, and then "jdee-nrepl" and "cider" proper. From where we stands, it feels like a good idea if we would have started off that way, but probably not worth the effort of moving. 

And even if we did, I think, a substantial number of JDEE users would still install cider as it provides the cute minor mode for REPL interaction (i.e. live rather than as a client).

**Comment by vspinu** [comment]
> The connection management is clearly a function of whatever package is using nrepl-client internally.

If possible, there should be one connection manager across all apps. No need for burden the user to learn different interfaces. Actions on connections are pretty generic and it would be rather convenient to see all connections in one place.

**Comment by bbatsov** [comment]
Recently I've decided that this extraction is unlikely to ever happen as no one seems really interested in it. I'll likely rename `nrepl-client.el` to `cider-nrepl.el` (don't want to pretend `nrepl-client.el` isn't coupled to cider anymore) and will consider this issue solved. If someone wants to work on extracting a standalone package - this will be still be a possibility, but it's definitely not on my agenda.

**Comment by Malabarba** [comment]
:+1:

**Comment by phillord** [comment]
I think this is probably accepting the reality of the situation.

A perhaps lighter-weight solution that would enable other people to use the mechanism to support other modes would be to document the parts of cider-nrepl.el which are stable and which could be considered to be an external API.

I added to this issue originally thinking about JDEE, but I have my own (small) package which hooks into cider, and keeping up with the API changes has been quite hard work. As I am sure you can guess, the prospect of having nrepl-client.el change it's name doesn't fill me with joy.

**Comment by bbatsov** [comment]
> A perhaps lighter-weight solution that would enable other people to use the mechanism to support other modes would be to document the parts of cider-nrepl.el which are stable and which could be considered to be an external API.

Maybe. I haven't thought much about this, I just posted my comment while going through the issue backlog.

> I added to this issue originally thinking about JDEE, but I have my own (small) package which hooks into cider, and keeping up with the API changes has been quite hard work. As I am sure you can guess, the prospect of having nrepl-client.el change it's name doesn't fill me with joy.

That probably won't happen very soon, as I've got my plate full with all sorts of other things right now. Eventually some change will happen, as the current situation is definitely pretty far from ideal... What and when will happen - that's another matter altogether. Whatever I end up doing, I'll try to make it as painless as possible for everyone.

**Comment by phillord** [comment]
That would be excellent!  In the ideal world, I would try and change the name over a release cycle where, otherwise, the API is untouched. That would make the port a big search-and-replace job. The last update I made involved both semantics and name changes which is what made life hard.

**Comment by Malabarba** [comment]
There's always define-obsolete-alias :)

**Comment by bbatsov** [comment]
Closing this as non-important and unlikely to happen soon.
