### ISSUE TITLE
Add a flag to show reloading info only in case of problems

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1239]
One user complained on gitter that he finds the window useless most of the time. One idea would be to add a flag to show it only when there are some issues. I'm open to other suggestions. At any rate - the default will continue to be the current behaviour.

**Comment by cichli** [comment]
If there are issues, the error buffer will popup with the stacktrace anyway. I think an option to not show the buffer (it will still be logged to), and instead display the most important messages (reloading started/successful/failed, calling/called before/after fns) in the echo area will do the trick.

**Comment by bbatsov** [comment]
Sounds good to me.
