### ISSUE TITLE
Reset the REPL buffer to blank

### ISSUE THREAD

**Issue by piotr-yuxuan** [clojure-emacs/cider#1240]
Hi maintainer, thanks for your work :-)

I've given a look at the list of issue and methinks the issue pointed by this [stackoverflow thread](http://stackoverflow.com/questions/28371102/how-to-clear-the-repl-in-cider-mode) has neither been reported not solved.

I feel Cider should have a key bindings for this.

**Comment by expez** [comment]
`C-c M-o` in the repl buffer is bound to `cider-repl-clear-buffer`

**Comment by piotr-yuxuan** [comment]
Yep you got it ~ it's about get a repl fresh again to get rid of old loaded stuff. For example, it means:
```
core > (def a 1)
core > a
=> 1
:reloading () ;; by your C-c C-x
core > a
1 ;; but I would like to get an error like "unknown a"
```

**Comment by bbatsov** [comment]
Got it. Perhaps a simple way to do this would be to simply create a clean nREPL session. Not sure if there are other simpler/more elegant alternatives. //cc @cemerick

**Comment by cemerick** [comment]
nREPL sessions only affect dynamic var bindings. What @piotr-yuxuan seems to be looking for is a complete environment reset. There are many tools that work in this space as described in the SO thread, e.g. tools.namespace, or SS' component library.

**Comment by cichli** [comment]
`tools.namespace` will only reload namespaces that are associated with files - did you create the `core` namespace at the REPL?

**Comment by expez** [comment]
One possible solution would be to use `ns-interns` to get a list of interned vars and then use `ns-unmap` to remove them.  Depending on what's wanted here, this could be combined with `tools.namespace/refresh` to get rid of any extra required namespaces, beyond those specified in the file on disk, as well.

I'm not sure how useful this would be in general, but this would be a great feature to work on for someone new to CIDER.

**Comment by piotr-yuxuan** [comment]
I'm new on the REPL but currently away from the keyboard. I'm OK to try to
work on this in next week! :-)

**Comment by Malabarba** [comment]
Hi @piotr-yuxuan. Did you give this a try?

**Comment by bbatsov** [comment]
Guess not. So what's the plan for this? Will we cook some middleware or just close the issue. It seems like a useful feature to me.

**Comment by Malabarba** [comment]
Doesn't refresh already deal with this? It unloads everything, and it's not going to reload anything that was defined in the repl since its not in a file.

**Comment by bbatsov** [comment]
I'm not sure what happens for namespaces that are not backed by files.

**Comment by bbatsov** [comment]
Nobody seems to be interested in this, so I'll just close it.

**Comment by hicksca** [comment]
While this is closed and not super importing in an overall ... I do think for new Clojure users who have used other repls (like ipython or pry) they do have a similar features that comes in handy when training or playing around in the repl. In ipython `%reset` and pry uses `reset`.

@Malabarba gave me a solution that solves that solved my issue which was switch to another namespace using `(ns bar)` and coming back `(ns foo)`. This works but could be cleared up by adding this as a built in option to mirror most other repls from other communities. (Speaking as a beginner this would have helped me.)  

Any thoughts not stated above as to why this would be a bad idea?

ps thanks @Malabarba for the assistance
