### ISSUE TITLE
Debugging overlay does not always display on the right line

### ISSUE THREAD

**Issue by vermiculus** [clojure-emacs/cider#1242]
Emacs 24.5 // Mac OS X

```clojure
; CIDER 0.10.0snapshot (package: 20150805.418) (Java 1.7.0_51, Clojure 1.6.0, nREPL 0.2.10)
(+ 1 2)
;;; place point below this line and C-x C-e
```
----
```clojure
; CIDER 0.10.0snapshot (package: 20150805.418) (Java 1.7.0_51, Clojure 1.6.0, nREPL 0.2.10)
(+ 1 2)
;;; place point below this line and C-x C-e => 3
![C-x C-e]
```

**Comment by bbatsov** [comment]
That's not a bug - it's a feature. By design the overlay is supposed to appear after the expression which was evaluated.

**Comment by Malabarba** [comment]
I'm a little confused, what's that `![C-x C-e]` on the last line?

**Comment by vermiculus** [comment]
Sorry, I didn't know a good way to present the information. `!` is the location of point when I press `C-x C-e`. And @bbatsov, I really doubt the comment is being eval'd to `3` :wink: 

In the hopes that this will make things clearer, here's what it *should* be, intuitively (to me):

```clojure
; CIDER 0.10.0snapshot (package: 20150805.418) (Java 1.7.0_51, Clojure 1.6.0, nREPL 0.2.10)
(+ 1 2)
;;; place point below this line and C-x C-e
```
```clojure
; CIDER 0.10.0snapshot (package: 20150805.418) (Java 1.7.0_51, Clojure 1.6.0, nREPL 0.2.10)
(+ 1 2)
;;; place point below this line and C-x C-e
! (point is placed here)
```
```clojure
; CIDER 0.10.0snapshot (package: 20150805.418) (Java 1.7.0_51, Clojure 1.6.0, nREPL 0.2.10)
(+ 1 2) => 3
;;; place point below this line and C-x C-e
![C-x C-e] (C-x C-e is fired off)
```
```clojure
; CIDER 0.10.0snapshot (package: 20150805.418) (Java 1.7.0_51, Clojure 1.6.0, nREPL 0.2.10)
(+ 1 2) => 3 (overlay appears after eval'd expression)
;;; place point below this line and C-x C-e
![C-x C-e]
```

**Comment by bbatsov** [comment]
This has nothing to do with the overlays - it's just how Emacs's sexp-navigation commands work. They ignore comments, so I'd say although a bit strange this is the correct behaviour.

**Comment by bbatsov** [comment]
Ops, spoke too soon. Yeah, that's a bug - the overlay actually appears on the comment line.

**Comment by bbatsov** [comment]
![image](https://cloud.githubusercontent.com/assets/103882/9138034/402cf130-3d2a-11e5-99de-5111ee065415.png)

**Comment by vermiculus** [comment]
Yes, sorry I couldn't give a screenshot :) I tried to replicate the situation with just text.
