### ISSUE TITLE
cider refresh and run tests

### ISSUE THREAD

**Issue by rhacker** [clojure-emacs/cider#1256]
I'm new to Elisp, what I'm trying to do is to write a simple function to refresh and run tests. This is what I've tried so far but it doesn't seem to work.
```
(defun clojure-run-tests () 
   (interactive)
   (cider-refresh)
   (cider-test-run-tests))

*** Eval error ***  Wrong type argument: number-or-marker-p, nil 
```

It'd be great if someone can help me with this. Thanks

**Comment by expez** [comment]
`cider-test-run-tests` takes a required argument, which you omitted.

This might help you in the future: http://endlessparentheses.com/debugging-emacs-lisp-part-1-earn-your-independence.html

**Comment by rhacker** [comment]
@expez thanks for pointing the useful documentation. I have looked it up and find the source code `cider-refresh` and `cider-test-run-tests`, but it doesn't ring me any idea how to set this up. 
I can see in the default binding key written in this lib, the key is defined like this : 
```
(define-key map (kbd "C-c ,") #'cider-test-run-tests)
```

They get the parameters magically some how. I tried another way, but it doesn't work either: 

```
(global-set-key (kbd "C-c ,") (lambda () (interactive) #'cider-refresh #'cider-test-run-tests))

```

**Comment by Malabarba** [comment]
@rhacker During interactive calls, Emacs uses the specification inside the `(interactive ...)` form to decide what the arguments are. In the case of `cider-test-run-tests` that is `"P"`, which specifies the prefix argument.
The prefix argument usually just `nil` (unless the user hit a prefix key first, but that's besides the point here).

So the right way to call `cider-test-run-tests` is by doing `(cider-test-run-tests nil)`.

**Comment by Malabarba** [comment]
Also, if you ever just want to "magically" use a function's interactive parameters, you can call it via `(call-interactively #'the-function-to-call)` instead.

This is not something to be done in production elisp code, but it's fine for you to use when you're just putting together a function for your own use.

**Comment by rhacker** [comment]
@Malabarba thanks for your information. It does really help me a lot since I'm new to elisp development. I will try it tomorrow since it's pretty late already ( 2 am ) :dancer:

**Comment by Malabarba** [comment]
@rhacker No problem, and welcome to elisp. ;-)

**Comment by bbatsov** [comment]
Generally it's preferable to ask questions on gitter/slack & the mailing list.
