### ISSUE TITLE
Displaying interactive eval result hides result overlay immediately

### ISSUE THREAD

**Issue by sp3ctum** [clojure-emacs/cider#1257]
Hi, I was very pleased with how the new overlays work. I recently picked up the [lispy](https://github.com/abo-abo/lispy/) package that has bindings for lisp navigation and evaluation. I'm experimenting with adding support for showing overlays in lispy, but I keep running into a wall and thought I'd ask for help.

Lispy has a binding for `lispy-eval`, which sends a sync request to the nrepl server. The result is calculated correctly, but I don't know how to invoke showing an overlay.

I tried this code:
```lisp
(cider--display-interactive-eval-result "test" (point))
```

The result is that the overlay is shown, but then hidden/removed right after. I notice this function is called, I presume from `post-command-hook`:

```lisp
;;; Displaying eval result
(defun cider--remove-result-overlay ()
  "Remove result overlay from current buffer.
This function also removes itself from `post-command-hook'."
  (remove-hook 'post-command-hook #'cider--remove-result-overlay 'local)
  (remove-overlays nil nil 'cider-type 'result))
```

Can you come up with something to work around this?

**Comment by Malabarba** [comment]
Indeed, the default behavior of  the results overlay  relies on the fact that it's called from the process filter (so it is outside the command loop). This ensures that the overlay gets destroyed after the next command. 

Synchronously, this fails because the overlay is created inside the command loop that started the evaluation. 
 I'm considering this a bug. I'll think of the best way to fix it. 

 For now, you can work around it by configuring a variable. I forgot its name now, but it lets you specify a timeout in seconds instead of stopping the overlay after the next command.

**Comment by sp3ctum** [comment]
Yes, I managed to work around it, thanks.

A thing to note: if the overlay sticks around for a pretty long time, such as 5 seconds, it's possible to type behind it. When doing this, the typed text will appear normally, but the cursor position seems to stay before the overlay.

I'm not sure how to resolve this. I used a 1 second overlay to mitigate the possibility of that bug for now. I'm worried this might affect non-lispy users of cider, too.

**Comment by bbatsov** [comment]
I'll close this, as generally we prefer to have similar discussions on either gitter, slack or the mailing list.

**Comment by Malabarba** [comment]
Still, the fact that the overlay is incompatible with synchronous evaluation is a proper bug, I think.

**Comment by bbatsov** [comment]
> Still, the fact that the overlay is incompatible with synchronous evaluation is a proper bug, I think.

Agreed. But let's have a separate ticket for this.

**Comment by Malabarba** [comment]
@sp3ctum If you have a moment, please check if #1275 fixes your original problem.

**Comment by sp3ctum** [comment]
I tested it, now it works. Thanks so much, guys!
