### ISSUE TITLE
Is clojurescript supported for debugging?

### ISSUE THREAD

**Issue by sp3ctum** [clojure-emacs/cider#1259]
I tried out the debugger, it is pretty awesome. Nice work!
But what about clojurescript?

Cider doesn't seem to be entering the debugger for clojurescript. I have a figwheel running, whose repl I connect to with cider, if that makes a difference.

**Comment by sp3ctum** [comment]
I see an error appear when I do `C-u C-M-x` on a defun:
`nREPL: No response handler with id nil found`

**Comment by bbatsov** [comment]
No, it's not supported. It was  on the roadmap for 0.10, but it turned out
to be more complex than initially expected.

**Comment by Malabarba** [comment]
Like @bbatsov said.
Now it's on the road map for "whenever my thesis is done and I have time in my hands again".

**Comment by sp3ctum** [comment]
I see, thanks for clarifying. Take all the time you need.
