### ISSUE TITLE
C-c C-z broken on clj+cljs project

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1262]
Working on cljs support for refactor-nrepl I get 

```
Could not determine relevant nREPL connection, using: CLJS refactor-nrepl@localhost:51483 (Java 1.8.0_31, Clojure 1.7.0, nREPL 0.2.10)
```

when I hit <kbd>C-c C-z</kbd> after doing `cider-jack-in-clojurescript`.

I have like two cljs files in the project, for testing purposes, so this guess was unfortunate.

**Comment by bbatsov** [comment]
Hmm, I guess the relevant REPL check is not factoring in the type of the REPL in question.

**Comment by Malabarba** [comment]
@expez What file were you using at the moment? Was it a `clj` or a `cljc`?

**Comment by expez** [comment]
`clj`

**Comment by bbatsov** [comment]
Is this still relevant?
