### ISSUE TITLE
Middleware based functionality not working after cider-jack-in-clojurescript

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1263]
Working on adding cljs for refactor-nrepl I did `cider-jack-in-clojurescript` on the refactor-nrepl project.  This project is really a clj project, but there will be some cljs files in the project moving forward, for testing purposes.

None of the middleware based functionality is working for me now.  I can't access docs, I can't jump to vars and there's no completion candidates available.

```clj
:dev {:plugins [[jonase/eastwood "0.2.0"]]
      :dependencies [[org.clojure/clojure "1.7.0"]
                     [org.clojure/clojurescript "1.7.28"]
                     [com.cemerick/piggieback "0.2.1"]
                     [commons-io/commons-io "2.4"]]
      :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}
```

**Comment by bbatsov** [comment]
I'm guessing this is some dispatch issue similar to #1262, but this has to be verified.

**Comment by bbatsov** [comment]
Btw, is this still an issue?
