### ISSUE TITLE
cider-find-ns doesn't work after cider-jack-in-clojurescript

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1265]
Only 3 namespaces were available `cljs.core`, `cljs.repl` and `cljs.user`.  None of these were relevant to my query issued from a clojure file.

**Comment by Malabarba** [comment]
Is that after https://github.com/clojure-emacs/cider/commit/f0256324fe74bf2dda04feec5b8a4ef3515726df ?

**Comment by expez** [comment]
No, I'll try this again after upgrading.
