### ISSUE TITLE
C-c M-p doesn't work with dual repls

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1266]
`Could not determine relevant nREPL connection, using: CLJS refactor-nrepl@localhost:51731 (Java 1.8.0_31, Clojure 1.7.0, nREPL 0.2.10)`

This was when called from a clj repl running https://github.com/clojure-emacs/cider/commit/f0256324fe74bf2dda04feec5b8a4ef3515726df

**Comment by bbatsov** [comment]
Is this still a problem?
