### ISSUE TITLE
cider-repl--send-input: Symbol's function definition is void: spinner-start

### ISSUE THREAD

**Issue by sakh1979** [clojure-emacs/cider#1270]
I can successfully connect to `cider` from emacs `clojure-mode` via `cider-jack-in` command. But, as soon as I start typing, or evaluate a function I get the following error: `cider-repl--send-input: Symbol's function definition is void: spinner-start`

My settings are: `CIDER 0.10.0snapshot (Java 1.8.0_31, Clojure 1.7.0, nREPL 0.2.10)`

Please let me know if you need more information from me. FYI: I don't get any stacktrace as well.

**Comment by bbatsov** [comment]
How did you install CIDER? Seems to me you don't have the spinner package installed (a recent dependency of CIDER).

**Comment by sakh1979** [comment]
Ah, I didn't know about the spinner package. I installed CIDER manually via `el-get`.

Anyway, here is my CIDER setting:

```
;----------------;
;;;  Clojure   ;;;
;----------------;

(require 'ac-cider)

(add-hook 'clojure-mode-hook 'paredit-mode)
(add-hook 'clojure-mode-hook 'rainbow-delimiters-mode)

(add-hook 'cider-repl-mode-hook 'paredit-mode)
(add-hook 'cider-repl-mode-hook 'rainbow-delimiters-mode)
(add-hook 'cider-repl-mode-hook 'ac-cider-setup)

(add-hook 'cider-mode-hook 'ac-flyspell-workaround)
(add-hook 'cider-mode-hook 'cider-turn-on-eldoc-mode)
(add-hook 'cider-mode-hook 'ac-cider-setup)

(eval-after-load "auto-complete"
  '(add-to-list 'ac-modes 'cider-mode))

(provide 'clojure-settings)
```

**Comment by bbatsov** [comment]
Well, it's pretty obvious - the `el-get` recipe is out-of-date. Someone has to update it.

**Comment by crodjer** [comment]
Created a PR: https://github.com/dimitri/el-get/pull/2235
