### ISSUE TITLE
Can't change namespace with nrepl-sync-request:eval

### ISSUE THREAD

**Issue by abo-abo** [clojure-emacs/cider#1273]
This code will not change the namespace as of now:

```
(nrepl-sync-request:eval "(ns foo)")
```

However, it used to work. The commit that broke it was d201a43.

**Comment by bbatsov** [comment]
I'll look into this. There are problems with sync requests right now, that I'm looking into (like hardcoded default connection, etc).

**Comment by bbatsov** [comment]
Is this still relevant?

**Comment by abo-abo** [comment]
Yes. Eval one-by-one with `cider-eval-last-sexp`:

```clojure
(ns foo)
;; => nil
(def x 10)
;; => #'foo/x
(ns bar)
;; => nil
(def x 9)
;; => #'foo/x
```

The same sequence works fine in the REPL.

**Comment by bbatsov** [comment]
Got it. Btw, this has nothing to do with `nrepl-sync-request:eval`, as the evaluations in Clojure buffers are async.

**Comment by abo-abo** [comment]
Of course. What I want in the end is for the above 4 statements to work with `lispy-eval`, which uses `nrepl-sync-request:eval`.  But since the async eval doesn't work, the sync one doesn't work by proxy.

**Comment by bbatsov** [comment]
@Malabarba I thought your recent changes in clojure-mode solved this. Basically here the problem is that the first ns form was picked up, instead of the closest one. @abo-abo are you using the newest clojure-mode from melpa?

**Comment by Malabarba** [comment]
They should have solved it, though I admittedly didn't test evaluation

**Comment by abo-abo** [comment]
Just updated to the latest `clojure-mode`: this issue still remains.

**Comment by bbatsov** [comment]
Ok, I'll debug this once I reassemble my keyboard.

On Sunday, 15 November 2015, Oleh Krehel <notifications@github.com> wrote:

> Just updated to the latest clojure-mode: this issue still remains.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/1273#issuecomment-156804462>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by dpsutton** [comment]
![it_works](https://cloud.githubusercontent.com/assets/6377293/21747736/23b8854a-d537-11e6-939a-5716718f5233.png)

It looks like this can be closed? @abo-abo is this correct?

**Comment by abo-abo** [comment]
@dpsutton Looks correct, thanks.
