### ISSUE TITLE
Insert links to the README's troubleshooting section for all REPL warnings

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1280]
No matter how descriptive the messages in the REPL are, many users are still confused by them. So, for the benefit of everyone it'd be best if we inserted troubleshooting links for all of the problems reported there.

**Comment by Malabarba** [comment]
Is there a way to get github to show me which branches contain a given commit? Or am I gonna have to check it out locally and ask git? 
The commit referenced above fixes this issue, but I can't figure out where I pushed it. 😓

**Comment by Malabarba** [comment]
Never mind. The mobile interface doesn't show it but the desktop interface does.

**Comment by bbatsov** [comment]
Great, then I guess you'll take care of this before the release.

**Comment by expez** [comment]
@Malabarba you can also just do `git cherry-pick b8eb54b` and it will fetch that commit from wherever it is locally.  You don't have to track down the specific branch or whatever, as long as you're on a machine and repo where that commit exists.

**Comment by Malabarba** [comment]
Good to know. 👍
