### ISSUE TITLE
Add an option to have the old connection dispatch

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1281]
While I believe the new smart connection dispatch (introduced in 0.10) is quite superior to the old algorithm based on the notion of "default connection", it would probably be best if the old algo was still available (via some config option). This was the default in CIDER for quite a while and it's also how SLIME works, so some people are probably attached to it. Implementing such an option should be pretty simple.

**Comment by Malabarba** [comment]
What was the old behavior again? Just use the first element of cider-connection?

**Comment by bbatsov** [comment]
Yes.

On Wednesday, August 26, 2015, Artur Malabarba <notifications@github.com>
wrote:

> What was the old behavior again? Just use the first element of
> cider-connection?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/1281#issuecomment-135111345>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by bbatsov** [comment]
There are two options to tackle this - make the current connection function customizable or just add a couple of options like static and dynamic (or smart) `cider-request-dispatch`. Any thoughts?

**Comment by Malabarba** [comment]
I vote for whichever complicates the code less. ☺ which is probably the latter.
