### ISSUE TITLE
Automatic :require form is incorrect when creating a .cljc form

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/cider#1282]
Create `src/test/a/b/c_test.cljc` and it produces:

``` Clojure
(ns a.b.c-test
  (:require [a.b.c :refer :all]
                 [clojure.test :refer :all]))
```

It would be better if it produced a clic aware test reference, for example:

``` Clojure
(ns a.b.c-test
  (:require [a.b.c :refer :all]
                #?(:clj [clojure.test :refer :all]
                     :cljs [cljs.test :refer :all)))  ;; or whatever the correct new cljs namespace is
```

I also really wish it would pull in the subject under test as `:as sut` rather than `refer all` ;-)

**Comment by Malabarba** [comment]
Maybe I'm wrong, but I think this is a clj-refactor.el feature.

**Comment by Malabarba** [comment]
Yep. Here it is: https://github.com/clojure-emacs/clj-refactor.el/wiki#automatic-insertion-of-namespace-declaration

This (and your other issue) should go there, I think.

**Comment by yatesco** [comment]
I apologise Malabarba - can I claim the all-forgiving `newbie` card ;-)

**Comment by Malabarba** [comment]
;)
