### ISSUE TITLE
Time to restructure the project a little?

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1285]
I found this to be pretty interesting: 
```
$ cloc .                                                                                                                             
     106 text files.
      88 unique files.                              
      42 files ignored.

-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Lisp                            63           3224           2266          15605
make                             1             10              0             36
Bourne Shell                     1              7              5             23
YAML                             1              0              1              8
-------------------------------------------------------------------------------
SUM:                            66           3241           2272          15672
-------------------------------------------------------------------------------
```

If this was a java project we'd have hundreds of files :p 

We have some circular dependencies that we have to eliminate if we want to be able to use byte compilation to find the most obvious problems.  `cider-interaction` and `cider-repl` are mutual dependencies at least.  

I'm guessing there are quite a few mutual dependencies created by our defcustoms.  We could move all these into a `cider-settings.el`.  This file is going to be huge, so we might consider having that only be used to require other files like `cider-repl-settings.el` to make it easier to find stuff.

**Comment by Malabarba** [comment]
Yes, `cider-interaction` as a whole definitely needs work, and so does `nrepl-client`.
@bbatsov has already been doing a lot of refactorings (specially on the latter).

I also think we have quite a bit of indirection in some places, so some code might just be able to go.

It might be necessary to have an extra file to keep some settings, as you suggest. But I'd like to leave that for last.
What I've found is that once you fix circular dependency in functions, the variables tend to be much easier to deal with.

**Comment by bbatsov** [comment]
This has been on my mind for quite a while now https://github.com/clojure-emacs/cider/issues/1068

I think @cichli was working on this, but I don't know if he's still is.
