### ISSUE TITLE
nrepl-sync-request:eval is breaking

### ISSUE THREAD

**Issue by looselytyped** [clojure-emacs/cider#1295]
I am not sure quite what the issue here is, so allow me to post what I have found so far. 

* I posted an issue on `lispy.el` - https://github.com/abo-abo/lispy/issues/115. The issue is that `lispy-eval` is breaking with a `No buffer named com.mycompany.job` error. 
* @abo-abo responded with https://github.com/abo-abo/lispy/issues/115#issuecomment-137040094 (reposting here) 

```
This is a breakage in CIDER and it should be fixed there, I think. Even the most basic eval request fails now:

(nrepl-sync-request:eval
 "(+ 2 2)"
 (cider-current-ns)
 (nrepl-current-session))
```
I am not quite sure if the the issue lies with CIDER or lispy, however, the issue seems to permeate from the fact that my buffer's name is _actually_ `job.clj` - but the error reports the name as the full `ns`. 

My apologies if this seems vague - I am trying to debug this on my machine, but my emacs-lisp-fu isn't all that great. 

Here is what I am running

Currently running `GNU Emacs 24.5.1` with

`cider 20150901.1605`
`lispy 20150901.550`

I will keep looking into this and see if I can come up with more info. 

On a final note, thank you for all your hard work on CIDER, and all other emacs/clojure tooling :)

**Comment by Malabarba** [comment]
This is because the CIDER internals are undergoing some breaking changes. If you look at the docstring for that function you'll see that its signature has changed to

    (nrepl-sync-request:eval INPUT CONNECTION SESSION &optional NS)

So that the correct way to call it is now

    (nrepl-sync-request:eval
     "(+ 2 2)"
     (cider-current-connection)
     (cider-current-session)
     (cider-current-ns))

I'm not sure if the refactoring is finished or not (@bbatsov?), but it is finished we should probably make a list of all the breaking changes.

**Comment by bbatsov** [comment]
It's a work in progress, but I have a pretty busy week at work and it's on hold for now. Looking at my schedule for the month I might not be able to finish everything until the beginning of October.

**Comment by looselytyped** [comment]
@Malabarba @bbatsov - Thank you for the prompt response. I can easily work around this if need be. And again, thank you for all your hard work. 

Would you rather I close this issue?

**Comment by bbatsov** [comment]
Guess that would be best.
