### ISSUE TITLE
Jumping doesn't work in cljc files

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1296]
There are a few issues here:
1. When it's ambiguous we need to prompt the user for a language context.
2. We need to check the context around point for reader macros to avoid asking a stupid question.
3. Right now I only have a clojure repl going and we shouldn't have to ask.  Just jump to the clj file.

I've written some code over in [clj-refactor](https://github.com/clojure-emacs/clj-refactor.el/blob/master/clj-refactor.el#L2263-L2295) to check if the context around point is for clojure. We might steal that.

**Comment by Malabarba** [comment]
I think these points apply to the smart dispatching in general, not just jumping. 

I agree with point 2, and it looks like your clj-refactor code would fill that need well. 

Point 1 would be good to have in some instances, but we need to be careful. We don't want to prompt while eldoc is fetching candidates in the background. 

Point 3 should already be the current behaviour. Cider only does smart dispatching when there are multiple repls for the current project. Did something different happen for you?

**Comment by expez** [comment]
> Point 3 should already be the current behaviour. Cider only does smart dispatching when there are multiple repls for the current project. Did something different happen for you?

Yes, it turned into a no-op.  But I couldn't `C-c C-k` so it probably didn't know enough to do anything at all...

**Comment by bbatsov** [comment]
Can you add some repro steps? I just tested this with one connection and everything seems to be working as expected.

**Comment by bbatsov** [comment]
> When it's ambiguous we need to prompt the user for a language context.

I'm not sure what you mean by this - as the metadata has the cljc filename there can never be ambiguity.

**Comment by Malabarba** [comment]
I think he meant "calling jump inside a cljc file on a variable that's defined in other files (both clj and cljs).

**Comment by bbatsov** [comment]
I see. This will have to be handled in the middleware - probably by returning a list of find candidates (as we do for the Java stuff).

**Comment by expez** [comment]
> This will have to be handled in the middleware - probably by returning a list of find candidates (as we do for the Java stuff)

in clj-refactor I've opted to prompt the user for the language context when it is ambiguous.  Just returning a bunch of candidates is kind of tricky because they're going to have the same name often.  We'd then have to annotate them with `<clj>` or `<cljs>` so the user can distinguish among them.  I'm not sure that solution is any more user friendly, and it appears to be more work.
