### ISSUE TITLE
[FR] Opening a new connection to an existing nREPL server

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/cider#1300]
I've found it convenient in the past to have severan nREPL connections to a single nREPL server. Especially when messing with expressions that take a while to evaluate. At present it's easy enough to start a new nREPL server (C-c M-j) but without inspecting the resulting nREPL server buffer for a host/port it's not trivial to open a new REPL buffer connected to the same server.

Obviously something I'm fully capable of working around, but it'd be a nice addition.

**Comment by bbatsov** [comment]
So, the auto-completion you get in `cider-connect` is not enough and you'd like a new command to "clone" a connection? I'm just trying to figure what exactly do you have in mind.

**Comment by Malabarba** [comment]
The auto completion has always been enough for me to connect to a previously started server. Is there anything you think it lacks?

**Comment by arrdem** [comment]
@bbatsov - That's exactly what I had in mind.

@Malabarba - In my experience which is now a few weeks stale, server/port auto complete only works on localhost. The context in which I would find a "clone" command interesting would be duplicating a connection (including reusing the SSH tunnel if possible) to another machine.

**Comment by Malabarba** [comment]
I see, then it's certainly a worthy feature. I didn't know it only works with localhost. 
Instead of a whole new command, we could build this into cider-connect. For instance, it could offer to clone the current connection if invoked directly from a repl buffer. 
Another option is to include currently active connections during host completion.

**Comment by bbatsov** [comment]
If we do this the command will end up doing too much IMO. Finding the balance is always hard. Btw, this is related to the portscanner feature request as well.
