### ISSUE TITLE
org-babel clojure now fails w/ nrepl-sync-request:eval error

### ISSUE THREAD

**Issue by julienchastang** [clojure-emacs/cider#1302]
Org babel clojure now fails. For example,

```
#+BEGIN_SRC clojure 
(+ 1 2)
#+END_SRC
```

yields

```
Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 4) 1)
  nrepl-sync-request:eval("(+ 1 2)")
  (nrepl-dict-get (nrepl-sync-request:eval expanded) (if (or (member "output" result-params) (member "pp" result-params)) "out" "value"))
```

**Comment by Malabarba** [comment]
The internals have changed. 
See a very recent closed issue for more explanation.

**Comment by bbatsov** [comment]
See https://github.com/clojure-emacs/cider/issues/1295

Libraries depending on CIDER will have to be updated.

**Comment by julienchastang** [comment]
Thanks. I've spent the latest few hours migrating to melpa-stable. All I'd ask is that cider not end up in melpa-stable until downstream code has had time to migrate to the new API (e.g., org-mode and ob-clojure).

**Comment by bbatsov** [comment]
This really depends on their maintainers. I don't have nor the time nor the energy to sync up with everyone maintaining a 3rd party extension. I just hope they're following the development and will do the necessary changes when needed.
