### ISSUE TITLE
No active nREPL connection

### ISSUE THREAD

**Issue by sg2002** [clojure-emacs/cider#1305]
The current version of Cider no longer sees repl connections. You get "No active nREPL connection" when you try to do C-c M-n, but doing C-c M-j again would complain that REPL buffer already exists.

I've traced the commit to 2455438.

**Comment by bbatsov** [comment]
I'll investigate this later today.

**Comment by bbatsov** [comment]
Superficial examination shows that this affects only jack-in. There's crazy coupling between the code that starts an nREPL server locally and connecting to the server, which convinces me for the millionth time the current structure of the code is super problematic...

**Comment by bbatsov** [comment]
To be more precise, the problem is that right now the `nrepl-server-filter` does too much - after it detects the port of the server it connects to it automatically, which is kind of crazy as it creates a different execution path for `cider-connect` and `cider-jack-in`. I'm not sure why at some point I felt this was a good idea, but it's definitely not.

**Comment by kostafey** [comment]
After last update the message is:
```
error in process filter: cider-nrepl-sync-request:eval: Wrong type argument: stringp, nil
error in process filter: Wrong type argument: stringp, nil
cider-ensure-connected: No active nREPL connection
```

**Comment by Immortalin** [comment]
I am getting this @bbatsov I am getting this problem too

**Comment by bbatsov** [comment]
Yeah, yeah. I'm well aware of this. I'm contemplating the proper solution for this.

**Comment by Immortalin** [comment]
Is there any temporarily work arounds for this?

**Comment by bbatsov** [comment]
Just use `cider-connect`.

**Comment by Immortalin** [comment]
I have tried. Getting the same problem:

```
REPL buffer already exists (*cider-repl web-scraper*).  Do you really want to create a new one? (y or n) y
nREPL: Establishing direct connection to localhost:43643 ...
nREPL: Direct connection established
cider-nrepl-sync-request:eval: Wrong type argument: stringp, nil

**Comment by Malabarba** [comment]
I still have a "no connection" issue on latest master.
Here's the backtrace I get from jack-in. This happens after the server is started, when the repl is querying for the namespace.

    Debugger entered--Lisp error: (wrong-type-argument stringp nil)
      set-buffer(nil)
      (save-current-buffer (set-buffer (cider-current-connection)) nrepl-session)
      cider-current-session()
      (nrepl-sync-request:eval input (cider-current-connection) (cider-current-session) ns)
      cider-nrepl-sync-request:eval("(str *ns*)")
      (nrepl-dict-get (cider-nrepl-sync-request:eval "(str *ns*)") "value")
      (read (nrepl-dict-get (cider-nrepl-sync-request:eval "(str *ns*)") "value"))
      (or (read (nrepl-dict-get (cider-nrepl-sync-request:eval "(str *ns*)") "value")) "user")
      (let ((initial-ns (or (read (nrepl-dict-get (cider-nrepl-sync-request:eval "(str *ns*)") "value")) "user"))) (setq cider-buffer-ns initial-ns))
      (save-current-buffer (set-buffer buffer) (let ((initial-ns (or (read (nrepl-dict-get (cider-nrepl-sync-request:eval "(str *ns*)") "value")) "user"))) (setq cider-buffer-ns initial-ns)))
      (let ((nrepl-sync-request-timeout nil)) (save-current-buffer (set-buffer buffer) (let ((initial-ns (or (read (nrepl-dict-get ... "value")) "user"))) (setq cider-buffer-ns initial-ns))))
      cider-repl-set-initial-ns(#<buffer *cider-repl clojure-playground*>)
      cider-repl-init(#<buffer *cider-repl clojure-playground*>)
      cider--connected-handler()
      run-hooks(nrepl-connected-hook)
      (save-current-buffer (set-buffer client-buf) (nrepl--init-client-sessions client-proc) (nrepl--init-capabilities client-buf) (run-hooks (quote nrepl-connected-hook)))
      (let* ((endpoint (nrepl-connect host port)) (client-proc (plist-get endpoint :proc)) (host (plist-get endpoint :host)) (port (plist-get endpoint :port)) (client-buf (funcall nrepl-create-client-buffer-function endpoint))) (set-process-buffer client-proc client-buf) (set-process-filter client-proc (quote nrepl-client-filter)) (set-process-sentinel client-proc (quote nrepl-client-sentinel)) (set-process-coding-system client-proc (quote utf-8-unix) (quote utf-8-unix)) (process-put client-proc :string-q (progn (vector (quote cl-struct-queue) nil nil))) (process-put client-proc :response-q (progn "Constructor for objects of type `nrepl-response-queue'." nil (vector (quote cl-struct-nrepl-response-queue) nil nil nil))) (save-current-buffer (set-buffer client-buf) (let ((server-buf (and server-proc (process-buffer server-proc)))) (if server-buf (progn (add-hook (quote kill-buffer-hook) (function nrepl--maybe-kill-server-buffer) (quote append) (quote local)) (setq nrepl-project-dir (buffer-local-value (quote nrepl-project-dir) server-buf) nrepl-server-buffer server-buf)))) (setq nrepl-endpoint (list host port) nrepl-connection-buffer client-buf nrepl-tunnel-buffer (let ((tunnel (plist-get endpoint :tunnel))) (if tunnel (progn (process-buffer tunnel)))) nrepl-pending-requests (make-hash-table :test (quote equal)) nrepl-completed-requests (make-hash-table :test (quote equal)))) (save-current-buffer (set-buffer client-buf) (nrepl--init-client-sessions client-proc) (nrepl--init-capabilities client-buf) (run-hooks (quote nrepl-connected-hook))) client-proc)
      nrepl-start-client-process(nil 39711 #<process nrepl-server>)
      (let* ((client-proc (nrepl-start-client-process nil port process)) (client-buffer (process-buffer client-proc))) (setq nrepl-connection-buffer client-buffer) (if (functionp nrepl-post-client-callback) (progn (funcall nrepl-post-client-callback client-buffer))))
      (save-current-buffer (set-buffer (process-buffer process)) (let* ((client-proc (nrepl-start-client-process nil port process)) (client-buffer (process-buffer client-proc))) (setq nrepl-connection-buffer client-buffer) (if (functionp nrepl-post-client-callback) (progn (funcall nrepl-post-client-callback client-buffer)))))
      (let ((port (string-to-number (match-string 1 output)))) (message (format "nREPL server started on %s" port)) (save-current-buffer (set-buffer (process-buffer process)) (let* ((client-proc (nrepl-start-client-process nil port process)) (client-buffer (process-buffer client-proc))) (setq nrepl-connection-buffer client-buffer) (if (functionp nrepl-post-client-callback) (progn (funcall nrepl-post-client-callback client-buffer))))))
      (progn (let ((port (string-to-number (match-string 1 output)))) (message (format "nREPL server started on %s" port)) (save-current-buffer (set-buffer (process-buffer process)) (let* ((client-proc (nrepl-start-client-process nil port process)) (client-buffer (process-buffer client-proc))) (setq nrepl-connection-buffer client-buffer) (if (functionp nrepl-post-client-callback) (progn (funcall nrepl-post-client-callback client-buffer)))))))
      (if (string-match "nREPL server started on port \\([0-9]+\\)" output) (progn (let ((port (string-to-number (match-string 1 output)))) (message (format "nREPL server started on %s" port)) (save-current-buffer (set-buffer (process-buffer process)) (let* ((client-proc (nrepl-start-client-process nil port process)) (client-buffer (process-buffer client-proc))) (setq nrepl-connection-buffer client-buffer) (if (functionp nrepl-post-client-callback) (progn (funcall nrepl-post-client-callback client-buffer))))))))
      nrepl-server-filter(#<process nrepl-server> "nREPL server started on port 39711 on host 127.0.0.1 - nrepl://127.0.0.1:39711\n")

**Comment by bbatsov** [comment]
> I still have a "no connection" issue on latest master.
> Here's the backtrace I get from jack-in. This happens after the server is started, when the repl is querying for the namespace.

I'm guessing your list of connections is still `nil` but after my latest changes this shouldn't be happening. I did some quick tests and `jack-in` seems to work fine for me. There might be some race condition, but that seems very likely.

**Comment by Malabarba** [comment]
In my case, it can be fixed by adding `(cider-make-connection-default buffer)` to the very start of `cider-repl-init`.
Does that sound bad?

**Comment by bbatsov** [comment]
Well, it doesn't sound terrible, but once again - the server callback already executes this, so I really can't understand why is this not working for you. Doing this in `cider-repl-init` might be problematic when REPL buffers get recycled.

**Comment by bbatsov** [comment]
Ideally the API should be changed in a way that jack-in simply boots the server, obtains its port and does `cider-connect`, but this will require a bit of rework.

**Comment by Malabarba** [comment]
> Well, it doesn't sound terrible, but once again - the server callback already executes this, 

Yes, but that's too late. Looking at the code:

      (with-current-buffer (process-buffer process)
        (let* ((client-proc (nrepl-start-client-process nil port process))
               (client-buffer (process-buffer client-proc)))
          ;; FIXME: Bad connection tracking system. There can be multiple client
          ;; connections per server
          (setq nrepl-connection-buffer client-buffer)

          (when (functionp nrepl-post-client-callback)
            (funcall nrepl-post-client-callback client-buffer))))

`nrepl-start-client-process` will immediately run `nrepl-connected-hook`. One of the functions in this hook is `cider--connected-handler`, which calls `cider-repl-init`, which tries to set the initial namespace, which fails because `nrepl-post-client-callback` hasn't been run yet and therefore the connection hasn't been registered.

To me it looks like the best place to make the connection as default is in `cider--connected-handler`.

**Comment by bbatsov** [comment]
> To me it looks like the best place to make the connection as default is in cider--connected-handler.

The problem is that there's not easy way to pass the connection to a hook function, unless you use dynamic variables... Clearly the real issue here is that the filter initiates a connection itself. You can also notice that the server process gets passed to the connection creation function for no good reason as well. It's hard to reason about all these spaghetti and it's even harder to modify the code in its current state.

**Comment by Malabarba** [comment]
Spaghetti indeed. I'm relatively certain we have more indirection than necessary here, so there should be room for simplification.
But, like you say, it's hard to reason about it so it's hard to be sure.

In any case, I still can't see how it currently works for you. The post-client-callback is clearly being run after starting the REPL, and starting the repl involves a couple of evaluations.

**Comment by bbatsov** [comment]
> In any case, I still can't see how it currently works for you. The post-client-callback is clearly being run after starting the REPL, and starting the repl involves a couple of evaluations.

No idea. Looking at the code you pointed out - it shouldn't be. :-)

> Spaghetti indeed. I'm relatively certain we have more indirection than necessary here, so there should be room for simplification.
> But, like you say, it's hard to reason about it so it's hard to be sure.

Probably. I just can't figure out a simplification that can be implemented quickly... One relatively simple idea would be for the filter to simply set the port in the server buffer and the code in jack-in to wait until the port if available so it can connect to that server instance, but I'm not sure I'll have time to deal with this today. Better ideas are welcome...

**Comment by bbatsov** [comment]
Btw, another solution would be dispensing with `nrepl-connected-hook`, as clearly right now we use callbacks that rely on more than just the fact than an nREPL connection was established...

**Comment by Malabarba** [comment]
I'm ok with the connection being created by the server filter. It's the act of connecting itself that ties knots on my brain. 

1. `cider.el` sets `nrepl-create-client-buffer-function` to `cider-repl-create`, which is a function in `cider-repl.el`.
2. `nrepl-start-client-process` calls `nrepl-create-client-buffer-function`.
3. `cider-repl-create` adds `cider--connected-handler` (which is a function back in `cider.el`) to `nrepl-connected-hook`.
4. `nrepl-start-client-process` then immediately runs `nrepl-connected-hook` (without waiting for the repl to actually connect) which causes `cider--connected-handler` to run.
5. `cider--connected-handler` then calls (amongst other things) `cider-repl-init`, which is a function back in `cider-repl.el`

Note that we jumped from `cider.el` to `cider-repl.el` back to `cider.el` then back to `cider-repl.el` again.
I'm not saying there must be a better way to do this, but it *feels* a little roundabout.

Maybe, instead of calling `cider-repl-create` to create the buffer, `nrepl-start-client-process` could just create the buffer itself, make the connection, and then call `cider--connected-handler`.
This way `cider--connected-handler` could do everything cider-related in one go (including the stuff that `cider-repl-create` does now, with the exception of creating a buffer).

This would entirely skip steps 3 and 4, but I think it would make it harder to reuse a zombie repl buffer. =/

**Comment by Vastorization** [comment]
happen again in cider-nrepl 0.11.0-snapshot, can't even connect from cider-connect. 

something from *Messages*:
nREPL: Establishing direct connection to localhost:46647 ...
nREPL: Direct connection established
Connected.  Hack and be merry!
cider-ensure-connected: No active nREPL connections

**Comment by usq** [comment]
I get exactly the same messages as @Vastorization on 0.11.0-snapshot

**Comment by maksr** [comment]
I upgraded to cider 0.11.0 from cider 0.8.2 and now C-c M-c breaks similarly as above:
```
nREPL: Establishing direct connection to localhost:12345 ...
nREPL: Direct connection established
Connected.  Hacks and glory await!
user-error: `cider-connect' needs an active nREPL connection
```
I tried to step through `cider-connect` but when I instrument it for edebug with C-u C-M-x, it works. If I then de-instrument it with C-M-x, it works until restart of Emacs. So this is my workaround until better times.

**Comment by Malabarba** [comment]
> I tried to step through cider-connect but when I instrument it for edebug with C-u C-M-x, it works. If I then de-instrument it with C-M-x, it works until restart of Emacs. So this is my workaround until better times.

That's a spot on sign of badly compiled code. 

Delete cider, upgrade all your packages, restart emacs, install cider.

**Comment by maksr** [comment]
Thank you, it was really the case.
