### ISSUE TITLE
cider-jack-in can instrument, but cider-connect can't

### ISSUE THREAD

**Issue by riaandewit** [clojure-emacs/cider#1308]
Hi folks -(clojure noob warning) cider looks tasty - thanks for everything. I'm sure I'm abusing the tool, but can't figure out how. I saw a couple of other issues that sort-of-kind-of look like they relate to this problem, but after trying a couple of things, still have no joy.

Used to edebug, I thought it'd be cool to create a hello-world ring app, run it and connect, then instrument a function and see how that works. 

In a terminal, I do 
```bash
lein ring server
```
.. and get feedback that nrepl is running on a port, the server starts up, and I can actually see the sample page. From inside emacs, I then do 
```bash
M-x cider-connect
```
, manage to connect, but get:
```
; CIDER 0.10.0snapshot (package: 20150908.444) (Java 1.8.0_31, Clojure 1.6.0, nREPL 0.2.7)
WARNING: The following required nREPL ops are not supported: 
apropos classpath complete eldoc format-code format-edn info inspect-pop inspect-push inspect-refresh macroexpand ns-list ns-vars ns-path refresh resource stacktrace toggle-trace-var toggle-trace-ns undef
Please, install (or update) cider-nrepl 0.10.0-SNAPSHOT and restart CIDER
```
... I'm still able to change to a namespace, eval a function after I've changed it, reload the web page, and see the results.

BUT - If I try to instrument a given function, I get:
```
RuntimeException No reader function for tag dbg  clojure.lang.LispReader$CtorReader.readTagged (LispReader.java:1180)
```
*cider-error* has a ton of stuff in it - but it looks like the above is the sane output.

When I do a "cider-jack-in" - the ring app is not started (sort of makes sense) - but I can play around and instrument, call some functions from the repl and step through the code.

Is wanting to instrument and step through functions in a running ring app a fair request, or is there some other approach I should be taking - or is something broken?

I'm on OS X Yosemite - Emacs 24.4.1 - I'm using prelude (thanks again) - and installed cider using M-x package-list-packages - version there is listed as 20150908.444

my ~/.lein/profiles.clj is this:
```clojure
{:user {:plugins [[cider/cider-nrepl "0.10.0-SNAPSHOT"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.7"]]}}
```

Any advice really,really appreciated

**Comment by expez** [comment]
Please see [this](https://github.com/clojure-emacs/cider#using-embedded-nrepl-server) section in the readme about how to embed an nrepl server into your application.

The reason this isn't working now is that the repl you're connected to doesn't have CIDER's middleware available.  This is reflected in the warning you receive.

When you use `cider-jack-in` CIDER does all the setup for you.

**Comment by riaandewit** [comment]
Thanks for that. My understanding of your message is that the nRepl that comes with ring is not what we need - CIDER's nRepl is much better, and must be activated. I've updated project.clj to:
```
(defproject webapp "0.0.1"
  :description "A hello world for a Ring based web app"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [ring "1.3.1"]
                 [cider/cider-nrepl "0.10.0-SNAPSHOT"]]
  :dev-dependencies [[lein-ring "0.4.5"]]
  :ring {:handler webapp.core/app}
  :profiles {:dev {:plugins [[lein-ring "0.8.13"]]}})
```

... and core.clj is:
```
(ns webapp.core
  (:require [clojure.tools.nrepl.server :as nrepl-server]
            [cider.nrepl :refer (cider-nrepl-handler)]))

(defn foo
  "I don't do a whole lot."
  [x]
  (println x "Hello, World:)!!"))

(defn app [req]
  {:status  200
   :headers {"content-Type" "text/html"}
   :body    "Hello World :)(:"})

(defn -main
  []
  (println "trying to setup nREPL")
  (nrepl-server/start-server :port 8888 :handler cider-nrepl-handler))
```

When I run 
```
lein ring server
```
I still get the server starting on port 3000 - but no message that nRepl is running on port 8888 - no connecting with cider-connect possible.

Should I be starting the app up in a different way, or am I still missing something?
If there's a "running nRepl tutorial" or something out there - just point me to it. 
Thanks for your time

**Comment by cichli** [comment]
I think you need to add `:nrepl {:start? true}` into the `:ring` map of your `project.clj`, rather than starting the nREPL server yourself - see [here](https://github.com/weavejester/lein-ring#web-server-options) in the `lein-ring` README :-). Not sure which versions that applies to - I'd recommend bumping to `[lein-ring "0.9.6"]` - you should only need that in `:plugins` btw, not in `:dev-dependencies` too.

On another note, it seems `lein-ring` bundles a pretty old version of nREPL - see [here](https://github.com/weavejester/lein-ring/blob/f64d86aa1d032b3423fa3ed652cbe10475f1b8d1/src/leiningen/ring/server.clj#L41-L44) - it's definitely worth adding an explicit dependency on `[org.clojure/tools.nrepl "0.2.10"]` to `:dependencies` in your `:dev` profile for CIDER to work properly.

Hope that helps!

**Comment by expez** [comment]
> lein ring server

**Comment by cichli** [comment]
> I don't see how this could be enough. How would it know to use cider-nrepl-handler?

`lein-ring` checks in `:repl-options` for the `:nrepl-middleware` key (as of 0.9.2), which `cider-nrepl` automatically populates with its middleware - see weavejester/lein-ring@d32ab8f80039d4c2af2b972cb4112b04628e13e4.

**Comment by riaandewit** [comment]
@cichli - great stuff, thanks :)
Just for when I forget, with a project.clj like this:
```
(defproject webapp "0.0.1"
  :description "A hello world for a Ring based web app"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [ring "1.3.1"]
                 [cider/cider-nrepl "0.10.0-SNAPSHOT"]
                 [org.clojure/tools.nrepl "0.2.10"]]
  :plugins [[lein-ring "0.9.6"]]
  :ring {:handler webapp.core/app
         :nrepl{:start? true}})
```
... and a core.clj like this:
```
(ns webapp.core)

(defn foo
  "I don't do a whole lot."
  [x]
  (concat x " Hello, World:)!!"))

(defn app [req]
  {:status  200
   :headers {"content-Type" "text/html"}
   :body    (foo "Excellent!")})
```

... I'm able to go into the root directory, and run 
```
lein ring server
```
which then fires up the browser, with the example message in it.

```
M-x cider-connect
```
then prompts and connects nicely, and browsing to core.clj inside Emacs, C-c M-n (switch to namespace) and C-u C-M-x can be used to instrument the foo function, and subsequent refreshes of the browser drops into the edebug type interface :)

I've made note of how to get the basics going here:
https://github.com/riaandewit/beginner-cider-nrepl
... just in case anyone else feels the need.
