### ISSUE TITLE
Fresh install cider-jack-in causing wrong-number-of-arguments error

### ISSUE THREAD

**Issue by tvanhens** [clojure-emacs/cider#1318]
I have a fresh install of clojure-mode and cider both installed from package-list-packages with no other packages installed. When I run cider-jack-in from a boot.build file containing the following code:

``` clojure
(set-env!
 :source-paths #{"src"})
```

I encounter the following emacs stack trace:

```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 0)
  nrepl--message-color()
  nrepl-log-message((---> "op" "clone" "id" "1"))
  nrepl-send-request(("op" "clone" "id" "1") #[257 "\301\300\"\207" [(dict) nrepl--merge] 4 "\n\n(fn RESP)"] #<buffer *cider-repl thebigsheet*<3>>)
  nrepl-send-sync-request(("op" "clone" "id" "1") #<buffer *cider-repl thebigsheet*<3>>)
  nrepl-sync-request:clone(#<buffer *cider-repl thebigsheet*<3>>)
  nrepl--init-client-sessions(#<process nrepl-connection<2>>)
  nrepl-start-client-process(nil 61018 #<process nrepl-server<2>>)
  nrepl-server-filter(#<process nrepl-server<2>> "nREPL server started on port 61018 on host 127.0.0.1 - nrepl://127.0.0.1:61018\n")

```

This is my profile.boot file:

```
(require 'boot.repl)

(swap! boot.repl/*default-dependencies*
       concat '[[cider/cider-nrepl "0.9.1"]]) ; Tried 0.10.0-SNAPSHOT as well

(swap! boot.repl/*default-middleware*
       conj 'cider.nrepl/cider-middleware)
```

Versions:
nrepl: 0.2.10
clojure: 1.6
boot: 2.2.0
cider: 0.10.0snapshot
clojure-mode: 4.2.0-snapshot

**Comment by expez** [comment]
@tvanhens When you say "fresh install" do you literally mean that or did you just upgrade both packages?  If it's the latter then it's likely that the package manager screwed up and things will work if you delete the cider folder(s) under `.emacs.d/elpa` and install again.

**Comment by tvanhens** [comment]
Deleting the elpa folder did it. Thought I had a fresh install but forgot to delete my .cask directory. Thanks.
