### ISSUE TITLE
Only track clojure.core at initialization

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1321]
`clojure.core` is an important namespace to track, but it's also huge and unlikely to ever change. We would probably gain something like 20-50ms if we just assumed that it never changes.

**Comment by bbatsov** [comment]
I think we can assume this for every ns that starts with `clojure.`.

**Comment by bbatsov** [comment]
This might be a bit of an issue if you're working on `clojure` or some of the core tools, though, so we should have some way to customize this behavior.

**Comment by Malabarba** [comment]
All true. Would be nice if we could detect that automatically too. Is there a way to differentiate whether a namespace is part of the project or part of a dependency?

**Comment by bbatsov** [comment]
We can always have an option to set the project's ns as a dir local, but I'm not sure how we can automate the detection - guess using c.t.n. on only the source files should be enough. We can assume that everything else is something that's not going to change.
