### ISSUE TITLE
Fix for #1317 slightly messes up my OpenCL syntax coloring

### ISSUE THREAD

**Issue by blueberry** [clojure-emacs/cider#1322]
This might be a low priority, but for people using other languages with Clojure, it seems to me that after the cider fix for the issue #1317 connected to rainbow-delimiters, I get a poorer syntax coloring in my C files (poorer meaning that some things are colored, but some other that I think previosly were in color, now are white).

I cannot give a concrete example, since it might depend on my (minimal) additional configuration, but it might be worth testing whether syntax coloring works well with other languages after cider-mode kicks in.

**Comment by Malabarba** [comment]
Cider only updates the font-lock rules on buffers with cider-mode turned on. Have you, by any chance, set `cider-mode` to `t` in those C buffers?

**Comment by blueberry** [comment]
Not as far as I can see with my very limited elisp-fu. I checked with C-h m and searched for anything cider - nothing was found.

**Comment by expez** [comment]
@blueberry you can check if a mode is on by inspecting the variable by the same name, so `C-h v <cider-mode> RET` should give you the answer.

**Comment by blueberry** [comment]
cider-mode is a variable defined in `cider-mode.el'.
Its value is nil

  Automatically becomes buffer-local when set.

Documentation:
Non-nil if Cider mode is enabled.
Use the command `cider-mode' to change this variable.

**Comment by Malabarba** [comment]
Then this makes no sense to me. ☺
You'll need to try to figure out exactly what part of your config is causing this, so that we can then figure out if it's a bug.

**Comment by blueberry** [comment]
I just reported this for future investigation. Thank you for help - I appreciate it and it is a low priority for me. If I manage to narrow the possible problem I'll report it. Thanks for being so helpful - please do not waste time on this (non)issue :)

**Comment by expez** [comment]
Closing this so it doesn't clutter up our issue tracker.  Feel free to re-open if/when you've done more investigation.
