### ISSUE TITLE
False positives when highlighting vars in core

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1324]
![](http://i.imgur.com/MvdngWY.png)

**Comment by Malabarba** [comment]
Yes. Sadly, there's very little we can do about that. 😢

**Comment by bbatsov** [comment]
We can teach font-locking about certain forms to avoid this (e.g. `ns`, `defn`, etc).

**Comment by expez** [comment]
Ignore `ns` sounds like a good idea to me, that's where the majority of the false positives will be.  What do you mean about avoiding `defn`?

**Comment by bbatsov** [comment]
Another common place of false positives are parameter names (and local variables). That's what I meant.

**Comment by Malabarba** [comment]
I know how to make font lock ignore a regexp, but not a form. 
I know it's possible though  (pretty much anything is possible with font lock).

**Comment by bbatsov** [comment]
I'm guessing there're no new ideas here. I'd really like us to reduce the false positives before the release as they are kind of annoying in bindings, but I can live with them.

**Comment by Malabarba** [comment]
I think it might be feasible to change font-lock-fontify-region to something that looks at sexps and sets the value of a `cider-local-vars` text property to a list of the local vars around a sexp. Then the font-lock rules would have to check the value of that variable before applying dynamic faces.

I believe this would work, though I've never done anything like this.

**Comment by bbatsov** [comment]
I hope you'll have a bit of time to give the idea shot.

**Comment by Malabarba** [comment]
Done. :+1:
