### ISSUE TITLE
Add the ability to “tail” the `*nrepl-server …*` buffer

### ISSUE THREAD

**Issue by MerelyAPseudonym** [clojure-emacs/cider#1328]
Given a situation like the following...
<img width="768" alt="_cider-repl_twitter-collector_" src="https://cloud.githubusercontent.com/assets/831177/9918309/0b04ec72-5c94-11e5-858d-2757661328d4.png" />

I'd _like_ for the window showing the `*nrepl-server …*` buffer to scroll as new input comes in.
Here are a couple more screenshots that demonstrate the <em>desired</em> behavior vs. the <em>actual</em> behavior.

# Desired outcome
<img width="768" alt="_cider-repl_twitter-collector_" src="https://cloud.githubusercontent.com/assets/831177/9918329/2efb7c5e-5c94-11e5-912f-bba491320fd4.png" />

# Actual outcome
<img width="768" alt="_cider-repl_twitter-collector_" src="https://cloud.githubusercontent.com/assets/831177/9918326/26a61faa-5c94-11e5-9624-569ba0535ea0.png" />

**Comment by Malabarba** [comment]
Now that the server buffer keeps track of all clients, we could also just forward to all connection(repl) buffers any messages it receives (subject to a user option). 

That should also be an easy elisp hack, if anyone wants to try. 😉

**Comment by bbatsov** [comment]
Yeah, probably this'd be best. I was musing over a similar solution a while back. I wonder, though, what's happening for people who're using `cider-connect`.

**Comment by expez** [comment]
This was implemented, discussed, and rejected previously https://github.com/clojure-emacs/cider/pull/818

I ended up putting the pertinent code in my `.emacs.d` because I really wanted that functionality.

**Comment by bbatsov** [comment]
As I said before - the server buffer will **never** get "tail" functionality, but I'm pretty open to @Malabarba's idea to simply redirect the output to the matching REPL buffer. If memory serves I suggested something similar.

**Comment by Malabarba** [comment]
> Yeah, probably this'd be best. I was musing over a similar solution a while back. I wonder, though, what's happening for people who're using cider-connect.

An ideal solution would be doing this in a middleware, instead of cider.el. Then people without a server buffer would benefit too. That said, either option would be a significant improvement on the current situation.

**Comment by bbatsov** [comment]
You can go over #818 for more details. I don't think this can be done using middleware as it seems that the output is dumped directly by the Clojure process and has nothing to do with nREPL. I haven't looked into this in a while, but I believe no one had ideas how to handle this reliably...

On the other hand this seems to work correctly with `reply`, although I'm not sure it will work correctly if you connect with `reply` to a running nREPL server.

**Comment by Malabarba** [comment]
It's not nREPL's fault, but the middleware can stil change the root value of `#'*out*`, can't it? Then the clojure process should respect that.

**Comment by bbatsov** [comment]
Hmm, something like this might work. We can probably send some init message to this middleware when cider launches. @cemerick does this sound sensible to you?

**Comment by bbatsov** [comment]
A bit more details about the proposed solution/workaround - https://gist.github.com/daviesian/4517859

**Comment by Malabarba** [comment]
Yeah, that gist is pretty it. The middleware could also define a custom output stream that prints to all connected sessions, instead of just one.

**Comment by bbatsov** [comment]
Yeah, that sounds reasonable.

**Comment by cemerick** [comment]
Yes, one can bash away at `*out*`, and it'll be picked up transparently.

This whole issues is related to http://dev.clojure.org/jira/browse/NREPL-4, but that's a far more ambitious, fiddly undertaking.

**Comment by bbatsov** [comment]
Once https://github.com/clojure-emacs/cider-nrepl/pull/257 is merged this will finally be resolved.

**Comment by bbatsov** [comment]
Guess now we can finally add the scrolling support.

**Comment by MerelyAPseudonym** [comment]
I'm happy to see that this was resolved, but I want to apologize to @bbatsov for (unintentionally) reopening a contentious topic: my bad.
