### ISSUE TITLE
Feature request: cider-error go to source location

### ISSUE THREAD

**Issue by malloc82** [clojure-emacs/cider#1330]
Currently upon encounter a run time error, cider-error will report the line number relatively to the function, which as we all know quite painful while debugging.

With latest nrepl, 0.2.11, more specifically [this patch](https://github.com/clojure/tools.nrepl/commit/64238a10a8465e0c590acb660ec5d54bf7cc3af4),  it seems that it's now possible to trace to actual source location. So is it possible to add this support in the upcoming cider 0.10 release?

**Comment by bbatsov** [comment]
Given the people involved in this patch, do you really have doubts we won't actually use it? :-)

**Comment by malloc82** [comment]
Yeah ... sorry, it's kinda obvious, but just I couldn't help myself :P
