### ISSUE TITLE
C-c C-q produces a ton of errors on Windows

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1333]
It appears to do what it should, but this stuff is appended to the `*messages*` buffer:

```
Connected.  The best way to predict the future is to invent it. -Alan Kay
Are you sure you want to quit the current CIDER connection *cider-repl refactor-nrepl*? (y or n) y
nREPL: Connection closed
Also kill server process and buffer? (y or n) y
error in process filter: save-current-buffer: Selecting deleted buffer
error in process filter: Selecting deleted buffer
error in process sentinel: cond: Could not start nREPL server: 
error in process sentinel: Could not start nREPL server: 
```

**Comment by expez** [comment]
`<kbd> C-x C-k`</kbd> to kill the repl gives the same result.

**Comment by Malabarba** [comment]
I just got cider from Melpa, and cider-nrepl from clojars. Here's my output after `C-c M-j` followed by `C-c C-q`:

    nREPL server started on 49507
    nREPL: Establishing direct connection to localhost:49507 ...
    nREPL: Direct connection established
    Connected.  Code long and prosper!
    Are you sure you want to quit the current CIDER connection *cider-repl clojure-playground*? (y or n) y
    nREPL: Connection closed
    Also kill server process and buffer? (y or n) y

**Comment by expez** [comment]
The offending line is this: `(when proc (delete-process proc))`

I don't understand how that triggers the messages in the OP.  Is killing the process flushing out messages or something?

**Comment by expez** [comment]
Aha, `nrepl-client-sentinel` is triggered, which calls `nrepl--maybe-kill-server-buffer` which tries to kill the same buffer as `cider--close-buffer`.

**Comment by expez** [comment]
Both also try to kill the process...

**Comment by Malabarba** [comment]
`cider-quit` should only call `cider--close-buffer` on the repl buffers, and the client sentinel should only try to kill the server (buffer and process). In addition, this server killing should only happen after the client process has died (that's when the sentinel is run).

At least, that's what was supposed to happen. :-)
Can you tell which one of these items isn't doing what it should?

**Comment by expez** [comment]
`server-buffer` is `#<killed buffer>` in `nrepl-server-sentinel` and `event` is `interrupted`.  The event being `interrupted` is what produces the `error in process sentinel: Could not start nREPL server: ` message.

I'm not sure where the other messages are produced, I haven't found the right code to instrument.  

Bit surprising that this is limited to windows, but that makes me not want to spend much more time on this.

**Comment by Malabarba** [comment]
Ok, I can mark the `interrupted` event to be handled just like the `killed` event.
Could you just check for me what's the value of `event` if the server actually fails to start? On my system, I just replaced my `project.clj` with an empty `(defproject)`, and got `"exited abnormally with code 1\n"`. If you get the same thing then I can push a fix.

**Comment by expez** [comment]
I'll have to check this on monday, I don't subject myself to Windows in my spare time :p

**Comment by expez** [comment]
The even here is `finished`.

**Comment by Malabarba** [comment]
Ok, that's a mess, but it's a manageable mess.
The cider now lets the server die silently if it gets the interrupted event. Let me know if it works.

**Comment by expez** [comment]
```
Connected.  This REPL is yours to command!
Are you sure you want to quit the current CIDER connection *cider-repl refactor-nrepl*? (y or n) y
nREPL: Connection closed
Also kill server process and buffer? (y or n) y
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: 
error in process sentinel: Could not start nREPL server: 
```

We're getting closer.  I've no idea what the deal with the server start as part of the shutdown is.  Any thoughts?

**Comment by Malabarba** [comment]
Gah. That's the opposite of what I would have expected.
I guess the fix is not so trivial. For now, I'll leave this open for one of our windows users to try and tackle. ☺

**Comment by expez** [comment]
When I tried stepping through this on friday I couldn't identify any code trying to start an nREPL server as part of quitting.  Do you have any idea?

**Comment by Malabarba** [comment]
I don't think it's trying to start a new server. I think that when we kill the original server emacs gets confused with the event  received and thinks that the server failed to start. Even though it started fine long ago. 

It's probably just a matter of misinterpreting the event, but I might well be wrong.

**Comment by expez** [comment]
I'm still getting 

```
Also kill server process and buffer? (y or n) y
error in process filter: Selecting deleted buffer [2 times]
```

Somewhere before entering the server sentinel, but I'm not sure why and this isn't really that big a deal.
