### ISSUE TITLE
Lisp error: (wrong-type-argument integer-or-marker-p t) in parse-partial-sexp

### ISSUE THREAD

**Issue by tsdh** [clojure-emacs/cider#1335]
I just updated to the MELPA version 20150918.631 and now when trying to complete a symbol, I get this error:

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p t)
  parse-partial-sexp(t 30150)
  cider-in-string-p()
  cider-complete-at-point()
  completion--capf-wrapper(cider-complete-at-point all)
  run-hook-wrapped(completion--capf-wrapper cider-complete-at-point all)
  completion-at-point()
  indent-for-tab-command(nil)
  funcall-interactively(indent-for-tab-command nil)
  call-interactively(indent-for-tab-command nil nil)
  command-execute(indent-for-tab-command)
```

**Comment by bbatsov** [comment]
Guess @expez will look into this.

**Comment by tvanhens** [comment]
I'm experiencing this issue as well. Makes cider unusable for me due as the cursor jumps to the top of the file any time autocompletion is attempted. Is there a workaround to turn off autocompletion?

**Comment by bbatsov** [comment]
The package will be updated pretty soon on MELPA. Generally the new packages are built without an hour.

**Comment by expez** [comment]
This has been fixed for two hours so it should be available now

**Comment by tvanhens** [comment]
I don't see it yet... newest is still `20150918.631` for me

**Comment by bbatsov** [comment]
You can always build the package locally http://emacsredux.com/blog/2015/05/10/building-melpa-packages-locally/

**Comment by expez** [comment]
Might be easier to just eval the tiny patch ^^

**Comment by tvanhens** [comment]
@bbatsov didn't know about that just tried it and the new version fixed the issue, thank you and @expez. Thats a very cool trick :+1:
