### ISSUE TITLE
Toggle between the Clojure & ClojureScript REPL

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1337]
If we have the two REPLs for some project it will be nice to be able to quickly toggle between them.

**Comment by expez** [comment]
any suggestion for keybiding?

I immediately thought of <kbd>C-c C-r</>, because I've never used that binding, to *rotate* the repl but that's bound to eval region.  Is eval region really something that's useful in the repl buffer?

**Comment by bbatsov** [comment]
I was thinking of `C-c M-z`. Frankly, I dislike the rotate terminology.

**Comment by Malabarba** [comment]
How about `cider-other-repl` under `C-c o` in analogy to `other-window`.

**Comment by bbatsov** [comment]
This is a keybinding reserved for users. (but I like the name for the command, this was my idea as well, although inspired by `find-other-file`).

**Comment by expez** [comment]
How about repurposing the `C-c C-o` binding?  It's currently used by:

```
C-c C-o runs the command cider-repl-clear-output, which is an
interactive compiled Lisp function in `cider-repl.el'.

It is bound to C-c C-o, <menu-bar> <REPL> <Clear output>.

(cider-repl-clear-output)

Delete the output inserted since the last input.
```

Since we already have `C-c M-o` (which clears the entire repl) I've never found the need for `C-c C-o`.

**Comment by bbatsov** [comment]
It's pretty useful when the last evaluation dumped some huge output and you lost context because of it. SLIME has the same command with the same keybinding, so I'm guessing plenty of people are used to it.

**Comment by expez** [comment]
Right, what about repurposing `C-c M-o` then, and let `C-c M-o` be what `C-c C-o` does when given a prefix?  That way `C-c C-o` clears the last or all output.

**Comment by Malabarba** [comment]
I like that.

**Comment by bbatsov** [comment]
I like it as well.

**Comment by arichiardi** [comment]
:+1 I use C-c M-o a lot, but I guess that change won' t bother me too much, it actually sounds more appropriate to have a prefix to C-c C-o

**Comment by bbatsov** [comment]
I didn't rebind the command in `cider-mode`, only in `cider-repl-mode`. Probably it'd better if were changed there as well for consistency.

**Comment by expez** [comment]
Yes

**Comment by bbatsov** [comment]
Done.

On 5 November 2015 at 10:08, Lars Andersen <notifications@github.com> wrote:

> Yes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/1337#issuecomment-153983100>
> .
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com
