### ISSUE TITLE
nrepl startup fails due to void definition of `-some->`

### ISSUE THREAD

**Issue by jklukas** [clojure-emacs/cider#1346]
When I attempt to install cider from the latest SNAPSHOT, the install seems to go fine, but when I actually try to `cider-jack-in`, and error is thrown before the nrepl actually starts up:
```
Starting nREPL server via lein repl :headless...
nREPL server started on 53229
nREPL: Establishing direct connection to localhost:53229 ...
nREPL: Direct connection established
error in process filter: nrepl--pp: Symbol's function definition is void: -some->
error in process filter: Symbol's function definition is void: -some->
```

It looks like this call to `-some->` was introduced 2 weeks ago in https://github.com/clojure-emacs/cider/commit/d4771d51fc456a7271aa14d05d10f86c27e8cddf.

Is it possible that `-some->` is defined in some package which isn't defined as a dependency for cider?

cc @carlosyslas, @cichli, and @expez who were involved in writing and reviewing that commit.

**Comment by expez** [comment]
Try [this](https://github.com/clojure-emacs/cider#i-upgraded-cider-using-packageel-and-it-broke).

**Comment by jklukas** [comment]
@expez : thanks for the suggestion. I removed the existing packages per the instructions and ended up installing from melpa stable.

**Comment by arichiardi** [comment]
I confirm bumping dash.el solves the problem.
