### ISSUE TITLE
Ditch dash.el

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1348]
In Emacs 25.1, seq.el will be built-in (it's also a smaller package). So it would be nice to replace the dash dependency with seq.

There are currently 102 usages of dash functions that I could find by grepping for `[(']-[-a-z]`. About half of them `-when-let`s and `-if-let`s. The other half are functions provided by `seq`. The only exception I found was `-map-indexed`.

One way to replace the `-when/if-let`s is to drop 24.3 support and use `when/if-let`. Another is to copy the definition of `when/if-let` from `subr-x.el`. What do we think?

**Comment by bbatsov** [comment]
:+1: Let's inline `when-let` and `if-let` and go forward with this.

**Comment by rogergl** [comment]
I could try to help with this task.

**Comment by bbatsov** [comment]
You're welcome to do so. :-)

**Comment by Malabarba** [comment]
👏👏👏👏🎉🎊🎆

:-)

**Comment by rogergl** [comment]
I had a first look at the source. There seems to be a subx-r version that contains if-let, when-let. The subx-r version my Emacs 24.5 uses,  does not. So inlining means copy them over ?

**Comment by bbatsov** [comment]
Yep.

**Comment by rogergl** [comment]
Should I copy them to cider-common.el ?

**Comment by bbatsov** [comment]
No, copy them to `cider-util.el.`. You'll see we have other backported stuff there.

**Comment by rogergl** [comment]
I think  prefixing them with cider, like the other function in util, would be not a very good idea ?

**Comment by bbatsov** [comment]
Take this approach instead https://github.com/bbatsov/projectile/blob/master/projectile.el#L56

I don't want us to prefix them.

**Comment by rogergl** [comment]
What about the other stuff from dash like -> ?

**Comment by bbatsov** [comment]
`subr-x` has `thread-first` and `thread-last` - you can copy and alias them (or use them with their Elisp names, it's all the same to me).

**Comment by rogergl** [comment]
Ok, than I'll use thread-first and thread-last. This makes it easier to see if there is still something used from dash.

**Comment by rogergl** [comment]
-when-let, -if-let, -> and ->> are gone. Not sure how I should include the stuff from seq.el.

**Comment by bbatsov** [comment]
> Not sure how I should include the stuff from seq.el.

Just add a dependency to `seq` (to the package itself, so it will work on older Emacsen) and apply your best judgement when swapping dash.el functions for their seq.el equivalents.

**Comment by rogergl** [comment]
Ok, most of the changes are done, except:

cider-eldoc  using -elem-index
cider-interaction using -each
cider-stacktrace using -repeat
cider-util -using map-indexed

**Comment by bbatsov** [comment]
They don't have equivalents?

On Sunday, 11 October 2015, Roger Gilliar <notifications@github.com> wrote:

> Ok, most of the changes are done, except:
>
> cider-eldoc using -elem-index
> cider-interaction using -each
> cider-stacktrace using -repeat
> cider-util -using map-indexed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/1348#issuecomment-147181445>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by Malabarba** [comment]
Could you open a PR with this stuff? 

Elem index sounds like something seq.el should have. Maybe we can ask @NicolasPetton for it. 

 -each sounds like a variation of map or dolist. Or is it something like checking that every element satisfies a predicate? 

-repeat can be done in several ways. Manually build a list with dotimes, or use make-list to create a dummy list and map over it. 

map-indexed is the trickier one. We could ask Nicolas to add it to seq.el too. Or we could implement it with dolist while incrementing a counter.

**Comment by bbatsov** [comment]
> -each sounds like a variation of map or dolist. Or is it something like checking that every element satisfies a predicate?

Or simply `mapc`. :-)

> map-indexed is the trickier one. We could ask Nicolas to add it to seq.el too.

Yeah, that'd be nice, but we can definitely use a custom solution for the time being.

**Comment by rogergl** [comment]
I do some QA tomorrow and trigger a pull request for the changes I made until then. After that I'll see how to handle the missing functions.

**Comment by NicolasPetton** [comment]
Artur Malabarba <notifications@github.com> writes:

> Elem index sounds like something seq.el should have. Maybe we can ask
> @NicolasPetton for it.

What would "elem index" be?

>  -each sounds like a variation of map or dolist.

`seq-doseq` works like `dolist`, but on any sequence.

> map-indexed is the trickier one. We could ask Nicolas to add it to
> seq.el too.

What does it do?  Does it pass the index of the element as an argument
to the function for each iteration?

**Comment by rogergl** [comment]
elem-index returns the index of an element e.g. (elem-index 'a ('b 'a 'c) returns 1

And, yes map-indexed passes the index on each iteration.

**Comment by NicolasPetton** [comment]
Guys, do you still need `seq-elt-index` and `seq-map-indexed`?

**Comment by bbatsov** [comment]
Sure. We applied some workarounds, but an unified solution would be better.

**Comment by Malabarba** [comment]
@NicolasPetton (just in case you don't know) cl-lib offers `cl-position`, so you can probably just alias that for `elt-index`.

**Comment by NicolasPetton** [comment]
@Malabarba `cl-position` only works on sequences, while seq.el can be extended to work on "custom" sequence data structures, so I won't be able to use `cl-position`, at least not directly.

**Comment by NicolasPetton** [comment]
I just added `seq-position` to seq, both in Emacs master and ELPA.

**Comment by Malabarba** [comment]
Thanks :+1:
