### ISSUE TITLE
Run checkdoc

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1352]
It would be nice to add checkdoc to our travis builds, but first we need to actually pass checkdoc. This means running checkdoc on each source file and making the edits suggested by it.
We don't need to do all files in one go. Fixing up a file should be enough for a PR.

Pretty much anyone can call `M-x checkdoc` in a file and follow the instructions, so this is as low as a fruit can hang.

**Comment by Malabarba** [comment]
If anyone takes this up, please set

    (setq checkdoc-package-keywords-flag nil)
    (setq checkdoc-arguments-in-order-flag nil)

so as to avoid these (irrelevant) warnings.

**Comment by bpacreau** [comment]
Hi Malabarba,

With @g12l, we are willing to help you on this issue. We're currently working on it and we're going to open our first PR soon

**Comment by bbatsov** [comment]
Sounds good!

**Comment by Malabarba** [comment]
That's great to hear! :)

**Comment by g12l** [comment]
Some files are already ok with checkdoc:
  -cider-scratch.el
  -cider-classpath.el
  -cider-resolve.el
  -cider-browse-ns.el
  -cider-compat.el
  -cider-selector
  -cider-eldoc
  -cider-macroexpansion.

With @bpacreau we corrected simple errors in cider-grimoire.el and cider-popul.el (PRs). We need some time for the other files and we will probably ask some questions on the gitter channel.

**Comment by bbatsov** [comment]
Roger that! :-)

**Comment by expez** [comment]
@g12l @bpacreau Thanks for taking this on,! :+1:

**Comment by Malabarba** [comment]
And feel free to ask away!
