### ISSUE TITLE
Weird prompt when associating connection with directory

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1356]
This is the prompt that I get when I `cider-connect` and chose to associate the connection with a directory (the cursor is between those two `//`):

    Project directory: ~/path/to/cider-nreplh//home/artur/path/to/cider-nrepl/

I should say that the prompt works. I can just hit `RET` and the directory used will be `/home/artur/path/to/cider-nrepl/`. But it's certainly not optimal.

I'm guessing this is due to #1326. @Peeja do you have this too?

**Comment by bbatsov** [comment]
Probably you're right. Guess we should fix it. :-)

**Comment by Malabarba** [comment]
Ping @Peeja :)

**Comment by bbatsov** [comment]
If someone can tell me how to reproduce this I can take a look at it.

**Comment by Peeja** [comment]
Sorry for the radio silence, @Malabarba! What are you using to read the prompt? Is that `ido`? It sounds like `helm` (which I use) and what you're using interpret the arguments to `read-directory-name` differently, and one of them is wrong.

**Comment by Malabarba** [comment]
@bbatsov 
> If someone can tell me how to reproduce this I can take a look at it.

1. Open a projec.clj file
2. cider-jack-in
3. cider-connect
4. Answer `y` to all prompts

@Peeja 
> What are you using to read the prompt?
Just stock Emacs.

**Comment by Peeja** [comment]
> Just stock Emacs.

Right, of course. I forget such a thing exists sometimes. :)

I tried using Emacs 24.4.1 with exactly enough config to install Cider and followed your steps. What I saw was

```
Project directory: {~/Inbox/prompt-test/} |/Users/peeja/Dropbox/Inbox/prompt-test/
```

(Where `|` is point.)

That looks sensible to me. What version of Emacs are you running? It looks like yours just has a different presentation for the default value.

**Comment by Malabarba** [comment]
I don't think it's sensible. :-)
I think it should only displays the directory once, with cursor at the end. Instead it's being displayed twice, with cursor in the middle.

**Comment by Peeja** [comment]
Oh, I see, if you start typing, it actually includes both strings on either side of the cursor. That's not right at all…

**Comment by Peeja** [comment]
Okay *now* I think I understand what all those arguments do. :) This looks much more reasonable, and appears to work correctly in plain Emacs and Helm.

**Comment by Malabarba** [comment]
I'll try this out when I can. But thanks already for taking the time @Peeja
