### ISSUE TITLE
[CLJS] cider-doc doesn't work on special symbols

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1358]
Evaluating `(def x 1)` in a cljs repl works fine, but if I try to `C-c C-d C-d` on the `def` symbol I get:

> Symbol def not resolved

**Comment by bbatsov** [comment]
@cichli Can you look into this?

**Comment by bbatsov** [comment]
@cichli ping :-)

**Comment by bbatsov** [comment]
I'm guessing the code there needs something similar to `resolve-special` in the `var-info` middleware. Was reminded about this today when I was investigating an eldoc bug.

**Comment by dpsutton** [comment]
So looking into this, it looks like it can resolve things you define in the namespace. So in `cljs.user`, I define `(defun foo [x] (+ 1 x))` and it gives me documentation on that. It seems like the core stuff is filtered out or not included in user.cljs is all. I'm gonna keep prodding.

**Comment by dpsutton** [comment]
I think this is a cljs-tooling issue.

**Comment by arichiardi** [comment]
Tried this with the new `cljs-tooling` `0.3.0-SNAPSHOT` and it works like a charm. See below both eldoc and `cider-doc` displayed.

![2018-08-09-184104_776x914_scrot](https://user-images.githubusercontent.com/1724788/43934367-e46eb8d8-9c03-11e8-8035-fb8da4e9f0ab.png)

It can be closed.

**Comment by xiongtx** [comment]
But it seems that the definition location is still unavailable?

**Comment by arichiardi** [comment]
There is no location for specials in ClojureScript all it is is a map of fields hardcoded in the code base.

**Comment by xiongtx** [comment]
If it's in the codebase, there should be a location?

**Comment by arichiardi** [comment]
Sorry maybe the explanation was not that great, here is a link, I basically copied that map in `cljs-tooling`.

https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/repl.cljc#L1105

Also opened CLJS-2808 on this topic in the ClojureScript Jira:

https://dev.clojure.org/jira/browse/CLJS-2808

**Comment by arichiardi** [comment]
This should be working now, if not it's just because we haven't merged it yet
