### ISSUE TITLE
Moving in the repl buffer

### ISSUE THREAD

**Issue by timur87** [clojure-emacs/cider#1361]
First of all, thank you for all the effort to create this cool development environment. Till now it has been working flawless but I have been experiencing some difficulties nowadays. It's expected as I'm using a snapshot version but sill wanted to inform you about this.

I'm having issues when I want to move the curser in a REPL buffer. EMACS starts to hang and it gets really annoying, I'm just guessing but it's an issue related to matching the start and end tags of clojure constructs. 

I'm using CIDER 0.10.0snapshot (package: 20151005.453) (Java 1.8.0_45, Clojure 1.6.0, nREPL 0.2.7) on GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)

If somehow I can provide more information please let me know.

**Comment by Malabarba** [comment]
1. `M-x toggle-debug-on-quit` 
2. Reproduce the issue
3. Hit `C-g` while Emacs is hanged
4. Show us the backtrace you get

**Comment by bbatsov** [comment]
> M-x toggle-debug-on-quit
> Reproduce the issue
> Hit C-g while Emacs is hanged
> Show us the backtrace you get

We should probably stuff this in the "troubleshooting" section.

**Comment by timur87** [comment]
Debugger entered--Lisp error: (quit)
  scan-sexps(1662676 -1)
  forward-sexp(-1)
  #[0 "\301\302\303\304\305\306\307\300!\310\"\311\312%D\313\302\314\301EDC\217\210`\315\316!\210`W\205(\300\211\242T\240\262\2050\202\207" [(6229) err funcall make-byte-code 0 "`\301\302!\210\301\303!\210`W\205\300\303\240\207" vconcat vector [forward-sexp -1 1] 3 "\n\n(fn)" error #[257 "\300\207" [nil] 2 "\n\n(fn ##)"] forward-sexp -1] 8 "\n\n(fn)"]()
  funcall(#[0 "\301\302\303\304\305\306\307\300!\310\"\311\312%D\313\302\314\301EDC\217\210`\315\316!\210`W\205(\300\211\242T\240\262\2050\202\207" [(6229) err funcall make-byte-code 0 "`\301\302!\210\301\303!\210`W\205\300\303\240\207" vconcat vector [forward-sexp -1 1] 3 "\n\n(fn)" error #[257 "\300\207" [nil] 2 "\n\n(fn ##)"] forward-sexp -1] 8 "\n\n(fn)"])
  cider-eldoc-beginning-of-sexp()
  cider-eldoc-info-in-current-sexp()
  cider-eldoc()
  #[0 "\302 \204\205G\303\304!\210\304\207	\203\303	 !\207\305 \306 \211\204$\304\202B@=\2038\307\310\"\206B\311!\202B\311!\206B\307\310\"\303!\266\203\207" [eldoc-last-message eldoc-documentation-function eldoc-display-message-p eldoc-message nil eldoc-current-symbol eldoc-fnsym-in-current-sexp apply eldoc-get-fnsym-args-string eldoc-get-var-docstring] 5 "\n\n(fn)"]()
  funcall(#[0 "\302 \204\205G\303\304!\210\304\207	\203\303	 !\207\305 \306 \211\204$\304\202B@=\2038\307\310\"\206B\311!\202B\311!\206B\307\310\"\303!\266\203\207" [eldoc-last-message eldoc-documentation-function eldoc-display-message-p eldoc-message nil eldoc-current-symbol eldoc-fnsym-in-current-sexp apply eldoc-get-fnsym-args-string eldoc-get-var-docstring] 5 "\n\n(fn)"])
  eldoc-print-current-symbol-info()
  #[0 "\205\301 \207" [eldoc-mode eldoc-print-current-symbol-info] 1 "\n\n(fn)"]()
  apply(#[0 "\205\301 \207" [eldoc-mode eldoc-print-current-symbol-info] 1 "\n\n(fn)"] nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 0 500000 t #[0 "\205\301 \207" [eldoc-mode eldoc-print-current-symbol-info] 1 "\n\n(fn)"] nil idle 0])

**Comment by Malabarba** [comment]
Thanks. Looks like it's coming from eldoc. 
Could you also show us the contents of the repl when this happens?

**Comment by timur87** [comment]
It's a kind of difficult it's a couple of millions of lines... And the more lines there are, the more it tends to hang

**Comment by Malabarba** [comment]
Oh dear. Then it's just emacs lagging on you.

**Comment by Malabarba** [comment]
Your best option will be to clear the buffer every once in a while. 

But you might be able to fix the lag by disabling some minor modes. Most minor modes don't optimize for millions of lines. :-)

**Comment by timur87** [comment]
OK thanks!
