### ISSUE TITLE
Display stacktrace when macroexpand fails

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1362]
When macroexpansion fails the request just times out instead of showing the corresponding stacktrace.

**Comment by bbatsov** [comment]
I think this is part of a general problem with sync requests. Fixing this eventually will be quite beneficial for the overall usability.

**Comment by expez** [comment]
How hard is this to fix?  This is a large pain point for me atm because I'm writing a library consisting of mostly macros.

**Comment by Malabarba** [comment]
To fix this, either make the macroexpand request async, or improve the sync request system to use more general err/out handlers.

**Comment by bbatsov** [comment]
I'd opt for the second option, as would have positive impact on so many places we're using sync requests (pretty much everything tooling related).

**Comment by bbatsov** [comment]
> How hard is this to fix? This is a real pain point for me atm because I'm writing a library consisting mostly of macros.

Not very hard - probably an hour of work or something like this...

**Comment by bbatsov** [comment]
Btw, I should also note that there's something wrong in the middleware - a timeout occurs only on unhandled exceptions there (so this would be the quick fix). This type of errors would at least be dumped into the REPL, but as was discussed a few times already - ideally we should display the stacktrace buffer for them.

**Comment by bbatsov** [comment]
Hmm, seems that the code there is just fine:

```
(defn macroexpansion-reply
  [{:keys [transport expander code ns display-namespaces print-meta] :as msg}]
  (let [expansion (macroexpansion expander code ns display-namespaces print-meta)]
    (try
      (transport/send
       transport
       (response-for msg :expansion expansion :status :done))
      (catch Exception e
        (transport/send
         transport (response-for msg (u/err-info e :macroexpand-error)))))))
```

Can't imagine why you'd be getting a timeout.

**Comment by expez** [comment]
> Can't imagine why you'd be getting a timeout.

Because the `try` block is around the sending of the macroexpanded form not around its creation.

**Comment by bbatsov** [comment]
Ah, fuck. Should have read this more carefully. I'll fix it right away.
