### ISSUE TITLE
C-x C-e produces cider--make-result-overlay: Wrong number of arguments

### ISSUE THREAD

**Issue by klaufir** [clojure-emacs/cider#1364]
I have a clean emacs install with melpa repo.
Installed cider and clojure-mode
M-x package-install cider
M-x package-install clojure-mode

To reproduce
1. load a clj file,
2. M-x cider-jack-in
3. type in "(+ 1 1)" and place the cursor at the end of the line
4. C-x C-e  

Version info:
GNU Emacs 24.3.1
CIDER 0.10.0alpha (package: 20151010.505) (Java 1.8.0_60, Clojure 1.7.0, nREPL 0.2.10)

**Comment by bbatsov** [comment]
Works for me just fine on Emacs 25.1 (the current master). Can you try upgrading your Emacs? We might have introduced some incompatibility with 24.3 without noticing it.

**Comment by klaufir** [comment]
Compiled git://git.savannah.gnu.org/emacs.git and on Emacs 25.0.50.1 it works fine now. Thanks for the help.

**Comment by bbatsov** [comment]
Still, it's worth checking what's wrong on 24.3 as we officially support it.

**Comment by Malabarba** [comment]
Yes. I'd rather leave this open as a reminder before we release.
