### ISSUE TITLE
CIDER doesn't show port when connecting to figwheel nREPL

### ISSUE THREAD

**Issue by malchmih** [clojure-emacs/cider#1367]
I'm starting `lein figwheel` which gives me nREPL server (as described [here](https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl#config)). 
I get: 
```lisp
cider-connect
localhost

cider-connect History
localhost
```
on the first screen, and empty port suggestion on the second one. If I manually type `7888` CIDER connects successfully.
My versions:
```lisp
; CIDER 0.10.0snapshot (package: 20151011.151) (Java 1.8.0_45, Clojure 1.7.0, nREPL 0.2.11)
user> 
```

**Comment by arichiardi** [comment]
Sorry to barge in. The first thing to check is whether figwheel write ```.nrepl-port```? The port file descriptors are still a hot topic. I don't know if you've seen [this](https://github.com/bhauman/lein-figwheel/issues/244), a little off topic actually. Just to show that there is still work to do.

**Comment by malchmih** [comment]
No, it doesn't. I just supposed that CIDER could get the port from somewhere else. I apologize if it's not the case.

**Comment by bbatsov** [comment]
Check the definition of `cider-locate-running-nrepl-ports` - apart from the `.nrepl-port` file we also try to extract them from the output of `ps`. I've never used figwheel, so I can't offer much help.

**Comment by expez** [comment]
@malchmih CIDER is actually able to get the port by parsing the output of the unix utility `ps`.

Here is the command that's used: ` "ps u | grep leiningen"`.  Most likely we need something else to support figwheel.  Could you find out what?

**Comment by bbatsov** [comment]
Btw, this issue is a reminder that the current code hasn't really been updated to support `boot`.

**Comment by malchmih** [comment]
Starting `lein repl`:
```shell
cider-dual ➤ lein repl                                                                                                                                                                                                                        
nREPL server started on port 42345 on host 127.0.0.1 - nrepl://127.0.0.1:42345
REPL-y 0.3.5, nREPL 0.2.11
Clojure 1.7.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> 
```
Running ps-grep:
```shell
cider-dual ➤ ps u | grep leiningen                                                                                                                                                                                                            
mma      18272 11.4  7.5 7542580 1232556 pts/7 Sl+  10:28   0:25 java -client -XX:+TieredCompilation -Xbootclasspath/a:/home/mma/.linuxbrew/Cellar/leiningen/2.5.1/libexec/leiningen-2.5.1-standalone.jar -Dfile.encoding=UTF-8 -Dmaven.wagon.http.ssl.easy=false -Dleiningen.original.pwd=/home/mma/workspace/cider-dual -Dleiningen.script=/home/mma/.linuxbrew/bin/lein -classpath :/home/mma/.linuxbrew/Cellar/leiningen/2.5.1/libexec/leiningen-2.5.1-standalone.jar clojure.main -m leiningen.core.main repl
```
There is nothing about the port in the output. So I guess `cider-locate-running-nrepl-ports` doesn't work for lein nrepl either?

**Comment by expez** [comment]
@malchmih sorry about wasting your time, I should've read the code more thoroughly.  It parses the output of `ps` to find the right dir.  In this case `/home/mma/workspace/cider-dual`

Then it does this, to find the port:

```el
(defun nrepl-extract-port (dir)
  "Read port from .nrepl-port, nrepl-port or target/repl-port files in directory DIR."
  (or (nrepl--port-from-file (expand-file-name "repl-port" dir))
      (nrepl--port-from-file (expand-file-name ".nrepl-port" dir))
      (nrepl--port-from-file (expand-file-name "target/repl-port" dir))))
```

**Comment by malchmih** [comment]
@expez Not a problem, glad to help :blush: There is no way for CIDER then to get port (without files), right? If so, I'll create issue in figwheel repository.

**Comment by expez** [comment]
@malchmih correct

**Comment by expez** [comment]
No changes are needed on our end.  This should work just fine once figwheel starts creating a `.nrepl-port` file.
