### ISSUE TITLE
Incorrect repl-buffer binding with both clj and cljs repls

### ISSUE THREAD

**Issue by malchmih** [clojure-emacs/cider#1368]
Worked perfectly till yesterday (I suppose). Now after connecting second repl (doesn't matter in which order) CIDER binds both .clj and .cljs files to it. Which is incorrect for one of them.

**Comment by bbatsov** [comment]
There's not really a binding between source buffers and REPL buffers - they are matched dynamically and we haven't updated anything related to this logic in a while. Can you provide us with more version details and perhaps some steps (or sample project) to reproduce this issue?

**Comment by malchmih** [comment]
@bbatsov Sorry, probably my wording was incorrect. Yeah, I understand that. What other details do you need?

**Comment by malchmih** [comment]
This is from my cider-repl buffer:
```lisp
; CIDER 0.10.0snapshot (package: 20151014.1429) (Java 1.8.0_45, Clojure 1.7.0, nREPL 0.2.11)
user> 
```

**Comment by malchmih** [comment]
Hmm... it works now. And I didn't change a thing. Will try to reproduce it in a separate repository.

**Comment by malchmih** [comment]
Cannot reproduce it now, closing. Will reopen (or create new one) if it happens again. @bbatsov Thank you anyway!

**Comment by malchmih** [comment]
This still doesn't work from time to time, but I cannot reproduce it reliably.

**Comment by Malabarba** [comment]
When it happens, does it stop working after a while, or does it happen right from the start of the session?

**Comment by malchmih** [comment]
I'm starting my every session by connecting to figwheel's nrepl service twice (clj/cljs). So the states are:
1. No repl
2. Clj repl
3. Cljs repl (from clj repl)
4. Another clj repl (now I use "clone", doesn't matter)
And on my forth step there are two possibilities. Either everything works fine (and never stops). Or both clj and cljs "stick" to my second (clj) repl and send all evaluation there. Last situation is also permanent.
