### ISSUE TITLE
When using Boot, cider-find-dwim jumps to a source file in tmp folder

### ISSUE THREAD

**Issue by env0der** [clojure-emacs/cider#1370]
Probably it's related to https://github.com/boot-clj/boot/issues/249

As far as I could understood from sources, ```cider``` uses absolute file path it get's from ```nrepl```. Under ```boot``` it points to the file in boot's tmp folder.

Steps to reproduce this issue:

1. Clone https://github.com/danielsz/holygrail
2. run ```boot dev``` inside project folder
3. ```cider-connect``` to it
4. Then go to https://github.com/danielsz/holygrail/blob/master/src/clj/holy_grail/core.clj#L3, place cursor under ```holy-grail.systems``` and do ```cider-find-dwim```.

A workaround that fixes this issue for me is to try to use relative file path first and fallback to absolute file path. Here is a modified function that I use:

```elisp
      ;; workaround for cider finding files in boot's temp directory
      ;; first try to find file using relative path (resource key in response)
      ;; if not found - it's probably a library and should be found using absolute path (file key in response)
      (defun cider--jump-to-loc-from-info (info &optional other-window)
        "Jump to location give by INFO.
INFO object is returned by `cider-var-info' or `cider-member-info'.
OTHER-WINDOW is passed to `cider-jamp-to'."
        (let* ((line (nrepl-dict-get info "line"))
               (file (nrepl-dict-get info "file"))
               (resource (nrepl-dict-get info "resource"))
               (name (nrepl-dict-get info "name"))
               (local-buffer (and resource
                                  (not (cider--tooling-file-p resource))
                                  (cider-find-file resource)))
               (buffer (or local-buffer (and file
                                             (not (cider--tooling-file-p file))
                                             (cider-find-file file)))))
          (if buffer
              (cider-jump-to buffer (if line (cons line nil) name) other-window)
            (error "No source location"))))

```

I don't know if it's the right repository for this issue. Maybe it should be fixed in cider-nrepl.

**Comment by bbatsov** [comment]
This was fixed in `cider-nrepl`.

**Comment by alexander-yakushev** [comment]
Not fixed for me in `cider-nrepl 0.10.0-SNAPSHOT`.

**Comment by bbatsov** [comment]
This is the relevant commit there https://github.com/clojure-emacs/cider-nrepl/commit/fbcecbaf10bb55aae875f93810b67b41c833da21

**Comment by alexander-yakushev** [comment]
Sorry, false alarm. I explicitly set nREPL version to `0.2.12` and the issue disappeared.

Now the other question is what pulls `org.clojure/tools.nrepl 0.2.8` if I don't manually mention it. But that's another story.

**Comment by bbatsov** [comment]
I think boot used to pull exactly 0.2.8 until recently.

**Comment by alexander-yakushev** [comment]
Makes sense. Thanks.
