### ISSUE TITLE
Font-lock deprecated vars

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1371]
This should be pretty simple to do using the same system that font-locks instrumented vars. 
Just add `:deprecated` to the keywords tracked by cider-nrepl's track-state middleware, and add a font-lock entry for it in `cider-mode.el` similar to the one we use for instrumented vars (the actual face should be different, of course).

**Comment by bbatsov** [comment]
Yeah, that's a good idea.
