### ISSUE TITLE
Support gradle and maven project in cider-jack-in

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1373]
Right now we properly detect only `boot` and `lein` projects, but some people are actually using `maven` and `gradle` adding the relevant project type detection logic and nREPL boot commands shouldn't be hard.

Related to https://github.com/clojure-emacs/refactor-nrepl/issues/124

//cc @kotarak

**Comment by bbatsov** [comment]
Basically, to make some progress on this we need info regarding how maven and gradle users typically boot the nREPL server.

**Comment by RadicalZephyr** [comment]
For gradle at least this is probably a good place to start looking: https://github.com/clojuresque

**Comment by kotarak** [comment]
I'm working on the gradle support. I created a pull request for this: https://github.com/clojure-emacs/cider/pull/1380. (Please let me know if the flow is different. I usually don't work work with PRs.)

I'm also working on the gradle plugin to provide the necessary interface from the "other" side.

**Comment by kotarak** [comment]
One question in particular, which is open for discussion in the PR, is the order of preference.

https://github.com/kotarak/cider/commit/9a22027d72530608b8266f7e0d5c3861edbb957b#diff-00bd1ee3b6816bf7f502bc824ec4a6e9R422

**Comment by bbatsov** [comment]
As I mentioned in the PR - there should be no order of preference; we should simply detect all possible project types and prompt the use to pick one. 

You'll have to update `clojure-project-root` in `clojure-mode` as well.

**Comment by kotarak** [comment]
Updated PR with sqashed commit: [PR #1391](https://github.com/clojure-emacs/cider/pull/1391).

**Comment by bbatsov** [comment]
Gradle support has been merged. I'll close this for now as it's unclear now many people are using Maven with CIDER and I don't want us to just fill the backlog with noise.
