### ISSUE TITLE
user shouldn't be default evaluation namespace

### ISSUE THREAD

**Issue by samaaron** [clojure-emacs/cider#138]
When evaluating code with `C-x-C-e` in a buffer, if the `ns` declaration hasn't already been evaluated for that specific buffer and therefore associating the ns with the buffer with a buffer-local variable, the form gets evaluated in the `user` namespace. 

This might feel like a sensible default, but I'm starting to get pretty annoyed with it. I end up thinking I'm evaluating stuff in a specific namespace, but because I forgot to manually evaluate the buffer's ns declaration, it's all gone into user. This causes all sorts of annoying issues with Overtone usage which relies on namespaces to limit/scope side effects.

I would much prefer it if the namespace was determined at eval time _every_ time an evaluation is triggered or, if a buffer hasn't had a ns associated with it, for it to be associated the first time any form is evaluated, not just the ns form. Evaluating the ns form should override whatever buffer ns association there is. Also (as noted in a previous issue) buffer ns associations should be per nrepl+buffer association not just per buffer.

**Comment by dddvvv** [comment]
This breaks my workflow. My business logic tries to evaluate in the documentation environment.

I am programming in a distributed emacs environment. I use one repl for business logic forms evaluation and another one for documentation forms. I rotate between this repls C-c M-r.

example:
[...] (business-logic-form) [...]
(comment
  (documentation-form "documentation-key"))
[...] (business-logic-form) [...]

Business logic is evaluated in a JVM with all dependencies loaded while documentation logic is evaluated in cljslua on top of autohotkey. The documentation nrepl environment only knows how to tile and open windows that contain reference documents.

**Comment by Malabarba** [comment]
The command `cider-eval-last-sexp-to-repl` evaluates a sexp in the REPL's namespace. That should do what you need.
