### ISSUE TITLE
Cider stopped working

### ISSUE THREAD

**Issue by iced** [clojure-emacs/cider#1382]
Starting with https://github.com/clojure-emacs/cider/commit/915f5639d821be8f1847d80a770840437c358c88 cider can't load with following stacktrace:

Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "seq")
  require(seq)
  eval-buffer(#<buffer  *load*-797864> nil "/home/iced/.emacs.d/el-get/cider/nrepl-client.el" nil t)  ; Reading at buffer position 3331
  load-with-code-conversion("/home/iced/.emacs.d/el-get/cider/nrepl-client.el" "/home/iced/.emacs.d/el-get/cider/nrepl-client.el" nil t)
  require(nrepl-client)
  eval-buffer(#<buffer  *load*-227463> nil "/home/iced/.emacs.d/el-get/cider/cider-client.el" nil t)  ; Reading at buffer position 1010
  load-with-code-conversion("/home/iced/.emacs.d/el-get/cider/cider-client.el" "/home/iced/.emacs.d/el-get/cider/cider-client.el" nil t)
  require(cider-client)
  eval-buffer(#<buffer  *load*-142567> nil "/home/iced/.emacs.d/el-get/cider/cider-interaction.el" nil t)  ; Reading at buffer position 1233
  load-with-code-conversion("/home/iced/.emacs.d/el-get/cider/cider-interaction.el" "/home/iced/.emacs.d/el-get/cider/cider-interaction.el" nil t)
  require(cider-interaction)
  eval-buffer(#<buffer  *load*> nil "/home/iced/.emacs.d/el-get/cider/cider-mode.el" nil t)  ; Reading at buffer position 1215
  load-with-code-conversion("/home/iced/.emacs.d/el-get/cider/cider-mode.el" "/home/iced/.emacs.d/el-get/cider/cider-mode.el" nil t)
  autoload-do-load((autoload "cider/cider-mode" ("/home/iced/.emacs.d/el-get/.loaddefs.elc" . 4755) t nil) cider-mode)
  command-execute(cider-mode record)
  execute-extended-command(nil "cider-mode")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by bbatsov** [comment]
Are you using el-get?

**Comment by bbatsov** [comment]
And to elaborate on this - every time we change the deps the `el-get` recipe gets broken as someone has to update it manually to reflect the new deps. I'm not an `el-get` user myself, so I always forget about this.

**Comment by bbatsov** [comment]
See https://github.com/dimitri/el-get/pull/2272

**Comment by iced** [comment]
el-get will need seq recipe as well :)
