### ISSUE TITLE
Cider checks nil process when reusing a buffer

### ISSUE THREAD

**Issue by udalrich** [clojure-emacs/cider#1385]
When the clojure server is stopped by calling `(clojure.tools.nrepl.server/stop-server the-server)`,  `cider-find-reusable-repl-buffer` throws an error because `get-buffer-process` returns nil and this is passed to `process-live-p`. 

This can be fixed by checking for a nil process around line 248 in cider.el:

      (if exact-buff
          (if (process-live-p (get-buffer-process exact-buff))
              (when (y-or-n-p

becomes

      (if exact-buff
          (if (and (get-buffer-process exact-buff)
                   (process-live-p (get-buffer-process exact-buff)))
              (when (y-or-n-p

**Comment by expez** [comment]
Thanks! :+1:

**Comment by expez** [comment]
What's your emacs version @udalrich?  I don't think this fix was necessary.  `process-live-p` handles `nil` just fine on `24.5.1`

**Comment by Malabarba** [comment]
@expez On 24.3, a nil argument to `process-live-p` meant “use the current buffer's process”, which then throws an error when the current buffer has no process.

**Comment by Malabarba** [comment]
Fortunately, we don't need the process-live-p at all. get-buffer-process apparently never returns dead processes. 
This information is not on the docstring, but it's on the info manual:

    -- Function: get-buffer-process buffer-or-name
         This function returns a nondeleted process associated with the
         buffer specified by BUFFER-OR-NAME.  If there are several processes
         associated with it, this function chooses one (currently, the one
         most recently created, but don’t count on that).  Deletion of a
         process (see ‘delete-process’) makes it ineligible for this
         function to return.
    
         It is usually a bad idea to have more than one process associated
         with the same buffer.
    
              (get-buffer-process "*shell*")
                   ⇒ #<process shell>
    
         Killing the process’s buffer deletes the process, which kills the
         subprocess with a ‘SIGHUP’ signal (*note Signals to Processes::).

**Comment by udalrich** [comment]
I was using 24.3.

Troy
