### ISSUE TITLE
Lisp error: (wrong-type-argument stringp nil) on cider-jack-in

### ISSUE THREAD

**Issue by tobiasbayer** [clojure-emacs/cider#1390]
When trying to ``cider-jack-in`` I get the following error:
````
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  nrepl-op-supported-p("artifact-list" nil)
  cider-nrepl-op-supported-p("artifact-list")
  cljr--op-supported\?("artifact-list")
  -remove(cljr--op-supported\? ("artifact-list" "artifact-versions" "clean-ns" "extract-definition" "find-symbol" "find-used-locals" "hotload-dependency" "namespace-aliases" "rename-file-or-dir" "resolve-missing" "stubs-for-interface" "version" "warm-ast-cache"))
  cljr--check-nrepl-ops()
  cljr--init-middleware()
  run-hooks(nrepl-connected-hook)
  nrepl-start-client-process(nil 55546 #<process nrepl-server<2>>)
  nrepl-server-filter(#<process nrepl-server<2>> "nREPL server started on port 55546 on host 127.0.0.1 - nrepl://127.0.0.1:55546\n")
````

**Comment by expez** [comment]
that `nil` is `(cider-current-connection)`.  As to why that might be `nil` in this context, is hard to say.

Did you recently upgrade CIDER, @tobiasbayer?

`M-x cljr-version <RET>` and `M-x cider-version <RET>` would also be hepful.

**Comment by tobiasbayer** [comment]
Yes, I recently upgraded. In fact, it seems to be broken since the upgrade.
Sorry for omitting the version info:

``clj-refactor 2.0.0-SNAPSHOT (package: 20151021.1408), refactor-nrepl is unreachable``
``CIDER 0.10.0snapshot (package: 20151028.758)``

**Comment by expez** [comment]
Maybe try [this](https://github.com/clojure-emacs/cider#i-upgraded-cider-using-packageel-and-it-broke), also wiping the clj-refactor files.

**Comment by tobiasbayer** [comment]
This did the trick! Thanks a lot.

**Comment by sjatkins** [comment]
I don't get the above.  What exactly fixed it?  The link is for the full repo which I don't find so clearly helpful.  The funny thing is that running exactly the same on my Mac and on Linux (ubuntu) I always have this problem on the mac and never on linux.

**Comment by arbscht** [comment]
@sjatkins (and anyone else who might find this issue), the [relevant documentation](https://github.com/clojure-emacs/cider/blob/master/doc/troubleshooting.md#i-upgraded-cider-using-packageel-and-it-broke) has moved.
