### ISSUE TITLE
Transfer meaningful file and line information on hot code eval

### ISSUE THREAD

**Issue by kotarak** [clojure-emacs/cider#1392]
Working on a function in a file, hot evaling it in the repl server and testing it immediately is a very fast way of working. Unfortunately the file and line information is not kept during hot eval. In case of an exception you get rather useless location information.

In VimClojure I implemented said information transfer to the backend and it worked rather well for debugging. I simply proxied the reader during eval and also set the compiler location specific Vars.

cf. [`make-reader` and `with-repl*`](https://bitbucket.org/kotarak/vimclojure/src/22bbb523b40189aea180bf2ace8eeffe24cb456b/server/src/main/clojure/vimclojure/repl.clj?fileviewer=file-view-default#repl.clj-102)

Is there a chance to have this implemented in cider also? And if yes, where should I start?

PS: I know that the location info of code below said function might get of out sync. I consider this less annoying than having no info at all during debug. And it can be easily fixed by hot eval if necessary.

**Comment by bbatsov** [comment]
This was (finally) added on nREPL 0.2.11, so you just have to start using it (together with the latest CIDER snapshot which sends this data to nREPL).

**Comment by bbatsov** [comment]
Details here https://github.com/clojure-emacs/cider/commit/2c24aaae2219689c05e7165a9b7b3acdbecae21d

**Comment by bbatsov** [comment]
You might also take a look here https://github.com/clojure-emacs/cider/issues/1389#issuecomment-152488257

**Comment by Malabarba** [comment]
Maybe I misunderstood this, but I think @kotarak was asking for something slightly different.
I think he is evaluating stuff on the REPL buffer, and just wants any previous line/col/file information to be preserved. If that's the case then:

1. @kotarak: you may want to try using `C-M-x` instead of using the repl to redefine stuff.

2. @bbatsov: a lot of people prefer the repl buffer, and I imagine it probably screws up with line/col/file information (since the repl knows nothing about those). It might be useful if repl evaluation didn't try to set this information (so as to avoid overriding a previous good value).

**Comment by bbatsov** [comment]
> It might be useful if repl evaluation didn't try to set this information (so as to avoid overriding a previous good value)

I'm pretty sure if you don't set anything it's just set to `nil`, so if we're to add some special handling in the REPL it should probably take into account the original metadata and reuse it. Btw, we can also do something pretty wild and treat the REPL buffer as file name - this would allow us to jump back to definition in the REPL itself. :-)

**Comment by kotarak** [comment]
Aside from other possible improvements, my point was actually switching between repl and file. I attached a picture, which illustrates my problem. Notice how the second call to `work.in/progress` yields useless non-information regarding location after editing the function and hot evaling it via `cider-eval-defun-at-point`.

![argh](https://cloud.githubusercontent.com/assets/40587/10845689/398fed6a-7f0a-11e5-8511-2c76496a0524.png)

**Comment by bbatsov** [comment]
This definitely works differently with the current snapshot and nREPL 0.2.11.

**Comment by kotarak** [comment]
Great! :D

**Comment by Malabarba** [comment]
Ok, then it sounds like Bozhidar had it right. :-)

>Btw, we can also do something pretty wild and treat the REPL buffer as file name - this would allow us to jump back to definition in the REPL itself. :-)

I'd be cool with this too. And it probably wouldn't involve any changes on the clojure side.

**Comment by bbatsov** [comment]
> I'd be cool with this too. And it probably wouldn't involve any changes on the clojure side.

Yep, I believe this can be implemented entirely in the EL portion of the code.

**Comment by johngit22** [comment]
I am not certain of what VIM CLOSURE is, thanks.  Please explain..a light explanation will do.

**Comment by kotarak** [comment]
VimClojure is a Clojure plugin for Vim, which I maintained for 5 years. It provided a state-of-the-art Clojure environment since 2008. Even nowadays I would be perfectly happy with it.
