### ISSUE TITLE
Support at least latest released version of Emacs

### ISSUE THREAD

**Issue by alexott** [clojure-emacs/cider#1394]
The fix #1348 brought new dependency (seq.el) that broke my setup that uses Emacs 24.5.

I think that it would be nice to support at least latest released version, because not all people can upgrade to snapshots - Emacs 25.1 isn't released yet.  It would be also nice to explicitly document such version-dependent changes.

**Comment by bbatsov** [comment]
This dependency is in GNU ELPA, so this should not be an issue. We support
Emacs 24.3+.

**Comment by alexott** [comment]
Hmmmm, somehow it wasn't handled in my setup - sorry for buzzz...

**Comment by bbatsov** [comment]
No problem.

On Saturday, 31 October 2015, Alex Ott <notifications@github.com> wrote:

> Hmmmm, somehow it wasn't handled in my setup - sorry for buzzz...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/1394#issuecomment-152717069>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com
