### ISSUE TITLE
cider-repl-type is clj for cljs buffers created by cider-jack-in-clojurescript

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1400]

**Comment by Malabarba** [comment]
I pushed the first 2 commits in your PR, and with the current master I can't reproduce this issue. Could you restart/reload everything and try again?

**Comment by expez** [comment]
Testing this now the situation is reversed.  The cljs repl has the correct type but the clj repl has `"cljs"`.  I just pulled in `master` and brought up a fresh pair of repls.

**Comment by Malabarba** [comment]
I still can't reproduce this. =/ Here's what I'm doing:

1. lein new app testing
2. Edit profiles.clj to look like this:

        (defproject testing "0.1.0-SNAPSHOT"
          :description "FIXME: write description"
          :url "http://example.com/FIXME"
          :license {:name "Eclipse Public License"
                    :url "http://www.eclipse.org/legal/epl-v10.html"}
          :dependencies [[org.clojure/clojure "1.7.0"]
                         [org.clojure/clojurescript "0.0-3165"]
                         [com.cemerick/piggieback "0.2.1"]]
          :plugins [[cider/cider-nrepl "0.10.0-SNAPSHOT"]]
          :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}
          :main ^:skip-aot testing.core
          :target-path "target/%s"
          :profiles {:uberjar {:aot :all}})

3. Visit core.clj and `C-c M-J`.
4. Verify that both repls have correct value for the variable (and this is still true after playing around a bit).

**Comment by expez** [comment]
I reproduced it in `lein new test` using my own `profiles.clj`, but it did take some time until the problem occurred.  I was testing out the new eval functionality in a `.cljc` file when the problem manifested itself.

i tried reproducing it in your project, with an empty `profiles.clj` but I keep getting:

``
error in process sentinel: Could not start nREPL server: Error loading cemerick.piggieback: java.lang.IllegalStateException: var: #'clojure.tools.nrepl.middleware.interruptible-eval/queue-eval is not public, compiling:(cemerick/piggieback.clj:240:3)
```

The only difference is that I used the jmost recent version of cljs.

**Comment by expez** [comment]
I had to put `nrepl` in the `:dev` profile to fix this.  It was being clobbered by my (very old) leiningen version.

**Comment by expez** [comment]
I'm seeing it right away in a test project with an empty profile.

**Comment by expez** [comment]
Since you fixed something related to this when the other PR got merged I'll just close this and re-open if the issue resurfaces.
