### ISSUE TITLE
eval a string of clojure code using cider-read-and-eval from emacs lisp

### ISSUE THREAD

**Issue by drorbemet** [clojure-emacs/cider#1401]
Would it make sence to extend cider-read-and-eval to accept a string of clojure code to eval in the cider-repl buffer belonging to the file of current buffer?
I would like to eval clojure code from command line after starting an emacs client with a clojure project and a cider-repl. For that I would like to eval clojure code using emacs lisp avoiding a clojure source file.

**Comment by bbatsov** [comment]
Can't you simply use `cider-nrepl-request:eval`?

**Comment by drorbemet** [comment]
I got errors trying to apply ``cider-nrepl-request:eval`` the first time around. 
Then I got doubts if that's the right function.
Thanks for the hint.
Now figured it out with the help of some source on github.
