### ISSUE TITLE
Cider overaggressively evaluates forms it shouldn't when you do C-M-x (namespace problem)

### ISSUE THREAD

**Issue by alain-picard** [clojure-emacs/cider#1403]
Imagine you a a file foo.clj which looks like this:

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    (ns foo.core)

    (defn foo-1 []
      (println "cider is awesome!"))

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

You load this file, all is peachy.  Then you put point at the end
of the foo-1 defun, and hit C-M-x, and all is still peachy.

Now imagine you edit the ns form to say:

(ns foo.core
  (:require [bar.core]))

And _BEFORE_ reloading the file, hit C-M-x again , you get this
stack trace:

      Show: Clojure Java REPL Tooling Duplicates All  (27 frames hidden)

    2. Unhandled clojure.lang.Compiler$CompilerException
       Error compiling: /private/tmp/blah.clj:1:1

		     Compiler.java: 7239  clojure.lang.Compiler/load
			      REPL:    1  gocatch.job.job/eval37251
		     Compiler.java: 6782  clojure.lang.Compiler/eval
		     Compiler.java: 6745  clojure.lang.Compiler/eval
			  core.clj: 3081  clojure.core/eval
			  main.clj:  240  clojure.main/repl/read-eval-print/fn
			  main.clj:  240  clojure.main/repl/read-eval-print
			  main.clj:  258  clojure.main/repl/fn
			  main.clj:  258  clojure.main/repl
		       RestFn.java: 1523  clojure.lang.RestFn/invoke
	    interruptible_eval.clj:   53  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
			  AFn.java:  152  clojure.lang.AFn/applyToHelper
			  AFn.java:  144  clojure.lang.AFn/applyTo
			  core.clj:  630  clojure.core/apply
			  core.clj: 1868  clojure.core/with-bindings*
		       RestFn.java:  425  clojure.lang.RestFn/invoke
	    interruptible_eval.clj:   51  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
	    interruptible_eval.clj:  183  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
	    interruptible_eval.clj:  152  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
			  AFn.java:   22  clojure.lang.AFn/run
	   ThreadPoolExecutor.java: 1145  java.util.concurrent.ThreadPoolExecutor/runWorker
	   ThreadPoolExecutor.java:  615  java.util.concurrent.ThreadPoolExecutor$Worker/run
		       Thread.java:  744  java.lang.Thread/run

    1. Caused by java.io.FileNotFoundException
       Could not locate blah/core__init.class or blah/core.clj on
       classpath.

			   RT.java:  449  clojure.lang.RT/load
			   RT.java:  412  clojure.lang.RT/load
			  core.clj: 5866  clojure.core/load/fn
			  core.clj: 5865  clojure.core/load
		       RestFn.java:  408  clojure.lang.RestFn/invoke
			  core.clj: 5671  clojure.core/load-one
			  core.clj: 5711  clojure.core/load-lib/fn
			  core.clj: 5710  clojure.core/load-lib
		       RestFn.java:  142  clojure.lang.RestFn/applyTo
			  core.clj:  632  clojure.core/apply
			  core.clj: 5749  clojure.core/load-libs
		       RestFn.java:  137  clojure.lang.RestFn/applyTo
			  core.clj:  632  clojure.core/apply
			  core.clj: 5832  clojure.core/require
		       RestFn.java:  408  clojure.lang.RestFn/invoke
			  blah.clj:    1  foo.core/eval37255/loading--auto--
			  blah.clj:    1  foo.core/eval37255
		     Compiler.java: 6782  clojure.lang.Compiler/eval
		     Compiler.java: 6771  clojure.lang.Compiler/eval
		     Compiler.java: 7227  clojure.lang.Compiler/load
			      REPL:    1  gocatch.job.job/eval37251
		     Compiler.java: 6782  clojure.lang.Compiler/eval
		     Compiler.java: 6745  clojure.lang.Compiler/eval
			  core.clj: 3081  clojure.core/eval
			  main.clj:  240  clojure.main/repl/read-eval-print/fn
			  main.clj:  240  clojure.main/repl/read-eval-print
			  main.clj:  258  clojure.main/repl/fn
			  main.clj:  258  clojure.main/repl
		       RestFn.java: 1523  clojure.lang.RestFn/invoke
	    interruptible_eval.clj:   53  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
			  AFn.java:  152  clojure.lang.AFn/applyToHelper
			  AFn.java:  144  clojure.lang.AFn/applyTo
			  core.clj:  630  clojure.core/apply
			  core.clj: 1868  clojure.core/with-bindings*
		       RestFn.java:  425  clojure.lang.RestFn/invoke
	    interruptible_eval.clj:   51  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
	    interruptible_eval.clj:  183  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
	    interruptible_eval.clj:  152  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
			  AFn.java:   22  clojure.lang.AFn/run
	   ThreadPoolExecutor.java: 1145  java.util.concurrent.ThreadPoolExecutor/runWorker
	   ThreadPoolExecutor.java:  615  java.util.concurrent.ThreadPoolExecutor$Worker/run
		       Thread.java:  744  java.lang.Thread/run

Basically, CIDER is attempting to evaluate the entire new namespace form, instead of
just `(ns foo.core)'.

Why does this matter in practice?  Because it's quite common, and convenient, to repl
in to a remote server with a local file which has a NS definition incompatible with that
existing on the remote, and you want to add or redefine a function on the remote to do
a hotfix.  This CIDER behaviour at best fails with no ill effects, and at worse might
inadvertantly change the behaviour on the remote in unexpected ways.  [Please don't warn
me to not do this "dangerous" action from a version of the file which is "incompatible";
IMO, the lisp philosophy is that the programmer knows what he is doing; you let him do it.]

For example, SLIME under common lisp doesn't suffer from this problem.

Another example of brokenness: imagine loading this file:

    ================================================================
    (ns foo.core)

    (defn foo-1 []
      (println "cider is less than awesome! is namespace FOO"))

    (ns blah.core)

    (defn foo-1 []
      (println "cider is awesome in namespace BAR!"))

    #_
    (foo-1)
    ================================================================

And putting point at end of last line and hitting C-M-x.
What gets printed in the repl is:

   cider is less than awesome! is namespace FOO

I would personally have expected to print

   cider is awesome! is namespace BAR

because, as we know, cider is awesome in _any_ namespace.  :-)

I think CIDER should find the semantically correct namespace by keeping the
semantics of what LOAD does; i.e. find the first NS form above the form being
eval'ed, and only set *ns*; not try to re-evaluate all the (:require ...) forms etc.
If the User means to change the shape of the *ns*, he will C-M-x on the NS form itself.

   --Alain Picard

**Comment by expez** [comment]
> Basically, CIDER is attempting to evaluate the entire new namespace form, instead of
just `(ns foo.core)`.

You are calling `cider-eval-defun-at-point`.  If you read the docstring you'll see: 

 > Evaluate the current toplevel form, and print result in the minibuffer.
With DEBUG-IT prefix argument, also debug the entire form as with the
command `cider-debug-defun-at-point'.

In other words, this function is acting on the entire toplevel form containing point.  

You talk quite a bit about putting the cursor after things, which isn't really what's intended for a function which acts on the 'toplevel form around point'.  I'd say that behavior is undefined, though an argument might be made that when this function is called from toplevel it should act on the previous toplevel form.

Perhaps you are looking for `cider-eval-last-sexp`?  This is bound to <kbd> C-x C-e</kbd> and has this docstring:

> Evaluate the expression preceding point.
If invoked with a PREFIX argument, print the result in the current buffer.

**Comment by Malabarba** [comment]
@expez Maybe there's been a bit of confusion. I think he's complaining that the ns form gets reevaluated everytime he evaluates any other form in the buffer. `C-M-x` and `C-x C-e` should behave the same in that regard.

@alain-picard I've pushed a change to clojure-mode that will behave better in files with multiple ns's. While I've never seen this used anywhere (and I'm fairly sure it's considered bad style), it was a very minor change so I don't think there's a problem supporting it.

As for your first complain, I'm not sure it would be a good improvement. The situation you describe about connecting to a remote to load stuff on it on the fly seems... dangerous. But then, I don't work on this suff (yet), so what do *I* know? :-)

I can probably give you a hack to work around it.

**Comment by bbatsov** [comment]
> While I've never seen this used anywhere (and I'm fairly sure it's considered bad style), it was a very minor change so I don't think there's a problem supporting it.

I've only seen it in Riemann config files. :-) Still, it's worth handling it as best as possible, even if it's not very common.

**Comment by alain-picard** [comment]
@expez - I think you're completely misunderstanding my report.  The point isn't whether
I hit C-M-x within any form or C-c C-e at end of a form; the problem is that 
 1. evaluating the form has side effects larger than simply redefining the function (by potentially damaging the state of the current namespace object in a manner that was not desired) and 
 2. that the *wrong* namespace may accidentally get used!

@Malabarba 
As I wrote in my initial report:
>  [Please don't warn
> me to not do this "dangerous" action from a version of the file which is "incompatible";
> IMO, the lisp philosophy is that the programmer knows what he is doing; you let him do it.]

and I meant it.  I totally agree it's dangerous to splice in random forms from one environment
into another.  That's why you're supposed to know what you're doing.  You're usually doing this
at 3:00 AM while customers are screaming, which is why you don't need to fight your tool at
the same time trying to re-evaluate NS forms needlessly/dangerously.  I've been doing this
near on 20 years... so - yeah, I've screwed up (quite a) few times; however sometimes a man's
gotta do what a man's gotta do.  I gravitated to Lisp/clojure because it trusts the programmer.

I realize the multiple NS forms in a file is rare (and probably considered bad style in clojure), but
remember that this is only because of Java limitations that clojure inherits.  There's no good reason
why a filename and a path on disk should have anything whatsoever to do why what namespace
the file is in, and even less reason why a namespace's complete description should not be 
constituted of several files.  In practice, I do this all the time.  This wouldn't even raise an eyebrow
in Common Lisp  (which is why SLIME tries so hard to make sure it gets the *package*, the lisp
equivalent of *ns*, right before sending a form to the inferior process).

Anyway, this is all up to you guys now; I hope the problem description is clear enough.  Otherwise
just ping back and I'll try to clarify further.

Thanks!
   Alain

**Comment by Malabarba** [comment]
> I realize the multiple NS forms in a file is rare, but
remember that this is only because of Java limitations that clojure inherits. 

By the way, after you upgrade clojure-mode let me know if this aspect of your issue is fixed. 

> There's no good reason
why a filename and a path on disk should have anything whatsoever to do why what namespace
the file is in

Other than the fact that we're all human and appreciate an easy way to guess in which file to find a namespace. :-)
But then, your code should suit you first. 

> and even less reason why a namespace's complete description should not be 
constituted of several files.

This is not _that_ rare, and I've actually seen a couple of times. Even in core IIRC.

**Comment by alain-picard** [comment]
I have checked out and tested the new clojure-find-ns in the tip of clojure-mode.
It now works perfectly!  Thanks!

I also realize now that I apparently raised this issue on the wrong project;
it should have been clojure-mode, but I did not know this.  I apologize for 
any inconvenience caused.

--Alain
