### ISSUE TITLE
test-report pops up even when all tests pass if the report buffer already exists

### ISSUE THREAD

**Issue by Fabricationatorishnicatorist** [clojure-emacs/cider#1405]
The desired behavior would be for the report buffer to pop only on failed tests, while green simply prints the status to the minibuffer. 

When `*cider-test-report*` does not exist and a test run is green, the behavior is as just described.
However, if a test fails and report buffer appears, if I bury the buffer instead of killing it,  it
pops up again when I rerun the (fixed) tests - even if they are all green.

**Comment by bbatsov** [comment]
What's your cider version? This behaviour is controlled by the variable `cider-test-show-report-on-success` and by default its value is `nil`.

**Comment by Fabricationatorishnicatorist** [comment]
I'm on MELPA tip and the variable value is nil.
It does the right thing, but only if the buffer doesn't already exist.

**Comment by Malabarba** [comment]
This might be due to a recent patch that updates the buffer when all tests pass regardless of the variable's value. The patch was suppose to just update the buffer, though, not display it.

**Comment by Fabricationatorishnicatorist** [comment]
... you mean https://github.com/clojure-emacs/cider/pull/1402

**Comment by Malabarba** [comment]
Yep.
