### ISSUE TITLE
The test ns should be displayed in the minibuffer test status message

### ISSUE THREAD

**Issue by Fabricationatorishnicatorist** [clojure-emacs/cider#1406]
When customizing `cider-test-infer-test-ns` with a custom function, it would be helpful to know
which tests ran when there might be multiple places. This would also be consistent with
the test report which prominently features the test ns.

**Comment by bbatsov** [comment]
So, you want it to say `Running tests in some-ns...`  instead of `Testing...`, right?

Do you want this to be displayed in the test report in the minibuffer as well? I'm open to the idea, but I wonder what others think about it.

@expez @Malabarba any thoughts?

**Comment by Malabarba** [comment]
I agree completely. There's no reason the `Testing...` message needs to be so sucint.

**Comment by Fabricationatorishnicatorist** [comment]
> Do you want this to be displayed in the test report in the minibuffer as well?

Actually,  I meant only that because a quick test suite means the miniubffer  "Testing..." message gets clobbered immediately. So, once I get the results I just want some indication of what just ran.
