### ISSUE TITLE
cider-refresh with leiningen checkout dependencies?

### ISSUE THREAD

**Issue by alex-glv** [clojure-emacs/cider#1409]
I have followed the tutorial on concurrently developing a project  and project dependencies.
https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#checkout-dependencies

My project boots up, but every time I am refreshing the namespaces (cider-refresh) I get errors that some of the dependencies are not found. Those are checkout project dependencies that are unresolved.

I am not exactly sure what's exactly going under the hood, my question is, are they meant to work together? If not, is there a workaround?

Emacs 24.5,
CIDER 0.10.0snapshot (package: 20151025.1201) (Java 1.8.0_45, Clojure 1.7.0, nREPL 0.2.11)
Thank you.

**Comment by expez** [comment]
Did you figure this out @alex-glv?

The lack of response here most likely indicates that you're the first person to run into this problem.  If you solved it, it might be helpful for someone from the future to know how.

**Comment by jumarko** [comment]
I'm also experiencing this issue. It'll be great if someone have a solution for this.
