### ISSUE TITLE
Emacs not finding lein even if it is found on exec path

### ISSUE THREAD

**Issue by favetelinguis** [clojure-emacs/cider#1414]
Im running 24.5 on Windows 7 and im getting the following error message

The lein executable (specified by `cider-lein-command') isn't on your exec-path

However when i inspect the exec-path variable like so:
(describe-variable 'exec-path) I can find the value there:
 "C:/Users/me/.lein/bin"

I have also tried to put this in my init file to exact.
(add-to-list 'exec-path "C:/Users/me/.lein/bin")

But im still getting the same error.

Is there some know issues aroudn this or am I missing something?

**Comment by expez** [comment]
What is the value of `cider-lein-command`?  For me it is `lein`.  If you look in `"C:/Users/me/.lein/bin"` do you see a file there called `lein.bat`?

**Comment by favetelinguis** [comment]
When i do (print cider-lein-command)
i get:
"lein"
"lein"

That is lein is printed two times.

No in that folder there is a file that is called lein, having this path in cygwin alloves my to use lein in cygwin.

**Comment by expez** [comment]
Well there's your problem.  

You've installed lein for unix, which works fine in cygwin, but you've not installed lein for windows and that is the context in which your emacs is running.  Perhaps you can start emacs from cygwin and solve it that way if you really don't want to install lein for windows.

**Comment by favetelinguis** [comment]
That was the problem. Thanks for the help!
