### ISSUE TITLE
Include a tip for aligning annotations

### ISSUE THREAD

**Issue by OlegTheCat** [clojure-emacs/cider#1415]
Include instructions to make company align completion annotations to right side of the box.
To make this the following line should be added:
```(setq company-tooltip-align-annotations t)```

Otherwise popup box looks a bit ugly:

![selection_004](https://cloud.githubusercontent.com/assets/1105265/11132032/49f8746a-8996-11e5-8bbf-1abae81c84c4.png)

and it is not clear why is this happening, especially for company newcomers.

**Comment by expez** [comment]
@dgutov Perhaps the default value should be changed?

**Comment by dgutov** [comment]
@expez IME, it doesn't work as well when you're using the annotation for the arglist, which is what the built-in backends do (they ones that use annotations at all).

We'll probably include some light-weight markup in annotations to allow aligning a part of it to the left, and a part to the right, and remove this variable altogether, someday.

**Comment by bbatsov** [comment]
I think CIDER's documentation shouldn't contain configuration info for other packages. Interested users will just look up the package documentation anyways.
