### ISSUE TITLE
Cider complaining of wrong nrepl version

### ISSUE THREAD

**Issue by favetelinguis** [clojure-emacs/cider#1417]
Not sure what more I need to do, i have installed the latest of CIDER and run lein upgrade but still cider is complaning:

WARNING: CIDER requires nREPL 0.2.12 (or newer) to work properly

This is what lein deps :tree gives me but i dont know what i should to to fix this...
https://gist.github.com/favetelinguis/b5a6d5990fcf6a83c66e

Might be good to add something about this in the readme since i cant be the onlyone that has run into this problem?

**Comment by Malabarba** [comment]
Did you add nrepl to your deps? https://github.com/clojure-emacs/cider/blob/master/README.md#warning-saying-you-have-to-use-nrepl-0212

You may have to add a ^:replace before it to make sure it takes effect.

**Comment by favetelinguis** [comment]
Sorry that was the problem, finaly Cider is working fine. However im having some problems when i have huge outputs in the repl. It slows down the whole emacs and the only way to get emacs working fine again is to restat. Is this a known problem?

**Comment by bbatsov** [comment]
Yeah, it's a known problem. See https://github.com/clojure-emacs/cider/issues/1115
