### ISSUE TITLE
Newly opened buffers show up as modified after using cider-connect

### ISSUE THREAD

**Issue by bstiles** [clojure-emacs/cider#1421]
1. Enable global-prettify-symbols-mode.
2. Connect to a REPL via cider connect.
3. Open a Clojure file not currently visited by a buffer.

The new buffer shows as modified. If I save the file and compare it to its previous state, there are no actual changes to the content.

I don't know where the bug lies and would be happy to debug further if you have some suggestions for things I should look at.

The problem does not occur if I disable global-prettify-symbols-mode but do connect to a REPL via cider-connect. The problem also does not occur if I enable global-prettify-symbols-mode but don't connect to a REPL via cider-connect. It only happens if I enable global-prettify-symbols-mode AND have connected to a REPL via cider-connect (it doesn't have to be currently connected, it just has to have been connected previously in the emacs session).

I have only noticed this behavior recently (can't pinpoint when it started). I'm using CIDER 0.10.0snapshot (package: 20151114.848) (Java 1.8.0_66, Clojure 1.8.0-RC1, nREPL 0.2.12) on OS X 10.10.5 and emacs 24.5.1. I upgrade CIDER and other packages probably once or twice a week, or less.

**Comment by Malabarba** [comment]
Cider doesn't mess with prettify symbols mode. Clojure-mode does a little bit, but it shouldn't have anything to do with cider-connect. 

Do you have any configuration related to prettify symbols mode?

**Comment by bstiles** [comment]
I had added some additional symbols for clojure mode, but I disabled them restarted emacs and retested. The problem still occurred. I would imagine that cider-connect wouldn't directly mess with prettify, but it could make assumptions that don't hold in the presence of prettify's interaction with the buffer. There's also the CIDER middleware. Not sure what I should do to rule any of that out.

**Comment by Malabarba** [comment]
That's odd. I'll try to figure out what might be causing this.
Does anyone else have any ideas?

**Comment by bstiles** [comment]
Here's the contents of the buffer-undo-list variable immediately after opening a file when the problem occurs:

(nil
   (nil cider-locals nil 30 . 34)
   (nil cider-locals nil 27 . 30)
   (nil cider-locals nil 26 . 27)
   (nil cider-block-dynamic-font-lock nil 18 . 19)
   (nil cider-block-dynamic-font-lock nil 5 . 18)
   (nil cider-block-dynamic-font-lock nil 4 . 5)
   (nil cider-block-dynamic-font-lock nil 2 . 4)
   (nil cider-block-dynamic-font-lock nil 1 . 2)
   (t 22089 4115 0 0))

buffer-undo-list is nil in both non-failure cases after newly opening a file: 1) I disable prettify-symbols-mode altogether, but have cider-connect'ed; 2) I enable prettify-symbols-mode, but have not cider-connect'ed.

**Comment by expez** [comment]
fwiw I'm seeing this too.  I'm not using `connect` but `jack-in`.

**Comment by Malabarba** [comment]
Should be fixed now. Let me know if it worked.

**Comment by bstiles** [comment]
I no longer see the issue after updating CIDER. Thank you!
