### ISSUE TITLE
RET doesn't go to a new line if form is incomplete in REPL

### ISSUE THREAD

**Issue by chadhs** [clojure-emacs/cider#1422]
I'm using spacemacs and the clojure layer.

If I jack in `SPC m s i`
and then switch to the REPL `SPC m s s`
and then start writing a function that looks like this:
```
(defn cool-function []
```
and press return, I get an `unbalanced parens` error. screenshot: https://www.dropbox.com/s/xtu4y9c18otyntk/Screenshot%202015-11-14%2022.26.00.png?dl=0

`^ j` does work for entering down, but the docs say that if an expression is incomplete return should do so as well.

Let me know if you need any further info, thank you!

**Comment by chadhs** [comment]
FYI `^ j` works just dandy for now:
https://www.dropbox.com/s/4o1iss9b133a9mm/Screenshot%202015-11-14%2022.29.58.png?dl=0

**Comment by johngit22** [comment]
Not Bad. It loo Damm Good in fact, thanks.

**Comment by Malabarba** [comment]
This is because RET sends the form in the REPL, it never inserts newlines. 
I guess we could have it insert newlines when the form is incomplete, as that's sort of what a regular repl does.

**Comment by bbatsov** [comment]
Yeah, probably we should do this. Should pretty simple if we just use `check-parens` or something like this.

**Comment by Malabarba** [comment]
We already do that, it's just a matter of inserting a newline instead of complaining of the unbalance.

**Comment by chadhs** [comment]
@bbatsov @Malabarba or would it make more sense to use `⇧↩`, especially with smart parens strict mode enabled.  thoughts?

**Comment by bbatsov** [comment]
The `Shift + RET` keybinding is not that common in Emacs (and we already have `C-j`). I'm a paredit/smartparens user and I know I'm supposed to press `C-j`; probably other people are aware of this as well.

**Comment by chadhs** [comment]
@bbatsov :+1: yeah i agree that sounds good.  thanks for all your work; CIDER is an amazing experience even for a novice Clojure tinkerer like me.  ^_^
