### ISSUE TITLE
Add feature: TDD development

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/cider#1425]
Following @bbatsov suggestion [on Twitter](https://twitter.com/bbatsov/status/666962253586038784): would it be possible to add the great @Malabarba [TDD-like solution](http://endlessparentheses.com/test-driven-development-in-cider-and-emacs.html) to CIDER?

**Comment by bbatsov** [comment]
Yeah, it's totally possible to add it. I think we briefly discussed this with Artur and he suggested adding some config value to enable/disable this, which sounds pretty reasonable to me. I won't have time to add this before the schedule release, so it's up to @Malabarba to do this, if he has some time to spare.

**Comment by Malabarba** [comment]
I'm still trying to perfect that feature locally. It'll likely be added only after release.

**Comment by bbatsov** [comment]
Roget that!

**Comment by manuel-uberti** [comment]
Thanks guys. Take your time, of course. :+1:

**Comment by bbatsov** [comment]
@Malabarba any updates regarding this?

**Comment by Malabarba** [comment]
Do we have a name for it yet?

I see 4 ways this could go

- Run tests after save (this didn't work so well for me).
- Run tests after load-file.
- Run tests after any eval operation that doesn't error.
- Load-file after save, and optionally run tests after save.

**Comment by bbatsov** [comment]
> Do we have a name for it yet?

`cider-auto-test`? 

> I see 4 ways this could go
> 
> Run tests after save (this didn't work so well for me).

That's a bad idea for sure.

> Run tests after load-file.
> Run tests after any eval operation that doesn't error.

I'd go for this option.

> Load-file after save, and optionally run tests after save.

This might be a useful option for some people (not only in the context of running tests). I use load-file rarely when I develop and this is definitely not something I'd use.
