### ISSUE TITLE
Document using CIDER with Fighweel

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1427]
Figwheel is super popular awesomesauce but its usage with CIDER is somewhat unintuitive 

How to make this work is documented over at fighweel [here](https://github.com/bhauman/lein-figwheel/blob/master/doc/editor_repls.md#nrepl-middleware-cider-etc) but the information is somewhat hard to find.

At least one of our users ran into this: https://github.com/clojure-emacs/cider-nrepl/issues/272

**Comment by bbatsov** [comment]
Guess we can simply link to this from our README.

**Comment by bbatsov** [comment]
@expez The documentation was moved. Any idea where to?

**Comment by bbatsov** [comment]
Seems it's here now https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl

**Comment by Naomarik** [comment]
FWIW I still couldn't get it working with those docs, but that could be just me. If someone had an alternate/simplified version of this it might help others get going in the future.

**Comment by expez** [comment]
> FWIW I still couldn't get it working with those docs, but that could be just me.

Most likely this isn't just you.  There are a lot of moving parts involved in getting a clj environment going for emacs these days...

>  If someone had an alternate/simplified version of this it might help others get going in the future.

Pull-request welcome after you've asked someone in the know on `#clojure`, on freenode, or `clojurians`, on slack :)

**Comment by thwg** [comment]
I've gotten figwheel working with the following setup, currently:

profiles.clj:
```clojure
{:repl
 {:dependencies [[org.clojure/tools.nrepl "0.2.12"]
                 [com.cemerick/piggieback "0.2.1"]
                 [figwheel-sidecar "0.5.0-2"]]     ;; <-- important
  :plugins [[cider/cider-nrepl "0.11.0-SNAPSHOT"]]
  :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}}}
```

project.clj (*must* be under root, not under a separate profile, or in profiles.clj.  The reason for this is that since figwheel is not running from the lein context, it will only read project.clj, not merge anything):

```clojure
:figwheel { ... custom settings ... }
:cljsbuild { ... :figwheel {:on-jsload "name.space/func"} ... rest of build }
```

Customize the `cider-cljs-repl` variable:
```emacs-lisp
(cider-cljs-repl "(do (use 'figwheel-sidecar.repl-api) (start-figwheel!) (cljs-repl))")
```

If interested, I could create a minimal working example for the documentation.

**Comment by thwg** [comment]
As a side note, this only works with `cider-jack-in-clojurescript` (so that it runs `cider-cljs-repl` commands), and won't work with any variant of `cider-connect` that I'm aware.

**Comment by bbatsov** [comment]
@magnars recently documented this.
