### ISSUE TITLE
The new local var font-lock is unstable and distracting. 

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1429]
I was doing some coding the last couple of days and noticed that the way we prevent local variables from being dynamically font locked doesn't work too well. 

It goes away when you edit some code nearby, and then comes back when you evaluate something. It's quite distracting. 

I don't know if I'll come up with a better solution before release, but if I don't I think we should disable this.

**Comment by bbatsov** [comment]
OK, just revert the changes you made about this. It's not a big deal and people who don't like it can simply turn off the cider-powered font-locking.

**Comment by bbatsov** [comment]
On a related note - I really think we should font-lock the vars that are coming from clojure itself differently. I recall we discussed this a while back, but now with direct linking it's even more relevant than before. It might also be reasonable to font-lock dynamic vars differently.

**Comment by Malabarba** [comment]
> I really think we should font-lock the vars that are coming from clojure itself differently. 

You mean the core vars/fucntions/macros should have different faces from other var/functions/macros? 
Or do you mean we should extend what we do with clojure.core to other clojure namespaces? 

> now with direct linking it's even more relevant than before.

What's that? :-) 

> It might also be reasonable to font-lock dynamic vars differently

The compiler complains if a dynamic var is not named with earmuffs, so this can probably be handled by a regexp in clojure-mode (though it should be trivial to do with dynamic font locking too).

**Comment by bbatsov** [comment]
> You mean the core vars/fucntions/macros should have different faces from other var/functions/macros?

At least the vars & functions. E.g. `font-lock-built-in-face`. Unfortunately they didn't foresee different faces for different built-in things...

> What's that? :-)

https://groups.google.com/forum/#!topic/clojure/D8Bh5zmVL7c

> The compiler complains if a dynamic var is not named with earmuffs, so this can probably be handled by a regexp in clojure-mode (though it should be trivial to do with dynamic font locking too).

Forgot about the warnings - guess there's not much to be done there. :-)

**Comment by Malabarba** [comment]
Forgot to close this. I improved the logic on a recent commit and it's much better now.
