### ISSUE TITLE
Show explicit error messages when invoking commands with no ClojureScript support

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1432]
People are often wondering if some command is supposed to work with ClojureScript or not. In the interest of better UX we should raise proper errors when commands that don't work with ClojureScript are invoked in a ClojureScript connection. 

Does anyone happen to have a list of those commands?

**Comment by Malabarba** [comment]
> we should raise proper errors

Make that user-errors. :-)

**Comment by bbatsov** [comment]
Sure. :-) Does anyone have a list of the commands that don't work on ClojureScript?

**Comment by expez** [comment]
<kbd>C-c C-.</kbd> aka `cider-find-ns` doesn't work with cljs atm.  An issue is open in our middleware repo to remedy that situation.

I don't think any of the tracing stuff works either.

**Comment by bbatsov** [comment]
> Does the cider-test-* stuff work with cljs?

No, although there's a port of `clojure.test` for cljs, so I guess this is doable.

According to the caveats sections the following don't work:

* Grimoire lookup (don't remember why)
* Reloading
* Running tests
* Tracing
* Debugging

**Comment by bbatsov** [comment]
@cichli should we add something more to the list?

We should probably create individual tickets to implement the missing cljs functionality and start tackling the simplest tasks first.

**Comment by Malabarba** [comment]
By the way, mind if I take this on? I have some thoughts on how to integrate this with the dynamic dispatch.

**Comment by bbatsov** [comment]
Sure. Go ahead.

**Comment by cichli** [comment]
Nothing springs to mind that's missing from your list.

* Grimoire lookup should be trivial to do (I think all the code for that is in the client currently, and the client's CLJS-aware now).

* Reloading - not sure if we should raise an error or not here; I often use `cider-refresh` even while in a CLJS REPL to reload the underlying CLJ codebase. There do of course already exist great tools like Figwheel for doing live reloading of CLJS code.

* I have some (hacky) ideas for how to support running tests but haven't done any experiments yet.

* Tracing is semi-difficult but probably not too bad. I haven't looked too deeply at the `tools.trace` implementation but I don't think there are any blockers preventing it from being ported to CLJS.

* Debugging - I'm not too familiar with how the current debugger works but this strikes me as being kind of difficult. @Malabarba happy to assist with any questions you have here; maybe the direction we end up taking with `cider-test` support will give us a better idea of how to do this. There do exist good tools (source maps + Chrome debugger) for doing this already but the experience is nowhere near that of the CIDER debugger.

**Comment by Malabarba** [comment]
> happy to assist with any questions you have here; 

Helping out with #1416 would be a very good start. :-)
