### ISSUE TITLE
ns endswith '+' failed when using `cider-repl-set-ns` 

### ISSUE THREAD

**Issue by mut0u** [clojure-emacs/cider#1433]
If I define the namespace end with `+` like `myself.test+`, the cider-repl will fail to set the namespace when call the function `cider-repl-set-ns` (key C-c M-n) .

It will ignore the end `+` and change to the namespace `myself.test`.

**Comment by bbatsov** [comment]
I didn't even know that's a valid namespace name. Why would you name a ns like this?

**Comment by expez** [comment]
> I didn't even know that's a valid namespace name.

I think you can use any valid symbol to name an ns.

**Comment by Malabarba** [comment]
Regardless. The fix is probably just a regexp somewhere.

**Comment by bbatsov** [comment]
Indeed.
