### ISSUE TITLE
cider-jack-in is broken

### ISSUE THREAD

**Issue by codahale** [clojure-emacs/cider#1434]
Just installed `cider-20151125.913` and `cider-jack-in` is broken:

```
nREPL server started on 62368
nREPL: Establishing direct connection to localhost:62368 ...
nREPL: Direct connection established
error in process filter: pcase--u1: Unknown upattern `(quote request)'
error in process filter: Unknown upattern `(quote request)’
```

**Comment by Malabarba** [comment]
Thanks for the report. Just to be sure, what's your Emacs version? 



@bbatsov you have to use a backtick instead of  a regular quote.

**Comment by codahale** [comment]
24.5.1 on MacOS 10.11.1, installed via Homebrew.

**Comment by bbatsov** [comment]
@Malabarba I'll look into this.

**Comment by codahale** [comment]
Awesome! Thanks for the quick response — much appreciated.
