### ISSUE TITLE
Improve error display is cider-test

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1435]
Currently if you execute the following code:

you'll get the following report:

![image](https://cloud.githubusercontent.com/assets/103882/11425427/9172526c-945d-11e5-9f7e-baf7c4ceea09.png)

Having `actual` and `expected` doesn't make sense here. We should probably just have link to see exception in a stacktrace buffer (this is actual right now).

**Comment by jeffvalk** [comment]
With this, we've now subsumed essentially all of the test running functions of `clojure.test` into `cider-test` other than fixtures. It's compatible with the original, but it's not really the original anymore.

**Comment by cap10morgan** [comment]
Testing for v0.10 branch, but not sure how to reproduce. @bbatsov looks like the "following code" is missing?

**Comment by jeffvalk** [comment]
Previously, all test results showed an "expected" and "actual" value. Now these should be reported specifically to the outcome:

```clj
;; Error outside of assertion -> "error" only; no "expected" value
(deftest a
  (throw (Exception. "bam")))

;; Assertion error -> "expected" + "error"
(deftest b
  (is (= 1 (throw (Exception. "bam")))))

;; Assertion fails -> "expected" + "actual"
(deftest c
  (is (= 1 2)))
```

**Comment by cap10morgan** [comment]
Great, thanks @jeffvalk. This one looks good in v0.10.1 too.
