### ISSUE TITLE
Hang in CIDER 0.10.0-snapshot

### ISSUE THREAD

**Issue by ogis-hashi** [clojure-emacs/cider#1436]
Hi,

I test the following rx-clojure code in cider-emacs borrowed from the 
book  'Clojure Reactive Programming'.

``` clj
(ns rx-playground.core)
(require '[rx.lang.clojure.core :as rx])
(import '(rx Observable))

(import '(java.util.concurrent TimeUnit))

(def  repl-out *out*)
(defn prn-to-repl [& args]
  (binding [*out* repl-out]
    (apply prn args)))

(def subscription (rx/subscribe (Observable/interval 100 TimeUnit/MILLISECONDS)
                                prn-to-repl))
```

The last expression caused cider-repl hang. It worked outside emacs(i.e. 'lein repl').

This is my _Messages_ buffer:

``` text
nREPL: Direct connection established
Connected.  Happy hacking!
=> nil
=> #'rx-playground.core/obs
=> #'rx-playground.core/repl-out
=> #'rx-playground.core/prn-to-repl
=> #'rx-playground.core/subscription
error in process filter: nrepl--dispatch-response: nREPL: No response handler with id nil found
error in process filter: nREPL: No response handler with id nil found
```

The followings are project.clj and ~/.lein/profiles.clj
- project.clj

``` clj
(defproject rx-playground "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [io.reactivex/rxclojure "1.0.0"]])
```
- ~/.lein/profiles.clj

``` clj
{:user {:plugins [
                  [cider/cider-nrepl "0.10.0-SNAPSHOT"]
                  ]
        }
 }
```

This problem occurred using cider 0.10.0-snapshot (package: 20151126.732) but it worked with cider 0.9.1.

**Comment by tokomakoma123** [comment]
I made a repository as follows:

https://github.com/tokomakoma123/rx-playground

**Comment by jackrusher** [comment]
I've been getting random emacs lockups since upgrading to `cider-0.10.2` with `[cider/cider-nrepl "0.10.2"]` yesterday, all of them giving a `nREPL: No response handler with id nil found`. Sadly, I haven't been able to get a consistent reproducible setup. Do we suspect it's the same bug?

**Comment by jackrusher** [comment]
After upgrading to cider-11, I'm stilling get complete emacs lockups with `error in process filter: nREPL: No response handler with id nil found`. This occurs whenever I evaluate a form that generates an error. I would send along the contents of the nrepl message buffer(s), but emacs is locked hard. 😿

**Comment by drorbemet** [comment]
I just hit this issue too, and have to kill and restart emacs (with loss of data) and resort to an other repl.
CIDER 0.13.0snapshot (package: 20160422.1026)
[cider/cider-nrepl "0.12.0"]

**Comment by bbatsov** [comment]
Ah, those mysterious issues. In theory there shouldn't be requests without `id`s, so I'm quite puzzled how is this happening. Guess we can suppress this error, but in a way this would masquerade the real problem (which is yet unknown).

**Comment by bbatsov** [comment]
Next time one of you gets this - post here the relevant `*nrepl-messages ...*` log.

**Comment by jackrusher** [comment]
I would already have done, but it wedges emacs such that I have to kill and restart it. I've been able to narrow down the conditions a bit: it only (but always) happens when an exception is thrown in the `(draw)` function of a `quil` sketch. My guess is that the `draw` function is running in a different thread that lacks some nREPL-related thread-local bindings, and is thus passing `nil` where the `id` should be.

**Comment by pholz** [comment]
i also get the same behaviour with `quil`. `*nrepl-messages*` shows this:

    (<-- 
      out  "Exception in  :draw  function:  #error {\n :cause nil\n :via\n [{:type    java.lang.NullPointerException\n   :message nil\n   :at nil}]\n :trace\n []} \nstacktrace:  java.lang.NullPointerException: null\n at [empty stack trace]\n\n"
      session  "2d6a2166-9472-4ed2-b679-2ffcb9340b5e"
    )

**Comment by xiongtx** [comment]
Is this still an issue? Seems like it can be closed otherwise.

**Comment by bbatsov** [comment]
Yeah, it is. @xiongtx See https://github.com/clojure-emacs/cider/issues/2138 I never managed to figure out why this happens, but it seems it's a reproducible problem. I was meaning to fix it, by applying some default handler for such mysterious `out` and `err` messages, but I never got the time to do so. I don't like my "fix" idea, because it will mask the real problem, which I don't have time to debug... :-(
