### ISSUE TITLE
Error with company mode.

### ISSUE THREAD

**Issue by Ysmiraak** [clojure-emacs/cider#1439]
Just updated from melpa to the newest version, and company mode won't work with cider anymore. Error messages:

Company: An error occurred in auto-begin
Company: backend company-capf error "Wrong type argument: stringp, abort-on-input" with args (candidates list)

Any idea how to fix it?

**Comment by expez** [comment]
Hi, could you do `M-x toggle-debug-on-error <RET>` and paste the entire stack trace when the problem occurs?

**Comment by Ysmiraak** [comment]
Debugger entered--Lisp error: (wrong-type-argument stringp abort-on-input)
  nrepl-send-request(("op" "complete" "session" "ad4b4013-a02a-4d6c-9224-b5b3c6b58367" "ns" "user" "symbol" "lis" "context" ":same") #[257 "\301\300\"\207" [(dict) nrepl--merge] 4 "\n\n(fn RESP)"] abort-on-input)
  nrepl-send-sync-request(("op" "complete" "session" "ad4b4013-a02a-4d6c-9224-b5b3c6b58367" "ns" "user" "symbol" "lis" "context" ":same") abort-on-input nil)
  cider-nrepl-send-sync-request(("op" "complete" "session" "ad4b4013-a02a-4d6c-9224-b5b3c6b58367" "ns" "user" "symbol" "lis" "context" ":same") abort-on-input)
  cider-sync-request:complete("lis" ":same")
  cider-complete("lis")
  #[771 "\211\242\301=\206\n\211\302=?\205+r\303 \304!\203\305!\202p\262q\210\306\300!$)\207" [cider-complete boundaries metadata minibuffer-selected-window window-live-p window-buffer complete-with-action] 8 "\n\n(fn STRING PRED ACTION)"]("lis" nil t)
  all-completions("lis" #[771 "\211\242\301=\206\n\211\302=?\205+r\303 \304!\203\305!\202p\262q\210\306\300!$)\207" [cider-complete boundaries metadata minibuffer-selected-window window-live-p window-buffer complete-with-action] 8 "\n\n(fn STRING PRED ACTION)"] nil)
  completion-pcm--all-completions("" ("lis" point) #[771 "\211\242\301=\206\n\211\302=?\205+r\303 \304!\203\305!\202p\262q\210\306\300!$)\207" [cider-complete boundaries metadata minibuffer-selected-window window-live-p window-buffer complete-with-action] 8 "\n\n(fn STRING PRED ACTION)"] nil)
  completion-basic-all-completions("lis" #[771 "\211\242\301=\206\n\211\302=?\205+r\303 \304!\203\305!\202p\262q\210\306\300!$)\207" [cider-complete boundaries metadata minibuffer-selected-window window-live-p window-buffer complete-with-action] 8 "\n\n(fn STRING PRED ACTION)"] nil 3)
  #[257 "\300
\2368\301\242\302\242\303\304\242$\207" [2 ("lis") (#[771 "\211\242\301=\206\n\211\302=?\205+r\303 \304!\203\305!\202p\262q\210\306\300!$)\207" [cider-complete boundaries metadata minibuffer-selected-window window-live-p window-buffer complete-with-action] 8 "\n\n(fn STRING PRED ACTION)"]) nil (3) completion-styles-alist] 6 "\n\n(fn STYLE)"](basic)
  #[0 "\302\300\301\242\301\211\242A\240\210\242!\240\207" [#[257 "\300
\2368\301\242\302\242\303\304\242$\207" [2 ("lis") (#[771 "\211\242\301=\206\n\211\302=?\205+r\303 \304!\203\305!\202p\262q\210\306\300!$)\207" [cider-complete boundaries metadata minibuffer-selected-window window-live-p window-buffer complete-with-action] 8 "\n\n(fn STRING PRED ACTION)"]) nil (3) completion-styles-alist] 6 "\n\n(fn STYLE)"] ((partial-completion emacs22)) (nil)] 5 "\n\n(fn)"]()
  funcall(#[0 "\302\300\301\242\301\211\242A\240\210\242!\240\207" [#[257 "\300
\2368\301\242\302\242\303\304\242$\207" [2 ("lis") (#[771 "\211\242\301=\206\n\211\302=?\205+r\303 \304!\203\305!\202p\262q\210\306\300!$)\207" [cider-complete boundaries metadata minibuffer-selected-window window-live-p window-buffer complete-with-action] 8 "\n\n(fn STRING PRED ACTION)"]) nil (3) completion-styles-alist] 6 "\n\n(fn STYLE)"] ((partial-completion emacs22)) (nil)] 5 "\n\n(fn)"])
  completion--some(#[257 "\300
\2368\301\242\302\242\303\304\242$\207" [2 ("lis") (#[771 "\211\242\301=\206\n\211\302=?\205+r\303 \304!\203\305!\202p\262q\210\306\300!$)\207" [cider-complete boundaries metadata minibuffer-selected-window window-live-p window-buffer complete-with-action] 8 "\n\n(fn STRING PRED ACTION)"]) nil (3) completion-styles-alist] 6 "\n\n(fn STYLE)"] (basic partial-completion emacs22))
  completion--nth-completion(2 "lis" #[771 "\211\242\301=\206\n\211\302=?\205+r\303 \304!\203\305!\202p\262q\210\306\300!$)\207" [cider-complete boundaries metadata minibuffer-selected-window window-live-p window-buffer complete-with-action] 8 "\n\n(fn STRING PRED ACTION)"] nil 3 nil)
  completion-all-completions("lis" #[771 "\211\242\301=\206\n\211\302=?\205+r\303 \304!\203\305!\202p\262q\210\306\300!$)\207" [cider-complete boundaries metadata minibuffer-selected-window window-live-p window-buffer complete-with-action] 8 "\n\n(fn STRING PRED ACTION)"] nil 3)
  company-capf(candidates "lis")
  apply(company-capf (candidates "lis"))
  #[0 "\302	!\203\303	\300\"\207\303\304	\300#\207" [(candidates "lis") company-backend functionp apply company--multi-backend-adapter] 4 "\n\n(fn)"]()
  funcall(#[0 "\302	!\203\303	\300\"\207\303\304	\300#\207" [(candidates "lis") company-backend functionp apply company--multi-backend-adapter] 4 "\n\n(fn)"])
  company-call-backend-raw(candidates "lis")
  company--fetch-candidates("lis")
  company-calculate-candidates("lis")
  #[0 "\n\203	\nC\202\n\211\205\233\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\224\314\300\242!\203\216\315\300\242!\211\301\316\f!\240\210\301\242:\204w
\203i\317\320!\210\301\242\310=\203\216\321\322!\210\202\216
\203\300\242\323\301\242!\210\324\325\326 \"\210\327\330!\210\331\332\301\242\"\210A\266\202\202\n\207" [("lis") (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" company-cancel unique company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix] 6 "\n\n(fn)"]()
  funcall(#[0 "\n\203	\nC\202\n\211\205\233\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\224\314\300\242!\203\216\315\300\242!\211\301\316\f!\240\210\301\242:\204w
\203i\317\320!\210\301\242\310=\203\216\321\322!\210\202\216
\203\300\242\323\301\242!\210\324\325\326 \"\210\327\330!\210\331\332\301\242\"\210A\266\202\202\n\207" [("lis") (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" company-cancel unique company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix] 6 "\n\n(fn)"])
  company--begin-new()
  company--perform()
  #[0 "\301 \210\207" [company-candidates company--perform] 1 "\n\n(fn)"]()
  funcall(#[0 "\301 \210\207" [company-candidates company--perform] 1 "\n\n(fn)"])
  company-auto-begin()
  company-idle-begin(#<buffer *cider-repl localhost*> #<window 6 on *cider-repl localhost*> 33 100)
  apply(company-idle-begin (#<buffer *cider-repl localhost*> #<window 6 on *cider-repl localhost*> 33 100))
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 22107 56 672072 nil company-idle-begin (#<buffer *cider-repl localhost*> #<window 6 on *cider-repl localhost*> 33 100) nil 0])

**Comment by Ysmiraak** [comment]
It seems to be some problem with nrepl. When I try cider-quit, the nrepl doesn't close properly:

Debugger entered--Lisp error: (error "Sync nREPL request timed out (op close session ddb1ecc8-c664-42d5-aa47-31c744e736fc)")
  signal(error ("Sync nREPL request timed out (op close session ddb1ecc8-c664-42d5-aa47-31c744e736fc)"))
  error("Sync nREPL request timed out %s" ("op" "close" "session" "ddb1ecc8-c664-42d5-aa47-31c744e736fc"))
  nrepl-send-sync-request(("op" "close" "session" "ddb1ecc8-c664-42d5-aa47-31c744e736fc") #<buffer *cider-repl localhost*<2>>)
  nrepl-sync-request:close(#<buffer *cider-repl localhost*<2>> "ddb1ecc8-c664-42d5-aa47-31c744e736fc")
  cider--close-buffer(#<buffer *cider-repl localhost*<2>>)
  cider--close-connection-buffer(#<buffer *cider-repl localhost*<2>>)
  cider--quit-connection(#<buffer *cider-repl localhost*<2>>)
  cider-quit(nil)
  #<subr call-interactively>(cider-quit nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> cider-quit nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (cider-quit nil nil))
  call-interactively(cider-quit nil nil)
  command-execute(cider-quit)

**Comment by Ysmiraak** [comment]
The nrepl I'm using is [cider/cider-nrepl "0.10.0-SNAPSHOT"]. Should I be using some other release?

**Comment by Malabarba** [comment]
I ran into the same thing earlier. I fixed it but forgot to push. Pushing now.

**Comment by Ysmiraak** [comment]
Thanks a lot!
