### ISSUE TITLE
Variable to configure behavior of cider-result buffer

### ISSUE THREAD

**Issue by joerupen** [clojure-emacs/cider#1441]
I use a dual monitor setup on emacs, showing the `*cider-result*` buffer on one screen and the code buffers and repl on the other screen. When I evaluate `cider--pprint-last-sexp` , it always opens a `*cider-result*` buffer on the same screen I am coding on. I couldn't find a variable to customize this behavior. Maybe you are considering adding such a feature, or you could give me a hint and I will happily contribute a pull request.

**Comment by Malabarba** [comment]
Does that happen even if the results buffer is already being displayed on the other screen?

**Comment by joerupen** [comment]
Yes, also then

**Comment by Malabarba** [comment]
OK. Then I'm marking this as a bug. Displaing on a new window a buffer that's already visible shouldn't happen.

**Comment by joerupen** [comment]
ok, thanks. I was using the 0.10-SNAPSHOT version, then I downgraded to 0.9.1 version and it still occurs. I can't remember exactly, but I think it didn't happen in an earlier version
