### ISSUE TITLE
Cides doesn't quit gracefully.

### ISSUE THREAD

**Issue by Ysmiraak** [clojure-emacs/cider#1442]
When I call cider-quit, it fires this error, and I have to kill the process. Could you please look into this?

Debugger entered--Lisp error: (error "Sync nREPL request timed out (op close session 7d466de4-9147-4a08-945d-ff384f59d9d4)")
  signal(error ("Sync nREPL request timed out (op close session 7d466de4-9147-4a08-945d-ff384f59d9d4)"))
  error("Sync nREPL request timed out %s" ("op" "close" "session" "7d466de4-9147-4a08-945d-ff384f59d9d4"))
  nrepl-send-sync-request(("op" "close" "session" "7d466de4-9147-4a08-945d-ff384f59d9d4") #<buffer *cider-repl animunculi*>)
  nrepl-sync-request:close(#<buffer *cider-repl animunculi*> "7d466de4-9147-4a08-945d-ff384f59d9d4")
  cider--close-buffer(#<buffer *cider-repl animunculi*>)
  cider--close-connection-buffer(#<buffer *cider-repl animunculi*>)
  cider--quit-connection(#<buffer *cider-repl animunculi*>)
  cider-quit(nil)
  #<subr call-interactively>(cider-quit record nil)
  ad-Advice-call-interactively(#<subr call-interactively> cider-quit record nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (cider-quit record nil))
  call-interactively(cider-quit record nil)
  command-execute(cider-quit record)
  execute-extended-command(nil "cider-quit")
  smex-read-and-run(("toggle-debug-on-error" "package-list-packages" "flyspell-buffer" "R" "mkdir" "eshell" "revert-buffer" "magit-status" "replace-string" "customize-group" "linum-mode" "neotree-toggle" "package-install" "load-theme" "emacs-init-time" "comment-or-uncomment-region" "goto-line" "comment-box" "flycheck-mode" "benchmark-init/show-durations-tree" "describe-mode" "visual-line-mode" "flyspell-mode" "powerline-center-theme" "projectile-global-mode" "markdown-export-pdf" "powerline-default-theme" "ido-mode" "speedbar" "powerline-reset" "yas-global-mode" "mc/mark-all-dwim" "cider-repl-clear-buffer" "auto-fill-mode" "whitespace-cleanup" "global-flycheck-mode" "neotree" "company-mode" "ispell-message" "projectile-mode" "projectile-remove-known-project" "flush-lines" "powerline-revert" "ido-toggle-prefix" "flycheck-clojure-setup" "upcase-initials-region" "cd" "R-mode" "tabify" "js2-mode" ...))
  smex()
  #<subr call-interactively>(smex nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> smex nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (smex nil nil))
  call-interactively(smex nil nil)
  command-execute(smex)

**Comment by Malabarba** [comment]
Hi. Could you tell us what's your system, Emacs version, cider version, and how do you start cider?

**Comment by Ysmiraak** [comment]
Hi, my system is OS X 10.11.1, emacs version 24.5.1, with cider from melpa (last updated yesterday), and I start cider from clojure mode with C-c M-j.

**Comment by bbatsov** [comment]
What's in the `*nrepl-messages*` buffer for the session in question? The only thing that could cause such an issue is probably trying to close an non-existing session or something like this.

**Comment by Malabarba** [comment]
I can reproduce this too. We probably messed up something basic.

**Comment by Malabarba** [comment]
Hm. Apparently, plist-get uses `eq`. =/

**Comment by Ysmiraak** [comment]
You guys are awesome.

**Comment by bbatsov** [comment]
> Hm. Apparently, plist-get uses eq. =/

That's lame. We should probably start using `map.el`.

**Comment by Malabarba** [comment]
> That's lame. We should probably start using map.el.

Well, other parts of the code use lax-plist-get, I just wasn't aware. :P
And sadly map.el doesn't support plists (you can't practically distinguish them from alists). So we'd have to switch to another system in that case.

**Comment by bbatsov** [comment]
I believe plists make sense only for keyword keys - otherwise they look pretty odd overall. I'm definitely open to improving the data structures we use for requests & responses.

**Comment by Malabarba** [comment]
I personally like alists (unless it's so large that it should be a hashmap). In this situation nrepl-dbind-response could be replaced with let-alist.
But the current system works well enough that I'm not motivated to change it.

**Comment by bbatsov** [comment]
Makes sense. Getting rid of `nrepl-dbind-response` has been on my radar for a while now.
