### ISSUE TITLE
Cider 20151129.745 doesn't close repl buffer

### ISSUE THREAD

**Issue by kostafey** [clojure-emacs/cider#1443]
Cider `20151129.745` doesn't close `*cider-repl <project-name>*` buffer on `cider-quit`. 

e.g.
`M-x cider-quit`
`M-x cider-jack-in`
`REPL buffer already exists (*cider-repl <project-name>*). Do you really want to create a new one?`

**Comment by Malabarba** [comment]
Try updating cider. I pushed a change today that was related to this.

**Comment by kostafey** [comment]
Exactly. Thank you!
