### ISSUE TITLE
Possible indentation issue

### ISSUE THREAD

**Issue by aviad** [clojure-emacs/cider#1451]
on CIDER 0.8.2, GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) compiled locally on ubuntu 14.04.3 LTS this happens:
```clojure
(cond
  (:alls-good) :here
  (and (:also) (:here)) :ok
  (but (:this)
       (:that)) :causes
       (:bad :indent "Should be indented to \"but\" sexp") :<)
```

**Comment by Malabarba** [comment]
Update clojure-mode. :-) And it wouldn't hurt to update cider too, you're several releases behind.

**Comment by aviad** [comment]
thanks!
