### ISSUE TITLE
ANSI coloring in REPL buffer is broken

### ISSUE THREAD

**Issue by rfkm** [clojure-emacs/cider#1452]
![cider](https://cloud.githubusercontent.com/assets/857162/11607774/c6d6c5be-9b97-11e5-83d7-a91310a8171c.png)

### How to reproduce

1. Interactively eval the following code:

```clj
  (println "foo")
  (println "\u001b[31mbar\u001b[0m")
  (println "baz")
```

2. Then you will see the following output in REPL buffer:

```
foo  <-- default face
bar  <-- red face
baz  <-- red face(!)
user>
```

### Cause

This is because new output of interactive-eval extends an overlay for ANSI coloring created before.

The following is a part of output of <kbd>C-u C-x =</kbd> at 'r' of 'bar' after evaluating `(println "\u001b[31mbar\u001b[0m")`:

```
There is an overlay here:
 From 1 to 4
  face                 (foreground-color . "#fb4934")
  modification-hooks   (ansi-color-freeze-overlay)
```

Then, the following is new one after evaluating `(println "baz")`:

```
There is an overlay here:
 From 1 to 8
  face                 (foreground-color . "#fb4934")
  modification-hooks   (ansi-color-freeze-overlay)
```

It cannot be probably said that it is due to CIDER because I suspect this is ansi-color's problem.
I think `ansi-color-freeze-overlay` [should prevent overlays from being extended](https://github.com/emacs-mirror/emacs/blob/acfb5cd0353406784f085ddb6edfb0d0587048c8/lisp/ansi-color.el#L488-L514) at the first place.
I've actually confirmed it works by modifying ansi-color to use `insert-behind-hooks` instead of `modification-hooks`.

However, I think it is not so difficult to introduce a workaround for this on CIDER's side.
For example, it seems to work for me to use `insert` instead of `insert-before-markers` [here](https://github.com/clojure-emacs/cider/blob/5cd56ce76bdc4b0c50962ce626521133fb9e6edb/cider-repl.el#L471) though I'm not sure whether this cause other problems.
(BTW, cider-repl-output-start/cider-repl-output-end seems not to work but it is another issue.)

I'm a novice at elisp (and CIDER internals, of course), so I would be happy if someone investigate this problem further.

**Comment by Malabarba** [comment]
I think the reason why we use `insert-before-markers` is to ensure that the `input-start` marker stays after the inserted output. So that might break if we change that.
However, this whole section of our code looks rather complicated, so maybe it would be good to trim it down a bit. Why do we need so many markers anyway? :-P

**Comment by bbatsov** [comment]
This code was mostly copy pasted from Slime. I guess it's time to rework
it.

**Comment by rfkm** [comment]
I think it does not affect `cider-repl-input-start-mark` because `bol` is `t` only when called via interactive-eval and `position` is determined by `(cider-repl--end-of-line-before-input-start)` which is always before `cider-repl-input-start-mark`.
Yeah, it's not too much to say that it accidentally works even if it's true. :P

Another hacky but more reliable way is manually to add a hook to overlays created by `ansi-color-apply-on-region`.
```elisp
(defun cider-repl--emit-interactive-output (string face)
  "Emit STRING as interactive output using FACE."
  (with-current-buffer (cider-current-repl-buffer)
    (let ((pos (cider-repl--end-of-line-before-input-start))
          (string (replace-regexp-in-string "\n\\'" "" string)))
      (cider-repl--emit-output-at-pos (current-buffer) string face pos t)
      (ansi-color-apply-on-region pos (point-max))

      ;; added
      (dolist (ov (overlays-at (1- (cider-repl--end-of-line-before-input-start))))
        (when (member #'ansi-color-freeze-overlay (overlay-get ov 'modification-hooks)) ; ensure ov is crated by ansi-color
          (unless (member #'ansi-color-freeze-overlay (overlay-get ov 'insert-behind-hooks))
            (push #'ansi-color-freeze-overlay (overlay-get ov 'insert-behind-hooks))))))))
```

**Comment by bbatsov** [comment]
PR welcome. :-)
