### ISSUE TITLE
"Please, install (or update) cider-nrepl" with cider-connect but not cider-jack-in

### ISSUE THREAD

**Issue by WorldsEndless** [clojure-emacs/cider#1454]
I am making a web app (Luminus, if it matters) that starts up REPL servers as part of "lein run". I consistently use the latest stable versions of Cider, in Emacs 24.5. However, whenever I use cider-connect (C-c M-c) my REPL is only partially functional, and starts with the following top-matter:

>; CIDER 0.10.0 (package: 20151204.303) (Java 1.8.0_65, Clojure 1.7.0, nREPL 0.2.12)
>WARNING: The following required nREPL ops are not supported: 
>  apropos classpath complete eldoc format-code format-edn info inspect-pop inspect-push inspect-refresh macroexpand ns-list ns-vars ns-path refresh resource stacktrace toggle-trace-var toggle-trace-ns undef
>  Please, install (or update) cider-nrepl 0.10.0 and restart CIDER

When I ignore the servers created by the app and just run cider-jack-in, I do not get the warnings. Is there a reason for the different behavior?

**Comment by bbatsov** [comment]
See https://github.com/clojure-emacs/cider#using-embedded-nrepl-server
