### ISSUE TITLE
highlighting despite disabled global-font-lock-mode 

### ISSUE THREAD

**Issue by atstp** [clojure-emacs/cider#1456]
My init file has `(global-font-lock-mode 0)` because my color vision isn't great and the slight differences I can make out are more distracting than useful -- but that's just a pity party backstory/use-case, the more applicable stuff is next.

The gist of it is that I'm getting some unwanted/unprompted highlighting.  

So far I've noticed it with `C-c M-j`, right after the repl opens up, and load(eval)ing a buffer with `C-c C-k`.  My previously unhighlighted clojure code becomes highlighted.  When I switch to the recently highlighted window and run `M-x font-lock-mode` it shows `Font-Lock mode enabled` with no other visible change. Running `M-x font-lock-mode` a second time removes the highlighting and shows `Font-Lock mode disabled`, returning things to normal.

Another observation, when the highlighting shows, if I edit code in one of the recently highlighted windows, the new text I add is _not_ highlighted.

Is there anything I can do to keep things unhighlighted?

In the grand scheme of things, I guess this checks in as a cosmetic edge-case, so anything on the hack-fix spectrum would be great, thanks!

`emacs --version` says I'm using `GNU Emacs 24.3.1` on Ubuntu 14.04.3 and cider's promt prints `; CIDER 0.10.0 (package: 20151204.303) (Java 1.8.0_45-internal, Clojure 1.7.0, nREPL 0.2.12)`

**Comment by Malabarba** [comment]
I'll look into this. Cider shouldn't do any highlighting if font-lock-mode is turned off.

**Comment by avli** [comment]
+1

**Comment by Malabarba** [comment]
Fixed locally. Will push when I'm back from holiday.

**Comment by avli** [comment]
@Malabarba Many thanks!
