### ISSUE TITLE
Add support for CLJ and CLJS sibling scratch buffers.

### ISSUE THREAD

**Issue by thwg** [clojure-emacs/cider#1459]
When working on a ClojureScript project, I usually do most of my work in scratch buffers rather than at the REPL.  I would find it handy to allow scratch buffers (created by `M-x` `cider-scratch`) to send the input to the correct process based on the major mode of the scratch buffer.

Current behavior (in a ClojureScript project) after `cider-jack-in-clojurescript` and `cider-scratch` is that the major mode is `clojure-mode`, but it is connected to the `cljs` process.  There doesn't appear to be a way to connect it to the `clj` process or have a separate scratch buffer for each.

**Comment by expez** [comment]
We should definitely improve this, but for now you can call `cider-rotate-connection` to switch the default connection.

**Comment by Malabarba** [comment]
On the topic of how to implement this, I think we should change the code that checks file extension to instead check the major-mode. I believe that would be more robust and would solve this issue.
