### ISSUE TITLE
Implement some font-locking for traced vars/namespaces (similar to that for instrumented vars)

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1460]
It'd be nice if we could see at a glance which are the traced vars and namespaces in our code. We have similar code for instrumented stuff, so I guess we can extend the idea a bit further. 

@Malabarba would you like to have a stab at this or point other people to the relevant code?

**Comment by Malabarba** [comment]
What's a traced var? :)

**Comment by Malabarba** [comment]
It's very easy, if anyone wants to try. (I'm currently relocating, so it'll take me a while to do).

1. Add `:clojure.tools.trace/traced` to the list of tracked keywords in `track_state.clj`.
2. Add some code to `cider-mode.el`. This should be a trivial copy-paste of the code that font-locks instrumented or deprecated vars. Just search the file for `"instrumented"`.

**Comment by bbatsov** [comment]
Insert those two somewhere:

```
(defn fact-rec [n]
  (if (= n 1)
    1
    (* n (fact-rec (dec n)))))

(defn fibo-rec [n]
  (case n
    0 0
    1 1
    (+ (fibo-rec (dec n)) (fibo-rec (- n 2)))))
```

And do `C-c M-t v` for one of the var names. Afterwards evaluate `fibo-rec 10` or something and you'll see. More screencast material. ;-)

**Comment by bbatsov** [comment]
Oh, you've deleted the original comment. :-)

**Comment by Malabarba** [comment]
True. I had no idea cider had an interface for this. :-)

**Comment by bbatsov** [comment]
Damn - Mr. Anderson messes up the metadata :mranderson046.toolstrace.v0v7v9.clojure.tools.trace/traced

@benedekfazekas I wonder what to do about this. I definitely don't want to make the code aware of Mr. Anderson.

**Comment by benedekfazekas** [comment]
will have a look. code is already aware of mranderson tho: https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/ns.clj#L13

**Comment by bbatsov** [comment]
Yeah, but this is not exactly the same. Btw, did you add some way to customize the ns prefix? At least I can make it `cider-something`, so I wouldn't have to check whether a key ends with some suffix.

**Comment by benedekfazekas** [comment]
yup, you can use `:project-prefix yourprefix` when you run `source-deps` lein task

**Comment by bbatsov** [comment]
@Malabarba I finally got to test this and you were right. :-)

While this works, however, something seems to be wrong. The font-lock doesn't appear immediately after doing the tracing, but only after evaluating something afterwards. Guess something else has to be changed in the middleware.

**Comment by Malabarba** [comment]
Yes. We need to add `trace` to the list of ops that the state tracker hooks on. I think the variable is called something like `ops-that-can-eval`.

**Comment by bbatsov** [comment]
Guess we should be solid now.
