### ISSUE TITLE
Highlight occurrences of symbols and alias usages

### ISSUE THREAD

**Issue by robert-stuttaford** [clojure-emacs/cider#1461]
When I place my cursor on a def'd var or a local symbol, I use https://www.gnu.org/software/emacs/manual/html_node/emacs/Highlight-Interactively.html with a custom `idle-highlight` face colour to colourise the background of all the occurrences of that symbol.

It would be great if CIDER could support this natively, and also support the highlighting of all the places where a required alias is used.

For example I point at `str` in `[clojure.string :as str]`, and it highlights all the occurrences of `str/<something>` in the file.

**Comment by bbatsov** [comment]
@Malabarba Sounds like something that'd be a nice addition for `cider-mode` (which some flag to disable it). I think this shouldn't be hard to do.

**Comment by Malabarba** [comment]
Shouldn't be hard at all. We could implement this (and a number of other useful feedback) with an idle-timer.

**Comment by Malabarba** [comment]
I'm not even sure if we need cider for this. Could possibly go into clojure-mode.

**Comment by bbatsov** [comment]
We can't use `clojure-mode` - you won't be certain what a symbol resolves to...

**Comment by Malabarba** [comment]
Do you mean for `:refer`s? Because for `:as` requirements we could just use a regexp.

**Comment by Malabarba** [comment]
Anyway, I think this would go better in cider too.

**Comment by robert-stuttaford** [comment]
hi-lock-mode works fine for straight-up symbol hilights – so potentially no need to re-invent anything there. It's really the alias case I'm after :-)

**Comment by bbatsov** [comment]
`hi-lock-mode` simply highlights some text in the buffer. It has no notion of a var, local, namespace, etc. You can't do proper highlighting without doing some introspection and this is why I believe it's important to do all of this highlighting directly in cider.

**Comment by bbatsov** [comment]
I wonder how to be best approach this - perhaps we should just look for symbols that are the same in the buffer and try to resolve them to see if they are a match or not. This will be simple, but it probably won't be very efficient.

**Comment by Malabarba** [comment]
My first thought is "what do we want to highlight?". 

- Marking all occurrences of a local in the current `defn` would be the nicest feature to me.
- I'm still trying to understand how it would work to highlight all usages of a namespace alias (or all usages of a var) automatically. If it's something that happens automatically when I place cursor on the `str` alias, would it vanish automatically when I move the cursor again?  
  I imagine many occurrences are likely to be beyond the visible part of the buffer (and scrolling to view them would vanish the highlight). So maybe the highlight should be somehow semi-permanent? We could have a command to make it permanent, but how can we teach users about the key?

**Comment by bbatsov** [comment]
> Marking all occurrences of a local in the current defn would be the nicest feature to me.

Agreed. Although for vars it makes some sense to highlight them in the entire namespace. Guess this can be configurable.

> I imagine many occurrences are likely to be beyond the visible part of the buffer (and scrolling to view them would vanish the highlight). So maybe the highlight should be somehow semi-permanent? We could have a command to make it permanent, but how can we teach users about the key?

Exactly - normally this would happen automatically, but we can add some command about sticky highlighting. The stuff with teaching the users is easy - if we do it by the 11th I'll include it my next CIDER presentation. :-)

We can use our metadata handling functionality to easily highlight some vars, but I'm so sure what we can do about the locals.

**Comment by Malabarba** [comment]
Yeah, we can pretty reliably highlight vars thanks to the state tracker. But we can highlight locals semi reliably too, thanks to the code we already have that prevents dynamic font locking of locals.

**Comment by bbatsov** [comment]
Sounds like a plan to me. Would you volunteer to tackle this? :-)

**Comment by Malabarba** [comment]
I'll keep it in mind, but I don't think I'll have time for it before the 11th. :-(

**Comment by bbatsov** [comment]
No problem. I might do a lightning talk at ClojureD a couple of weeks later. ;-)

**Comment by bbatsov** [comment]
@Malabarba any chance you can take a stab at this in the foreseeable future?

**Comment by Malabarba** [comment]
I still think it would be nice to have, and I've decided to get back to OSS this week, but this specific issue is not my topmost priority so it may take me a while. :)

**Comment by bbatsov** [comment]
OK. It's definitely not urgent. It'd be nice to see more of you in the realm of CIDER. :-)

I haven't been doing much OSS work myself lately. Had some pretty quiet months since April, hopefully I'll be able to do more OSS work until the end of the year.

**Comment by rgkirch** [comment]
For anyone who finds they way here, like I did, I'll save you a little time and link to a package that does this the "dumb" way.
https://melpa.org/#/idle-highlight-mode
