### ISSUE TITLE
Don't ask users whether to associate connections

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1463]
We should just assume that the user is creating the connection from inside the project, and save a lot of people some confusion. And say on the command's docstring (and the readme instructions) that the command should be invoked from within the project.
And then have a custom option to not use that assumption

**Comment by bbatsov** [comment]
The new default is - if you're in a project, use it, if not - prompt for a project. 

Btw, an even better solution would be to insert the project dir (if available) in the nREPL session description.
