### ISSUE TITLE
Improve travis setup and add some test coverage

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1464]
Here are some ideas - https://github.com/chrisbarrett/swift-mode/pull/124

**Comment by AdrieanKhisbe** [comment]
Hey @bbatsov, 

I'll be pleased to  guide you through [cask-package-toolset](https://github.com/AdrieanKhisbe/cask-package-toolset.el) to improve `cider` build :)

**Comment by Malabarba** [comment]
I'm lost here even after reading the linked thread. What are these ideas?

**Comment by AdrieanKhisbe** [comment]
I think we does, but I let @bbatsov confirm :)

**Comment by bbatsov** [comment]
Yeah, more or less. I'm not sure if `ert-runner` would bring us some benefits, but using containers means faster builds and some coverage report would be quite useful.

**Comment by bbatsov** [comment]
These days I think that adopting something like https://github.com/jorgenschaefer/emacs-buttercup makes more sense. ert's too basic and the resulting test structure ain't pretty.

**Comment by AdrieanKhisbe** [comment]
@bbatsov Totally legit! 
[that reminds me and I should invest some time to improve https://github.com/AdrieanKhisbe/cask-package-toolset.el so that it's more flexible (eg. for tests) , and propose some **buttercup** :wink: ]
