### ISSUE TITLE
FileNotFound when compiling cider/nrepl/middleware/pprint.clj

### ISSUE THREAD

**Issue by papachan** [clojure-emacs/cider#1465]
Hi. Recently i have this error when i try to launch cider 0.11.0 with cider-nrepl 0.11.0

```
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate mranderson046/fipp/v0v6v3/fipp/edn__init.class or mranderson046/fipp/v0v6v3/fipp/edn.clj on classpath: , compiling:(cider/nrepl/middleware/pprint.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7142)
```

My project clj and profiles.clj file are really basic.
```
{:user {:plugins [[cider/cider-nrepl "0.11.0-SNAPSHOT"]
                  [lein-cljs "0.2.2"]
                   [refactor-nrepl "1.2.0-SNAPSHOT"]]
        :dependencies [[org.clojure/clojure "1.7.0"]
                       [org.clojure/tools.nrepl "0.2.12"]
                       [acyclic/squiggly-clojure "0.1.2-SNAPSHOT"]]}}
```

**Comment by cichli** [comment]
If you run `lein deps :tree` in the project in question, is Clojure 1.7 definitely the version being used?

**Comment by papachan** [comment]
Yeah correct `[org.clojure/clojure "1.7.0"]`

**Comment by papachan** [comment]
Right now i have rolled back cider-nrepl to 0.10.0 and it work fine.

![selection_431](https://cloud.githubusercontent.com/assets/38855/11761763/74a07c9e-a09d-11e5-813a-251ff41bfae8.png)

**Comment by cichli** [comment]
This one has me a bit stumped :-). What does `java -version` output?

**Comment by papachan** [comment]
i have tried also to remove all repo cache.

Java version do:
```
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

**Comment by Malabarba** [comment]
Could it be an issue with Mr Anderson?

**Comment by cichli** [comment]
What about `lein version`? It might also be related to reader conditionals (`fipp.edn` is defined in a `cljc` file).

**Comment by papachan** [comment]
Nice ! it have been fixed upgrading to leiningen-2.5.3.

**Comment by bbatsov** [comment]
Just for the protocol - what was your lein version before you upgraded?

**Comment by cichli** [comment]
Support was added in 2.5.2, FWIW - technomancy/leiningen/issues/1827

**Comment by bbatsov** [comment]
Got it. Seem we need to do a lein version warning as well on boot. That won't be very hard. We know when a connection is created via lein, so we can execute some version check afterwards and warn users.

**Comment by papachan** [comment]
@bbatsov yeah correct. before upgrading i had lein 2.5.2.
