### ISSUE TITLE
Cider inspect fails with "wrong type argument"

### ISSUE THREAD

**Issue by Kungi** [clojure-emacs/cider#1468]
Everywhere I try to use cider-inspect I get the following error:
```
error in process filter: condition-case: Wrong type argument: char-or-string-p, ("Class" ": " ("value" "java.lang.String" 0) ("newline") "Value: " "\":credential-fn\"")
error in process filter: Wrong type argument: char-or-string-p, ("Class" ": " ("value" "java.lang.String" 0) ("newline") "Value: " "\":credential-fn\"")
```

I am using cider0.11.0-snapshot (20151212.1044) from melpa.

**Comment by bbatsov** [comment]
Seems to work fine for me. Can you give us some repro steps?

**Comment by Kungi** [comment]
Obviously you telling "works fine for me" intimidated my cider into working properly. I cannot reproduce the behaviour. Thanks for making the problem disappear :-).

**Comment by lvh** [comment]
FWIW, I'm running into this issue too. Also unable to reliably reproduce; sometimes, it works fine...

**Comment by dpsutton** [comment]
@lvh can you post a screenshot or stack trace or anything to get a handle on where to start looking next time it pops up?

**Comment by aisamu** [comment]
For the record, something very similar happened here. The error was (on every inspect):
```
cider-inspector--render-value: Wrong type argument: char-or-string-p, ("Class" ": " ("value" "java.lang.String" 0) ("newline") "Value: " "\"[1 2 3]\"")
```
It turned out to be a bad interaction between `venantio/ultra` and some other dependency. Removing it brought things back to normal.
#### Setup
```clojure
:dependencies [[org.clojure/clojure "1.9.0-alpha17"]
               [instaparse "1.4.5"]
               [slingshot "0.12.2"]
               [org.clojure/algo.generic "0.1.2"]
               [org.clojure/test.check "0.9.0"]
               [org.clojure/core.match "0.2.2"]
               [digest "1.4.5"]
               [jonase/kibit "0.1.5"]
               [org.clojure/core.logic "0.8.11"]
               [cheshire "5.7.1"]]

;; CIDER 0.15.1-SNAPSHOT
;; no ‘profile.clj’, ‘~/.lein/profile.clj’
```
#### Tested expression: 
`[1 2 3]` -> cider-inspect

#### Without `[venantius/ultra "0.5.1" ]`
```
cider-next-expression
=> “[1 2 3]/n” 

cider-sync-request:inspect-expr
=> "(\"Class\" \": \" (:value \"clojure.lang.PersistentVector\" 0) (:newline) \"Contents: \" (:newline) \"  \" \"0\" \". \" (:value \"1\" 1) (:newline) \"  \" \"1\" \". \" (:value \"2\" 2) (:newline) \"  \" \"2\" \". \" (:value \"3\" 3) (:newline))"
```

#### With `[venantius/ultra "0.5.1" ]`
```
cider-next-expression
=> “[1 2 3]/n” 

cider-sync-request:inspect-expr
=> ("Class" ": " ("value" "java.lang.String" 0) ("newline") "Value: " "\"[1 2 3]\"")
```
So there's the issue! 

On a blank project, though, `ultra`+`CIDER` works fine... 😕

**Comment by Kungi** [comment]
Thank you very much. The ultra dependency in my .lein/profiles.clj was indeed the problem. I started experiencing this error again some time ago but just ignored it grudgingly.
