### ISSUE TITLE
cider-debug stepping through a compojure macro

### ISSUE THREAD

**Issue by xihan** [clojure-emacs/cider#1473]
This is the related google-group question: https://groups.google.com/forum/#!topic/cider-emacs/PcHGXhdmd0o

The question was how to instrument the compojure macros (GET, POST, etc) for step-through
debugging. 

(GET '/foo/{:id}' [id] (ok nil)) <-- instrumenting the form causes an immediate evaluation
A workaround is to wrap the route in a function:
(defn foo [id] (ok nil)) <-- instrumenting this form will correctly set up the debugger once a request is made
(GET '/foo/{:id}' [id] (foo id))

I am aware that there are other debugging techniques which do not require stepping through
code, but it would still be nice to be able to do this from time to time. 

Artur kindly asked me to report this issue.

Thanks
xihan

**Comment by Malabarba** [comment]
Hi @xihan.
Thanks for reporting this. I know I said I had also noticed some issues when trying to debug routes, but now that I'm looking into it I think I was mistaken. 

For instance, if I define this route:

    (GET "/foo/:id" [id] (println "Id was" id))

Debugging works fine. (that is, I can debug it and when the route is triggered I can correctly step through the entire `(println "Id was" id)` expression. 

I tried testing your expression, but (AFAIK) `(GET '/foo/{:id}' id)` is not a valid route.
