### ISSUE TITLE
Difference between connecting to running nREPL and jack-in?

### ISSUE THREAD

**Issue by favetelinguis** [clojure-emacs/cider#1478]
Im building on a Luminus project wich starts a webserver and nREPL via lein run command. The nREPL session is avaliable on localhost:7000.

Using C-c M-c and then selecting localhost and then typing in 7000 asks me for selecting a project. After CIDER fires up a repl buffer im getting a warning:
WARNING: The following required nREPL ops are not supported: 
apropos classpath complete eldoc format-code format-edn info inspect-pop inspect-push inspect-refresh macroexpand ns-list ns-vars ns-path refresh resource stacktrace toggle-trace-var toggle-trace-ns undef
Please, install (or update) cider-nrepl 0.10.0-SNAPSHOT and restart CIDER

However if I do C-c M-j on a buffer in the project cider starts up a repl buffer as always without any problems.

Why is there a difference when trying to connect to a running nREPL session and when im doing a jack-in?

**Comment by Malabarba** [comment]
Your lein run command probably isn't adding the  cider middleware to the nrepl server it starts. 
Have you looked at the readme instructions on embedding cider-nrepl?
