### ISSUE TITLE
cider--get-symbol-indent: Args out of range: -1, -1 error on newline-and-indent when REPL connected

### ISSUE THREAD

**Issue by cap10morgan** [clojure-emacs/cider#1481]
Very often (but not always) when I have a REPL connected to a buffer and I hit enter at the end of a line, I get this error and indentation doesn't happen (the point stays at column 0):

`cider--get-symbol-indent: Args out of range: -1, -1`

This just started with CIDER 0.10. It never occurs when there is not a REPL connected to the buffer.

**Comment by bbatsov** [comment]
This is fixed on `master` https://github.com/clojure-emacs/cider/commit/44cc9c01ba5f119c6e38f0dd6f1da4f44b86944d

We'll see if we'll backport the fix to a potential 0.10.1 release. I'd like us to do one, but I don't have time to deal with it.

**Comment by cap10morgan** [comment]
@bbatsov Happy to help any way I can there. The fix seems to drop right in to the same line of code in the v0.10.0 tag, so a PR doesn't seem like much help (though happy to create one if I'm wrong about that).

I'm applying the fix to my local v0.10.0 code in `~/.emacs.d/elpa` to test it out. I'll report back here how it goes.

**Comment by bbatsov** [comment]
Great.

In general we need someone to maintain the 0.10 branch and maybe do a couple of releases down the road. Its the last version that supports Clojure 1.5 and 1.6 and I can imagine that some people will be stuck on it for a while.

**Comment by cap10morgan** [comment]
*raises hand*

I can probably do that if you and any other veteran maintainers don't mind a question or two from time to time.

To start, are there any other fixes on master you'd like me to pull into a 0.10 branch to start prepping the 0.10.1 release?

**Comment by Malabarba** [comment]
I never mind answering questions. :-)

**Comment by bbatsov** [comment]
Well, every bugfix should probably be merged to 0.10 and we have to fix the restart and quit bugs before we can release it. There hasn't been much activity since 0.10.

**Comment by cap10morgan** [comment]
OK, I can create a new `v0.10.x` branch (unless you prefer a different naming convention) and start backporting everything categorized as a bug fix in the changelog (and keep monitoring for new ones).

Seem like a good first step?

Can I make a pull request into a new branch? Never tried that before.

**Comment by bbatsov** [comment]
The branch can be simply `v0.10`.

> Can I make a pull request into a new branch? Never tried that before.

No idea. :-)

**Comment by cap10morgan** [comment]
It doesn't look like I can request a pull into a new branch. Can someone w/ permissions create a `v0.10` branch here and I'll issue a PR into that with my first cut at the bug fixes on master applied on top of the `v0.10.0` tag?

**Comment by cap10morgan** [comment]
@bbatsov It looks like all the fixes are backported now and both `cider-restart` and `cider-quit` seem to be working just fine. Once there's a branch for my `v0.10` PR to target over here, I'll issue it.

**Comment by bbatsov** [comment]
I've just pushed the `v0.10` branch.

**Comment by cap10morgan** [comment]
This is fixed on master and will be fixed in v0.10.1 too.
