### ISSUE TITLE
Cannot re-connect after repl quits unexpectedly

### ISSUE THREAD

**Issue by pesterhazy** [clojure-emacs/cider#1482]
Thanks for the awesome project! In recent versions of CIDER, I have to restart Emacs to connect to an `nrepl` after the previous `lein` process died.

## STR

1. `lein repl`
1. `cider-connect`
1. In the repl terminal window, `^D`
   `nREPL: Connection closed unexpectedly (connection broken by remote peer)`
1. re-start the repl
1. `cider-connect`
1. Re-use zombie REPL buffers? Yes

## Expected result

I can re-evaluate the buffer

## Actual result

I see a beach ball (on OSX) and Emacs becomes unresponsive. Evaluating the buffer doesn't work.

`*Messages*` shows ```nrepl-send-sync-request: Sync nREPL request timed out (op clone id 2)```

## System

```
; CIDER 0.11.0snapshot (package: 20151220.156) (Java 1.8.0_51, Clojure 1.5.1, nREPL 0.2.10)
```

In this test I'm using leiningen with an ancient version of Clojure, but the same problem exists with `boot` and Clojure 1.7.

Not that I'm *not* using cider-nrepl-middleware because it slows down startup of a largish projects by many seconds.

In tests the problem doesn't occur if I `cider-quit` before exiting the external `lein repl` (but you sometimes don't have that luxury).

**Comment by bbatsov** [comment]
You should also post here your `*nrepl-messages*` log.

**Comment by Malabarba** [comment]
Sounds like we don't cleanup the buffer when the connection is lost, and then when starting the new connection we try to send a message to the dead connection for some reason (which times out).

**Comment by bbatsov** [comment]
I think the zombie repl handling code was supposed to do the cleanup, when the dead connection is reused. Don't recall any recent changes there, though.

**Comment by pesterhazy** [comment]
@bbatsov, sure! I've updated to current lein/nrepl and created an empty project, but the issue persists.

There are two buffers labeled "nrepl messages" (1.txt, 2.txt). I'm also attaching the relevant section of my messages (3.txt). 

[1.txt](https://github.com/clojure-emacs/cider/files/71177/1.txt)
[2.txt](https://github.com/clojure-emacs/cider/files/71178/2.txt)
[3.txt](https://github.com/clojure-emacs/cider/files/71179/3.txt)

**Comment by pesterhazy** [comment]
Also, this is in latest spacemacs (if that matters).

**Comment by jgeraerts** [comment]
same issue here with cider 0.10.0 on "GNU Emacs 24.5.1 (i686-pc-mingw32)\n of 2015-04-11 on LEG570"

**Comment by rfkm** [comment]
I think the cause of this issue is that nrepl client unexpectedly picks up an old session id.
The easiest way to fix this is to add `(setq nrepl-session nil)` into `cider-repl-create` function.

**Comment by bbatsov** [comment]
Yeah, we should make sure both the normal and the tooling sessions are reset for the reused REPL buffer. @rfkm feel free to submit a PR. I'm pretty sure this problem was introduced recently. Maybe we should search with bisect for the problematic commit.

**Comment by Malabarba** [comment]
It was probably introduced when I made the send-request function automatically add the session parameter to the request. 
I agree with the suggestion of how to fix it, but I think we should also set that variable to nil in the process sentinel.

**Comment by bbatsov** [comment]
And the `nrepl-tooling-session`.

**Comment by pesterhazy** [comment]
Confirming that the fix in master works. Thanks for the fast response! :)
