### ISSUE TITLE
Functions bound to keys in documentation

### ISSUE THREAD

**Issue by agzam** [clojure-emacs/cider#1485]
Would it be possible to add function names to documentation next to keyboard shortcuts for those who use Spacemacs or other distributions of Emacs based on evil mode. That would be amazing. Thanks.

**Comment by bbatsov** [comment]
You can simply see what the keybindings are bound to with `C-h k`. Or even better - see the bindings in a particular mode with `C-h m`.

**Comment by agzam** [comment]
Yeah I know, it's just CIDER is quite amazingly has quite number of things that I thought would be easier to discover right from the docs. After posting my initial question I realized what you have in docs actually a convention widely used in Emacs. I guess function names often change, keybindings less so.
