### ISSUE TITLE
Regression in stacktrace font-locking

### ISSUE THREAD

**Issue by jeffvalk** [clojure-emacs/cider#1486]
401e819 changed uses of `face` to `font-lock-face`, including [here](https://github.com/clojure-emacs/cider/blob/546de8f6f2e68f6854e3363e8da94fb5ce1225d2/cider-stacktrace.el#L506-L507). This may have fixed a larger font-lock compatibility issue, but it disabled font-locking of stack frame detail: the `face` set [here](https://github.com/clojure-emacs/cider/blob/546de8f6f2e68f6854e3363e8da94fb5ce1225d2/cider-stacktrace.el#L500) overrides those uses of `font-lock-face`.

**Comment by bbatsov** [comment]
It's amazing no one noticed this for over one year.

**Comment by bbatsov** [comment]
You might want to mention the fix in the changelog as well.

**Comment by jeffvalk** [comment]
That's what I thought too. Maybe everyone is just conditioned to ugly errors. For all Clojure's awesomeness, errors are still not sane.

On the other hand, the updates to to CIDER in the last year are really fantastic. Seriously great stuff!

**Comment by cap10morgan** [comment]
I'm trying to test that this is fixed in the v0.10 branch, but I'm not 100% sure how to reproduce it. Can someone post some simple reproduction steps? Thanks!

**Comment by jeffvalk** [comment]
If the file, line number, namespace/class, and function/method for stacktrace frames all appear with the same face, you're seeing this issue. If the function name is in bold and the ns is fontified as a comment, you're seeing the fix.

**Comment by cap10morgan** [comment]
@jeffvalk Thanks, looks good in that case.
