### ISSUE TITLE
auto-completion breaks after moving to a new namespace on a CLJS REPL.

### ISSUE THREAD

**Issue by crocket** [clojure-emacs/cider#1489]
After launching a CLJS REPL, auto-completion works well.
But, after moving to a new namespace with such a command as (ns something.core), auto-completion breaks for many namespaces.

**Comment by bbatsov** [comment]
Are we talking about built-in auto-completion or some third-party package?

**Comment by crocket** [comment]
What do you mean by third-party package?

**Comment by bbatsov** [comment]
Third-part completion package - auto-complete-mode, company-mode, etc

**Comment by crocket** [comment]
Nope, I reproduced the issue on nrepl-figwheel-node-template without any third party auto-completion package.

**Comment by bbatsov** [comment]
@cichli Can you take a look at this, please?

**Comment by crocket** [comment]
1. If I use company mode, the issue doesn't occur.
2. The issue is with built-in auto-completion.

**Comment by crocket** [comment]
According to my test,
* After pressing `C-c M-n` in a cljs file, `cljs.repl/doc` is not displayed in auto-completion.
* After executing `(ns something.core)`, `cljs.repl/doc` is not displayed in auto-completion.
* After executing `(ns something.core (:use-macros [cljs.repl :only [doc]]))`, `cljs.repl/ TAB` displays the full content of its namespace.

**Comment by cichli** [comment]
Including conversation from Slack for more context:

```
cichli [2:07 PM] 
Thanks, that's enough for me to replicate - I'll take a look this evening :simple_smile:

​[2:08] 
I ​_think_​ the first two examples are expected; `cljs.repl` is only automatically required in the `cljs.user` namespace

crocket [2:09 PM] 
So, what is wrong?

cichli [2:09 PM] 
But the latter sounds like either a bug in the CLJS autocompletion code, or possibly a bug in the CLJS compiler itself (can you successfully use any of the macros in `cljs.repl` that you ​_didn't_​ specifically impot?)

​[2:10] 
Oh, I see, you're still seeing `print-doc` in the completions for the first two cases

crocket [2:11 PM] 
@cichli: I can execute `(cljs.repl/source cljs.repl/doc)` after executing `(ns hello-world.test (:use-macros [cljs.repl :only [doc]]))`.

​[2:11] 
Macros are only not available for auto-completion, but they are always there.

​[2:12] 
Even after `(ns something.core)`, `cljs.repl/doc`, `cljs.repl/source`, etc are available for invocation. But, they are not available for auto-completion.(edited)

cichli [2:13 PM] 
Gotcha, thanks

​[2:13] 
This issue might be specific to `cljs.repl`, so we might just have to special-case that. I'll see if the issue occurs for other macro namespaces
```

**Comment by bbatsov** [comment]
@arichiardi Can you look into this?

**Comment by vemv** [comment]
Probably this hasn't been the case for a long while.
