### ISSUE TITLE
cider-inspect pops up even when evaluation fails

### ISSUE THREAD

**Issue by alexander-yakushev** [clojure-emacs/cider#1490]
When I inspect some expression, and the expression throws an exception instead of returning a value, the inspector is still shown with the contents of the previous successful inspection.

Expected behavior: inspector shouldn't appear, only the *cider-error* buffer.

**Comment by expez** [comment]
This might be related to https://github.com/clojure-emacs/cider/issues/1420?

**Comment by alexander-yakushev** [comment]
Thanks a lot!
