### ISSUE TITLE
Eldoc is missing for special forms

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1493]
There's no eldoc for special forms like `if`, `def` and `throw`. Seems like some regression to me (or a glaring oversight if we never had it).

**Comment by bbatsov** [comment]
@jeffvalk do you recall if this ever worked? It might be just a figment of my imagination. Maybe we just never implemented it to begin with...

**Comment by jeffvalk** [comment]
@bbatsov I could be wrong, but I'm not sure this was ever there.
