### ISSUE TITLE
cider-jack-in does not start repl

### ISSUE THREAD

**Issue by J2112O** [clojure-emacs/cider#1494]
Hi. I am new to learning Clojure with emacs. I am trying to get the repl up and going with cider-jack-in but it does not seem to be starting. In the mini buffer the only message displayed is Starting nREPL server via lein repl :headless ... And it just sits there and never starts up, that I can tell. I thought the issue was due to using emacs-24.3 but I have upgraded to emacs-24.4 and the problem is still there. Any advice on how I can fix this? Maybe some sort of configuration I am missing. Thanks

**Comment by bbatsov** [comment]
What cider version are you using?
What's your lein version?
Do you get any error messages?

We need more information to be able to help you.

**Comment by ivermac** [comment]
Hey @J2112O, I'm also a clojure and emacs newby - in fact I installed emacs and cider today - and I found [this link](http://clojure-doc.org/articles/tutorials/emacs.html) really helpful to get you up and running. I was also having problems having to run the repl but the url helped me. Hope this helps!

**Comment by bbatsov** [comment]
Closing due to lack of response.
