### ISSUE TITLE
Evaluating things before -jack-in is done throws an ugly error

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1495]
It's a small thing, but if the user runs `cider-jack-in` and then tries to evaluate something before the connection is established, they'll get a `Wrong type argument: stringp, nil` error.
Ideally, they'd get a `user-error` instead, saying something like "still waiting for the JVM to start so we can start a REPL".

**Comment by bbatsov** [comment]
Agreed. This should be simple to implement.

**Comment by bbatsov** [comment]
Guess you fixed this accidentally. Now I get `user-error: `cider-eval-last-sexp' needs a Clojure REPL.` when to eval something without a connection.

**Comment by Malabarba** [comment]
Yay! 😊
