### ISSUE TITLE
cider marks wrong line for error in source code

### ISSUE THREAD

**Issue by malloc82** [clojure-emacs/cider#1497]
It seems that cider error has been consistently marking the wrong line in source code, here is an example: ![example](https://cdn.img42.com/f8f5f8fb32ac4bfc270a7dab1005fdbc.png)

cider-error has report the error at line 197, and it is correct. But in the source code line 196 gets marked.

**Comment by bbatsov** [comment]
Could it be you changed the code and didn't re-evaluate it?

**Comment by malloc82** [comment]
Couldn't reproduce it at the moment, but it did came up quite often today.

No, I didn't change the source file after the error pops up. The screenshot was taken right after the cider-load-file command. Even if I change the source file, the red mark should follow that line as well.

Although it shouldn't matter, that problem occurred on a RedHat 6.5 machine. I'm using Mac at the moment.

**Comment by malloc82** [comment]
Interestingly, I think it's platform related. With the same code base, and the same emacs setting, the issue will show up on RedHat 6.5 but not on Mac. So far it seems that the problem only happens in loop bindings.

**Comment by bbatsov** [comment]
If this happens right after `load-file`, it's likely a bug in Clojure, not in Cider.

**Comment by Malabarba** [comment]
Back when I was messing with this stuff a bit, I definitely noticed a lack of consistency. Some errors would report the correct line, while others would be off by exactly 1.
It might be a discrepancy between the way we count lines and the way clojure.lang.Reader counts lines. Sometimes the line information is provided by us (regular eval), and sometimes it is provided by the reader (load-file).

**Comment by malloc82** [comment]
Just want to correct my previous statement a bit: I just had another case in let binding. This is after issuing C-c C-c, cider-eval-defun-at-point.

**Comment by malloc82** [comment]
Also, all cases I encountered so far are all inside defrecord's method implementation.

**Comment by bbatsov** [comment]
> Also, all cases I encountered so far are all inside defrecord's method implementation.

Sounds like a Clojure bug then. Did you check if their location metadata was correct?
