### ISSUE TITLE
Cider no longer prints stuff to the repl

### ISSUE THREAD

**Issue by gja** [clojure-emacs/cider#1499]
I've just upgraded from cider 0.8.0 and 0.10.0, and this seems to be a change in the default behaviour. 0.8.0 used to print stdout to the repl buffer.

For some reason, it goes into this other buffer called *nrepl-messages*. 

Is there some way to get stdout/stderr back on the repl? If so, is there documentation for it?

It seems at least one other person has faced this issue (and they stopped using cider for that reason) https://gist.github.com/levand/b1012bb7bdb5fcc6486f

**Comment by bbatsov** [comment]
There has been no such change. Post here steps to reproduce your problem.

**Comment by gja** [comment]
Interesting. I just assumed this was intentional. Did a bit of debugging.

Looks like I have an old version of nrepl (0.2.5). I just upgraded this to 0.2.10 and this suddenly started working.

Sorry for the false bug.
