### ISSUE TITLE
No print output when using "cider-nrepl-sync-request:eval"

### ISSUE THREAD

**Issue by seanirby** [clojure-emacs/cider#1506]
Hi,

So I can print to the REPL fine if I'm in a clojure file and I use something like "cider-eval-last-sexp".  But I have an emacs project i'm working on and it's using the cider client to programmatically evaluate some clojure code using "cider-nrepl-sync-request:eval".  I need to debug it, but it's difficult because I currently get no print output whenever I evaluate something through the cider client.  I've checked the value of \*out\* in both use cases and they're identical.  Can you reproduce this?

**Comment by seanirby** [comment]
I'm using version 0.11.0

**Comment by bbatsov** [comment]
What do you mean by "I get no output"?

**Comment by seanirby** [comment]
I'm trying to evaluate a defn that prints to the repl.  When using 'cider-eval-last-sexp' the repl gets printed to as expected.  When the defn gets run programmatically through 'cider-nrepl-sync-request:eval' there is not print output in the repl.

**Comment by bbatsov** [comment]
Sync eval requests don't result in REPL output - they return their output in the response map and you're supposed to do with it whatever you like.

**Comment by seanirby** [comment]
Im OK with the fact that the RESULT of the eval sync request is not sent to the REPL.  That's expected.  But if I have added "(println 'foo)" somewhere in my code then I expect that to print 'foo to the output stream when its evaluated.  It's not clear to me why printing to the output stream should be suppressed with a sync-request.

**Comment by Malabarba** [comment]
It shouldn't.
It's probably just a flaw in our sync requests response handler.

As a momentary workaround, is it possible for you to use regular requests instead?

**Comment by cichli** [comment]
Nothing is being suppressed. The REPL buffer in CIDER is not a literal output stream - CIDER appends output to it as it receives it for async eval requests.

```emacs-lisp
(cider-nrepl-sync-request:eval "(println 'foo)")
=> (dict "status" ("done" "state") "id" "132" "out" "foo
" "session" "92885a49-3d3c-4658-b3ce-486f42a04df7" "ns" "user" "value" ...)
```

As you can see, the output is there under the `"out"` key of the response dict. If you want that to be printed to the REPL, then you need to do it yourself using `cider-repl-emit-interactive-stdout` (or whatever function you want to use that will emit it wherever you want it to):

```emacs-lisp
(let ((resp (cider-nrepl-sync-request:eval "(println 'foo)")))
  (cider-repl-emit-interactive-stdout (nrepl-dict-get resp "out")))
```

**Comment by seanirby** [comment]
Ah, I wasn't aware of the 'out' key.  Thanks everyone.  Closing.

**Comment by cichli** [comment]
No problem :-). Also be aware of the `err` key for `*err*`, and the fact that sync requests return as soon as they receive a message with `:status :done` - so if your expression prints stuff after it returns a value (e.g. `(future (Thread/sleep 1000) (println "hi!"))`, then that output will be lost.
