### ISSUE TITLE
Display images of various format generated by clojure code in dedicated buffers or inline in the REPL

### ISSUE THREAD

**Issue by blueberry** [clojure-emacs/cider#1510]
Bozidar mentioned that he already has this Idea, but I imagine that it is not high priority now. 

I am opening this issue to hear thoughts from other interested users. I would implement that if I wasn't total elisp beginner, but am willing to take on this if in the future (currently I only have tiny time for learning elisp, so that won't be soon! :)

**Comment by bbatsov** [comment]
Basically the value handlers (the code that deals with return values) should check if the type of some return value is an image and process this differently.

**Comment by arrdem** [comment]
Kinda poking at this, since I've been doing a bunch of graphs recently. It looks like there's an old sketch at this from Phil here - https://github.com/technomancy/nrepl-discover/blob/master/src/nrepl/discover/samples.clj#L135

**Comment by bbatsov** [comment]
Yeah, it'd be really nice to finally implement this. Phil was working on middleware discovery and support for rich content types, but sadly this work never got finished. For the images themselves I think it'd be enough to just enhance the eval op to put some content type for special types in the response (and perhaps deliver the images in a format more convenient for external consumption) and on the client side we can look for such results and just visualize them.

**Comment by bbatsov** [comment]
Actually I noticed that this is pretty much what Phil has done. :-)

**Comment by arrdem** [comment]
So part one of this is ... probably just picking machinery on the Clojure side for identifying "images" in results which could be displayed nicely.

Part two here as Bozhidar mentioned is extending `nrepl-make-response-handler` to be more general, in terms of accepting eg. a `content-type` handler or even just accepting an alist from response types to handlers or some other dispatching structure. Took me a bit of digging to identify that.

Probably the thing to do which is truest to Phil's original vision would be to allow the user to supply their own alist of content-types to content-handlers - see the original idea of defining editor overlays and such with rich data fed from the server.

**Comment by arrdem** [comment]
@bbatsov yeah the REPL side of this is exactly what Phil's got a prototype of above. Looks like wiring this up on the CIDER side shouldn't be too hard, just need to make `nrepl-make-response-handler` less dumb.

**Comment by stardiviner** [comment]
Can it support other packages like [ob-clojure-literate](https://code.orgmode.org/bzg/org-mode/src/master/contrib/lisp/ob-clojure-literate.el)?

Even though I already implemented a way to display inline image result in
Org-mode buffer. But the implemented method is limited on "Incanter".

As this link:

> https://github.com/technomancy/nrepl-discover/blob/master/src/nrepl/discover/samples.clj#L135

code shows, might can improve it.

And hope CIDER can support Org-mode ob-clojure.el inline image result better (currently not supported).

**Comment by bbatsov** [comment]
Well, if the core functionality is there it can be extended to other packages easily.

**Comment by arrdem** [comment]
![2018-03-18-035402_910x630_scrot](https://user-images.githubusercontent.com/704767/37565108-141eb06c-2a60-11e8-86bf-aaae475d07af.png)

I totally got a cut at this working, between some patches to `nrepl-client.el`, `cider-repl.el` and `cider/cider-nrepl`. The really sticky bits in the changeset are dealing with the various point expectations in `cider-repl.el`, because the REPL as currently written relies on `insert-before-markers` to achieve output insertion and it only supports inserting text, not images which means I wound up doing some manual point management which .. isn't ideal.

**Comment by bbatsov** [comment]
Nice!

> because the REPL as currently written relies on insert-before-markers to achieve output insertion and it only supports inserting text, not images which means I wound up doing some manual point management which .. isn't ideal.

You have to start somewhere. ;-) No need to make it perfect from the start.
