### ISSUE TITLE
Calling `nrepl-op-supported-p` with wrong number of arguments

### ISSUE THREAD

**Issue by nblumoe** [clojure-emacs/cider#1512]
On `cider-jack-in` I get this error:

```lisp
Debugger entered--Lisp error: (wrong-number-of-arguments (2 . 2) 1)
  nrepl-op-supported-p("artifact-list")
  -remove(nrepl-op-supported-p ("artifact-list" "artifact-versions" "clean-ns" "configure" "extract-definition" "find-debug-fns" "find-symbol" "find-unbound" "hotload-dependency" "rename-file-or-dir" "resolve-missing" "stubs-for-interface" "version" "warm-ast-cache"))
  cljr--check-nrepl-ops()
  cljr--init-middleware()
  run-hooks(nrepl-connected-hook)
  nrepl-start-client-process(nil 44922 #<process nrepl-server>)
  nrepl-server-filter(#<process nrepl-server> "nREPL server started on port 44922 on host 127.0.0.1 - nrepl://127.0.0.1:44922\n")
```

using CIDER 0.10.1 (Java 1.8.0_65, Clojure 1.7.0, nREPL 0.2.12), Emacs 24.5.1 on Fedora 23

**Comment by expez** [comment]
You're likely running an old version of clj-refactor.  Please update to version 2.0.0-SNAPSHOT, which is the current version available on MELPA.

You can check the version you're running with `M-x cljr-version <RET>`

**Comment by nblumoe** [comment]
thanks @expez 

I actually had this pinned to maple-stable, same as I have with CIDER.
So far, after upgrading `clj-refactor` and `refactor-nrepl` accordingly, it seems to be back to normal.

Let's hope nothing else pops up from that.. .;)
