### ISSUE TITLE
Can't invoke simple repl with 'lein repl'

### ISSUE THREAD

**Issue by petegrif** [clojure-emacs/cider#1513]
I get a lot of unresolved symbol errors.

```
Error loading cider.nrepl.middleware.apropos: java.lang.RuntimeException: Unable to resolve symbol: response-for in this context, compiling:(cider/nrepl/middleware/apropos.clj:90)
Error loading cider.nrepl.middleware.classpath: java.lang.RuntimeException: Unable to resolve symbol: response-for in this context, compiling:(cider/nrepl/middleware/classpath.clj:15)
Error loading cider.nrepl.middleware.complete: java.lang.RuntimeException: Unable to resolve symbol: fuzzy-matches? in this context, compiling:(compliment/sources/ns_mappings.clj:16)
Error loading cider.nrepl.middleware.info: java.lang.RuntimeException: Unable to resolve symbol: mapv in this context, compiling:(cider/nrepl/middleware/util/java.clj:105)
Error loading cider.nrepl.middleware.inspect: java.lang.RuntimeException: Unable to resolve symbol: response-for in this context, compiling:(cider/nrepl/middleware/inspect.clj:74)
Error loading cider.nrepl.middleware.macroexpand: java.lang.RuntimeException: Unable to resolve symbol: response-for in this context, compiling:(cider/nrepl/middleware/macroexpand.clj:69)
Error loading cider.nrepl.middleware.ns: java.lang.RuntimeException: Unable to resolve symbol: response-for in this context, compiling:(cider/nrepl/middleware/ns.clj:46)
Error loading cider.nrepl.middleware.resource: java.lang.RuntimeException: Unable to resolve symbol: response-for in this context, compiling:(cider/nrepl/middleware/resource.clj:15)
Error loading cider.nrepl.middleware.stacktrace: java.lang.RuntimeException: Unable to resolve symbol: ex-data in this context, compiling:(cider/nrepl/middleware/stacktrace.clj:118)
Error loading cider.nrepl.middleware.test: java.lang.RuntimeException: Unable to resolve symbol: ex-data in this context, compiling:(cider/nrepl/middleware/stacktrace.clj:118)
Error loading cider.nrepl.middleware.trace: java.lang.RuntimeException: Unable to resolve symbol: response-for in this context, compiling:(cider/nrepl/middleware/trace.clj:16)
Error loading cider.nrepl.middleware.undef: java.lang.RuntimeException: Unable to resolve symbol: response-for in this context, compiling:(cider/nrepl/middleware/undef.clj:19)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.apropos/wrap-apropos in this context, compiling:(/private/var/folders/qb/p56gb2td4pvdqjgv07fq98bh0000gn/T/form-init6283531484480977693.clj:1)
```

any help gratefully accepted. :)

**Comment by bbatsov** [comment]
Some version info would be useful - Clojure, cider-nrepl, etc.

**Comment by petegrif** [comment]
cider/cider-nrepl "0.8.1"
clojure "1.7.0"

**Comment by bbatsov** [comment]
Just a reminder - 0.10.1 is the current stable version. I'm guessing you followed the installation instructions for setting up `cider-nrepl`, right?

**Comment by petegrif** [comment]
Yes. It is now 0.10.1. I am now checking it is compatible with CIDER.

**Comment by petegrif** [comment]
Excuse my ignorance but when I list packages to see which version of CIDER
I have i expected to find a clear indication that it was compatible with
the 0.10.1 for the reply but it isn't that clear to me. What i am seeing is
(a) the version is 20160113.2303 which is obviously recent, but (b) I also
see under 'Other Versions' an earlier version 20141120.1746 (installed). I
have no idea if that may be a problem.  Is my CIDER installation compatible
with the cider-repl?

**Comment by expez** [comment]
@petegrif you can do `M-x cider-version <RET>` to get cider to tell you its version information.  If you did `M-x package-list-packages <RET>` you'll get a list of all packages that are available (given the package repositories emacs knows about).  In that list you'll see a few different versions usually.  It's my guess that this is where you're looking now and it's telling you that `20160113.2303 ` is available and that `20141120.1746` is currently installed.

As you probably guessed the versions of the middleware and the code running in emacs should match, and it looks like you'll need to update CIDER on the emacs end.

IIRC, in the package list you can hit <kbd>U</kbd> followed by <kbd>x</kbd> to update all your installed packages.

**Comment by petegrif** [comment]
Thanks Lars, gradually getting there.  I have managed to mark the package
list but can't figure out how to execute the updates and deletes :(  Where
to I hit the u and the x?  on the line?

**Comment by expez** [comment]
`M-x package-list-packages` then <kbd>U</kbd> followed by <kbd>x</kbd>.  Notice the capital <kbd>U</kbd>.  This will update all installed packages.

[Here's](https://www.gnu.org/software/emacs/manual/html_node/emacs/Packages.html) the relevant page in the manual if you're still stuck.

**Comment by petegrif** [comment]
Got it.  Many thanks guys.  So now I've made some progress: all updated and when I'm in Emacs and cider-jack-in I am told I'm connected.  But no repl appears and from bash I still get the errors when invoking the reply by 'lein repl'    Is the 0.11.0 SNAPSHOT version of CIDER compatible with cider-nrepl "0.10.1" as setup in profile.clj  with {:user {:plugins [[cider/cider-nrepl "0.10.1"]]}} or do I have to step CIDER back to exactly the same version?

**Comment by expez** [comment]
You can step CIDER back, if you prefer to run on stable.  That would mean figuring out how melpa-stable works and how to pin packages to a specific version.

Or, you could just run the bleeding edge on the backend as well:

profiles.clj:
```
{:user {:plugins [[cider/cider-nrepl "0.11.0-SNAPSHOT"]]}}
```

**Comment by Malabarba** [comment]
I recommend just removing the Melpa repository from your config, and setting up Melpa-stable instead. Then delete all snapshot packages you have installed, restart emacs, and install the stable versions.

**Comment by bbatsov** [comment]
I'm closing this as it's not really an issue with cider. If you need more help - hop on slack or gitter.

**Comment by petegrif** [comment]
Thanks
