### ISSUE TITLE
cider--get-symbol-indent: Args out of range: -1, -1

### ISSUE THREAD

**Issue by stathissideris** [clojure-emacs/cider#1524]
I sometimes get this error when pressing TAB at the beginning of the line in order to indent it:

```
cider--get-symbol-indent: Args out of range: -1, -1
```

Indentation fails no matter how many times I press TAB after it happens the first time. Interestingly TAB does *not* fail on other lines of the same file!

**Comment by bbatsov** [comment]
Can you share with us your cider version info?

**Comment by bbatsov** [comment]
Closing due to lack of extra info.

**Comment by stathissideris** [comment]
Sorry for the delay, I cannot reproduce this with 0.10.1, so great! thanks :-)

**Comment by celwell** [comment]
Upgrading fixed this for me as well.
