### ISSUE TITLE
Add the ability to route stdout and stderr to different buffers based on regular expressions

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1525]
It would be useful if we had the ability to redirect certain type of output (e.g. logging output to dedicated buffers for quick inspection). 

Adding support for this won't be hard - basically we need a mapping between regular expressions or functions, that will be used to check if some output is a match, a buffer name (or some function) that will be used when we have a match. We just have to figure out what to do in the unlikely scenario of multiple matches - should check all patterns & predicates or just stop after the first match. 

This functionality should be exposed to the users in the form of a defcustom.

**Comment by cch1** [comment]
+1

**Comment by cch1** [comment]
Still dreaming of seeing the `org.apache.log4j.ConsoleAppender` output in emacs... without having to go via a file.

**Comment by bbatsov** [comment]
In general it seems that this is not really doable, as when I created the ticket I had forgotten that output is spread over multiple messages (each containing a chunk of the output). Matching the contents of any one of them with a regular expression doesn't make much sense as they'd often be partial messages.

**Comment by hiteshjasani** [comment]
I'm working with a system in kubernetes that is generating a large amount of logs to STDOUT. The ability to blacklist certain log messages by regex so they get dropped and not printed to the REPL would be valuable to me.

Would this be doable, since I assume partial messages have to be reassembled before being printed to the REPL?
