### ISSUE TITLE
Add Inline code evaluation and watches like in the Light Table IDE

### ISSUE THREAD

**Issue by SlightlyCyborg** [clojure-emacs/cider#1528]
[Here](https://www.youtube.com/watch?v=mNO-vgq3Avg&feature=youtu.be) is a demo of a similar plugin for Emacs lisp

**Comment by Malabarba** [comment]
FWIW, I've been working on something like this, albeit less aggressive.

**Comment by bbatsov** [comment]
Yeah, that'd be nice to have in some form of another. At some point I was planning to work on a similar feature, but I never got anywhere with it.
