### ISSUE TITLE
*nrepl-messages lkahdg-asdfjkh-asdfkjh* buffers are never cleaned 

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1529]
I have a gazillion of these `*nrepl-message 123asdf- qwruyw35-asdflk3*` buffers after jumping in and out of various clojure projects today.

It's frustrating enough to guess which buffer to check when the odds are 33% but I had to kill all these buffers and restart the repl in order to debug the refactor-nrepl middleware today.

**Comment by Malabarba** [comment]
Perhaps instead of using the connection id in the buffer name, we should use the result of `cider--connection-info`, which is way more informative.

**Comment by bbatsov** [comment]
@Malabarba That way you'd couple cider & nrepl. 
@expez Using the `cider-selector` command you won't be doing any guesswork.

This will all be addressed when I find some time to rework the message logging.

**Comment by Malabarba** [comment]
> That way you'd couple cider & nrepl. 

True. :-(
