### ISSUE TITLE
Metadata isn't updated when evaluating a buffer

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1530]
1. Start a repl.
2. Add metadata to an ns of your choice.
3. <kbd> C-c C-k</kbd> (or `M-x cider-eval-ns-form`)
4. Change metadata.
5. <kbd> C-c C-k</kbd> (or `M-x cider-eval-ns-form`)
6. Be surprised when you still see the metadata you loaded in step 3 after running `(meta (find-ns 'your-ns-of-choice)`

**Comment by Malabarba** [comment]
I think this is a bug with the ns macro.

**Comment by bbatsov** [comment]
Sounds like a bug in `ns` indeed. Are you able to change the metadata without cider?

**Comment by expez** [comment]
> Are you able to change the metadata without cider?

Yes
```
user=> (ns ^:foo bar)
nil
bar=> (meta (find-ns 'bar))
{:foo true}
bar=> (ns ^:baz bar)
nil
bar=> (meta (find-ns 'bar))
{:baz true}
bar=>
```

**Comment by Malabarba** [comment]
What clojure version is that?

**Comment by expez** [comment]
1.8, but I doubt this behavior is different across versions

**Comment by bbatsov** [comment]
Well, this definitely doesn't work the same on 1.7:

```
user=> (ns ^:foo bar)
nil
bar=> (meta (find-ns 'bar))
{:foo true}
bar=> (ns ^:fuu bar)
nil
bar=> (meta (find-ns 'bar))
{:foo true}
```

**Comment by Malabarba** [comment]
Yes. Precisely why I asked. I did try it here before shifting blame to the macro. :-)

**Comment by bbatsov** [comment]
OK, I'm closing this as it's clear it's not cider-related.

**Comment by Malabarba** [comment]
Isn't it? I was under the impression that (with cider) the ns metadata doesn't get updated even on Clojure 1.8.

**Comment by bbatsov** [comment]
Can't imagine how cider could be affecting a simple eval operation.
