### ISSUE TITLE
Cider should inject its own dependencies/plugins automatically at cider-jack-in

### ISSUE THREAD

**Issue by phillord** [clojure-emacs/cider#1531]
Currently, cider complains when the dependencies are wrong in profile.clj. I understand the reasons for this, but it would be nice if Cider offered the ability to update your profile for you.

Another possibility would be for cider to check whether pomegranate is present and if not, inject the correct dependencies. Don't know if that is possible with plugins, but worth thinking about.

This would be great for me when I am switching Emacs' -- sometimes using melpa-stable, sometimes melpa normal. Then I have to continually re-edit my profile.clj. Painful.

**Comment by benedekfazekas** [comment]
I've been thinking along the same lines (for clj-refactor as well) lately so +1

**Comment by stardiviner** [comment]
+1 for this, don't want to continuously monitor version change update.

**Comment by Malabarba** [comment]
I mentioned this on slack. I'll be glad to provide this if lein (or boot) has a way to specify deps on the command line. Otherwise it would involve manually parsing the project.clj file in elisp, which is not something I'm super excited to do. =) 

One thing that would be easier to do is to offer a "new project" command, which would create the project with the right deps. However, this wouldn't solve any of the complaints here.

**Comment by phillord** [comment]
I've been thinking about it -- a "cider shim" plugin which pulls the middleware into the JVM with pomegranate really seems possible to me. It should be possible to write it once and rarely update it. I guess it needs to inject both into the repl and the leiningen JVM?

I've been watching a new colleague of mine trying to install cider, and this step really isn't nice.

**Comment by benedekfazekas** [comment]
We do something like this in refactor-nrepl eg. add dependency to a running REPL. My worry is tho that these artifacts are not simple deps but nrepl middlewares there could be some extra steps to register them. No idea if this works dynamically.

**Comment by phillord** [comment]
I think it works. Can someone give this a go: https://github.com/phillord/plugin-inject

You launch with lein plugin-inject repl :headless and it pushes the nrepl middleware plugin in first, then passes execution to repl task. End result, cider works despite there not being any cider middleware plugin around.

Might not work for anyone else, but seems a reasonable start. It's only a few lines of code.

**Comment by Malabarba** [comment]
@phillord do you think it would be possible to specify the version of the cider middleware?

**Comment by phillord** [comment]
Hmmm, think I've made a mistake. I had an old "cider-nrepl" dependency left in my .lein. So, it's not working. Try again.

I think more generally this is a leiningen issue -- if cider could specify it's own profile.clj which was merged with the users, this would solve the problem. A shim is a bit of a cheap plastic solution (bad pun).

**Comment by expez** [comment]
It might be easier to just check if `profiles.clj` contains a matching version and if not offer to update the text specifying the version, before starting the repl at all.  This would far simpler than the proposed solutions so far.

**Comment by phillord** [comment]
I don't think would help with the new install. I agree, the shim is rather complex. Having support in lein would be the easiest.

**Comment by benedekfazekas** [comment]
this seems to be working for me:

`lein update-in :plugins conj "[cider/cider-nrepl \"0.11.0-SNAPSHOT\"]" -- repl`

**Comment by benedekfazekas** [comment]
it seems to me that boot has even better support for this via their `boot.repl/*default-dependencies*` and `boot.repl/*default-middleware*` atoms, [see details](https://github.com/boot-clj/boot/wiki/Cider-REPL#a-better-way) and [1a765793](https://github.com/boot-clj/boot/commit/1a76579304e816d3407a00c114b0bd4a8b82a549)

**Comment by benedekfazekas** [comment]
more on leiningen:

in fact it is doable even now with setting `cider-lein-parameters`:
`(setq cider-lein-parameters "update-in :plugins conj \"[cider/cider-nrepl \\\"0.11.0-SNAPSHOT\\\"]\" -- repl")`
 
so I guess we could introduce a variable listing all nrepl middleware plugins (so clj-refactor can add its own) and then update those in as plugins by default with perhaps an opt out config in case somebody wants to start up cider without this.

**Comment by Malabarba** [comment]
> lein update-in :plugins conj "[cider/cider-nrepl \"0.11.0-SNAPSHOT\"]" -- repl

Nice! If it's as simple as that, I'd like to start using this as soon as the next release.
I've set a milestone so that we at least give it a try and see if it's feasible.

**Comment by phillord** [comment]
It looks like so. I just removed my `profile.clj`, ran a clean emacs, installed cider, added this:

    (setq cider-lein-parameters "update-in :plugins conj \"[cider/cider-nrepl \\\"0.10.2\\\"]\" -- update-in :dependencies conj \"[org.clojure/tools.nrepl \\\"0.2.12\\\"]\" -- repl :headless")

And started cider on a test clojure project. Bingo, all works.

The command line is a bit of a gobsmacker, and probably doesn't need to get displayed to the user, but that's just a matter of adding a new variable.

@benedekfazekas Thanks! I hadn't seen the update-in task.

**Comment by benedekfazekas** [comment]
no worries. will try to have a look on boot as well. not sure we need to handle `gradle`

**Comment by phillord** [comment]
Boot can be handled with a custom task -- like the "cider repl" task in the doc, but passing in version numbers as keys.

This has been a PITA ever since the middleware came in, so removing the hassle for new users is going to be a major contribution to useability. And it should cleanly update from version to version.

**Comment by benedekfazekas** [comment]
after having a chat with @micha on slack it seems there is CLI way for boot too, something like:
`boot -d asdf/qwer:1.2.3 repl -m asdf.qwer/middleware`

**Comment by phillord** [comment]
With boot, I put this into my boot.profile

    (deftask cider "CIDER profile"
      [c cider-nrepl VAL str "The cider-nrepl version"
       t tools-nrepl VAL str "The tools-nrepl version"
       ]
      (require 'boot.repl)
      (swap! @(resolve 'boot.repl/*default-dependencies*)
             concat `[[org.clojure/tools.nrepl ~(:tools-nrepl *opts*)]
                      [cider/cider-nrepl ~(:cider-nrepl *opts*)]])
      (swap! @(resolve 'boot.repl/*default-middleware*)
             concat '[cider.nrepl/cider-middleware])
      identity)


Added this into a clean emacs, with cider installed.

     (setq cider-boot-parameters "cider -c \"0.10.2\" -t \"0.2.1\" repl -s wait" )

Loaded a new project, and it works.

**Comment by benedekfazekas** [comment]
yup this is nice but we still need the user to define this task or hide it somewhere in the elisp code of cider or something. would be even nicer to:
`(setq cider-boot-parameters "-d cider/cider-nrepl:0.10.2 -m cider.nrepl/cider-middleware repl -s wait" )`
which should be possible (have not tested it yet)

**Comment by Malabarba** [comment]
INdeed, if we have to tell users to define that task, then we haven't gained much on the boot front. It'd be nicer to do it all directly.

**Comment by benedekfazekas** [comment]
the boot guys discussing the scenario when you connect to an running repl process which apparently is how quite a few ppl prefer to work even with emacs (instead of jack-in). for that case finding a way to add the middleware at run time would still have good value. but I suppose solving this at runtime for the `jack-in` use case is much higher priority

**Comment by phillord** [comment]
@Malabarba with that task you would at least have gained version independence, so it would be worth documenting anyway. So long as cider's dependency requirements are accessible from lisp, then it can be made to work anyway of course.

Still, agree it's suboptimal. Surprised to find boot doesn't have an "eval" or "load-file" task, a la emacs --batch. Would solve the problem

**Comment by Malabarba** [comment]
> the scenario when you connect to an running repl process which apparently is how quite a few ppl prefer to work 

I think that's a slightly more advanced task, so people who understand how that works should have no problems following the readme.
Of course, it would be nice to make that fully automated, but I'm less concerned with it because of the above (and because I think it would be moderately harder to do).

> with that task you would at least have gained version independence, so it would be worth documenting anyway.

True. If there's no better alternative, we should document it. :+1:

**Comment by phillord** [comment]
@benedekfazekas if you are already talking to the boot guys, want to ask whether they will add a eval or load-file task? It's generic, totally future proof and, sometimes, only lambda is enough:-)

**Comment by benedekfazekas** [comment]
@phillord why would that be beneficial? It seems that we can do the same (or very similar) with boot on the CLI as with lein at start up time -- see my comment above. So the ux would be the same for both lein and boot when jacking in without any extra config done by the user.

Btw thanks a lot for raising this!

**Comment by phillord** [comment]
@benedekfazekas Oh, I couldn't get that to work; sorry, should have said. Is there a -m option command line option?

**Comment by benedekfazekas** [comment]
There is, yes, for the repl task. So you will only see it if you run help for the repl task. Will have a play with it when I have a little time.

**Comment by phillord** [comment]
@benedekfazekas Right you are.

    (setq cider-boot-parameters
      "-d cider/cider-nrepl:0.10.2 -d org.clojure/tools.nrepl:0.2.12 repl -m cider.nrepl/cider-middleware -s wait")

This seems to do the trick on a clean emacs.

**Comment by benedekfazekas** [comment]
Awesome :+1: thx for figuring it out

**Comment by benedekfazekas** [comment]
i might try to put together a PR for this tmrw *if* nobody else is already working on it in anger. let me know

**Comment by phillord** [comment]
I am not at the moment, and will not get to it for tomorrow or the next few days, so please go ahead.

**Comment by Malabarba** [comment]
I'm also not working on it. Feel free to go ahead.
