### ISSUE TITLE
Indentation problems with om next

### ISSUE THREAD

**Issue by favetelinguis** [clojure-emacs/cider#1533]
Code is not getting indented correct in the case below, im using 0.10.0 cider version.
Is this a known issue or is there something todo about it?

    (defui Status
      static om/IQuery
      (query [this]
             [:id :type :title :user])
      Object
      (render [this]
              (let [{:keys (title betfair user)} (om/props this)]
                (dom/div nil PLACE POINT HERE AND HIT C-j))))

**Comment by bbatsov** [comment]
We don't ship special indentation settings for `defui`, so you'll have to add them yourself. See the [manual](https://github.com/clojure-emacs/cider/blob/master/doc/Indent-Spec.md#indent-specification).

**Comment by Malabarba** [comment]
You can probably just copy the spec for defrecord.

**Comment by favetelinguis** [comment]
So then I have to add {:style/indent ...} explicitly for every defui i make like so:

    (defui Status
    {:style/indent [2 :form :form [1]]} ;; trying the example from defrecord
      static om/IQuery
      (query [this]
             [:id :type :title :user])
      Object
      (render [this]
              (let [{:keys (title betfair user)} (om/props this)]
                (dom/div nil PLACE POINT HERE AND HIT C-j))))
However this blows up in the when i try to run with error:

    PersistentArrayMap cannot be cast to clojure.lang.Named

I might have misunderstod how to do this, I was hoping there was hoping there was some way I could add it globaly and not have to explicitly add it to every defui.

**Comment by bbatsov** [comment]
No, indentation metadata should be applied to `defui` itself. As the name is fairly unique you can just use `clojure-mode`'s `put-clojure-indent` - https://github.com/clojure-emacs/clojure-mode#indentation-of-macro-forms.

**Comment by favetelinguis** [comment]
Nice got it working with this:

    (put-clojure-indent 'defui '(2 nil nil (1)))

Thanks!

**Comment by dehli** [comment]
I was trying to figure this out and changed what @favetelinguis wrote (thanks btw!)

```
(put-clojure-indent 'defui '(1 nil nil (1)))
(setq clojure-indent-style :always-indent)
```

The only problem is that `:always-indent` is applied to all of your ClojureScript. I'd like to try and only apply it to functions in the `defui` macro. I'll update this if I can figure it out!
