### ISSUE TITLE
Expose api for injecting additional middlewarep deps

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1534]
Once https://github.com/clojure-emacs/cider/issues/1531 gets solved CIDER users won't have to manually add the cider-nrepl plugin.  It would be nice if CIDER exposed an API for additional things to be added to this bootstrap process.  clj-refactor would benefit from transparent inclusion of its middleware, as would packages like clojure-flycheck aka squiggly-clojure.

**Comment by Malabarba** [comment]
Agreed. My suggestion would be a variable somewhat like this:

```el
(defvar cider-repl-dependencies
  `((cider-nrepl ,(upcase cider-version)))
  "List of Clojure dependencies for starting a REPL.
Each item is a list whose first element is the artifact name (a
symbol) and second element is the version (a string).")
```

**Comment by benedekfazekas** [comment]
we might need different vars for leiningen and boot as their CLI api has slightly different semantics.

in detail for leiningen we need to provide a list of dependenices (for nrepl 0.2.12) and plugins (cider-nrepl and refactor-nrepl). however, for boot we need list of dependcies and list of middlewares (or we could use the latter for leiningen too perhaps if we decide not to use the lein plugins provided...)

**Comment by Malabarba** [comment]
Then it probably makes sense to add a third element to that list identifying the middleware name. 

The difference in semantics (or the difference in how much information is necessary) should be handled by cider. The plugins just need to provided all necessary information, without bothering with which interface needs what.

**Comment by bbatsov** [comment]
Do we need to do something here? I guess everyone can just modify the defcustoms.

**Comment by benedekfazekas** [comment]
They are (def)vars so they don't show in customize buffers. But I don't
think there is anything here to do. Clj-refactor actually using this system
already

**Comment by bbatsov** [comment]
One less ticket then. :-)
