### ISSUE TITLE
instrumenting test with with-redefs debugs the wrong thing

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1537]
When using `with-redefs` in a test you cannot step through the test itself anymore.  Only the function being redefined with `with-redefs` is instrumented and stepped through in the debugger.

**Comment by Malabarba** [comment]
Thanks for the report. Looking into it...

**Comment by Malabarba** [comment]
I can't reproduce this. Here's what I'm trying:

```
(defn a-f [x]
  (inc x))

(deftest lala
  (with-redefs [a-f (fn [x] (* 2 x))]
    (a-f 2)))
```

I evaluate the `a-f` function normally, and I debug the `lala` test. When I run the `lala` test the debugger correctlyu takes me inside the `fn` and then shows me the result of `(a-f 2)`.

**Comment by Malabarba** [comment]
Any news on this @expez ?

**Comment by expez** [comment]
I ended up rewriting the test in question so I I can't retest this.  Since you couldn't reproduce, the general case probably works as it should and something else happened.

Sorry about the noise.
