### ISSUE TITLE
Symbol's function definition is void: string-remove-suffix

### ISSUE THREAD

**Issue by mikeivanov** [clojure-emacs/cider#1539]
Emacs 24.5 on Mac OS, Cider 20160202.926.

M-x cider-connect fails with an error message saying "nrepl-connection-identifier: Symbol's function definition is void: string-remove-suffix".

This actually happens in nrepl-client.el, line 235:
(string-remove-prefix "*cider-repl " (string-remove-suffix "*" (buffer-name conn))))

The string-remove-* functions were introduced in Emacs 24.4 and must be imported with (require 'subr-x), according to http://ergoemacs.org/emacs/elisp_trim_string.html.

**Comment by bbatsov** [comment]
Yeah, yeah. I messed up, as those were loaded from another package in my config. Not to mention they don't exist in 24.3. :-)

> The string-remove-* functions were introduced in Emacs 24.4 and must be imported with (require 'subr-x), according to http://ergoemacs.org/emacs/elisp_trim_string.html.

Really? I authored this package, so I should know better. :-)

**Comment by mikeivanov** [comment]
;-)
OK, I'm not going

**Comment by mikeivanov** [comment]
A workaround (for people hitting the same issue):

1. Open ~/.emacs.d/elpa/cider-20160202.926/nrepl-client.el
2. Add a line saying "(require 'subr-x)" somewhere at the begining
3. rm ~/.emacs.d/elpa/cider-20160202.926/nrepl-client.elc
4. Restart Emacs

**Comment by bbatsov** [comment]
Actually it's way simpler than this - just eval `(require 'subr-x)` anywhere in Emacs and that's all. There's no need to restart anything. E.g. you can do `M-:`.

**Comment by bbatsov** [comment]
Problem solved. Sorry about the inconvenience.
