### ISSUE TITLE
Wat's the recommended [current [And/OR] minimal] profiles.clj file, please!! 

### ISSUE THREAD

**Issue by Txellenne** [clojure-emacs/cider#1542]
Hi, group. I'm trying some literacy on Clojure but I'm stuck at this output:  
```lisp
; CIDER 0.11.0snapshot (package: 20160121.1400) (Java 1.8.0_71, Clojure 1.7.0, nREPL 0.2.10)
WARNING: CIDER requires nREPL 0.2.12 (or newer) to work properly
WARNING: The following required nREPL ops are not supported: 
  format-code format-edn ns-path refresh
  Please, install (or update) cider-nrepl 0.11.0-SNAPSHOT and restart CIDER
WARNING: CIDER's version (0.11.0-snapshot) does not match cider-nrepl's version (0.8.1). Things will break!
```
My `.lein/profiles.clj` is quite basic (well, I dunno whether this is good or bad, actually)
```lisp
{:user {:plugins [[cider/cider-nrepl "0.8.1"]
                  [lein-try "0.4.3"]]}}
```
& After some reading around this site, I think I should include the version of related `EMACS` pkges. These are as following, if it helps to any suggestion:
```lisp
;; all of them are new installation, not upgrading job.. 
cider-20160121.1400
clojure-mode-20160117.450
clojure-mode-extra-font-locking-20160116.321
```

**Comment by bbatsov** [comment]
> {:user {:plugins [[cider/cider-nrepl "0.11.0-SNAPSHOT"]
>                   [lein-try "0.4.3"]]}}

**Comment by bbatsov** [comment]
P.S. You should have read the warning more carefully. :-)

**Comment by bbatsov** [comment]
There's also info regarding this in the README - https://github.com/clojure-emacs/cider#setting-up-ciders-nrepl-middleware
