### ISSUE TITLE
Improve the welcome banner

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1543]
I've been thinking for a while that newcomers would benefits from an extended welcome banner with some pointers to get people started (help commands, etc). It might even make sense to inject some CIDER functions into the user namespace (e.g. some help/tutorial).

The display of this banner should be controlled via some variable, as it won't be very useful after some point.

**Comment by Malabarba** [comment]
I really like this idea. My first suggestions would be:

- A link to the readme's "Getting Started".
- A mention of the following keys:
  - C-M-x, or/and C-c C-k, or/and C-c C-e
  - C-c C-z (to "reopen this window")
  - C-h C-m (to list all cider-specific keybinds)

**Comment by bbatsov** [comment]
I've cooked something to get the ball rolling. Feel free to extend/refine it. :-)

**Comment by ackalker** [comment]
While we're at it, please make the banner display nicely in a window with 80 columns. Not all of us use Emacs with 240+ column windows (for lack of magnifying goggles), y'know ;)

**Comment by Malabarba** [comment]
Done, though the efficacy will depend on whether the user has rebound any keys.

**Comment by bbatsov** [comment]
> While we're at it, please make the banner display nicely in a window with 80 columns. Not all of us use Emacs with 120+ column windows (for lack of magnifying goggles), y'know ;)

Btw, the version message is pretty long itself, and the wrapped version doesn't look very nice on bigger displays. Anyways, @Malabarba already folded it; I just wanted to mention that both approaches have their downsides. I'd rather not fret too much on something as trivial as this.

**Comment by bbatsov** [comment]
Guess we can consider this done (at least for now).

**Comment by ackalker** [comment]
Thanks :-)
