### ISSUE TITLE
Expand the menu and divide it into several menus on the menu-bar 

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1548]
CIDER is more than a major-mode, it's an IDE. As such, it deserves to have more than one menu on the menu-bar. 

I think we should significantly expand our current menu to include almost all commands, and a significant portion of the options (though options are slightly more cumbersome to add).
Once that happens, the menu should be large enough to take up at least 3 menus on the menu-bar.

**Comment by bbatsov** [comment]
Fine by me. I originally just modeled the menu after SLIME's menu. The "influence" is so strong that `cider-repl-mode`'s menu is named just REPL which I'm guessing is confusing for some people...
