### ISSUE TITLE
cider-jack-in fails 

### ISSUE THREAD

**Issue by mgrbyte** [clojure-emacs/cider#1551]
GNU Emacs 24.5.1 x86_64-unknown-linux-gnu, GTK+ Version 3.14.14
clojure-mode version: 20160206.1042

After upgrading via package.el (melpa) to `cider-20160207.112`, I get the following traceback when invoking `cder-jack-in` (or `cider-mode`):

https://gist.github.com/mgrbyte/9e10fde3629b30a605eb

**Comment by bbatsov** [comment]
That's already fixed on master. Guess the package on Melpa will be updated
soon.

**Comment by mgrbyte** [comment]
ah, ok thanks! I did search before hand for cider-test-menu, but didn't find anything.
Sorry for the noise.
