### ISSUE TITLE
clojure-project-dir not defined

### ISSUE THREAD

**Issue by pdenno** [clojure-emacs/cider#1553]
cider-client.el and cider.el make reference to "clojure-project-dir" in function position. It does not appear to be defined. Melpa distribution cider-20160208.1007 and later are also affected, resulting in a failure to load at emacs startup.

**Comment by bbatsov** [comment]
It's defined in `clojure-mode`. I'm guessing you're using a very old version of clojure-mode. Update it and this problem will go away.

**Comment by pdenno** [comment]
Yes, that fixed it. Thanks.
