### ISSUE TITLE
CIDER error "cl-struct-define" 

### ISSUE THREAD

**Issue by aishablfgeh** [clojure-emacs/cider#1556]
After installing updates of Linux, Emacs cannot connect to Cider (0.10.2) at all. 
The error is:
Symbol's function definition is void: cl-struct-define
any ideas what could be the solution to this?
Thank you in advance.

**Comment by bbatsov** [comment]
What's your complete stacktrace? I don't see us using this function anywhere in cider.

**Comment by syohex** [comment]
This is similar to following issues. Please remove all `*.elc` files and recompile them and try again.

- https://github.com/magit/magit/issues/1838
- https://github.com/syl20bnr/spacemacs/issues/3129

**Comment by timvisher** [comment]
@syohex LOL I was about to link to my issue and there it was. :P

**Comment by Malabarba** [comment]
If you don't know how to recompile. Just delete cider, restart emacs, and install cider again.

**Comment by aishablfgeh** [comment]
Thanks every one.
Yes, I tried that and problem solved!
