### ISSUE TITLE
Add mouse-over and right-click support to symbols

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1560]
When the user hovers the mouse pointer over a symbol, we could show info such as 
1. relevant metadata, 
2. Is it a local, a Var from this namespace, or a Var from another namespace?

On right-click, we could offer all operations that act on symbols (find source, documentation, etc).

**Comment by bbatsov** [comment]
Excellent idea! A few times users have discussed with me that CIDER is not mouse-friendly (and many newcomers are not exactly Emacs ninjas...).

**Comment by cskksc** [comment]
I'd like to try this. I'll submit a PR soon.
Also, is there something else to be done for which there's no issue filed yet ? Like the docstring thing ? I really enjoyed doing that. Otherwise for the next few days, I'm gonna try and take up issues tagged with the 0.13 milestone.

**Comment by Malabarba** [comment]
Nothing in particular comes to mind, but there's always something else to be done. :-)

As for the current feature. The idea is to add a few (2 or 3) submenus inside the right-click menu listing all operations that act on a symbol-at-point. Feel free to tackle it. 👍🙏

**Comment by cskksc** [comment]
I couldn't work on this for the last two days. The PR should be ready by tomorrow.

**Comment by bbatsov** [comment]
@cskksc Any progress here?

**Comment by cskksc** [comment]
@bbastov I had forgotten about this one. Ever since I've started taking classes at the university again, I'm not getting as much time to work on CIDER as I would like. I'll try to take this up next week :-)

**Comment by Ramblurr** [comment]
Another idea along the same lines: ctrl+clicking on a var could take you to its definition. This is a common pattern in other ides.

**Comment by vemv** [comment]
I'm going to close this one simply because the years kept passing.

PRs certainly welcome.

Anyone can take a look at `cider*.el` - there should be plenty of APIs that a motivated user can leverage.
