### ISSUE TITLE
cider-apropos blows up on invalid regular expressions

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1563]
We should process those specially and give some sensible feedback to the users instead of dumping a stacktrace on them.

**Comment by Malabarba** [comment]
The regexp is used on the Clojure side, right? 
If so, should be just a matter of using a try block somewhere in there.

**Comment by bbatsov** [comment]
Yeah, there should simply be specific handling for this exception and some specific processing of the return value on the Emacs side. Perhaps as importantly - it's not really clear the search key is a regexp (just as the Emacs's own apropos). We know it, but some users probably don't...
