### ISSUE TITLE
cider's namespaces and vars should be filtered pretty much everywhere

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1564]
In a lot of places (e.g. apropos, the ns browser, etc) the users can see cider's namespaces and vars. We should filter those out (although we also need a way to not filter them while hacking on cider itself).

**Comment by cskksc** [comment]
I'd like to give this a try. Two approaches I can think of:

* Put a filtering fn in cider somewhere, and a custom var which would contain the filtering prefixes.
Then, all functions, `cider-sync-request:*`, would filter out the configured prefixes.

* Or, we could add another param to middleware requests, something like `filter?` and then the middleware would take care of this. 

Thoughts ? I like the second one better.

@bbatsov @Malabarba

**Comment by expez** [comment]
We already do this in the middleware for the dependencies we've munged with [mranderson](https://github.com/benedekfazekas/mranderson).

**Comment by cskksc** [comment]
@expez Yup. Are you referring to the [inlined-dependency](https://github.com/clojure-emacs/cider-nrepl/blob/0fa99e5f9553f3f35e026f6f5b2e7bcb6b6139cf/src/cider/nrepl/middleware/util/namespace.clj#L42) fn? Guess we'll have to add support to optionally filter out `cider.nrepl` and `refactor-nrepl` in a similar way.
