### ISSUE TITLE
cider-apropos's font-locking is messed up

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1565]
See this:

![image](https://cloud.githubusercontent.com/assets/103882/13032677/b24c2c0c-d304-11e5-8f2e-d3cfbaaa4c1d.png)

The offending code is here:

```el
(defun cider-show-apropos (summary results query docs-p)
  "Show SUMMARY and RESULTS for QUERY in a pop-up buffer, formatted for DOCS-P."
  (with-current-buffer (cider-popup-buffer cider-apropos-buffer t)
    (let ((inhibit-read-only t))
      (set-syntax-table clojure-mode-syntax-table)
      (apropos-mode)
      (cider-mode)
      (if (boundp 'header-line-format)
          (setq-local header-line-format summary)
        (insert summary "\n\n"))
      (dolist (result results)
        (cider-apropos-result result query docs-p))
      (goto-char (point-min)))))
```

Not sure why the syntax table is used here. Enabling `cider-mode` also seems redundant.

**Comment by bbatsov** [comment]
@jeffvalk do you remember why you added this - https://github.com/clojure-emacs/cider/blob/master/cider-apropos.el#L93

**Comment by jeffvalk** [comment]
Mainly for navigating/copy-and-pasting code examples that are embedded in docstrings. Has the font locking always been like this? I don't recall that...

**Comment by bbatsov** [comment]
Don't recall. But I'm pretty sure dropping this and disabling cider-mode would fix the font-locking, Probably the addition of dynamic font-locking messed this up.

**Comment by bbatsov** [comment]
This also fixed one more annoying problem - I'd get prompted about a comment delimiter when using `cider-apropos` (I'm guessing this was something to do with the syntax table).
