### ISSUE TITLE
cider-run should not create eval overlays

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1566]
It's odd when you run `cider-run` when in a source buffer, but it's even stranger when you run while in the REPL.

![image](https://cloud.githubusercontent.com/assets/103882/13032751/8e87d11a-d307-11e5-8791-8caec19fa8ef.png)

In general no evaluation command should dump overlays in the REPL buffer.

**Comment by Malabarba** [comment]
I'm taking a more general approach for this, where the overlay will not be created if we don't know where the code came from.
