### ISSUE TITLE
Clicking on folded nrepl dicts in the messages buffer results in an error

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1568]
We had this problem in the past, but @Malabarba fixed it. Guess we've got a regression.

**Comment by bbatsov** [comment]
Just verified the old fix is here https://github.com/clojure-emacs/cider/blob/master/nrepl-client.el#L1287

I'm at a loss...

**Comment by bbatsov** [comment]
Just consulted the docs:

```
Perform the action specified by a button at location pos. pos may be either a buffer position or a mouse-event. If use-mouse-action is non-nil, or pos is a mouse-event (see Mouse Events), try to invoke the button’s mouse-action property instead of action; if the button has no mouse-action property, use action as normal. pos defaults to point, except when push-button is invoked interactively as the result of a mouse-event, in which case, the mouse event’s position is used. If there’s no button at pos, do nothing and return nil, otherwise return t.
```

Seems our code is correct, but for some reason the `mouse-action` is not registered at all.

**Comment by Malabarba** [comment]
It might be an emacs bug. I'll try to reproduce on 25.1 tomorrow.

**Comment by bbatsov** [comment]
Yeah, maybe. That'd be fun. :-)

**Comment by Malabarba** [comment]
Yeah, I was working on it. Can't believe I spent half an hour on this. This is really one of Emacs dark corners. :P
