### ISSUE TITLE
Add support for variables in eldoc

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1572]
In Emacs Lisp even variables have eldoc:

![image](https://cloud.githubusercontent.com/assets/103882/13078024/43cd9582-d4c5-11e5-9828-5d8042d92369.png)

Adding this to cider should be easy.

**Comment by bbatsov** [comment]
Btw, @cskksc as you've been doing some eldoc-related work lately you might eventually take a look at this as well. Basically we just need to make eldoc consider the symbol-at-point in addition to the first symbol of the list at point (which we currently do). So in a form like `(map inc ...)` if your cursor is over `inc` you'd see its docstring and when you move forward you'd see once again the docstring for `map`.

**Comment by cskksc** [comment]
Yeah. Will do. :-)
