### ISSUE TITLE
repl fails to start with leiningen with :pedantic? :abort

### ISSUE THREAD

**Issue by pcarlisle** [clojure-emacs/cider#1573]
Since #1531.

With no ~/.lein/profiles.clj, I can create a new project, set :pedantic? :abort in the project.clj, and the new cider-jack-in that adds dependencies fails with

```
Possibly confusing dependencies found:
[org.clojure/tools.nrepl "0.2.12"]
 overrides
[org.clojure/tools.nrepl "0.2.12" :exclusions [org.clojure/clojure]]

Consider using these exclusions:


Aborting due to :pedantic? :abort
```

I believe this is because the tools.nrepl dependency is added with conj and lein already has an internal dependency on tools.nrepl so you end up with two of them.

**Comment by bbatsov** [comment]
@benedekfazekas can you take a look a this?

**Comment by bbatsov** [comment]
Anyways, even before the change cider overrode the lein dependency most of the time, so I wonder how this worked before.

**Comment by benedekfazekas** [comment]
Will have a look. Wonder if this is lein version dependent and if we should use the exclusion perhaps

**Comment by Malabarba** [comment]
I think lein previously just ignored cider's attempt at overriding that dep, which would explain why it wasn't a problem before.

**Comment by bbatsov** [comment]
@hyPiRion any thoughts on this?

Or it might just be a shortcoming of `lein-ancient`...

**Comment by benedekfazekas** [comment]
@Malabarba it seems it should have been a problem before too: testing with `[cider/cider-nrepl "0.11.0-SNAPSHOT"]` in my `~/.lein/profiles.clj` (lein 2.5.3):

```
benedek.fazekas@bf-macbook:~/projects/clj-kafka(master)$ lein repl
Possibly confusing dependencies found:
[org.clojure/tools.nrepl "0.2.10" :exclusions [jline com.sun.jmx/jmxri com.sun.jdmk/jmxtools javax.jms/jms javax.mail/mail org.clojure/clojure]]
 overrides
[cider/cider-nrepl "0.11.0-SNAPSHOT"] -> [org.clojure/tools.nrepl "0.2.12" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[cider/cider-nrepl "0.11.0-20160213.223915-27" :exclusions [org.clojure/tools.nrepl]]

Aborting due to :pedantic? :abort
```

that said @pcarlisle are you sure this is since #1531?

**Comment by benedekfazekas** [comment]
@pcarlisle are you testing with lein `2.6.x`? can you pop into cider gitter room to discuss?

**Comment by benedekfazekas** [comment]
just for the record @pcarlisle is right: if you add TNR as a dependency to your profiles.clj that solves the problem.

**Comment by hyPiRion** [comment]
So for the record, the issue is that there are multiple tools.nrepl entries in the dependency vector. We have technomancy/leiningen#2074, which should make #1531 easier to work with when it's done, and I'll peek through the implementation to see if we can defer the injection of TNR and clojure-complete into the dependency vector before it's needed.

**Comment by benedekfazekas** [comment]
at this moment I can see to easy solutions (keeping in mind that CIDER 0.11 is coming up very soon):
- warn in README that if you use `:pedantic? :abort` you still need to add TNR `0.2.12` to your profiles
- don't inject the TNR dependency at all with the new feature and perhaps add this to the wrong TNR version warning at REPL startup (eg. if you are using lein 2.5.3 or older pls edit your profiles.clj so and so)

**Comment by Malabarba** [comment]
>don't inject the TNR dependency at all with the new feature and perhaps add this to the wrong TNR version warning at REPL startup (eg. if you are using lein 2.5.3 or older pls edit your profiles.clj so and so)

I'd rather keep injecting by default. This was a big upgrade IMO and most people don't use pedantic. We can document this issue on the readme and tell people to either disable injection or disable pedantic.

**Comment by bbatsov** [comment]
I agree with @Malabarba. Let's just add this to troubleshooting and caveats for now.

@hyPiRion btw, why does lein depend on `clojure-complete`? Doesn't reply depend on it anyways?
