### ISSUE TITLE
nrepl-server-filter called, even though process buffer is dead

### ISSUE THREAD

**Issue by jonpither** [clojure-emacs/cider#1578]
Trying to debug #390. This may or may not be related:

I often see an error when I kill CIDER in windows using `cider-quit`: 

````
Debugger entered--Lisp error: (error "Selecting deleted buffer"))
nrepl-server-filter(#<process nrepl-server> "^CTerminate batch job (Y/N)? ")
````

This happens inside of `nrepl-server-filter`, specifically the line:

````
(with-current-buffer (process-buffer process))
````

TBH my knowledge of process buffers and sentinels etc is a bit naive. But it seems to me that CIDER kills the process buffer, yet this server-filter is still hanging around to intercept output from the nREPL process which is still on-going, in particular the output "Terminate batch job (Y/N)", which always happens on windows when you try to exit from batch jobs (.bat files).

So my question is, a) can you help me understand how this nrepl-server-filter is being called for a process with a dead corresponding process buffer, and b) could CIDER have some defensive code? I.e. don't call `with-current-buffer` on a potentially dead buffer.

**Comment by Malabarba** [comment]
> So my question is, a) can you help me understand how this nrepl-server-filter is being called for a process with a dead corresponding process buffer, and

I'm never quite sure when it comes to Emacs+Windows+Subprocesses, so it *is* possible, and your analysis sounds reasonable.

> b) could CIDER have some defensive code? I.e. don't call with-current-buffer on a potentially dead buffer.

If we are sure that this is happening (and I tend to agree), then yes, we should add defensive code (with comments explaining why).

**Comment by jonpither** [comment]
Thanks. I'll try out some defensive code on Monday, when I'm back in a windows environment.

**Comment by Malabarba** [comment]
Thanks. Feel free to open a PR when you have it. Should be a simple of matter of wrapping that code in a

    ;;; In Windows this can be false.
    (when (buffer-live-p (process-buffer process))
      ...
      )

**Comment by jonpither** [comment]
Yes I'll do it tomorrow
