### ISSUE TITLE
history not working with piggieback+clojurescript

### ISSUE THREAD

**Issue by johanatan** [clojure-emacs/cider#1579]
This is probably something wrong with my local config but I followed standard tutorials and everything seemed to succeed along the way. I'm using the latest Spacemacs.

**Comment by bbatsov** [comment]
History == REPL history? Some repro steps would be useful.

**Comment by johanatan** [comment]
Yes, REPL history. The repro steps for me were (on a fresh system):
https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl

particularly the "advanced" section regarding integration with Emacs.

**Comment by johanatan** [comment]
It's unclear to me how to even invoke the REPL history-- in a normal shell or emacs window the 'up' arrow will do this; however in an evil window (as in spacemacs), up actually moves the cursor to the line above. Is there a way to disable evil mode in REPL windows?

**Comment by bbatsov** [comment]
`M-p` & `M-n`.

**Comment by johanatan** [comment]
Sweeeeet! It works now, lol

**Comment by johanatan** [comment]
I would still be curious about disabling evil mode in REPL windows though...

**Comment by bbatsov** [comment]
See http://stackoverflow.com/questions/19623545/disabling-a-package-in-emacs-term-mode (just keep in mind the REPL uses `cider-repl-mode`).
