### ISSUE TITLE
Enhancement: proposed code to simplify cider-connect with boot

### ISSUE THREAD

**Issue by tmarble** [clojure-emacs/cider#1580]
I have recently had success converting some projects to use http://boot-clj.com/

In particular I used the https://github.com/Deraen/saapas with CIDER to have
a CLJS bREPL and  CLJ REPL *at the same time* -- this was awesome to live edit
both sides of the application.

I have written some crude elisp to simplify this process.... It seems like it could
usefully become part of CIDER, but I don't know where it should go (and it needs
some obvious code cleanups).

Reviews and suggestions welcome!

```
;; The following is intended to work with http://boot-clj.com/
;; after launching the project *a la* https://github.com/Deraen/saapas
;; the shell buffer has string like
;; nREPL server started on port 44918 on host 127.0.0.1 - nrepl://127.0.0.1:44918
;; The user can invoke my-cider-connect which will find that string
;; and also the most recently visited build.boot buffer to construct
;; a proper cider-connect call -- and then does calls it!
;; NOTE: For applications with both a CLJ web server and CLJS application
;; CIDER can be invoked twice! Once calling (start-repl) to initiate
;; a browser REPL and a second time to have a server REPL.

(defvar my-cider-host nil)
(defvar my-cider-port nil)
(defvar my-cider-project-dir nil)

(defun set-my-cider-project-dir (project-dir)
  (interactive "CIDER project directory: ")
  (setq my-cider-project-dir project-dir)
  (message (concat "my-cider-project-dir is now: " my-cider-project-dir)))

(defun update-my-cider-project-dir ()
  (interactive)
  (let* ((bfiles (mapcar (function buffer-file-name) (buffer-list)))
         dir)
    (dolist (bfile bfiles)
      (message bfile)
      (when (and (not dir) bfile (string-suffix-p "build.boot" bfile))
        (setq dir (file-name-directory bfile))))
    (if dir ;; found
        (setq my-cider-project-dir dir)
      (call-interactively 'set-my-cider-project-dir)) ;; prompt user
    (message (concat "my-cider-project-dir: " my-cider-project-dir))
    my-cider-project-dir))

(defun find-nrepl-host-port ()
  (interactive)
  (let* (nrepl-url host port)
    (save-excursion
      ;; go to the end of the buffer
      (goto-char (point-max))
      ;; search backwards for nrepl://127.0.0.1:33703
      (search-backward "nrepl://")
      (setq nrepl-url (buffer-substring-no-properties
                       (point) (line-end-position))))
    (when (and nrepl-url
               (string-match "nrepl://\\([^:]*\\):\\([0-9]*\\)" nrepl-url))
      (setq host (match-string 1 nrepl-url))
      (setq port (match-string 2 nrepl-url)))
    (if (and host port)
        (progn
          (message (concat "nrepl: " host ":" port))
          (setq my-cider-host host)
          (setq my-cider-port port))
      (message "nrepl: not found"))))

(defun my-cider-connect ()
  (interactive)
  (find-nrepl-host-port)
  (update-my-cider-project-dir)
  (if (and my-cider-host my-cider-port my-cider-project-dir)
      (cider-connect my-cider-host my-cider-port my-cider-project-dir)
    (message "my-cider-connect: missing host, port or project-dir")))

```

**Comment by bbatsov** [comment]
Frankly I'm not quite certain what's the problem this code would solve, so if you can provide us with more details - that'd be great.

**Comment by tmarble** [comment]
@bbatsov unlike projects with lein where we simply do `cider-jack-in` **boot** will start nrepl from the command line and then print the host/port on STDOUT. This code finds and parses the host/port to do `cider-connect`.

Alas I don't understand enough about the inner workings of boot+cider to know if a better solution is to fix `cider-jack-in` for **boot**.

**Comment by bbatsov** [comment]
> @bbatsov unlike projects with lein where we simply do cider-jack-in boot will start nrepl from the command line and then print the host/port on STDOUT. This code finds and parses the host/port to do cider-connect.

That's what leiningen does as well. It prints it and we parse it. The boot maintainers changed their output to match lein's so tools like cider would work without modifications. I was under the impression `cider-jack-in` just work with boot. 

Any boot users around to confirm this?

**Comment by Malabarba** [comment]
Cider-jack-in just works with boot for me.

**Comment by tmarble** [comment]
@Malabarba can you show me your **boot** setup?

Are you using something like https://github.com/boot-clj/boot/wiki/Cider-REPL ?

When I try it I get `Debugger entered--Lisp error: (error "nREPL: Direct connection failed")`

NOTE: emacs 24.5.1, profile.boot has `[cider/cider-nrepl "0.11.0-SNAPSHOT"]`, `BOOT_VERSION=2.5.5`

**Comment by Malabarba** [comment]
> Are you using something like https://github.com/boot-clj/boot/wiki/Cider-REPL ?

I used to use the first part of that link, yes. But the latest cider snapshots inject themselves automatically, so you don't need that anymore. Here's my entire `profile.boot`:

```clj
(require 'boot.repl)

(swap! boot.repl/*default-dependencies*
       concat '[[expectations "2.1.4"]])
```

Note that there's nothing cider-related in there. And `cider-jack-in` works on any new boot project "out of the box".

**Comment by tmarble** [comment]
@Malabarba Thanks.. I was able to get `cider-jack-in` to work fine with *.clj files.

Now the remaining use case is when I want to do CLJS bREPL development.
When I have a project with CLJS (e.g. [avenir](https://github.com/tmarble/avenir/blob/master/build.boot#L68)) things will work properly if I *temporarily* mutate **cider-boot-parameters** to be `cljs-dev repl -s wait`. I suspect I can create a boot task which will handle both
cases so I don't need to constantly change **cider-boot-parameters**.

Thanks for your help!

**Comment by Malabarba** [comment]
👍
