### ISSUE TITLE
Show corresponding cider function names in keybinding cheatsheet

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#1582]
Hey there!

I'd find it useful if each cider function name was included as a third column in the following table.

![image](https://cloud.githubusercontent.com/assets/1162994/13203975/0376cb0e-d8c4-11e5-925d-fa6cd7be0399.png)

Hopefully you can do it without much work (maybe that table is auto-generated already? In that case it would just need a tweak).

Cheers - Victor

**Comment by timvisher** [comment]
:+1: :)

**Comment by Malabarba** [comment]
I think a short, human-readable version of the command-name (like "Eval last sexp" or "Eval and replace") might be good. This way people can briefly look over the table without having to read everything.

**Comment by bbatsov** [comment]
There are many interactive commands that don't have keybindings at all. The table is not auto-generated.

> I think a short, human-readable version of the command-name (like "Eval last sexp" or "Eval and replace") might be good. This way people can briefly look over the table without having to read everything.

Is this a suggestion for another column in this table?

**Comment by Malabarba** [comment]
Yes. Or this could go in bold at the start of the second column.

**Comment by timvisher** [comment]
@Malabarba So that would be 4 columns total? I think that might be too much.

The reason I think this is a good idea is because of a very old emacs trick where you learn the names of the commands prior to learning their keybindings. Especially with tab completion or `ido-ubiquitous`, it's much easier to pick them up and then with Emacs echoing the keybinding you could have done at you every time you do it you pick up the important keybindings as you go.

**Comment by Malabarba** [comment]
> @Malabarba So that would be 4 columns total? I think that might be too much.

No, it would be 3 columns. I'm just suggesting we use short names *instead* of the full command names. I think it would be a waste of space to repeat `cider-` on every line of the table.

**Comment by bbatsov** [comment]
Well, if someone wants to work on this - be my guest! PR welcome! :-)

**Comment by Biserkov** [comment]
I'm willing to do the grunt work. Any pointers/advice?

Also, should I put the full or short (without cider-) names?

**Comment by bbatsov** [comment]
> Also, should I put the full or short (without cider-) names?
> 
> I

Add the `cider-` prefix.

> I think the function names should be the first column.

That's fine.

> I'm willing to do the grunt work. Any pointers/advice?
> 

I'd also add interactive commands that don't have keybindings. You can see a few of them in the menus.

**Comment by bbatsov** [comment]
@Biserkov any progress with this one?

**Comment by Biserkov** [comment]
Sorry about the delay, both in the actual work and in this response. Urgent family matters are keeping me occupied. Is there some sort of milestone (release, conference :-р) you would like to hit?

**Comment by bbatsov** [comment]
Not at all. I just wanted to know where are we with this.

On Monday, 21 March 2016, Jordan Biserkov <notifications@github.com> wrote:

> Sorry about the delay, both in the actual work and in this response.
> Urgent family matters are keeping me occupied. Is there some sort of
> milestone (release, conference :-р) you would like to hit?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/1582#issuecomment-199233685>
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by bbatsov** [comment]
Guess I'll close this due to lack of activity.
