### ISSUE TITLE
Eval in context for debugger

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1583]
The elisp debugger lets you stop somewhere and eval code in that context.  This is great when you want to query the locals to find out what's wrong, instead of just listing them.

**Comment by Malabarba** [comment]
Is that the `e` key?

**Comment by bbatsov** [comment]
Yep. One of the favourite features there.

**Comment by Malabarba** [comment]
I'll rephrase. :-)
Isn't that already implemented as the `e` key in CIDER's debugger?

**Comment by bbatsov** [comment]
I guess it is.
