### ISSUE TITLE
e is missing from the debugger keybinding overlay

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1585]
This caused me to open https://github.com/clojure-emacs/cider/issues/1583 yesterday

![image](https://cloud.githubusercontent.com/assets/1006557/13251401/44e47006-da30-11e5-8303-9edbe3f80936.png)

**Comment by Malabarba** [comment]
The motivation for hiding the e key was that any evaluation operates in the current debugging context. For instance, you can just keep using C-x C-e, or C-c M-: and they'll magically work in the debugger. 

IIRC, Bozhidar was against me hiding the e key, so I guess it's 2 against 1 now. :-)

**Comment by bbatsov** [comment]
> you can just keep using C-x C-e, or C-c M-: and they'll magically work in the debugger.

I was reminded about this just now, when I was going through the code. :-) I'm guessing showing `e` in the menu won't hurt.

**Comment by expez** [comment]
> For instance, you can just keep using C-x C-e, or C-c M-: and they'll magically work in the debugger.

That's awesome! ...but I'd never thought to try that.
