### ISSUE TITLE
Wrong REPL connection for ClojureScript

### ISSUE THREAD

**Issue by r0man** [clojure-emacs/cider#1587]
After running `cider-jack-in-clojurescript` CIDER uses the wrong connection to eval ClojureScript files. 

I noticed the following:

- When opening ClojureScript files without CIDER running, files are correctly put into `clojurescript-mode`. Buffers in `clojurescript-mode` should use CIDER's ClojureScript connection.
- When I start CIDER, all buffers visiting ClojureScript files that were in `clojurescript-mode` turn into `clojure-mode`.
- Now CIDER thinks those buffers are using the Clojure connection. Evaluating an expression in a ClojureScript file results in an exception, because the Clojure connection is used.
- Manually putting a ClojureScript buffer back into `clojurescript-mode` fixes the problem, but only for that buffer.
- When I open a new ClojureScript file (with CIDER running), it's buffer ends up in `clojure-mode`. Even though my `auto-mode-alist` is configured to load `clojurescript-mode`.

Somehow CIDER messes up a buffers mode, I just haven't figured out where ... :)

I see this behavior with:
- CIDER 0.11.0snapshot (package: 20160224.727)
- GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.6) of 2015-09-10 on foutrelis
- Arch Linux

**Comment by Malabarba** [comment]
>When I start CIDER, all buffers visiting ClojureScript files that were in clojurescript-mode turn into clojure-mode.

Oh my, this is bad. 😝

I'll try to reproduce this  later, but it might be good to look into your hooks and see if one of them might be misbehaving.

**Comment by Malabarba** [comment]
What do you mean by "When I start CIDER"? Do you mean a plain `cider-jack-in`?

If that's the case then I can't reproduce this. Jacking-in doesn't cause clojurescript buffers to suddenly switch mode for me.

The only cause I can think of is that you may have some misbehaving hook. What do you see when you evaluate this?

    (concat (format "cider-mode-hook: %S" cider-mode-hook)
            (format "clojure-mode-hook: %S" clojure-mode-hook)
            (format "clojurescript-mode-hook: %S" clojurescript-mode-hook)
            (format "clj-refactor-mode-hook: %S" clj-refactor-mode-hook)
            (format "cider-repl-mode-hook: %S" cider-repl-mode-hook))

**Comment by r0man** [comment]
@Malabarba I can't reproduce it either anymore. Not sure how/why I got this behavior yesterday. Those are my hooks. Do you see anything suspicious?

```
cider-mode-hook: (eldoc-mode)
clojure-mode-hook: (cider-mode yas-minor-mode projectile-mode dim-parens enable-clj-refactor-mode paredit-mode subword-mode)
clojurescript-mode-hook: (paredit-mode)
clj-refactor-mode-hook: nil
cider-repl-mode-hook: (paredit-mode subword-mode) 
```
I'm closing this now. Sorry, for the noise.

**Comment by Malabarba** [comment]
No, nothing suspicious. Let us know if it happens again.

**Comment by bbatsov** [comment]
Btw, you don't need to add `paredit-mode` to `clojurescript-mode-hook`, as parent hooks are executed for derived modes anyways.
