### ISSUE TITLE
cider-repl (read-line) not working

### ISSUE THREAD

**Issue by vivekramaswamy** [clojure-emacs/cider#1592]
Use the template below when reporting bugs. Please, make sure that
you're running the latest stable CIDER and that the problem you're reporting
hasn't been reported (and potentially fixed) already.

## Expected behavior
clojure-noob.core=> (do (print "What's your name? ") (flush) (read-line))
What's your name? vivek
"vivek"
clojure-noob.core=> 
## Actual behaviour
clojure-noob.core> (do (print "What's your name? ") (flush) (read-line))
What's your name? 
vivek
just hangs here, does not return
## Steps to reproduce the problem
just use (read-line) function on cider-repl inside emacs
This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

## Environment & Version information
emacs
### CIDER version information
cider/cider-nrepl "0.9.1"
Include here the version string displayed when
CIDER's REPL is launched. Here's an example:

```
; CIDER 0.11.0snapshot (package: 20151112.1551) (Clojure 1.7.0, nREPL 0.2.12)
```

### Emacs version

24.5

### Operating system

mac osx al-capatain

**Comment by bbatsov** [comment]
Works just fine for me (tested on the current `master`).

**Comment by bbatsov** [comment]
P.S. You should upgrade to at least 0.10.2. 0.9 is way too old these days.
