### ISSUE TITLE
Debug namespace

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1597]
I was thinking that it might be useful to be able to debug all functions in a namespace. Perhaps you'd be debugging some function calling out to several functions in the namespace and this would be more convenient than finding and instrumenting those manually. We already have similar functionality for tracing.

**Comment by bbatsov** [comment]
@Malabarba how easy would be do to something like this?

**Comment by Malabarba** [comment]
The simplest way would be to visit the file and instrument each top-level sexp (by evaluating it with #dbg as a prefix). 

The difficulty is that it would have to be done one at a time. I believe it won't work if you instruments the whole file in the same message (although I didn't actually test).

**Comment by bbatsov** [comment]
That sounds reasonable. I'm guessing if try to instrument something like `(+ 1 2 3)` this will simply be ignored.

**Comment by Malabarba** [comment]
Yes, but that's only because everything in there is a constant. If you try to instrument a similar expression with variables in it, the debugger will be triggered immediately.

We could partially avoid that by only adding the #dbg to a top-level sexp if it is a def. But that still wouldn't be foolproof.

**Comment by bbatsov** [comment]
True, but few things in cider are foolproof. :-) I'm guessing filtering just the top-level defs will be good enough for most people.

**Comment by vspinu** [comment]
I personally never needed such a feature. What would be more useful IMO is to be able to select a region, `C-u C-M-x` on it, and have all forms within the region debugged.
