### ISSUE TITLE
Error when test makes 0 assertions

### ISSUE THREAD

**Issue by amoe** [clojure-emacs/cider#1599]
## Expected behavior

Cider should either proceed as normal and say that zero assertions passed, or warn the user that they defined a test that had zero assertions.

## Actual behavior

Message from emacs: `error in process filter: Wrong type argument: stringp, nil`

Stack trace:

    Debugger entered--Lisp error: (wrong-type-argument stringp nil)
      propertize(nil face font-lock-type-face)
      cider-propertize(nil ns)
      cider-test-echo-summary((dict "error" 0 "fail" 0 "ns" 1 "pass" 0 "test" 0 "var" 1) (dict))
      #[257 "\306" <a lot of strange output that goes on for a long time on a long line>
      nrepl--dispatch-response((dict "id" "14" "results" (dict) "session" "3b6d0ec7-7c66-49e4-ba64-cf1bb2499309" "summary" (dict "error" 0 "fail" 0 "ns" 1 "pass" 0 "test" 0 "var" 1) "testing-ns" "wn-prototype.users-test"))
      nrepl-client-filter(#<process nrepl-connection> "d2:id2:147:resultsde7:session36:3b6d0ec7-7c66-49e4-ba64-cf1bb24993097:summaryd5:errori0e4:faili0e2:nsi1e4:passi0e4:testi0e3:vari1ee10:testing-ns23:wn-prototype.users-teste")

## Steps to reproduce the problem

This is a mistake by the user, they meant to write `(is (= 2 2))`, but it shouldn't be an error.

    (ns wn-prototype.users-test
      (:require [clojure.test :refer :all]))

    (deftest my-test
      (testing "something"
          (= 2 2)))

Run this test.  

### CIDER version information

    ;; Connected to nREPL server running on port 33122 on host localhost - nrepl://localhost:33122
    ;; CIDER 0.11.0 (package: 20160302.2126) (Bulgaria), nREPL 0.2.12
    ;; Clojure 1.7.0, Java 1.7.0_91

### Emacs version

24.5.1

### Operating system

Debian unstable

**Comment by RickMoynihan** [comment]
Thanks a lot
