### ISSUE TITLE
cider-test-run-project-tests runs 0 tests

### ISSUE THREAD

**Issue by sooheon** [clojure-emacs/cider#1600]
## Expected behavior

`cider-test-run-project-tests` should run all tests defined in project.
## Actual behavior

```
Running tests in all project namespaces...
0 namespaces: Ran 0 tests. 0 failures, 0 errors.
```
## Steps to reproduce the problem

Add simple test to core namespace (i.e. `(deftest test-test (is (= 1 1)))`), check that `cider-test-run-ns-tests` functions properly, and then try calling `cider-test-run-project-tests`
### CIDER version information

```
;; CIDER 0.11.0snapshot (package: 20160302.1321), nREPL 0.2.12
```
### Emacs version

GNU Emacs 24.5.1 (x86_64-apple-darwin15.2.0, NS apple-appkit-1404.34)
### Operating system

OSX El Capitan

**Comment by bbatsov** [comment]
Are you sure your tests are on the classpath?

**Comment by sooheon** [comment]
`, classpath` in the cider repl shows me that my test files are there..

This is the backtrace I'm getting now, calling `cider-test-run-project-tests` (and `cider-test-run-loaded-tests`):

```
Debugger entered--Lisp error: (error "Wrong number of arguments")
  propertize("Ran %s tests, but found no assertions.Did you forget to use `is'?" cider-test-failure-face)
  cider-test-echo-summary((dict "error" 0 "fail" 0 "ns" 0 "pass" 0 "test" 0 "var" 0) (dict))
  #[257 "\306\307\"\306\310\"\306\311\"\306\312\"\306\313\"\314\235\203$\315\316\317\300\320\"\"\202\211\203.\321!\202\211\211\2038\322!\202\211\205\211\306\323\"\306\324\"\325!\210\326\"\210\327\\!\203b\203o\330\331\f
\"#\202\207\332\f!\205\207r\fq\210\333\334 \210*\330\f#\266\202\207" [:project cider-test-last-summary cider-test-last-results cider-test-show-report-on-success cider-test-report-buffer cider-auto-select-test-report-buffer nrepl-dict-get "summary" "results" "status" "out" "err" "namespace-not-found" message "No test namespace: %s" cider-propertize ns cider-emit-interactive-eval-output cider-emit-interactive-eval-err-output "error" "fail" cider-test-highlight-problems cider-test-echo-summary zerop cider-test-render-report cider-popup-buffer get-buffer t erase-buffer inhibit-read-only] 12 "\n\n(fn RESPONSE)"]((dict "id" "578" "results" (dict) "session" "9405d6d0-2973-4957-bc97-456b1cca8f84" "summary" (dict "error" 0 "fail" 0 "ns" 0 "pass" 0 "test" 0 "var" 0) "testing-ns" nil))
  nrepl--dispatch-response((dict "id" "578" "results" (dict) "session" "9405d6d0-2973-4957-bc97-456b1cca8f84" "summary" (dict "error" 0 "fail" 0 "ns" 0 "pass" 0 "test" 0 "var" 0) "testing-ns" nil))
  nrepl-client-filter(#<process nrepl-connection> "d2:id3:5787:resultsde7:session36:9405d6d0-2973-4957-bc97-456b1cca8f847:summaryd5:errori0e4:faili0e2:nsi0e4:passi0e4:testi0e3:vari0ee10:testing-nsleed2:id3:5787:session36:9405d6d0-2973-4957-bc97-456b1cca8f846:statusl4:doneee")
```

**Comment by Malabarba** [comment]
That last one's my fault. Just fixed it now, so we should be back to your previous problem.

Are you sure you've loaded the tests file?

**Comment by sooheon** [comment]
Yep, I continue to get `Ran 0 tests, but found no assertions.Did you forget to use `is'?` message, even after `C-c C-k` in the tests buffer, and confirming that the same tests will run with `cider-test-run-ns-tests`.

**Comment by Malabarba** [comment]
I just managed to reproduce this on boot. Are you using boot?

**Comment by Malabarba** [comment]
The cause is in this function, from `namespace.clj`.

    (defn project-namespaces
      "Find all namespaces defined in source paths within the current project."
      []
      (->> (cp/classpath-directories)
           (filter #(re-find (re-pattern (str "^" project-root))
                             (str %)))
           (mapcat ns-find/find-namespaces-in-dir)))

In boot, the `project-root` is something like `"/home/artur/project-name/"`, but all the dirs returned by `(cp/classpath-directories)` are inside `"~/.boot"` (as weird as that seems). Because of that, the function always returns an empty list.

One option is to ditch that method, and replace it with the method used by the state-tracker.

    (def jar-namespaces
      (->> (cp/classpath-jarfiles)
           (mapcat ns-find/find-namespaces-in-jarfile)
           (into #{})))

    (defn project-namespaces
      "Find all namespaces defined in source paths within the current project."
      []
      (->> (map ns-name (all-ns))
           (remove jar-namespaces)))

This works for me in boot, but it includes a few false positives (namespaces created in weird ways, that don't have a corresponding jar file).
Still, I think false positives are better than false negatives in this scenario.

**Comment by bbatsov** [comment]
We've got some code to detect we're in a boot project, so I guess we should leverage it here. That's what we have been doing so far.

**Comment by bbatsov** [comment]
See - https://github.com/clojure-emacs/cider-nrepl/blob/2a336e9c3575f747212e846dc34da5e1f71c708c/src/cider/nrepl/middleware/info.clj#L15

**Comment by jeffvalk** [comment]
If a boot-compatible definition is approximate (allows false positives), I'd think branching with `boot-project?` here is preferable, as the current definition should be correct using leiningen.

**Comment by bbatsov** [comment]
Yep, that's what I meant.

**Comment by bbatsov** [comment]
Any volunteers to apply and test the suggested fix?

**Comment by bbatsov** [comment]
No volunteers I guess. :-)

**Comment by bkruczyk** [comment]
It looks like @Malabarba already applied mentioned [fix](https://github.com/clojure-emacs/cider-nrepl/blob/edde9fc83dbb1489b4f9fb152b7c0cc55856b566/src/cider/nrepl/middleware/util/namespace.clj#L35).

Runnig `cider-test-run-project-tests` works after loading buffer into repl (`C-k C-l`).

**Comment by xiongtx** [comment]
`cider-load-file` is `C-c C-l`, not `C-k C-l`.

**Comment by bkruczyk** [comment]
Right, I meant `C-c C-k` i.e. `cider-load-buffer`.

**Comment by xiongtx** [comment]
@bbatsov This seems like it can be closed.
