### ISSUE TITLE
After expression evaluation cursor is moving to the beginning of buffer

### ISSUE THREAD

**Issue by novakboskov** [clojure-emacs/cider#1601]
After perform `cider-eval-last-sexp`(`C-x C-e`) or `cider-load-buffer`(`C-c C-k`) cursor is moving to the beginning of buffer (or sometimes at the beginning of line) instead of stay at the position showing result in the line continuation.

Cider 20160303.1214
Emacs 24.5.3
Ubuntu 14.04

**Comment by Malabarba** [comment]
Ops. My bad. Thanks for the fix @cichli

**Comment by cichli** [comment]
No worries :-).

**Comment by novakboskov** [comment]
All fine
