### ISSUE TITLE
Inspector hangs on infinite lazy seqs inside something else

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1602]
1. In a Clojure buffer, write `(repeat 1)` and run `cider-inspect`. 
2. Note that inspector correctly renders the infinite sequence.
3. Now replace that with `{'a (repeat 1)}` and run `cider-inspect` again.
4. CIDER hangs.

**Comment by Malabarba** [comment]
A user on slack reported that this worked fine on 0.10, so it's probably a recent regression.
@alexander-yakushev any ideas?

**Comment by base698** [comment]
Thanks again!
