### ISSUE TITLE
error in process filter when printing system map in repl

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1612]
## Expected behavior

no errors in process filter 
## Actual behavior
```
error in process filter: Scan error: "Unbalanced parentheses", 68, 1028
error in process filter: forward-sexp: Scan error: "Unbalanced parentheses", 991, 1034
error in process filter: Scan error: "Unbalanced parentheses", 991, 1034
error in process filter: forward-sexp: Scan error: "Unbalanced parentheses", 71, 1025
error in process filter: Scan error: "Unbalanced parentheses", 71, 1025
error in process filter: forward-sexp: Scan error: "Unbalanced parentheses", 197, 1036
error in process filter: Scan error: "Unbalanced parentheses", 197, 1036
error in process filter: forward-sexp: Scan error: "Unbalanced parentheses", 828, 1025
error in process filter: Scan error: "Unbalanced parentheses", 828, 1025
error in process filter: forward-sexp: Scan error: "Unbalanced parentheses", 220, 1025
error in process filter: Scan error: "Unbalanced parentheses", 220, 1025
error in process filter: forward-sexp: Scan error: "Unbalanced parentheses", 714, 1025
error in process filter: Scan error: "Unbalanced parentheses", 714, 1025
error in process filter: forward-sexp: Scan error: "Unbalanced parentheses", 273, 1029
error in process filter: Scan error: "Unbalanced parentheses", 273, 1029
```

etc in `*messages*`

REPL freezes midway in printing a largish data structure, but actually finished eventually (~2 minutes while filing this report).

## Steps to reproduce the problem

Happened with `reloaded/restart`in the repl which prints the `system` map so I'm guessing it's  related to a pprint response.
### CIDER version information

Include here the version string displayed when
CIDER's REPL is launched. Here's an example:

```
;; Connected to nREPL server - nrepl://localhost:36196
;; CIDER 0.12.0snapshot (package: 20160308.539), nREPL 0.2.12
;; Clojure 1.7.0, Java 1.8.0_66
```

### Emacs version

24.5.1

### Operating system

Linux

**Comment by expez** [comment]
If I do `(do (reset) nil)`, instead of just `(reset)` the system map isn't printed to the repl and I can continue my day.

**Comment by Malabarba** [comment]
What's the system map? :-)

**Comment by Malabarba** [comment]
Or (more importantly) what does it look like?

**Comment by expez** [comment]
It's a map full of various crap.  Some of it isn't `read`able.  I got the same process filter error when running c.t.n/reload manually at the repl.  That too printed unbalanced / unreadable data. 

I tried triggering this by just evaluating various `println` statements but that didn't do it.
