### ISSUE TITLE
cider-refresh fails if cider-refresh-before-fn or cider-refresh-after-fn are set to functions which aren't loaded

### ISSUE THREAD

**Issue by codahale** [clojure-emacs/cider#1613]
## Expected behavior

It would be nice if it logged a warning about the functions not existing, but still ran the refresh.

## Actual behavior

Throws an exception when it tries to reference the var.

## Steps to reproduce the problem

1. Set `cider-refresh-before-fn` and `cider-refresh-after-fn` to functions in your application.
2. Accidentally introduce an error in a file in your application. (Whoops.)
3. Run `cider-refresh`.
  1. It runs `cider-refresh-before-fn`, which does something like shut down your application.
  2. It unloads the modified namespaces.
  3. It tries to load the modified namespaces, but encounters the error from step 2.
  4. It displays the error from step 2.
4. Fix the error from step 2. (Hopefully.)
5. Run `cider-refresh` again.
6. CIDER throws an exception because `cider-refresh-before-fn` was unloaded in step 3/ii but was not reloaded.
7. :frowning: 
8. Kill the CIDER repl process and jack-in all over again.

### CIDER version information

```
;; CIDER 0.12.0snapshot (package: 20160310.330), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_72
```

### Emacs version

24.5

### Operating system

MacOS 10.11.3

**Comment by bbatsov** [comment]
Makes sense. @cichli would you, please, look into this?

**Comment by bbatsov** [comment]
@dpsutton And another `cider-refresh` bug? ;-)

**Comment by dpsutton** [comment]
Cleaning up something in the elisp code and I'll get on this @bbatsov

**Comment by dpsutton** [comment]
I'm looking into this. Right now it throws an error when the function can't work. I'm thinking of removing the illegal argument exception when it can't resolve the symbol and substituting its own function that just writes couldn't resolve whatever. What do these functions look like, and where do they typically write? Do I want to put something into the messages buffer, or can i just write to *out*? 

If I can write to *out*, I'm thinking that if I can't resolve the function, I'll just substitute my own function stating so as the before and after function. This allows all of the logic to remain inside of the function rather than at call sites with `(when (symbol-loaded? after) (resolve-and-invoke after msg))`

**Comment by bbatsov** [comment]
> What do these functions look like, and where do they typically write? Do I want to put something into the messages buffer, or can i just write to out?

Not sure what you mean by this. Generally putting something in *messages* is not the best course of action, as people often don't notice such messages. Outputting some warning to the REPL or showing the `cider-refresh` status buffer might be better.

**Comment by dpsutton** [comment]
Agreed. I've got a working prototype right now where it tries to call the function provided and falls back to a some type of notification if the function cannot be found. Unfortunately, after running once I'm getting error messages that the debugger is unattached. I think I have observed this when running nrepl locally so its tough to distinguish effects of my changes from trying to run the local version of nrepl in other projects.

**Comment by dpsutton** [comment]
I've got it testing and working. Gonna use it locally for a few days. Little worried about cljs stuff as I don't use that much.

**Comment by dpsutton** [comment]
```
(<-- 
  before  "bobby"
  id  "12"
  session  "746abbb5-2bd8-440b-9822-885c78506c41"
  status  ("invoking-before")
)
(<-- 
  before  "bobby"
  id  "12"
  session  "746abbb5-2bd8-440b-9822-885c78506c41"
  status  ("invoked-not-resolved")
)
```

**Comment by bbatsov** [comment]
I'm a bit confused by the two statuses. What's the purpose of the first status? Just a notice that we're trying to invoke the before-fn?

I'd also use names like `invoking-refresh-before-fn` and `refresh-before-fn-not-resolved`.

**Comment by dpsutton** [comment]
The first is currently what it does. And If it could not resolve the function it would just error, preventing refreshing. It now tries to resolve the function, and if not, sends back a message that the function could not be resolved. The latter message is new while the former is currently there. There is a sequence of 

1. refreshing
2. invoking-function 
3. invoked-function
4. done

I've changed 3 to be either the current invoked-function or invoked-not-resolved. It writes to the refresh log but i'm not sure how to make it shout out to the repl so its a little more in your face.

**Comment by bbatsov** [comment]
Got it. 

> I've changed 3 to be either the current invoked-function or invoked-not-resolved. It writes to the refresh log but i'm not sure how to make it shout out to the repl so its a little more in your face.

I guess that'd be good enough for now. I might cut a new CIDER as soon as tomorrow for selfish reasons. :-)

**Comment by dpsutton** [comment]
I can reduce the steps if we like. Note this will require new versions of
nrepl as well as cider at the same time. I can get the requests out today.
All tests are passing just had a meeting at work when I was setting up the
pull requests

**Comment by bbatsov** [comment]
Regarding the steps - it's seems to be there should be "resolving" step, before trying to invoke something, but I can live with the current step structure. It just feels a bit odd to see "invoking-something" and then "invoked-not-resolved". Updating `cider-nrepl` is not an issue - updating the snapshot is trivial. I do after every PR I merge for it.

**Comment by codahale** [comment]
Awesome! Thank you!
