### ISSUE TITLE
keep eval overlay on screen

### ISSUE THREAD

**Issue by pvinis** [clojure-emacs/cider#1614]
## Expected behavior
i would like to have an option to keep the eval overlays on screen

## Actual behavior
is there such an option?
Include here the version string displayed when
CIDER's REPL is launched. Here's an example:

```
; CIDER 0.12.0snapshot (package: 20160310.330)
```

### Emacs version

24.5

### Operating system
osx 10.11

**Comment by Malabarba** [comment]
Yes there is. The name is something like cider-overlay-duration, but I'm not 100% sure.

**Comment by pvinis** [comment]
i need them to sray even after moving the point though. i will try when im
back on the computer and report back.

-- 
Pavlos Vinieratos

**Comment by bbatsov** [comment]
I don't think that's a good idea - e.g. imagine the effect of one big result... Why would you want to do something like this?

**Comment by pvinis** [comment]
as long as there is a way to also hide an eval result, its fine. in
lighttable the results either get shortened and you have to click on them
to reveal the full thing, or you just leave it there and other code gets
pushed down. so shortening, ability to hide, or push code down would be
possible solutions.

-- 
Pavlos Vinieratos

**Comment by bbatsov** [comment]
@Malabarba Thoughts?

**Comment by Malabarba** [comment]
The name of the variable I forgot is `cider-eval-result-duration` 

    (setq cider-eval-result-duration nil)

The overlay is cleared whenever you evaluate something around it, or kill the sexp before it.

**Comment by pvinis** [comment]
ok i will try that now

**Comment by pvinis** [comment]
i tried `(setq cider-eval-result-duration nil)` but when i move the cursor it still disappears.

**Comment by Malabarba** [comment]
Are we talking about the results you get with code evaluation? Like C-x C-e or C-c C-c? 
It works for me.

**Comment by pvinis** [comment]
yes exactly. i want the results to stay when i move the cursor. but they always go away after moving. that works for you?

**Comment by Malabarba** [comment]
Yes, it does. :-/

**Comment by pvinis** [comment]
is `cider-eval-result-duration` the only thing that you have set? like if you try with a clean cider, set that to nil and it works for you?
i will try it again..

**Comment by Malabarba** [comment]
Yes. Just tested it now.

**Comment by pvinis** [comment]
indeed it worked. i must set up something wrong. cool.
how do i dismiss it now? or truncate it so i see only a part of it?

**Comment by Malabarba** [comment]
You can't truncate it. If it's super long you can do `M-x toggle-truncate-lines` so it won't be folded back into the screen (this is just Emacs, not really cider).

The overlay goes away if you delete what's around it, or if you reevaluate the code-block (though in this case it will get replace by a new overlay, which might just look the same). 
It's far from optimal, but this is really just a niche option made available for those who want it.

**Comment by bbatsov** [comment]
I guess we can close this then.
