### ISSUE TITLE
CIDER assigning Clojurescript buffers to Clojure REPL

### ISSUE THREAD

**Issue by seanirby** [clojure-emacs/cider#1619]
So this started happening to me a couple days ago where in the middle of development I'll notice that the cljs buffer I've been working in is suddenly assigned to a clojure repl, meaning I can't use CIDER to it's fullest extent.  I really wish I knew what caused it but it seems to happen randomly and it seems to go away randomly too :/ .  It could totally be something I'm doing incorrectly but I'm not sure so I'll try and give as much relevant information as I can.

CIDER version: 0.12.0snapshot

Invoking CIDER from a .cljs file in my project with <kbd>C-c M-J</kbd>.  

I'm currently using figwheel along with Clojurescript and I've followed the directions in the README by adding the following to my init:

```
(setq cider-cljs-lein-repl "(do (use 'figwheel-sidecar.repl-api) (start-figwheel!) (cljs-repl))")
```

My ```project.clj```

```
(defproject komokio "0.1.0-SNAPSHOT"
  :description ""
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :dependencies [[org.clojure/clojure "1.8.0-RC5"]
                 [org.clojure/core.async "0.2.374"]
                 [org.clojure/clojurescript "1.7.228"]
                 [org.clojure/tools.nrepl "0.2.12"]
                 [org.omcljs/om "1.0.0-alpha30"]
                 [com.cemerick/piggieback "0.2.1"]
                 [org.clojure/clojure "1.7.0"]
                 [figwheel-sidecar "0.5.0-2"]
                 ]

  :clean-targets ^{:protect false} ["resources/public/js/out"]

  :source-paths ["src/clj" "src/cljs"]

  :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}

  :cljsbuild {:builds
              [{:id "dev"
                :figwheel true
                :source-paths ["src/cljs"]
                :compiler {:main komokio.core
                           :asset-path "js/out"
                           :output-to "resources/public/js/main.js"
                           :output-dir "resources/public/js/out"
                           :parallel-build true
                           :compiler-stats true
                           :verbose true}}]}

  :figwheel {:validate-config true
             :css-dirs ["resources/public/css/out"]
             :server-port 3000})
```

This affects all cljs buffers I open and the  ```cider-repl-type``` buffer-local variable for each one is equal to "clj".  

Let me know if you need anything else from me.

**Comment by Malabarba** [comment]
The value of `cider-repl-type` in source files is irrelevant. All that matters is the value of this variable on the REPL buffers. That is the `*cider-repl komokio*` and its CLJS analogue. Could you check the value on these two buffers when the problem comes up again?

**Comment by seanirby** [comment]
So my project was inside of a Dropbox synced folder.  This usually presents no problems since I'm only accessing it from one machine at a time but I've since learned that this isn't a good idea.

When I move the project out of the synced folder then everything works as expected.  I think that's what was causing the issue so I'll go ahead and close this.  If it happens to come back I'll take note of ```cider-repl-type```  and reopen.  Thanks.

**Comment by Malabarba** [comment]
NP
