### ISSUE TITLE
Expression results not printed in repl

### ISSUE THREAD

**Issue by JvJ** [clojure-emacs/cider#1620]
Use the template below when reporting bugs. Please, make sure that
you're running the latest stable CIDER and that the problem you're reporting
hasn't been reported (and potentially fixed) already.

## Expected behavior

Typing an expression in the repl prints the result of that expression.

## Actual behavior

The expression is evaluated, but the result is not printed.  Additionally, it takes several seconds longer than it should for the expression to complete.

## Steps to reproduce the problem

Jack into nrepl from a clojure file using C-c M-j.
Try evaluating any expression.  The result does not print.

## Environment & Version information

I am using the following in my dev profile:
`:plugins [[lein-cljsbuild "1.1.2"]
                             [lein-figwheel "0.5.0-4"]
                             [cider/cider-nrepl "0.12.0-snapshot"]]
                   :dependencies [[reloaded.repl "0.2.1"]
                                  [lein-figwheel "0.5.0-4"]
                                  [com.cemerick/piggieback "0.2.1"]
                                  [org.clojure/tools.nrepl "0.2.12"]]`

### CIDER version information

Include here the version string displayed when
CIDER's REPL is launched. Here's an example:

```
; CIDER 0.12.0snapshot (package: 20160313.2315), nREPL 0.2.12
```

### Emacs version

E.g. 24.5

### Operating system

E.g. Windows 10

**Comment by bbatsov** [comment]
This certainly works for me, so you'll have to be more specific.

**Comment by Malabarba** [comment]
It would also help to see the contents of your `*nrepl-messages ...*` buffer when this happens.

**Comment by bbatsov** [comment]
Closing due to lack of additional information.
