### ISSUE TITLE
cider-jack-in starts nrepl but does not connect

### ISSUE THREAD

**Issue by elarkin** [clojure-emacs/cider#1621]
Use the template below when reporting bugs. Please, make sure that
you're running the latest stable CIDER and that the problem you're reporting
hasn't been reported (and potentially fixed) already.

## Expected behavior

cider-jack-in starts and then connects to an nrepl corresponding to the current clojure project

## Actual behavior

cider-jack-in starts the nrepl, reports that it is connected, but does not connect to nrepl

## Steps to reproduce the problem

(I have no global lein profiles)
lean new project-name
find-file src/project-name/core.clj
cider-jack-in

## Environment & Version information

\*nrepl-messages \*nrepl-connection\* buffer contains:
>(--> 
>  op  "clone"
>  id  "1"
>)
>(<-- 
>  id  "1"
>  new-session  "328fc25b-0e29-492a-bdfe-546c44dd7d58"
>  session  "2db806e6-8be7-4937-8e22-82f11038cb25"
>  status  ("done")
>)
>(--> 
>  op  "clone"
>  id  "2"
>)
>(<-- 
>  id  "2"
>  new-session  "5c7f62be-0752-41e1-a23c-8795492dd245"
>  session  "8d3b9bc6-ecb5-4c5c-9520-e749dcfd7f8c"
>  status  ("done")
>)
>(--> 
>  op  "describe"
>  session  "328fc25b-0e29-492a-bdfe-546c44dd7d58"
>  id  "3"
>)
>(<-- 
>  aux  (dict 
>         current-ns  "user")
>  id  "3"
>  ops  (dict 
>         apropos  (dict)
>         artifact-list  (dict)
>         artifact-versions  (dict)
>         classpath  (dict)
>         clean-ns  (dict)
>         clone  (dict)
>         close  (dict)
>         complete  (dict)
>         complete-doc  (dict)
>         debug-input  (dict)
>         debug-instrumented-defs  (dict)
>         debug-middleware  (dict)
>         describe  (dict)
>         eldoc  (dict)
>         eval  (dict)
>         extract-definition  (dict)
>         find-symbol  (dict)
>         find-used-locals  (dict)
>         find-used-publics  (dict)
>         format-code  (dict)
>         format-edn  (dict)
>         hotload-dependency  (dict)
>         info  (dict)
>         init-debugger  (dict)
>         inspect-next-page  (dict)
>         inspect-pop  (dict)
>         inspect-prev-page  (dict)
>         inspect-push  (dict)
>         inspect-refresh  (dict)
>         inspect-set-page-size  (dict)
>         interrupt  (dict)
>         load-file  (dict)
>         ls-sessions  (dict)
>         macroexpand  (dict)
>         namespace-aliases  (dict)
>         ns-list  (dict)
>         ns-list-vars-by-name  (dict)
>         ns-path  (dict)
>         ns-vars  (dict)
>         out-subscribe  (dict)
>         out-unsubscribe  (dict)
>         pprint-middleware  (dict)
>         refresh  (dict)
>         refresh-all  (dict)
>         refresh-clear  (dict)
>         rename-file-or-dir  (dict)
>         resolve-missing  (dict)
>         resource  (dict)
>         resources-list  (dict)
>         retest  (dict)
>         stacktrace  (dict)
>         stdin  (dict)
>         stubs-for-interface  (dict)
>         test  (dict)
>         test-all  (dict)
>         test-stacktrace  (dict)
>         toggle-trace-ns  (dict)
>         toggle-trace-var  (dict)
>         track-state-middleware  (dict)
>         undef  (dict)
>         version  (dict)
>         warm-ast-cache  (dict)
>         warm-macro-occurrences-cache  (dict))
>  session  "328fc25b-0e29-492a-bdfe-546c44dd7d58"
>  status  ("done")
>  versions  (dict 
>              clojure  (dict 
>                         incremental  0
>                         major  1
>                         minor  8
>                         version-string  "1.8.0")
>              java  (dict 
>                      incremental  "0"
>                      major  "1"
>                      minor  "8"
>                      update  "74"
>                      version-string  "1.8.0_74")
>              nrepl  (dict 
>                       incremental  "12"
>                       major  "0"
>                       minor  "2"
>                       qualifier  ""
>                       version-string  "0.2.12"))
>)

\*Messages\* buffer contains:
>Starting nREPL server via lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.2.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.11.0\"\] -- repl :headless...
>nREPL server started on 62160
>nREPL: Establishing direct connection to localhost:62160 ...
>nREPL: Direct connection established
>Connected.  Write you some Clojure for Great Good!

\*nrepl-server project-name\* buffer contains:
>nREPL server started on port 62160 on host 127.0.0.1 - nrepl://127.0.0.1:62160

When I try to eval the buffer:
>user-error: `cider-eval-defun-at-point' needs a Clojure REPL.
>If you don't know what that means, you probably need to jack-in (`C-c M-j').

Further, when I execute cider-connect on host 127.0.0.1 and port 62160, it says:
>user-error: `cider-connect' needs an active nREPL connection

### CIDER version information

I cannot start a cider repl. cider is version 0.11.0 pinned to melpa-stable.

### Emacs version

E.g. 24.5.1

### Operating system

E.g. OSX 10.11.3 (El Capitan)

### Comments

I'm sure that I haven't included all necessary information to debug the issue, I'd be happy to supply more information, but I'm not sure what would even be useful.

This issue only started to occur upon upgrading to 0.11.0. Before I was on 0.8.2 and things worked alright.

**Comment by bbatsov** [comment]
Likely there's something outdated in your setup. So much has changed since 0.8.2... What's in your cider config?

**Comment by elarkin** [comment]
I do not have anything in my .emacs.d/init.el related to cider. Is there another file that I should be looking at?

**Comment by elarkin** [comment]
sorry, nothing other than a hook to turn cider-mode on when I enter clojure-mode

**Comment by bbatsov** [comment]
What's your `clojure-mode` version?

**Comment by elarkin** [comment]
I currently get that one from melpa: 20160314.2147 (latest)

**Comment by elarkin** [comment]
Well, by paring down my config to nothing but cider, I've got a cider real. One of these packages is causing the interference:

async-20160223.146
auctex-11.89.1
cider-0.11.0
clj-refactor-20160303.536
clojure-mode-20160314.2147
color-theme-20080305.34
color-theme-solarized-20160219.924
csharp-mode-20160217.1211
dash-20160306.1222
edn-20160215.419
emmet-mode-20151213.738
epl-20150326.1212
epl-20150517.433
evil-20160315.949
git-commit-20160130.649
goto-chg-20131228.1459
highlight-20151231.1337
hydra-20160304.1157
inflections-20121016.157
js2-mode-20160318.846
magit-20160312.2307
magit-popup-20160302.322
midje-mode-20150430.1255
midje-mode-20150921.1750
moe-theme-20160216.1821
multiple-cursors-20160304.659
paredit-20150217.713
peg-20150707.2341
pkg-info-20140610.630
pkg-info-20150517.443
queue-0.1.1
rainbow-delimiters-20150320.17
restclient-20150421.324
restclient-20151128.1512
s-20160313.2240
scss-mode-20150107.1400
seq-1.11
smartparens-20160225.705
spinner-1.7
undo-tree-20140509.522
web-mode-20160308.1556
with-editor-20160223.1155
yasnippet-20160226.1359

I guess this can be closed as invalid.

**Comment by elarkin** [comment]
Deleting .emacs.d/elpa and re-downloading my packages (without changing any of my config) **ALSO** fixed my issue.

bbatsov, I'm sorry for wasting your time.

**Comment by bbatsov** [comment]
No problem.

**Comment by endrebak** [comment]
Same here - `rm -rf .emacs.d` did the trick.

> "If you don't think managing state is tricky, consider the fact that 80% of all problems in all complex systems are fixed by rebooting." - Stuart Halloway
