### ISSUE TITLE
cider-test-run-ns-tests fails if no assertions are made

### ISSUE THREAD

**Issue by ericnormand** [clojure-emacs/cider#1623]
If I make a test in a new namespace but the test does nothing, `cider-test-run-ns-tests` fails to report anything but fails with the following message in Emacs. 

> error in process filter: Wrong type argument: stringp, nil

## Expected behavior

CIDER should report passing tests (green) with 1 test and 0 assertions.

## Actual behavior

CIDER fails and reports an error.

## Steps to reproduce the problem

Create a new project with `lein new app xyz`, open the `test/xyz/core_test.clj` in Emacs, `cider-jack-in`. Then delete the assertion in the generated test. Compile and then `cider-test-run-ns-tests`.

### CIDER version information

Include here the version string displayed when
CIDER's REPL is launched. Here's an example:

```
;; CIDER 0.11.0 (Bulgaria), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_51
```

### Emacs version

24.5

### Operating system

Mac OS 10.11.3

**Comment by Malabarba** [comment]
Thanks for reporting. I believe this is fixed on master (at least, I know I _tried_ to fix it).

**Comment by ericnormand** [comment]
Ok, thanks!

**Comment by bbatsov** [comment]
Closing this.
