### ISSUE TITLE
Unable to cider-eval-last-sexp with boot project after 11.0 upgrade

### ISSUE THREAD

**Issue by jackrusher** [clojure-emacs/cider#1624]
## Expected behavior

I expect to be able to evaluate forms after I `cider-connect`.

## Actual behavior

After upgrading to `cider-0.11.0` and updating my profile.boot like so:

```
(swap! boot.repl/*default-dependencies*
       concat '[[org.clojure/tools.nrepl "0.2.12"]
                [cider/cider-nrepl "0.11.0"]])
```

... when I start a (formerly working) boot project that gives me this message:

```
nREPL server started on port 64938 on host 127.0.0.1 - nrepl://127.0.0.1:64938
```

... and then `cider-connect` to it, which gives me one of the rotating cast of success messages and changes the modeline to indicate that `cider` is active with the right port number, I get this error in the mini-buffer whenever I try to `cider-eval-last-sexp`:

```
user-error: 'cider-eval-last-sexp' needs a ClojureScript REPL.
If you don't know what that means, you probably need to jack-in (`C-c M-J').
```

When I switch to the `*cider-repl localhost*` buffer, I am able to evaluate forms there. Also, there are no warnings or errors in the repl buffer.

## Steps to reproduce the problem

So far for me, it's `cider-connect` to a boot project and try to eval forms.

## Environment & Version information

```
#http://boot-clj.com
#Mon Mar 21 09:30:40 CET 2016
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.5.5
```

### CIDER version information

```
;; CIDER 0.11.0 (Bulgaria), nREPL 0.2.12
;; Clojure 1.7.0, Java 1.8.0_45
```

### Emacs version and OS

```
GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, Carbon Version 157 AppKit 1347.57) 
```

**Comment by Malabarba** [comment]
What file are you visiting when you call this command? And what is the active major mode there?

**Comment by jackrusher** [comment]
The major mode is `Clojurescript`, minor `cider`, like so:

https://www.dropbox.com/s/3hrivwjnbi06se1/Screenshot%202016-03-21%2010.43.19.png

**Comment by bbatsov** [comment]
Have you started the cljs repl before doing this evaluation? We changed the logic in 0.11 and now you cannot evaluated code in cljs files without having a cljs connection.

**Comment by jackrusher** [comment]
@bbatsov That was it. Isn't this the sort of thing that ought to go into the release notes? :smile:

**Comment by Malabarba** [comment]
It's hard to remember to document everything. :-)

That said, @bbatsov, maybe we should revert the restriction? i.e., try to use the right buffer but allow the user to use the wrong one.

**Comment by jackrusher** [comment]
In either case, thanks for the quick assistance with the problem.

**Comment by bbatsov** [comment]
> It's hard to remember to document everything. :-)

Guess you can add this retroactively. :-)

> That said, @bbatsov, maybe we should revert the restriction? i.e., try to use the right buffer but allow the user to use the wrong one.

I'd rather make the error message more informative.

**Comment by jackrusher** [comment]
Although I thought all was well, I'm now having the same problem intermittently *after* doing a `(start-repl)`, though not yet with a clear enough pattern to make a decent reproducible case.
