### ISSUE TITLE
cider-test-run-test should name the test it's running

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1625]
When you hit <kbd>C-c C-t C-t</kbd> to run a single test you now get 

```
Running tests in my-test-ns...
```

in the modeline.

This is the same text you get when you do <kbd> C-c C-t C-n</kbd> which run all the tests in that ns.

Having the same text for both commands has lead me to believe I hit the wrong key combination more than once.

**Comment by Malabarba** [comment]
Makes sense. :+1:

**Comment by bbatsov** [comment]
Just an oversight. I never run individual tests, that's why I didn't notice it.

**Comment by bbatsov** [comment]
I've added a dirty fix. In general the code can use some refactoring as the addition of new functionality (e.g. running loaded/project tests) didn't fit very well the original design of the code.

**Comment by jeffvalk** [comment]
@bbatsov What strikes you as in need of refactoring? The loaded/project tests feature didn't really change the overall code structure.

**Comment by bbatsov** [comment]
It seems to me that the case of running just a single test doesn't fit very well the general structure of the code. I also dislike a bit passing some keyword instead of the namespace when running `:loaded`/`:project` tests. Nothing major for sure, but I just feel we can do a bit better.

**Comment by jeffvalk** [comment]
Fair enough. In actuality, there isn't a single test function; it has always taken a list of tests. That is a bit at odds with the UI, where "one" or "all" are the most natural actions. That could be better aligned, I agree.

The keyword passing seems quite reasonable to me though. Maybe a symbol would be more elisp-y, but I think it makes for understandable code.
