### ISSUE TITLE
C-x C-e not evaluating for me

### ISSUE THREAD

**Issue by hnry** [clojure-emacs/cider#1626]
Most likely not a bug, but can't seem to find the answer elsewhere...

I'm new to emacs _and_ clojure so :fearful: 

When I C-x C-e it just shows a popup next to my cursor and in the minibuffer but it doesn't evaluate the expression:
![cider](https://cloud.githubusercontent.com/assets/25837/13931653/ab22d4a2-ef7a-11e5-8312-a372768d7dc7.png)

The relevant .emacs stuff
```
(add-hook 'clojure-mode-hook 'enable-paredit-mode)
(add-hook 'clojure-mode-hook 'subword-mode)
(require 'clojure-mode-extra-font-locking)
(add-hook 'cider-mode-hook 'cider-turn-on-eldoc-mode)
(add-hook 'cider-repl-mode-hook 'paredit-mode)
```

Emacs 24.5 - OS X 10.11.3

**Comment by bbatsov** [comment]
Evaluating a function definition is not the same as running it. :-) Try `C-x C-e` after the expression (-main). Or simply use `M-x cider-run`.
