### ISSUE TITLE
Assertions are referred to as tests in cider-test

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1627]
I've noticed that in our messages we never use the term `assertion`, which is what lein uses extensively. I mean tests are composed of assertions:

```
(deftest error-handling-test
  (testing "Handles a fake error done via mocked function"
    (with-redefs [cider.nrepl.middleware.apropos/find-symbols
                  (fn [& args] (throw (Exception. "boom")))]
      (let [response (session/message {:op "apropos" :query "doesn't matter"})]
        (is (= (:status response) #{"apropos-error" "done"}))
        (is (= (:ex response) "class java.lang.Exception"))
        (is (.startsWith (:err response) "java.lang.Exception: boom")))))

  (testing "Handles a real error caused by an improper regular expression"
    (let [response (session/message {:op "apropos" :query "*illegal"})]
      (is (= (:status response) #{"apropos-regexp-error" "done"}))
      (is (.startsWith (:error-msg response) "Dangling")))))
```

This is one test with 5 assertions (`is`) in it. However, our message right now is:

```
cider.nrepl.middleware.apropos-test: Ran 5 tests. 0 failures, 0 errors.
```

It should be

```
cider.nrepl.middleware.apropos-test: Ran 1 test, 5 assertions. 0 failures, 0 errors.
```

@jeffvalk Was there a particular reason you avoided the term `assertion`?

**Comment by bbatsov** [comment]
And, of course, when running just a single test with `C-c C-t t` we should probably use a more specific message. E.g.:

```
cider.nrepl.middleware.apropos-test/error-handling-test: Ran 5 assertions. 0 failures, 0 errors.
```

**Comment by jeffvalk** [comment]
No good reason. :-) I agree with you that "assertion" would be better here. Names are always a pain.

**Comment by bbatsov** [comment]
True that. I'll have to check if the middleware keeps track of both the number of tests and the number of assertions that were executed.

**Comment by jeffvalk** [comment]
It does. What you're calling a `test` is currently `var`, and `assertion` is now `test`. In context, you can see how they got named this way.

**Comment by bbatsov** [comment]
Got it. That definitely makes sense and I don't might referring those as we do internally, but in the UI we should probably follow in lein's footsteps in terms of terminology.

**Comment by Malabarba** [comment]
Indeed. I believe boot also follows the same terminology.
