### ISSUE TITLE
Was going to report bug, but this template is overwhelming.

### ISSUE THREAD

**Issue by sdegutis** [clojure-emacs/cider#1628]
I think I've found a legitimate bug, but all the work involved in just filing the bug (including checking if it already exists) will take me about 15 minutes. I'm already days behind schedule at work, where I'm using Cider. So I thought my time would be better spent reporting the fact that this bug-reporting process is overwhelming to the user (e.g. me) and you'll probably get a lot fewer bug reports because of it than otherwise.

*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable CIDER and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

**Remove all of the placeholder text in your final report!**

## Steps to reproduce the problem

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
; CIDER 0.11.0snapshot (package: 20151112.1551) (Clojure 1.7.0, nREPL 0.2.12)
```

### Emacs version

*E.g. 24.5*

### Operating system

*E.g. Windows 10*

**Comment by sdegutis** [comment]
I'm unsubscribing from this issue. (I'm very busy as it is and don't want to discuss it at all.)

**Comment by bbatsov** [comment]
> I think I've found a legitimate bug, but all the work involved in just filing the bug (including checking if it already exists) will take me about 15 minutes. I'm already days behind schedule at work, where I'm using Cider. So I thought my time would be better spent reporting the fact that this bug-reporting process is overwhelming to the user (e.g. me) and you'll probably get a lot fewer bug reports because of it than otherwise.

So, you're basically saying that your time is more important than my time and the time of the other CIDER maintainers... A good bug report saves us a lot of guesswork and increases the chance we'll actually fix a problem. If you don't want to check whether something was already fixed - that's fine. Filling all the other info takes just a couple of minutes for most bugs, which doesn't feel overwhelming to me.

**Comment by bbatsov** [comment]
> I'm unsubscribing from this issue. (I'm very busy as it is and don't want to discuss it at all.)

As you wish. I just wonder why you started this discussion to begin with.

**Comment by sdegutis** [comment]
I wasn't planning on looking at this again, but I've thought about this more since yesterday, which was a very busy and overwhelming day for me.

> So, you're basically saying that your time is more important than my time and the time of the other CIDER maintainers...

Not at all. But I'm getting paid to work, not to fill out bugs in open source projects. And when I get home, I'm not going to spend my very little free time filling out bugs in open source projects, when I ought to be spending my time with my children and wife instead. Cider isn't my responsibility, my work and my family are.

I've filled out bugs in plenty of open source projects on Github. And all of them got the information they needed, whether right away or through a focused inquiry by a project maintainer. But none of them involved nearly as much work as your template requires. So I'm confident that this bug report about your bug report process isn't unreasonable.

> As you wish. I just wonder why you started this discussion to begin with.

Because, regardless if whether you consider it to be a legitimate reason or not, there are going to be people like me who find the 15 minutes of work that you're requiring to fill out a bug in your project to be too high of a barrier, and will get to this page and then close it without filling out a bug. For the project's own sake, I thought it would be appropriate at the very least to report *that* as a bug in and of itself, since it will probably lead to fewer bug reports until it is resolved.

If you're okay with that, then re-mark this issue as closed. Otherwise I'm reopening it and suggesting you consider it to be a valid issue needing some kind of active resolution. Again, I'm not asking you to consider this issue for my own sake -- I don't care whether Cider disappears into oblivion or becomes the greatest Clojure IDE of all time. I'm just dutifully reporting the bug I consider to be most urgent. Do whatever you want with this report.

**Comment by Malabarba** [comment]
> Not at all. But I'm getting paid to work, not to fill out bugs in open source projects.

The same goes for the CIDER maintainers, we're not paid to do this. :-)
At the end of the day it's a collective effort, and yes, everyone who wants to help needs to pitch in more than 2 min. 

If taking 5-15min for a bug report is too long for you, consider how much time you have **gained** in the past by using CIDER.
If, OTOH, taking 5-15min is too long for your employer, then I understand your predicament but we're not going to remove the template.

Besides, you're allowed to ignore the template if you know what you're doing (in fact, I did that today).

>I've filled out bugs in plenty of open source projects on Github. And all of them got the information they needed

CIDER is a complex project that takes a lot of work to maintain. So yes, it does ask a little more effort from its bug reports. Before we had the template I was constantly asking people the same questions on bug reports and it consumed a lot of time. 
That no longer happens now that we have the template.

I manage plenty of other OSS projects for which a template would not be helpful, but specifically for CIDER I've found it to be very helpful.

**Comment by sdegutis** [comment]
Okay.

**Comment by bbatsov** [comment]
@sdegutis Btw, I don't understand one thing - apart from potentially installing the latest version to check if the problem wasn't solved there, what exactly requires a lot of work in the steps we've outlined? These are all basic things, that we'd typically ask people anyways, even if they didn't include the info in their bug report. Any time that will be saved reporting a bug without the template would be wasted afterwards anyways...

**Comment by bbatsov** [comment]
P.S. We're still tweaking the template from time to time. Its current form won't be its final form for sure.

**Comment by sdegutis** [comment]
> what exactly requires a lot of work in the steps we've outlined?

Ultimately it wasn't a lot of work. But it was a giant wall of text on a day when I was already extremely overwhelmed. Maybe there was no real issue and it was just that I shouldn't have tried to file a bug report on a day when it seemed a thousand things were going wrong and behind on schedule.
