### ISSUE TITLE
Scrolling freezes sometimes when scrolling Clojure sources

### ISSUE THREAD

**Issue by avli** [clojure-emacs/cider#1629]
## Expected behavior

There shouldn't be lags while scrolling with C-n and C-p in files of any size.

## Actual behavior

When scrolling sources with C-n or C-p scroll freezes from time to time, which is very annoying.

## Steps to reproduce the problem

Open a project, jack in to nREPL, go to a definition of some Clojure build in function to open large source file, e.g. core.clj, and try to scroll with C-n or C-p.

I've also noticed that _disabling_ projectile mode resolves the issue. Probably, CIDER tries to communicate with projectile somehow and this causes these freezes.

### CIDER version information

```
CIDER 0.12.0snapshot (package: 20160321.1158), nREPL 0.2.12
```

### Emacs version

24.5.1

### Operating system

Mac OS X 10.11.3

**Comment by avli** [comment]
Hmm... I've checked the CIDER code and it seems like it doesn't use any projectile related stuff. Now I'm not sure if it is a CIDER issue at all. But the interesting thing is when CIDER is not active I experience no freezes even when the projectile is active. Once both CIDER and projectile are active freezes are back.

**Comment by bbatsov** [comment]
> I've also noticed that disabling projectile mode resolves the issue. Probably, CIDER tries to communicate with projectile somehow and this causes these freezes.

Really? That's extremely surprising, as CIDER doesn't really use projectile for anything and nothing in Projectile can cause something like this... Can you post here your CIDER & projectile configs?

**Comment by avli** [comment]
Here are my Clojure/CIDER configs:

```
(add-hook 'clojure-mode-hook 'eldoc-mode)
(add-hook 'clojurescript-mode-hook 'eldoc-mode)

(add-hook 'clojure-mode-hook 'company-mode)
(add-hook 'clojurescript-mode-hook 'company-mode)

(add-hook 'cider-repl-mode-hook 'company-mode)

(add-hook 'cider-repl-mode-hook 'enable-paredit-mode)
```

And here is projectile:

```
(projectile-global-mode)
```

As I mentioned before, I'm not sure it is a CIDER issue. What surprises me is when the CIDER is not active, there are no freezes.

**Comment by Malabarba** [comment]
It's possible that you're experiencing small and unrelated lags from cider and from projectile, and only when you put the two together the lag becomes noticeable.

This sounds like it's related to the mode-line refreshing. Try doing something like:

    (setq cider-mode-line " cider")

This will prevent CIDER from doing expensive processing on the mode-line refresh. Does it help?

**Comment by avli** [comment]
@Malabarba Thank you for the advice! I tried to apply the option you've suggested, but unfortunately, I can't say something has changed or maybe it has changed insignificantly (it's hard to say, it's very subjective).

I've also tried to disable all Emacs plugins, but CIDER and projectile and can confirm the issue still exists.

**Comment by bbatsov** [comment]
> (add-hook 'clojure-mode-hook 'eldoc-mode)
> (add-hook 'clojurescript-mode-hook 'eldoc-mode)
> 
> (add-hook 'clojure-mode-hook 'company-mode)
> (add-hook 'clojurescript-mode-hook 'company-mode)
> 
> (add-hook 'cider-repl-mode-hook 'company-mode)
> 
> (add-hook 'cider-repl-mode-hook 'enable-paredit-mode)

I few pointers from me - adding the same things to clojure-mode-hook and clojurescript-mode-hook is not needed, as the latter is derived from the former. Also - `enable-paredit-mode` is the same as `paredit-mode`.

**Comment by avli** [comment]
@bbatsov Thank you for the advice :)

**Comment by bbatsov** [comment]
@avli did you figure out what caused this problem for you?

**Comment by avli** [comment]
@bbatsov Not really. The problem still exists, but I just used to it :)

**Comment by bbatsov** [comment]
Hmm. Can you please run the Emacs profiler (https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html) so we can see what exactly is causing the slowness for you?

**Comment by avli** [comment]
@bbatsov Here are the profiling results:

```
- redisplay_internal (C function)                               40504  88%
 - eval                                                         40380  88%
  - if                                                          40369  88%
   - format                                                     40366  88%
    - projectile-project-name                                   40366  88%
     - projectile-project-root                                  40366  88%
      - cl-some                                                 40366  88%
       - #<compiled 0x4302ba63>                                 40365  88%
        - projectile-root-top-down                              24707  54%
         - projectile-locate-dominating-file                    24707  54%
          - #<compiled 0x40fa603d>                              24692  54%
           - cl-find-if                                         24692  54%
            - apply                                             24692  54%
             - cl-find                                          24692  54%
              - apply                                           24692  54%
               - cl-position                                    24692  54%
                - cl--position                                  24681  54%
                 + #<compiled 0x40fa664d>                       24681  54%
          + abbreviate-file-name                                    6   0%
        + projectile-root-bottom-up                              7331  16%
        + file-truename                                          4853  10%
        + projectile-root-top-down-recurring                     3470   7%
     file-remote-p                                                  2   0%
  + format                                                         11   0%
 + linum-after-scroll                                             123   0%
   file-remote-p                                                    1   0%
+ ...                                                            2830   6%
+ linum-update-current                                           1707   3%
+ command-execute                                                 470   1%
+ timer-event-handler                                               2   0%
```

The results were collected on Mac OS X 10.11.6, Emacs version 25.1, projectile 20160921.902, cider 20160925.2057. What I did:

1. Created an empty project with Leiningen.
2. Opened a Clojure file, did cider-jack-in, wrote a dummy function, then went to `defn` definition.
3. Went to the beginning of the core.clj file and scrolled down to line 1000 with `C-n`.

Please, let me know if you need additional information.

**Comment by bbatsov** [comment]
The slowness comes from Projectile, not CIDER. Setting `projectile-mode-line` to nil should fix the slowness for you.

**Comment by avli** [comment]
@bbatsov You're right. I've tried to profile scrolling in other large files and see the same picture. Scrolling becomes jumpy when `projectile-mode-line` is not `nil`. Do you think it's a Projectile bug or just the way it works?

**Comment by bbatsov** [comment]
It's not exactly a bug - it's just that the project-name is recalculated on each movement operation and on a slower machine or a remote file this is going to cause a noticeable delay. I've been thinking for a while how to address this in projectile, but at least there's the workaround I mentioned.

Sorry for taking so long to respond to something so simple.

**Comment by avli** [comment]
No worries. Appreciate your help!
