### ISSUE TITLE
Cider has gotten substantially slower recently

### ISSUE THREAD

**Issue by sdegutis** [clojure-emacs/cider#1631]
## Expected behavior

Everything about using Cider used to be really fast.

## Actual behavior

Showing me the arglist in the status bar, or autocompleting a variable name, sometimes these take a really long time lately.

## Steps to reproduce the problem

I'm not sure. It only seemed to get really slow this past week. I just upgraded to 0.11.0 from 0.10.1 so that may be involved.

### CIDER version information

```
CIDER 0.11.0 (Bulgaria), nREPL 0.2.12
```

### Emacs version

24.5.1

### Operating system

OS X latest.

**Comment by bbatsov** [comment]
Might be an interaction with some other mode, as someone mentioned they had performance issues with CIDER and projectile, although I use them both (and develop them both) and I've never noticed such issues. You might try to load only cider (using `emacs -q`) so we can be sure this is a problem in CIDER.

**Comment by sdegutis** [comment]
Thanks. It's difficult to reproduce, so I'll close it for now, and hopefully never need to reopen it. (Fwiw I don't use projectile mode, my Emacs setup is insultingly simple and all I use are cider-mode and clojure-mode.)

**Comment by tanders** [comment]
I found that company greatly slows down CIDER (using CIDER version 20160623.12  and company  20160626).
