### ISSUE TITLE
Redefining a function shows the outdated arglist in the status bar

### ISSUE THREAD

**Issue by sdegutis** [clojure-emacs/cider#1632]
## Expected behavior

When I redefine a function with a new arglist, the new arglist doesn't show up in the Emacs status bar while inside that function form.

## Actual behavior

It's always the first one that was defined.

## Steps to reproduce the problem

Type:

```clojure
(defn foo [a b c])
```

Then <kbd>C-c C-e</kbd> to eval it.

Now type `(foo ` (note the space) and wait for the arglist to show up in the status bar. It shows up fine.

But now go and change the parameters in `foo` any way you'd like, e.g.:

```clojure
(defn foo [x y])
```

And again do <kbd>C-c C-e</kbd> to redefine the var.

Now type `(foo ` somewhere again or go back into your first one and press space.

Notice the arglist in the status bar is the old version only.

### CIDER version information

CIDER 0.11.0 (Bulgaria), nREPL 0.2.12

### Emacs version

24.5.1

### Operating system

OS X latest

**Comment by Malabarba** [comment]
Yep, I can reproduce it here.

**Comment by sdegutis** [comment]
Fwiw this was also a bug in 0.10.1 which is what prompted me to upgrade to 0.11.0 hoping it was alreday fixed. So it's present in both versions and was introduced earlier.

**Comment by Malabarba** [comment]
Looks like the cause is here:

    (defun cider-eldoc-arglist (thing)
      "Return the arglist for THING."
      (when (and (cider-nrepl-op-supported-p "eldoc")
                 thing
                 (not (string= thing ""))
                 (not (string-prefix-p ":" thing)))
        ;; check if we can used the cached eldoc info
        (if (string= thing (car cider-eldoc-last-symbol))
            (cdr cider-eldoc-last-symbol)
          (when-let ((eldoc-info (cider-sync-request:eldoc (substring-no-properties thing))))
            (let ((arglist (nrepl-dict-get eldoc-info "eldoc")))
              (setq cider-eldoc-last-symbol (cons thing arglist))
              arglist)))))

Clearly, this caching was meant to speedup eldoc in the case where you're jut typing inside the same function. What we need is to invalidate `cider-eldoc-last-symbol` whenever something is evaluated.

**Comment by sdegutis** [comment]
Wow that was fast. I'll patch this in my local version for now. Thanks @Malabarba :+1:.

**Comment by Malabarba** [comment]
:+1: ;)
