### ISSUE TITLE
*cider-scratch* buffer can switch namespace unexpectedly

### ISSUE THREAD

**Issue by sanjayl** [clojure-emacs/cider#1633]
## Expected behavior
The active namespace in the `*cider-scratch*` buffer will not be changed until a namespace altering function is evaluated (eg, `in-ns`).
## Actual behavior
The active *ns* of the scratch buffer is dependent on `cider-find-ns` by way of the `cider-current-ns` fn. `cider-find-ns` does not query the middleware to find the actual running namespace, instead, I think it parses the text around point to find the nearest ns form and it uses that as the `:ns` in subsequent `eval` calls. 

See [the screencast of the bug](https://www.youtube.com/watch?v=ej89SeeFxQ4). Note that the `(in-ns 'clojure.set)` form was **not** evaluated in the scratch buffer, but `clojure.set/union` was still available to me.

As an aside, discovered while writing a hook to change to header line of the scratch buffer to the current namespace, also relying on `cider-current-ns`. As you can see in the video by following the header line, the active ns is changing while I type.

As a bonus aside, here's the code that I put in my setup in case anyone else might want to use it:
```elisp
(defun update-cider-scratch-header ()
  (interactive)
  (when (eq major-mode 'cider-clojure-interaction-mode)
    (let* ((ww (window-width))
           (ns (cider-current-ns))
           (ns-len (length ns))
           (mid-point (/ (- ww ns-len) 2))
           (padding (make-string mid-point ? )))
      (setq header-line-format (concat padding ns)))))

(add-hook 'buffer-list-update-hook #'update-cider-scratch-header)
```
## Steps to reproduce the problem
Open a cider scratch buffer and do the following:
```clojure
(in-ns 'user) ; eval me
(union #{3})  ; eval me, get a stacktrace

(in-ns 'clojure.set) ; DO NOT eval this form
(union #{3})  ; eval me, unexpected success!!
```
## Environment & Version information
n/a
### CIDER version information
CIDER 0.12.0snapshot (package: 20160321.1158), nREPL 0.2.12
;; Clojure 1.7.0, Java 1.8.0_74
### Emacs version
24.5.1
### Operating system
Ubuntu Wily

**Comment by bbatsov** [comment]
So, regarding the ns - we should probably leverage `cider-set-buffer-ns` in cider-scratch (as we do for the REPL buffers). Basically we store the ns as a buffer-local variable, so commands like `cider-find-ns` will work even with ns forms. 

You're also raising a good point about the visibility of the namespace for the scratch buffer - although I'd just use the standard modeline update functionality of Emacs.

**Comment by Malabarba** [comment]
> Open a cider scratch buffer and do the following:
> 
>     (in-ns 'user) ; eval me
>     (union #{3})  ; eval me, get a stacktrace
>     
>     (in-ns 'clojure.set) ; DO NOT eval this form
>     (union #{3})  ; eval me, unexpected success!!

This is a feature. It allows evaluation to “just work” in Clojure files.

The question is, do we want to specifically disable it in the scratch buffer?

**Comment by bbatsov** [comment]
Well, for me the big issue is that it's not really clear what's the effective `ns` being in use. Frankly I didn't think a lot when I implemented this feature. There are other things to consider as well - e.g. the buffer derives directly `clojure-mode`, which creates a problem for people wanting to play with say cljs.

**Comment by Malabarba** [comment]
Honestly, I would be inclined to say the scratch buffer is just a development burden, as the user can get the same effect by creating a `blabla.clj` file. **But**, I can't deny a lot of people seem to be using it.

**Comment by sanjayl** [comment]
The same behavior exists in a regular, non-scratch, `blabla.clj` cider buffer as well. I don't think this feature has ever tripped me up, but it definitely surprised me when I saw what was actually happening.

**Comment by bbatsov** [comment]
> The same behavior exists in a regular, non-scratch, blabla.clj cider buffer as well. I don't think this feature has ever tripped me up, but it definitely surprised me when I saw what was actually happening.

In source files usually there's just one `ns` form and no one is using `in-ns`. But yeah - the behaviour is exactly the same as `cider-interaction-mode` is simply `clojure-mode`.

**Comment by bbatsov** [comment]
Back to the problem in question - a while back I was thinking of maybe adding a toggle to switch off this magical behaviour. Frankly, I don't like it at all, but newcomers seem to enjoy it as they don't have to manually evaluate `ns` forms when they add/change them.

One idea I had in the past was to show a warning if the effective ns is out of sync with what they had previously evaluated. Another was to simply do nothing and assume the users will know what they're doing.

**Comment by Malabarba** [comment]
Frankly, I don't even mind if it's on or off by default. I think having more than one ns form is pretty rare, so either behaviours are fine by me.

**Comment by bbatsov** [comment]
I meant that the functionality is exactly the same even if you have a single ns - if it's not evaluated it will be automatically, which probably is not what some people are expecting. On the other hand - I know a lot of people were wondering why they'd get ns error when they didn't evaluate their ns forms. Go figure what's the best solution... :-)

**Comment by bbatsov** [comment]
I think we can close this.
