### ISSUE TITLE
Alt doc for higher-order functions

### ISSUE THREAD

**Issue by achesnais** [clojure-emacs/cider#1638]
## Expected behavior

When using a higher-order function, CIDER could display the function signature of whichever function is being manipulated in the mini-buffer, rather than that of the higher-order function itself (or both if there's a clever way to do that).
For example, when writing `(partial some-function ...)`, the minibuffer would display the signature of `some-function`, not that of `partial`.
Similar behaviour could be expected of `map`, `filter`, etc.

I find I'm often going back to the signature of functions I'm manipulating with higher-order ones, as the order of arguments is always crucial when using `partial`, `map`, etc.
## Actual behavior

Currently CIDER displays the doc of whichever function comes first in the s-exp.

**Comment by Malabarba** [comment]
I can see the benefit in that, but I can also see it might be surprising. So I'm on the fence about it. :-)

**Comment by bbatsov** [comment]
Btw, something like this is on my personal radar. I'll probably implement it when I get do adding eldoc for variables (as the implementation is related - you have to consider the symbol at point in addition to the symbol at the beginning of the list).

**Comment by bbatsov** [comment]
This is the related ticket, btw https://github.com/clojure-emacs/cider/issues/1572
