### ISSUE TITLE
Cider in Org-Mode: "nrepl-send-sync-request: Sync nREPL request timed out" with long running calls

### ISSUE THREAD

**Issue by fgiasson** [clojure-emacs/cider#1639]
I am using `Cider` in `Org-mode` to execute code blocks. The middleware that calls Cider is [ob-clojure](http://orgmode.org/w/org-mode.git?p=org-mode.git;a=blob;f=lisp/ob-clojure.el;h=5b023e679f6581453a8e7c2102805a9c7022de76;hb=1045e9e9c0e6438f5ee9dc4f0e5c720a8b670cdd).

Everything works perfectly until I try to run long-running code (procedures that can takes a few minutes to complete. When I am doing this, I am getting the following error:

> nrepl-send-sync-request: Sync nREPL request timed out (op eval session 57bdacff-b178-4952-8bf8-5e01ac9d745a code (def umbel (create-ontology-structure))

A few questions regarding this:

1. Is this a bug?
2. Is it possible to re-define the timeout to increase it?
3. Is it possible to modify `ob-clojure` to make that work?

This problem occurs when I use `Org-mode` as a Notebook and that I have to run background procedures that can take some time to procedure its results.

Note 1: that I could probably put everything in a `future`, but I would like to get the results in a `#+Results` block within the Org file to know when the code finished to run.

Note 2: I am running Cider `0.11.0`

**Comment by fgiasson** [comment]
I am wondering if I could set `nrepl-sync-request-timeout` to `nil`. I would guess so, but then I could I re-define that value, possible in my .emacs when I configure `Org-mode`?

**Comment by Malabarba** [comment]
Yes, that is the right variable. I think ob-clojure shold `let-bind` this to `nil` around its code executions.

**Comment by bbatsov** [comment]
Exactly.

**Comment by fgiasson** [comment]
@Malabarba, @bbatsov ok great, let me try this in `ob-clojure.el` to see if that fix all my issues, if it does then I will propose to expose a new parameter for `ob-clojure` to be able to play with that as necessary.

**Comment by fgiasson** [comment]
Great, it worked. Here is the modified version of the `org-babel-execute:clojure` function for documentation purpose:

``` lisp 
(defun org-babel-execute:clojure (body params)
  "Execute a block of Clojure code with Babel."
  (let ((expanded (org-babel-expand-body:clojure body params))
	result)
    (case org-babel-clojure-backend
      (cider
       (require 'cider)
       (let ((result-params (cdr (assoc :result-params params))))
	 (setq result
	       (nrepl-dict-get
		(let ((nrepl-sync-request-timeout nil))
		  (nrepl-sync-request:eval
		   expanded (cider-current-connection) (cider-current-session)))
		(if (or (member "output" result-params)
			(member "pp" result-params))
		    "out"
		  "value")))))
      (slime
       (require 'slime)
       (with-temp-buffer
	 (insert expanded)
	 (setq result
	       (slime-eval
		`(swank:eval-and-grab-output
		  ,(buffer-substring-no-properties (point-min) (point-max)))
		(cdr (assoc :package params)))))))
    (org-babel-result-cond (cdr (assoc :result-params params))
      result
      (condition-case nil (org-babel-script-escape result)
	(error result)))))
```
