### ISSUE TITLE
Debugger fails on inline protocol implementations

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1641]
```clj
(defrecord MyComponent []
  component/Lifecycle
  (start [this]
   ...)
  (stop [this]
    ....))
```

Instrumenting either `start` or `stop` here causes the debugger to blow up with a `ClassNotFoundException`.

Even if this functionality is out of scope we could let the user know in a helpful manner instead of just blowing up.

**Comment by Malabarba** [comment]
Yes, I've been bumping into this too. I'm sure it worked in the past, so I'll mark it as a real bug.
One workaround is to put a `#dbg` inside the method definitions and just evaluate the `defrecord` normally.
