### ISSUE TITLE
Running tests clears all overlays in the buffer

### ISSUE THREAD

**Issue by wasamasa** [clojure-emacs/cider#1643]
## Expected behavior

I have a Clojure test buffer with overlays.  Launching tests will not touch these overlays and do the necessary bookkeeping for CIDER's overlays.

## Actual behavior

All overlays are removed.  [This](https://github.com/clojure-emacs/cider/blob/master/cider-test.el#L501-L502) looks like the culprit.

## Steps to reproduce the problem

- Open a Clojure test buffer
- Enable a minor mode that adds its own overlays to the current buffer (I'm using [column-enforce-mode](https://github.com/jordonbiondo/column-enforce-mode/) and a buffer with long lines)
- `C-c ,`

### CIDER version information

```
; CIDER 0.10.0snapshot (package: 20151125.2330) (Java 1.8.0_74, Clojure 1.7.0, nREPL 0.2.12)
```

### Emacs version

Emacs 24.5.1

### Operating system

Arch Linux

**Comment by Malabarba** [comment]
This was probably done to remove the “test failed” overlays. But I agree it's a bug. It should _only_ remove the test-related overlays.

**Comment by wasamasa** [comment]
Now that I think of it, I suspect that's the source of smartparen's post-command handler breaking on overlays...

This should be reasonably simple to fix.  Assuming every CIDER-related overlay is tagged, the following could work (untested):

```elisp
(let ((overlays (overlays-in (point-min) (point-max))))
  (dolist (overlay overlays)
    (when (eq (overlay-get overlay 'category) 'cider-test)
      (delete-overlay overlay))))
```
