### ISSUE TITLE
Enable a default selection for cider-apropos-act-on-symbol

### ISSUE THREAD

**Issue by martintrojer** [clojure-emacs/cider#1646]
`cider-apropos-act-on-symbol` presents a selection on what action to take.

It would speed-up / improve my flow if a default action could be configured (in my case `find-def`).

**Comment by mallt** [comment]
While adding a defcustom for this request, I noticed the cider-apropos functions are not available when testing a clean emacs installation with "make run-cider". Is it somehow possible to make these functions available in the "make run-cider" environment, or is it necessary to load them manually?
