### ISSUE TITLE
cider repl warning

### ISSUE THREAD

**Issue by JoePython1** [clojure-emacs/cider#1648]
## Expected behavior
No warnings
## Actual behavior
```
;; =================================================================
;;WARNING: CIDER's version (0.12.0-snapshot) does not match cider-nrepl's version (0.8.1). Things will break!
```
## Steps to reproduce the problem
In prelude, type C-c M-J

### CIDER version information
```
;; CIDER 0.12.0snapshot (package: 20160401.1308), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_77
```

### Emacs version
24.5.1 

### Operating system
Ubuntu  14.04 LTS

**Comment by Malabarba** [comment]
Try removing any reference to `cider-nrepl` from your `project.clj` and `profiles.clj`.

**Comment by JoePython1** [comment]
That works thank you.
