### ISSUE TITLE
Replace ert with buttercup

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1650]
ert gets the job done, but it does little to enforce good test structure and to help with code reuse. [buttercup](https://github.com/jorgenschaefer/emacs-buttercup) is an RSpec-like test framework which seems way more capable (and modern).

**Comment by cskksc** [comment]
I'd like to give this a try. I have not used `buttercup` before,  but have worked quite a lot with rspec, so I think I can work this out. I'll submit a PR soon, with some of the tests changed, and then lets see if my level to elisp knowledge is sufficient to tackle this.

**Comment by bbatsov** [comment]
Great!

**Comment by Malabarba** [comment]
🎉🎉🎊🎊

**Comment by phillord** [comment]
If I may be permitted a plug, I've been working an http://github.com/phillord/assess which provides a set of stateless predicates (and ert-explainer functions, although you are perhaps less interested in that).

**Comment by bbatsov** [comment]
@cskksc Do you plan to finish the migration? Now we're in a nasty place using two systems and should try to kill ert as soon as possible.

**Comment by cskksc** [comment]
@bbatsov Sorry for the delay. Only 1 file `cider-tests` is pending. I'll finish that in the next 2 days.

**Comment by bbatsov** [comment]
Great!

On 26 April 2016 at 20:17, Chaitanya Koparkar <notifications@github.com>
wrote:

> @bbatsov <https://github.com/bbatsov> Sorry for the delay. Only 1 file
> cider-tests is pending. I'll finish that in the next 2 days.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/1650#issuecomment-214959196>
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by vspinu** [comment]
I am late to the party but all I have noticed so far that buttercup is close to impossible to use interactively. 

With ert I could run each test interactively, run all all loaded tests and step-through with debugger on each test. With buttercup nothing of that seem to be available. There is one interactive function `buttercup-run-at-point` which does nonsence with cider tests (splits windows in N buffers, resets buffers states, doesn't report failed tests correctly).  

How do you use it correctly?  Run full suite after each test?

**Comment by dpsutton** [comment]
I've had some luck with the `buttercup-run-at-point` but it's not particularly great. But I haven't had a good experience otherwise. I looked at buttercup and there seems to be no way to specify running tests of just a single file, which seems like a pretty bad omission. I either run `make test` in a terminal or `M-x compile [ret] make test`. both take about 15 seconds to compile all of the files and 2 seconds to run the tests.

**Comment by dpsutton** [comment]
ah and for debugging, you can't debug the form in the test but you can debug any functions outside of that. I'll instrument them, eval the buttercup form and then run the `buttercup-run-at-point` and I'm able to step through.

**Comment by bbatsov** [comment]
Yeah, buttercup has some regrettable shortcomings, but I think it's much easier to fix them than to fix ert, which basically hasn't changed in ages. I mostly run the tests with make and that's ok overall, but yeah - some interactive functionality would be welcome.

**Comment by bbatsov** [comment]
I'd open those issues on the buttercup issue tracker, btw.

**Comment by xiongtx** [comment]
@jorgenschaefer is a great Elisper, so I'd definitely [raise some issues](https://github.com/jorgenschaefer/emacs-buttercup/issues/new) and see what he thinks.

However, it's not that interactive testing has not been considered. From the [`buttercup` docs](https://github.com/jorgenschaefer/emacs-buttercup/blob/68692d9e04ba0791c791395ee68500e4a5511ff9/docs/running-tests.md#usage) (emphasis mine):

> Buttercup is **primarily meant to be used non-interactively**, to automatically test a project independent of a user’s setup, before a commit and on a continuous integration platform. Because of this, **the recommended workflow for buttercup does not use interactive commands but instead the command line**.
