### ISSUE TITLE
Exception while launching the boot repl

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#1652]
## Expected behavior
The repl starts when you execute `boot cider repl wait` at the terminal.

## Actual behavior
An exception is thrown.

## Steps to reproduce the problem
At the terminal `boot cider repl wait`

### CIDER version information
0.12.0-SNAPSHOT (master)

### Lein/Boot version
*boot 2.5.5*

### Emacs version
*24.5*

### Operating system
*Ubuntu Linux 14.10*

The exception involves `fipp` and it is [here](https://gist.github.com/arichiardi/b09dc1466f55a4a395a0c74f4213015e).

My `cider` task is:
```
(deftask cider
  "Add CIDER support:
   https://github.com/boot-clj/boot/wiki/Cider-REPL"
  []
  (require 'boot.repl)
  (swap! boot.repl/*default-dependencies*
         conj '[cider/cider-nrepl "0.12.0-SNAPSHOT"])
  (swap! boot.repl/*default-middleware*
         conj 'cider.nrepl/cider-middleware)
  identity)
```

Removing the `cider`, removing the middleware, successfully launches the repl.

**Comment by Malabarba** [comment]
> At the prompt `boot cider repl wait`

What do you mean by this? Do you mean you ran this command in a terminal?

I think @benedekfazekas might recognize this exception.

**Comment by arichiardi** [comment]
Yes sorry, at the terminal, but it happens with `jack-in` as well.

**Comment by benedekfazekas** [comment]
well I don't but luckily you can search gitter history ;)

based on that it seems we had the same problem with with leiningen prior version 2.5.3. no immediate memory how older lein version caused this. just a stab in the dark: what is your clojure version btw?

also a possible workaround could be if you set `(setq cider-pprint-fn 'pprint)`, at least for `cider-jack-in`

also you only need the cider task if you want to use a separate REPL, `cider-jack-in` sorts out dependencies (wonder if you get the same exception if you use that.)

**Comment by arichiardi** [comment]
Clojure version is `1.6.0` which is the minimal supported version that boot supports...it might be that then. I am trying...

**Comment by arichiardi** [comment]
Bumping the version solves, so I can live with this, so basically `1.6.0` is not officially supported anymore for `boot` right? I would like to add it in their wiki.

```
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.7.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_77-b03
```

**Comment by benedekfazekas** [comment]
this may be a reader conditionals related issue then.

**Comment by arichiardi** [comment]
The wiki page is [this](https://github.com/boot-clj/boot/wiki/Cider-REPL) and as you were saying before I gather that also the "A better way" section is not required anymore (since `0.11.0`?)

**Comment by benedekfazekas** [comment]
well I guess you can't use stuff with 1.6 that uses reader conditionals. incl. refactor-nrepl as we use some stuff using cljc files. it seems same goes with cider-nrepl as well then?

`A better way` section only applies if you want to use cider (and refactor-nrepl) with REPL you *connect* to instead of using `cider-jack-in`. see [this](https://github.com/clojure-emacs/cider/blob/master/doc/installation.md#ciders-nrepl-middleware) for details

**Comment by arichiardi** [comment]
Ok then, I guess I have to specify it there so that people don't get bitten. Boot still supports back to `1.6.0`

**Comment by arichiardi** [comment]
Ok done: https://github.com/boot-clj/boot/wiki/Cider-REPL, closing this.

**Comment by benedekfazekas** [comment]
thx!
