### ISSUE TITLE
Injected middlewares should have test scope

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#1653]
I am working on a `boot` task that resolves and fetches jars from the project dependency tree.
I have noticed that all the injected middlewares have `:scope "compile"` which cause me to include them in my final artefact (a folder containing the deps source files).

It would probably be more correct to inject them with scope `"test"` or `"provided"` so that they won't be considered as compile time dependencies by my or other tools. Additionally the same would avoid including their transitive dependencies.

I can take care of this, it should be a simple addition in the `cider`-produced dependency vector.

**Comment by Malabarba** [comment]
I don't understand how you reached this problem? Normally you build your artefact with a boot command, in which case cider's dependencies wouldn't be injected. Are you somehow building it from the repl instead?

**Comment by arichiardi** [comment]
Yes I am, you are right though that normally I would just execute my boot task from outside the repl. Well, I would say it is not that big of a deal for now maybe...

**Comment by Malabarba** [comment]
Do you know of a way to add the test scope? This is what the command currently looks like:

    boot -d org.clojure/tools.nrepl\\:0.2.12 -d refactor-nrepl\\:2.3.0-SNAPSHOT -d cider/cider-nrepl\\:0.12.0-SNAPSHOT repl -m refactor-nrepl.middleware/wrap-refactor -m cider.nrepl/cider-middleware -s wait

**Comment by arichiardi** [comment]
Ah! Maybe there is no way as of now:
```-d --dependencies SYM:VER   Add dependency to project (eg. -d foo/bar:1.2.3).```

**Comment by Malabarba** [comment]
Ok. Given the limitations, I think we can close this now. I'm fine with reopening if support for that is ever implemented in boot (though I'm a little wary of adding something that fixes a corner-case but will break for every user who doesn't have the latest boot version). :-)

**Comment by arichiardi** [comment]
Agree 100%, also considering that the case is a very cornery one, thanks Artur and sorry for the noise.

**Comment by Malabarba** [comment]
No problem, reporting issues is always helpful. :-)
