### ISSUE TITLE
Eldoc error in ns :require form

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1654]
If I place point where the `|` symbol is in the following snippet,

    (ns some.server
      (:require [com.stuartsierra.component :as component]
    |           [another.ns :as ns]))

I get this error:

    Debugger entered--Lisp error: (wrong-type-argument stringp ("map"))
      string=(("map") "")
      (not (string= ns ""))
      (and ns (not (string= ns "")))
      (if (and ns (not (string= ns ""))) (format "%s/%s" (cider-propertize ns (quote ns)) (cider-propertize symbol (quote var))) (cider-propertize thing (quote var)))
      cider-eldoc-format-thing(("map") ("map" "not-found") ":require")
      (format "%s: %s" (cider-eldoc-format-thing ns symbol thing) (cider-eldoc-format-arglist arglists pos))
      (progn (format "%s: %s" (cider-eldoc-format-thing ns symbol thing) (cider-eldoc-format-arglist arglists pos)))
      (if eldoc-info (progn (format "%s: %s" (cider-eldoc-format-thing ns symbol thing) (cider-eldoc-format-arglist arglists pos))))
      (let* ((sexp-info (cider-eldoc-info-in-current-sexp)) (thing (car sexp-info)) (pos (car (cdr sexp-info))) (eldoc-info (cider-eldoc-info thing)) (ns (nth 0 eldoc-info)) (symbol (nth 1 eldoc-info)) (arglists (nth 2 eldoc-info))) (if eldoc-info (progn (format "%s: %s" (cider-eldoc-format-thing ns symbol thing) (cider-eldoc-format-arglist arglists pos)))))
      (progn (let* ((sexp-info (cider-eldoc-info-in-current-sexp)) (thing (car sexp-info)) (pos (car (cdr sexp-info))) (eldoc-info (cider-eldoc-info thing)) (ns (nth 0 eldoc-info)) (symbol (nth 1 eldoc-info)) (arglists (nth 2 eldoc-info))) (if eldoc-info (progn (format "%s: %s" (cider-eldoc-format-thing ns symbol thing) (cider-eldoc-format-arglist arglists pos))))))
      (if (and (cider-connected-p) (not (member last-command (quote (next-error previous-error))))) (progn (let* ((sexp-info (cider-eldoc-info-in-current-sexp)) (thing (car sexp-info)) (pos (car (cdr sexp-info))) (eldoc-info (cider-eldoc-info thing)) (ns (nth 0 eldoc-info)) (symbol (nth 1 eldoc-info)) (arglists (nth 2 eldoc-info))) (if eldoc-info (progn (format "%s: %s" (cider-eldoc-format-thing ns symbol thing) (cider-eldoc-format-arglist arglists pos)))))))
      cider-eldoc()
      eldoc-print-current-symbol-info()
      [SOME GARBAGE HERE]

**Comment by bbatsov** [comment]
I'll look into this. I've added some custom handing of keywords at a function position, but forgot to account for cases like `:require` and `:import`.

**Comment by expez** [comment]
I'm seeing this elsewhere:


```
Debugger entered--Lisp error: (wrong-type-argument stringp ("args*"))
  cider-eldoc-format-thing(("args*") nil "FileReader.")
  cider-eldoc()
```

With point on:

```clj
(FileR|eader. path)
```

**Comment by bbatsov** [comment]
Yeah, that's another custom handling I've added. Maybe the arguments were supposed to be symbols instead of strings. I'm confused, because I recall that I tested this.
