### ISSUE TITLE
cider-result popup buffer doesn't support the ansi escape sequences

### ISSUE THREAD

**Issue by BrunoBonacci** [clojure-emacs/cider#1656]
## Expected behavior
Ansi escape sequences are rendered properly like in the cider repl buffer

## Actual behavior
ansi escape sequences are printed-out without proper rendering

## Steps to reproduce the problem
* Add `[com.taoensso/timbre "4.3.1"]` to your project
* start a repl
* open a clojure buffer and type:
``` clojure
(require '[taoensso.timbre :as log])
(log/error (RuntimeException. "boom") "bang")
```
* evaluate these in the repl and you'll see a rendered output
* evaluate these lines with <kbd>C-c C-p</kbd> and you'll see the escape codes.

### CIDER version information
Tried on:
`CIDER 0.12.0snapshot (package: 20160405.2359), nREPL 0.2.12` and `CIDER 0.11.0`
on `Clojure 1.7.0, Java 1.8.0_45`

### Emacs version
Emacs 24.5.1

### Operating system

OS X 10.11 "El Capitan"

**Comment by bbatsov** [comment]
While fixing this is simple, it seems to me the whole functionality is kind of broken. Why are we dumping the stdout and the stderr in a `clojure-mode` buffer, together with the result? This makes no sense to me.

@Malabarba @cichli Any thoughts?

**Comment by BrunoBonacci** [comment]
I somehow agree with you, the output of the cider-result should in norm contain only the result of the function and not the side effect. However not all functions are pure and having *stdout* and *stderr* redirected as it is now, it makes it way easier to work with, rather than going to look for the repl server output.
It is really only from a practical standpoint.

**Comment by bbatsov** [comment]
Perhaps. On the other hand, this is marked as a clojure-mode buffer and all the output gets corrupted there because of this, so it looks really ugly to me (not to mention it's not exactly clear what's the result and what's the output in some situations). 

I'll fix your particular problem, but it definitely seems more important to me to reconsider this functionality at a more basic level.

**Comment by BrunoBonacci** [comment]
Thanks. I'm a big fan of this functionality. The inline evaluation is good only for very small results, but data structures do not render nicely inline. I now got used to it and it is my main evaluation method.
So if you want review it, I would be glad to give you early feedback on the idea or the first draft.

**Comment by bbatsov** [comment]
I'll fix this for now and we can discuss potential improvements in another ticket.
