### ISSUE TITLE
eldoc not working for certain core functions 

### ISSUE THREAD

**Issue by mgrubb** [clojure-emacs/cider#1664]
This could be related to #1358 but I'm not using CLJS in this project.

## Expected behavior
When point in in/on s-exp shows function params in mini-buffer for clojure.core functions.

## Actual behavior
Only some clojure.core functions (e.g. let, def, loop, if and others) show argument info in minibuffer, others show nothing.  Also If I use C-c C-d C-d I'm prompted for a symbol when I enter the symbol, (e.g. assoc! or reduce, etc) I get Symbol assoc! not resolved.  Also these functions that do not work, do not have the same face as other core functions that do work.

## Steps to reproduce the problem
Move point to where eldoc should show a hint in the mini-buffer for a core function and/or
use C-c C-d C-d

## Environment & Version information
Using evil-mode version 1.2.12
clojure-mode v 5.3.0

Init code for cider:
```elisp
  (use-package cider
    :ensure t
    :commands (cider-mode cider-jack-in)
    :diminish "CDR"
    :init
    (setq cider-prompt-for-symbol nil)
    (setq nrepl-log-messages nil)
    :config
    (add-hook 'cider-mode-hook #'eldoc-mode))
```

### CIDER version information
```
;; CIDER 0.12.0snapshot (package: 20160410.2022), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_60
```

### Lein/Boot version
Leiningen 2.6.1

### Emacs version

GNU Emacs 24.5.1 (x86_64-apple-darwin15.3.0, NS apple-appkit-1404.34) of 2016-03-21

### Operating system

Mac OS X 10.11.4

**Comment by bbatsov** [comment]
Have you loaded the buffers in question (e.g. with `C-c C-k`)? None of the functionality related to symbol resolution works, if some namespace isn't actually loaded.

**Comment by mgrubb** [comment]
Yep, that seemed to fix it, sorry for the bogus report.
