### ISSUE TITLE
cider-find-var doesn't work for all java classes

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1666]
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  compare-strings("*" nil nil nil 0 1 nil)
  string-prefix-p("*" nil)
  cider--jump-to-loc-from-info((dict "status" ("done") "class" "org.joda.time.Period" "id" "2535" "interfaces" ("org.joda.time.ReadablePeriod" "java.io.Serializable") "javadoc" "org/joda/time/Period.html" "modifiers" "#{:public :final}" "name" "Period" "package" "org.joda.time" "session" "450c9c46-a161-4bda-9ad8-e961666d6a52" "super" "org.joda.time.base.BasePeriod"))
  cider--find-var("org.joda.time.Period")
  cider-read-symbol-name("Symbol" cider--find-var)
  cider-find-var(nil)
  call-interactively(cider-find-var nil nil)
  command-execute(cider-find-var)
```

Not entirely sure what's special with `Period`. Jumping to e.g. `java.lang.Exception` works fine.  Perhaps it's that it's in a jar.

```
;; Connected to nREPL server - nrepl://localhost:51749
;; CIDER 0.12.0snapshot (package: 20160410.2022), nREPL 0.2.12
;; Clojure 1.7.0, Java 1.8.0_66
```

**Comment by bbatsov** [comment]
Likely the source jar is not on the classpath.

**Comment by expez** [comment]
> Likely the source jar is not on the classpath.

This happened with `org.joda.time.Period` IIRC. Does it not work because that jar is pulled in by `clj-time`?

**Comment by bbatsov** [comment]
Probably. It likely pulled just the compiled classes, but you also need the source jar for source lookup to work.

**Comment by bbatsov** [comment]
Btw, you shouldn't be getting an error, but some message saying the source can't be found. That's odd...

**Comment by bbatsov** [comment]
I tested this and got a `No source location` message (as expected). Maybe we can improve this message a bit...

**Comment by vspinu** [comment]
Is there a known workaround for this? I have manually built and installed maven project which contains both source and javadoc jars. CIDER cannot locate neither source nor javadoc.

**Comment by vspinu** [comment]
Just found a rudimentary workaround by manually adding jar files to lein's :resource-paths.

**Comment by bbatsov** [comment]
Guess we can close this then. Unless someone wants to contribute some documentation on the subject?

**Comment by dpsutton** [comment]
I'll have to get up to speed but I can do it tomorrow

**Comment by bbatsov** [comment]
@dpsutton Sounds good.

**Comment by dpsutton** [comment]
I've been trying to figure this out. I've built a project `mvn install` and then referenced it. I got no errors, just info that no documentation was found when trying to view docs. @vspinu can you help shed some light on circumstances that could trigger an error?

**Comment by bbatsov** [comment]
I think a larger point is that we haven't documented at all how one can add source jars to their lein/boot project.

**Comment by expez** [comment]
@vspinu I tried adding paths to jars in `:resource-paths` and I still can't jump to the java source nor view its documentation.  What did you do?

**Comment by vspinu** [comment]
Just that, added full paths to the `:resource-paths`

```clj
  :resource-paths ["/home/vspinu/.m2/repository/com/interactivebrokers/tws-api/9.71.1/tws-api-9.71.1-sources.jar"
                  "/home/vspinu/.m2/repository/com/interactivebrokers/tws-api/9.71.1/tws-api-9.71.1-javadoc.jar"]
```

Did the trick for me, both for refs and javadocs.

**Comment by vspinu** [comment]
Documenting this is just passing the ball to the user.  How hard would it be to check for `-sources.jar` or`-javadoc.jar` and add them to the classpath dynamically?

**Comment by expez** [comment]
Thanks, the mistake was mine, I added the wrong jar (with only `.class` files).

It would be easy to check for jars, but where would we check?

**Comment by vspinu** [comment]
> but where would we check? 

In the parent directory of the class jar.

**Comment by vspinu** [comment]
The trick with `:resource-path` no longer works. Has something changed in the java-ref lookup in the past 7 months or so?

I now see a lot "bad source file" errors like this when I first call `cider-find-var`:

```
  bad source file: /home/vspinu/.m2/repository/io/netty/netty-transport/4.1.22.Final/netty-transport-4.1.22.Final-sources.jar(io/netty/channel/ChannelFactory.java)
    file does not contain class io.netty.channel.ChannelFactory
    Please remove or make sure it appears in the correct subdirectory of the sourcepath.
```

If I check manually I do see an _interface_ `ChannelFactory` in that java file.

**Comment by vspinu** [comment]
Another simple workaround for this is to use tags instead

```bash
## fetch sources and javadocs
lein pom
mvn dependency:sources
mvn dependency:resolve -Dclassifier=javadoc

## build tags
mkdir java-sources && cd java-sources
jar -xvf ~/.m2/repository/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final-sources.jar
ctags -eR 
```

**Comment by bbatsov** [comment]
> The trick with :resource-path no longer works. Has something changed in the java-ref lookup in the past 7 months or so?

@jeffvalk is our resident expert here. I don't recall any changes in this area for quite a while until very recently. It still seems to me that the only thing needed for the lookup to work should be for the source artifacts to be on the classpath.

**Comment by jeffvalk** [comment]
Is this still an issue? If the source is on the classpath, `info` should work for java sources. The JDK sources are added to classpath by Orchard. Anything else, the user would needs to add in `project.clj`, etc.
