### ISSUE TITLE
cider-help-echo prompts for disambiguation

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1668]
I don't want prompts for disambiguation created when cider-help-echo can't figure out which var/class to display documentation for.  This should be best effort imo.  I didn't even notice the prompt until I was done moving my mouse around and tried to resume work and found myself typing into a prompt.

````
;; Connected to nREPL server - nrepl://localhost:51749
;; CIDER 0.12.0snapshot (package: 20160410.2022), nREPL 0.2.12
;; Clojure 1.7.0, Java 1.8.0_66
```

**Comment by Malabarba** [comment]
Oops. I'll make a patch for this.

Meanwhile, do you know which situations lead to ambiguity?
