### ISSUE TITLE
Symbol's value as variable is void: find-tag-marker-ring

### ISSUE THREAD

**Issue by radirk** [clojure-emacs/cider#1669]
## Actual Behavior
error in process filter: cider-handle-compilation-errors: Symbol's value as variable is void: find-tag-marker-ring

## Steps to reproduce the problem

Occurs at all eval commands after successful cider-jack-in e.g.
C-c C-k
C-x C-e
Eval/compilation works but M-. is not working (prompt Symbol:). Obviously the find-tag-marker-ring is not filled as it's void.

### Cider Version Information
;; CIDER 0.12.0alpha (package: 20160411.1934), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.7.0_95

### Lein version
Leiningen 2.5.3

### Emacs version
GNU Emacs 24.3.1 (x86_64-suse-linux-gnu, GTK+ Version 3.10.9)

### Operating system
Opensuse 13.1

**Comment by bbatsov** [comment]
I'll take care of this.

**Comment by bbatsov** [comment]
Done. Guess I accidentally deleted it while re-arranging the code. It's strange this didn't produce a compilation warning, though.
