### ISSUE TITLE
Unable to cider-jack-in from emacs, lein repl works fine

### ISSUE THREAD

**Issue by vandr0iy** [clojure-emacs/cider#1670]
![screenshot_2016-04-12_12-59-39](https://cloud.githubusercontent.com/assets/5510334/14458125/74a53b2c-00af-11e6-9a3b-4a363edcc7ca.png)
Good morning,

I just updated my cider from 0.8.1 (because it did not match nrepl's version, which was the 0.12.0-SNAPSHOT
![screenshot_2016-04-12_12-59-39](https://cloud.githubusercontent.com/assets/5510334/14458125/74a53b2c-00af-11e6-9a3b-4a363edcc7ca.png)

) and it is not starting anymore.
I am not very familiar with emacs, but I'll try to provide all of the material I got to reproduce my issue.
Also, this is popping out every time I launch cider-jack-in instead of the old "lein repl :headless"

## Expected behavior
cider starting and connecting to nrepl server

## Actual behavior
this is what emacs prompts in the *Warnings* buffer:
https://paste.debian.net/plain/432332
and this one is the error message emacs prompts in the backtrace buffer (the one showing up when emacs is started with '--debug-init' option:
https://paste.debian.net/plain/432330

## Steps to reproduce the problem
> download the emacs configuration from braveclojure.com:
https://github.com/flyingmachine/emacs-for-clojure
> update the nrepl and cider to the current version
> try to start cider with M-x cider-jack-in

## Environment & Version information
GNU Emacs 24.5.1

### CIDER version information
cider 20160411.1934

###.lein/profiles.clj
{:user {:plugins [[cider/cider-nrepl "0.12.0-SNAPSHOT"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.12"] [org.clojure/clojure "1.8.0"]]}}

###OS
uname -a
Linux 4.5.0-gentoo #1 SMP Wed Mar 16 11:34:11 CET 2016 x86_64 Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz GenuineIntel GNU/Linux

**Comment by expez** [comment]
This is a problem with your config.  Grep it for `global-rainbow-delimiters-mode` and fix whatever the problem is.  Most likely that function is called in a hook and it either doesn't exist at all or the package owning that symbol hasn't been loaded yet.

**Comment by vandr0iy** [comment]
I just removed this line (apparently responsible for having the rainbow parentheses globally in emacs whenever it starts), but when I try to start cider it starts only the lein server. This is what emacs messages say about it:

Starting nREPL server via lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.12.0-SNAPSHOT\"\] -- repl :headless...
nREPL server started on 32956
[nREPL] Establishing direct connection to localhost:32956 ...
[nREPL] Direct connection established
Connected.  Code never lies, comments sometimes do. -Ron Jeffries

**Comment by Malabarba** [comment]
Nope. That message is saying everything is fine. “Direct connection established” means we've connected to the server (a.k.a., “started a REPL”).

If you still don't see a REPL buffer, maybe it's a bad compilation issue. Try removing CIDER, updating your packages, restarting Emacs, and installing CIDER again.

**Comment by vandr0iy** [comment]
Oh... thanks, malabarba! It worked. The issue relative to the global-rainbow-parentheses-mode persists, and I have no idea on how to reenable it, but that's not CIDER's fault.
Thank you very much!

**Comment by waylandc** [comment]
vandr0iyi, just a FYI but the rainbow-delimiters-mode removed support for the 'global' mode. 
[https://github.com/Fanael/rainbow-delimiters#global-mode](url)

**Comment by vandr0iy** [comment]
@waylandc the project does not exist
