### ISSUE TITLE
On-hover tooltips make mouse navigation laggy

### ISSUE THREAD

**Issue by alexander-yakushev** [clojure-emacs/cider#1671]
This new feature is nice, but because of the latency from requesting the tooltips, my first or even subsequent clicks are swallowed or significantly delayed.

## Expected behavior

When I click on a symbol of a function, the cursor should move there immediately.
 
## Actual behavior

The click is often swallowed, or the cursor transition is delayed.
 
## Steps to reproduce the problem

Move the mouse cursor to some function, wait for mere 100ms and then click.

## Environment & Version information

Latest everything.
```
;; CIDER 0.12.0snapshot (package: 20160411.2326), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_74
```

**Comment by bbatsov** [comment]
Guess we should display those in an async manner. Not sure if there are other options we might explore.

We should probably add an option to disable this functionality as well.

**Comment by Malabarba** [comment]
Pushed a change that should fix this. Please let me know if it helped, or I'll look for another solution.

**Comment by alexander-yakushev** [comment]
Oops, forgot to say thank you for this. Thanks @Malabarba and @bbatsov! ;)

**Comment by Malabarba** [comment]
;-)
