### ISSUE TITLE
A way to specify a default for "Which command should be used?" in `cider-jack-in`

### ISSUE THREAD

**Issue by harold** [clojure-emacs/cider#1672]
## My thought

1) When I do `M-x cider-jack-in` (`C-c M-j`) I am presented with a minibuffer saying:

`Which command should be used?` ... I believe this is because our team semi-recently put some boot scripts along side our project.clj.

It would be nice if I could set an elisp variable, or some other mechanism, to force always `lein` there, to remove one-last enter-key press before the repl starts for projects where I know I always want to start the repl with `lein`.

Thanks!

### CIDER version information

```
;; CIDER 0.11.0 (Bulgaria), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_77
```

### Lein/Boot version

2.5.3

### Emacs version

24.4.1

### Operating system

Ubuntu 15.04

**Comment by bbatsov** [comment]
This makes sense. We can certainly do it.

**Comment by Malabarba** [comment]
I'm think we could change the prompt to something like this:

> Choose the command to use: **l**ein, **b**oot.  
> Hold Shift to make the choice permanent.

If the user holds shift, we save the choice to a custom variable.

They can make CIDER “forget” the choice by invoking `cider-jack-in` with a prefix argument.
The prefix argument is already used as “prompt for the project”, but I think it makes sense to extend it to “prompt for things”.

**Comment by bbatsov** [comment]
Interesting idea, although it's not something I've seen so far in Emacs (the "hold shift" part at least).

**Comment by Malabarba** [comment]
Yeah. It would at least let us avoid an extra prompt, and probably make things easier for everybody.

**Comment by dpsutton** [comment]
We talked about this in slack. Thinking so far (and this is by no means binding or the "right" answer):

Have a single defvar that holds the preferred lein or boot, set to nil and must be explicitly set. When there are multiple build systems identified, check to see if the resolution strategy (this variable) is set. If so, use this one, otherwise do the current behavior which is to ask the user.

**Comment by Malabarba** [comment]
Sounds good! Just 3 small changes:

>Have a single **defcustom** that holds the preferred lein, boot, **or gradle** , set to nil and must be explicitly set. When there are multiple build systems identified, check to see if the resolution strategy (this variable) is set **and if it is one of the available options**. If so, use this one, otherwise do the current behavior which is to ask the user.
