### ISSUE TITLE
CIDER Hydras

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/cider#1674]
@bbatsov 

I've created a repository [here](https://github.com/xiongtx/cider-hydras) for CIDER hydras, as mentioned in issue #1411. 

I can't push against [the one you created](https://github.com/clojure-emacs/cider-hydra) because I'm not a member of this group.

Let's see if this is closer to what we want before submitting it to MELPA. In particular, I haven't added any key bindings except for the obvious replacements for prefix keys in `cider-mode-map`; I wonder if we should leave it to the user to bind to the keys they prefer, or introduce defaults of our own.

**Comment by bbatsov** [comment]
> I can't push against the one you created because I'm not a member of this group.

Sorry about this. I've granted you commit access to the repo.

> Let's see if this is closer to what we want before submitting it to MELPA. In particular, I haven't added any key bindings except for the obvious replacements for prefix keys in cider-mode-map; I wonder if we should leave it to the user to bind to the keys they prefer, or introduce defaults of our own.

We can at least suggest some keybindings.

**Comment by bbatsov** [comment]
P.S. You should probably add some animated gif to the readme and mention the new package in cider's manual.

**Comment by bbatsov** [comment]
I also think we need one hydra to navigate to the other other hydras. I'm not an expert, but the idea to have a single point of entry for all commands sounds appealing to me.

**Comment by bbatsov** [comment]
@xiongtx Any progress here?

**Comment by xiongtx** [comment]
It's been a low priority, especially since I thought we were going with `which-key` as a preferred option?

I'll find some time to work over the next few days.

**Comment by bbatsov** [comment]
Great. I just want us to wrap this ticket, obviously you're right and this is not high prio.

**Comment by xiongtx** [comment]
I still don't have access to the @clojure-emacs/cider-hydra repository. I get "permission denied" when trying to push to the repo.

Might this be the issue?

![cider-hydra-no-access](https://cloud.githubusercontent.com/assets/1624090/16860961/1e673b56-4a02-11e6-81b2-a4d6d1103b32.png)

**Comment by Malabarba** [comment]
I just added the repo to the team. Try again. 👍

**Comment by bbatsov** [comment]
We can finally close this.
