### ISSUE TITLE
Disconnect without closing the bufer

### ISSUE THREAD

**Issue by maksr** [clojure-emacs/cider#1675]
Would it be (or is it) possible to disconnect a `*cider-repl...*` buffer from the server without closing the buffer? In other way, making a zoombie nrepl buffer without shutting down the server.
May be it's possible to break the connection in some way in Emacs, but I'm not aware of it.

**Comment by Malabarba** [comment]
You can kill the `*nrepl-server ...*` buffer. That will kill the connection without killing the repl buffer.

**Comment by maksr** [comment]
I'm sorry, I don't see such a buffer. My Cider version is 0.11.0.
I start the session with `cider-connect`, not `cider-jack-in`.

**Comment by Malabarba** [comment]
Ah. Indeed, cider-connect doesn't have a server buffer. I'm afraid there's no good way to get what you're asking for.

If you want to preserve the buffer's content, you can save it to a file (`C-x C-s` or `C-x C-w`).
If you want to preserve the history, you can turn on history saving with `cider-repl-history-file`.

**Comment by maksr** [comment]
I see recent versions of cider can nicely reuse the zoombie repl buffer, so I thouhgt it should not be difficult to get what I want. After a little digging it seems the following
```
M-: (delete-process (get-buffer-process (current-buffer)))
```
does it.

**Comment by Malabarba** [comment]
Great! Guess it shouldn't be hard to make that into a command.

**Comment by maksr** [comment]
It would be fine if the comand were among Cider builtin commands, maybe as `cider-repl-disconnect`.

**Comment by Malabarba** [comment]
Sorry for the accidental close.
While such a command would be fine, it can't be implemented that way. It would have to be a little more respectful to the connection and do something like what `cider--close-buffer` does.

**Comment by bbatsov** [comment]
True. I'm also wondering how to implement this - a defcustom, a new command, some prefix argument... For this is actually much harder than just writing the code to close the connection without closing the REPL buffer.

**Comment by Malabarba** [comment]
Since the OP was the first to ever ask this (that I know) and seems to have already found a custom solution, maybe we can close this issue until more people start asking for it.

**Comment by bbatsov** [comment]
Fair enough.
