### ISSUE TITLE
REPL doesn't interpret carriage return

### ISSUE THREAD

**Issue by thomas-morgan** [clojure-emacs/cider#1677]
I entered `(println "foo\rbar")` in the Cider REPL, hoping to see

```
bar
nil
```

Instead I saw

```
foobar
nil
```

This breaks progress bars among other things, as reported here: <http://stackoverflow.com/questions/34649151/progress-indicator-bar-auto-changed-line-in-cider-nrepl-buffer/34651898#34651898>.

For comparison, `(display "foo\rbar\n")` displays `bar` in the REPL started by `run-guile`.

### CIDER version information

```
;; CIDER 0.11.0 (Bulgaria), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_60
```

### Lein/Boot version

Leiningen 2.6.1 on Java 1.8.0_60 OpenJDK 64-Bit Server VM

### Emacs version

GNU Emacs 24.5.2 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.28) of 2015-09-25 on machine

### Operating system

NixOS 15.09

**Comment by bbatsov** [comment]
Seems you're right - this is a bug. I'm not sure what's causing it, though. The message we send to the nREPL server seems correct to me:

```
(--> 
  ns  "cider-demo.core"
  op  "eval"
  session  "4bab8d15-cbc4-4ec7-a6ad-087c51c37845"
  code  "(println \"foo\\rbar\")\n"
  file  "*cider-repl cider-demo*"
  line  58
  column  17
  id  "55"
)
```

**Comment by bbatsov** [comment]
@dpsutton Maybe you'd like to investigate another REPL bug? :-)

**Comment by dpsutton** [comment]
This appears to be a bug in the `nrepl--bdecode-1` function, 
```

;; normalise any platform-specific newlines
        (let* ((original (buffer-substring-no-properties beg end))
               (result (replace-regexp-in-string "\r" "" original)))
          (cons nil (nrepl--push result stack))))))
```

in nrepl-client.el.  I'm gonna go learn about platform specific newlines as I've never really understood the difference between \r and \r\n, etc. If i remove that line, i'm getting `^M` in the buffer, which is the perennial problem with git on multiple platforms. So I just need to learn the actual issue at hand instead of a hand-wavy idea about newlines.

**Comment by dpsutton** [comment]
I guess I don't know if a `\r` by itself is valid. I've always seen the windows style as `\r\n`, which is why the code was only removing the `\r` by itself. 
```
;; ======================================================================
user> (print "bob\rsmith\n")
bobsmith
nil
user> (print "bob\rsmith\n")
bob
smith
nil
user> (print "bob\r\nsmith\n")
bob

smith
nil
user> 
```

The following works, but I'm not sure if its hacky, nor if its correct. I'll play with this today and see what I can get

```
;; normalise any platform-specific newlines
        (let* ((original (buffer-substring-no-properties beg end))
               (result (replace-regexp-in-string "\r\n" "\n" original))
               (result (replace-regexp-in-string "\r" "\n" result)))
          (cons nil (nrepl--push result stack))))))
```

**Comment by bbatsov** [comment]
Guess there's not much more we can do about this now, so I'll close this. Thanks for fixing the handling for `\r` @dpsutton.
