### ISSUE TITLE
cider-nrepl not installed

### ISSUE THREAD

**Issue by typedeph** [clojure-emacs/cider#1678]
I'm not sure if I'm duplicating a previous issue. If I am please direct me to the issue I can post to.

I just installed Cider from melpa-stable using list-packages. It doesn't work for any configuration I've tried using cider-jack-in. A clean install leads to:
```
WARNING: The following required nREPL ops are not supported: 
  apropos classpath complete eldoc format-code format-edn info inspect-pop inspect-push inspect-refresh macroexpand ns-list ns-vars ns-path refresh resource stacktrace toggle-trace-var toggle-trace-ns undef
  Please, install (or update) cider-nrepl 0.11.0 and restart CIDER
WARNING: CIDER's version (0.11.0) does not match cider-nrepl's version (not installed). Things will break!
```
I tried it first not having a profiles.clj profile at all as the docs say:

```
Starting with version 0.11, When cider-jack-in (C-c M-j) is used, CIDER takes care of injecting it and its other dependencies.
profiles.clj or profile.boot don't need to be modified anymore for the above usecase!
```
and I've tried adding a profiles.clj as pre-0.11 version used to do and nothing works. What should I try next?

**Comment by bbatsov** [comment]
Are you inside your project when doing `cider-jack-in`?

**Comment by typedeph** [comment]
I believe so but correct me if I am wrong since I am a clojure newbie. The file is a local clone of this repo: https://github.com/clojuredatascience/ch1-statistics/blob/master/src/cljds/ch1/core.clj. In the local copy is where I am doing cider-jack-in

**Comment by typedeph** [comment]
I apologize for opening this issue, it seems that the project.clj was hijacking the defaults I was expecting. I realized this after creating a fresh app template with leiningen. I should have inspected the project.clj file and updated the clojure version.
