### ISSUE TITLE
cider-debug-defun-at-point not asking for input ? , not working at all..

### ISSUE THREAD

**Issue by hexa00** [clojure-emacs/cider#1681]
I have a clojure file open then use cider-jack-in to start cider.

I can see I have the cider-mode enabled, most functions work.

If I try to use C-u C-M-x however to instrument and start a debug session, I see a red square on the function name but in the minibuffer all I see as the name of the function being returned.

Then nothing happens... 

I would expect the form to start evaluating and the debugger to ask to to continue etc...

No errors or backtrace with debut-on-error , t :(

I'm on :

;; CIDER 0.12.0snapshot (package: 20160414.1712), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.7.0_95
Leiningen 2.6.1 on Java 1.7.0_95 OpenJDK 64-Bit Server VM
GNU Emacs 24.4.1
Ubuntu linux 14.04

Lein .profile.clj:
{:user {:plugins [[lein-exec "0.3.6"], [lein-drip "0.1.1-SNAPSHOT"]]}}
{:repl {:plugins [[cider/cider-nrepl "0.12.0"]]}}

You can find my init.el at : https://github.com/hexa00/emacs/blob/master/init.el

I can see in the nrepl log:

```
(--> 
  ns  "exclude-clj.core"
  op  "eval"
  session  "6f377b9c-7cff-476e-bfc5-5a11bf2e9e81"
  code  "#dbg\n(defn read-all-tests [filename]\n  (->> (slurp filename)\n       (string/split-lines)\n       (map extract-test-from-all)\n       (set)))\n"
  file  "/home/xx/src/exclude-clj/src/exclude_clj/core.clj"
  line  19
  column  0
  id  "61"
)
(<-- 
  id  "61"
  ns  "exclude-clj.core"
  session  "6f377b9c-7cff-476e-bfc5-5a11bf2e9e81"
  value  "#'exclude-clj.core/read-all-tests"
)
(<-- 
  id  "61"
  session  "6f377b9c-7cff-476e-bfc5-5a11bf2e9e81"
  status  ("done")
)
(<-- 
  changed-namespaces  (dict 
                     exclude-clj.core  (dict 
                                            aliases  (dict 
                                                       set  "clojure.set"
                                                       string  "clojure.string")
                                            interns  (dict 
                                                       extract-test-from-all  (dict 
                                                                                arglists  "([line])")
                                                       extract-test-from-racy  (dict 
                                                                                 arglists  "([racy-line])")
                                                       main  (dict 
                                                               arglists  "([& args])")
                                                       read-all-tests  (dict 
                                                                         arglists  "([filename])"
                                                                         cider.nrepl.middleware.util.instrument/breakfunction  "#'cider.nrepl.middleware.debug/breakpoint-if-interesting")
                                                       read-excluded-tests  (dict 
                                                                              arglists  "([filename])"))))
  id  "61"
  repl-type  "clj"
  session  "6f377b9c-7cff-476e-bfc5-5a11bf2e9e81"
  status  ("state")
)
```
Ideas on what it could be ?

**Comment by Malabarba** [comment]
You have to actually run the function after instrumenting it. :-)

Just evaluate some code that calls the function.

**Comment by hexa00** [comment]
That does not seem to help.

Evaluating the function with C-c C-c does not start the debug.

Evaluation a function calling this function with C-c C-c does not either...

Am I doing it wrong?

Thanks,

**Comment by hexa00** [comment]
Hoo If I call it directly in the repl it works !! :)

But there's no cider keybinding for that or ?

**Comment by bbatsov** [comment]
You'll have to have a function invocation in the source buffer and evaluate it (e.g. with `C-c C-c`). As most functions take some params you can't just run a function without supplying the params, so there's no command to evaluate a definition and run the resulting function.

**Comment by hexa00** [comment]
Right makes sense:)
Thanks for the clarifications !
