### ISSUE TITLE
Give users some indication of the fact that the ns isn't loaded

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1684]
Just a record of a conversation we had on Gitter, so we don't forget about it.

> Bozhidar Batsov Apr 14 14:06
> some status icon that goes from red to green the first time you do load-buffer
> not super reliable, but better than nothing
> guess we can dwell on this for 0.13
> I’ll add something to the REPL for the time being
> 
> Artur Malabarba Apr 14 14:08
> We could also change the lighter to display "not-loaded" instead of clj:PROJECT@:44358

**Comment by NightMachinary** [comment]
What segment of the modeline is responsible for showing the server status? Mine doesn't show it recently (I think it's a spaceline bug, just asking so I can debug it better):
![image](https://user-images.githubusercontent.com/36224762/38863780-fd3b6f10-424d-11e8-96ff-2597c8c4c213.png)

(The server is connected in this buffer)

**Comment by bbatsov** [comment]
Normally it looks like this:

![image](https://user-images.githubusercontent.com/103882/38867873-f11e2f7e-424d-11e8-91e1-770ee647109f.png)

Guess the package the use to modify the modeline looks hid the connection status.
