### ISSUE TITLE
Simplify the keybindings in the macroexpansion buffer

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1685]
There's no need to have people press `C-c C-m` and `C-c M-m` there. We should replace those with single keystrokes. I have no idea what we were thinking originally.

**Comment by dpsutton** [comment]
Have you got ideas for the key bindings? currently they are:

    (define-key map (kbd "g") #'cider-macroexpand-again)
    (define-key map (kbd "q") #'cider-popup-buffer-quit-function)
    (define-key map (kbd "d") #'cider-doc)
    (define-key map (kbd "j") #'cider-javadoc)
    (define-key map (kbd ".") #'cider-find-var)

There are macroexpand-1, presumably to `m` and macroexpand-all to `a` perhaps? And of course these will be the inplace methods. I'd also like a useful reminder of the keybindings here, perhaps binding `?` to display them?

**Comment by bbatsov** [comment]
We can probably also add some keybinding for using `macroexpand` (instead of `macroexpand-1` or `macroexpand-all`. I'd also make `h` display the help as well as `?`.

**Comment by dpsutton** [comment]
I'm not sure that i see a function called `cider-macroexpand`. Is this some type of do what i mean function somewhere or is it the `macroexpand` function written in c in eval.c?

Do you know of a good utility to display the keymappings? I'd like to not reinvent the wheel here and I'm sure there's a good way to do it. Which-key requires a prefix which we have eliminated. I really like the debugger overlay so perhaps adding that style menu might work? Then it doesn't require an explicit invocation but is always right above?

**Comment by bbatsov** [comment]
> I'm not sure that i see a function called cider-macroexpand

`cider-macroexpand-1` uses `macroexpand` when invoked with a prefix argument. I still wonder if this was a good idea or not, but it's not a big deal. 

> Do you know of a good utility to display the keymappings? I'd like to not reinvent the wheel here and I'm sure there's a good way to do it. Which-key requires a prefix which we have eliminated. I really like the debugger overlay so perhaps adding that style menu might work? Then it doesn't require an explicit invocation but is always right above?

The debugger is special, as it's active in source buffers. There's no need to display anything in special buffers - every Emacs user would know to pressess `?` or `h` to see what's available there.

**Comment by bbatsov** [comment]
Fixed in #1704.
