### ISSUE TITLE
Using a number for "port" in cider-known-endpoints throws error

### ISSUE THREAD

**Issue by futuro** [clojure-emacs/cider#1686]
I recently ran into an issue where how I formatted my `cider-known-endpoints` stopped cider-connect from working, and it was really opaque why. The short of it is that `mapconcat` inside of `cider-string-join` doesn't like trying to parse int's, and want's a sequence instead. When you view the docs for cider-known-endpoints, it shows an example with the port in quotes, but it doesn't warn the user that you **must** use quotes.

I'm not sure this needs a fix, I really just wanted to document this in case someone else runs into this problem, and now they can find a fix online.

## Expected behavior
That `cider-connect` won't throw an error with a cider-known-endpoint like `'(("backend" "127.0.0.1" 7000))`.

## Actual behavior
`cider-connect` throws `(wrong-type-argument sequencep 7000)`.

## Steps to reproduce the problem
Set your `cider-known-endpoints` to `'(("backend" "127.0.0.1" 7000))`, then call `cider-connect`.

## User Fix
Wrap your port in quotes. F.e. instead of 
`'(("backend" "127.0.0.1" 7000))` 
use
`'(("backend" "127.0.0.1" "7000"))`

### CIDER version information
```
;; CIDER 0.12.0 (Seattle), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_77
```

### Lein/Boot version

Lein 2.6.1

### Emacs version
24.5.2

### Operating system

Arch Linux

**Comment by Malabarba** [comment]
I've tuned the defcustom so you can't make that mistake from the customize-menu, and I've added an error message that should be more informative.
