### ISSUE TITLE
Should load-buffer undefine any previous defs in that namespace?

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1687]
`cider-load-buffer` currently just sends the entire file to be evaluated. If the file had already been loaded with some functions that have since been removed, these old functions stick around in the repl state. This can easily lead to invalid code as the user can leave around some calls to that function without realising it.

Should load-buffer undefine everything from the namespace before loading it again? This would be a sort of mini-refresh functionality. There are two drawbacks I see with this: 

- `defonce` would be redefined.
- It's common for people to write stateful code inside a `(comment ...)` macro. These would be lost.

**Comment by Malabarba** [comment]
Now that I've written it, I guess the twodrawbacks are not worth the benefit. But I'd like to hear what others think.

**Comment by bbatsov** [comment]
I think that working on something like this would be pointless, given the presence of `cider-refresh`.

**Comment by Malabarba** [comment]
Yeah, I've changed my mind.
