### ISSUE TITLE
Seattle release can't find lein.bat in Windows 10

### ISSUE THREAD

**Issue by jorgeu** [clojure-emacs/cider#1688]
## Expected behavior

cider-jack-in finds lein.bat in c:/Windows/System32/lein.bat

## Actual behavior

The lein executable (specified by `cider-lein-command' or `cider-boot-command') isn't on your `exec-path'

## Steps to reproduce the problem
Install Emacs 24.5 in Windows 10
configure melpa-stable
install cider
open .clj file
Download latest lein.bat 
copy lein.bat to c:\windows\system32
in Emacs M-x (enter) cider-jack-in (enter)

## Environment & Version information
Windows 10
Emacs 24.5
Melpa stable
Cider 0.12.0 
Leiningen 2.6.1 on Java 1.8.0_77 Java HotSpot(TM) 64-Bit Server VM

**Comment by bbatsov** [comment]
Likely this folder is not on your `exec-path` and you'll have to add it there manually.

**Comment by jorgeu** [comment]
![image](https://cloud.githubusercontent.com/assets/965419/14627351/5e152162-05a8-11e6-8cd1-1be12b52e7a6.png)

**Comment by bbatsov** [comment]
What's the result of running `(executable-find "lein")` or `(executable-find "lein.bat")`?

**Comment by jorgeu** [comment]
Both `nil`

Double checked the file can be read and executed by the user. 
![image](https://cloud.githubusercontent.com/assets/965419/14662661/42f4adce-066d-11e6-821f-7c78c2695d04.png)

**Comment by yveszoundi** [comment]
@jorgeu , setting `cider-lein-command` to the full path of the lein command *should* work under Windows.

Have you tried the following?
```lisp
(setq cider-lein-command  "c:/Windows/System32/lein.bat")
```
Alternatively, you could customize the variable in your `custom-file`:
`M-x customize-variable RET cider-lein-command`

**Comment by bbatsov** [comment]
I'm not very familiar with Windows, so I can really suggest how to debug this properly. The `exec-path` seems correct, but probably something else is not; otherwise `executable-find` would work. Guess you can drop this file in another folder and add it explicitly to the `exec-path`. Or do what @yveszoundi suggested.

**Comment by bbatsov** [comment]
I'll close this, as I don't really have anything more to add here. On my Windows machine I've installed lein to a dedicated folder and just added this folder to the `PATH`.
