### ISSUE TITLE
Show which form has been evaluated

### ISSUE THREAD

**Issue by lianxiangru** [clojure-emacs/cider#1689]
Thanks for creating cider. It is really a great tool!

Recently I find sometimes it is a little time wasting to figure out which forms have been sent to the REPL/evaluated and which forms have been changed since last sending.

One possible way to overcome it could be keeping showing the results evaluated, like what is done in proto-repl of atom editor:

![ss](https://cloud.githubusercontent.com/assets/8991941/14613035/672980ee-0568-11e6-9e2b-29f5a411780b.png)

and making the results of the forms have been changed a different color. (Just a suggestion)

**Comment by Malabarba** [comment]
I think it might be possible (and not too difficult) to display a green dot on the fringe at the left of the form start. @bbatsov WDYT?

**Comment by expez** [comment]
How about also briefly flashing an overlay, like those we use in cljr, over the evaluated form?

**Comment by Malabarba** [comment]
IIUC, the point is to have a semi-permanent reminder that this has been evaluated (of course it would have to be removed if the form changes).

**Comment by expez** [comment]
> IIUC, the point is to have a semi-permanent reminder that this has been evaluated (of course it would have to be removed if the form changes).

I got that, but I it made me think of another cool thing we could do :p

**Comment by Malabarba** [comment]
Ah yes. In that case I'm all for it. :-)

**Comment by bbatsov** [comment]
> How about also briefly flashing an overlay, like those we use in cljr, over the form as it gets evaluated?

Doesn't `eval-sexp-fu` do this already? I thought of adding some eval effects to CIDER but I decided that probably it's better to just use the existing package. I know there's some CIDER adapter for `eval-sexp-fu`, but I've never used it myself (looking at the download stats - few people have).

**Comment by bbatsov** [comment]
> IIUC, the point is to have a semi-permanent reminder that this has been evaluated (of course it would have to be removed if the form changes).

I like this (and `eval-sexp-fu` definitely doesn't do this). Although some people might prefer an overlay applied to the form that was evaluated. Btw, we can also change the colour based on whether the evaluation was successful or not.

**Comment by lianxiangru** [comment]
> IIUC, the point is to have a semi-permanent reminder that this has been evaluated (of course it would have to be removed if the form changes).

In my opinion it's better to not remove the reminder, but make a reminder that they are out of date, since an older version of them has been in the namespace. 

Also, keeping the result of the form visible could be helpful.

**Comment by bbatsov** [comment]
> In my opinion it's better to not remove the reminder, but make a reminder that they are out of date, since an older version of them has been in the namespace.

That'd be both hard and confusing IMO, so I'd rather not go into such extremes. I guess you're thinking that'd be great for definition, but there plenty of other forms you can evaluate and it gets pretty sketchy when you factor them in.

**Comment by lianxiangru** [comment]
> That'd be both hard and confusing IMO, so I'd rather not go into such extremes. I guess you're thinking that'd be great for definition, but there plenty of other forms you can evaluate and it gets pretty sketchy when you factor them in.

I see your point. Yes it will be neater to just remove the reminders on edited forms. What do you think about showing the results of the form compared with showing an indicator of whether it is evaluated?

**Comment by Malabarba** [comment]
@lianxiangru You can set `cider-eval-result-duration` to nil and the overlays will stick around permanently.

**Comment by lianxiangru** [comment]
@Malabarba Thank you. That helps, though it does not disappear after the form is modified.
Given that, probably an indicator/reminder is enough.

**Comment by Malabarba** [comment]
>  though it does not disappear after the form is modified.

That should be fixed now.

**Comment by lianxiangru** [comment]
@Malabarba That works! Thank you!

**Comment by Malabarba** [comment]
FOrgot to tag this for closing in the PR.

**Comment by lxr-shadow** [comment]
@Malabarba Sorry to reopen this. It seems that if I evaluate multiple forms at once (e.g. using evaluate region or evaluate buffer), only the overlay of the last form will be shown. It is better to show a overlay for every form, isn't it?
