### ISSUE TITLE
Set the max length of the eval result

### ISSUE THREAD

**Issue by lianxiangru** [clojure-emacs/cider#1692]
Could the maximum length of the eval result be set to a value? Sometimes the result is extremely long, for example the result is the body of a webpage 
![ss](https://cloud.githubusercontent.com/assets/8991941/14623453/61abeb38-05a0-11e6-8c3d-3248bf7e21ea.png)
It would be helpful if the length could be limited.

**Comment by bbatsov** [comment]
Ideally we should add some folding, instead of just cutting this up to some length. Maybe down the road we also add the ability to expand nested arrays/maps/sets.

**Comment by Malabarba** [comment]
The problem is that it's impossible to click on that overlay. It's really an `after-string

**Comment by Malabarba** [comment]
The problem is that it's impossible to click on that overlay. What you see there is not really the overlay, it's just an `after-string` property.

Of course, we can truncate it. I'm just saying there's no good way to make it expandable.

**Comment by lianxiangru** [comment]
> Ideally we should add some folding, instead of just cutting this up to some length. Maybe down the road we also add the ability to expand nested arrays/maps/sets. 

Folding is definitely way better than just cutting them, while we can simply cut them before we have the folding functionality to solve the problem to some extent :)

> The problem is that it's impossible to click on that overlay. What you see there is not really the overlay, it's just an after-string property.

Could be folding them at the first place and then expanding them in another buffer if the expanding keystroke is received a good solution? In that way we can make the interaction part in another buffer without using the overlays.

**Comment by bbatsov** [comment]
Maybe. I'll defer to @Malabarba for this, as his our overlays master.

But at any rate - I'm fine with adding some limit after which overlay results get truncated.

**Comment by lianxiangru** [comment]
Great! Thank you all :+1:

**Comment by Malabarba** [comment]
Truncation done. And an inspection command has been added for this purpose.
