### ISSUE TITLE
warn when clojure version is not supported

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/cider#1698]
## Expected behavior

Cider only currently supports clojure versions 1.7.0 and 1.8.0
It would be preferable if the following was displayed when using cider with older versions of clojure:
![image](https://cloud.githubusercontent.com/assets/6377293/14660402/b205712e-066a-11e6-8ed8-b7dd4f56c79b.png)

I've created a fork and I've got some of the functionality going. I'm putting this in inside of the function `cider--connected-handler`. There is an a-list of project types and their project files that I have extracted and can now reuse this. This is on my fork at [github:dpsutton/cider](https://www.github.com/dpsutton/cider)

1. [extract the alist](https://github.com/dpsutton/cider/commit/6445c6ee9a0f96dbe7407599ee027de1c1ff6772)
2. [add checking to the jack in process](https://github.com/dpsutton/cider/commit/1b3d38940d66d051fee760bfa3e8d3d3204c2fd3)
3. [where i need help](https://github.com/dpsutton/cider/commit/5e054b2730bd2e100eae20bab27202a2161bffa2)

I'm not sure of the best way to try to visit all of the project type files (using the same info from the alist) to determine the clojure version. I feel like a simple regex, with-current-buffer and try to open a file and we are done. I'm playing around and reading docs to make sure that I do this in a safe and idiomatic way.

## Actual behavior
When you run `cider-jack-in`, there are issues if the clojure version is not supported. However, this currently displays:

![image](https://cloud.githubusercontent.com/assets/6377293/14660442/0b9157ee-066b-11e6-9393-d5ef7af821ae.png)

This is obviously unhelpful, as it does not help to diagnose the problem (things do break, like navigating to definition) as well as it _misleads_ in diagnosing the problem.
## Steps to reproduce the problem
Having a dependency of 1.6.0 triggers this for me.

### CIDER version information
I'm running the seattle version

```
;; CIDER 0.12.0snapshot (package: 20160331.421), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_31
```

### Lein/Boot version

*E.g. Lein 2.6.1* (skip this when you didn't start the nREPL server
using Lein or Boot)

### Emacs version

*E.g. 24.5* (use <kbd>M-x emacs-version</kbd> to check it if unsure)
I'm building emacs from source and this is some random commit on 25 branch from a month or so ago.

### Operating system
Fedora 23.

**Comment by dpsutton** [comment]
I've got the following to visit the files, but its not quite right and I'm not sure what the issue is:

    (defun cider--try-open-project-file-for-clojure-version (file)
      "Given a project FILE, try to open it and determine if there is a clojure
      version in it."
      (let ((filename (concat (clojure-project-dir (cider-current-dir)) file)))
        (when (file-exists-p filename)
          (with-temp-buffer
            (insert-file-contents
             filename
             (save-excursion
               (goto-char (point-min))
               (when (re-search-forward cider--clojure-version-regex nil t)
                 (buffer-substring-no-properties (match-beginning 1) (match-end 1)))))))))

    (defvar cider--clojure-version-regex
      "org.clojure/clojure\s-*\"\\(.*\\)\""
      "Regex for matching clojure version in project files like project.clj,
      boot.clj, etc.")

When i'm running the regex on my project file it works, but i'm somehow not getting the contents into the temp-buffer correctly i think. But once this is done, I just map this function over the cdr's of the (lein . project.clj) ... alist and then we are done i think

**Comment by Malabarba** [comment]
Your save-excursion is inside the insert-file-contents. That's why it's not working. 

Also, use expand-file-name instead of concat.

**Comment by dpsutton** [comment]
Ah thanks @Malabarba. Just figured out the save excursion. 
I've switched to expand-file-name. As it stands, the feature is now working correctly. You can see the commits if you like over at [github:dpsutton/cider](https://www.github.com/dpsutton/cider).  As it stands now, if the clojure version is too low, it prints both the previous nrpel cryptic message as well as the message about the mismatch in clojure version. I'm trying to figure out where to slot this in. I might just move this function call to inside of the check-middleware check.

**Comment by dpsutton** [comment]
![image](https://cloud.githubusercontent.com/assets/6377293/14662486/33c7e5aa-067c-11e6-9e11-70e77bf9926a.png)

**Comment by dpsutton** [comment]
Ok. I've updated my repo to be a fork (according to github) of this one. I'm conflicted about what to do about the above output: should the nrepl warning be visible? should it show a different message when clojure version mismatch also exists? 

I might dig around and see where i can find cider-nrepl's version number being returned as nil before submitting a pull request.

Also I wasn't sure what the opinions were on tests but it might be possible to change this a little bit more to put most stuff in more or less pure functions that will be easier to test.

**Comment by Malabarba** [comment]
(Just to keep this issue in sync with the State of things) There was a conversation on slack and we figured it's better to just eval `*clojure-version*` after connecting.

**Comment by dpsutton** [comment]
ah ok. I'll change it tonight. About to get off from work.

**Comment by dpsutton** [comment]
@Malabarba on slack, it looked like @bbatsov was saying that 

> 
@malabarba: The problem is that you can’t really check the version this way
>
[4:53] 
as the middleware will blow up before you can evaluate any code...

Is he saying that if you're worried about invalid state in your middleware, you can't use it to query which version of clojure you are running?

**Comment by Malabarba** [comment]
I'm not sure. But I just tested it locally and evaluation does work. The CIDER middleware blows up, but tools.nrepl (which provides evaluation) still works.
So evaluating `*clojure-version*` works fine and returns `{:major 1, :minor 6, :incremental 0, :qualifier nil}`.

Now that I see it, I think the easiest approach would be to evaluate `(>= (:minor *clojure-version*) 7)` and check that the `value` in the response equals `"true"`.

**Comment by dpsutton** [comment]
I ran into that issue of `*clojure-version*` returning the map so i found that `(clojure-version)` returns the string (actually `"\"1.8.0\"'` so i strip out the escaped ones). I've got the pull request up and its much simpler than before. includes the pull request checklist as well

**Comment by dpsutton** [comment]
Hmm. that information doesn't seem to be populated. I'm not sure how that value is set.

    (defun cider--clojure-version ()
      "Retrieve the underlying connection's Clojure version."
      (with-current-buffer (cider-current-connection "clj")
        (when nrepl-versions
          (thread-first nrepl-versions
            (nrepl-dict-get "clojure")
            (nrepl-dict-get "version-string")))))

    (defun cider--nrepl-version ()
      "Retrieve the underlying connection's nREPL version."
      (with-current-buffer (cider-current-connection "clj")
        (when nrepl-versions
          (thread-first nrepl-versions
            (nrepl-dict-get "nrepl")
            (nrepl-dict-get "version-string")))))

Mine is exactly the same. I'm not sure where this actually gets populated

**Comment by dpsutton** [comment]
Updated with both of your suggestions and we are good to go.
