### ISSUE TITLE
Break the text in the error field of cider-test-error-report

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1707]
Here is an example of how the error of a failing test:

![image](https://cloud.githubusercontent.com/assets/1006557/14738970/1c2662f4-0885-11e6-9526-b30aa3560766.png)

The problem I'm having is that this is quite unreadable, as it's just one long line and I have to scroll to read it all.  

If I hit <kbd>RET</kbd> on the error to get the stracktrace buffer to popup, I can read the message with proper text breaks.  This is now my current workflow.

It looks this is just dumping the `ExceptionInfo` on one line.  Perhaps we can split it into `msg` and `cause` and wrap the message text so it's readable without scrolling?

**Comment by Malabarba** [comment]
Formatting the exception cause message does make sense to me. I've ran into that problem as well.

**Comment by bbatsov** [comment]
Yeah, there's definitely room for improvement here. I wonder why the line wasn't wrapped though, as I seem to recall such long messages were wrapped for me.

**Comment by bbatsov** [comment]
@jeffvalk Any thoughts on this?

**Comment by jeffvalk** [comment]
I seem to recall that wrapping the error text broke some other formatting, so I kept it simple. That made sense then, but I certainly agree it would be better.
