### ISSUE TITLE
Symbols with colons in the middle break other-namespace auto-completion.

### ISSUE THREAD

**Issue by sdegutis** [clojure-emacs/cider#1709]
## Expected behavior

In namespace `a` run `(def foo:bar 1)` and (def foo:quux 2).

In namespace `b`, make an alias to `a`, and type `(a/foo`. The auto-completion menu pops up. Type `:` and it should narrow down the choices between `foo:bar` and `foo:quux`.

## Actual behavior

The autocomplete menu actually goes away.

## Version information

Latest everything as of the time of writing.

**Comment by bbatsov** [comment]
Oh, I didn't even know such symbols were legal in Clojure. It never seizes to amaze me...

**Comment by sdegutis** [comment]
@bbatsov we just discovered this the other day in `#clojure`, the official docs say `:` is valid except at the beginning or end of a symbol, and when there's no more than one in a row. So `foo:`, `:foo`, and `foo::bar` are all invalid symbols, but `foo:bar` and `foo:bar:quux` are both fine.

**Comment by sdegutis** [comment]
Wow, these rules are a lot different than I thought:

* Symbols begin with a non-numeric character and can contain alphanumeric characters and `*`, `+`, `!`, `-`, `_`, `'`, and `?` (other characters may be allowed eventually).
* `/` has special meaning, it can be used once in the middle of a symbol to separate the namespace from the name, e.g. my-namespace/foo. `/` by itself names the division function.
* `.` has special meaning - it can be used one or more times in the middle of a symbol to designate a fully-qualified class name, e.g. `java.util.BitSet`, or in namespace names. Symbols beginning or ending with `.` are reserved by Clojure. Symbols containing `/` or `.` are said to be "qualified".
* Symbols beginning or ending with `:` are reserved by Clojure. A symbol can contain one or more non-repeating `:`s.

[Source.](http://clojure.org/reference/reader)

**Comment by bbatsov** [comment]
And as far as I know Clojure itself doesn't follow them - e.g. `'` at the end is not allowed officially, but it actually works...

**Comment by sdegutis** [comment]
@bbatsov Oh? Where does it say `'` isn't allowed at the end?

**Comment by sdegutis** [comment]
FWIW, the specific use-case I've found `foo:bar` for is when making enum-like things, such as `unit:day` and `unit:month`, (which refer to `ChronoUnits/DAYS` etc.) etc.

**Comment by expez** [comment]
> And as far as I know Clojure itself doesn't follow them - e.g. `'` at the end is not allowed officially, but it actually works...

There has been functions containing `'` in core since forever, but this is the first time I can remember seeing it mentioned explicitly in the reader docs.  Guess it's been blessed :)

**Comment by bbatsov** [comment]
Hmm, that's new for sure. I remember this discussion - https://github.com/clojure-emacs/clojure-mode/issues/290

**Comment by dpsutton** [comment]
(--> 
      op  "complete"
      session  "3a323a7c-e91d-4310-8b80-edf7b405cfc1"
      ns  "b"
      symbol  "a/foo"
      context  ":same"
      id  "1572"
    )
    (<-- 
      completions  ((dict "candidate" "a/foo:bar")
     (dict "candidate" "a/foo:qux"))
      id  "1572"
      session  "3a323a7c-e91d-4310-8b80-edf7b405cfc1"
      status  ("done")
    )
    (--> 
      op  "complete"
      session  "3a323a7c-e91d-4310-8b80-edf7b405cfc1"
      ns  "b"
      symbol  "a/foo:"
      context  ":same"
      id  "1574"
    )
    (<-- 
      completions  nil  id  "1574"
      session  "3a323a7c-e91d-4310-8b80-edf7b405cfc1"
      status  ("done")
    )


I was looking into `nrepl-bdecode` to see if this was an encoding issue as there is a `:` in one of the cond looking-at cases, but it seems that nothing is coming back from the java side. I don't think this is a CIDER issue per se in that sense.

I'm gonna look into the java side of it but i've never really debugged that, and I'm not sure how to get that going.

**Comment by dpsutton** [comment]
Looking on the clojure side, it looks like the nrepl-completion just politely asks compliment, which is where I suspect that nothing is coming back.

**Comment by dpsutton** [comment]
I believe that this issue has been closed now. So when the middleware updates the version of compliment we should be good to go.

**Comment by bbatsov** [comment]
Indeed. I'll close this.
