### ISSUE TITLE
cider-interactive-eval-result-prefix seems not respected

### ISSUE THREAD

**Issue by BrunoBonacci** [clojure-emacs/cider#1718]
## Expected behavior

After setting `cider-interactive-eval-result-prefix` and running evaluation with <kbd>C-u C-c C-e</kbd>
the output of the expression evaluation should insert in the buffer with the given prefix.

Example:
```
;; in *scratch* buffer
(setq cider-interactive-eval-result-prefix ";;=> ")
```

```
;; in a Clojure buffer eval with C-u C-c C-e
(+ 1 1)
;;=> 2
```
Searching in github for the `cider-interactive-eval-result-prefix` it seems isn't utilised at all.
I guess that the var should be included at this line:
https://github.com/clojure-emacs/cider/blob/6ae64216162b636c1c24e3ca5d322cb16fe7ef64/cider-interaction.el#L701

## Actual behavior

Result is added in the buffer **without** prefix
```
;; in a Clojure buffer eval with C-u C-c C-e
(+ 1 1)
2
```

## Steps to reproduce the problem

set the var:
```
(setq cider-interactive-eval-result-prefix ";;=> ")
```
Then run `M-x cider-jack-in` and evaluate a clojure expression
with <kbd>C-u C-c C-e</kbd>

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.13.0snapshot (package: 20160423.2330), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_45
```

### Emacs version

*GNU Emacs 24.5.1*

### Operating system

*OS X 10.11 "El Capitan"*

**Comment by Malabarba** [comment]
I think that's a documentation bug. The docs should say `cider-eval-result-prefix` instead, which is a real variable that's used twice at least in cider-overlays.el.

However, that's not going to help your case. That prefix is used only when displaying the result. It does not get inserted into the buffer when you do `C-u C-c C-e`.

I think there's a separate command for what you want. It's called `cider-eval-defun-to-comment`, or something similar.

**Comment by BrunoBonacci** [comment]
Thanks @Malabarba, 

`cider-eval-defun-to-comment` is bound to `C-c M-;`

https://github.com/clojure-emacs/cider/blob/master/cider-mode.el#L290
