### ISSUE TITLE
Add defcustom for cider--help-echo

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1719]
I'd love to be able to turn this off

**Comment by expez** [comment]
Yes, though the `defcustom` should use the `cider-` prefix so it's properly namespaced.

**Comment by edipofederle** [comment]
Nice. Yes, I take a look in some `defcustom` examples on the code. One more this. I see that `cider--help-echo` is used  here: https://github.com/clojure-emacs/cider/blob/93651b7853eb9605fa49fcaa03c0314f9c6abc52/cider-mode.el#L689

I should check for setting on this function or in `cider--help-echo itself`?

Thanks

**Comment by expez** [comment]
The former, imo.

**Comment by Malabarba** [comment]
`cider-use-tooltips`, people. :-)

**Comment by Malabarba** [comment]
Guess I should alias it to cider-use-help-echo

**Comment by expez** [comment]
I tried finding this setting by looking for a guard around `cider--help-echo`.  Guess I should've looked at the source code of `cider--help-echo` too, to see if it conditionally created tooltips.  Sorry for the noise ;(
