### ISSUE TITLE
Keybinding for evaluating current form

### ISSUE THREAD

**Issue by ryepesg** [clojure-emacs/cider#1720]
`C-c C-c` evaluates the top level form, but some times you want to evaluate just the most near current form. For example in the following code when you have the cursor on the word _reduce_, there is not an easy way to evaluate just _(reduce + [1 2 3])_:

```
(defn f []
  (inc (redu|ce + [1 2 3])))
```

My suggested keybinding for this functionality is `C-c C-v`.

**Comment by expez** [comment]
You should use <kbd>C-x C-e</kbd>.   Just move your cursor a little :)

**Comment by ryepesg** [comment]
Thank you, I know it is a possibility, but still you have to come back again to continue editing your form. Also, in nested forms is not that easy find the correct parenthesis without move, visually check highlighted parenthesis, move again, visually check...

**Comment by bbatsov** [comment]
I think such a command makes sense. From time to time I've wondered myself why no (few?) Emacs modes have it.

**Comment by Malabarba** [comment]
I've had several people ask me why cider evals the previous sexp instead of the current one, so I guess this command would make sense to a lot of people.

**Comment by ryepesg** [comment]
So fast! Thank you!!
