### ISSUE TITLE
Improve the eldoc for interop forms

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1725]
Currently the eldoc for interop forms is not very clear. We simply display the name of the method and all possible arglists from all matching classes. I'm reasonably sure not all users are aware of this.

We can improve this a bit in the following manner:

* display the class name when the method/field in question is present in just one class
* display the number of matching classes (or their names) before the method name in cases of ambiguities

Some the end results should be something like "SomeClass/someMethod: ..." and "(n classes)/someMethod: ...".

**Comment by cskksc** [comment]
I'd like to give this a try. I'll submit a PR soon.

**Comment by bbatsov** [comment]
Great!
