### ISSUE TITLE
Improve the presentation of nrepl messages

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1726]
The presentation of nREPL messages we currently use leaves a ton of room for improvement.

![image](https://cloud.githubusercontent.com/assets/103882/14937348/a20f9202-0eb9-11e6-9a53-e302cb7e4859.png)
- we lack proper font-locking that would make it easier to figure out what is what
- even the standard message keys are displayed in different order in every message
- values are not properly indented
- sometimes several keys end up being displayed on the same line, which gets me every time (I just miss the second key)

**Comment by bbatsov** [comment]
[This article](http://www.wilfred.me.uk/blog/2016/04/28/effortless-major-mode-development/) might be useful for the font-locking code if anyone decides to tackle this.

**Comment by Malabarba** [comment]
Font locking in the sense of font-lock-mode shouldn't be necessary. We can just propertize a specific face to every other sexp.

**Comment by bbatsov** [comment]
True. I mostly want top-level keys to stand out. Bonus points for properly font-locked, strings, nils, etc.

**Comment by dpsutton** [comment]
Did @Malabarba 's commit fully satisfy the request? I find myself reinventing lots of things in cider only to find out that the necessary features already exist, there's a pattern to follow, etc. If yall would put a few pointers in here I'd be happy to run through and work on this.

**Comment by Malabarba** [comment]
My commit only highlights the request's keys, which was the lowest-hanging of the fruits here. I feel that improves the readability significantly.

It would also be nice to have proper string font-locking and proper indentation, but these might be a little more difficult to do efficiently (without making the buffer supper slow) and they're really not high priority for me.

**Comment by bbatsov** [comment]
I'd say that ordering the request/response keys consistently should be relatively easy to do and would be very helpful as well. Tackling the bug with several keys getting displayed on the same line is also important.

**Comment by bbatsov** [comment]
@dpsutton This ticket is still yours if you want it. ;-)

**Comment by Malabarba** [comment]
Given that this only really affects the cider developers, and even we weren't bothered enough to actually do something significant about it, maybe it's not that relevant. People's effort might be better spent elsewhere.

**Comment by bbatsov** [comment]
While this is true, this issue still represents an open thread and requires way less effort than most open tasks we have. I've been trying to do some cleanup lately, as tasks really piled on in the past 5-6 months. Hopefully contributor activity will pick up, as I'm pretty short on time myself.

**Comment by harold** [comment]
After goofing around here for a bit another potential improvement would be:

```
(-->
  code     "(defn map-sequence->dataset "Turns an infinite training se..."
  column   1
  file     "/home/harold/src/cortex/src/cortex/dataset.clj"
  id       "45"
  line     377
  ns       "cortex.dataset"
  op       "eval"
  session  "499ca8d8-43c8-40bf-aa19-ff369673ce4c"
)
```

over the existing

```
(-->
  code  "(defn map-sequence->dataset "Turns an infinite training se..."
  column  1
  file  "/home/harold/src/cortex/src/cortex/dataset.clj"
  id  "45"
  line  377
  ns  "cortex.dataset"
  op  "eval"
  session  "499ca8d8-43c8-40bf-aa19-ff369673ce4c"
)
```

**Comment by bbatsov** [comment]
Yeah, that'd be pretty great and pretty easy as well.

**Comment by harold** [comment]
Updated the PR with an additional commit.

**Comment by dpsutton** [comment]
the build failed with
> nrepl-client.el:1324:1:Error: the function ‘copy-list’ is not known to be defined

![image](https://cloud.githubusercontent.com/assets/6377293/23764136/072278d6-04c2-11e7-9185-7d4f8294189a.png)

**Comment by harold** [comment]
@dpsutton I believe that's fixed in the latest commit. See the discussion on the PR.
