### ISSUE TITLE
I don't have a ClojureScript REPL when working with Weasel/Piggieback

### ISSUE THREAD

**Issue by turbopape** [clojure-emacs/cider#1730]
## Expected behavior
Even if I follow the instructions of setting up PiggieBack/Weasel for Cider, when I cider-jack-in-clojurescript Must give me tow repls : one for Clojure and one for ClojureScript.
## Actual behavior
I only have the Clojure REPL.
## Steps to reproduce the problem
1. Add piggieback and weasel dependencies
2. Add the Weasel Code to connect the browser to the cljs REPL
3. Set the cider-cljs-lein-repl to Weasel
4. visit a Cljs Buffer
5. M-x cider-jack-in-clojurescript

### CIDER version information
CIDER 0.13.0snapshot (package: 20160501.1921), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_92

### Lein/Boot version
lein 2.6.1

### Emacs version
Emacs 25.0.92.1

### Operating system
OS X 10.11 "El Capitan"

### Miscellaneous
piggieback 0.2.1, Weasel 0.7.0, lein-cljsbuild  1.1.3

**Comment by Malabarba** [comment]
>Actual behavior
>I only have the Clojure REPL.

Do you get 2 Clojure REPLs or just 1 Clojure REPL? (Look for buffers called `*cider-repl ...`).

**Comment by turbopape** [comment]
Hi, I just get 1 Clojure REPL ...

**Comment by turbopape** [comment]
I Only get one Clojrure REPL.

**Comment by Malabarba** [comment]
Then it's not about weasel. You should get two repls no matter what. 

There's something wrong with cider for you. Try reinstalling.

**Comment by turbopape** [comment]
Hi, 

Actually, If I cider-jack-in-clojruescript in a non weasel project, I have the two REPLS (with the cljs complaining about not finding the weasel class obviously)

But in a weasel project, I think the CLJS REPL creation aborts with the following message:

error in process filter: run-hooks: Symbol’s function definition is void: cider-turn-on-eldoc-mode

**Comment by Malabarba** [comment]
> error in process filter: run-hooks: Symbol’s function definition is void: cider-turn-on-eldoc-mode

Remove this function from your configs. It doesn't exist anymore. Just use `eldoc-mode` instead.

**Comment by turbopape** [comment]
Hi @Malabarba,

Once I removed the erroneous function, everything is working good again !

Tahnk you !
