### ISSUE TITLE
Improve class names in eldoc for interop forms

### ISSUE THREAD

**Issue by cskksc** [clojure-emacs/cider#1735]
## Actual behavior
<img width="303" alt="screen shot 2016-05-06 at 8 19 13 am" src="https://cloud.githubusercontent.com/assets/5201497/15062947/52e37064-1363-11e6-9e6d-ecc505da5bd8.png">

## Steps to reproduce the problem

In a clojure buffer with active nREPL connection, enter the form ` (java.lang.X/.length)`
When the cursor is on the form `(java.lang.X/.length)`, the eldoc is shown as is ; `(java.lang.X/.length): ([this])`, because the ns entered by user is always prioritised.

## Suggested behaviour

From the information returned by the middleware, we know that `.length` is not a member of class X. Should we display some warning in such case ? But if that class is not loaded, or we don't have its eldoc information, our warning would be totally wrong.

This is just a "good to have" sort of thing, as the class name is rarely used with an interop form.
Relevant PR, #1729 .

**Comment by Malabarba** [comment]
If we know that it's not a member we should simply not display the eldoc hint.

I'm fine with displaying a warning about this kind of stuff, but I think it's not eldoc's job to do it.

**Comment by bbatsov** [comment]
Yeah, probably not displaying anything would be best.

**Comment by cskksc** [comment]
Ok. I'll submit a PR for this. Skipping the `warning` bit.
