### ISSUE TITLE
[debugger] Local values in tooltip

### ISSUE THREAD

**Issue by harold** [clojure-emacs/cider#1737]
I am in the debugger (and wow, is it nice!), when I mouse hover local variables I get a nice tooltip-like thing with:

```
`x' is a local
````

cooler would be 
```
`x' is a local with value 4
```

(where 4 is the current value of x). 

fwiw, the `l` key works well for finding out the values of locals, but the mouse hover workflow would be neat too, I think.

**Comment by harold** [comment]
I realize now that the tooltip thing isn't even really coming from the debugger, it's the doc tooltip.

It would be neat if the debugger provided a bit more data (since it presumably has it).

Thanks again for cider, I think I'll go have a sip now.

**Comment by Malabarba** [comment]
I appreciate the assignment, but I have some stuff on my plate right now. I'd rather leave it open to volunteers. :-)

**Comment by bbatsov** [comment]
Fair enough. :-)

**Comment by Malabarba** [comment]
And, for anyone reading, this is indeed pretty easy. The debugger keeps track of the most recent message, and the message contains locals information, so we just need to look in there.
