### ISSUE TITLE
How to override 80-line rule for long string literals?

### ISSUE THREAD

**Issue by blueberry** [clojure-emacs/cider#1739]
My Clojure code occasionally contains strings that are rather long. Emacs displays them properly, following the 80-line rule.
However, sometimes I have long strings that I'd like to see in their normal color. Is there a way to do that in emacs and cider?

**Comment by bbatsov** [comment]
Pretty sure cider has nothing to do with this. Probably you're using whitespace-mode or something like this. If you show us some screenshots we might be able to give you some advice what to do.

**Comment by blueberry** [comment]
That was it. Disabled whitespace-mode (I'm using prelude, so didn't know everything that was there). Thanks!
