### ISSUE TITLE
eldoc only available for functions of current namespace

### ISSUE THREAD

**Issue by mallt** [clojure-emacs/cider#1740]
## Expected behavior
eldoc available for all namespaces (current and required)

## Actual behavior
eldoc only available for current namespace, not for required namespaces

## Steps to reproduce the problem
position point on a function of a required namespace => no eldoc available in the minibuffer

### CIDER version information
;; CIDER 0.13.0snapshot (package: 20160506.1235), nREPL 0.2.12
;; Clojure 1.7.0, Java 1.8.0_72-internal

### Emacs version
GNU Emacs 24.5.1 

### Operating system
Ubuntu 14.04

**Comment by cskksc** [comment]
@mallt Is the required namespace being used with a alias ? Some recent changes in eldoc have introduced this bug. It'll be fixed soon.

**Comment by mallt** [comment]
Yes, it is used with an alias indeed. Thank you!

**Comment by bbatsov** [comment]
> @mallt Is the required namespace being used with a alias ? While making some changes in eldoc, I have introduced this bug. It'll be fixed soon.

The classes changes broke this?

**Comment by cskksc** [comment]
@bbatsov Yes. I am working on the PR. It'll be done in a bit.

**Comment by cskksc** [comment]
@mallt Can you please pull the latest master and check if the issue is resolved ?

**Comment by Malabarba** [comment]
Or just update from Melpa. :-)

**Comment by mallt** [comment]
@cskksc The issue is resolved, thanks!
