### ISSUE TITLE
Support a default pprint with fipp

### ISSUE THREAD

**Issue by priyatam** [clojure-emacs/cider#1743]
Cider currently does not support pretty print out of the box. The configuration and setup for 0.12.0 is broken and needlessly complicated. Please provide a sensible default.

## Expected behavior

The console and cider repl results should be pretty printed, colorized, etc.,

## Actual behavior

Console or Cider repl is not pretty printed.

## Steps to reproduce

- add `(setq cider-pprint-fn "puget.printer/pprint")`
- and [puget](https://github.com/greglook/puget) or [whidbey](https://github.com/greglook/whidbey) in user plugins under `~./lein/profiles.clj`
- start repl manually via `lein with-profile +local repl :headless`
- cider-connect and eval 

## Environment

- CIDER 0.12.0 (stable)
- Clojure 1.7.0, Java 1.8.0_51
- Lein 2.6.1
- Emacs 24.5.1
- OS X 10.11 "El Capitan"

**Comment by bbatsov** [comment]
> Cider currently does not support pretty print out of the box. The configuration and setup for 0.12.0 is broken and needlessly complicated. Please provide a sensible default.

Broken how?

> The console and cider repl results should be pretty printed, colorized, etc.,

That's pretty subjective. Seems that most people are perfectly fine with the default behaviour.

**Comment by Malabarba** [comment]
> The console and cider repl results should be pretty printed, colorized, etc.

I don't know what you mean by console, but the cider-repl result *is* colorized, and you can set it to be pretty-printed by simply doing `(setq cider-repl-use-pretty-printing t)`. Does that work for you?

**Comment by bbatsov** [comment]
Closing due to lack of an answer.
