### ISSUE TITLE
overlays are shown white instead of font locked as clojure

### ISSUE THREAD

**Issue by mallt** [clojure-emacs/cider#1747]
## Expected behavior
Overlays are font-locked as clojure code if the var cider-overlays-use-font-lock is set to t.

## Actual behavior
Overlays are shown white 

### CIDER version information
;; CIDER 0.13.0snapshot (package: 20160510.2138), nREPL 0.2.12
;; Clojure 1.7.0, Java 1.8.0_91

### Emacs version
24.5.1

### Operating system
Ubuntu 14.04

**Comment by Malabarba** [comment]
I have no idea what could have caused this. Have you recently installed any packages or changed anything that could affect this?

**Comment by mallt** [comment]
For some reason the (prepend-face 'cider-result-overlay-face) in cider--make-result-overlay seems to be causing this behavior.

If I outcomment the funcall:
          ;; (funcall (if cider-overlays-use-font-lock
          ;;              #'font-lock-prepend-text-property
          ;;            #'put-text-property)
          ;;          0 (length display-string)
          ;;          'face prepend-face
          ;;          display-string)

the overlay is displayed correctly.

If I check my cider-result-overlay-face, the state says "THEMED", and only the foreground is set to white. So if I understand correctly, even if cider-overlays-use-font-lock is set to true, this white foreground will be applied to the overlays?

**Comment by Malabarba** [comment]
Ah, yes. That face is applied on top of the font locking, so it should NOT have a foreground.

**Comment by mallt** [comment]
Thanks for the help! Apparently the white foreground of the cider-result-overlay-face is set in the theme I use (solarized). I fixed the issue by removing the foreground in the solarized.el file. I'll try to submit a pull request for that repo later on.

**Comment by Malabarba** [comment]
Thanks. I'm sure other people will have the same problem.

**Comment by malchmih** [comment]
Looks like I might have got the same issue with the zenburn theme.
![image](https://cloud.githubusercontent.com/assets/450680/19400653/cf53189a-925f-11e6-881f-6955e92bdd08.png)
My config for cider looks like this:
```
      (setq default-fill-column 80
            nrepl-log-messages nil
            nrepl-hide-special-buffers t
            cider-repl-prompt-function 'cider-repl-prompt-abbreviated
            cider-prompt-for-symbol nil
            cider-repl-display-in-current-window t
            cider-font-lock-dynamically '(macro core function var)
            cider-overlays-use-font-lock t
            cider-repl-toggle-pretty-printing t)
```
changing `cider-overlays-use-font-lock` has no effect. All the other config options work btw

**Comment by mallt** [comment]
@malchmih You should be able to fix the issue by removing the `:foreground` attribute of the  `cider-result-overlay-face` of the zenburn theme. This is what solved the issue for the solarized theme (https://github.com/bbatsov/solarized-emacs/pull/233/files).

**Comment by malchmih** [comment]
@mallt Thanks for your tip! Checked it and works perfectly. Will send a PR to a zenburn theme repo.

**Comment by malchmih** [comment]
Created the PR: https://github.com/bbatsov/zenburn-emacs/pull/252
