### ISSUE TITLE
Cannot select Zombie REPL buffer with cider-connect

### ISSUE THREAD

**Issue by mrrodriguez** [clojure-emacs/cider#1755]
## Expected behavior

I use cider-connect to connect to an already running nREPL server process.  Cider finds that I have Zombie REPL buffers via a message (1) like

```
Zombie REPL buffer exists (*cider-repl localhost:11111*, *cider-repl localhost:22222*). Reuse? (y or no)
```

I say "y".  Cider prompts with message (2)
```
Choose REPL buffer: 
```
 
I try to type the buffer name, it auto-completes and I can choose one of the two listed in the message (1) to reuse the zombie REPL buffer.

## Actual behavior

In message (2) the minibuffer does suggest any auto-completions as I try to type the buffer name.  I also can never find a match for Cider to open, even if I type out the whole name myself and hit <enter>.

## Steps to reproduce the problem

After selecing "y" to message (1) above to respond to message (2) 

I type:
```
*cider-repl
```

Since there is no auto-complete, I now need to hit <space> key.  However, I cannot hit <space>.  If I hit <space> it maps to <enter> I guess so I get a message in the prompt
```
[no match]
```

I can try to escape the <space> key with a C-q <space>, then complete the whole buffer name myself.
When I do this, I still get

```
[no match]
```

### CIDER version information

```
;; CIDER 0.12.0  nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_91
```

### Lein/Boot version

Lein 2.6.1

### Emacs version

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

### Operating system

OS X 10.11.4 "El Capitan"

**Comment by Malabarba** [comment]
Should be fixed now. Thanks for reporting!

**Comment by mrrodriguez** [comment]
Thanks for looking into it so fast!
