### ISSUE TITLE
cider-quit ignores global-font-lock-mode

### ISSUE THREAD

**Issue by atstp** [clojure-emacs/cider#1768]
## Expected behavior

`cider-quit` respects `global-font-lock-mode`

## Actual behavior

`cider-quit` highlights previously un-highlighted buffers

## Steps to reproduce the problem

start a cider connection (`cider-connect` or `cider-jack-in`)

 * <kbd>M-: (global-font-lock-mode 0) </kbd>
 * <kbd>M-x cider-quit </kbd>

clojure buffers become highlighted

## Environment & Version information

  * CIDER 0.12.0 (Seattle)
  * nREPL 0.2.12
  * Clojure 1.8.0
  * Java 1.8.0_91
  * Boot 2.4.2
  * Emacs 24.5.1
  * OS Ubuntu 14.04

I'm assuming this falls in pretty closely with #1456 and judging by that, I'm the only one who minds this stuff &mdash; no need to rush on my behalf, thanks!

**Comment by bbatsov** [comment]
So, you're basically saying that `cider-quit` applies some font-locking?

**Comment by atstp** [comment]
yeah, that's correct.  I'll update the description above with more specific terminology after I brush up on it.

For what it's worth, the last similar issue was closed with [this commit](https://github.com/clojure-emacs/cider/commit/bfd519d498e93c8a8b2c466e11f877939aa17131)

**Comment by Malabarba** [comment]
Should be fixed now. Let me know if it works.
