### ISSUE TITLE
Display Clojure.spec in the doc buffer 

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1769]
According to http://clojure.org/about/spec

> Functions specs defined via fdef will appear when you call doc on the fn name. You can call describe on specs to get descriptions as forms

We should probably ensure that cider doc buffers display the same information.

**Comment by bbatsov** [comment]
Yep, we should probably do this, although 1.9 is not going to be released for a while, so this is definitely not something particularly important right now.

**Comment by Malabarba** [comment]
Here's an example of what we'd like to display: http://clojure.github.io/java.jdbc/#clojure.java.jdbc/create-table-ddl

**Comment by cskksc** [comment]
I'd like to take this up. I'll submit a PR soon.

**Comment by bbatsov** [comment]
Great!

**Comment by expez** [comment]
You still interested in taking this on, @cskksc?

**Comment by cskksc** [comment]
Yep. But I have been traveling for the last couple of weeks. I'll finish this by Tuesday next week. Is that ok ?

**Comment by bbatsov** [comment]
Absolutely. It's not like Clojure 1.9 is even released yet... :-)

**Comment by bbatsov** [comment]
@cskksc Any updates here?

**Comment by cskksc** [comment]
I'm done with the nREPL changes. The elisp interface should be done soon. Got caught in some university work. Sorry, I forgot to post an update here.

**Comment by lvh** [comment]
I don't know if it's relevant, but `clojure.repl/doc` exposes this for you.

**Comment by cskksc** [comment]
@Ivh Yep. Even `clojure.spec` has fn's for this. The nREPL would return `(clojure.spec/describe (clojure.spec/get-spec namespace-qualified-var))` and we just have pretty-print this into the doc buffers.

**Comment by cskksc** [comment]
For the `ranged-rand` from the spec guide;

```
(require '[clojure.spec :as s])

(defn ranged-rand
  "Returns random int in range start <= rand < end."
  [start end]
  (+ start (long (rand (- end start)))))

(s/fdef ranged-rand
        :args (s/and (s/cat :start int? :end int?)
                     #(< (:start %) (:end %)))
        :ret int?
        :fn (s/and #(>= (:ret %) (-> % :args :start))
                   #(< (:ret %) (-> % :args :end))))
```

this is how our doc buffers would look.

<img width="715" alt="screen shot 2016-08-25 at 8 04 37 am" src="https://cloud.githubusercontent.com/assets/5201497/17968435/d347c46a-6a9a-11e6-809f-f9845f0c692d.png">

Does it look ok ? I just have to write tests and tidy up some code before submitting a PR.

**Comment by cskksc** [comment]
I mean it looks exactly same as the `clojure.repl/doc` fn displays it. Do we want to change/add anything ? I was thinking of adding something like "Spec is defined here: *hyperlink*". I'm not sure if the API provides metadata for this, but I'm gonna check that now.

**Comment by expez** [comment]
I think it makes more sense to add the location of the function at the bottom instead of between the docstring and the spec.  This is because I view the spec to be part of the documentation.  

This is obviously a minor thing, so don't spend any time on it if it's hard to change.

**Comment by cskksc** [comment]
@expez Done ;-)

<img width="723" alt="screen shot 2016-08-25 at 8 27 57 am" src="https://cloud.githubusercontent.com/assets/5201497/17968978/daad7288-6a9d-11e6-8e68-100dbedb6991.png">

**Comment by expez** [comment]
👍

**Comment by lvh** [comment]
Looks awesome to me :)

**Comment by Malabarba** [comment]
:+1:

**Comment by bbatsov** [comment]
Looks good indeed.
