### ISSUE TITLE
Improve our ClojureScript exceptions

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/cider#1771]
Spawned from a Slack conversation:

Currently our ClojureScript exceptions show up in red text on the REPL, which is just painful. It would be nice to have them displayed in a proper `*cider-error*` buffer like Clojure exceptions do.

IIUC what @bhauman explained on Slack these come in 3 different kinds
1. Javascript runtime exceptions, which should be pretty easy to fix.
2. Compiler exceptions, these are syntax and reader errors and often come with column and line information along with a brief explanation.
3. Compiler warnings. There can be multiple warnings per compile and these come with a description and location information as well.

I'm pretty sure that handling items **1** and **2** on the Emacs side will be simple. In fact, if the messages can mimick the Clojure exceptions we receive it might not even take any coding at all.
Item **3** is less important and can wait until later since it'll take more work to handle properly,

cc: @bbatsov

**Comment by bhauman** [comment]
And a note here, is that I'm willing to work on piggieback so that you get appropriate messages back for these different events.

**Comment by bbatsov** [comment]
@bhauman That would be great.
