### ISSUE TITLE
Jump to definition M-. error symbol function definition is void : cider-turn-on-eldoc-mode

### ISSUE THREAD

**Issue by chemouna** [clojure-emacs/cider#1781]
Jump to definition M-. is not working for me on any version 0.12.0.
I get this error:
```
symbol function definition is void : cider-turn-on-eldoc-mode
```
The repl, code completion and almost everything else is working, but not the jump to definition.
Is this expected, or should it be working?
Thanks.

**Comment by syohex** [comment]
`cider-turn-on-eldoc-mode` was obsoleted function and removed. You can use `eldoc-mode` instead of it.

**Comment by eallik** [comment]
...but how to fix the error?

**Comment by bbatsov** [comment]
Yeah, indeed. There's a section on this in the manual, btw. :-) See http://www.cider.mx/en/latest/configuration/#configuring-eldoc
