### ISSUE TITLE
Disable symbol documentation in minibuffer?

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider#1782]
I find display of the documentation in the minibuffer a non-feature. It's almost never useful, interferes with eldoc, and it constantly resizes/recenteres the display. How do I disable that? Thanks.

**Comment by cskksc** [comment]
@vspinu Are you referring to the docs which are displayed for `def`'d vars ? Right now that is tied together with `eldoc` for functions, so there's no way to disable it independently. You'll have to disable entire `eldoc` for this. Although it would be easy to add a `defcustom` to control this. @bbatsov @Malabarba ?

**Comment by bbatsov** [comment]
> I find display of the documentation in the minibuffer a non-feature. It's almost never useful, interferes with eldoc, and it constantly resizes/recenteres the display. How do I disable that? Thanks.

This is exactly how Elisp's eldoc works, although it shouldn't resize or recenter the display. Can you share some repro steps for this?

> Although it would be easy to add a defcustom to control this. @bbatsov @Malabarba ?

Obviously we can do this, but I don't want to add a config option for absolutely anything someone might have an issue with. If more people find this behaviour problematic then a defcustom would make more sense. Right now I'd rather focus on what exactly is problematic for @vspinu and try to address it.

**Comment by vspinu** [comment]
> Are you referring to the docs which are displayed for def'd vars ? 

Not only. I am seeing blinking doc for functions as well. For instance when I navigate to `(count ...)` I see a blinking full size docstring and immediately after the eldoc argument string. 

This blinking is not comming from eldoc. It shows as a message in the `*Messages*` buffer. Eldoc inhibits pollution of `*Messages*` buffer so it's either something else or eldoc breaks somewhere.  

> This is exactly how Elisp's eldoc works,

Not quite. Elisp eldoc never shows the full docstring, only the first line. This doesn't resize minibufer or recenter the display.  BTW, eldoc function should respect `eldoc-echo-area-use-multiline-p` which cider currently doesn't.

> Can you share some repro steps for this?

For example
```clojure
(def blabla 
  "Some doc.

  Another line.
  Another line"
  nil)
```

Go to last visible line in the script window and insert `(count blabla)`. When cursor is moved over `count` I see the doc of `count` for a fraction of a second and window is recentered. Same happens when you go over  `blabla`. First I see blabla doc for a fraction of a second, then `count` argumetns. The behavior is somewhat non-systematic, due to caching I guess.

The blinking of `blabla` doc happens even when `cider-eldoc-display-for-symbol-at-point` is set to nil.

In the repl the behavior is different. I don't see the blinking doc here but the behavior is still incorrect. Go to repl and center the buffer such that the last line is on the bottom (3 times `C-l`). Now type `blabla`. Nothing happens. Make it `(blabla)`. The eldoc shows the documentation of `blabla` and recenters the window.  I think this is the opposite of what should happen because `blabla` is not a function. Now, make it `(count blabla)`. Thing behave normally now. That is, if `cider-eldoc-display-for-symbol-at-point` is nil, no doc is displayed on `blabla`, only the arguments of `count`.

I am on master's head both for cider and cider-nrepl.

**Comment by bbatsov** [comment]
Show me a screenshot, as I'm having a hard-time figuring out what exactly are you seeing.

**Comment by vspinu** [comment]
Seems like it's my problem only. I will track it down myself.

This is what I see. It's a plain message (no eldoc color) with output to `*Message*` buffer

![eldoc](https://cloud.githubusercontent.com/assets/1363467/16044048/23e8c968-3243-11e6-8db3-7e611db62bd8.png)

**Comment by cskksc** [comment]
@vspinu This is a problem for everyone. https://github.com/clojure-emacs/cider/blob/master/cider-eldoc.el#L150 is what you're looking for, till we consider `eldoc-echo-area-use-multiline-p`.

**Comment by bbatsov** [comment]
The font faces always look off and there should definitely be nothing in `*Messages*`.

**Comment by cskksc** [comment]
@bbatsov I'm working on the multiline docstring. I'd not considered `eldoc-echo-area-use-multiline-p`.
However, on my setup, it doesn't post anything in `*Messages*` buffer. Does this behave like @vspinu for you too?

**Comment by Malabarba** [comment]
Hey there. Looks like it's an issue with the mouse-over functionality.

**Comment by cskksc** [comment]
@Malabarba You're saying, eldoc strings being printed in `*Messages*` could be related to mouse-over ? I'm not able to reproduce it.

**Comment by Malabarba** [comment]
I got interrupted while writing that message, so I couuldn't finish.

@vspinu The message you're seeing looks a lot like the message that gets displayed as a **tooltip** when the user mouses-over a symbol. Maybe you've configured your emacs to show tooltips in the echo area *and* show echo-messages according to cursor position (instead of mouse position)?
I'm not saying you're wrong to do that, I'm just trying to understand what's hapenning.

**Comment by vspinu** [comment]
> Maybe you've configured your emacs to show tooltips in the echo area and show echo-messages according to cursor position (instead of mouse position)?

Hmm.  Not what I am aware of. I have a couple of tooltip settings but all those are innocent AFAICT.  Also when I move my mouse over a symbol I do see a proper tool tip with the doc. So it's not that, but might be related. I am almost sure it's not eldoc as it happens before eldoc function enters. I will debug it in the night.

**Comment by vspinu** [comment]
@Malabarba hit the nail on the head. I tracked it down to `help-at-pt-display-when-idle` which I set to `t` some time ago to see messages that eclim puts on java error locations.  As cider now places `help-echo` property on the entire buffer I found myself bombarded with the help messages. 

I guess there is nothing cider can do about it as there is no way to distinguish between tooltip and other consumers of `help-echo`. So please consider this part fixed.

**Comment by Malabarba** [comment]
Given that the feature is super intrusive in that case, and given that it's a built-in emacs option, maybe we should disable the tooltip when that variable is the.

**Comment by bbatsov** [comment]
> Given that the feature is super intrusive in that case, and given that it's a built-in emacs option, maybe we should disable the tooltip when that variable is the.

Makes sense.

**Comment by bbatsov** [comment]
@cskksc Did we ever add a check for the current value of `help-at-pt-display-when-idle`?

**Comment by cskksc** [comment]
@bbastov I dint get a chance to work on anything in the last couple of days. Let's finish this too, before 0.13 ? This shouldn't take a lot of time. The other upgrade ticket would be done by Tuesday. I'll finish this off after that.

On 10-Jul-2016, at 12:48 PM, Bozhidar Batsov <notifications@github.com<mailto:notifications@github.com>> wrote:


@cskksc<https://github.com/cskksc> Did we ever add a check for the current value of help-at-pt-display-when-idle?

-

**Comment by bbatsov** [comment]
Sounds good.

**Comment by hotpxl** [comment]
@vspinu Hi. I ran into your comment while searching for something else. You mentioned ElDoc inhibits polluting `*Messages*` buffer even if using `message` function. How does it achieve this? I don't have a clue reading the source code. Thanks
