### ISSUE TITLE
Make `cider-eval-map` and bind it to `C-c C-e` instead of `C-c C-v`

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider#1783]
Two related issues. 

First, would be good to place `C-c C-v` [eval commands](https://github.com/vspinu/cider/blob/master/cider-mode.el#L290-L293) into a specialized map. 

Secondly, have you considered using `C-c C-e` for that map? `cider-eval-last-sexp` is already bound on `C-x C-e`, so using `C-c C-e` seems like a waste of a good key. `C-c C-v` is very handy and could be dedicated to something more useful than redundant eval commands.

**Comment by Malabarba** [comment]
> First, would be good to place C-c C-v eval commands into a specialized map.

You mean actually write a separate keymap for eval commands? We could do that, there's no harm in it, but there isn't much benefit either.

However, I don't see a reason to bind it to some other key. I know a lot of people use C-c C-e, so I'd rather keep the redundancy in this case.

**Comment by vspinu** [comment]
> but there isn't much benefit either.

The benefit is that people can move the whole map around to their favorite key. C-c C-v is too good to be wasted for those rarely used keys.

>  I know a lot of people use C-c C-e,

It might be too late to change it indeed. My personal opinion is that enforcing a consistent C-x C-e across emacs modes is worth the pain of breaking the backward compatibility.

**Comment by bbatsov** [comment]
I'd say it's too late for `C-c C-e`, but eventually we might have all eval commands under `C-c C-v` for convenience's sake.

**Comment by Malabarba** [comment]
> > but there isn't much benefit either.
> The benefit is that people can move the whole map around to their favorite key. 

PRs welcome. :-)

**Comment by bbatsov** [comment]
Like @Malabarba said. :-)

**Comment by bbatsov** [comment]
Fixed in #1805. What remains to be done is to stuff all other eval commands there as well for consistency.
