### ISSUE TITLE
(void-variable cider-mode)

### ISSUE THREAD

**Issue by mambolevis** [clojure-emacs/cider#1784]
Considering the following configuration: 
```
(use-package cider
  :ensure t
  :defer t   
  :config
  (add-hook 'cider-mode-hook 'eldoc-mode)
  (add-hook 'cider-repl-mode-hook #'paredit-mode))
```
An error message appears when trying to open a clojure project
```
ebugger entered--Lisp error: (void-variable cider-mode)
  (not cider-mode)
  redisplay_internal\ \(C\ function\)()
```

## Expected behavior
The idea is to defer cider, as default, and only activate it when necessary. I also want to  reduce emacs start up proces.
## Steps to reproduce the problem

- Add `:defer t` to the configuration used by Bozhidar Batsov in his emacs config
- Open a project.clj file and the error message appears.

## Environment & Version information
- Windows 10
- GNU Emacs 25.1.50.1
- CIDER 0.13.0snapshot (package: 20160606.1209)

**Comment by mambolevis** [comment]
To solve the problem, I added the following :init configuration:
```
  :init
  (with-eval-after-load 'clojure-mode
    (add-hook 'clojure-mode-hook 'cider-mode))
```
So, my final working configuration is:
```
(use-package cider
  :ensure t
  :defer t   
  :init
  (with-eval-after-load 'clojure-mode
    (add-hook 'clojure-mode-hook 'cider-mode))
  :config
  (add-hook 'cider-mode-hook 'eldoc-mode)
  (add-hook 'cider-repl-mode-hook #'paredit-mode))

```
Even it is working now, I would like to see your opinion/advice.

**Comment by Malabarba** [comment]
> To solve the problem, I added the following :init configuration:
> ```
>   (with-eval-after-load 'clojure-mode
>     (add-hook 'clojure-mode-hook 'cider-mode))
> ```

You don't need that `with-eval-after-load`. Hooks work even before they're defined, so you can just use this:

    (add-hook 'clojure-mode-hook 'cider-mode)

Indeed, that's the correct way to hook-up Cider, but I'm a little worried about the error you were getting. I don't think that was supposed to happen. Can anyone else reproduce it by following the same config?

**Comment by bbatsov** [comment]
Isn't `defer` deprecated now? I recall something like this. I definitely don't use it in my own config.

**Comment by mambolevis** [comment]
I checked use-package (GitHub) documentation, but  I couldn't find information about `:defer` deprecation. Is there any place (or website) where emacs deprecated `symbols/function/vars `are listed?

**Comment by bbatsov** [comment]
Guess I was recalling https://github.com/jwiegley/use-package#notes-about-lazy-loading
