### ISSUE TITLE
Load (C-c C-k) and load-defun is not consistently working properly.

### ISSUE THREAD

**Issue by EricGebhart** [clojure-emacs/cider#1786]
## Load  / Reload of code should not cause existing code to start crashing.

This is really strange, It is so fundamental I cannot see how it could be possibly broken.

## Running a cascalog query after deleting/adding a blank line or function 
and then reloading the code causes the code to crash. It is seemingly only a cascalog
problem in that it only fails when there is a filterfn or logic-ops function involved.

There is function which is a clojure/cascalog hybrid `(filter-test foo-catv)` is the equivalent
of the full clojure `(cats foo-catv)`.  It works fine when the full cascalog version fails.

However, I have seen where I had an error in a function, repaired that function, loaded
only that function and continued to get the same error that I repaired until doing a full
code reload. 

The nrepl-messages files show a failure, and subsequent success.  The second file
goes further in that I broke it again by adding a function (defn s [x] x) and loading
just the defun.  That resulted in a crash again. 

There are 4 versions of nrepl-messages.txt.

The third is the complete session with a transcript at the top.
it starts with a failure, then success, then failure after
loading a defun, failures after subsequent loads and eventually
success when after loading a defun and doing a file load immediately
after.  The 4th file is just the same weirdness with a regular clojure function and arity error.

Reloading the code again will frequently cause the code to work again as expected.
Sometimes it takes multiple reloads before this happens. Sometimes It seems to take
a reload of a function followed by a full reload to recover.  Thats what I do once multiple
full reloads fail. It seems to work consistently.

Deleting or adding a blank line and reloading can also cause the code
to begin giving a stacktrace.

## Reproducing the problem.

I'm really doubting that anyone will be able to reproduce this.  But I have a repo that fails 
for me.  See the readme.

https://github.com/EricGebhart/cascalog-check

I did capture a failing session, and documented it. I have created a repository here with 
instructions, nrepl-messages.txt of a failed session etc.,
my .lein/profile.clj is also there. 

This behavior seems fishy to me. It wouldn't surprise me if this was not reproducable
for anyone else. If there is something else I can do to trace what is happening I would be happy to
do so.  I have not dug any deeper than to look at the **nrepl-messages** or to 
`toggle-debug-on-error` which no longer catches anything.

That this problem behaves the same for cider 10, 12 and 13
is odd, but that it works ok in lein repl is also odd. I've updated everything in emacs
to match cider 12/13.  I saw a lot of instability in emacs in that process, but the problem
never changed, and now emacs is behaving flawlessly.

The differences in the **nrepl-messages** between the working load and the non-working 
load are interesting but I don't know enough about what I'm looking at there.

I did have some signature errors from eastwood and squiggly clojure on
occasion, but I have fixed all of the errors that I have seen, whether it is in code 
(warnings in nrepl-messages from eastwood or kibit) or actual emacs errors caused 
by mismatched emacs packages. 

### CIDER version
I started last week with cider 10. I upgraded everything to cider 12,
and today switched to cider 13 to see if it was better. The only difference
between the cider 12 and 13 environment is the cider package.
I let cider do the injections as I generally use ```cider-jack-in```

```
    ;; CIDER 0.13.0snapshot (package: 20160612.1230), nREPL 0.2.12
    ;; Clojure 1.7.0, Java 1.8.0_73
```

```
    Cascalog 3.0    -  I have not tried this with cascalog 2.0 yet.
```

### Lein/Boot version

```Leiningen 2.6.1 on Java 1.8.0_73 Java HotSpot(TM) 64-Bit Server VM```

I generally let cider start the repl.

### Emacs version

24.4.1

### Operating system

OS X 10.11 "El Capitan",

**Comment by EricGebhart** [comment]
I've upgraded java.  

    ;; CIDER 0.13.0snapshot (package: 20160612.1230), nREPL 0.2.12
    ;; Clojure 1.7.0, Java 1.8.0_91

The first run was marginally better.  But still failed after adding a function and loading it.  Loading all the code also failed.  Loading the function, then loading the code got it to work again.
I've tested this over and over.  Adding a function and loading the file does not work.  Only loading the function then loading the file will cause the code to work.   This is running  `(codes 3)`.

I have also discovered this has nothing to do with cascalog.  An function with a fix will persist as broken until the code actually manages to get loaded.

    cascalog-check.core> (codes 3)
    (["foo" 1 3] ["foo" 2 100] ["bar" 1 5] ["bar" 2 22] ["baz" 1 3] ["baz" 2 100])
   
    ;; Added (defn s [x] x); (C-c C-c) 
    cascalog-check.core> (codes 3)
    FlowException local step failed  cascading.flow.planner.FlowStepJob.blockOnJob     i   (FlowStepJob.java:219)
   
    ;; Reloaded file (C-c C-k)
    cascalog-check.core> (codes 3)
    FlowException local step failed  cascading.flow.planner.FlowStepJob.blockOnJob (FlowStepJob.java:219)
    
    ;; reloaded a function, any will do, reloaded the file. (C-c C-c) (C-c C-k)
    cascalog-check.core> (codes 3)
    (["foo" 1 3] ["foo" 2 100] ["bar" 1 5] ["bar" 2 22] ["baz" 1 3] ["baz" 2 100])
    
    ;; Added another function.  (C-c C-c) (C-c C-k)
    cascalog-check.core> (codes 3)
    (["foo" 1 3] ["foo" 2 100] ["bar" 1 5] ["bar" 2 22] ["baz" 1 3] ["baz" 2 100])
   ```

**Comment by EricGebhart** [comment]
I upgraded emacs, and moved my .emacs.d out of the way.  All packages are fresh.

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

The problems persist.  I've established that the problem cannot be reproduced with a friend's setup using cider 9-snapshot and an old version of my emacs setup.

Trying a vanilla emacs setup next.

**Comment by EricGebhart** [comment]
I now have a very minimalist .emacs file which shows the problem.  The only packages it loads are
`cider, clojure-mode, flycheck-clojure and flycheck-pos-tip.`

It is somehow related to `flycheck-clojure`.  Disabling `flycheck-clojure` causes the problem to go away.

However it seems somehow related to whether the file is currently saved or not. 

If I add a new function `(defn a [x] x)`, save the file and load-file `C-c C-k`. There is no problem.  If I load-file and get a cider-prompt to save, that does not work.  If I load-file twice in a row, where the first one prompts for save, then that does work.  

It does not seem to matter if I eval the new function or not. Simply adding the function without any load of any kind and then going back to the repl and repeating the last eval will cause a crash.
Returning back to the code, saving and reloading will cause it to work the next time.
Returning back to the code, and reloading twice will also cause it to work the next time.

I have updated the readme with more information about the lint checkers. They are all running without errors.

**Comment by bbatsov** [comment]
If it's related to `flycheck-clojure` this should be reported there I guess. I don't use it and I'm not familiar with it.

**Comment by EricGebhart** [comment]
It is Eastwood.  It corrupts the jvm session in the process of linting.  It is a bad interaction with Cascalog code.  Eastwood makes no guarantees that this won't happen when it is used in this way.  Eastwood might be fixed for this problem at some point, but it is still possible that other problems will remain due to the way Eastwood works.

A solution might be to have clojure flycheck use a separate jvm instance from the session instance.
