### ISSUE TITLE
cider-format-buffer does not honor indent spec

### ISSUE THREAD

**Issue by raszi** [clojure-emacs/cider#1787]
## Expected behavior

`cider-format-buffer` should indent macros as they are defined with [`{:style/indent 2}` specification](http://cider.readthedocs.io/en/latest/indent_spec/).

The correct formatting, if I indent with `indent-region`:

```clojure
(defsomething x []
    (println "x"))
```

## Actual behavior

It is formatting the standard way if I format that with `cider-format-buffer`:

```clojure
(defsomething x []
  (println "x"))
```

## Steps to reproduce the problem

Create a macro and define a custom indentation, like:

```clojure
(defmacro defsomething
  "Doc string"
  {:style/indent 4}
  [name args & body]
  `(do
     (println name)))
```

Then use the macro and format the code with `cider-format-buffer`.

### CIDER version information

```
;; CIDER 0.13.0snapshot (package: 20160612.1230), nREPL 0.2.12
```

### Boot version

`2.5.5`

### clojure-mode version information

```
clojure-mode (version 5.5.0-snapshot)
```

### Emacs version

```
GNU Emacs 24.5.1 (x86_64-apple-darwin15.4.0, Carbon Version 157 AppKit 1404.46) of 2016-05-02 on istkarm2.corp.w3data.com
```

### Operating system

`OS X El Capitan - Version 10.11.5`

**Comment by bbatsov** [comment]
That's a problem with cljfmt - https://github.com/weavejester/cljfmt/issues/49

Someone has to add support for the metadata to it.
