### ISSUE TITLE
core.typed: Attempting to call unbound fn: #'clojure.core.typed.contract-utils/boolean?

### ISSUE THREAD

**Issue by muhuk** [clojure-emacs/cider#1790]
When I do `M-.` and confirm (`Enter`) that want to go to the var cursor is on...

## Expected behavior

...it should jump to the definition of that var.

## Actual behavior

It displays:

    core.typed: Attempting to call unbound fn: #'clojure.core.typed.contract-utils/boolean?

In the info bar and does not go to the definition.

### CIDER version information

```
;; CIDER 0.13.0snapshot (package: 20160510.2138), nREPL 0.2.12
;; Clojure 1.9.0-alpha7, Java 1.8.0_91
```

### Lein/Boot version

Leiningen 2.6.1 on Java 1.8.0_91 OpenJDK 64-Bit Server VM

### Emacs version

GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-08 on binet, modified by Debian

### Operating system

Debian Stretch

**Comment by bbatsov** [comment]
Some steps to reproduce this would be useful.

**Comment by muhuk** [comment]
I couldn't reproduce it myself. Closing.

(didn't work at first, until I fixed `(add-hook 'cider-mode-hook 'cider-turn-on-eldoc-mode)` thing)
