### ISSUE TITLE
Symbol's value as variable is void: u}«

### ISSUE THREAD

**Issue by brandoncc** [clojure-emacs/cider#1792]
When I attempt to install cider, I am given the following error:

````
cider-client.el:28:1:Error: Symbol's value as variable is void: u}«
```

Then:

```
Done (Total of 7 files compiled, 19 failed, 2 skipped)
```

[Here](https://gist.github.com/brandoncc/e5488c326be1101c2e85df10aff453a8) is a gist of my errors.

**Comment by Malabarba** [comment]
It looks like you're not installing cider through the package menu. Is that the case?

**Comment by brandoncc** [comment]
I actually use spacemacs which has a layer for clojure which installs cider. I tried installing cider using `package-install` as well, without the spacemacs layer. I'm not sure if `package-install` is the menu you are talking about about.

**Comment by Malabarba** [comment]
The menu I'm talking about is what you get from `list-packages`, but it's more-or-less equivalent to `package-install`. Maybe you can ask around at spacemacs too. That error you reported is being signaled at every file, and it doesn't look like cider could be causing it. 

You could also try a clean install, or try removing all of your customizations temporarily.

**Comment by brandoncc** [comment]
Okay. I agree that it seems weird that it is signaled everywhere, but I haven't experienced it with any other package. I did ask in the spacemacs gitter room with no response. I will try removing all of my customizations temporarily and see if I can nail down the cause. If I do, I will update this issue. Thanks @Malabarba !

**Comment by brandoncc** [comment]
Well, I deleted my packages and let them reinstall and I got that problem fixed, only to have a new one:

```
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: jsr166y.ForkJoinPool, 
```

https://gist.github.com/brandoncc/f1fa6debeead3ff9daa03867ff26e39a

I'll open an issue for that one unless I can find one already open.
