### ISSUE TITLE
java.lang.ClassNotFoundException: jsr166y.ForkJoinPool

### ISSUE THREAD

**Issue by brandoncc** [clojure-emacs/cider#1793]
## Expected behavior

I would like the repl to run when I run `cider-jack-in`.

## Actual behavior

I get an error which you can see [here](https://gist.github.com/brandoncc/f1fa6debeead3ff9daa03867ff26e39a).

## Steps to reproduce the problem

I'm not sure, I have a fresh install of emacs (spacemacs) and cider.

### CIDER version information

```
;; CIDER 0.13.0snapshot (package: 20160623.12)
```

### Lein/Boot version

Lein 2.6.1

### Emacs version

GNU Emacs 24.5.1 (x86_64-apple-darwin15.4.0, Carbon Version 157 AppKit 1404.46) of 2016-04-13

### Operating system

OSX 10.11.5

**Comment by bbatsov** [comment]
Looks like some dependency issue. What happens if you execute the lein command triggered by `cider-jack-in` manually in a terminal?

**Comment by brandoncc** [comment]
I get the same message. Is there a dependency that needs to be in my profiles.clj or project.clj? I have tried the following `profiles.clj` configurations:

from https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/clojure#quick-start-with-lein :

```clojure
{:repl {:plugins [[cider/cider-nrepl "0.10.0-SNAPSHOT"]
                  [refactor-nrepl "2.0.0-SNAPSHOT"]]
        :dependencies [[alembic "0.3.2"]
                       [org.clojure/tools.nrepl "0.2.12"]]}}
```

from https://github.com/clojure-emacs/refactor-nrepl/issues/141 :

```clojure
{:user {:plugins [[cider/cider-nrepl "0.11.0-SNAPSHOT"]
                  [refactor-nrepl "2.0.0-SNAPSHOT"]                  
                  [quickie "0.3.6"]
                  [lein-pprint "1.1.2"]
                  [lein-try "0.4.3"]
                  [lein-figwheel "0.5.0-6"]
                  [com.jakemccrary/lein-test-refresh "0.10.0"]
                  [jonase/eastwood "0.2.1"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.12"]
                       [org.clojure/tools.namespace "0.2.11"]]}}
```

**Comment by brandoncc** [comment]
@bbatsov Do you have any idea what the fix might be? I'm brand new to clojure, cider, etc. I haven't even been able to write any code yet because of this. There could easily be something I am missing that I don't know I needed to do in an initial setup of my machine.

**Comment by gtrak** [comment]
jsr166y is the old package for forkjoin, if you are on java 1.7+, you
should be able to use java.util.concurrent.ForkJoinPool instead.  Either
upgrade your java version if it's older than 1.7, or add the backport
library: http://g.oswego.edu/dl/concurrency-interest/

I'm guessing this is the maven artifact:
http://search.maven.org/#artifactdetails%7Corg.coconut.forkjoin%7Cjsr166y%7C281207%7Cjar

**Comment by brandoncc** [comment]
Thank you @gtrak!!!!!!!!!!! The problem was that I had originally installed java from oracle, but it wasn't recognized in my terminal so I installed it from Apple. That installed the older version. I removed that and reinstalled from Oracle, then rebooted. Terminal recognizes it and all is well now. I cannot thank you enough!
