### ISSUE TITLE
Unable to connect to a cljs repl

### ISSUE THREAD

**Issue by vandr0iy** [clojure-emacs/cider#1797]
Hi! I'm trying to write an application using cljs on frontend and clj on backend. My greatest issue so far is: I'm unable to connect to the repl of any of the cljs files.
## Expected behavior
emacs jacking in the cljs file correctly 
## Actual behavior
repl pops up, but c-c c-k warns me:
```user-error: `cider-load-buffer' needs a ClojureScript REPL.
If you don't know what that means, you probably need to jack-in (`C-c M-J').```
## Steps to reproduce the problem
lein new chestnut -- --reagent newproject
open the base cljs in emacs - it will be wrong about detecting it by setting clojure as primary mode, so you do m-x clojurescript-mode
then - m-x cider-jack-in-clojurescript

I believe that this is the same issue from https://github.com/clojure-emacs/cider/issues/1509

### CIDER version information
attaching everything in the image 

*Including here the version string displayed when
CIDER's REPL is launched.*

;; Connected to nREPL server - nrepl://localhost:38673
;; CIDER 0.13.0snapshot (package: 20160629.946), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_92
![arst](https://cloud.githubusercontent.com/assets/5510334/16543305/b937ae56-40cd-11e6-9c48-db0e2c9ad9b4.png)

### Emacs version

GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-05-23 on ***

### Operating system
`uname -a`
```Linux *** 4.6.3-gentoo #1 SMP Tue Jun 28 10:20:19 CEST 2016 x86_64 Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz GenuineIntel GNU/Linux```

**Comment by bbatsov** [comment]
> open the base cljs in emacs - it will be wrong about detecting it by setting clojure as primary mode, so you do m-x clojurescript-mode

I don't understand this. A bit more details would be helpful.

P.S. Did you read this http://cider.readthedocs.io/en/latest/up_and_running/#clojurescript-usage ?
