### ISSUE TITLE
Eval-top-level-sexp not working

### ISSUE THREAD

**Issue by joansc** [clojure-emacs/cider#1802]
Hey guys, Im having problems with eval-top-level-sexp
## Expected behavior

When eval-top-level-sexp called, it should evaluate all the 'block'

## Actual behavior

When I call it, I just get this message: 

command-execute: Symbol's function definition is void: cider--eval-defun-at-point

and nothing else happens. However, the eval-last-sexp function works...

## Steps to reproduce the problem

I just use the key binding or from the menu bar to call eval-top-level-sexp

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### CIDER version information

Cider 0.12.0

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

CIDER 0.12.0 (Seattle), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.7.0_79

### Emacs version

24.5.1

### Operating system

OS X El capitan 10.11.3

**Comment by Malabarba** [comment]
> When eval-top-level-sexp called, it should evaluate all the 'block'

`eval-top-level-sexp` is not a Cider command, so it's a little hard to help there. :-)

> command-execute: Symbol's function definition is void: cider--eval-defun-at-point

Indeed, `cider--eval-defun-at-point` is not defined. It's also not referenced anywhere in the codebase, so I'm not sure what you're doing. :-)
If that's some code you wrote yourself, then you probably meant to call `cider-eval-defun-at-point` instead.

**Comment by joansc** [comment]
Hey Malabarba! First of all thanks for answering :)
Yeah what I meant with eval-top-level-sexp is the option it appears on the CIDER menu (C-M-x), so I guess that in that case it should be from cider...
Anyway, I have tried to remap (init.el) with another keybinding doing:

(setq mac-command-modifier 'super)
(global-set-key (kbd "s-d") 'cider-eval-defun-at-point)

and it displays the same message when I use the keybinding...

But its weird that in the message displayed there appear two dashes between cider and eval, isnt it? Maybe its not well defined wherever it is defined or something...
Any idea? :)
Thanks,
J.

**Comment by bbatsov** [comment]
> Yeah what I meant with eval-top-level-sexp is the option it appears on the CIDER menu (C-M-x), so I guess that in that case it should be from cider...

This is an Emacs Lisp command. Can you show me where exactly do you see it?

**Comment by joansc** [comment]
Yes, I attach here two images one with this option and the other one what it shows when I click on Eval-top-level-sexp.
Appreciate your responses man!
<img width="513" alt="screen shot 2016-07-14 at 10 49 43" src="https://cloud.githubusercontent.com/assets/17720862/16835500/dfd37432-49b0-11e6-87ef-70326d7a1ca3.png">
<img width="303" alt="screen shot 2016-07-14 at 10 49 24" src="https://cloud.githubusercontent.com/assets/17720862/16835501/dfd4b658-49b0-11e6-84a2-ef552a71bde6.png">

**Comment by Malabarba** [comment]
`cider--region-for-defun-at-point` is also not referenced anywhere in the codebase. :-/
This sounds like a bad installation. Or maybe you have an old version of cider lying around somewhere that's shadowing some of the functions.

Try deleting cider, restarting Emacs, and installing cider again.

**Comment by joansc** [comment]
Ok I will do that! How I can delete cider btw? :/

**Comment by Malabarba** [comment]
Did you install from the packages menu?

**Comment by joansc** [comment]
Can't remember now... but when I search for installing it from emacs it doesnt appear

**Comment by Malabarba** [comment]
1. `M-x list-packages`
2. Somewhere near the bottom you should see something like `cider       installed`.
3. Click on it and it will open a description page.
4. Click on `Delete`.

**Comment by joansc** [comment]
It doesnt even appear on the list... But I can do do nearly everything with cider. Understand nothing :/

**Comment by bbatsov** [comment]
Use `M-x find-library RET cider RET` and tell us what's the folder in which the file `cider.el` is located for you.

**Comment by joansc** [comment]
Here we go(photo)
<img width="628" alt="screen shot 2016-07-15 at 13 33 47" src="https://cloud.githubusercontent.com/assets/17720862/16874365/d6356b52-4a90-11e6-9a57-7c70707df413.png">

**Comment by bbatsov** [comment]
Seems you're using some Emacs starter pack. I guess you might have to reinstall it.

**Comment by bbatsov** [comment]
I'll close this as it's not really a bug in CIDER. Btw, if you're into starter kits you might check Prelude https://github.com/bbatsov/prelude
