### ISSUE TITLE
Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.

### ISSUE THREAD

**Issue by Ninlives** [clojure-emacs/cider#1803]
This is **NOT** a bug, I just want to know why cider-jack-in behave like this.

## Expected behavior
Start the nRepl directly.
## Actual behavior
Well, I have Clojure 1.8.0 installed on my machine. When I first call `cider-jack-in` it started to retrive Clojure 1.2.0. After that, every time I call `cider-jack-in` these messages 
`Warning: refactor-nrepl requires org.clojure/clojure 1.7.0 or greater.
Warning: refactor-nrepl middleware won't be activated due to missing dependencies.`
show in the `nrepl-server` buffer, and it takes around 1 minute to start the repl and establish the connection. I'm new to clojure so I'm not sure what cause the delay, but start a repl in commandline window takes only about 7 seconds.

## Steps to reproduce the problem
Just call `cider-jack-in`

### CIDER version information

```
;; CIDER 0.13.0snapshot (package: 20160711.31), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_73
```

### Lein/Boot version

Lein 2.6.1

### Emacs version

24.5

### Operating system

Windows 10

**Comment by expez** [comment]
It looks for clojure in the lein profile and if the version doesn't match this warning is displayed.  If you're just calling `lein repl` and don't have a project you can safely ignore this message.

Closing this as it doesn't have anything to do with cider.
