### ISSUE TITLE
Evaluate let bindings in the Repl

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#1809]
Dear `cider` team, 

today I woke up seeing an incredibly useful feature, which I use daily but never had the idea that it could actually be automated (don't know why). The thing is that it has been implemented in one of our competitors: https://github.com/jasongilman/proto-repl/raw/master/images/saved_values_table_expanded.png

And...I know that Bozhidar does not tolerate competition...so I was wondering if we can we can include this in cider.

The use case is simple, you have a `let` form with bindings (same applies for `doseq`, ... etc..) and you want to inspect in the repl their interaction with each other, given some data. I would like to basically wrap the bindings in a def, one by one, so that with one key binding I can send and evaluate in the repl:

```
;; Buffer
(let [a [1 2 3 4]
       b (conj 5 a)]
  ....)

;; Repl

...new cider function on the first line of the let...
(def a [1 2 3 4])

...after some playing with a...new cider function on the second line of the let...
(def b (conj 5 a))

...continue playing...
```

I hope it is clear what the function will do, `proto-repl` uses a def button, but we can either evaluate or send to repl the result or send the `def` to the repl...in any case the symbols in the right-hand side of the `let` will be bound to their value in the repl, one by one.

Also, would you implement this here or in `clojure-mode`? My emacs Lisp skills are weak by maybe with the help of `dash` I could actually hack something together. 

Thanks for listening!

**Comment by Malabarba** [comment]
I'm not sure I understand the feature, perhaps a video of it in action might clear things up.
The way you've explained it, it kind of sounds like stepping through the let bindings with the debugger.

**Comment by arichiardi** [comment]
So when I step through in the debugger, can I change the value of the `let` binding? Basically my point is that I would like to play with the value of a let, rebinding the symbol if necessary from the repl, so that I can inject stuff in the intermediate step for debugging purposes. If it is already there, even better, less work :dancer:

**Comment by Malabarba** [comment]
Yes, you can inject different values (I think it's bound to `j` nowadays).

**Comment by bbatsov** [comment]
I think this wraps this ticket, so I'll close it.
