### ISSUE TITLE
How to setup Leiningen and Emacs CIDER for ClojureScript code completing and interactive with browser?

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#1810]
I checked out some related issues in this CIDER issues repo, and followed those steps trying to setup ClojureScript code completing and interactiving with browser with Figwheel etc.
But none of them works.

Can somebody tell me how to do this? And maybe add this setup tutorial to README?

**Comment by bbatsov** [comment]
See http://cider.readthedocs.io/en/latest/up_and_running/#clojurescript-usage

If something in those instructions doesn't work I'd suggest filing more specific issues, as the current one is extremely vague.
