### ISSUE TITLE
Canonicalizing namespace alias

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/cider#1815]
Is there a way to canonicalize a namespace alias (e.g. `async` in `(require '[clojure.core.async :as async])'` without a symbol?

`(cider-var-info "async/chan")` will return an nREPL dict that contains the canonical namespace as an entry. However, I cannot seem to find a way to resolve the namespace without a symbol.

**Comment by Malabarba** [comment]
I don't understand the question. What do you mean by without a symbol? Could you exemplify what you're trying to do?

**Comment by xiongtx** [comment]
I mean without a var. Just the namespace itself.
