### ISSUE TITLE
Tooltips Conflict With Mouse Selection After cider-jack-in 

### ISSUE THREAD

**Issue by ska2342** [clojure-emacs/cider#1817]
_Use the template below when reporting bugs. Please, make sure that
you're running the latest stable CIDER and that the problem you're reporting
hasn't been reported (and potentially fixed) already._
As discussed on Slack, here is my report for the problematic behavior.
## Expected behavior

Mouse selection in Emacs just works. :-)
## Actual behavior

When I open a clojure buffer, everything works fine. I can also M-x cider-mode and all is well.  But after jacking into a project I can not select text reliably with the mouse anymore.
Doubleclicking works, but dragging only works when start and end are either at eol or bol
## Environment & Version information

emacs-version "24.5.1"
cider version 0.13-SNAPSHOT (just realize, this is pretty old)
at commit ce55e3648baf64db63f7113c4fc6c5ef349cf84c,  Thu Jun 30 09:31:49 2016 +0300
### Operating system

Xenial

**Comment by Malabarba** [comment]
I haven't had that problem, but for now one workaround is to just disable the tooltips.

**Comment by bbatsov** [comment]
@Malabarba tried to reproduce this and noticed I'm not getting any tooltips on the current master with Emacs 25. Can you check if they still work for you?

**Comment by Malabarba** [comment]
I'll try it out tonight. :+1:

**Comment by ska2342** [comment]
Can't reproduce anymore on Cider 0.18.0 and Emacs 25.5.2. But then again, I can't get Cider to show any tooltips at all, even if I set `cider-use-tooltips` to `t`. So, not sure if me not being able to reproduce means that this was really solved.

**Comment by Malabarba** [comment]
Hold-off stalebot
