### ISSUE TITLE
paredit problems

### ISSUE THREAD

**Issue by recursor94** [clojure-emacs/cider#182]
I'm having a little bit of paredit trouble in nrepl 0.1.5.  In my .emacs I have this line

`(add-hook 'nrepl-mode-hook 'paredit-mode)`

and paredit, in general works correctly in the REPL buffer.  paredit-open-curly and paredit-close-curly do not work, however, when I type the actual '{' and '}' keys.  It simply never forms a matching pair.

The second issue is that it can be hard to use paredit in the nrepl buffer when trying to format multiline commands into the buffer without them registering as entered commands.

For example this:

```
(lazy-seq
   (cons term-3
      (next-terms term-2 term-3)))))
```

Is difficult to format correctly in the REPL because paredit-close-round will automatically close the first line before creating a newline, RET will enter the code, and C-j will not indent the code in the newline.

Thank you for considering this issue,
--recursor

**Comment by malcolmsparks** [comment]
I'm finding that this line is causing me problems

https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L238

because my paredit version is not defined - perhaps because:

```
paredit            20150217.713  installed             minor mode for editing parentheses
```

Removing that guard from `clojure-paredit-setup` fixes my problem

**Comment by bbatsov** [comment]
`paredit-version` is defined in `paredit.el` (at the very beginning). Using melpa will not affect it.
