### ISSUE TITLE
Syntax highlighting for #_ forms comments out next form

### ISSUE THREAD

**Issue by danielcompton** [clojure-emacs/cider#1822]
When using the `#_` reader macro, you can chain several together. This lets you comment out more than one form at a time. However the Cider syntax highlighting uses the first `#_` to comment out the second one. For example:

<img width="220" alt="screenshot of emacs 12-08-16 8-05-56 am" src="https://cloud.githubusercontent.com/assets/811954/17603138/ece6f40e-6063-11e6-84d3-7fd03e3e6058.png">

In Cursive:

<img width="172" alt="screenshot of intellij idea 12-08-16 8-08-51 am" src="https://cloud.githubusercontent.com/assets/811954/17603155/036b2d9e-6064-11e6-8ba7-2adff68ee7bc.png">

**Comment by Malabarba** [comment]
I agree it's an issue, but it's (unfortunately) unlikely to be fixed any time soon. (Unless you want to submit a PR :smile: )

**Comment by bbatsov** [comment]
Btw, that's actually a bug in `clojure-mode`.

**Comment by danielcompton** [comment]
Sorry! Moved over there.
