### ISSUE TITLE
Column index of metadata is different when evaluating by cider-load-buffer and cider-eval-last-sexp

### ISSUE THREAD

**Issue by snufkon** [clojure-emacs/cider#1823]
When I run this code with `cider-load-buffer`

```clj
(ns hoge.core)

(def foo "hello world")
(println (meta #'foo))
```

the output is following (column index is **1**)

```
{:line 3, :column 1, :file core.clj, :name foo, :ns #namespace[hoge.core]}
```

when I run the code with `cider-eval-last-sexp`, the output is following (column index is **0**)

```
{:line 3, :column 0, :file core.clj, :name foo, :ns #namespace[hoge.core]}
```

Also when I run the code on `lein repl`, the output is following (column index is **1**)

```
user=> (require 'hoge.core)
{:line 3, :column 1, :file hoge/core.clj, :name foo, :ns #namespace[hoge.core]}
```

## Environment & Version information

- cider: CIDER 0.13.0 (California)
- lein: Leiningen 2.6.1 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM
- emacs: GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2015-04-08 on Atago.local
- OS: OS: OS X Yosemite (10.10.4)

**Comment by dpsutton** [comment]
I cannot reproduce this. I ran every cider-eval command, and all agreed column is 1.

**Comment by bbatsov** [comment]
I can reproduce this on Clojure 1.7. @dpsutton @snufkon what are your Clojure versions?

**Comment by bbatsov** [comment]
Hmm, I get the same results on 1.7 and 1.8 actually.
