### ISSUE TITLE
unicode apostrophes in help banner

### ISSUE THREAD

**Issue by johnv02139** [clojure-emacs/cider#1831]
## Expected behavior

Words will appear as words, with no funny numbers in them.  :)

## Actual behavior

The apostrophes in the help banner show up as u\2019

## Steps to reproduce the problem

Admittedly I have an unusual setup.  I'm running emacs (24.5.1) on OS X inside of a Putty on a Windows box.

Perhaps emitting a -*- line at the top would work.  Or we could simply replace the Unicode apostrophes with ASCII.  Or, if everyone else is happy with it, you can just close this.  But it doesn't give a nice first impression, if you happen to have an environment like mine.

### CIDER version information

;; CIDER 0.13.0 (California), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_45

### Lein/Boot version

2.7.0

### Emacs version

24.5.1

### Operating system

Running on OS X, but connected to OS X via ssh from Putty and displaying emacs -nw within Putty

**Comment by Malabarba** [comment]
What's the value of `buffer-file-coding-system` in you repl buffer?

**Comment by johnv02139** [comment]
nil

**Comment by Malabarba** [comment]
Could you try doing `M-x set-buffer-file-coding-system` and choosing utf8?

**Comment by johnv02139** [comment]
Unfortunately that definitely didn't change the apostrophes.  As far as I could tell, it didn't refresh the buffer at all, but maybe it did it so quickly I just didn't notice.

I have the same problem viewing the cider-repl.el file.  There, I tried revert-buffer-with-coding-system, and tried utf-8 and a few other things, and actually saw the display change, but nothing I tried actually made it right.

Note: I use Putty to ssh to the OS X machine, then run "emacs -nw" from the command line.  I tried viewing the .el file with "less" in the terminal, and it didn't display the characters correctly there, either.  So it's not just emacs.

Putty has settings for "translation", and my settings appear to be correct, but maybe there's some subtle thing somewhere that I haven't checked.

**Comment by Malabarba** [comment]
If you type `C-x 8 RET 2019`, on some other buffer (unrelated to cider), does it display correctly?

**Comment by johnv02139** [comment]
Nope.

A couple of other data points: as expected, everything was fine when running the same Emacs on the same OS X machine in "window mode" (i.e., not "-nw").  It also looked correct when running "emacs -nw" from inside Apple's "Terminal" program.  It did not work correctly when using iTerm2, a third-party terminal emulator which is (otherwise) vastly superior to "Terminal"

I never would have expected C-x 8 RET 2019 to work, at least not in a generic buffer.  Again, I hold out the possibility that there is some way to get Emacs to display Unicode characters in these environments, but I never thought it was specifically CIDER's fault.

**Comment by bbatsov** [comment]
Seems to me this must be tied to the encoding settings of the underlying terminal and I doubt there's much we can do.

Btw, what exactly is causing the problem for you? I don't recall any non-ASCII characters in the standard REPL banner.

**Comment by johnv02139** [comment]
It's the "smart apostrophes", e.g., in "you're".
![cider-youre](https://cloud.githubusercontent.com/assets/5966147/19165870/5b3356f6-8bba-11e6-85af-826c400e511b.jpg)

Obviously I agree there's nothing cider can do to make those non-ASCII chars show up properly in an environment that doesn't support them.  I would simply suggest changing them to ASCII apostrophes, and would be happy to submit a pull request if you tell me you'd take it.

**Comment by bbatsov** [comment]
Hmm, I thought this was an ascii character. They certainly look like regular apostrophes to me in the source code. Feel free to change them, though. I might be missing something...

**Comment by xiongtx** [comment]
`C-u C-x =` in the source code reports that It's actually a [RIGHT SINGLE QUOTATION MARK](http://www.fileformat.info/info/unicode/char/2019/index.htm).

**Comment by johnv02139** [comment]
Thanks, xiongtx.  Updated https://github.com/clojure-emacs/cider/pull/1857
