### ISSUE TITLE
Feature request: eldoc for datomic query input parameters

### ISSUE THREAD

**Issue by mallt** [clojure-emacs/cider#1832]
I guess this request might be too specific, but I think it would be useful if there would be eldoc support for datomic query input parameters.

For example in the following query, the `:in` keyword specifies the list of input parameters:
<img width="524" alt="datomic_query_example" src="https://cloud.githubusercontent.com/assets/8885691/18002373/a83bef1a-6b87-11e6-9ea0-569c2156a4a2.png">
so I guess it should be possible to use them in the eldoc info.

I'm not sure how this should be implemented, but if someone could give directions on how to do it, I would gladly give it a try.

Thanks a lot!

**Comment by bbatsov** [comment]
How do you imagine resulting eldoc for this query? I have never used datomic, so I'm not sure what exactly are we aiming for here.

**Comment by mallt** [comment]
The q function of datomic expects a query and the inputs of the query. This is the current eldoc info:
<img width="271" alt="datomic_q_eldoc" src="https://cloud.githubusercontent.com/assets/8885691/18026701/1edba1f6-6c50-11e6-8d88-efeb16adef30.png">

By examining the `:in` keyword of the query, the eldoc for the example query above could then become:
<img width="288" alt="datomic_q_eldoc_vars" src="https://cloud.githubusercontent.com/assets/8885691/18026837/fda6be78-6c52-11e6-9f1a-a8f5e653bba7.png">

**Comment by Malabarba** [comment]
I could see this as part of a larger feature. For instance, in macros
with a rich structure (like `letfn` or `defrecord`) when the cursor is
deep inside the macro, eldoc could tell you that here you should be
typing a function/method name, or here you should be typing an
arglist.

Then the same could apply to datomic queries, which follow a similar logic.

The problem, as usual, is implementing. Even in this generalized form, the feature has fairly limited application, and would require quite a bit more effort than the current eldoc.
