### ISSUE TITLE
cider-other-connection when jack-in with params

### ISSUE THREAD

**Issue by agzam** [clojure-emacs/cider#1834]
## Expected behavior
`(cider-repl-switch-to-other)` should take to Clojurescript repl

## Actual behavior
nothing

## Steps to reproduce the problem
- in a Clojurescript project with Figwheel, use Figwheel-sidecar, with a script similar to
https://github.com/bhauman/lein-figwheel/wiki/SASS-watcher
(to start Figwheel with sidecar api)
 
- set CIDER vars, e.g.:
```
(setq cider-lein-parameters "do clean, repl :headless")
(setq cider-cljs-lein-repl "(ra/start-figwheel! figwheel-config)")
```

- Jack-in `(cider-jack-in-clojurescript)`

- Try swiching to CLJS repl buffer with `(cider-repl-switch-to-other)` 

### CIDER version information
```
;; CIDER 0.14.0snapshot (package: 20160825.249), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_74
```

### Lein/Boot version
Leiningen 2.7.0 on Java 1.8.0_74 Java HotSpot(TM) 64-Bit Server VM

### Emacs version
24.5.1

### Operating system
OS X 10.11.6

**Comment by agzam** [comment]
Actually once connected (repl sees the browser session) it seem to work as expected. I'll keep an eye on it. This issue may have been reported prematurely and not an issue at all.

**Comment by bbatsov** [comment]
Guess we can close this then.
