### ISSUE TITLE
Allow function highlight in case of exception

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#1837]
A very nice (in progress) addition to `proto-repl` is the highlight (in red in the picture) of the functions involved in an exception, given the stacktrace.

![captura_de_pantalla_de_2016-08-29_12-05-47](https://cloud.githubusercontent.com/assets/1724788/18072966/3b81b6f6-6e17-11e6-98e4-d0505117a353.png)

It'd be very nice if we could add it to `cider` as well!

**Comment by bbatsov** [comment]
So, I'm guessing the idea is to highlight all lines featuring a function that appears in the stacktrace, right?

**Comment by arichiardi** [comment]
Yes exactly :)
-ar
