### ISSUE TITLE
Running two debuggable function calls in parallel hangs evaluation of first thread

### ISSUE THREAD

**Issue by aengelberg** [clojure-emacs/cider#1839]
## Steps to reproduce the problem

Write this function and send its definition to the REPL:

``` clojure
(defn foo
  [x]
  #dbg (+ x 2))
```

This compiles normally. Then, evaluate this in the REPL:

``` clojure
user=> (do (future (println (foo 1)))
           (Thread/sleep 1000)
           (future (println (foo 2))))
```
## Expected behavior

I get to step through `(foo 1)`, and then I get to step through `(foo 2)`.
## Actual behavior

The debugger appears showing `x => 1`. One second later, the 1 turns into a 2. After hitting <kbd>n</kbd> multiple times to step through the second expression, `4` prints out in the repl. The first expression never appears to finish evaluating.
### CIDER version information

```
;; CIDER 0.13.0 (California), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_92
```
### Lein/Boot version

Leiningen 2.6.1
### Emacs version

24.5.1
### Operating system

OS X 10.11.3 "El Capitan"

**Comment by grammati** [comment]
Yes, this is limitation at the moment.

I would like to see something like this:
- Debugger pops up, stopped in the call to `(foo 1)`
- a second later, a second debug buffer pops up, stopped in `(foo 2)`
- you can step through either one, interleaving execution order as you choose

I think this would be possible, but not easy. As a starting point, I think all the `def`-ed data that stores the debugger state [1] would need to move into, say, a map, keyed by thread. Cider would need to have separate nrepl sessions for each.

[1]
https://github.com/clojure-emacs/cider-nrepl/blob/86a52215acf45b14dfa000ff52d7103b05ac1fdd/src/cider/nrepl/middleware/debug.clj#L60-L78
https://github.com/clojure-emacs/cider-nrepl/blob/86a52215acf45b14dfa000ff52d7103b05ac1fdd/src/cider/nrepl/middleware/debug.clj#L178-L194

**Comment by vspinu** [comment]
> a second later, a second debug buffer pops up, stopped in (foo 2)

Opening a separate debugger buffer is not the best solution. You might have thousands of same function invocations in some instances. 

I think we need to proceed as edebug does, stop on first, but pass through subsequent invocations of the debugger if a debugger session for this function is already active.
