### ISSUE TITLE
test using clojure.spec.test/check throws weird exception (cider.nrepl.middleware.test$report cannot be cast to clojure.lang.MultiFn)

### ISSUE THREAD

**Issue by lvh** [clojure-emacs/cider#1841]
## Expected behavior

Wrote a test using `clojure.spec.test/check`:

``` clojure
(deftest ^:generative check-test
  (is (every? (comp nil? :failure) (stest/check))))
```

I was expecting the same failure as what I see on the command line with `lein test`, except with the usual CIDER-y goodness.
## Actual behavior

```
Show: Clojure Java REPL Tooling Duplicates All  (16 frames hidden)

3. Unhandled java.util.concurrent.ExecutionException
   java.lang.ClassCastException: cider.nrepl.middleware.test$report
   cannot be cast to clojure.lang.MultiFn,
   compiling:(clojure/test/check/clojure_test.cljc:95:1)

           FutureTask.java:  122  java.util.concurrent.FutureTask/report
           FutureTask.java:  192  java.util.concurrent.FutureTask/get
                  core.clj: 2290  clojure.core/deref-future
                  core.clj: 6847  clojure.core/future-call/reify
                  core.clj: 2310  clojure.core/deref
                  core.clj: 6898  clojure.core/pmap/step/fn
              LazySeq.java:   40  clojure.lang.LazySeq/sval
              LazySeq.java:   49  clojure.lang.LazySeq/seq
                 Cons.java:   39  clojure.lang.Cons/next
                   RT.java:  703  clojure.lang.RT/next
                  core.clj:   64  clojure.core/next
              dispatch.clj:   68  clojure.pprint/pprint-simple-list/fn
              dispatch.clj:   67  clojure.pprint/pprint-simple-list
              dispatch.clj:   77  clojure.pprint/pprint-list
              dispatch.clj:   76  clojure.pprint/pprint-list
              MultiFn.java:  229  clojure.lang.MultiFn/invoke
           pprint_base.clj:  194  clojure.pprint/write-out
              dispatch.clj:   68  clojure.pprint/pprint-simple-list/fn
              dispatch.clj:   67  clojure.pprint/pprint-simple-list
              dispatch.clj:   77  clojure.pprint/pprint-list
              dispatch.clj:   76  clojure.pprint/pprint-list
              MultiFn.java:  229  clojure.lang.MultiFn/invoke
           pprint_base.clj:  194  clojure.pprint/write-out
              dispatch.clj:   68  clojure.pprint/pprint-simple-list/fn
              dispatch.clj:   67  clojure.pprint/pprint-simple-list
              dispatch.clj:   77  clojure.pprint/pprint-list
              dispatch.clj:   76  clojure.pprint/pprint-list
              MultiFn.java:  229  clojure.lang.MultiFn/invoke
           pprint_base.clj:  194  clojure.pprint/write-out
           pprint_base.clj:  249  clojure.pprint/pprint/fn
           pprint_base.clj:  248  clojure.pprint/pprint
           pprint_base.clj:  241  clojure.pprint/pprint
           pprint_base.clj:  245  clojure.pprint/pprint
           pprint_base.clj:  241  clojure.pprint/pprint
                  test.clj:   79  cider.nrepl.middleware.test/test-result/fn
                  test.clj:   79  cider.nrepl.middleware.test/test-result
                  test.clj:   62  cider.nrepl.middleware.test/test-result
                  test.clj:  111  cider.nrepl.middleware.test/report
                  test.clj:   96  cider.nrepl.middleware.test/report
                  test.clj:  357  clojure.test/do-report
                  test.clj:  351  clojure.test/do-report
               my_test.clj:  129  myns.my-test/fn
               my_test.clj:  128  myns.my-test/fn
                  test.clj:  152  cider.nrepl.middleware.test/test-var/fn
                  test.clj:  152  cider.nrepl.middleware.test/test-var
                  test.clj:  144  cider.nrepl.middleware.test/test-var
                  test.clj:  168  cider.nrepl.middleware.test/test-vars/fn/fn
                  test.clj:  686  clojure.test/default-fixture
                  test.clj:  682  clojure.test/default-fixture
                  test.clj:  168  cider.nrepl.middleware.test/test-vars/fn
                  test.clj:  686  clojure.test/default-fixture
                  test.clj:  682  clojure.test/default-fixture
                  test.clj:  164  cider.nrepl.middleware.test/test-vars
                  test.clj:  158  cider.nrepl.middleware.test/test-vars
                  test.clj:  181  cider.nrepl.middleware.test/test-ns
                  test.clj:  172  cider.nrepl.middleware.test/test-ns
                  test.clj:  195  cider.nrepl.middleware.test/test-nss
                  test.clj:  186  cider.nrepl.middleware.test/test-nss
                  test.clj:  240  cider.nrepl.middleware.test/handle-test/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  657  clojure.core/apply
                  core.clj: 1963  clojure.core/with-bindings*
                  core.clj: 1963  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
                  test.clj:  237  cider.nrepl.middleware.test/handle-test/fn
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run

2. Caused by clojure.lang.Compiler$CompilerException
   Error compiling clojure/test/check/clojure_test.cljc at (95:1)

             Compiler.java: 7415  clojure.lang.Compiler/load
                   RT.java:  374  clojure.lang.RT/loadResourceScript
                   RT.java:  365  clojure.lang.RT/loadResourceScript
                   RT.java:  455  clojure.lang.RT/load
                   RT.java:  421  clojure.lang.RT/load
                  core.clj: 6008  clojure.core/load/fn
                  core.clj: 6007  clojure.core/load
                  core.clj: 5991  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5812  clojure.core/load-one
                  core.clj: 5807  clojure.core/load-one
                  core.clj: 5852  clojure.core/load-lib/fn
                  core.clj: 5851  clojure.core/load-lib
                  core.clj: 5832  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5889  clojure.core/load-libs
                  core.clj: 5873  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5911  clojure.core/require
                  core.clj: 5911  clojure.core/require
               RestFn.java:  482  clojure.lang.RestFn/invoke
                check.cljc:   10  clojure.test.check$eval37910$loading__7531__auto____37911/invoke
                check.cljc:   10  clojure.test.check$eval37910/invokeStatic
                check.cljc:   10  clojure.test.check$eval37910/invoke
             Compiler.java: 6951  clojure.lang.Compiler/eval
             Compiler.java: 6940  clojure.lang.Compiler/eval
             Compiler.java: 7403  clojure.lang.Compiler/load
                   RT.java:  374  clojure.lang.RT/loadResourceScript
                   RT.java:  365  clojure.lang.RT/loadResourceScript
                   RT.java:  455  clojure.lang.RT/load
                   RT.java:  421  clojure.lang.RT/load
                  core.clj: 6008  clojure.core/load/fn
                  core.clj: 6007  clojure.core/load
                  core.clj: 5991  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5812  clojure.core/load-one
                  core.clj: 5807  clojure.core/load-one
                  core.clj: 5852  clojure.core/load-lib/fn
                  core.clj: 5851  clojure.core/load-lib
                  core.clj: 5832  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5889  clojure.core/load-libs
                  core.clj: 5873  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5911  clojure.core/require
                   gen.clj:   18  clojure.spec.gen/dynaload
                   gen.clj:   26  clojure.spec.gen/fn
                   gen.clj:   26  clojure.spec.gen/fn
                Delay.java:   37  clojure.lang.Delay/deref
                  core.clj: 2310  clojure.core/deref
                   gen.clj:   27  clojure.spec.gen/quick-check
                   gen.clj:   27  clojure.spec.gen/quick-check
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  661  clojure.core/apply
                  test.clj:  305  clojure.spec.test/quick-check
                  test.clj:  332  clojure.spec.test/check-1
                  test.clj:  408  clojure.spec.test/check/fn
                  core.clj: 6895  clojure.core/pmap/fn/fn
                  core.clj: 2020  clojure.core/binding-conveyor-fn/fn
                  AFn.java:   18  clojure.lang.AFn/call
           FutureTask.java:  266  java.util.concurrent.FutureTask/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run

1. Caused by java.lang.ClassCastException
   cider.nrepl.middleware.test$report cannot be cast to
   clojure.lang.MultiFn

                  core.clj: 1807  clojure.core/get-method
                  core.clj: 1807  clojure.core/get-method
         clojure_test.cljc:   95  clojure.test.check.clojure_test$eval37947/invokeStatic
         clojure_test.cljc:   95  clojure.test.check.clojure_test$eval37947/invoke
             Compiler.java: 6951  clojure.lang.Compiler/eval
             Compiler.java: 7403  clojure.lang.Compiler/load
                   RT.java:  374  clojure.lang.RT/loadResourceScript
                   RT.java:  365  clojure.lang.RT/loadResourceScript
                   RT.java:  455  clojure.lang.RT/load
                   RT.java:  421  clojure.lang.RT/load
                  core.clj: 6008  clojure.core/load/fn
                  core.clj: 6007  clojure.core/load
                  core.clj: 5991  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5812  clojure.core/load-one
                  core.clj: 5807  clojure.core/load-one
                  core.clj: 5852  clojure.core/load-lib/fn
                  core.clj: 5851  clojure.core/load-lib
                  core.clj: 5832  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5889  clojure.core/load-libs
                  core.clj: 5873  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5911  clojure.core/require
                  core.clj: 5911  clojure.core/require
               RestFn.java:  482  clojure.lang.RestFn/invoke
                check.cljc:   10  clojure.test.check$eval37910$loading__7531__auto____37911/invoke
                check.cljc:   10  clojure.test.check$eval37910/invokeStatic
                check.cljc:   10  clojure.test.check$eval37910/invoke
             Compiler.java: 6951  clojure.lang.Compiler/eval
             Compiler.java: 6940  clojure.lang.Compiler/eval
             Compiler.java: 7403  clojure.lang.Compiler/load
                   RT.java:  374  clojure.lang.RT/loadResourceScript
                   RT.java:  365  clojure.lang.RT/loadResourceScript
                   RT.java:  455  clojure.lang.RT/load
                   RT.java:  421  clojure.lang.RT/load
                  core.clj: 6008  clojure.core/load/fn
                  core.clj: 6007  clojure.core/load
                  core.clj: 5991  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5812  clojure.core/load-one
                  core.clj: 5807  clojure.core/load-one
                  core.clj: 5852  clojure.core/load-lib/fn
                  core.clj: 5851  clojure.core/load-lib
                  core.clj: 5832  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5889  clojure.core/load-libs
                  core.clj: 5873  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj: 5911  clojure.core/require
                   gen.clj:   18  clojure.spec.gen/dynaload
                   gen.clj:   26  clojure.spec.gen/fn
                   gen.clj:   26  clojure.spec.gen/fn
                Delay.java:   37  clojure.lang.Delay/deref
                  core.clj: 2310  clojure.core/deref
                   gen.clj:   27  clojure.spec.gen/quick-check
                   gen.clj:   27  clojure.spec.gen/quick-check
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  661  clojure.core/apply
                  test.clj:  305  clojure.spec.test/quick-check
                  test.clj:  332  clojure.spec.test/check-1
                  test.clj:  408  clojure.spec.test/check/fn
                  core.clj: 6895  clojure.core/pmap/fn/fn
                  core.clj: 2020  clojure.core/binding-conveyor-fn/fn
                  AFn.java:   18  clojure.lang.AFn/call
           FutureTask.java:  266  java.util.concurrent.FutureTask/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run
```
## Steps to reproduce the problem

Write above test, go to test, `C-c C-t t` (`cider-test-run-test`).

Other tests work fine.
### CIDER version information

```
;; CIDER 0.14.0snapshot (package: 20160830.23), nREPL 0.2.12
;; Clojure 1.9.0-alpha11, Java 1.8.0_102
```
### Emacs version

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org
### Operating system

OS X 10.11.6

**Comment by bbatsov** [comment]
@sebastianpoeplau can you take a look at this bug report?

**Comment by sebastianpoeplau** [comment]
I think this is the same issue as https://github.com/clojure-emacs/cider-nrepl/issues/369. @lvh, could you try the solution proposed there? See the linked ticket for background - essentially, it's not an issue with CIDER directly but an unfortunate interleaving of CIDER's test instrumentation and spec's dynamic loading of `test.check`. (You will most likely be seeing a crash with `lein test` too, but the exception message will be slightly different.)

**Comment by lvh** [comment]
It does seem very similar! However, _most_ tests for me work fine, it's only the one that calls `stest/check`. Also, the error did start spuriously disappearing on me today; I'll attempt to reproduce and then try the workaround.

**Comment by lvh** [comment]
FWIW, lein test works fine for me, as sometimes did cider, e.g.:

http://dev.clojure.org/jira/browse/CLJ-2008

**Comment by lvh** [comment]
Managed to reproduce the issue in a fresh REPL. You're definitely right that this has something to do with it though, because then added a `[clojure.test.check]`, running the test again:

```
2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling clojure/test/check.cljc at (10:1)

1. Caused by java.lang.Exception
   namespace 'clojure.test.check.clojure-test' not found
```

- With a fresh REPL, no other namespaces loaded, the generative tests don't fail with an exception, but don't test anything; with or without `clojure.test.check` require
- With a fresh REPL, one other non-test ns loaded that defines specs with `fdef`, and no `clojure.test.check` require, tests fail as above
- With a fresh REPL, one other non-test ns loaded that defines specs with `fdef`, and `clojure.test.check` require, tests peg a core and seem to run forever -- I'll see if they eventually work :D 

So you're definitely right that that impacts the issue :)

**Comment by lvh** [comment]
The hanging forever bit appears to be a separate problem; so you can ignore that part.

**Comment by sebastianpoeplau** [comment]
When you say you're using a fresh REPL, how do you launch it? `lein repl`? If so, could you check if adding `:monkeypatch-clojure-test false` to your project.clj has any effect? (It will prevent leiningen from patching the test framework, which seems to be another cause of exceptions under some circumstances.)

**Comment by sebastianpoeplau** [comment]
Sorry, I might have misunderstood; if the "fresh REPL" is within CIDER then never mind what I said above.

Let me elaborate a little on what I think the issue is, so maybe you can find the trigger in your code: The first element of the problem is that `test.check` extends a multi-function in `clojure.test`. The second element is that CIDER patches that very same function, essentially wrapping it with something that is not a multi-function. Usually, this is not a problem because the extension happens first, i.e. when `test.check` is loaded, and later CIDER kicks in and wraps everything. With `spec`'s lazy loading of `test.check`, however, the order is reversed: CIDER wraps the multi-function in `clojure.test`, and later on `spec` lazily loads `test.check`, which tries to extend the now-wrapped multi-function; as CIDER's wrapping is not a multi-function you see the `ClassCastException`. (My suggestion to require a namespace from `test.check` explicitly is meant to eliminate the lazy loading when running tests.)

Hope this helps to identify the problem.

**Comment by bbatsov** [comment]
So, does anyone has an action plan regarding this or we can close the ticket?

**Comment by Malabarba** [comment]
Sounds like it's our fault then. Wrapping a multi-fn in something else is probably not part of clojure.test's intended API. Could we do this without the wrapping? Or maybe wrap more inteligently (like wrapping in a multi-fn that can still be extended)?

**Comment by lvh** [comment]
Sorry; I completely lost track of this ticket.

a. The workaround works. Thanks!
b. I don't think the workaround is more than a validated hypothesis or a temporary band-aid: this is tricky to discover without filing a ticket.

**Comment by sebastianpoeplau** [comment]
I guess it's somewhat hard to intercept test results without wrapping that function, and I think leiningen does it the same way. Let me check...

**Comment by sebastianpoeplau** [comment]
Indeed, leiningen also [wraps](https://github.com/technomancy/leiningen/blob/master/src/leiningen/test.clj#L96) `clojure.test/report` (and it also crashes in the scenario we're discussing). Another way to obtain information about the test results is the return value of `clojure.test/run-tests`, but it's very basic. That's what leiningen relies on when you [disable](https://github.com/technomancy/leiningen/blob/master/src/leiningen/test.clj#L211) monkey-patching, but I guess it's not sufficient for the detailed failure information that CIDER wants to display.

**Comment by sebastianpoeplau** [comment]
[TCHECK-113](http://dev.clojure.org/jira/browse/TCHECK-113) discusses the problem in the context of `lein test`, but the conclusion seems to be that people are unlikely to run into the issue...

As for wrapping more intelligently, I guess it might be possible to wrap `clojure.test/report` in a multi-fn and use the `:default` implementation to forward to the wrapped function. It would avoid the crash but we'd miss calls related to `test.check` because later extensions would capture them before they reach us. In that case I think we'd lose the ability to display the generated input that a test failed on (see https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/test.clj#L117), but it might still be a better solution than what we currently have.

**Comment by owickstrom** [comment]
I have also run in to this problem with cider and the Emacs plugin. With `:monkeypatch-clojure-test false` the tests run properly with `lein test`, but all variations of test runs inside Emacs with Cider fails for `check`-based tests.

**Comment by sebastianpoeplau** [comment]
@owickstrom I don't know if there are plans to fix the issue, but you can almost certainly keep using Emacs if you just explicitly require some `test.check` namespace before using one of spec's test functions.

**Comment by owickstrom** [comment]
@sebastianpoeplau OK, I'll try that, thanks!

**Comment by yenda** [comment]
@sebastianpoeplau I had this error too and requiring [clojure.test.check] in my test namespace got rid of it.

**Comment by sebastianpoeplau** [comment]
@yenda glad to hear that it helped!

It seems that more people are affected by this than suggested by [TCHECK-113](http://dev.clojure.org/jira/browse/TCHECK-113). Maybe Cider should try to wrap `clojure.test/report` in a multi-fn, as described above.

**Comment by dpsutton** [comment]
@yenda @owickstrom can one of you perhaps upload a repo that has a minimum example? I haven't really delved into spec but if you give me the repo I can work on this. I'm just lacking a starting point for investigation.

**Comment by owickstrom** [comment]
@dpsutton the codebase I have trouble with is onfortunately private, but I'll try to reproduce with a minimal example as soon as possible.

**Comment by MaheshBabuRajasekar** [comment]
@sebastianpoeplau I add this error too. I have added `(require [clojure.test.check :as tc]` in my test namespace and recompiled my cider-repl (Emacs).
It compiled and ran my spec-check-tests using `deftest` successfully without any errors.
Thanks!

**Comment by FossiFoo** [comment]
just wanted to add in that i also ran into this. proposed workaround works.

**Comment by mathpunk** [comment]
Just in case it helps, I tried this workaround by loading

    (ns game.board-test
      (:require  [clojure.test :refer [deftest testing is]]
                 [clojure.test.check :as chk]
                 [clojure.spec.alpha :as s]    
                 [clojure.spec.gen.alpha :as gen]
                 [clojure.spec.test.alpha :as stest]
                 [clojure.pprint :as pprint]
                 [game.board :refer :all]))

And the resulting stacktrace included
    ...
    regrow.clj:   18  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
    ...

I don't have slamhound in my lein profile anymore so, this struck me as weird.

**Comment by annapawlicka** [comment]
I've started seeing this error yesterday, out of the blue. None of the workarounds helped but everything went back to normal when I deleted `clojure.test.check` jar from `.m2` and downloaded a fresh copy ¯\_(ツ)_/¯

**Comment by codeasone** [comment]
I'm still seeing this today. With `[org.clojure/test.check "0.9.0"]` in `project.clj`, the work-around for me was to add `[clojure.test.check.impl]` to the require list in my test namespace. 

Without this, I was seeing the aforementioned `cider.nrepl.middleware.test$report cannot be cast to
   clojure.lang.MultiFn`.

**Environment:** 
```
;; CIDER 0.15.1 (package: 20170913.434) (London), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_144
```

**Comment by xiongtx** [comment]
Seem this can be closed.

- The original test case doesn't even fail with `clojure.spec.test.alpha`.
- `cider.nrepl.middleware.test/report` is [now a multimethod](https://github.com/clojure-emacs/cider-nrepl/pull/510).
    - Not sure if this has any impact on [TCHECK-113](https://dev.clojure.org/jira/browse/TCHECK-113)
