### ISSUE TITLE
Non-descript error when leiningen is not found on the path

### ISSUE THREAD

**Issue by credmp** [clojure-emacs/cider#1842]
## Expected behavior
When calling cider-jack-in without leiningen available I would expect to be told "Leiningen can not be found"

## Actual behavior
The error message "shell-quote-argument: Wrong type argument: arrayp, nil" is shown.

## Steps to reproduce the problem
Call cider-jack-in without leiningen on the path.

### CIDER version information
Version: 0.13.0

### Lein/Boot version
Lein was not available on the path

### Emacs version
Emacs: 24.5.1

### Operating system
OS: Windows 10

**Comment by bbatsov** [comment]
This is already fixed on `master`. See https://github.com/clojure-emacs/cider/commit/ee63ad0eeda42e958c90e540a4e65579f73edadd
