### ISSUE TITLE
Required feature ‘spinner’ was not provided

### ISSUE THREAD

**Issue by madeye-matt** [clojure-emacs/cider#1843]
## Expected behavior

After following the install instructions, and executing "M-x cider-jack-in" I expect the Cider REPL to run

## Actual behavior

After following the install instructions, and executing "M-x cider-jack-in" I get the error:

eval-buffer: Required feature ‘spinner’ was not provided

## Steps to reproduce the problem

(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
M-x package-install [RET]cider[RET]
M-x cider-jack-in

## Additional information

Following the installation of cider, M-x list packages shows:
```
spinner is a dependency package.
Status: Installed in ‘spinner-1.7.1/’ (unsigned).
Version: 1.7.1
Summary: Add spinners and progress-bars to the mode-line for ongoing operations
Required by: cider-20160830.23
Homepage: https://github.com/Malabarba/spinner.el
Keywords: processes mode-line 
Other versions: 1.7.1 (gnu).

```
so it looks like spinner is installed.  However, running (spinner "1.7.1") or any of the spinner functions from a scratch buffer gives the same error (void-function spinner) and (require 'spinner) gives "Required feature 'spinner' was not provided", so possibly this is an issue with spinner.  However I don't know enough about emacs to know how to unpick the dependency and manually install a fresh version (any advice welcome!)

### CIDER version information

Cider does not run so no version available from REPL.  Emacs reports the package as:
cide-20160830.23

### Lein/Boot version

N/A

### Emacs version

GNU Emacs 25.0.94.2 (x86_64-w64-mingw32) of 2016-05-26

### Operating system

Windows 10

**Comment by madeye-matt** [comment]
Now I've gone to the lengths to report the problem I've found the solution - looks like the spinner install from melpa may be broken - I uninstalled/re-installed cider 3 times and the results were the same, namely that spinner.el came down empty.

So to fix my problem, I:

1. downloaded the release files from: https://github.com/Malabarba/spinner.el/releases/tag/1.7.1
2. Extracted the correct spinner.el from the download
3. Delete spinner.elc from my emacs.d directory

**Comment by mattdeboard** [comment]
So I just upgraded all my emacs packages on an older laptop, and when I tried to `cider-jack-in` to a new project, I got the error in the initial bug report.

For me, all I had to do was:

1. `M-x package-list`
2. Find `spinner` in the buffer, then tap `d` on that line, then `x` to uninstall that package.
3. `M-x package-install RET spinner RET`

Then `cider-jack-in` worked.

However, since there does not appear to be a `spinner` package listed at melpa.org, it might be wise to remove this dependency or work with the spinner maintainer to sort out whatever issue this is between their repo and melpa.

**Comment by bbatsov** [comment]
@mattdeboard this package is on ELPA - the official Emacs package repository that's enabled by default for every Emacs installation.

**Comment by mattdeboard** [comment]
Alright.

**Comment by zoechi** [comment]
I have read somewhere that this is an issue with http vs https

I tried to install a package that seems to have spinner as a dependency and I get
```
Error while verifying signature spinner-1.7.3.el.sig:

Command output:
gpg: verify signatures failed: Unknown system error
```

**Comment by bbatsov** [comment]
There's also this article I wrote https://metaredux.com/posts/2019/12/09/dealing-with-expired-elpa-gpg-keys.html Probably it's worth adding this to CIDER's own FAQ.

**Comment by metayan** [comment]
> There's also this article I wrote https://metaredux.com/posts/2019/12/09/dealing-with-expired-elpa-gpg-keys.html Probably it's worth adding this to CIDER's own FAQ.

Oh, this might been helpful during the recent hours of fighting with `eldev compile` about "expired key". Thanks for the article.
Not sure what really made a difference, but as a finishing touch I had to delete `~/.cache/eldev` as well.
Just another tip thrown into the cauldron.

https://github.com/Malabarba/spinner.el/issues/30
