### ISSUE TITLE
cider-test-run-last-test - feature request

### ISSUE THREAD

**Issue by decoursin** [clojure-emacs/cider#1851]
Sometimes, I just want to run the last test, but I don't want to have to flip-back just to run it.

Thanks so much for Cider!

**Comment by bbatsov** [comment]
What's your definition of the "last test"?

**Comment by xiongtx** [comment]
Do you know about the `cider-test-*` commands, particularly `cider-test-rerun-tests`? It re-runs the tests that failed in the previous run.

**Comment by johngit22** [comment]
Unknown by me at least..

**Comment by decoursin** [comment]
The last run test. My test may have failed or passed, doesn't matter; since now I've changed the code, say, and I want to rerun the test.

**Comment by decoursin** [comment]
Thank you!
