### ISSUE TITLE
Problem with jack-in and tramp

### ISSUE THREAD

**Issue by carrete** [clojure-emacs/cider#1854]
When I have a buffer open, project.clj for example, over a tramp connection and I try to jack-in, CIDER somehow replaces `lein` with the tramp buffer name. For example:

```
Starting nREPL server via /ssh\:root\@localhost\#32808\: update-in :dependencies conj \[acyclic/squiggly-clojure\ \"0.1.5\"\] -- update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.13.0\"\] -- repl :headless...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: /bin/sh: 2: /ssh:root@localhost#32808:: not found
```
## Expected behavior

When `M-x cider-jack-in` or `M-x cider-jack-in-clojurescript` is run in a tramp buffer CIDER should use `lein` to start an nrepl server on the command-line.
## Actual behavior

CIDER uses the tramp buffer name in place of `lein` on the command-line.
## Steps to reproduce the problem
1. Use tramp to open a buffer.
2. In this buffer run `M-x cider-jack-in` or `M-x cider-jack-in-clojurescript`.
### CIDER version information

CIDER 0.13
### Lein/Boot version

lein 2.6.1
### Emacs version

25.1.1
### Operating system

macOS Sierra

**Comment by bbatsov** [comment]
@benedekfazekas Can you look into this? Perhaps you didn't took into account remote buffers in the new jack-in logic or something?

**Comment by benedekfazekas** [comment]
will have a look

**Comment by benedekfazekas** [comment]
had a look. I don't think it is a regression actually. It seems to me that jack in over tramp is kinda half baked, this todo comment perhaps seconds that?! https://github.com/clojure-emacs/cider/blob/master/cider.el#L686

I may be misunderstanding the code but I assume this:
```
 (when-let ((command (or (file-remote-p default-directory) 
                         (executable-find cider-lein-command)
                         (executable-find (concat cider-lein-command ".bat")))))
    (shell-quote-argument command))
```
will never work for a remote project.clj as it tries to run the remote default directory as a lein command?!

**Comment by bbatsov** [comment]
Oh, shit - yeah. I now remember I couldn't quickly figure out how to check for the executable on the remote host. But I remember this check was actually fixing something. :-)

**Comment by benedekfazekas** [comment]
i can put this on my list but cljr hacking comes first now. as a temporary measure we can show an error if the file is remote I guess and point the user towards using `cider-connect` to a remote REPL i suppose. there could be also some rabbit holes with remote files (have not grepped cljr issues but we had some problems with them afair)

**Comment by carrete** [comment]
> as a temporary measure we can show an error if the file is remote I guess and point the user towards using cider-connect to a remote REPL

Could I set a variable instead to specify the remote command?

**Comment by bbatsov** [comment]
This can be done, but it'd be messy. All variable would have to be set to `nil` by default, otherwise all resolve commands would always match. Ideally we should figure out if there's something like `executable-find` working over tramp.

**Comment by zenspider** [comment]
@bbatsov I don't have a direct answer to your question...but I know that `ssh.el` tab completes commands correctly. Looking at `ssh-tab-or-complete` shows it calls `completion-at-point`. Not sure that's going to help.

**Comment by carrete** [comment]
> I've committed a potential workaround - on remote hosts we simply assume the command we need is available. Please, try it out.

Thanks @bbatsov. I dropped the new cider.el on top of cider.el v0.13, restarted emacs, opened project.clj over tramp, then jacked-in, and still the same problem. What more can I provide to you to help with this?

**Comment by benedekfazekas** [comment]
you might have it compiled. remove cider.elc if it is in the directory

**Comment by bbatsov** [comment]
I can't imagine how my fix wouldn't be working - it basically returns the name of the command matching the project's type, without trying to resolve it. If this binary exists on the remote host everything should work just fine.

**Comment by carrete** [comment]
> you might have it compiled. remove cider.elc if it is in the directory

Damnit. That was it. It works! Thanks!

**Comment by bbatsov** [comment]
Seems that the proper solution for this would be the use of `tramp-find-executable` (part of the built-in library `tramp-sh.el`.).  Down the road we should leverage this.

**Comment by soulawaker** [comment]
I've tried `cider-jack-in` in remote machine source.
```
Tramp: Opening connection for <remote host info> using ssh...
Tramp: Sending command `exec ssh -q   -o ControlMaster=auto -o ControlPath='tramp.%C' -o ControlPersist=no -e none <remote host info>'
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on <remote host info>
Tramp: Opening connection for <remote host info> using ssh...done
Making nrepl-create-client-buffer-function local to *nrepl-server guestbook* while let-bound!
Making nrepl-use-this-as-repl-buffer local to *nrepl-server guestbook* while let-bound!
Starting nREPL server via lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.13\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refactor-nrepl\ \"2.4.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.17.0-SNAPSHOT\"\] -- repl :headless :host ::...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: /bin/sh: 2: lein: not found

error in process sentinel: Could not start nREPL server: /bin/sh: 2: lein: not found
```

I've traced from `cider-jack-in` to `nrepl-server-sentinel`. Edebugger shows that `set-process-coding-system`'s parameter, `serv-proc` has the message, "Input file descriptor of nrepl-server closed". So, I guess this problem is related `set-process-sentinel`. I'm stuck here.

BTW, I already report [`cider-connect` related issue](https://github.com/clojure-emacs/cider/issues/2148). I heartily thank you for developing cider. I want to work directly in remote service server. Could I work it with cider?

**Comment by bbatsov** [comment]
I see that `lein` is not your `exec-path` on the remote server. I guess that's what the cause of your problem.

**Comment by soulawaker** [comment]
I already set `lein` to `exec-path`.

**Comment by bbatsov** [comment]
So, you did something like this https://stackoverflow.com/questions/26630640/tramp-ignores-tramp-remote-path and you verified that tramp sees the remote `lein`?

**Comment by soulawaker** [comment]
I'm very sorry. My PATH setting placed in `.profile`. So I thought Tramp should check this naturally. But it ignored. I was thoughtless. Thank you for the hint.

**Comment by holtzermann17** [comment]
FYI, with a recent version of cider, I tried to connect to a server and got this message:

> nrepl-connect: [nREPL] Direct connection to my.server:43681 failed; try setting ‘nrepl-use-ssh-fallback-for-remote-hosts’ to t

After putting that setting in place, the remote connection works for me.

**Comment by vemv** [comment]
See https://github.com/clojure-emacs/cider/issues/2703#issuecomment-1679387356
