### ISSUE TITLE
bam!

### ISSUE THREAD

**Issue by timothypratley** [clojure-emacs/cider#1855]
*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable CIDER and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

*When requesting new features or improvements to existing features you can
discard the template completely. Just make sure to make a good case for your
request.*

**Remove all of the placeholder text in your final report!**

## Steps to reproduce the problem

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.12.0snapshot (package: 20160331.421), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_31
```

### Lein/Boot version

*E.g. Lein 2.6.1* (skip this when you didn't start the nREPL server
using Lein or Boot)

### Emacs version

*E.g. 24.5* (use <kbd>M-x emacs-version</kbd> to check it if unsure)

### Operating system

*E.g. Fedora 23, OS X 10.11 "El Capitan", Windows 10, etc*

**Comment by bbatsov** [comment]
@timothypratley Guess you forgot to add something here. :-)

**Comment by timothypratley** [comment]
oppS! :)
