### ISSUE TITLE
Enhancement request: include `(testing ...)` context in *cider-test-report* buffer

### ISSUE THREAD

**Issue by ncalexan** [clojure-emacs/cider#1856]
This ticket tracks displaying the `(testing ...)` context string of failing tests in the test report buffer.

Context: many of my tests have non-trivial setup time, so I prefer to structure my tests as a single `deftest` with multiple `(testing ...)` context blocks.  I tend to get a lot of mostly useless stacktraces from my tests (i.e., no indication _which_ test failed), and it would help a lot to have at least the context string displayed.  For example:

```
datomish.db-test
1 non-passing tests:

Error in test-fulltext
Uncaught exception, not in assertion
   error: clojure.lang.ExceptionInfo: Transaction violates unique constraint {}
```

would be much easier to interpret if it showed me the `(testing "Can upsert keyed by fulltext indexed datoms" ...)` message.

**Comment by bbatsov** [comment]
Guess we should check how easy it's to get a hold of this information.

**Comment by jcf** [comment]
I'm not sure if this helps, but I see `testing` strings in my test reports…

``` clj
(deftest t-testing
  (testing "things"
    (is (= 1 2))))
```

```
Fail in t-testing
things
expected: (= 1 2)
  actual: (not (= 1 2))
```

![2017-01-19-17 20 08-233ca8147ba5](https://cloud.githubusercontent.com/assets/18374/22117357/8e1b5f9c-de6b-11e6-97aa-18237df55026.png)

I'm using Spacemacs so maybe there's something in my Emacs config adding is outside of Cider?

**Comment by expez** [comment]
I'm not using spacemacs andI see the same.  I guess this was working all along.

**Comment by bbatsov** [comment]
Perhaps @ncalexan was using an older CIDER version?
