### ISSUE TITLE
Find usages error on lein-bikeshed code

### ISSUE THREAD

**Issue by doubleagent** [clojure-emacs/cider#1858]
Screenshot shows all the details I have.  I commented out virtually all the code, saved, killed and restarted cider a few times.  The error occurs during project analysis.  Something to do with leiningen plugins, maybe?

![cider_bikeshed_find_usages_err](https://cloud.githubusercontent.com/assets/56522/19178515/f4788e0e-8c18-11e6-8ffb-1e45d1ff741d.png)

**Comment by bbatsov** [comment]
This functionality is not in CIDER - it's in `clj-refactor.el`. Please, report the issue there.

**Comment by doubleagent** [comment]
Thanks
