### ISSUE TITLE
Optimize the performance of the nREPL message log

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1859]
As discussed in https://github.com/clojure-emacs/cider/issues/1758 the nREPL message logging is pretty slow (especially when big data structures are involved) and enabling logging causes constant freezes.

To alleviate the problem logging was disabled by default, but we still need to analyze and optimize the problematic code (`nrepl--pp` seems to be the main culprit here). 

//cc @vspinu

**Comment by vspinu** [comment]
The issues seem to be coming from `pp-to-string`. It shouldn't be hard to get rid of it.

**Comment by bbatsov** [comment]
@vspinu Can you look into this?

**Comment by vspinu** [comment]
Sure. I will have a look over the weekend.

**Comment by bbatsov** [comment]
@vspinu Thanks!
