### ISSUE TITLE
Possible security vulnerability from connecting to clojure via TCP on localhost

### ISSUE THREAD

**Issue by frejanordsiek** [clojure-emacs/cider#1864]
This just popped up as affecting Guile and I looked at Cider and it seems to be connecting to clojure over TCP on localhost, so it would be similarly vulnerable. The report on Guile's bug database is at

https://lists.gnu.org/archive/html/guile-user/2016-10/msg00007.html

It's third reference details the general attack

http://bouk.co/blog/hacking-developers/

Basically, if you are using cider to connect to clojure over a TCP port, even locally on localhost only on a machine where you are the only user, but using a modern web browser, arbitrary code can be injected into the clojure session. Using some sort of shared secret key to authenticate to clojure or using local sockets are ways to mitigate it. Hopefully, cider does mitigate this already and I missed where it does it. If not, this is definitely something to fix.

**Comment by bbatsov** [comment]
Thanks for reporting this! Guess we'll have to look into it.

**Comment by bbatsov** [comment]
Btw, here's something related we've been working on - https://github.com/nrepl/nREPL/pull/46 (authentication support for nREPL).
