### ISSUE TITLE
Instrumented function is stopped only once when called by core.async thread/go.

### ISSUE THREAD

**Issue by sjlnk** [clojure-emacs/cider#1869]
## Expected behaviour

Get back to the debugger mode after pressing c and calling the instrumented code again from `thread` or `go` block. Code should stop on the debugger on each iteration of the loop inside `looper` function.
## Actual behavior

Debugger is initialized only on the first run and cannot be reinitialized again.
## Steps to reproduce the problem

``` clojure
(ns tests.core
  (:require
   [clojure.core.async :refer [thread go offer! poll! promise-chan]]))

(defn testfun []
  (println (java.util.Date.)))

(defn looper [exprom]
  (loop []
    (when-not (poll! exprom)
      (testfun)
      (Thread/sleep 3000)
      (recur)))
  (println "exit"))

(comment
  (def exprom (promise-chan))
  (thread (looper exprom))
  (offer! exprom :exit))
```

Use the snippet above to get into the problematic environment. Call `looper` in `thread` or `go` macro and instrument `testfun`. After pressing `c` (for continue) or removing instrumentation (by evaluating `testfun` definition normally) debugger cannot be reached anymore. I have not found any way to get back to the debugger at this point.

The debugger seems to be working properly when working with java.lang.Thread directly.
### CIDER version information

commit @0803409

;; CIDER 0.15.0snapshot, nREPL 0.2.12
;; Clojure 1.8.0, Java 1.7.0_111
### Lein/Boot version

Leiningen 2.7.1 on Java 1.7.0_111 OpenJDK 64-Bit Server VM
### Emacs version

GNU Emacs 25.0.95.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2016-07-24
### Operating system

Linux Mint 17 Qiana, kernel 3.13.0-24-generic

**Comment by cch1** [comment]
I'm seeing something similar with emacs 25 and cider 0.15.0, but core.async is not involved.  I'm still trying to find a simple-to-reproduce example, but I thought I'd lend my voice to this issue.
