### ISSUE TITLE
Option for opening REPL but not moving cursor

### ISSUE THREAD

**Issue by raxod502** [clojure-emacs/cider#1872]
We have the option `cider-repl-pop-to-buffer-on-connect`, which affects what happens when CIDER connects to the REPL. When it's on, the REPL buffer is opened and my cursor is moved to it. When it's off, the REPL buffer is not opened.

I would like the REPL buffer to be opened but my cursor to _not_ be moved to it.

This is my current solution:

```
(setq cider-repl-pop-to-buffer-on-connect nil)
(defadvice cider-repl-init (after display-repl-buffer)
  (display-buffer buffer))
```

It's not ideal because it means that when I do `C-c M-J`, only one of the REPLs is opened, instead of both, which is what happens when `cider-repl-pop-to-buffer-on-connect` is enabled (https://github.com/raxod502/radian/issues/105).

**Comment by Malabarba** [comment]
Minor comment. If we do this, it should be a different value for this variable, not a new variable.

**Comment by bbatsov** [comment]
Yeah, I guess that would be best.
