### ISSUE TITLE
Pretty Printing Exceptions in cider-test

### ISSUE THREAD

**Issue by rymndhng** [clojure-emacs/cider#1873]
When I'm working with `cider-test` and a test throws a `ex-info` with a large data structure (i.e. working with prismatic.schema), it's always printed in a single line (regardless if I have pretty-printing enabled or disabled). 

If we had the ability to pretty-print these objects, it would make inspecting large objects easier.

**Comment by bbatsov** [comment]
Is your issue similar to https://github.com/clojure-emacs/cider/issues/1707 ?

I'm not sure what exactly are you suggesting that we should pretty-print.

**Comment by rymndhng** [comment]
@bbatsov Similar error, (in fact I am using schema as well). 

I'm wondering if it's possible to take that exception object and pretty print it because the map object is quite big.

<img width="709" alt="screen shot 2016-10-25 at 10 10 28 pm" src="https://cloud.githubusercontent.com/assets/1694040/19714038/decb533e-9aff-11e6-93ad-46efbbc716a3.png">

**Comment by bbatsov** [comment]
The problem is that this is just plain text in the exception message and here's no way to know what's a Clojure object there and what is not...

**Comment by xiongtx** [comment]
Is there a way to tell whether the exception is an `ExceptionInfo` object? If so, we know that it's a [message followed by a map](https://clojuredocs.org/clojure.core/ex-info).

Clojure itself tends to be pretty consistent in using `ex-info` to raise exceptions.

**Comment by bbatsov** [comment]
Perhaps, I don't have any time to research this. If someone else would like to tackle it - be my guest. :-)

**Comment by vemv** [comment]
These days, ex-data is printed nicely:

<img width="585" alt="image" src="https://github.com/clojure-emacs/cider/assets/1162994/0233e7f3-0fca-4cf4-abaf-0f9d5b8a5069">
