### ISSUE TITLE
pprinting expressions _always_ uses window width as *print-right-margin*

### ISSUE THREAD

**Issue by cemerick** [clojure-emacs/cider#1876]
I have my splits around 120 columns each, so this is really not what I want: 120 columns pretty-printed isn't very…pretty. At least IMO.

It'd be nice to be able to disable the binding of `*print-right-margin*`, or set it at some fixed width in cider. Absent that, here's what I'm using:

``` emacs
; don't pprint wider than 80 columns, regardless of the width of the current split
(let ((-cider--pprint--orig (symbol-function 'cider--nrepl-pprint-request-plist)))
  (defun cider--nrepl-pprint-request-plist (right-margin &optional pprint-fn)
    (funcall -cider--pprint--orig 80 pprint-fn)))
```

(Go ahead, make fun of my elisp, I care not.)

**Comment by bbatsov** [comment]
It will be pretty easy to add some defcustom that would override the current default.

**Comment by dpsutton** [comment]
Should we obey the `fill-column` variable in emacs and just ignore this completely?

**Comment by cemerick** [comment]
Makes sense to me, especially given high DPI screens, etc.

**Comment by dpsutton** [comment]
I think this can be closed now.
