### ISSUE TITLE
Emacs cider hangs after loading incanter's stats library. 

### ISSUE THREAD

**Issue by malloc82** [clojure-emacs/cider#1878]
I  was trying to use [incanter](https://github.com/incanter/incanter)'s stats library. You usually do this by adding this in ns form:
```clojure
(ns example.core
   (:use ...)
   (:require ...
             [incanter.core :as incanter]
             [incanter.charts :as charts]
             [incanter.stats :as stats]
             ...))
```
When I use cider 0.13.0, ```[incanter.stats :as stats]``` will cause emacs to hang and become non responsive. This is not the case with cider 0.12.0. I'm not sure what's happening, since there is no error nor any messages printed out. 

Incanter's other libraries loads fine. In the example above, I can load both core and charts without any issue.

I have already filed a bug report on incanter's repo as well. 

## Expected behavior
I expect the library to load without any issue.

## Actual behavior
Emacs hangs, use 100% CPU time on the core it's running on.

## Steps to reproduce the problem
- Create a new project using lein
- Add the following to your dependencies:
```clojure
:dependencies [[org.clojure/clojure "1.8.0"]
                 [incanter/incanter-charts "1.9.1"]
                 [incanter/incanter-core   "1.9.1"]]
```
- In a clojure source file, have the following:
```clojure
(ns example.core
  (:use clojure.core)
  (:require [incanter.core   :as incanter]
            [incanter.charts :as charts]
            [incanter.stats :as stats]))
```
- Start a dedicated repl in terminal, and connect to it.
- Evaluate the ns form with C-c C-c

At this point, emacs should hang and become non responsive. However, if you go to the repl, you can see that everything works fine there, and the library is loaded, including the stats. You can verify this by changing to the namespace, then evaluate the following:
```clojure
(stats/sd [1 2 3 4 5])
```
If you open another emacs, and try to connect to the same repl, emacs will hang right away. 

However, if you remove the line ```[incanter.stats :as stats]```, and repeat the process. Then everything is fine.

Also if you change both cider-nrepl and cider to version 0.12.0, and repeat the above process, emacs will evaluate the form without any  issue.

## Environment & Version information
- RedHat Enterprise Linux 6.5
- Emacs-25.1
- cider 0.13.0
- cider-nrepl 0.13.0

### CIDER version information
```
;; CIDER 0.13.0 (California), nREPL 0.2.12
;; Clojure 1.7.0, Java 1.8.0_102
```

### Lein/Boot version

Lein 2.7.1

### Emacs version

25.1

### Operating system

- RedHat Enterprise Linux 6.5

**Comment by bbatsov** [comment]
Is this an issue with CIDER 0.14 as well?

**Comment by malloc82** [comment]
Just realize that latest is 0.14 not 0.13. I've actually been using 0.14 on my mac at home which runs fine, does not have this problem. However, when I fallback the version to 0.13 on mac, it still does not have this problem. So it's probably has something to do with something else as well. 

I'll verify 0.14 tomorrow when I get back to the RedHat box.

**Comment by malloc82** [comment]
Yup,the problem went away with 0.14.
