### ISSUE TITLE
Cider removed `cider-compat.el` which appears to have removed support for emacs 24.x not 24.3

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/cider#1882]
## Expected behavior
CIDER should be able to jack in

## Actual behavior

`cider-add-to-alist: Invalid function: (cons (assoc car alist))` is the error message.

This can be seen from the build logs

https://api.travis-ci.org/jobs/177236922/log.txt?deansi=true

```
cider.el:812:1:Warning: the following functions are not known to be defined:
    when-let, if-let, exact-buff
Wrote /home/travis/build/clojure-emacs/cider/cider.elc
Compiling /home/travis/build/clojure-emacs/cider/cider-util.el...


In cider-add-to-alist:
cider-util.el:338:39:Warning: `(cons (assoc car alist))' is a malformed
    function
cider-util.el:348:15:Warning: reference to free variable `cons'
```

I believe that `cider-compat.el` was removed and `subr-x.el` was included thinking this included `if-let`. However, while `subr-x.el` exists on emacs 24.4+, it does not include the macros `if-let`. I believe that this commit mistakenly moved support for emacs to 25+.

## Steps to reproduce the problem

Install CIDER from elpa for git in emacs 24.4.
The build logs from https://travis-ci.org/clojure-emacs/cider/builds/177236920 support this as well

**Comment by tommy-mor** [comment]
getting this problem as well, on v 24.5

**Comment by bbatsov** [comment]
Ops, guess I forgot those macros were added later. I guess by Emacs 26 your actually mean 25. :-)

**Comment by tommy-mor** [comment]
I installed emacs from github using the --HEAD flag in homrbrew, and when I ckeck the version it says v 26. I guess that makes me somewhere in between
