### ISSUE TITLE
How to rewrite call to nrepl-send-string-sync to use new api

### ISSUE THREAD

**Issue by sooheon** [clojure-emacs/cider#1887]
This is not a bug but a question:

The slam hound package uses the old api of nrepl-send-string-sync [here](https://github.com/technomancy/slamhound/blob/master/slamhound.el#L60) How should this be updated to call the new api?

**Comment by bbatsov** [comment]
You should use `cider-nrepl-sync-request:eval`.

**Comment by bbatsov** [comment]
I'll close this ticket now - feel free to reopen it if you have more questions. Guess `slamhound.el` can be updated a bit more in general, although all updates should be trivial. To my knowledge all of its important functionality is now in `clj-refactor.el` - @benedekfazekas and @expez can confirm this.

**Comment by gavinmbell** [comment]
Can someone post the patch?

**Comment by bbatsov** [comment]
Which patch? For `slamhound.el`?

**Comment by gavinmbell** [comment]
Hey @bbatsov Pardon... I am just not understanding... I have a problem getting slamhound working with emacs.  It tells me: `plist-get: Symbol’s function definition is void: nrepl-send-string-sync`

This is all I can see:
%> ag nrepl-send-string-sync
slamhound-20140506.1618/slamhound.el
61:         (result (plist-get (nrepl-send-string-sync code) :stdout)))

So essentially I am asking... how do I do 'cider-nrepl-sync-request:eval' as you mentioned above?
You are saying s/nrepl-send-string-sync/cider-nrepl-sync-request:eval/ in slamhound.el ?
Is that literally it? (my elisp is not so good)

Any help you can provide would be appreciated
:-)

**Comment by bbatsov** [comment]
> You are saying s/nrepl-send-string-sync/cider-nrepl-sync-request:eval/ in slamhound.el ?

Yes, in theory that should be enough.
