### ISSUE TITLE
Ignore next form breaks with keyword namespace alias

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/cider#1890]
## Expected behavior

Evaluating the following code with `cider-eval-buffer` should be a no-op.

```clojure
#_(defn foo
    [x]
    ::bar/baz)
```

This is true of the following:

```clojure
;; (defn foo
;;   [x]
;;   ::bar/baz)
```

## Actual behavior

The following exception is thrown:

```
 Caused by java.lang.RuntimeException
   Invalid token: ::bar/baz

                 Util.java:  221  clojure.lang.Util/runtimeException
           LispReader.java:  390  clojure.lang.LispReader/interpretToken
           LispReader.java:  283  clojure.lang.LispReader/read
           LispReader.java: 1200  clojure.lang.LispReader/readDelimitedList
           LispReader.java: 1049  clojure.lang.LispReader$ListReader/invoke
           LispReader.java:  263  clojure.lang.LispReader/read
           LispReader.java:  200  clojure.lang.LispReader/read
           LispReader.java:   40  clojure.lang.LispReader/access$200
           LispReader.java:  595  clojure.lang.LispReader$DiscardReader/invoke
           LispReader.java:  691  clojure.lang.LispReader$DispatchReader/invoke
           LispReader.java:  263  clojure.lang.LispReader/read
           LispReader.java:  196  clojure.lang.LispReader/read
             Compiler.java: 7374  clojure.lang.Compiler/load
                      REPL:    1  user/eval20180
                      REPL:    1  user/eval20180
             Compiler.java: 6927  clojure.lang.Compiler/eval
             Compiler.java: 6890  clojure.lang.Compiler/eval
                  core.clj: 3105  clojure.core/eval
                  core.clj: 3101  clojure.core/eval
                  main.clj:  240  clojure.main/repl/read-eval-print/fn
                  main.clj:  240  clojure.main/repl/read-eval-print
                  main.clj:  258  clojure.main/repl/fn
                  main.clj:  258  clojure.main/repl
                  main.clj:  174  clojure.main/repl
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  646  clojure.core/apply
                  core.clj:  641  clojure.core/apply
                regrow.clj:   18  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  646  clojure.core/apply
                  core.clj: 1881  clojure.core/with-bindings*
                  core.clj: 1881  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run
```

No exception is thrown when evaluating from `lein repl`.

## Steps to reproduce the problem

1. Create a new project with `lein new`
2. Start CIDER.
2. In `core.clj`, add the problematic form.
3. Call `cider-eval-buffer`

### CIDER version information

```
CIDER 0.15.0snapshot (package: 20161016.424)
CIojure `1.8.0`
```

### Lein/Boot version

```
Leiningen 2.7.0 on Java 1.8.0_102 Java HotSpot(TM) 64-Bit Server VM
```

### Emacs version

```
25.1
```

### Operating system

```
Darwin C02RW05YFVH6 15.6.0 Darwin Kernel Version 15.6.0
```

**Comment by dpsutton** [comment]
I am able to recreate this in just plain `lein repl`.
![lein_repl](https://cloud.githubusercontent.com/assets/6377293/21491897/8f48072a-cbc5-11e6-946b-dd8123d8c284.png)

If I'm not mistaken, the difference in #_ reader and comments is that the #_ syntax must be valid. In 1.8, this appears to not be valid. I'm not sure that there is a bug here?

**Comment by xiongtx** [comment]
The image you linked to does not show the use of `#_` syntax. Am I missing something?

**Comment by dpsutton** [comment]
You are right! I thought I had run it with the ignore next form syntax but it was in CIDER that I had run it. I'm starting to look into it. My current suspicion is its in bencode or something but there's no telling.  I'm suspecting that we use `:` as a separator of byte length from string and the double `:` is confusing a decoding step. But that is not really based on anything and just my first avenue.

**Comment by dpsutton** [comment]
I really can't figure out what's going on. Doesn't seem to be any rhyme or reason to it:
![screenshot from 2016-12-27 23-45-56](https://cloud.githubusercontent.com/assets/6377293/21514797/b849907a-cc8e-11e6-8b1b-1cca6798d331.png)

**Comment by xiongtx** [comment]
Regular `lein repl` throws an exception with `#_ (defn foo [x] blah ::)`:

```
RuntimeException Invalid token: ::  clojure.lang.Util.runtimeException (Util.java:221)
RuntimeException Unmatched delimiter: )  clojure.lang.Util.runtimeException (Util.java:221)
```

and `#_ (defn foo ^)`:

```
RuntimeException Unmatched delimiter: )  clojure.lang.Util.runtimeException (Util.java:221)
```

I think the takeaway here is that the form after `#_` needs to be a "valid" form in the sense that variables obey naming constraints (e.g. `$` is OK in name but `^` is not, `::foo` is OK but `::` is not). After all, the reader needs to read it so it can where the form begins/ends.

**Comment by xiongtx** [comment]
Surprisingly, **the behavior of CIDER seems to be that of regular Clojure REPL, but not Lein repl**.

### Clojure REPL

```
$ java -cp /home/txx/.m2/repository/org/clojure/clojure/1.8.0/clojure-1.8.0.jar clojure.mainClojure 1.8.0
user=> #_ ::foo/bar
RuntimeException Invalid token: ::foo/bar  clojure.lang.Util.runtimeException (Util.java:221)
```

### CIDER REPL

```
user> #_ ::foo/bar
RuntimeException Invalid token: ::foo/bar  clojure.lang.Util.runtimeException (Util.java:221)
```


### Lein repl

```
$ lein repl
nREPL server started on port 45383 on host 127.0.0.1 - nrepl://127.0.0.1:45383
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_111-b16
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> #_ ::foo/bar

```

So either the Lein REPL uses a different reader, or it swallows the exception that's throw with `#_ ::foo/bar`.

**Comment by dpsutton** [comment]
The specs from http://clojure.org/reference/reader state

> Ignore next form (#\_)
> The form following #\_ is completely skipped by the reader. (This is a more complete removal than the comment macro which yields nil).

I was looking at lein to see if they ignore those things and don't even send them to tools.nrepl. As far as I can tell, we aren't getting a bug in any of the cider-nrepl middleware but in the reader. So this is either a) intended behavior or b) a bug in tools.nrepl. But I kinda can't get a straight answer on if this _should_ be a bug or not.

**Comment by dpsutton** [comment]
@xiongtx from the clojure repl, do you get an error on the ignore next form version? ie, `#_ (defn foo [x] ::foo/bar)`

**Comment by dpsutton** [comment]
> The CIDER repl seems to be doing more than the lein repl by trying to resolve keywords like ::foo/bar, which is why we get:

The CIDER repl doesn't do anything really. It bencodes the code and sends it off to Clojure. I was looking to see if the encoding was incorrect but it seems correct. That's why my suspicion is that lein repl is ignoring things on its own and not even showing it to the reader. But per conversations on slack, 

> the code behind #_ is literally:
``` 
 data = rdr.read()
  return nil
```
So it seems like it should be possible to throw an error in read even if we get nothing back. I'm still not sure if this should be an error or should be ignored.

**Comment by xiongtx** [comment]
> from the clojure repl, do you get an error on the ignore next form version? ie, `#_ (defn foo [x] ::foo/bar)`

Yes, I do.

```
user=>  #_ (defn foo [x] ::foo/bar)
RuntimeException Invalid token: ::foo/bar  clojure.lang.Util.runtimeException (Util.java:221)
RuntimeException Unmatched delimiter: )  clojure.lang.Util.runtimeException (Util.java:221)
```

**Comment by dpsutton** [comment]
So i suppose CIDER does the correct thing then?

**Comment by xiongtx** [comment]
> Since it's the Lein REPL that differs from the Clojure REPL, we may simply say that this is expected behavior. I'd be interested in knowing why the Lein REPL behaves differently, however.

We could say that, but I wonder what's the *intended* behavior--*should* `#_` throw an error when encountering undefined keywords or not?

**Comment by dpsutton** [comment]
My thinking is that if this is a bug, its a bug in Clojure, either tools.nrepl or the reader itself. I wouldn't want to add a bug fix for something in Clojure and then remove it when their bug is fixed, if this is indeed a bug. I think CIDER's goal should be to faithfully send your stuff to clojure, which it is doing here. If that is an error, then that is invalid Clojure code, from my view. I wouldn't want CIDER to modify clojure code.

**Comment by xiongtx** [comment]
Sounds reasonable.
