### ISSUE TITLE
specify clojure version does not work for CIDER

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#1891]
**Remove all of the placeholder text in your final report!**

## Expected behavior

I set options:

```elisp
(setq cider-jack-in-auto-inject-clojure "1.9.0-alpha12"
      cider-latest-clojure-version "1.9.0-alpha12"
      cider-minimum-clojure-version "1.8.0")
```

Hope CIDER will use Clojure version 1.9.0.

## Actual behavior

I check out clojure version with `(clojure-version)`, it still is `1.8.0`.

## Steps to reproduce the problem

I use minimal Emacs config with `emacs -q -l minimal-init.el`.
Here is my `minimal-init.el`:

```elisp
;;; add my init files directory
(let ((default-directory "~/.emacs.d/init/"))
  (setq load-path
        (append
         (let ((load-path (copy-sequence load-path))) ; shadow
           (append
            (copy-sequence (normal-top-level-add-to-load-path '(".")))
            (normal-top-level-add-subdirs-to-load-path)))
         load-path)))

;;; [ package.el ]
(require 'cl)
(require 'package)
(setq package-menu-async t)
(setq package-user-dir "~/.emacs.d/elpa")
(setq-default package-archives
              '(("org"   . "http://orgmode.org/elpa/")
                ("melpa" . "http://melpa.org/packages/")
                ;; ("melpa-stable" . "http://stable.melpa.org/packages/")
                ;; ("marmalade" . "http://marmalade-repo.org/packages/")
                ("gnu" . "https://elpa.gnu.org/packages/")
                ))

(package-initialize)

;;; [ use-package ]
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package cider
  :ensure t
  :config
  (setq cider-auto-mode t
        ;; versions
        cider-jack-in-auto-inject-clojure "1.9.0-alpha12"
        cider-latest-clojure-version "1.9.0-alpha12"
        cider-minimum-clojure-version "1.8.0"
        ;; cider-required-nrepl-version "0.2.12"

        ;; REPL
        cider-inject-dependencies-at-jack-in t
        cider-repl-display-in-current-window nil
        cider-repl-pop-to-buffer-on-connect nil
        
        ;; multiple connections
        cider-request-dispatch 'dynamic

        ;; project
        cider-prompt-for-project-on-connect 'when-needed
        )

  ;; auto start CIDER jack-in.
  (setq cider-allow-jack-in-without-project t)
  (add-hook 'after-init-hook #'cider-jack-in)
  )
```

### CIDER version information

```
;; CIDER 0.15.0snapshot (package: 20161201.757), nREPL 0.2.12
;; Clojure 1.9.0-alpha12 (installed in leiningen profile), Java 1.8.0_102
```

### Lein/Boot version

`Leiningen 2.7.0 on Java 1.8.0_102 Java HotSpot(TM) 64-Bit Server VM`

### Emacs version

`GNU Emacs 25.1.1`

### Operating system

Arch Linux: `kernel 4.8.13-1-ARCH`

**Comment by bbatsov** [comment]
@benedekfazekas Can you take a look at this?

**Comment by expez** [comment]
@stardiviner Please read the docstring for these variables, you're using every one of them in the wrong manner.

To get the result you want, reset these variables to their default and put the right clojure version in `project.clj`.

**Comment by bbatsov** [comment]
@expez Are you sure about this?

```
If nil, do not inject clojure into the REPL.  If ‘latest’, inject
‘cider-latest-clojure-version’, which should approximate to the most recent
version of clojure.  If ‘minimal’, inject ‘cider-minimum-clojure-version’,
which will be the lowest version cider supports.  If a string, use this as
the version number.  If it is a list, the first element should be a string,
specifying the artifact ID, and the second element the version number.
```

**Comment by expez** [comment]
Sorry, I was a bit hasty myself.  The first variable is used correctly, to override the version in `project.clj`, but the other two variables or not.

The minimum clojure version is updated by us to indicate what we require and we use that to produce warnings / disable middleware.

The latest clojure version variable is also updated by us, to indicate what we've tested against.

You can see in the output from CIDER in the REPL, in the OP, that everything works as it should:

```
;; CIDER 0.15.0snapshot (package: 20161201.757), nREPL 0.2.12
;; Clojure 1.9.0-alpha12 (installed in leiningen profile), Java 1.8.0_102
```

I'm not sure why the parenthetical statement "installed in leiningen profile" was added, but if you're overriding the existing value with the same value you can be doubly sure you'll get the same result...

**Comment by expez** [comment]
I tested this on a fresh project created by `lein new test` just to be sure.

`core.clj` and did:

`(setq-local cider-jack-in-auto-inject-clojure "1.9.0-alpha12")` and then `cider-jack-in`


### project.clj

```clj
(defproject test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]])
```

### REPL output
```
;; Connected to nREPL server - nrepl://localhost:46831
;; CIDER 0.15.0snapshot (package: 20161201.757), nREPL 0.2.12
;; Clojure 1.9.0-alpha12, Java 1.8.0_112
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
user> (clojure-version)
1.9.0-alpha12
user> 
```

**Comment by stardiviner** [comment]
@expez with your steps, I tested ok. Thanks. I will find it out why my previous steps are wrong.

**Comment by stardiviner** [comment]
@expez I found specifying Clojure version for CIDER with variable `cider-jack-in-auto-inject-clojure "1.9.0-alpha12"`, but it still failed, when I start CIDER without in project.
The `*Messages*` buffer shows command `cider-jackin` does start command with my specified clojure version, here is the output:

```
Starting nREPL server via /home/stardiviner/bin/lein update-in :dependencies conj \[org.clojure/clojure\ \"1.9.0-alpha12\"\] -- update-in :dependencies conj \[acyclic/squiggly-clojure\ \"0.1.6\"\] -- update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.15.0-SNAPSHOT\"\] -- repl :headless...
```

But `(clojure-version)` still shows `1.8.0`. That's weird.

**Comment by expez** [comment]
> When I start CIDER without in project.

Doesn't work when you're not in a project.

**Comment by bbatsov** [comment]
I think this was some leiningen bug. @benedekfazekas should know more.

**Comment by expez** [comment]
> I think this was some leiningen bug. 

`update-in` affords updates to the project map, so I guess an argument can be made that outside a project updates should be made to the default project map.
