### ISSUE TITLE
Restarting a repl does not connect to same port

### ISSUE THREAD

**Issue by bostonaholic** [clojure-emacs/cider#1895]
## Expected behavior

`cider-restart` should connect to the same `host:port` as when I used `cider-connect`.

1. `cider-connect` to connect to a repl running on `localhost:6005`.
2. Then call `cider-restart`.
3. The new repl should connect to `localhost:6005` as before.

## Actual behavior

`cider-restart` seems to use `cider-jack-in` instead, and does not connect to the repl running on `localhost:6005`.

**Comment by bbatsov** [comment]
This should be easy to implement. I wonder why no one noticed it for so long. :-)

**Comment by xiongtx** [comment]
Should we change `cider-jack-in` to read the `.nrepl-port` file? Or use a different command?

**Comment by bbatsov** [comment]
> Should we change cider-jack-in to read the .nrepl-port file?

Not sure how this is related. We simply need to remember the old connection port prior to restarting the REPL (this should do `jack-in` at all but simply do `cider-connect` again).

**Comment by xiongtx** [comment]
> Not sure how this is related. 

[`cider-restart`](https://github.com/clojure-emacs/cider/blob/master/cider-interaction.el#L1747) calls [`cider--restart-connection`](https://github.com/clojure-emacs/cider/blob/master/cider-interaction.el#L1732), which calls [`cider-jack-in`](https://github.com/clojure-emacs/cider/blob/master/cider.el#L501).

**Comment by bbatsov** [comment]
I'm aware of this. :-) But the actually fix would involve tagging connections with some marker denoting how they were created (using jack-in or connect) and in the case of the latter just re-invoking `cider-connect` for the appropriate host/port. That's why I was curious how `cider-jack-in` plays into this ticket.
