### ISSUE TITLE
Feature request: integration with `clojure.spec`

### ISSUE THREAD

**Issue by viebel** [clojure-emacs/cider#1901]
It would be super cool to provide an integration of `cider` with `clojure.spec`

For instance a cider command that calls `spec/exercise` on the form preceding point or `spec/exercise-fn` on the function name preceding point.

And maybe other spec functions.

What do you think?

**Comment by johngit22** [comment]
Very Nicely Stated

**Comment by bbatsov** [comment]
Yeah, that'd be nice for sure. I haven't played with `clojure.spec` at all by this point - was waiting for a final release of Clojure 1.9 before looking into it. If someone has good ideas about spec-related functionality at this point - you're welcome to start working on it. //cc @dpsutton @cskksc

**Comment by dpsutton** [comment]
I can start looking into it, but I haven't touched spec yet at all. I'm surprised at how much production software seems to be running on beta versions of Clojure. I've been waiting for them to release 1.9 officially.

**Comment by viebel** [comment]
@dpsutton let me know if you need help with spec. 

BTW, I wrote a [tutorial](http://blog.klipse.tech/clojure/2016/05/30/spec.html) of `clojure.spec` with interactive code snippets powered by [KLIPSE](https://github.com/viebel/klipse).

**Comment by bbatsov** [comment]
> I'm surprised at how much production software seems to be running on beta versions of Clojure.

You and me both. :-)

**Comment by bbatsov** [comment]
#1918 and #1919 are two related tickets that should be pretty easy to implement.

**Comment by bbatsov** [comment]
@dpsutton any progress with this?

**Comment by dpsutton** [comment]
@bbatsov no, actually none at all. I still haven't even messed with spec. I've been doing other things and waiting for a non-beta, but I guess it's getting to the point where I need to start learning. I'd like to finish up the cleanup of startup and then dive into this.

**Comment by bbatsov** [comment]
Got it.

**Comment by jpmonettas** [comment]
@bbatsov @expez Current spec browser implementation supports spec sample creation, keep hitting e on the spec browser when looking at any spec and you should see a pprint of that.
Nothing for excercise-fn yet.

**Comment by bbatsov** [comment]
Closing this for now, as we already have some support for spec now. Hopefully someone will find the time and the energy to improve it.
