### ISSUE TITLE
cider-show-spec

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1919]
`cider-show-spec` shows the definition for some spec.

* Completing read among all specs in `(keys (s/registry)`, defaulting to the keyword at point, to make it easier to select which spec definition to show.
* Popup buffer with the spec definition (found by calling `(s/form (s/get-spec :my-spec))`).

Bonus points if you can click to view the definitions of any constituent specs in the popup buffer.

**Comment by bbatsov** [comment]
You should be more specific about the feature request. I've got a feeling I understand what you mean, but neither the title nor the description of this ticket is very clear.

**Comment by bbatsov** [comment]
P.S. I'd probably name this command differently.

**Comment by expez** [comment]
I've tried to make it a little bit clearer, and picked another name.

I've sprinkled in the details about how to acquire the information needed, to do a completing read among the specs to show, as well as how to get ahold of the spec definition.  Not everyone is familiar with spec, so that hopefully makes the ticket easier to close.

**Comment by bbatsov** [comment]
@jpmonettas Guess this command is upcoming. Should be trivial to implement now that the groundwork has been created.

**Comment by jpmonettas** [comment]
> Guess this command is upcoming. Should be trivial to implement now that the groundwork has been created.

The description of that command is exactly `cider-browse-spec`, should we create an alias?

**Comment by bbatsov** [comment]
> The description of that command is exactly cider-browse-spec, should we create an alias?

Not really. It should simply present you a completing list of all the specs and you should jump to one of those - not need for a filtering regex or a browser from which to see the spec. Or if supports a filter regex it should behave exactly like `cider-apropos-select`.

**Comment by jpmonettas** [comment]
As it is now, `cider-browse-spec` doesn't ask you for a regex, just let you write a spec name with autocompletion and once you hit RET shows you that selected spec in the browser so you can navigate deep into sub specs.

The command that ask you for a regex and sends you to the browser with the listing is `cider-browse-spec-all`

If you think this is confusing we can change the naming.

**Comment by jpmonettas** [comment]
@bbatsov @expez Is there something still to be done here? I think `cider-browse-spec` does exactly what the issue description says plus the bonus.

**Comment by xiongtx** [comment]
@bbatsov Think this can be closed thanks to @jpmonettas's work.
