### ISSUE TITLE
Spec discovery

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#1924]
When I left Haskell for Clojure one of the things I missed was [Hoogle](https://www.haskell.org/hoogle/).  Hoogle, and tools like it, lets you search by function signature and types in order to find functions that might interest you.

It would be helpful to be able to query the spec registry to find all functions that use some spec.  E.g. I might want to find all the functions that deal with a `User`.

**Comment by bbatsov** [comment]
> It would be helpful to be able to query the spec registry to find all functions that use some spec. E.g. I might want to find all the functions that deal with a User.

Some more details about the functionality you have in mind would be useful.

**Comment by expez** [comment]
> Some more details about the functionality you have in mind would be useful.

**Comment by jpmonettas** [comment]
I started working on spec stuff(spec browser) and was looking at this, but given that function specs are not mandatory I don't know if this is a useful feature.
I mean, maybe there are a bunch of functions that works with :my/spec but they will not be listed because they don't have a spec.

**Comment by expez** [comment]
> I started working on spec stuff(spec browser) and was looking at this, but given that function specs are not mandatory I don't know if this is a useful feature.

Plenty of users have enough discipline (or their boss mandates it) to make this useful.  At work we put specs on all public functions and in our experience the effort pays for itself many times over.  We did this first with schema and am now in the process of migrating everything over to clojure.spec.

There's also a positive feedback loop here between features like this and adding specs that I think is excellent.  The more you spec the better tooling you get causing you to spec even more.

**Comment by jpmonettas** [comment]
@expez make sense to me.
 
I'll be making a pull request shortly with what I have related to specs browsing and will try to add that functionality after. It shouldn't be hard.

**Comment by jmckitrick** [comment]
Should this issue be closed based on the merges made above?

**Comment by xiongtx** [comment]
This should be addressed by #2025.
