### ISSUE TITLE
[exceptions] Potential improvement for `*cider-error*` buffers

### ISSUE THREAD

**Issue by harold** [clojure-emacs/cider#1929]
[Prone](https://github.com/magnars/prone) is a helpful library for debugging clojure/ring web applications.

A great feature of Prone is their display of stack traces, a lot of typically useless and distracting information is elided. I was reading about how they achieved that:
https://github.com/magnars/prone#how-does-prone-determine-what-parts-of-a-stack-trace-belongs-to-the-application

(they do some sort of filtering on the namespaces)

I wonder if something similar would be possible/good in Cider? The existing stacktrace/error functionality is sophisticated, useful, and a key part of my day to day work already; but I think additional filtering could still help.

Thanks again for Cider, I can't mention enough how lovely and great it is.

**Comment by bbatsov** [comment]
Basically you want some toggle that just displays only the application stack frames?

**Comment by harold** [comment]
Yes. Does that sound right to you?

**Comment by bbatsov** [comment]
Yeah, it does. As we already have a filtering mechanism in place I'm assuming that extending it to account just for application frames should be easy.

**Comment by dpsutton** [comment]
The pull request to cider-nrepl above will flag frames with 'project.

Adding a filter in the method of the others does not accomplish what we want though. They are negative filters in the sense that they remove frames marked with the symbol given. We need a different notion of a filter that removes the _complement_ of the button hit. Shouldn't be hard but doesn't just plug right in. I'll get on this as soon as the clojure side pull request is up to snuff and accepted.

**Comment by harold** [comment]
Mmm, I like where this is headed. Let me know if there's more I can do to help.

**Comment by xiongtx** [comment]
@dpsutton Hasn't the "negative" filter been implemented as `Show` instead of `Hide`?

![image](https://user-images.githubusercontent.com/1624090/37394285-96f9985e-2730-11e8-8b99-6ab214d2f0be.png)

@harold Can this be closed?

**Comment by harold** [comment]
Woah. I just clicked `Project-Only` for the first time, and good things happened! Great work, all.

I will experiment with this more in more real-world use and see how it goes.

I have no problem closing this, future thoughts can be put into new issues.

Thanks again all.
