### ISSUE TITLE
Put an upper limit on the amount of data the cider repl is willing to print to buffer when it prints rv

### ISSUE THREAD

**Issue by SlightlyCyborg** [clojure-emacs/cider#1934]
If I accidentally call a fn that returns an enormous amount of data, it kills my repl

**Comment by expez** [comment]
I have a similar problem when running my tests and getting a `clojure.spec` failure.  It's never caused my REPL to fail, but it does slow things down.

When clojure spec encounters a problem it dumps the complete datastructure to `*out*`, along with a path into that datastructure which describe where the spec failed.  Needless to say when working with large datastructures this isn't optimal.

I find this behavior in `clojure.spec` sub-optimal in general as I'm usually not interested in anything but `val` (the leaf node that failed the spec) and the `path` which describes where in the original datastructure the problematic value is.

**Comment by bbatsov** [comment]
One of those days we should really invest some time in profiling the REPLs performance so we can remove at least some of the causes for these freezes. That's the only **real** solution to the problem at hand, everything else is mere patchwork. 

I don't see a good user experience for what you're suggesting. Should we display some warning if we're about to generate excessive output? Constantly checking the buffer size and the limit is also going to produce some (hopefully small) slowdown. What you ask for is certainly doable, but I do wonder good of an idea it is overall.

**Comment by SlightlyCyborg** [comment]
If it generates data over a certain length, perhaps we inject it into a web
page and give a link

**Comment by bbatsov** [comment]
I'll think what we can do about this.

**Comment by behrica** [comment]
I somehow thing that the 2 existing variables to control the max output size,
so "cider-repl-print-length" and "cider-repl-print-level" are not enough.

Sometimes I return "by accident" a very large single strings from my methods, which can crash Emacs.
So a single String of some megabytes gets returned by a function and emacs tries to print it.

I thought that eventually this could be solved inside of any of the "pretty printer" libraries we can use in cider already know.
I saw the source code of "fipp" for example here:
https://github.com/brandonbloom/fipp/blob/master/src/fipp/engine.cljc#L16

This is the line which converts a given text to a String via the "str" function.

If we would limit the size of any single String here, we might some to a solution that achieves a nearly 100% guaranty of not print "too large" output by  limiting on all three levels:

- print-length
- print-level
- length of a single string

So this "max-string-length" could become a optional parameter of the fipp library.

**Comment by behrica** [comment]
I have thought about an other "work-arround" for this proble, which could be usefull.

I defined my self a little function "pr-info" , which prints a small summary on every clojure datastructure.
(which keys, if map; how long if sequence; it shortens strings)

```
(defn shorten-string [s]
  (if (> (count s) 1000)
    (str (.substring s 0 1000) " ...")
    s)
  )

(defn info [x]
  (cond (string? x)   (shorten-string x)
        (map? x) (str "keys: "(keys x)) 
        (sequential? x) (str "count: " (count x))
        true x))

(defn pr-info [x]
  (print (info x))
  )

```
This guaranties that the output never becomes too long for emacs.

This I can then register as the "pretty print function" in cider:

```
(setq cider-pprint-fn "xxx/pr-info")
```

Like this, any data structure evaluated in the shell gets printed in this format.
In order to see then the data structure in full,
I either toggle cider pretty print ('cider-repl-toggle-pretty-print'),
or I evaluate "(print x)" in the repl.

It could be maybe interesting to add a new toggle to cider (cider-repl-toggle-summary-print),
which switches this in and off.

**Comment by gonewest818** [comment]
This looks like a duplicate of #1115, and work on a scheme to shorten long lines of output is underway. It's not exactly what you're proposing, though I think it will meet your need.

Incidentally, in my experience even setting up the default pretty printer, plus adjusting the *print-length* and *print-level* settings have helped me avoid lockups for the most part.

**Comment by behrica** [comment]
I found a working solution, which puts an upper limit on the length of data cider inserts into the repl for each command. For me the reason behind this is, that of I get a result of an evaluation larger the 1000 characters, I did a mistake anyway.

The following code monkey patches cider to restrict the result of an evaluation (success or error) to 1000 character.

It is a kind of last defense against the risk of freeze. I combine this typically with a solution to print only "shortened" individual strings as well.

see my comments on #1115 


```
(defun my/truncate-string (string)
  (if (< 1000 (length string))
      (concat (substring string 0 1000) " ...["  (number-to-string (length string)) "]"  )
    string))


(defun cider-repl-emit-result (buffer string show-prefix &optional bol)
  "Emit into BUFFER the result STRING and mark it as an evaluation result.
If SHOW-PREFIX is non-nil insert `cider-repl-result-prefix' at the beginning
of the line.  If BOL is non-nil insert at the beginning of the line."
  (with-current-buffer buffer
    (save-excursion
      (cider-save-marker cider-repl-output-start
	(cider-save-marker cider-repl-output-end
	  (goto-char cider-repl-input-start-mark)
	  (when (and bol (not (bolp)))
	    (insert-before-markers "\n"))
	  (when show-prefix
	    (insert-before-markers (propertize cider-repl-result-prefix 'font-lock-face 'font-lock-comment-face)))
	  (if cider-repl-use-clojure-font-lock
	      (insert-before-markers (cider-font-lock-as-clojure (my/truncate-string string)))
	    (cider-propertize-region
		'(font-lock-face cider-repl-result-face rear-nonsticky (font-lock-face))
	      (insert-before-markers (my/truncate-string string)))))))
    (cider-repl--show-maximum-output)))



(defun cider-repl--emit-output-at-pos (buffer string output-face position &optional bol)
  "Using BUFFER, insert STRING (applying to it OUTPUT-FACE) at POSITION.
If BOL is non-nil insert at the beginning of line.  Run
`cider-repl-preoutput-hook' on STRING."
  (with-current-buffer buffer
    (save-excursion
      (cider-save-marker cider-repl-output-start
	(cider-save-marker cider-repl-output-end
	  (goto-char position)
	  ;; TODO: Review the need for bol
	  (when (and bol (not (bolp))) (insert-before-markers "\n"))
	  (setq string (propertize (my/truncate-string string)
				   'font-lock-face output-face
				   'rear-nonsticky '(font-lock-face)))
	  (setq string (cider-run-chained-hook 'cider-repl-preoutput-hook string))
	  (insert-before-markers  string)
	  (cider-repl--flush-ansi-color-context)
	  (when (and (= (point) cider-repl-prompt-start-mark)
		     (not (bolp)))
	    (insert-before-markers "\n")
	    (set-marker cider-repl-output-end (1- (point)))))))
    (cider-repl--show-maximum-output)))
```
