### ISSUE TITLE
Unable to connect to the remote host with cider-connect

### ISSUE THREAD

**Issue by Freyr666** [clojure-emacs/cider#1935]
I use ssh connection with a non-standard port specified in ssh/config

After emacs packages upgrade i'm not able to connect to server anymore, it returnes

```
[nREPL] Establishing direct connection to srv:7000 ...
[nREPL] Direct connection failed
let*: Wrong type argument: processp, nil
```

I've tried to recompile elc files but the issue is still there.

Lein 2.7.1

GNU Emacs 25.1.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.22.4)
Fedora 25

Upd:

It seems that new version of nrepl-connect just returns an error after trying nrepl--direct-connect while the older versions call nrepl--ssh-tunnel-connect in case of nrepl--direct-connect failure. Msg log for the older versions:

```
[nREPL] Establishing direct connection to srv:7000 ...
[nREPL] Direct connection failed
[nREPL] Establishing SSH tunneled connection ...
[nREPL] SSH port forwarding established to localhost:7000
[nREPL] Establishing direct connection to localhost:7000 ...
[nREPL] Direct connection established
```

**Comment by dpsutton** [comment]
@Freyr666 can you help get me up and running with a minimum example that demonstrates? I cranked up a fizzbuzz `lein repl` and then cider connected to it from master. All of this over port 35083. Do you think this port number is important? Or can you help me get to a place where I can recreate the issue locally?

**Comment by Freyr666** [comment]
Well. I use nrepl-plugin on port 7000 fetched by lein luminus web template (http://www.luminusweb.net/docs/repl.md)

I have an ssh config file because sshd runs on non-default port:

```
Host srv
	HostName ip
	Port 1922
	User my_user
```

After updating package from melpa i get the `let*: Wrong type argument: processp, nil` error while with the backuped files everything works just fine.

**Comment by bbatsov** [comment]
> It seems that new version of nrepl-connect just returns an error after trying nrepl--direct-connect while the older versions call nrepl--ssh-tunnel-connect in case of nrepl--direct-connect failure. Msg log for the older versions:

See the changelog. Some people disliked the automated ssh fallback and it was disabled by default. There's a config option to enable it. Still, raising an error is definitely a bug. We should look into this. 

Can you post the complete backtrace?

**Comment by Freyr666** [comment]
Ok.

After `(setq nrepl-use-ssh-fallback-for-remote-hosts t)` the error still exists.

How could I see the complete backtrace?

I'm still getting
```
[nREPL] Establishing direct connection to srv:7000 ...
[nREPL] Direct connection failed
nrepl-start-client-process: Wrong type argument: processp, nil
```

**Comment by bbatsov** [comment]
This is the problematic code:

```el
(defun nrepl-start-client-process (&optional host port server-proc)
  "Create new client process identified by HOST and PORT.
In remote buffers, HOST and PORT are taken from the current tramp
connection.  SERVER-PROC must be a running nREPL server process within
Emacs.  This function creates connection buffer by a call to
`nrepl-create-client-buffer-function'.  Return newly created client
process."
  (let* ((endpoint (nrepl-connect host port))
         (client-proc (plist-get endpoint :proc))
         (host (plist-get endpoint :host))
         (port (plist-get endpoint :port))
         (client-buf (funcall nrepl-create-client-buffer-function endpoint)))

    (set-process-buffer client-proc client-buf)

    (set-process-filter client-proc 'nrepl-client-filter)
    (set-process-sentinel client-proc 'nrepl-client-sentinel)
    (set-process-coding-system client-proc 'utf-8-unix 'utf-8-unix)

    (process-put client-proc :string-q (queue-create))
    (process-put client-proc :response-q (nrepl-response-queue))
```

We'll have to debug it to see why is the `client-proc` nil, which causes the problem you're experiencing.

**Comment by bbatsov** [comment]
Yeah, the problem is that before my changes the code always returned some endpoint, but now it can return `nil` - although it shouldn't return `nil` when you've enabled the ssh fallback.

**Comment by bbatsov** [comment]
I finally got to fixing this. Please, let me know if it works properly now.
