### ISSUE TITLE
Cider fails to jack-in, complaining `-i` flag unknown option

### ISSUE THREAD

**Issue by ckampfe** [clojure-emacs/cider#1937]
## Expected behavior

Cider starts using Boot in response to the `cider-jack-in` command, while focused buffer is a file in a Boot project. In my case, the file is a `build.boot` file.

## Actual behavior

Cider errors out when running `cider-jack-in`.

This is the message that is in \*Messages\* after the failure:

```
Starting nREPL server via /usr/local/bin/boot -i "(require 'cider.tasks)" -d org.clojure/tools.nrepl\:0.2.12 -d refactor-nrepl\:2.3.0-SNAPSHOT -d cider/cider-nrepl\:0.15.0-SNAPSHOT cider.tasks/add-middleware -m refactor-nrepl.middleware/wrap-refactor -m cider.nrepl/cider-middleware repl -s wait...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Unknown option: "-i"
```

## Steps to reproduce the problem

- Open a file in a project that uses Boot.
- invoke `cider-jack-in`. (In my case this is in Spacemacs, so I run `, s i` to jack in)

### CIDER version information

```
Starting nREPL server via /usr/local/bin/boot -i "(require 'cider.tasks)" -d org.clojure/tools.nrepl\:0.2.12 -d refactor-nrepl\:2.3.0-SNAPSHOT -d cider/cider-nrepl\:0.15.0-SNAPSHOT cider.tasks/add-middleware -m refactor-nrepl.middleware/wrap-refactor -m cider.nrepl/cider-middleware repl -s wait...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Unknown option: "-i"
```

### Lein/Boot version

```
xcxk066$> boot -u
Retrieving maven-metadata.xml from https://clojars.org/repo/
#http://boot-clj.com
#Sat Feb 04 15:59:13 CST 2017
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.7.1
BOOT_CLOJURE_VERSION=1.9.0-alpha14
```

### Emacs version

```
GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-20
```

### Operating system

`OS X 10.12.3 "Sierra"`

```
xcxk066$> java -version
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (Zulu 8.19.0.1-macosx) (build 1.8.0_112-b16)
OpenJDK 64-Bit Server VM (Zulu 8.19.0.1-macosx) (build 25.112-b16, mixed mode)
```

**Comment by arichiardi** [comment]
About this, I would makes sure that `/usr/local/bin/boot` is using `2.7.1`, you could try to create a `boot.properties` file either in the project root or in `.$HOME/boot` (global) with the following in order to be sure:

```
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.7.1
BOOT_CLOJURE_VERSION=1.9.0-alpha14
```

**Comment by ckampfe** [comment]
@arichiardi can confirm that I had the `~/.boot/boot.properties` in place with the parameters you suggested prior to reporting

**Comment by ckampfe** [comment]
Ha! there was an old, old boot.properties that made its way into the project dir that was overrideing the global configuration :( Sorry for opening the ticket, thank you @arichiardi

**Comment by arichiardi** [comment]
No problem, I have had a couple of similar issues :smile: Feel free to close this if solved.
