### ISSUE TITLE
cider-jack-in-clojurescript no longer honors buffer local variable

### ISSUE THREAD

**Issue by plexus** [clojure-emacs/cider#1938]
This seems to be a regression in recent versions of CIDER. It's unfortunate, because setting `cider-cljs-lein-repl` in `.dir-locals.el` provided an elegant way to configure the CLJS repl on a per-project basis.

## Expected behavior

Having this as a `.dir-locals.el` in a project:

``` emacs-lisp
((nil . ((cider-cljs-lein-repl    . "(do (reloaded.repl/go) (user/cljs-repl))"))))
```

And calling `M-x cider-jack-in-clojurescript` from a buffer within that project, the ClojureScript REPL should be started using `(do (reloaded.repl/go) (user/cljs-repl))`.

## Actual behavior

The root value of `cider-cljs-lein-repl` is used, ignoring the dir-local/buffer-local value.

## Steps to reproduce the problem

clone [this repo](https://github.com/lambdaisland/redolist/), open `project.clj` in emacs, do `M-x cider-jack-in-clojurescript`. In the `*cider-repl CLJS redolist*` buffer, you should see the line

```
Garden: watching src/clj/css.clj
```

If you don't then this problem is still present.

## Environment & Version information

This worked at least until CIDER 0.13.0. After upgrading to 0.15.0-SNAPSHOT it no longer works.

### CIDER version information

```
;; CIDER 0.15.0snapshot (package: 20170129.1941), nREPL 0.2.12
;; Clojure 1.9.0-alpha14, Java 1.8.0_91
```

### Lein/Boot version

```
Leiningen 2.6.1 on Java 1.8.0_91 Java HotSpot(TM) 64-Bit Server VM
```
### Emacs version

```
26.0.50.1
```

### Operating system

Ubuntu 16.04.1 LTS

**Comment by julienfantin** [comment]
Possibly related to #1933 ?

@plexus does it work as expected if you manually set `cider-cljs-lein-repl` with `setq` for example?

**Comment by plexus** [comment]
That does sound like the same problem, since they are also setting `cider-cljs-lein-repl` through `.dir-locals.el`.

The problem is that the CLJS repl is getting created indirectly in a process handler, at which point the buffer context is no longer there.

I came up with this solution, not sure to call it a fix or a hack though :) should I turn it into a PR?

https://github.com/clojure-emacs/cider/compare/master...plexus:dir_local_cljs_repl_hack

**Comment by julienfantin** [comment]
Can't comment on whether this is a good fix or not, but I'll add that using `setq` works for me as well.

**Comment by arichiardi** [comment]
Oh wow, that was beyond me (an emacs noob) :smile:

**Comment by mahinshaw** [comment]
Setting up my dir-locals with the this
