### ISSUE TITLE
Cancel jack-in

### ISSUE THREAD

**Issue by aengelberg** [clojure-emacs/cider#1941]
When I `C-c M-j` I cannot cancel the jack-in operation (the `lein repl :headless` command) without closing Emacs until the REPL finishes starting up (then I can `C-c C-q`). I would like to be able to cancel during startup if I change my mind about starting the REPL.

**Comment by bbatsov** [comment]
So, basically you want to be able to `C-g` the jack-in process?

**Comment by aengelberg** [comment]
Correct

**Comment by bbatsov** [comment]
Guess we'll have to look into this - as the REPL is started as an async independent process I'm not quite sure if this is possible or not. Likely something would be possible, but I'm not sure if it'd be straightforward or not.

**Comment by bbatsov** [comment]
@vspinu In light of your recent work on the jack-in, what do you think would be the best way to tackle this?

**Comment by bbatsov** [comment]
Fair enough. Now that the REPL starts much faster than before probably it's not worth tackling this indeed. When it was taking 30+ seconds I can certainly understand why people might have wanted to interrupt the process. :)
