### ISSUE TITLE
Non-MELPA installation methods hinted by docs, but link is broken

### ISSUE THREAD

**Issue by erno** [clojure-emacs/cider#1942]
"The canonical way to install CIDER is via package.el (Emacs's built-in package manager), but plenty of other options exist (see the wiki)."

But the wiki link is broken and Googling doesn't seem to turn up manual installation hints either.

**Comment by erno** [comment]
I found the what I was looking for here:  https://cider.readthedocs.io/en/latest/hacking_on_cider/

**Comment by bbatsov** [comment]
Yeah, the wiki was killed a while ago, guess we should update the docs not to refer to it anymore.

**Comment by bbatsov** [comment]
I've extended the manual - it now includes instructions for manual installation and installation via el-get.
