### ISSUE TITLE
error in process filter: [nREPL] Direct connection failed

### ISSUE THREAD

**Issue by hanshuebner** [clojure-emacs/cider#1945]
`M-x cider-jack-in` fails to successfully connect to the leiningen subprocess in some cases.  I have been seeing this issue in a long time, on various machines and with a number of cider versions.   Sometimes, retrying the `M-x cider-jack-in` one or a few times helped.  Recently, when I was annoyed by this again, I tried to figure out what the problem could be by running `telnet localhost <the-port-number>` and found that telnet tried to connect to `::1` (ipv6 localhost), getting a "connection refused" message.  When I used `telnet 127.0.0.1 <the-port-number>` however, the connection was accepted.  It seems that the nrepl server only listens on ipv4 (maybe by using an explicit `127.0.0.1` address to listen on), but cider uses `localhost` as host name to connect.  Thus, it depends on the local systems' interpretation and name resolution configuration what address cider tries to connect to.

Bozhidar made the very good suggestion that the message could be improved to include information as to what connection actually failed.  Something like `[nREPL] could not connect to localhost:12345` would already give a hin in what direction one could investigate.

The connection between cider and the nrepl server should use the same host specification, I think.  Thus, if nrepl listens on `127.0.0.1` by default, cider should also use `127.0.0.1` and not `localhost` to avoid mismatches caused by name resolution.

**Comment by bbatsov** [comment]
We'll definitely improve those messages. As for the nREPL's behaviour - seems to me that it listens on `localhost` (see https://github.com/clojure/tools.nrepl/blob/fcac1e13d6f80eb0db28773247a769c1dc9659b1/src/main/clojure/clojure/tools/nrepl/server.clj#L125).

**Comment by hanshuebner** [comment]
The real fix is within tools.nrepl, as @bbatsov has pointed out.  The trick is to bind the socket to the anylocal address `::` instead of `localhost`, `127.0.0.1` or `::1`.  If done that way, the nrepl server accepts connections both to the IPv4 and IPv6 localhost address.  I will try to get this changed in tools.nrepl.

**Comment by bbatsov** [comment]
Great! Hopefully @cemerick will have time to apply your patch and issue a new release.

**Comment by hanshuebner** [comment]
As a workaround, `:repl-options {:host "::"}` can be specified in the user's profile to override the default in `tools.nrepl` until it is fixed there.

**Comment by bbatsov** [comment]
> As a workaround, :repl-options {:host "::"} can be specified in the user's profile to override the default in tools.nrepl until it is fixed there.

I've updated the connection messages. Maybe we should add this workaround to the global lein options in cider for the time being, as I doubt the nREPL patch would be merged any time soon.

**Comment by bbatsov** [comment]
@benedekfazekas do you know if we can pass this as a command line option to `lein` and `boot`?

**Comment by benedekfazekas** [comment]
should be possible, yes. with `lein` you can merge anything into the project map from the CLI and a quick look on boot repl options shows me:
```
-H, --host HOST       HOST sets the host client connects to.
```
this should do the trick for boot.

really busy but I might have time to give this a go over the weekend

**Comment by bbatsov** [comment]
I was just looking into this myself and found what I needed. In `lein` you can also do `lein repl :headless :host :port`. 

I'll likely just add those to the default commands. Seems like an overkill to add defcustoms for them.

**Comment by ryanswilson59** [comment]
@hanshuebner sorry for the noob question but how would one go about adding :repl-options {:host "::"} to their user profile

**Comment by hanshuebner** [comment]
This [blog post](https://world-in-atom.com/posts/2016-07-15-leiningen-profiles/) has an overview of leiningen profiles.

**Comment by saramsey** [comment]
> We'll definitely improve those messages. As for the nREPL's behaviour - seems to me that it listens on `localhost` (see https://github.com/clojure/tools.nrepl/blob/fcac1e13d6f80eb0db28773247a769c1dc9659b1/src/main/clojure/clojure/tools/nrepl/server.clj#L125).

Thank you, this hint was super helpful.
