### ISSUE TITLE
Add a command to quickly inspect the metadata for some var

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1953]
Often I find myself needing to check the metadata of some var. Usually I just use the REPL to do so, but it would definitely be easier there was an interactive command to help with this. 

Developing a command that simply displays the metadata in a window similar to the docview should be pretty simple. Alternatively the metadata can be displayed in doc buffers, but I think a dedicated view makes a bit more sense for this.

**Comment by xiongtx** [comment]
Something like the following should work:

```clojure
(defconst cider-metadata-buffer "*cider-metadata*")

(defun cider-metadata (&optional var)
  (interactive (list (cider-symbol-at-point)))
  (let* ((result-buffer (cider-popup-buffer cider-metadata-buffer t 'clojure-mode t))
         (handler (cider-popup-eval-out-handler result-buffer)))
    (cider-interactive-eval (format "(meta (var %s))" (concat (cider-current-ns) "/" var))
                            handler
                            nil
                            (cider--nrepl-pprint-request-plist (cider--pretty-print-width)))))
```

**Comment by bbatsov** [comment]
Yeah, that'd be a start.

Although, ideally this would be handled by a middleware and the data would be displayed as some table. We can even add functionality to quickly edit some metadata key from the table.

**Comment by bbatsov** [comment]
At any rate - I'm fine with accepting a simpler solution, as I definitely don't have the time to work on what I just outlined (although at least the tabular listing should be easy to do even with the current approach).

**Comment by xiongtx** [comment]
> We can even add functionality to quickly edit some metadata key from the table.

**Comment by bbatsov** [comment]
> Not sure how to check if <ns>/<var> exists before trying to call meta on it though. We could prevent errors if that was available.

Another problem to keep in mind is that you don't want to do something like this in the eval session as it would affect variables like `*1` and so on. That's why the tooling session exists - for building commands based on evaluation without messing up the primary session. But in general I do believe that usually building such things as middleware is better as the result is simpler client-side code.

**Comment by n2o** [comment]
What about adding the meta-information to the cider-doc command? I am just experimenting with meta-data and the most intuitive way to show the information is to append it to the normal doc-command in my opinion. At least that's the place where I'd expected my "deprecated" note.

**Comment by vemv** [comment]
This worked:

```lisp
(cider-inspect-expr (concat "(clojure.core/meta #'" (cider-symbol-at-point) ")") (cider-current-ns))
```
