### ISSUE TITLE
Have some way of auto reconnect along with cider-connect

### ISSUE THREAD

**Issue by vigneshsarma** [clojure-emacs/cider#1961]
Right now when you connect to a running nrepl server using `cider-connect` and that server dies. You have to manually kill the associated buffers and do a `cider-connect` again. It would be convenient if we can have way to do auto reconnect or manually call reconnect and everything gets cleaned or even maintain the same buffers.

If I am given some pointers, I can try to do this myself.

**Comment by mallt** [comment]
You might try running `cider-restart`. Does this yield the expected result?

**Comment by vigneshsarma** [comment]
`cider-restart` is not what I am looking for. Once the connection is broken for the current cider repl, specifically when it has been created through `cider-connect`, when the service is back up I would want it to connect without any manual intervention. 

This might require some kind of polling to see if the service is back up.

**Comment by bbatsov** [comment]
True. I can't imagine a way to do this without polling.

**Comment by jcsims** [comment]
I'm looking to do something similar myself: I'd like `(cider-connections)` to filter REPL buffers that have been killed, as well as those whose backing service has been killed (e.g. I use `cider-connect`, and then kill the REPL process, without using `cider-quit`). This should be a first step to accomplish what you want, I think?

I'll look into this when I have some time.
