### ISSUE TITLE
mapcar: Wrong type argument: stringp, doc

### ISSUE THREAD

**Issue by Pitometsu** [clojure-emacs/cider#1963]
Can't quite from cider repl. That error occured. Can't even quite emacs as normal after running cider repl.

```
Leiningen 2.7.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM
CIDER 0.15.0snapshot (commit f5a1ade83c0299df9ae99bbb5a2bb843e0168452)
GNU Emacs 25.1.2 (x86_64-pc-linux-gnu, GTK+ Version 3.20.9) of 2016-09-29
```

**Comment by bbatsov** [comment]
Some stacktrace would be pretty useful.

**Comment by Pitometsu** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument stringp dor)
  substring-no-properties(dor)
  mapcar(substring-no-properties (dor require))
  cider-repl--history-write("/home/netsu/Documents/Projects/url-matcher/.lein-repl-history")
  cider-repl-history-save("/home/netsu/Documents/Projects/url-matcher/.lein-repl-history")
  cider-repl-history-just-save()
  kill-emacs()
  #[256 "\302\303\"\210C\303\304\305\306 \">\203
```

**Comment by Pitometsu** [comment]
While in `.dir-locals.el`:
```
((nil . ((flycheck-disabled-checkers
          . (clojure-cider-typed))
         (eval . (when (require 'projectile)
                   (setq cider-repl-history-file
                         (concat (projectile-project-root)
                                 ".lein-repl-history")))))))

```

**Comment by dpsutton** [comment]
Can you post the contents of the lein repl history file that is on disk? I'm wondering if that got into a bad state. It seems like the filename is correct and it's blowing up on serializing the contents back? or possibly your current repl history.

    (defun cider-repl--history-write (filename)
      "Write history to FILENAME.
    Currently coding system for writing the contents is hardwired to
    utf-8-unix."
      (let* ((mhist (cider-repl--histories-merge cider-repl-input-history
                                                 cider-repl-input-history-items-added
                                                 (cider-repl--history-read filename)))
             ;; newest items are at the beginning of the list, thus 0
             (hist (cl-subseq mhist 0 (min (length mhist) cider-repl-history-size))))
        (unless (file-writable-p filename)
          (error (format "History file not writable: %s" filename)))
        (let ((print-length nil) (print-level nil))
          (with-temp-file filename
            ;; TODO: really set cs for output
            ;; TODO: does cs need to be customizable?
            (insert ";; -*- coding: utf-8-unix -*-\n")
            (insert ";; Automatically written history of CIDER REPL session\n")
            (insert ";; Edit at your own risk\n\n")
            (prin1 (mapcar #'substring-no-properties hist) (current-buffer))))))

Also, it's probably easiest if you could step through the function I posted above from `cider-repl.el` to see exactly what's going on. But it seems like the list of things to write to disk is getting into a weird state, so your firsthand knowledge would be very helpful here.

**Comment by Pitometsu** [comment]
First one:

```clojure
(dor require)
(doc require)
(require [instaparse.core :as insta])
(require '[instaparse.core :as insta])
(doc insta)
insta
(def parser
(insta/parser
""))
(def parser
(insta/parser
""))
(def parser
(insta/parser
"eps"))
(keyword "example.com")
(keyword "example//com")
'A'
'AB'
(type 'AB')
(type 'ABC')
('ABC' + 'D')
(+ 'ABC' 'D')
(count 'abc')
{:example//.com "example//.com"}
(:example//.com {:example//.com "example//.com"})
(let [print 1] (eval `(print "Hi")))
(let [print 1] `(print "Hi"))
(let [p 1] `(print p))
(let [p 2] (let [p 1] `(print p)))
(let [p 2] (let [p 1] (print `(print p))))
(let [p "2"] (let [p "1"] (print `(print p))))
(let [p "2"] (let [p "1"] (eval `(print p))))
(let [p 1] `(print p))
(let [p 1] (eval `(print p)))
(let [p 1] (eval '(print p)))
(let [p 1] (eval ~'(print p)))
(let [p 1] (eval ~`(print p)))
(let [p 1] ~`(print p))
(let [p 1] `(print ~p))
(let [p 1] (eval `(print ~p)))
(let [p 1] `(print ~p))
(println ("a" "b"))
(println '("a" "b"))
(println '@("a" "b"))
(println '~@("a" "b"))
(println ~@("a" "b"))
@(println ("a" "b"))
@(println '("a" "b"))
(#(print %) (#'first #'rest))
#'nil
(#(identity `(print ~%)) (#'first #'rest))
(#(identity `(print ~@%)) (#'first #'rest))
(#(identity `(print ~@%)) '(#'first #'rest))
(`#(print ~@%) '(#'first #'rest))
(#`(print ~@%) '(#'first #'rest))
(#(identity `(print ~@%)) '(#'first #'rest))
(#(identity `(print ~@(eval %))) '(#'first #'rest))
(#(identity `(print ~@%)) '(#'first #'rest))
(#(identity `(do ~@%)) '(#'first #'rest))
@(#(identity `(do ~@%)) '(#'first #'rest))
(eval (#(identity `(do ~@%)) '(#'first #'rest)))
(doc for)
(#(identity `(~@%)) '(:a))
(#(identity `(~@%)) '(:a :b))
(#(`(~@%)) '(:a :b))
(#(identity `(~@%)) '(:a :b))
(#(identity `(print ~@%)) '(:a :b))
(#(identity `(~@% "hello")) '(print))
(#(eval `(~@% "hello")) '(print))
(#(eval `(~@% "Hello, World!")) '(println))
(gensym :hi)
(gensym ::hi)
::hi#
```

second:

```clojure
(doc doc)
(doc client/get)
(http/get "https://api.dribbble.com")
(require clj-http.client :as http)
(require '[clj-http.client :as http])
(http/get "https://api.dribbble.com")
(require '[clj-http.client :as http])
(http/get "https://api.dribbble.com")
lein deps :tree
(require '[clj-http.client :as http])
(http/get "https://api.dribbble.com")
args
*command-line-args*
(read #{:a})
(str #{:a})
(description #{:a})
(read-string #{:a})
(pr-string #{:a})
(pr-str #{:a})
(pr-str #{:a :c})
(str #{:a :c})
```

**Comment by dpsutton** [comment]
How did you come by these files? I ask because I just wrote some repl history and mine looks distinctly different from yours:

```

**Comment by Pitometsu** [comment]
Maybe because `lein repl` use same file for history. I hoped, it use same format and will be sync so. Looks like I mistaken. However, is there possibility to keep `lein repl` and `cider` history synchronized?

**Comment by dpsutton** [comment]
I had not heard of that before. I think this would be a novel feature. Tough for them to write to the same file. But looking at it, it looks like it's just

    (form ...)

versus

    ("(form ...)")

which doesn't seem that bad to wrangle.

**Comment by dpsutton** [comment]
@Pitometsu do you consider this ticket resolved and therefore should be closed? If you would like to request this feature it would probably be good to create a ticket for it with that title and the information about the logging differences, although i'm sure it would be pretty low on the priority list. I'm sure a PR would be welcome though as it sounds like a nice "play nice" feature.

**Comment by Pitometsu** [comment]
@dpsutton yep.
