### ISSUE TITLE
Coordinate fixing documentation discrepancies with regards to the version mismatch problem.

### ISSUE THREAD

**Issue by bigos** [clojure-emacs/cider#1967]
I have encountered 3 different pieces of documentation suggesting somewhat different solutions to the following problem. Sadly no one worked for me.

"WARNING: CIDER's version (X.X.X) does not match cider-nrepl's version (nil). Things will break!”.

Suggestion 1
Link next to the warning in the REPL will lead to a documentation page providing more details about the problem and a link to this page:
http://cider.readthedocs.io/en/latest/installation/#ciders-nrepl-middleware

Suggestion 2
Cider REPL provides different solution:
https://github.com/boot-clj/boot/wiki/Cider-REPL

Suggestion 3
This page another solution
https://github.com/clojure-emacs/cider-nrepl
Section "Via Boot" suggest to use:

```
(set-env! :dependencies '[[org.clojure/tools.nrepl "0.2.12"]
                          [cider/cider-nrepl "0.x.y-SNAPSHOT"]])
```

However, none of those 3 solutions has worked for me. 

my current ~/.boot/profile.boot
```
(set-env! :dependencies '[[org.clojure/tools.nrepl "0.2.12"]
                          [cider/cider-nrepl "0.15.0-SNAPSHOT"]])

(require '[cider.tasks :refer [add-middleware]])

(task-options! add-middleware {:middleware '[cider.nrepl.middleware.apropos/wrap-apropos
                                             cider.nrepl.middleware.version/wrap-version]})
```
## Expected behavior

Unified documentation which describes how to handle version with snapshot and without snapshot suffix

## Actual behavior

All pieces of documentation differ, which is confusing to a new user.

## Steps to reproduce the problem

M-x cider-connect and selecting the host and port.

### CIDER version information

```
org.clojure/tools.nrepl\:0.2.12  
cider/cider-nrepl\:0.15.0-SNAPSHOT 
CIDER 0.15.0snapshot (package: 20170322.155)
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
Clojure 1.8.0
```

### Lein/Boot version

BOOT_VERSION=2.7.1

### Emacs version

GNU Emacs 25.2.6

### Operating system

Linux Mint 18.1 Cinnamon 64-bit

**Comment by bbatsov** [comment]
Guess someone should go over the 3 places of documentation and align them. Usually CIDER's manual is the best and the most up-to-date documentation resource.

**Comment by xiongtx** [comment]
> Sadly no one worked for me

Did anything actually work? No point unifying documentation if they're all wrong...

**Comment by vemv** [comment]
Boot support is about to be dropped these days.

And the linked docs have changed since.
