### ISSUE TITLE
Parameter hints in minibuffer are hijacked by keywords and function names

### ISSUE THREAD

**Issue by daveliepmann** [clojure-emacs/cider#1968]
## Expected behavior
`(update foo :data dissoc :squuid)`
The parameter list in the minibuffer should bold whichever of `update`'s parameters that the cursor is on. 

For instance:
`(update foo :data dissoc :squuid)`
`........^`
should show `update`'s parameter `m` bolded in the minibuffer:
>clojure.core/update: ([**m** k f]) ([**m** k f x]) ([**m** k f x y]) ([**m** k f x y z]) ([**m** k f x y z & more]))`

and:
`(update foo :data dissoc :squuid)`
`..............^`
should show `update`'s parameter `k` bolded in the minibuffer:
>clojure.core/update: ([m **k** f]) ([m **k** f x]) ([m **k** f x y]) ([m **k** f x y z]) ([m **k** f x y z & more]))`

## Actual behavior
`(update foo :data dissoc :squuid)`
`............^^^^^........^^^^^^^`
With the cursor at any of the positions marked `^`, the minibuffer shows parameters for the keyword under the cursor, instead of for `update`:

>:data: ([map] [map not-found])

This is suboptimal. I'm never curious about the parameters of a keyword literal; I'm frequently curious about the exact order of parameters in a function that has >2 parameters and multiple arities. Bolding the parameter that matches the value under my cursor is most useful when used on multi-arity, multi-parameter functions like `update`. That's lost when the minibuffer switches to the parameter list of a keyword that's not even being used in a function context.

Similarly:
`(update foo :data dissoc :squuid)`
`..................^^^^^^`
With my cursor anywhere in `dissoc`, the minibuffer shows parameters for `dissoc`, instead of for `update`:

>clojure.core/dissoc: ([map]) ([map key]) ([map key & ks]))

The parameters to `dissoc` aren't relevant to the context of the sexp my cursor is in. (They may of course be relevant to the functionality I'm designing, but there are other methods to be reminded for that purpose.)

With my cursor on `dissoc` I'd prefer to keep the parameter list of `update`, with the `f` parameter bolded:

>clojure.core/update: ([m k **f**]) ([m k **f** x]) ([m k **f** x y]) ([m k **f** x y z]) ([m k **f** x y z & more]))`

## Steps to reproduce the problem

1. Start CIDER
1. Find a function call that involves passing a keyword or named function
1. Put the cursor at a point with a keyword or function
1. Monitor the minibuffer as it switches from reporting the parameters of the sexp's function to the parameters of the function or keyword at point

### CIDER version information
```
;; CIDER 0.15.0snapshot (package: 20170322.155), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_25
```

### Lein/Boot version
>Leiningen 2.7.1 on Java 1.8.0_25 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

>GNU Emacs 25.1.1 (x86_64-apple-darwin16.3.0, Carbon Version 157 AppKit 1504.76) of 2017-01-23

### Operating system

MacOS Sierra 10.12.3

**Comment by mallt** [comment]
Setting the variable `cider-eldoc-display-for-symbol-at-point` to `nil` should give you the behavior you're looking for:

```
Documentation:
When non-nil, display eldoc for symbol at point if available.
So in (map inc ...) when the cursor is over inc its eldoc would be
displayed.  When nil, always display eldoc for first symbol of the sexp.
```

**Comment by daveliepmann** [comment]
Thanks, @mallt! That's precisely what I need.

**Comment by bbatsov** [comment]
Well, I wouldn't close this just yet - the real problem is that the functionality you mentioned doesn't play well with keywords under point. In eldoc I assume those are always map access and this messes up things.
