### ISSUE TITLE
Where to stick a post-processing of the *cider-result* buffer?

### ISSUE THREAD

**Issue by drorbemet** [clojure-emacs/cider#1970]
Using a call to `cider--pprint-eval-form` to return the result in a separate buffer I would like to apply a post processing of the `*cider-result*` buffer using a named or unnamed function with a body similar to this :
```
(with-current-buffer the-current-cider-result-buffer
        (my-custom-action-within-the-result-buffer))
```
I searched the dependencies of `cider--pprint-eval-form` but didn't find a place that made sense to me or returned the desired effect.
Untill now I call the `my-custom-action-within-the-result-buffer` manually each time after the creation of a `*cider-result*` buffer.

**Comment by drorbemet** [comment]
I found the place I think.
For now I stuck `my-custom-action-within-the-result-buffer` at the end of `cider-emit-into-popup-buffer`.

**Comment by bbatsov** [comment]
What type of post-processing would you like to do there?

**Comment by drorbemet** [comment]
I'm inlining images mentioned in the result of the clojure evaluation by using some variant of org-mode's inline image command. It already works for me. Though it didn't work using advice-add but only by editing `cider-emit-into-popup-buffer`.

**Comment by drorbemet** [comment]
It makes more sense to work with a new buffer for a result specific visualization.

**Comment by bbatsov** [comment]
I've been thinking for a while about rendering in-buffer image results, but I never actually got to doing this.
