### ISSUE TITLE
cider 0.15.0 doesn't work on Emacs 24.4

### ISSUE THREAD

**Issue by ha2ne2** [clojure-emacs/cider#1979]
## Expected behavior
working normally

## Actual behavior
doesn't work

*Messages*
Making nrepl-create-client-buffer-function local to *nrepl-server* while let-bound!
Making nrepl-use-this-as-repl-buffer local to *nrepl-server* while let-bound!
Starting nREPL server via "c:/home/ha2ne2/.lein/bin/lein.bat" update-in :dependencies conj ^"[org.clojure/tools.nrepl \^"0.2.12\^" :exclusions [org.clojure/clojure]]^" -- update-in :plugins conj ^"[cider/cider-nrepl \^"0.15.0-SNAPSHOT\^"]^" -- repl :headless :host ::...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server:  w 肳 ꂽ p X         ܂    B
error in process sentinel: Could not start nREPL server:  w 肳 ꂽ p X         ܂    B

## Steps to reproduce the problem

> emacs-24.4.exe -q
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
M-x package-install [RET] cider [RET]
M-x cider-jack-in

doesn't work:

> emacs-25.2.exe -q
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
M-x package-install [RET] cider [RET]
M-x cider-jack-in

work

### CIDER version information

;; CIDER 0.15.0snapshot (package: 20170403.402), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_71

### Lein/Boot version

Leiningen 2.7.1 on Java 1.8.0_71 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

24.4.1 and 25.2

### Operating system

Windows10

**Comment by bbatsov** [comment]
Is this the complete backtrace? Likely we've accidentally used something 25.x-specific - e.g. a new function.

**Comment by ha2ne2** [comment]
That is all log message in \*Message\* buffer about this.
Didn't you reproduce that?

**Comment by xiongtx** [comment]
Can you set `debug-on-error` to `t` and provide the stacktrace?

**Comment by ha2ne2** [comment]
Debugger entered--Lisp error: (void-function debug-on-error)
  (debug-on-error t)
  eval((debug-on-error t) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

**Comment by ha2ne2** [comment]
OK, Here is that.
It seems misconversion.
something error message had output.
but I can't read that.

Debugger entered--Lisp error: (error "Could not start nREPL server: \216w\222肳\202ꂽ\203p\203X\202\252\214\251\202\251\202\350\202܂\271\202\361\201B
")
  signal(error ("Could not start nREPL server: \216w\222肳\202ꂽ\203p\203X\202\252\214\251\202\251\202\350\202܂\271\202\361\201B
\n"))
  error("Could not start nREPL server: %s" "\216w\222肳\202ꂽ\203p\203X\202\252\214\251\202\251\202\350\202܂\271\202\361\201B
\n")
  nrepl-server-sentinel(#<process nrepl-server> "exited abnormally with code 1\n")

**Comment by dpsutton** [comment]
Is it possible that after the first run the cider files are still present? I'm wondering if we have .elc files with emacs 24.x byte compilation and then emacs 25.x trying to interpret them.

**Comment by bbatsov** [comment]
Can someone else try starting cider on 24.4?

**Comment by dpsutton** [comment]
I can confirm this on windows 7 with emacs 24.4

**Comment by bbatsov** [comment]
@dpsutton did you get a meaningful error?

**Comment by dpsutton** [comment]
no, same info as above. I remembered the exec-path changing from 24 -25 emacs but lein appears to be still on the path visible. I'm gonna check if its having trouble exec'ing even though it looks like its on the path. i'm investigating a little bit more and want to see the actual command its invoking to start lein. as far as i can tell from the error, lein is failing.

```
Starting nREPL server via "c:/Users/daniel.sutton/.lein/bin/lein.bat" update-in :dependencies conj ^"[org.clojure/tools.nrepl \^"0.2.12\^" :exclusions [org.clojure/clojure]]^" -- update-in :plugins conj ^"[cider/cider-nrepl \^"0.15.0-SNAPSHOT\^"]^" -- repl :headless :host ::...
error in process sentinel: cond: Could not start nREPL server: The system cannot find the path specified.


error in process sentinel: Could not start nREPL server: The system cannot find the path specified.


```

**Comment by dpsutton** [comment]
issuing the exact jack-in command from a command prompt works. This is some kind of permissions and path issue.

![image](https://cloud.githubusercontent.com/assets/6377293/25536068/f5cddf30-2bfe-11e7-9da0-a6ac6d99c6f4.png)

**Comment by dpsutton** [comment]
`(executable-find cider-lein-command)` => "c:/Users/daniel.sutton/.lein/bin/lein.bat"

which is a valid path and works. For whatever reason, `nrepl-start-server-process` is not finding it though.

**Comment by dpsutton** [comment]
```
(start-file-process-shell-command "nrepl-server" "*scratch*" (shell-quote-argument "c:/Users/daniel.sutton/.lein/bin/lein.bat"))Leiningen is a tool for working with Clojure projects.

Several tasks are available:
change              Rewrite project.clj by applying a function.
check               Check syntax and warn on reflection.
classpath           Print the classpath of the current project.
clean               Remove all files from project's target-path.
compile             Compile Clojure source into .class files.
deploy              Build and deploy jar to remote repository.
deps                Download all dependencies.
do                  Higher-order task to perform other tasks in succession.
help                Display a list of tasks or help for a given task.
install             Install the current project to the local repository.
jar                 Package up all the project's files into a jar file.
javac               Compile Java source files.
new                 Generate project scaffolding based on a template.
plugin              DEPRECATED. Please use the :user profile instead.
pom                 Write a pom.xml file to disk for Maven interoperability.
release             Perform :release-tasks.
repl                Start a repl session either with the current project or standalone.
retest              Run only the test namespaces which failed last time around.
run                 Run a -main function with optional command-line arguments.
search              Search remote maven repositories for matching jars.
show-profiles       List all available profiles or display one if given an argument.
test                Run the project's tests.
trampoline          Run a task without nesting the project's JVM inside Leiningen's.
uberjar             Package up the project files and dependencies into a jar file.
update-in           Perform arbitrary transformations on your project map.
upgrade             Upgrade Leiningen to specified version or latest stable.
vcs                 Interact with the version control system.
version             Print version for Leiningen and the current JVM.
with-profile        Apply the given task with the profile(s) specified.

Run `lein help $TASK` for details.

Global Options:
  -o             Run a task offline.
  -U             Run a task after forcing update of snapshots.
  -h, --help     Print this help or help for a specific task.
  -v, --version  Print Leiningen's version.

These aliases are available:
downgrade, expands to upgrade

See also: readme, faq, tutorial, news, sample, profiles, deploying, gpg,
mixed-source, templates, and copying.

Process nrepl-server finished
```

for some reason i can invoke it myself

**Comment by bbatsov** [comment]
Is this some Windows-specific issue?

**Comment by yiwan** [comment]
@bbatsov I'm using macOS and also stuck there. I can execute the command within shell directly and it works, but just can't start nrepl with cider-jack-in.

I agree with @dpsutton it seems like permission or path? issue.

macOS 10.12.4 | emacs 25.2 | cider 0.15.0 | Java 1.8.0_131 |

**Comment by bbatsov** [comment]
Hmm, you're having this issue on 25.2. Seems it's not something specific to 24.4 then...

**Comment by bbatsov** [comment]
Given the lack of activity here I guess we can close this ticket.
