### ISSUE TITLE
[Feature request] Integrate CIDER doc displaying with quick-peek or inline-docs

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#1982]
Hope CIDER can integrate `quick-peek` or `inline-docs` for functions like query docs.

This can be set in an option.

- https://github.com/cpitclaudel/quick-peek
- https://github.com/stardiviner/inline-docs.el

**Comment by bbatsov** [comment]
I'm assuming integrating something like this should be trivial, but unless a lot of people demand such a feature it should probably be implemented as a separate package, so that we don't introduce more dependencies to CIDER.

**Comment by stardiviner** [comment]
I see, I will dive into CIDER source code to check out this. If have any question, will ask for help here. Thanks.

**Comment by bbatsov** [comment]
Sure.

**Comment by bbatsov** [comment]
Btw, I've noticed both libraries you've mentioned are tiny, so I'm not opposed that much to depending on one of them. I'm curious about the invisioned workflow for the inline docs, thought - would this a replacement for eldoc or just a command bound to some keystroke? Would we should just prototypes or docstrings and metadata as well? Guess those are the most important things to consider.

**Comment by stardiviner** [comment]
Those two libraries are just a library, not functional package which can be used directly. There is an existing package which uses `inline-docs.el`. https://github.com/stardiviner/eldoc-overlay-mode. It uses as a replacement of `eldoc` default echo-area display. It can be used for other places too. Just change the way of people viewing their information. Don't need to move eye into bottom echo-area. Just viewing info at inline place.

**Comment by bbatsov** [comment]
I guess we can implement some command in terms of `inline-docs.el` and also mention in the eldoc section of the manual `eldoc-overlay-mode`.

**Comment by stardiviner** [comment]
That's great, this is my first time my Emacs library been used in large project. Happy coding.
Because I don't know `CIDER` much, hope someone can pick this up. and create an branch for this? I will try to dive into the cider source code. Thanks.

**Comment by bbatsov** [comment]
Everything that needs doing is pretty trivial as all the documentation and eldoc code is in `cider-doc.el` and `cider-eldoc.el` and the data simply needs to be presented with the new library. I'll mark this as a long-hanging fruit in case some newcomer is interested in tackling it.

**Comment by vemv** [comment]
PRs welcome for whatever support work is necessary for those libraries to be integrated.

CIDER already has a variety of "APIs" that Elisp hackers can leverage to get something working.
