### ISSUE TITLE
Set `cider-repl-use-pretty-print` to `t` by default

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/cider#1984]
## Expected behavior

`cider-repl-use-pretty-print` should be `t` by default.

## Actual behavior

`cider-repl-use-pretty-print` is `nil` by default.

This variable is rather obscure, and I spent a *long* time manually doing `clojure.pprint/pprint` in the REPL before discovering it. It's such a big qualify-of-life improvement that I wonder why it's not `t` by default.

## Steps to reproduce the problem

N/A

### CIDER version information

```
CIDER 0.15.0snapshot (package: 20170129.1941)
```

### Lein/Boot version

```
Leiningen 2.7.1 on Java 1.8.0_111 OpenJDK 64-Bit Server VM
```

### Emacs version

```
GNU Emacs 25.1.1
```

### Operating system

```
Fedora 24
```

**Comment by bbatsov** [comment]
Pretty-printing messes up the return values, so I don't think it's a good default - in general it's rarely a good idea to use as a default something non-standard. I've never seen a REPL default to pretty-printing. 



> This variable is rather obscure, and I spent a long time manually doing clojure.pprint/pprint in the REPL before discovering it. It's such a big qualify-of-life improvement that I wonder why it's not t by default.

Really? There's a mention of it in the manual and a function to toggle it is available in the mode menu. :-)

**Comment by xiongtx** [comment]
Fair enough. I guess I was just surprised to discover it after so long.

> There's a mention of it in the manual

:running_man: :book:

**Comment by bbatsov** [comment]
> Pretty-printing messes up the return values

Seems we actually fixed this and I forgot about it. :-) But the rest still stands true. :-)
