### ISSUE TITLE
cider-jack-in-clojurescript only opens single REPL 

### ISSUE THREAD

**Issue by mrwizard82d1** [clojure-emacs/cider#1989]
## Expected behavior

Expect two REPL buffers for ClojureScript

## Actual behavior

I see only *one* REPL: the Clojure REPL

## Steps to reproduce the problem

- Given I have installed the latest stable version of CIDER (0.14.0)
- And I have created a new project using `lein new demo-cljs``
- And I have created a source file `demo-cljs/core.cljs
- And I have added a dependency on ClojureScript 1.9.521 to `project.clj`
- And I have added the `piggieback` dependency as described in the docs
- And have added the `:repl-options` as described in the docs
- When I navigate to the file `demo-cljs/core.cljs`
- And I execute `cider-jack-in-clojurescript`
- Then I expect to see two REPL buffers: one for Clojure and one for ClojureScript
- But I only see one REPL buffer for Clojure

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:60096
;; CIDER 0.14.0 (Berlin), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_102
```

### Emacs version

* GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1004)) of 2016-10-06

### Operating system

*OS X 10.11.16 "El Capitan"

[demo-cljs.tar.gz](https://github.com/clojure-emacs/cider/files/998980/demo-cljs.tar.gz)

**Comment by bbatsov** [comment]
Is this still an issue with 0.16?

**Comment by bbatsov** [comment]
Closing this in light of the big changes in 0.18.
