### ISSUE TITLE
Feature request: make `cider--offer-to-open-app-in-browser` configurable

### ISSUE THREAD

**Issue by agzam** [clojure-emacs/cider#1991]
When creating a sibling CLJS repl or using `jack-in-clojurescript`, CIDER asks if user wants to open the app in the browser.
This is extremely annoying, especially in the case when opening it in the browser won't achieve anything - CLJS code still might be being compiled.
Can someone make this dialog configurable? And default option to be "Don't ask"

**Comment by drewverlee** [comment]
Can we make this configurable so that it also automatically opens the browser? I have to wait for this option to present itself and hit yes or else the entire operation will fail.
