### ISSUE TITLE
macOS freeze: redisplay_internal when CIDER is running

### ISSUE THREAD

**Issue by zrzka** [clojure-emacs/cider#1992]
## Actual behavior

I do use Emacs on daily basis and when the CIDER is not running, everything is okay. But when CIDER is running, lot of freezes. Totally random. Sometimes no freeze per day. Sometimes > 20 freezes per day.

`C-g` doesn't help, `kill -SIGUSR2` does.

Backtrace after magit fetch:

```
Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
```

Backtrace after mouse wheel scrolling:

```
Debugger entered--entering a function:
* command-error-default-function((quit) "" nil)
  recursive-edit()
  debug(error (quit))
  ...
  linum-update(#<buffer post.cljs>)
  linum-after-scroll(#<window 3 on *Backtrace*> 2215)
  redisplay_internal\ \(C\ function\)()
```

 See https://github.com/syl20bnr/spacemacs/issues/8557 for more of them. It ends up in `redisplay_internal` in almost all cases (with few / rare exceptions).

Emacs freezes even when I'm not interacting with CIDER. Simple jack in (cljs) is enough. Whenever it is started, it causes these issues.

Any idea what can cause this issue and how to hunt it down?

## Expected behavior

No freeze.

## Steps to reproduce the problem

This one is the hardest one. There're no steps to reproduce. I can do basically anything like:

* Scroll with mouse wheel
* Refactor namespace
* Simple typing clj code
* Git fetch

And simple jack in (cljs) is enough.

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:59308
;; CIDER 0.15.0snapshot (package: 20170509.208), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_112
```

### Lein/Boot version

Leiningen 2.7.1 on Java 1.8.0_112 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

25.2.1

### Operating system

OS X 10.12.5

**Comment by bbatsov** [comment]
This error is clearly coming from `linum` (see your stacktrace). It's extremely unlikely anything in CIDER would cause such a problem.

**Comment by zrzka** [comment]
For this one, yes. There're others that are not `linum` related. Anyway, good point, disabled.

**Comment by bbatsov** [comment]
So, the repro steps remain the same without `linum`?

**Comment by zrzka** [comment]
Yep, did happen without linum as well. I'm now tracking where it loops in LLDB with help from Emacs devs. Basically to find why Emacs is freezing in redisplay_internal, iow what's going on on C level. AFK for now, will finish this journey next week.

**Comment by zrzka** [comment]
Update https://github.com/syl20bnr/spacemacs/issues/8557#issuecomment-304465458

**Comment by bbatsov** [comment]
This doesn't seem related to CIDER to me.
