### ISSUE TITLE
Auto inject piggyback dependency when calling cider-jack-in-clojurescript

### ISSUE THREAD

**Issue by sunng87** [clojure-emacs/cider#2003]
I found the [setup steps](https://cider.readthedocs.io/en/latest/up_and_running/#clojurescript-usage) of ClojureScript is a little verbose and requires some cider specific things in `project.clj`. So I think we can auto inject these depdencies and repl-options just like what we did for nrepl.

If it works, I will attempt to create a pull request for this.

**Comment by bbatsov** [comment]
Sounds reasonable, but it should be dependent on the configured default ClojureScript REPL type I guess.

**Comment by bbatsov** [comment]
That's finally done in 0.18.
