### ISSUE TITLE
Load debug data readers in template projects

### ISSUE THREAD

**Issue by Aljendro** [clojure-emacs/cider#2006]
## Expected behavior
Load *data-readers* in template projects for debugging.

## Actual behavior
The data readers are not being loaded (dbg, break).

## Steps to reproduce the problem
I go into any lein template project, jack-in, but cannot get the data readers to load for debugging.
One example is the luminus-template.
In any regular Clojure project the data readers are loaded without a problem.

### CIDER version information

```
;; CIDER 0.14.0 (Berlin), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_131
```

### Lein/Boot version

Lein 2.7.1

### Emacs version

24.5.1

### Operating system

Ubuntu 16.04

**Comment by bbatsov** [comment]
@Malabarba @vspinu can you take a look?

**Comment by vspinu** [comment]
It was a dependency conflict on my side. After fixing that, I can confirm that the readers are not loaded. 

If I do 

```clj
(#'clojure.core/load-data-readers)
;; {dbg #'cider.nrepl.middleware.debug/debug-reader,
;;  break #'cider.nrepl.middleware.debug/breakpoint-reader,
;;  light #'cider.nrepl.middleware.enlighten/light-reader}
```
clojure does find those readers, but the *data-readers* stays empty. That's definitely  odd.
