### ISSUE TITLE
cider mode always opened when switch project use projectile

### ISSUE THREAD

**Issue by ChinaXing** [clojure-emacs/cider#2010]
I'm use Emacs-Prelude, manage 2 project: one is web-project , another is clojure-project.

when use C-c p p to switch project from clojure-project to web-project, I can see cider mode, also

exist in the buffer of web-project's file.

> 14k 209:19 UUU -[shiva-console-frontend].../syncTablePane.jsx 46% :multi-env [Web] cider[not connected] guru company FlyC:18/0 ws +

this is incorrect, because the current buffer is Web's, not a clojure buffer.

so, is this a bug or has some switcher can fix the problem ?

very thanks your reply :)

**Comment by bbatsov** [comment]
Sounds like a bug, but it's a rather odd one, as `cider-mode` gets activated just for clojure buffers normally.

**Comment by xiongtx** [comment]
Can you reproduce using vanilla Emacs? If not, this is likely a Prelude issue, not CIDER's.
