### ISSUE TITLE
Q: can I see a list of all known symbols within CIDER?

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/cider#2011]
Is it possible to see a (preferably in a `helm` or `ivy` completion) list of all known symbols within a (`projectile`) project?

CIDER obviously understands symbols as it allows me to jump to the declaration of a symbol, but equally it states it will take a while to analyse the entire project to find usages, which is surprising as I assumed it already had the list to enable the 'jump to' functionality.

At the moment, `helm-ag` goes a long way but it has some pretty obvious and fundamental issues.

Thanks!

**Comment by xiongtx** [comment]
`helm-imenu-in-all-buffers` gives symbols in all buffers with the same major mode (or associated major modes via `helm-imenu-all-buffer-assoc`). Not the same as all symbols in project, but you can get around it by having one frame per project and opening all their files.

[`helm-cider`](https://github.com/clojure-emacs/helm-cider) gives all symbols, including those from project dependencies (e.g. `clojure.core`). You can also refine by namespace.

**Comment by jiacai2050** [comment]
`C-c M-n b` (cider-browse-ns) will list all top-level symbols.

```
  (defun my/browse-current-ns ()
    (interactive)
    (cider-browse-ns (cider-current-ns)))
```
Bind func above to your favorite key
