### ISSUE TITLE
Cider debug not working on functions wrapper with other 

### ISSUE THREAD

**Issue by rmuslimov** [clojure-emacs/cider#2013]
## Expected behaviour
Debugging methods wrapped with trivial `def` macro should work

## Actual behaviour
If method function A wrapped by function B, debugging A not working (or require re-evaluating place where A wrapped with B).

## Steps to reproduce

Consider next chunk of code. 
```
(defn funcA
  [a]
  (inc a))

(def funcB (partial funcA 1))

(funcA 1)
(funcB)      ;; eval this, this won't open debugger
```
1. Eval forms
2. Execute `cider-debug--defun-at-point` while cursor inside of funcA function
3. Eval `(funcB)` form ,It should stop debugger in funcA body, but it doesn't and just return proper result

## Cider version 
;; CIDER 0.14.0 (Berlin), nREPL 0.2.12
;; Clojure 1.9.0-alpha15, Java 1.8.0_65

**Comment by bbatsov** [comment]
I'll leave this one for our debugger experts @Malabarba & @vspinu.

**Comment by vspinu** [comment]
This is expected. When you created your `funcB` you used an instance of `funcA`. Then you instrumented `funcA` and redefined it by side effect, but `funcB` is still using your old version of `funcA`. 

Either redefine your `funcB` after you instrumented `funcA` or use vars:

```clj
(def funcB (partial #'funcA 1))
```

**Comment by rmuslimov** [comment]
Makes sense, thanks!
