### ISSUE TITLE
Manual installation is not properly documented

### ISSUE THREAD

**Issue by georgek** [clojure-emacs/cider#2019]
Currently the manual installation instructions consist of just adding `(require 'cider)` somewhere. This is fine and great. But there are two problems:

* Package dependencies are not documented. I had to keep trying the above to see what package it would complain about next,
* `cider-macroexpansion` is not included, and possibly other things that I haven't noticed yet. This manifests itself in the macroexpansion keys being bound to undefined functions.

I don't know how the emacs package managers work but it should be pretty easy to also maintain a human readable list of dependencies and requires.

**Comment by vspinu** [comment]
Package dependencies are in cider.el
```el
;; Package-Requires: ((emacs "24.4") (clojure-mode "5.6.0") (pkg-info "0.4") (queue "0.1.1") (spinner "1.7") (seq "2.16"))
```

But it looks like you are asking what components of cider itself to load and in what order. This is what I got with the trial and error long time ago

```el
(require 'clojure-mode)
(require 'cider)
(require 'cider-selector)
(require 'cider-eldoc)
(require 'cider-repl)
(require 'cider-util)
(require 'nrepl-client)
(require 'cider-scratch)
(require 'cider-selector)
(require 'cider-stacktrace)
(require 'cider-client)
(require 'cider-inspector)
(require 'cider-interaction)
(require 'cider-macroexpansion)
(require 'cider-mode)
(require 'cider-browse-ns)
```

Would be great to have it pulled from one place; `(require 'cider-all)` maybe.

You will also get problems with reverse dependencies. For instance you won't be able to install packages that depend on cider from melpa. You will have to pull those as source libraries as well. Any hints of how to fix this would be very much appreciated.

**Comment by bbatsov** [comment]
> Package dependencies are not documented. I had to keep trying the above to see what package it would complain about next,

http://cider.readthedocs.io/en/latest/installation/#manual-installation

That's mentioned here. The deps are not explicitly listed as the manual installation is discouraged in general.

cider-macroexpansion is not included, and possibly other things that I haven't noticed yet. This manifests itself in the macroexpansion keys being bound to undefined functions.

Such commands are autoloaded, but when you install manually you have to manually generate the autoloads. Another strong argument against doing this.
