### ISSUE TITLE
CLJS: Can't find namespace, file in same directory, multiple directories in :source-paths

### ISSUE THREAD

**Issue by anticrisis** [clojure-emacs/cider#2028]
## Expected behavior

C-c C-k successfully loads ClojureScript file which references a namespace in another file in the same directory, when using a nested directory structure for cljs and cljc files.

## Actual behavior

```
Caused by: clojure.lang.ExceptionInfo: No such namespace: testcider.foo, could not locate testcider/foo.cljs, testcider/foo.cljc, or Closure namespace "testcider.foo" in file d:\dev\testcider\src\cljs\testcider\core.cljs {:tag :cljs/analysis-error}
```

## Steps to reproduce the problem

2 ways to do this. Simplest is to use an unmodified lein reagent template, I believe the problem is caused by the directory structure used:

```
src
- cljs
- cljc
- clj
```

```
lein new reagent testcider
```

2. visit testcider/src/cljs/testcider/core.cljs
3. `cider-jack-in-clojurescript`
3. add `[testcider.foo]` to `:require`
4. visit foo.cljs in same directory and add `(ns testcider.foo)` and save file
5. visit core.cljs and type `C-c C-k`
6. Exception thrown

`lein cljsbuild once` succeeds without error.

Unfortunately, evaluating `testcider.foo` first with `C-c C-k` does not offer a workaround. The file evaluates, but another exception is thrown when trying to evaluate `testcider.core`

Another way to reproduce is to use a simpler template that does not use nested directories, and then introduce nested directories

```
lein new figwheel testcider
```

2. observe that the project builds and works as expected with `cider-jack-in-clojurescript`
3. visit testcider/project.clj and change `:source-paths` to ` ["src/cljs" "src/cljc"]`
4. create those subdirectories under `src` and move `testcider` under `src/cljs`
5. quit both cider repls and manually end the leftover java task using Task Manager
6. visit src/cljs/testcider/core.cljs and `cider-jack-in-clojurescript`
7. continue with step 3 in the previous test.

### CIDER version information

```
;; CIDER 0.15.0snapshot (package: 20170630.2342), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_131
```

### Emacs version

GNU Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24

### Operating system

Windows 10

**Comment by raxod502** [comment]
Is there a workaround?

**Comment by raxod502** [comment]
See also https://dev.clojure.org/jira/browse/CLJS-1473, https://groups.google.com/forum/#!topic/clojure/qSiGeQZzyT0, https://github.com/tomjakubowski/weasel/issues/28.

Note that the error messages appear to be spurious, i.e. the namespaces are loaded correctly and all vars defined in them are usable.

**Comment by raxod502** [comment]
Also, the error is not related to CIDER. It occurs when you start a manual `lein repl`, start `figwheel-sidecar.repl-api/cljs-repl`, and try to `require` something. But interestingly it doesn't happen when you `lein figwheel` and try to `require` something. I've created https://github.com/bhauman/lein-figwheel/issues/585.

Although, now that I think of it, I guess you don't have to eval things using CIDER, since Figwheel does that for you on file save.

**Comment by anticrisis** [comment]
Stale bot woke me up. I can no longer reproduce this test case with a fresh install. Closing.
