### ISSUE TITLE
Regex not working with cider-browse-spec-all

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#2030]
Hello folks!

this new feature is super cool and I am trying it out :smile: The function `cider-browse-spec-all` works fine and shows the list of all the specs loaded, but the filter-by-prefix feature returns an empty buffer here.

Will try to debug a bit and report if I can!

## Expected behavior

Should show the list of specs, filtered by prefix.

## Actual behavior
It shows an empty buffer (only header `All specs with `:resource' prefix in registry` is shown).

## Steps to reproduce the problem
Run `cider-browse-spec-all` then filter by prefix, I specified `:resource` for instance.

### CIDER version information

I am on `master`

### Lein/Boot version
Latest Boot

### Emacs version

*E.g. 24.5*

### Operating system
*Ubuntu*

**Comment by bbatsov** [comment]
> Should show the list of specs, filtered by prefix.

Actually it should just filter by regexp, not prefix. Anyways, it's clear it's broken for some reason. //cc @jpmonettas

**Comment by arichiardi** [comment]
I have tried both with and without `:` so a regex would match in theory.

**Comment by jpmonettas** [comment]
Yeah the prompt is wrong, I removed prefix everywhere but the prompt sorry. Currently it's using a regex, so for resource you should try resource.+

I'll push that prompt fix immediately.

**Comment by arichiardi** [comment]
Ok will try that, but shouldn't it match anyways?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jpmonettas** [comment]
Don't know, should we automatically add something to the regex?

**Comment by arichiardi** [comment]
I think it should, maybe there is something else going on there, afk now but I can check tomorrow.
 
https://regex101.com/r/LRrAjT/1

**Comment by bbatsov** [comment]
> I'll push that prompt fix immediately.

I actually fixed this myself after I noticed it.

**Comment by jpmonettas** [comment]
Currently we are using re-matches clojure side to filter the specs.

`(re-matches #"resource" "resource/url") => nil`
`(re-matches #"resource.+" "resource/url") => resource/url`

so that's why it isn't showing anything if you just type resource

What should be the correct behavior here?

**Comment by arichiardi** [comment]
Found, you need `re-find`: https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/spec.clj#L34

**Comment by jpmonettas** [comment]
Great, will fix that and send a PR

**Comment by arichiardi** [comment]
See [here as well](https://clojuredocs.org/clojure.core/re-matches#example-542692c8c026201cdc3269eb). Seems sensible to match anywhere in the string.
