### ISSUE TITLE
`cider-browse-spec-mode` should allow navigating back and forth

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/cider#2035]
## Expected behavior

`cider-browse-spec-mode` should allow navigating back and forth between specs, like `cider-doc view-mode` does.

## Actual behavior

`cider-browse-spec-mode` only allows navigation to the top-level `"All specs in registry"` buffer.

### Analysis

`cider-browse-spec` is modeled on `cider-browse-ns`, but there's a critical difference: it is possible to navigate from one spec to another from the spec browser, but not from one symbol to another from the ns browser. This is because namespaces and symbols are a tree, while specs are a graph.

`cider-docview-mode` is [derived from `help-mode`](https://github.com/clojure-emacs/cider/blob/ff4c0ed9bc70c3f48ad74d08c9f7c97e91b2553c/cider-doc.el#L177), which has built-in support for navigation via `help-go-back` and `help-go-forward`. `cider-browse-spec-mode` should do the same.

## Steps to reproduce the problem

1. View a spec that uses another spec in its definition via `cider-browse-spec`
2. Navigate to the other spec (by clicking on it)
3. Note that you cannot navigate back to the first spec, only to the top-level all specs browser

### CIDER version information

Commit ff4c0ed9bc70c3f48ad74d08c9f7c97e91b2553c.

**Comment by bbatsov** [comment]
This is in a way related to #2036 - I believe we shouldn't be using the same mode from browsing specs and viewing them.
