### ISSUE TITLE
Namespace alias in keyword stops debug working

### ISSUE THREAD

**Issue by mantree** [clojure-emacs/cider#2039]
## Expected behavior

All three functions should debug

## Actual behavior

The third call doesn't.

## Steps to reproduce the problem

(ns other)
(ns scratch)
(alias 'o 'other)

#dbg
(defn debugs
  [r]
  (inc (:n r)))

#dbg
(defn debugs-2
  [r]
  (inc (:other/n r)))

#dbg
(defn no-debug
  [r]
  (inc (::o/n r)))

(debugs {:n 1})
(debugs-2 {::o/n 1})
(no-debug {::o/n 1})

In a cider-scratch buffer as you compile you can see the third function doesn't get treated like the others, running each call make's it clear the third has not had the breakpoints inserted.

### CIDER version information

;; Connected to nREPL server - nrepl://localhost:42887
;; CIDER 0.15.0snapshot (package: 20170705.951), nREPL 0.2.12
;; Clojure 1.9.0-alpha13, Java 1.8.0_121

### Lein/Boot version

lein version
Leiningen 2.7.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.10) of 2017-04-22

### Operating system

uname -r
4.11.9-1-ARCH

**Comment by vspinu** [comment]
It's namespace related. Reading in the debugging is not done in requested namespace. 

Thrown in the debugger:

```
#error {
 :cause Invalid token: ::o/n
 :via
 [{:type java.lang.RuntimeException
   :message Invalid token: ::o/n
   :at [clojure.lang.Util runtimeException Util.java 221]}]
```

It's essentially as if doing: 

```clojure
::undefined/n
```

There are number of ns related issues in the debugger. Will have a look at all of them when I have time.

**Comment by expez** [comment]
Duplicate 

https://github.com/clojure-emacs/cider/issues/2004
https://github.com/clojure-emacs/cider-nrepl/issues/420

**Comment by vspinu** [comment]
@expez, strictly speaking this one is not a duplicate. It concerns the debugging definition while others concern evaluation during the debugging. While similar, fixes should be applied in different places.
