### ISSUE TITLE
All #?(:cljs code in cljc is commented out (cider-reader-conditional-face)

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider#2040]
I am seeing the following with the latest CIDER. 

![cljs](https://user-images.githubusercontent.com/1363467/28144938-d169146a-676e-11e7-9519-28a5006f5293.png)

This happens in `.cljc` files irrespectively of clojurescript repl running. AFAICU from the description it should show up on cljs connections.

For what it's worth, I thinking commenting conditionals is a bit too much.  Slight deeming might work better. I still read a lot of cljs code when cljs repl is not running, and this feature becomes quickly a nuisance.

**Comment by bbatsov** [comment]
> For what it's worth, I thinking commenting conditionals is a bit too much. Slight deeming might work better. I still read a lot of cljs code when cljs repl is not running, and this feature becomes quickly a nuisance.

Deeming -> dimming, right?

That's an interesting idea, btw!
