### ISSUE TITLE
*cider-scratch* is killed on connection exit  

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider#2045]
If this is by "design" it is a bad idea. You might have quite some code in *scratch* and want to restart connection for whatever reason, and then boom, everything is gone.

**Comment by bbatsov** [comment]
> If this is by "design" it is a bad idea. You might have quite some code in scratch and want to restart connection for whatever reason, and then boom, everything is gone.

Yeah, it's by design. It's not treated the same way as buffers like help buffers. Guess we should rethink this behaviour.

**Comment by rcullito** [comment]
definitely would further support the validity of this issue. this has happened to me several times and I've ended up recreating most of the work that I had in the old `cider-scratch`
