### ISSUE TITLE
cider-repl-switch-to-other doesn't work correctly with multiple projects

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider#2048]
clojurescript-jack-in in one project. Then go to another project and clojure-jack-in. From the REPL of the second project call `cider-repl-switch-to-other`. You will end up in CLJS REPL of the first project. From then on navigation between buffer and REPL is wrong. 

Somewhat surprisingly evaluation seem to be doing all right, even though `cider-map-connectons` is also based on `cider-other-connection`.

**Comment by jiacai2050** [comment]
This also happened among multiple clojure project.

**Comment by vspinu** [comment]
These and other similar issues should be eventually fixed in #2069.

**Comment by bbatsov** [comment]
The magic PR is in, this should be fixed now.
