### ISSUE TITLE
Better mode for cider grimoire

### ISSUE THREAD

**Issue by AlainPicard-at-gocatch** [clojure-emacs/cider#2049]
## *cider-grimoire* buffer is in Fundamental mode.

Dear cider maintainers,

This is a (minor) feature request.  I think it would be useful
if, when invoking (cider-grimoire), one would be left in a 
mode more useful than fundamental.  Perhaps something
based off view-mode, at the very least, so one could 
scroll with space bar and backspace.

For extra credit, one could parse the result page from grimoire,
which appears to be formatted in some sort of markdown, and use
the markdown mode fontification regexes to make the page fontified.

This is definitely just a nice to have, in case anyone feels like hacking
on this; no extra functionality would be added by this, just...  elegance.  :-)

Thanks for all the hard work on CIDER.
          Alain Picard

Cider 0.14.0

**Comment by xiongtx** [comment]
This is already the case as of 238c60c6, from #2007.

**Comment by AlainPicard-at-gocatch** [comment]
Thanks!  

Yes, I've just tried the current tip of master, and indeed, the grimoire
is fontified.

It is not, alas, in a view-mode, so hitting spacebar yields:
and error and prints:  Buffer is read-only: #<buffer *cider-grimoire*>

However, I've just noticed that view-mode already runs as a minor mode,
and can just be invoked in a grimoire buffer, so all we're missing now is
a hook we can run when entering the grimoire mode.  (Although I suppose
I could simply use the existing markdown-mode-hook, since I don't use markdown
myself).

Or do you have a better suggestion altogether?  

Thanks again,
  Alain

**Comment by xiongtx** [comment]
Using `view-mode` seems like a good idea. Doesn't seem to clash w/ `markdown-mode`'s bindings either. #2050 should address this. You can also try it out yourself; it's a extremely simple change.
