### ISSUE TITLE
Can't use cider-browse-spec in emacs24.5

### ISSUE THREAD

**Issue by vlaaad** [clojure-emacs/cider#2056]
## Expected behavior
`cider-browse-spec` displays spec data
## Actual behavior
`cider-browse-spec` opens empty buffer and displays message:
`Symbol's function definition is void: font-lock-ensure`

## Steps to reproduce the problem

- use emacs24.5.1
- enable cider
- `cider-browse-spec`
- select some spec
- press enter

### CIDER version information
```
;; CIDER 0.15.0 (package: 20170720.248) (London), nREPL 0.2.12
;; Clojure 1.9.0-alpha15, Java 1.8.0_121
```

### Lein/Boot version

Leiningen 2.7.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM  

### Emacs version

GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-17 on lgw01-04, modified by Debian

### Operating system

Ubuntu 16.04.2 LTS

**Comment by bbatsov** [comment]
Ah, yeah. Sorry about this.

Note to self - https://github.com/jaor/geiser/commit/733ea7a4ed1f527b70764a52fe865926d90f5177

**Comment by xiongtx** [comment]
@bbatsov There's already [`cider--font-lock-ensure`](https://github.com/clojure-emacs/cider/blob/e503f5628ef98bd768f08c698863e8e33a7af3b4/cider-util.el#L218) in `cider-util.el`.
