### ISSUE TITLE
[Feature Request] Support for shebang line and clojure scripting

### ISSUE THREAD

**Issue by phillord** [clojure-emacs/cider#2060]
It would be nice to have better support for writing clojure scripts.

For example, boot provides shebag support so a script might look like this:

     #!/usr/bin/env boot
     (println "hello world")

But the shebang line confuses syntax highlighting. It would be nice if clojure mode understood first line shebang lines!

**Comment by bbatsov** [comment]
I think this should be a `clojure-mode` ticket. Probably we can also add some command to run a script.
