### ISSUE TITLE
Invalid face reference: t continuously in message buffer

### ISSUE THREAD

**Issue by yalu** [clojure-emacs/cider#2062]
I am not sure if this a Cider problem, but it happens in Clojure buffers only.

## Expected behavior
No message of the type
## Actual behavior
Continuously get
`Invalid face reference: t [xx times]
`
## Steps to reproduce the problem
open any clj or cljs file
no need to fire repl

## Environment & Version information
MacOSX El Capitan

### CIDER version information
0.15.0

**Comment by yalu** [comment]
I had `(setq clojure-enable-fancify-symbols t)`

when I remove it the message goes away and all is fine.

**Comment by skrat** [comment]
I'm still getting these and not willing to give up fancy symbols. How is this closed?
