### ISSUE TITLE
cider cant connect to running remote repl after latest update (0.15.0)

### ISSUE THREAD

**Issue by vadali** [clojure-emacs/cider#2065]
Hi,
In an effort to eliminate the old "method too large" error message in the debugger, I upgraded to the newest cider. However, for some reason now I cannot connect to a running (remote) nrepl (through trump).

Here's some info: 
Client OS: OSx Yosemite 10.10.5 
Server OS: Ubuntu 14.04.4 LTS
Emacs: Emacs 25.2.1
Cider version: Retrieving cider/cider-nrepl/0.15.0/cider-nrepl-0.15.0.jar from clojars (tried both this and the SNAPSHOT version)
Cider in emacs: cider              0.15.0        installed             (package-list-packages)

Content of \*Messages\* buffer:
 
> Tramp: Inserting ‘/scp:server:/home/me/work/project/.nrepl-port’...
> Tramp: Encoding remote file ‘/scp:server:/home/me/work/project/.nrepl-port’ with ‘base64 <%s’...done
> Tramp: Decoding local file ‘/var/folders/xp/6j_21nwx08v0gk4259r6bpbc0000gp/T/tramp.33934lsP’ with ‘base64-decode-region’...
> Tramp: Decoding local file ‘/var/folders/xp/6j_21nwx08v0gk4259r6bpbc0000gp/T/tramp.33934lsP’ with ‘base64-decode-region’...done
> Tramp: Inserting ‘/sshx:server:/home/me/work/project/.nrepl-port’...done
> [nREPL] Establishing direct connection to server:36433 ...
> [nREPL] Direct connection to server:36433 failed
> nrepl-connect: [nREPL] Cannot connect to server:36433
> 

Tried restarting emacs, lein, ssh connection, etc. 
Any clues? Any way to get you more info? 

Thanks,
Shlomi

**Comment by bbatsov** [comment]
Seems you're impacted by this change `Don't try to use ssh automatically when connecting to remote hosts and a direct connection fails. See nrepl-use-ssh-fallback-for-remote-hosts.`. Simply put - this ssh fallback was confusing for many people and it was disabled by default.

**Comment by vadali** [comment]
Thanks @bbatsov for your quick reply! 

Man, I wish I'd notice that somehow before.. I use remote lein'ing all the time, my laptop is simply an ssh/emacs terminal :)

For reference, add `(setq nrepl-use-ssh-fallback-for-remote-hosts 't)` to your init.el to gain back ssh capabilities.

Thanks for Cider man, I love it

**Comment by vspinu** [comment]
I think there there should be an extra line in the message buffer:

```
 [nREPL] ssh fallback for remote hosts disabled (see `nrepl-use-ssh-fallback-for-remote-hosts`)
```

All puzzled folks will be looking there first.

**Comment by vadali** [comment]
@vspinu That would have made a major difference.
