### ISSUE TITLE
cider-eval-defun-at-point does not appear to work in .cljc files in CIDER 0.15

### ISSUE THREAD

**Issue by alasdairm** [clojure-emacs/cider#2066]
Cider version 0.15 does not appear to support evaluating expressions (C-M-x) within .cljc files. A test can be created using two files with the same content, differing only in .clj vs .cljc file name extensions. C-M-x will work in the .clj file but not in the .cljc file.

## Expected behavior
Using C-M-x to evaluate (e.g.) (println "Hello") I would expect to see "Hello" in the REPL window and "=> nil" in the file

## Actual behavior
user-error: ‘cider-eval-defun-at-point’ needs a Clojure REPL.
If you don’t know what that means, you probably need to jack-in (‘C-c M-j’).

## Steps to reproduce the problem
lein new test
Start emacs
visit project.clj
M-x cider-jack-in ~ message "Connected.  Code fun!"
visit new file src/test.cljc <-- cljc file
type (println "hello")
save file
C-M-x to evaluate the expression
Emacs display message
"user-error: ‘cider-eval-defun-at-point’ needs a Clojure REPL.
If you don’t know what that means, you probably need to jack-in (‘C-c M-j’)."

When in the .cljc file emacs reports ClojureC mode
When in the .clj file emacs reports Clojure mode

### CIDER version information
;; Connected to nREPL server - nrepl://localhost:53121
;; CIDER 0.15.0 (London), nREPL 0.2.12
;; Clojure 1.9.0-alpha14, Java 1.8.0_131

### Lein/Boot version
Leiningen 2.6.1 on Java 1.8.0_131 Java HotSpot(TM) Client VM
But NB, session started with cider-jack-in

### Emacs version
GNU Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24

### Operating system
Windows 10

**Comment by dpsutton** [comment]
@alasdairm can you try a seemingly strange behavior for me? Crank up your repl and try to evaluate this again, and I'll bet you get the same error. Then focus in the clojure repl, maybe evaluate something trivial in there like `(+ 1 1)`. Then go back to your cljc file and try to evaluate it again.

I think there was a change to the dispatching method that would look up the last repl you were in and this may have a bug if there is no such repl.

**Comment by alasdairm** [comment]
Tried that but see the same behaviour in the file.  I have two files test.clj and test.cljc I can switch back and forth between them.  Evaluation works in the test.clj file but not the test.cljc.  The files just have (println "Hello") in them, nothing else.

**Comment by alasdairm** [comment]
If I try and start a REPL or connect to one I am told there is an existing REPL.

**Comment by dpsutton** [comment]
I made a new project,
`lein new dispatch`, renamed core to test.clj and then copied to test.cljc. I'm able to evaluate in both repls after `cider-jack-in`. Is there a clojurescript jack in requirement? Perhaps some other repro steps that I'm missing?

**Comment by alasdairm** [comment]
I followed your steps and still get the error. I will check my config.

**Comment by alasdairm** [comment]
If I go into test.cljc and switch the major mode from ClojureC mode to Clojure mode, C-M-x starts working. If I switch back into ClojureC mode it stops. Equally, going into ClojureC mode in test.clj causes the problem to manifest in test.clj.  It appears to be something specific to ClojureC mode.

**Comment by vspinu** [comment]
Fixed in ea6aa352f7e

**Comment by alasdairm** [comment]
(with apologies for the late response). Yes - updated cider-client.el as per that change and evaluation now working in .cljc files.
