### ISSUE TITLE
Potential improvements to spec browser

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider#2074]
The recently added spec browser is great but still raw. I am listing here some suggestions for improvements in case @jpmonettas, @xiongtx or someone else are willing to have a look.

  - There should be intermediate narrowing between `cider-browse-spec` and `cider-browse-spec-all`. Something like `cider-browse-ns-spec` and `cider-browse-project-spec`.
  - Currently everything is displayed in one buffer `*cider-spec-browser*` which is then switched between `cider-browse-spec-view-mode` and `cider-browse-spec-mode`. This is non-idiomatic and sometimes confusing. For instance, open the spec listing, press RET on one of them and then "l" (help-go-back). You are not ending in the original spec browser. 
  - Relatedly, I think the actual spec view should be opened along side the listing buffer (like grep, occur, compilation, helm etc. do it). Then RET would pop-up to the spec view buffer without closing the listing buffer. A standard extra key (`o` or `C-o`) to show the view but don't pop-up to it should also be there.

**Comment by xiongtx** [comment]
> There should be intermediate narrowing between `cider-browse-spec` and `cider-browse-spec-all`. Something like `cider-browse-ns-spec` and `cider-browse-project-spec`.

I agree. `cider-browse-ns-all` shows a list of namespaces, then allows the user to explore vars in a namespace. It doesn't list *all* vars at once.

> Currently everything is displayed in one buffer `*cider-spec-browser*` which is then switched between `cider-browse-spec-view-mode` and `cider-browse-spec-mode`. This is non-idiomatic and sometimes confusing. For instance, open the spec listing, press RET on one of them and then "l" (`help-go-back`). You are not ending in the original spec browser.

No, you use `^` (mnemonically "top") to go back to the spec browser. The spec browser, which is a listing of specs, is not part of the forward / backward system of inspecting individual specs.

> Relatedly, I think the actual spec view should be opened along side the listing buffer (like grep, occur, compilation, helm etc. do it). Then `RET` would pop-up to the spec view buffer without closing the listing buffer. A standard extra key (`o` or `C-o`) to show the view but don't pop-up to it should also be there.

Putting the list of spec and details of individual specs in separate buffers sounds fine. I'm not sure how useful the pop-up functionality would be, but I'll explore and see.

**Comment by vspinu** [comment]
> No, you use ^ (mnemonically "top") to go back to the spec browser. 

It's an inconvenient design. List of vars is long and when I navigate to the part with all the vars in my ns I expect to stay there on return. But ^ re-generates the list brings me always to the top of the list.

> The spec browser, which is a listing of specs, is not part of the forward / backward system of inspecting individual specs.

Yes. And this is precisely why reusing the same buffer for this is not the ideal UI. 

> I'm not sure how useful the pop-up functionality would be,

Just as useful as it is with helm (helm-execute-persistent-action) and with standard igrep, occur, compilation etc buffers (`C-o` by default).

**Comment by jpmonettas** [comment]
> There should be intermediate narrowing between cider-browse-spec and cider-browse-spec-all. Something like cider-browse-ns-spec and cider-browse-project-spec.

Currently cider-browse-spec-all always ask for a regexp to narrow down your specs. I don't think it makes sense to have ns-spec or project-spec since specs don't belong to a project or a ns, is something you register globally under a name.

> Currently everything is displayed in one buffer *cider-spec-browser* which is then switched between cider-browse-spec-view-mode and cider-browse-spec-mode. This is non-idiomatic and sometimes confusing. For instance, open the spec listing, press RET on one of them and then "l" (help-go-back). You are not ending in the original spec browser.

I made it that way because there isn't a big difference between the spec listings and the subsequent "spec view". For me it is a registry browser, and the registry is just a graph you can follow links. The only thing special about `cider-browse-spec-all` is that it shows all the graph nodes.
I understand that its not behaving like those other cider functionality so if we figure out a way of doing it I can work on that.

**Comment by vspinu** [comment]
> specs don't belong to a project or a ns, is something you register globally under a name.

Sure, but they are all defined in some ns. I want to see only my own specs and don't care about potentially thousands of specs from other projects. Doesn't clojure.spec preserve the ns metadata within the specs?

**Comment by jpmonettas** [comment]
Currently when I want to do that I just use `cider-browse-spec-all` narrowing with a regex.

```clojure
user> (meta (first (keys (s/registry))))
nil

user> (meta (first (vals (s/registry))))
{:line 1136, :column 5, :clojure.spec.alpha/name :clojure.core.specs.alpha/local-name}
```

At least `[org.clojure/spec.alpha "0.1.123"]` doesn't seem to store any ns info in it's meta.

**Comment by vspinu** [comment]
[CLJ-2037](https://dev.clojure.org/jira/browse/CLJ-2037) and [CLJ-2194](https://dev.clojure.org/jira/browse/CLJ-2194). The fix for the `:file` metadata is super easy,  so hopefully it gets in, in some form, by the 1.9 release.

**Comment by bbatsov** [comment]
Unless people upvote the tickets in JIRA that's unlikely.

**Comment by xiongtx** [comment]
@jpmonettas Can you take a crack at this? Personally, when I do use the spec browser, I use the [helmized interface](https://github.com/clojure-emacs/helm-cider#specs), so I don't have a lot of motivation to work on this :man_shrugging:.

**Comment by jpmonettas** [comment]
@xiongtx  What needs to be done here?

> There should be intermediate narrowing between cider-browse-spec and cider-browse-spec-all. Something like cider-browse-ns-spec and cider-browse-project-spec

There is no way around that yet. https://dev.clojure.org/jira/browse/CLJ-2037 is still open, we recently discussed that in https://github.com/clojure-emacs/cider/issues/2163#issuecomment-357663035.

**Comment by xiongtx** [comment]
There are some other points by @vspinu worth considering.
