### ISSUE TITLE
go to definition for java class

### ISSUE THREAD

**Issue by xfcjscn** [clojure-emacs/cider#2075]
I can not go to defintion (M-.) for java class, is it possible in cider?

**Comment by bbatsov** [comment]
It should work out of the box for all classes that have their source added to your classpath.

**Comment by xfcjscn** [comment]
After read the related implementation, I found the root cause: I used jre instead of jdk as runtime, so cider can not find the source. Better to have this documented.

**Comment by bbatsov** [comment]
> After read the related implementation, I found the root cause: I used jre instead of jdk as there is no tools.jar in jre, so cider can not find the source. Better to have this documented.

Well, the JRE simply doesn't ship sources for obvious reasons, so it's actually the same problem. I'm relatively certain this is mentioned somewhere in the docs.
