### ISSUE TITLE
Compilation error displays additional REPL frame

### ISSUE THREAD

**Issue by rogergl** [clojure-emacs/cider#2080]
## Expected behavior

A compilation error caused by "load this buffer" should add the "display error" frame to the current frame layout

## Actual behavior

The error frame and an addition REPL frame is displayed, although the REPL frame is already displayed.
 
## Steps to reproduce the problem

Have a buffer with a compilation error and load this buffer into the REPL (,sb on Spacemacs)

### CIDER version information

CIDER 0.15.1snapshot (package: 20170729.133), nREPL 0.2.12

### Lein/Boot version

Leiningen 2.7.1 on Java 1.8.0_144 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

 Emacs 25.1, Spacemacs

### Operating system

Mac OS X 10.12.6

**Comment by bbatsov** [comment]
Can you show us the concrete problem? Right now I can't quite get what's wrong.

**Comment by xiongtx** [comment]
I've not idea what's wrong here. Seems like this can be closed.
