### ISSUE TITLE
Ability to turn off eldoc for `SomeClass.` forms

### ISSUE THREAD

**Issue by jonathanj** [clojure-emacs/cider#2087]
The eldoc for all Java class instantiation forms using the `SomeClass.` style is not very informative but maybe better than nothing. However when using GNU Global (via ggtags, for example) cider produces an eldoc before ggtags has the opportunity to produce (a more useful) one. On bare class names, or the expanded `(new SomeClass)` form, the ggtags eldoc is produced.

Disabling the functionality altogether is undesirable as Cider's eldocs are generally quite good.

It looks like a conditional could be introduced to `cider-eldoc-info` for the `SomeClass.` case to control this behaviour?

**Comment by bbatsov** [comment]
What's the eldoc produced by `ggtags`?

**Comment by bbatsov** [comment]
> It looks like a conditional could be introduced to cider-eldoc-info for the SomeClass. case to control this behaviour?

Everything's possible, I just don't like adding branching for something unless a lot of people think it's useful.

**Comment by jonathanj** [comment]
The eldoc produced by ggtags is from the Java tags so it's something like `public class Foo implements IFoo { [guess]` (it would be better if this were the possible constructors, of course) for a class instantiation and `public int bar(int a, int b) { [guess]` for a method.

That being said, a while after posting this issue I discovered that I could modify the syntax table for Clojure so that `.` is not considered part of the symbol, which suits me better and doesn't require any modification to cider, so I'll close the issue. Thanks!
