### ISSUE TITLE
cider-jack-in broken repl with latest from elpa

### ISSUE THREAD

**Issue by twillis** [clojure-emacs/cider#2092]
## Expected behavior

`M-x cider-jack-in` and eval anything such as (+ 2 2) repl should output 4

## Actual behavior
```
ERROR: Unhandled REPL handler exception processing message {:ns user, :op eval, :code (+ 2 2)
, :file *cider-repl prjclj*, :line 43, :column 7, :session 0b768c5f-b56a-4ef6-ab5c-3e3cad94718b, :id 13}
java.lang.IllegalAccessError: with-safe-transport does not exist, compiling:(cider/nrepl/middleware/info.clj:1:1)
...
```

## Steps to reproduce the problem

`lein new tstprjclj`

open the generated `project.clj` 

eval `(+ 2 2)` in the repl

`M-x cider-jack-in`

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

## Environment & Version information

OSX

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:57198
;; CIDER 0.16.0snapshot (package: 20171001.112), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_40
```

### Lein/Boot version

Leiningen 2.7.1 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 25.2.1 (x86_64-apple-darwin16.6.0, Carbon Version 157 AppKit 1504.83) of 2017-07-25

### Operating system
OSX Sierra 10.12.6

**Comment by vspinu** [comment]
Do you set your own cider middleware stack somewhere?

**Comment by slipset** [comment]
No

**Comment by vspinu** [comment]
Most likely a consequence of concurrent  namespace loading in clojure.  More details in #2078. There is no imediate fix for that, sorry.

**Comment by slipset** [comment]
Maybe revert #2078 while a fix is being made, since it renders Cider unusable?

**Comment by twillis** [comment]
I have a clean .lein/profile.clj and just the clojure layer enabled in spacemacs I did an update this morning and I can't use cider now 😓

**Comment by vspinu** [comment]
> Maybe revert #2078 

#2078 is not a culprit, it's an attempt to solve the problem.

Try the following for time being:

```el
(defun cider--connected-handler ()
  (let ((cider-enlighten-mode nil))
    (cider-make-connection-default (current-buffer))
    (cider-repl-init (current-buffer))
    (cider--check-required-nrepl-version)
    (cider--check-clojure-version-supported)
    (cider--check-middleware-compatibility)
    (cider--subscribe-repl-to-server-out)
    (when cider-auto-mode
      (cider-enable-on-existing-clojure-buffers))
    (sleep-for 0.1) ;; <-- Increase timeout till it works 
    (cider--debug-init-connection)
    (run-hooks 'cider-connected-hook)))
```

Does the manual sleep-for before debug init solves the problem? If you comment `(cider--debug-init-connection)` line, does it fix it?

**Comment by slipset** [comment]
This worked for me with the 0.1 timeout.

**Comment by vspinu** [comment]
And without the time-out?

**Comment by vspinu** [comment]
Ok. Then let's add the temporary delay in the master till I figure out how to fix this properly.

Just to check that nothing went wrong with your CIDER install, when removing (sleep-for 0.1), does it work? It would be the same code as in the current master.

**Comment by slipset** [comment]
Both removing sleep and cider-debug-init-connection worked for me.

**Comment by vspinu** [comment]
That means something went wrong with your CIDER installation. Removing sleep-for from the above results in the current CIDER's code in the master.

**Comment by slipset** [comment]
That's interesting...

**Comment by vspinu** [comment]
clojure-emacs/cider-nrepl#444 should be fixing this.  I cannot reproduce the problem on my machine whatever I try, so I will have to rely on you to confirm that the "lock" fix has indeed worked.

**Comment by benedekfazekas** [comment]
had the same yesterday. had to downgrade back to latest stable. is the fix on clojars?

**Comment by bbatsov** [comment]
Not yet.

**Comment by bbatsov** [comment]
Anyways, more people are welcome to take a look at the relevant PR and provide feedback before we merge it.

**Comment by vspinu** [comment]
Please test the proposed fix:

```
git clone -b deferred-middleware-extras https://github.com/vspinu/cider-nrepl.git
cd cider-nrepl/
lein install
## restart CIDER session in emacs
```

I cannot come with a small reproducible example to report it on JIRA, but I am fairly confident that it has something to do with the concurrent loading of transitive dependencies.

**Comment by benedekfazekas** [comment]
tried but failed to test it due to a corporate firewall :/

**Comment by twillis** [comment]
@vspinu  new cider-nrepl fixed my issue.

**Comment by julienfantin** [comment]
> git clone -b deferred-middleware-extras https://github.com/vspinu/cider-nrepl.git
> cd cider-nrepl/
> lein install


This works with `cider-jack-in` but still fails for `cider-connect`:

```
[nREPL] Establishing direct connection to localhost:7888 ...
[nREPL] Direct connection to localhost:7888 established
nrepl-send-sync-request: Sync nREPL request timed out (op describe)
```

**Comment by vspinu** [comment]
> still fails for cider-connect:

That's likely a different issue. You need to update your plugin version on the server side (` :plugins [[cider/cider-nrepl "0.16.0-SNAPSHOT"]]`, or in case you explicitly list it, new middleware comes under [different names](https://github.com/vspinu/cider-nrepl/blob/75641b634faf81b06b2a4977b1f532e0909f725a/project.clj#L34-L55).
