### ISSUE TITLE
cider-inspect shows "wrong type argument"

### ISSUE THREAD

**Issue by MicahElliott** [clojure-emacs/cider#2093]
Emacs v25.3.1, Arch Linux, CIDER 0.16.0snapshot (package: 20171001.112)

For simple code:

    (def x '(:a :b :c))

Placing point on `x` and pressing `C-c M-i` does nothing; is that a problem?  Point right after x, mini-buffer shows:

    cider-inspector--render-value: Wrong type argument: char-or-string-p,
      ("Class" ": " ("value" "java.lang.String" 0) ("newline") "Value: " "\"(:a :b :c)\"")

Why is there an error?  Am I using this wrong?  It would be nice to see `Class` as `IPersistentList` instead of `String` (if I'm reading that right).

**Comment by vspinu** [comment]
Probably something went wrong with CIDER installation.

Works fine here:

```clj
Class: clojure.lang.PersistentList
Meta Information: 
  :line = 5
  :column = 9
Contents: 
  0. :a
  1. :b
  2. :c
```

**Comment by bbatsov** [comment]
Hmm, the list has meta? I thought it was supposed to be associated with the var. Seems like some bug.

**Comment by vspinu** [comment]
It's the meta from the var "x".

**Comment by bbatsov** [comment]
Given the lack of activity here I guess we can close this ticket.
