### ISSUE TITLE
Jump to variable defined in let binding

### ISSUE THREAD

**Issue by AndreaCrotti** [clojure-emacs/cider#2095]
At the moment `cider-find-var` will only find variables defined in namespaces.
Would be nice if it could be able to find and jump to variables defined in the local scope by a `let` form.

**Comment by bbatsov** [comment]
Just a note for someone willing to work on this, here's an outline of how this can be implemented:

* use https://github.com/lambdaisland/parseclj or middleware side parsing of the enclosing expressions all the way to the top-level to build a map of all locals defined there and their locations
* try to resolve something as a local first and if the fails check whether something is a var as usual

**Comment by xiongtx** [comment]
Note that `parseclj` is [not (yet) on MELPA](https://melpa.org/#/?q=parseclj).

**Comment by divs1210** [comment]
this would be really good to get working.

**Comment by divs1210** [comment]
also, @bbatsov, github shows me an error regarding the `FUNDING.yml` file when I click Sponsor

**Comment by divs1210** [comment]
I currently use `dumb-jump-go` in case `cider-find-var` fails. Maybe CIDER could automatically fall back to that till this is implemented?

**Comment by bbatsov** [comment]
Well, I'd rather prefer that we implement this properly, but it seems that no one is interested in working on this and I simply don't have the time. With `parseclj` the implementation should be pretty straightforward and this could done directly in `clojure-mode`, as you don't really need a REPL connection if you're parsing the expression client-side.

**Comment by divs1210** [comment]
I'm an elisp n00b, unfortunately.
had a look at `parseclj` and `cider-find`.
don't know where to start.

**Comment by divs1210** [comment]
@narendra9 wondering if you would find this interesting.

**Comment by narendraj9** [comment]
@divs1210 Here is a quick and dirty implementation: https://gist.github.com/narendraj9/9e98aa5e227f3fbf46a041728cf841b2

**Comment by narendraj9** [comment]
There are numerous ways to have local bindings, e.g. de-structuring with `{when-let,if-let,defun}` but ^ only covers `let` bindings. Maybe you can extend it further to support those.

**Comment by divs1210** [comment]
Thank you, @narendraj9! 🙏 
We could get rid of all destructuring by macroexpanding the source, which would convert everything to `let`s, but I'm guessing then we'd want sourcemaps to find the exact line.

**Comment by divs1210** [comment]
Another approach would be to first try and resolve it as a var, and if not found, jump to the first occurrence in the top level sexp.

**Comment by divs1210** [comment]
an easier approach might be to try and resolve it as a var, and if not found, jump to the first occurrence in the top level sexp.
