### ISSUE TITLE
get all namespaces including unloaded

### ISSUE THREAD

**Issue by drorbemet** [clojure-emacs/cider#2098]
Hi, I want to use the clojure namespaces and java-classes provided by the packages on the classpath 
of a clojure project within https://github.com/abo-abo/swiper counsel completion functions.

I looked at https://github.com/alexander-yakushev/compliment 
but if I can get unloaded namespaces from nrepl in cider 
I would like to avoid an aditional dependency and 
untill now I am unsure how it would play along with ivy counsel.

clojure.core/all-ns seems to list only loaded namespaces, correct?

I searched the cider docs and tried to understand and adapt 
cider-sync-request:ns-list and cider-sync-request:complete but without success so far.
Maybe it's already implemented somewhere?

Thanks a lot for the bits I am missing to solve this. 

## searching for a solution
This example doesn't deliver unloaded namespaces:
```emacs-lisp
(defun cider-sync-request:ns-list-no-filter ()
  (thread-first `("op" "ns-list")
    (cider-nrepl-send-sync-request)
    (nrepl-dict-get "ns-list")))
```

How is the dict in completions configured in order to deliver just all namespaces without any annotations?
```emacs-lisp
(defun cider-sync-request:completions ()
  (->> (thread-first `("op" "complete")
         (cider-nrepl-send-sync-request)
         (nrepl-dict-get "completions"))
       (-flatten)
       (-distinct)))
```

## draft of solution
```emacs-lisp
(defun cider-sync-request:ns-list-all ()
  "Get a list of all namespaces including unloaded. 
Just like cider-sync-request:complete does."
(thread-first `("what could I choose here?")
    (cider-nrepl-send-sync-request)
    (nrepl-dict-get "and what could I choose here?")))
```

**Comment by bbatsov** [comment]
We don't have any functionality to retrieve a list of non-loaded namespaces. For something like this you'd normally have to process and parse all the source files of a project, which I don't really like as it's a rather slow and complex thing to do. `compliment` doesn't return unloaded namespaces either.

**Comment by drorbemet** [comment]
Ok, thanks for clarifying.
