### ISSUE TITLE
cider-current-ns can get confused by namespace metadata with newline

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#2100]
Given this Clojure ns declaration:

```
(ns ^{:doc "An awesome namespace"}
    my-ns
   ...)
```

When one places the cursor **exactly** in the `my-ns` line, `(cider-current-ns)` will return `"^{:doc"`.

Both conditions must happen: newline after metadata, and cursor being in the `my-ns` line.

It works well in all other cases.

I'm using CIDER latest. This looks environment-independent and easy to reproduce, so kindly allow me to skip the issue template.

Cheers - Victor

**Comment by bbatsov** [comment]
And this is most likely an issue with `clojure-mode`, not CIDER. 😉

**Comment by bbatsov** [comment]
On a related note:

```
(ns ^{:doc "An awesome namespace"}
    my-ns
   ...)
```

Would normally be written as:

```
(ns 
   "An awesome namespace"
    my-ns
   ...)
```

**Comment by bbatsov** [comment]
Yeah, I can now confirm that this is a bug in `clojure-find-ns`.

**Comment by xiongtx** [comment]
Actually, this can occur any time when point is in the middle of what is considered an "ns form" by the `clojure-namespace-name-regex` regexp. E.g. w/ `|` as point:

```clojure
(ns ^{:doc |"An awesome namespace"}
    my-ns
   ...)
```

or

```clojure
(ns ^{:doc "An awesome namespace"} |my-ns
   ...)
```

A simple solution would be to always go to end of line, so we don't do the `re-search-backward` in `clojure-find-ns` from the middle of the match.

**Comment by vemv** [comment]
> And this is most likely an issue with clojure-mode, not CIDER. 😉

Whoops! Sorry.

> Would normally be written as [...]

Sure 👍 it was a minimal example.

Thanks both for the fix!
