### ISSUE TITLE
cider-format-buffer can delete whole buffer's contents on invalid Clojure syntax

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#2102]
Given the following clojure buffer with a dangling parens (doesn't matter if it has a ns form):

```
"Precious content"

(
```

if I run `(cider-format-buffer)`, the whole buffer's contents will disappear.

Issue is easy to cleanly reproduce; GH template seems excessive in this case.

Using:

```
cider-20171001.112
clj-refactor-20170720.712
clojure-mode-20170819.2159
paredit-20170405.1149
```

Cheers - Victor

**Comment by xiongtx** [comment]
Cannot reproduce. You mean you don't see the following?

![image](https://user-images.githubusercontent.com/1624090/32248742-db55dc16-be43-11e7-8bfe-e7a60db67a97.png)

**Comment by vemv** [comment]
I do get that buffer! (Hadn't noticed before; under my setup most 'foreign' windows/buffers don't pop up)

```
 Show: Project-Only All 
  Hide: Clojure Java REPL Tooling Duplicates  (78 frames hidden)

  This is an unexpected CIDER middleware error.
  Please submit a bug report via `M-x cider-report-bug`.

  If these stacktraces are occuring frequently, consider using the
  button(s) below to suppress these types of errors for the duration of
  your current CIDER session. The stacktrace buffer will still be
  generated, but it will "pop under" your current buffer instead of
  "popping over". The button toggles this behavior.

 Suppress format-code-error 

1. Unhandled java.lang.Exception
   Unexpected EOF. [at line 39, column 1]

                reader.clj:   18  cider.inlined-deps.cljfmt.v0v5v6.rewrite-clj.v0v5v2.rewrite-clj.reader/throw-reader
                reader.clj:   11  cider.inlined-deps.cljfmt.v0v5v6.rewrite-clj.v0v5v2.rewrite-clj.reader/throw-reader
               RestFn.java:  425  clojure.lang.RestFn/invoke
                  core.clj:   78  cider.inlined-deps.cljfmt.v0v5v6.rewrite-clj.v0v5v2.rewrite-clj.parser.core/eval106591/fn
              MultiFn.java:  229  clojure.lang.MultiFn/invoke
                reader.clj:  132  cider.inlined-deps.cljfmt.v0v5v6.rewrite-clj.v0v5v2.rewrite-clj.reader/read-with-meta
                reader.clj:  128  cider.inlined-deps.cljfmt.v0v5v6.rewrite-clj.v0v5v2.rewrite-clj.reader/read-with-meta
                  core.clj:   34  cider.inlined-deps.cljfmt.v0v5v6.rewrite-clj.v0v5v2.rewrite-clj.parser.core/parse-next
                  core.clj:   32  cider.inlined-deps.cljfmt.v0v5v6.rewrite-clj.v0v5v2.rewrite-clj.parser.core/parse-next
                  core.clj:   42  cider.inlined-deps.cljfmt.v0v5v6.rewrite-clj.v0v5v2.rewrite-clj.parser.core/parse-delim/fn
                reader.clj:  141  cider.inlined-deps.cljfmt.v0v5v6.rewrite-clj.v0v5v2.rewrite-clj.reader/read-repeated
```

---

I just enabled `(setq debug-on-error t)` for getting an elisp stacktrace as well:

```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  cider--format-buffer(cider-sync-request:format-code)
  cider-format-buffer()
  eval((cider-format-buffer) nil)
  eval-expression((cider-format-buffer) nil)
  funcall-interactively(eval-expression (cider-format-buffer) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by xiongtx** [comment]
You get the error buffer but the contents of the source buffer is still erased? I don't get that. 

Can you try w/ `emacs -Q` so we can exclude issues w/ your init file?

**Comment by vemv** [comment]
Can't `-Q` since that would't load CIDER or anything. At least that's how
my emacs initialization is organized...

Tried disabling various stuff in my init; no luck.

I played a bit with the cider elisp code. I'd say the issue is:
`(cider-sync-request:format-code "(")` returns nil, but the
`cider--format-buffer` implementation expects a string somewhere.

You might be able to reproduce with: (cider--format-buffer (lambda (_) nil))

**Comment by vemv** [comment]
I know the issue!

```
(defun cider--format-buffer (formatter)
  "Format the contents of the current buffer.

Uses FORMATTER, a function of one argument, to convert the string contents
of the buffer into a formatted string."
  (let* ((original (substring-no-properties (buffer-string)))
         (formatted (funcall formatter original)))
    (unless (equal original formatted)
      (erase-buffer)
      (insert formatted))))
```

`(insert formatted)` with `formatted` being nil causes the original `(wrong-type-argument char-or-string-p nil)` error.

Fix:

```diff
- unless (equal original formatted)
+ (unless (or (not formatted) (equal original formatted)))
...
```

**Comment by xiongtx** [comment]
Still doesn't explain why you're seeing this issue that I'm not. An unmatched paren like that should result in an EOF error thrown by the reader.

**Comment by vemv** [comment]
It is reasonable to try determining the exact cause, however as usual my
emacs setup has accumulated lots of stuff over the years. Bisecting could
be a painful effort.

Nil check seems cheap?

Cheers - Victor

**Comment by xiongtx** [comment]
If someone else can reproduce (cc @bbatsov), I'll look into it further. Randomly adding null checks is not the way to go.

**Comment by bbatsov** [comment]
I agree. I'll try to find some time to test this myself.

**Comment by bbatsov** [comment]
I can't reproduce this myself.

**Comment by bbatsov** [comment]
I've also checked the message exchange between CIDER and nREPL and there's no response except the error. 

At any rate there's a real problem here that's easy to fix - the middleware should gracefully handle bad code and send back some meaningful message to CIDER.

**Comment by bbatsov** [comment]
Basically the code here https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/format.clj#L13 should feature some exception handling and return some meaningful message to CIDER when this happens.

**Comment by bbatsov** [comment]
(or we can add `check-parens` in the CIDER command)
