### ISSUE TITLE
Option to disable syntax highlighting

### ISSUE THREAD

**Issue by lgrapenthin** [clojure-emacs/cider#2108]
I'd like to disable syntax highlighting. Is there an option?

**Comment by xiongtx** [comment]
You can turn [`font-lock-mode`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Font-Lock.html) off.

**Comment by bbatsov** [comment]
I guess he's actually talking about CIDER's dynamic font-locking. There's already a variable for this - `cider-font-lock-dynamically` (and it's even featured in the manual, which no one ever reads :-) ).
