### ISSUE TITLE
Dependency conflict on tools.nrepl (when cider injects depdencies)

### ISSUE THREAD

**Issue by dchelimsky** [clojure-emacs/cider#2110]
## Expected behavior

I should be able to start a repl with new leiningen project with `:pedantic? :abort`

## Actual behavior

Instead I get the following error:

```
$ lein repl
Possibly confusing dependencies found:
[org.clojure/tools.nrepl "0.2.12" :exclusions [org.clojure/clojure]]
 overrides
[cider/cider-nrepl "0.15.1"] -> [org.clojure/tools.nrepl "0.2.13" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[cider/cider-nrepl "0.15.1" :exclusions [org.clojure/tools.nrepl]]

Aborting due to :pedantic? :abort
```

## Steps to reproduce the problem

```
$ lein new example
Generating a project called example based on the 'default' template.
The default template is intended for library projects, not applications.
To see other templates (app, plugin, etc), try `lein help new`.
$ cd example/
$ vi project.clj # add `:pedantic? :abort` to the project map
$ lein repl
Possibly confusing dependencies found:
[org.clojure/tools.nrepl "0.2.12" :exclusions [org.clojure/clojure]]
 overrides
[cider/cider-nrepl "0.15.1"] -> [org.clojure/tools.nrepl "0.2.13" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[cider/cider-nrepl "0.15.1" :exclusions [org.clojure/tools.nrepl]]

Aborting due to :pedantic? :abort
```

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:52280
;; CIDER 0.15.1 (London), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_131
```
### Lein/Boot version

$ lein -v
Leiningen 2.7.1 on Java 1.8.0_131 Java HotSpot(TM) 64-Bit Server VM```

### Emacs version

GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0) of 2017-09-11

### Operating system

OS X 10.12.6 (16G1036)

**Comment by bbatsov** [comment]
The only solution I see for this is to just update the nREPL dependency in Leiningen. @dchelimsky Do you have another possible solution in mind?

**Comment by dchelimsky** [comment]
@bbatsov I started to look into making a pull request for this, changing the version on https://github.com/clojure-emacs/cider/blob/46367ce4088cd7ec57895bff3aa2d9f1f6c4216d/cider.el#L303 and https://github.com/clojure-emacs/cider/blob/7a7225929138d13163b96d68fd80b018de357ca0/cider-interaction.el#L256, but ran into other breakage that I didn't understand so reported it as an issue instead. So that's what I had in mind. In the mean time, I was able to get around this by telling cider not to inject dependencies and then specifying what I want in a :repl profile. This suggests to me that the problem is not within leiningen itself, but I could be misunderstanding it.

**Comment by bbatsov** [comment]
That should actually be updated in Leiningen IMO. CIDER is using the latest nREPL for a reason (a bugfix it includes) and ideally Leiningen should use the latest version as well. I've filed a PR there. 

For the end users of CIDER it's always better to be running the latest version of nREPL.

**Comment by bbatsov** [comment]
See https://github.com/technomancy/leiningen/pull/2367

**Comment by bbatsov** [comment]
And https://github.com/boot-clj/boot/pull/664

**Comment by dchelimsky** [comment]
Thanks for all the follow through!

**Comment by bbatsov** [comment]
My PRs were merged in both Lein and Boot. I guess we can now only hope they'll cut new releases soon.
