### ISSUE TITLE
cider-find-var: jump to namespace-qualified keywords

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#2112]
Hi there!

I have a feature request, hopefully a reasonable one.

When using `cider-find-var` over a ns-qualified keyword such as e.g. `::other.namespace/foo`, CIDER won't jump to anything.

This is partly justified, as keywords are literal values, and as such don't belong anywhere in particular.

OTOH, it'd be intuitively useful that it jumps to the first occurrence of `::foo` in `other.namespace`.

Maybe `other.namespace` has more occurrences of `::foo` but we pick the first one because that's the best-effort thing to do.

If `other.namespace` had no occurrences of `::foo`, we'd still jump to that namespace, it's very probably what the user wants. The user could have a look in the namespace and check himself that there are no occurrences of ::foo - that's still a useful activity when programming.

Cheers - Victor

**Comment by oliyh** [comment]
Hi,

I wanted this too, specifically for re-frame registrations. My solution (which is re-frame specific) is here: https://github.com/oliyh/re-jump.el

It lets you jump from `::model/foo` to something that looks like `(re-frame/reg-sub ::foo)` in the `model` ns. It works very well for my use case!

**Comment by vemv** [comment]
Nice!

I took a look - is it actually re-frame specific? The code looks clean although there might be an implicit assumption I fail to see.

**Comment by oliyh** [comment]
Hi @vemv,

The one assumption is on this line: https://github.com/oliyh/re-jump.el/blob/master/re-jump.el#L22

It's looking for something that has a "reg" which is the pattern that re-frame uses. I found I needed this because the first instance in a file wouldn't necessarily be the registration, but that's the only bit you need to change if you want a much more generic case.

**Comment by bbatsov** [comment]
I guessing this can be done relatively easy:

* we can check if the thing at point is a namespaced symbol
* extract the namespace
* do find ns for the namespace
* search forward in its buffer for the first mention of the symbol

**Comment by bbatsov** [comment]
I see @oliyh did something along those lines but for some reason decided not to use `cider-find-ns`, which would simplify things a lot IMO.

**Comment by oliyh** [comment]
Thanks for the tip @bbatsov :)

The problem with the first mention is that it may still be a usage rather than a declaration. re-jump searches for the registration. I could do the same for (def ::xyz) if the search for reg failed and then it should handle this use case too.

**Comment by bbatsov** [comment]
Of you can do it configurable in the spirit of Emacs and people would be able to just set different values for different projects. :-)

Anyways, feel free to submit this to CIDER if you want.

**Comment by vspinu** [comment]
> I wanted this too, specifically for re-frame registrations.

My solution for such case is to add custom regexp to imenu and then use imenu-anywhere to jump around.

Specifically, for re-frame it's:

```el
(add-to-list 'imenu-generic-expression
               '("re-frame" "(register-\\(handler\\|sub\\)[ \n]+\\([^\t \n]+\\)" 2)
               t)
```

**Comment by bbatsov** [comment]
That's a very cool idea!

**Comment by bbatsov** [comment]
I've added something similar to @oliyh's command. @vemv Feel free to play with it.

**Comment by vemv** [comment]
Tried out!

Unfortunately the functionality won't work for me: it will print `Can't find namespace xxx`.

The culprit seems to be this call: `(cider-resolve-alias (cider-current-ns) ns-qualifier)`

If you see its implementation:

```
(defun cider-resolve-alias (ns alias)
  "Return the namespace that ALIAS refers to in namespace NS.
If it doesn't point anywhere, returns ALIAS."
  (or (cider-resolve--get-in ns "aliases" alias)
      alias))
```

You'll see that it does a somewhat dubious `or`, so the fn returns either a useful result, or a result that will cause `cider-find-keyword` to fail.

So the root cause (at least in my case) is that `cider-resolve-alias` is not working. In any given ns with an active conection, `(cider-resolve-alias (cider-current-ns) "set")` will return "set" rather than "clojure.set".

Using clojurescript. CIDER works great for me (no setup issues) so IDK why `cider-resolve-alias` isn't working.

**Comment by vemv** [comment]
I just checked, and this functionality and `cider-resolve-alias` both work well in clojure, but not in cljs for me

**Comment by bbatsov** [comment]
Maybe something is broken with the ns caching on ClojureScript. Run this with the Elisp debugger and see what's going on exactly there.
