### ISSUE TITLE
pretty-printing does not work with venantius/ultra lein plugin

### ISSUE THREAD

**Issue by svend** [clojure-emacs/cider#2114]
## Expected behavior

Results in the REPL are pretty-printed when pretty-printing is enabled.

## Actual behavior

Results in the REPL are printed the same as without pretty-printing.

## Steps to reproduce the problem

Create `~/.lein/profiles.clj` with the following contents:

```
{:user {:plugins [[venantius/ultra "0.5.1"]]}}
```

Create a new project:

```
lein new example
```

Start a Cider REPL:

```
emacs -q
M-x package-initialize
(open example/src/example/core.clj)
M-x cider-jack-in
M-x cider-repl-toggle-pretty-printing
(prints: Pretty printing in REPL enabled.)
```

Input a map and hit enter:

```
{:availability-zones
 [{:state "available",
   :region-name "us-east-1",
   :zone-name "us-east-1a",
   :messages []}
  {:state "available",
   :region-name "us-east-1",
   :zone-name "us-east-1b",
   :messages []}
  {:state "available",
   :region-name "us-east-1",
   :zone-name "us-east-1c",
   :messages []}
  {:state "available",
   :region-name "us-east-1",
   :zone-name "us-east-1d",
   :messages []}
  {:state "available",
   :region-name "us-east-1",
   :zone-name "us-east-1e",
   :messages []}]}
```

The result is printed on a single line instead of being pretty-printed.

### CIDER version information

```
;; CIDER 0.16.0snapshot (package: 20171001.112), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_121
```

### Lein/Boot version

Leiningen 2.7.1 on Java 1.8.0_121 OpenJDK 64-Bit Server VM

### Emacs version

GNU Emacs 26.0.90 (build 1, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29)) of 2017-10-23

### Operating system

OS X 10.12.6 Sierra

**Comment by bbatsov** [comment]
That should work on CIDER 0.21+.
