### ISSUE TITLE
Doesn't work for ClojureScript

### ISSUE THREAD

**Issue by derekchiang** [clojure-emacs/cider#2116]
## Expected behavior

`cider-doc` and `jump-to-definition` work for ClojureScript.

## Actual behavior

`cider-doc` and `jump-to-definition` only work for Clojure, but not ClojureScript.

## Steps to reproduce the problem

* Clone a full-stack Clojure/CLJS project such as [this one](https://github.com/swarmpit/swarmpit).
* Note that the project [has been set up properly](https://github.com/swarmpit/swarmpit/blob/master/project.clj#L92) to work with CLJS.
* Open a file and call `cider-jack-in-clojurescript`.
* Observe that two REPLs start up, one for Clojure and one for CLJS.
* Observe that `cider-doc` and `jump-to-definition` only works in Clojure files, but not CLJS files.

Specifically, `cider-doc` shows the prompt `Doc for:`, and `jump-to-definition` shows the prompt `Symbol:`.

### CIDER version information

```
;; CIDER 0.16.0snapshot (package: 20171001.112), nREPL 0.2.12
;; Clojure 1.9.0-alpha16, Java 1.8.0_151
```

### Emacs version

25.2.2

### Operating system

Ubuntu 17.10

**Comment by derekchiang** [comment]
So I realized that once I use `cider-eval-buffer` in the CLJS file, all Cider functionalities work.  So am I just misunderstanding how Cider is supposed to work?  Am I supposed to evaluate the entire buffer before Cider works for a given file?  I'm just confused because in `vim-fireplace` I don't have to do that.

**Comment by dpsutton** [comment]
CIDER doesn't do any static analysis or parsing of your file. It interacts with the running jvm. To get the benefits, you have to load the namespace. I often use `cider-load-buffer-and-switch-to-repl-buffer` which loads the ns. When used with prefix it sets the ns as well. But this behavior should be similar to the clojure side. For example, in a clojure file without evaluating it it should not have much information from eldoc, etc. I'm not sure how vim-fireplace works but i imagine it would be similar.

**Comment by derekchiang** [comment]
@dpsutton thanks for the clarification.  I'm guessing `vim-fireplace` must have some sort of auto-loading then.  Anyways, closing this issue.
