### ISSUE TITLE
Make it possible to differentiate a Java class from a symbol

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2121]
Just something I came across from `unrepl`:

![image](https://user-images.githubusercontent.com/103882/33611437-484b147e-d9c6-11e7-8fde-d232e3401c95.png)

Basically in `unrepl` those are font-locked differently, while normally most REPLs would font-lock them the same.

**Comment by xiongtx** [comment]
Isn't this font-locking [controlled by `clojure-mode`](https://github.com/clojure-emacs/clojure-mode/blob/118c19700c904ae6a45fb409ca795bb93ff8dbd8/clojure-mode.el#L862-L863)?

**Comment by bbatsov** [comment]
That's why I opened this ticket - `clojure-mode` can't possibly tell those apart, but our dynamic-font-locking can (if we enhance it that is).
