### ISSUE TITLE
REPL not connecting to namespace

### ISSUE THREAD

**Issue by WaygoneWilco** [clojure-emacs/cider#2125]
Hello everyone, thank you for creating such a great tool. I am having a problem connecting my repl to my namespace.

I expect that when I hit C-x C-e at the end of my namespace line, that the namespace will be loaded into the repl. This does not happen. Instead, the Messages buffer simply reports => nil. The command line of the repl, instead of starting the input line with the namespace information, the line starts with just user. Also, executing code from the file with C-c C-e works in the mini-buffer, but only if the code does not reference another portion of the code file, i.e. it works for (+ 2 2) but not (+ 2 num).

Here are the commands I used:
1) Load file C-x C-f
2) Load repl in new window, C-c M-j
3) Place pointer at end of namespace line and C-c C-e

Here is a bit more info from the messages buffer about the repl:
```
Starting nREPL server via lein repl :headless...
nREPL server started on 43489
nREPL: Establishing direct connection to localhost:43489 ...
nREPL: Direct connection established
```

CIDER 0.8.1 (package: 20141120.1746) (Java 1.8.0_151, Clojure 1.8.0, nREPL 0.2.12)

GNU Emacs 25.3.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-15

Ubuntu 16.04 LTS

Thank you

**Comment by bbatsov** [comment]
> I expect that when I hit C-x C-e at the end of my namespace line, that the namespace will be loaded into the repl. This does not happen. Instead, the Messages buffer simply reports => nil.

Well, `nil` is the result from evaluating a `ns` form. :-) That's fine.

Generally the best thing you can do is to evaluate the entire file buffer with `C-c C-k` in the beginning and just start playing with the definitions in the REPL buffer. Not sure whether you've seen videos like https://www.youtube.com/watch?v=aYA4AAjLfT0 ?

> CIDER 0.8.1 (package: 20141120.1746) (Java 1.8.0_151, Clojure 1.8.0, nREPL 0.2.12)

0.8.1 is ancient! You should really update to 0.15.1 soon!

**Comment by WaygoneWilco** [comment]
Oh boy. Thank you for the quick reply. I have not seen that video, no. I tried to figure out some of the basics, and frankly the documentation was too deep for me. I better spend some more time learning about cider... At least now I am experienced in writing up bug issues here :)

**Comment by WaygoneWilco** [comment]
Also, I found the command I was looking for: C-c M-n. To load the namespace into the repl. I'll update cider and see if this fixes things.

**Comment by WaygoneWilco** [comment]
I appears that my problem is installing emacs/cider using the instructions provided by [Clojure for the Brave and True](https://www.braveclojure.com/basic-emacs/).

**Comment by bbatsov** [comment]
Ah, yeah - those are extremely outdated unfortunately.

**Comment by bbatsov** [comment]
And I also guess we can close this now.
