### ISSUE TITLE
cider-format-buffer changes the point position

### ISSUE THREAD

**Issue by kommen** [clojure-emacs/cider#2126]
## Expected behavior

Calling `cider-format-buffer` shouldn't change the point position

## Actual behavior

Currently, if the buffer is changed by `cider-format-buffer` the point is moved to the end of the buffer.

## Steps to reproduce the problem

1) Have a buffer which would be changed by `cider-format-buffer`
2) run `cider-format-buffer`

### CIDER version information

```
;; CIDER 0.15.0snapshot (package: 20171126.150), nREPL 0.2.12
;; Clojure 1.9.0-RC2, Java 1.8.0_102
```

### Lein/Boot version

lein 2.8.1

### Emacs version

GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29)) of 2017-09-15

### Operating system

macOS 10.13.2

## Notes

I tried wrapping `cider-format-buffer` in `save-excursion`, but that did't fix the issue for me.

I looked at how other modes are achieving that behavior and found both `go-mode` and `reason-mode` to use an approach where they produce a diff between the original buffer and a reformatted buffer and then apply that diff back to the original buffer line by line. See:

https://github.com/dominikh/go-mode.el/blob/7eb5b3dd0ac31d176e9d56da4172f66aef8fae47/go-mode.el#L1064

and 

https://github.com/reasonml-editor/reason-mode/blob/a9de59cced37b44db72ee248107021a660561d11/refmt.el#L168

**Comment by xiongtx** [comment]
> I tried wrapping `cider-format-buffer` in `save-excursion`, but that did't fix the issue for me.

`save-excursion` doesn't work b/c it saves a [marker](https://www.gnu.org/software/emacs/manual/html_node/elisp/Overview-of-Markers.html#Overview-of-Markers), which is an object representing position relative to chars immediately before and after it. `erase-buffer` erases all text, causing the marker to lose position.

> Deleting text around a marker's position leaves the marker between the characters immediately before and after the deleted text.

See [this Emacs StackExchange answer](https://emacs.stackexchange.com/a/7577/10269).
