### ISSUE TITLE
"Cask could not be bootstrapped" errors in Travis CI

### ISSUE THREAD

**Issue by gonewest818** [clojure-emacs/cider#2129]
## Expected behavior

Consistent CI test runs every time.

## Actual behavior

CI jobs intermittently failing with the message:

```
Cask could not be bootstrapped. Try again later, or report an issue at https://github.com/cask/cask/issues

The command "curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh" failed and exited with 1 during .
```

## Steps to reproduce the problem

Unfortunately this bug is intermittent. However in my experience it usually occurs at least once in any given matrix of Travis jobs.

Examples: Travis builds [4907.1](https://travis-ci.org/clojure-emacs/cider/jobs/314609496#L5083-L5088), [4907.7](https://travis-ci.org/clojure-emacs/cider/jobs/314609502), [4907.11](https://travis-ci.org/clojure-emacs/cider/jobs/314609506)

## Workaround

This appears to be transient. If you restart the Travis job, sooner or later it will succeed, provided there aren't other unresolved bugs in the source code.

### CIDER version information

Varies.  Does not seem related to the version of emacs/cider being tested in Travis.

### Lein/Boot version

n/a

### Emacs version

n/a

### Operating system

Linux (Travis runs Ubuntu 14.04)

**Comment by bbatsov** [comment]
Cask is abandonware and causes way more problems than it solves so we should drop it and just replace it with some simple script that fetches the cider dependencies. I'm sick from having to deal with it. Not sure if EVM uses Cask in any way as they have the same author. If that's true maybe we'll have to find a different approach to test on multiple Emacs versions as well.

**Comment by xiongtx** [comment]
> Cask is abandonware

Really? The [last commit](https://github.com/cask/cask/commit/eea660b78c05d70159067f5be8cd3bddb55df4c5) is only one month ago.

**Comment by bbatsov** [comment]
Count the numbers of commits since then https://github.com/cask/cask/issues/376 For me Cask is dead at this point.

**Comment by xiongtx** [comment]
> For me Cask is dead at this point.

:ghost: 

> Not sure if EVM uses Cask in any way as they have the same author.

[Doesn't seem like EVM uses Cask](https://github.com/rejeep/evm/search?utf8=%E2%9C%93&q=cask&type=), for what it's worth.

**Comment by bbatsov** [comment]
Thanks for looking into this!

**Comment by gonewest818** [comment]
A proposal: 

Based on what I know from #2120 - I think we can cache the evm and cask bits in the same way as gnutls-cli.  At least then, when we have good, clean versions of those tools installed and bootstrapped they will remain in cache and not cause problems down the road...  opinions?

**Comment by gonewest818** [comment]
ok, I have a possible fix.

https://github.com/gonewest818/cider/tree/2129-bootstrap-evm-and-cask

This does cache evm and cask for responsiveness, but more importantly it has retry logic for the "cask upgrade-cask" call which is what leads to this "cask could not be bootstrapped" error. Naturally, I haven't seen a bootstrapping failure today. I'm going to keep experimenting with this until I see a retry, and then I'll pull request.

**Comment by gonewest818** [comment]
ok to close?

**Comment by bbatsov** [comment]
Indeed.
