### ISSUE TITLE
obsolete if-let and when-let causing test-bytecomp errors on emacs >=26.1

### ISSUE THREAD

**Issue by gonewest818** [clojure-emacs/cider#2130]
## Expected behavior

Clean "make test-bytecomp" on all emacs versions configured in Travis.

## Actual behavior

On emacs >= 26.1 we're getting errors like this. 
```
cider-mode.el: ‘if-let’ is an obsolete macro (as of 26.1); use ‘if-let*’ instead.
cider-mode.el: ‘when-let’ is an obsolete macro (as of 26.1); use ‘when-let*’ instead.
```

This warning is not isolated to cider-mode.el but occurs when compiling many other files. 

## Steps to reproduce the problem

Merge #2128 and wait for the CI jobs to trigger and run.

## Environment & Version information

Happens in Travis right now for emacs-26-pretest-travis and emacs-git-snapshot-travis.

**Comment by bbatsov** [comment]
Hmm, that's interesting. Those were added to Emacs just recently. Progress! 😆 

I guess something was flawed in their design or something. Probably we can just drop the from our codebase completely for now, as they are not important.

**Comment by xiongtx** [comment]
> I guess something was flawed in their design or something.

I'd guess the issue is that `if-let` and `when-let` actually allowed binding multiple vars in sequence, more like `let*` than `let`. But making them obsolete is 🙄 .

**Comment by bbatsov** [comment]
Yeah, I'd just fix them instead and issue some warning if they're not used properly.

**Comment by gonewest818** [comment]
Isn't it a problem that `if-let*` and `when-let*` aren't available in older emacs builds?

**Comment by xiongtx** [comment]
We define them in `cider-compat.el`.

**Comment by Miciah** [comment]
For the record, it is true that at one point, `if-let` was marked obsolete ([commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=4612b2a2b37026bef5a9b8e92878a15dabb9b261)), but the change was reverted ([commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=af4697faa1f5b643f63a9ea61aa205a4c1432e23)).  It looks like the discussion in this issue took place during the time in between these two commits.  These changes both happened prior to the Emacs 26.1 release, and [the Emacs 26.1 NEWS file](http://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS?h=emacs-26.1) does not say that `if-let` is obsolete.  As far as I know, there is no *released* version of Emacs in which `if-let`, `if-let*`, `when-let`, or `when-let*` is obsolete.

**Comment by raxod502** [comment]
@Maciah is correct; tragically, however, EVM's `emacs-git-snapshot-travis` is outdated and still has trouble with the `if-let*` stuff despite this being a non-issue in every released version of Emacs and/or the _actual_ Git snapshot. See also https://github.com/rejeep/evm/issues/32#issuecomment-316422904.
