### ISSUE TITLE
CI errors in "nrepl--bdecode-message" occurring in emacs >= 26

### ISSUE THREAD

**Issue by gonewest818** [clojure-emacs/cider#2135]
## Expected behavior

successful tests

## Actual behavior

tree errored tests:
https://travis-ci.org/clojure-emacs/cider/jobs/314874738#L1760-L1817

## Steps to reproduce the problem

See recent Travis builds using emacs-26-pretest-travis and emacs-git-snapshot-travis

## Environment & Version information

n/a

### CIDER version information

on master branch

### Lein/Boot version

n/a

### Emacs version

26-pretest and git-snapshot (27)

### Operating system

Linux

**Comment by dpsutton** [comment]
yeah these are just changes to representations. the tests just need to be updated:
```

**Comment by gonewest818** [comment]
oops.  This seems to be a duplicate of #2133
