### ISSUE TITLE
need a docker image to mimic the travis environment

### ISSUE THREAD

**Issue by gonewest818** [clojure-emacs/cider#2144]
While resolving other travis-related issues, it became clear the project needs a dev docker environment that can run locally on one's laptop but emulates what is going on in travis. This would be a place to debug not only issues with travis, but also a way to run "make test" and "make test-bytecomp" locally.

**Comment by bbatsov** [comment]
That would be nice indeed.

**Comment by timvisher** [comment]
I think it's possible to use TravisCI's images? https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e

**Comment by gonewest818** [comment]
Interesting. I hadn't seen that one before. But for sake of simplicity, all I'm doing is building a Dockerfile and a few convenience scripts such that you can build a docker container that runs and drops you into a bash shell.

So it's an emulation of the build environment that Travis uses, but it doesn't at all try to emulate the way the jobs are launched in Travis.

https://github.com/gonewest818/cider/blob/2144-docker-image/Dockerfile

You can run that container *with your source tree mounted* such that you can edit as you like from your host computer but then switch to the docker shell and `make clean test` to confirm tests. I'm preinstalling `emacs-{25.3,26-pretest,git-snapshot}-travis` so you can toggle emacs versions and retest `evm use emacs-26-pretest-travis; make elpaclean test`.

Still a work in progress.
