### ISSUE TITLE
Unclear what is coloring clojure.core fns

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#2147]
CIDER adds extra a font-lock setup to clojure-mode, which doesn't seem documented prominently enough.

My specific problem is that I don't want clojure.core/* fns to be colored differently:

![image](https://user-images.githubusercontent.com/1162994/34465786-1aa69a30-eebf-11e7-9872-9995aa5b803d.png)

In the screenshot, CIDER detects that `filter` belongs to clojure.core and colors it differently.

I'd like to either turn that off or customize what font-face is dispatched to those.

Thanks - Victor

**Comment by vemv** [comment]
Solved with:

```
(custom-set-variables
 '(cider-font-lock-dynamically '(macro deprecated)))
```

i.e., remove the `core` symbol

I'll close for not keeping the issue count high, but IMO font-lock documentation could be more prominent

**Comment by bbatsov** [comment]
See  http://cider.readthedocs.io/en/latest/configuration/

That's actually documented, but I guess it's not very prominent.
