### ISSUE TITLE
cider-repl-clear-buffer returns:  Wrong type argument: integer-or-marker-p, nil

### ISSUE THREAD

**Issue by eranb** [clojure-emacs/cider#2153]
When running the `cider-repl-clear-buffer` command I get this error: `Wrong type argument: integer-or-marker-p, nil` and the repl buffer stays the same (e.g not cleaned).

And when I run the `cider-repl-clear-buffer` function from the repl buffer it gets cleaned as expected without showing the error above. 

### Trace
```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  overlays-in(1 nil)
  cider-repl--clear-region(1 nil)
  cider-repl-clear-buffer()
  funcall-interactively(cider-repl-clear-buffer)
  #<subr call-interactively>(cider-repl-clear-buffer nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> cider-repl-clear-buffer nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (cider-repl-clear-buffer nil nil))
  call-interactively(cider-repl-clear-buffer nil nil)
  command-execute(cider-repl-clear-buffer)
```

### Mode
```-UU-:----F1  engine.clj     Top L16   Git:master  [(Clojure cider[XXX@:63439] , Paredit Projectile[XXX] ElDoc)]```

### CIDER version information
```
;; CIDER 0.17.0snapshot (package: 20180101.958), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_71
;; cider-nrepl 0.16.0
```

### Lein
`Leiningen 2.7.1 on Java 1.8.0_71 Java HotSpot(TM) 64-Bit Server VM`

### Emacs

`GNU Emacs 25.3.1 (x86_64-apple-darwin17.0.0, NS appkit-1561.00 Version 10.13 (Build 17A405)) of 2017-10-24`

### OS
`MacOS High Sierra 10.13.2 (17C88)`

**Comment by bbatsov** [comment]
@eranb Does this happen all the time? I can't reproduce it myself.

**Comment by xiongtx** [comment]
Can reproduce. I guess `cider-repl-clear-buffer` is not meant to be called from a non-REPL buffer.

**Comment by bbatsov** [comment]
Seems for you this function:

```
(defun cider-repl--clear-region (start end)
  "Delete the output and its overlays between START and END."
  (mapc #'delete-overlay (overlays-in start end))
  (delete-region start end))
```

Somehow got `nil` for the `end`, but without some repro steps I can't figure out what went wrong for you.

**Comment by xiongtx** [comment]
@bbatsov Are you calling from a non-REPL buffer?

**Comment by bbatsov** [comment]
Ah, thanks @xiongtx. I didn't pay enough attention to the report - yeah, that's true. There's a different command for when you're outside the repl. It's `cider-find-and-clear-repl-output` (with a prefix argument it clears the entire repl).

**Comment by xiongtx** [comment]
And it's conveniently bound to `C-c C-o`, the same binding as `cider-repl-clear-output` in the REPL buffer :grin:.

**Comment by eranb** [comment]
Hi @bbatsov, @xiongtx 
when I call the `cider-find-and-clear-repl-output` function (from any buffer - repl & clj file) nothing happens :(

Do you have any idea how I can debug it ?

**Comment by xiongtx** [comment]
You can use the [Emacs debugger](https://www.gnu.org/software/emacs/manual/html_node/eintr/Debugging.html).

What do you mean by "nothing happens"? By default, `cider-find-and-clear-repl-output` clears _output_, not the whole REPL buffer. To clear the whole buffer, use a prefix arg (`C-u`).

**Comment by eranb** [comment]
@xiongtx by nothing I mean that I still see the previous REPL output on the buffer.
When I run the command inside the REPL window/buffer it clears the output as expected.
I'll try the debbuger

**Comment by xiongtx** [comment]
Are you sure the buffer is associated w/ the REPL? Try `cider-jack-in` again.

**Comment by eranb** [comment]
`cider-jack-in` produce `REPL buffer already exists (*cider-repl XXX*).  Do you really want to create a new one? (y or n) `

**Comment by xiongtx** [comment]
Cannot reproduce. You're doing `C-u C-c C-o` from the non-REPL buffer and the REPL buffer is _not_ being cleared?

**Comment by eranb** [comment]
Thanks a lot, this combo works `C-u C-c C-o` 👍 
before I tired to use `C-x C-o`
