### ISSUE TITLE
travis-ci/install-gnutls.sh should exit early if libnettle can't be installed

### ISSUE THREAD

**Issue by gonewest818** [clojure-emacs/cider#2155]
I noticed an error in [a recent Travis CI log](https://travis-ci.org/clojure-emacs/cider/jobs/324610574)

```
configure: error: 
  ***
  *** Libnettle 3.1 was not found.
```

## Expected behavior

`install-gnutls.sh` should download and compile (1) libnettle, and (2) gnutls.

## Actual behavior

When libnettle isn't found (in the example job linked above, it looks like this particular Travis CI worker got borked somehow) this install script carries on and attempts to compile gnutls anyway, but it obviously can't succeed without the necessary dependency.

## Steps to reproduce the problem

This is frustrating, but the error is transient and seems to be relatively rare. The faulty behavior is clear from the logs, however. Simple fix.

## Environment & Version information

n/a

### Lein/Boot version

n/a

### Emacs version

n/a

### Operating system

n/a

**Comment by xiongtx** [comment]
If @travis-ci is such a problem, maybe we should try @circleci?

**Comment by gonewest818** [comment]
Just note that the CircleCI free plan is limited to one build at a time (one container) and 1500 build minutes per month.

Currently a single commit to this project seems to be incurring 20-45 minutes of build time on Travis CI. Furthermore, you've got concurrency so that everything completes somewhat faster than the sum of the individual job times.

However on CircleCI it would be 1x concurrency unless you are willing to pay. The immediate workflow impact would be serialized builds and managing to the monthly time limit. Granted, this project's build matrix could easily be pruned, but one wonders if managing to this cap will end up being a burden nobody wants.

* 30 minutes per commit = 1500/30 = 50 builds per month
* 20 minutes per commit = 1500/20 = 75 builds per month
* 10 minutes per commit = 1500/30 = 150 builds per month

Finally, the pricing ramp is steep.... capacity at $50/container/month.

**Comment by xiongtx** [comment]
That's some pretty thorough analysis! Guess we'll be sticking w/ @travis-ci for now...

**Comment by gonewest818** [comment]
:) Having run a few startups, it has become sort of a habit double-checking the numbers on services like these.

However, I don't want to suggest I *prefer* Travis CI over the alternatives, because clearly they are suffering consistency problems in their operations, and that's really not ok.

**Comment by xiongtx** [comment]
Have you reported these problems to them? Perhaps they're not aware.

**Comment by gonewest818** [comment]
I will, but the last time I reported an error they got back to me ~10 days later.

**Comment by bbatsov** [comment]
Travis seem to be having a lot of issues, lately. For a week or some builds have been failing randomly for one of my Ruby projects as well https://github.com/bbatsov/rubocop/pulls

But they also don't have a lot of alternatives in the OSS space...

> Currently a single commit to this project seems to be incurring 20-45 minutes of build time on Travis CI. Furthermore, you've got concurrency so that everything completes somewhat faster than the sum of the individual job times.

That's really odd, but I assume all of this is build setup. The tests themselves should be a few seconds.

**Comment by gonewest818** [comment]
Exactly. Those rubocop jobs are failing to update from Ubuntu package repositories &/or failing to install gems, etc.  That happens far too often in my opinion.  

I sent email to Travis CI help desk but they’re still on vacation.

**Comment by gonewest818** [comment]
@traviscistatus: "We are investigating increased networking errors on container-based Linux jobs."
https://www.traviscistatus.com/incidents/lrc4yp46t8wb

**Comment by bbatsov** [comment]
Thanks for the update!

Btw, would be willing to check the problems with the stability of the `cider-nrepl` build and the mysteriously missing test coverage report there?

**Comment by gonewest818** [comment]
Yes, I’ll take a look.
