### ISSUE TITLE
passing regex directly to cider-browse-spec-all

### ISSUE THREAD

**Issue by qq00** [clojure-emacs/cider#2163]
## problem

we should have something like cider-browse-spec-all which takes a regex as an argument (instead of querying the user for it)

this is so it is easy for users to say "show me all specs in src/" instead of showing all specs in clojure.core + included libraries

## discussion

me:: the problem I was running into with spec ... was that it was showing me all types of specs from clojure core + external libraries

@bbatsov: Yeah, that totally makes sense. We should add some filtering for the specs that come outside the project. Please, file a ticket for this. Should be easy to do IMO.

## current solution

(assuming that all src/ namespaces start with "aa.")

```
("j" (my-cider-browse-spec-all "aa\."))
(defun my-cider-browse-spec-all (filter-regex)
  (interactive "P")
  (cider-ensure-connected)
  (cider-ensure-op-supported "spec-list")
  (with-current-buffer (cider-popup-buffer cider-browse-spec-buffer t)
    (let ((specs (cider-sync-request:spec-list filter-regex)))
      (cider-browse-spec--draw-list-buffer (current-buffer)
					   (if (string-empty-p filter-regex)
					       "All specs in registry"
					     (format "All specs matching regex `%s' in registry" filter-regex))
					   specs))))

```

**Comment by bbatsov** [comment]
@jpmonettas Can you take a look at this? I think we should definitely add some way to filter out non-project specs. Potentially we can have an inverse filter as well.

**Comment by jpmonettas** [comment]
@bbatsov the problem with specs is aren't attached to any project, namespace or file so you can't tell where does it come from.

I can't figure out any hack for this either given that keywords ns are not clojure namespaces.

For @qq00 use case I'll send a pull request.

**Comment by bbatsov** [comment]
Thanks for the fast response here!

> @bbatsov the problem with specs is aren't attached to any project, namespace or file so you can't tell where does it come from.

I don't quite get this - aren't specs usually attached to namespaced keywords? Can't we used this?

**Comment by jpmonettas** [comment]
> Thanks for the fast response here!
You are welcome

> I don't quite get this - aren't specs usually attached to namespaced keywords? Can't we used this?
@bbatsov We can but I will not be very accurate, for example:

```clojure
  (ns geometry-project.core
    (:require [clojure.spec.alpha :as s]))

  (s/def :shapes/triangle (s/cat :base int? :height int?))
```
now if we are looking at the registry we will see a :shapes/triangle spec 

```clojure
(meta (s/get-spec :shapes/triangle)) ;; => nil
```

but what project it belongs to?

**Comment by bbatsov** [comment]
I see your point. I was under the impression people often did it like this:

```clj
(ns geometry-project.core
    (:require [clojure.spec.alpha :as s]))

  (s/def ::triangle (s/cat :base int? :height int?))
```

**Comment by jpmonettas** [comment]
Yeah I think most people does like that, but have also done the other way so don't know if that feature is a good idea.
