### ISSUE TITLE
`cider-test-run-project-tests` and `cider-load-all-project-ns` do not behave as expected

### ISSUE THREAD

**Issue by cwhitey** [clojure-emacs/cider#2166]
## Expected behavior
`cider-test-run-project-tests` should run all tests in project, and `cider-load-all-project-ns` should list all of my namespaces

## Actual behavior
`cider-test-run-project-tests` yields the message:
> No assertions (or no tests) were run.Did you forget to use ‘is’ in your tests?

`cider-load-all-project-ns` yields the message:
> Loaded 0 namespaces

`cider-classpath` gives an empty buffer

## Steps to reproduce the problem
- Create a new default project with `lein new app my-app` 
- `cider-jack-in`
- Open `core_test.clj
- Confirm `cider-test-run-ns-tests` runs the test in `core_test.clj`
- Run `cider-test-run-project-tests` and `cider-load-all-project-ns` and observe results

### CIDER version information

```
;; CIDER 0.16.0 (Riga), nREPL 0.2.13
;; Clojure 1.8.0, Java 9.0.1
```

### Lein/Boot version

Leiningen 2.8.1 on Java 9.0.1 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-13

### Operating system

OS X 10.12.6 "Sierra"

**Comment by bbatsov** [comment]
Hmm, likely this is related to some refactoring work done recently by @SevereOverfl0w in `cider-nrepl`. I thought I updated the related client code, though. I'll look into this when I have some time, but if someone wants to beat me to it - I'd appreciate it.

**Comment by cwhitey** [comment]
It works for me with the following version from MELPA:
```
;; CIDER 0.17.0snapshot (package: 20180115.1350), nREPL 0.2.13
;; Clojure 1.9.0, Java 9.0.1
```
I was pulling from MELPA-stable earlier because of an issue with refactor-nrepl which has since been fixed, so this is no longer an issue for me. Feel free to close, but I suppose this is still an issue for those running Cider 0.16.0.

**Comment by bbatsov** [comment]
That's interesting. I don't recall anything that changed related to running tests since 0.16.
