### ISSUE TITLE
clojure.math.numeric-tower won't load

### ISSUE THREAD

**Issue by unhandyandy** [clojure-emacs/cider#2169]
## Expected behavior

(:require  [clojure.math.numeric-tower :as math])

is successfully executed.

## Actual behavior

Error:
2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling src/collatz/core.clj at (1:1)

1. Caused by java.io.FileNotFoundException
   Could not locate clojure/math/numeric_tower__init.class or
   clojure/math/numeric_tower.clj on classpath. Please check that
   namespaces with dashes use underscores in the Clojure file name.

## Steps to reproduce the problem

project:.clj:
```
(defproject foobar "0.1.0-SNAPSHOT"
  :description "foobar explorer"
  :url ""
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/math.numeric-tower "0.0.4"]
                 ]
  :main ^:skip-aot foobar.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}}
  :bin {:name "foobar"
        :bin-path "~/bin"
        :bootclasspath false}
  )
```
src.clj:

```
(ns foobar.core
  (:gen-class)
   (:require  [clojure.math.numeric-tower :as math]
  ) )

```

C-c C-k in src.clj

## Environment & Version information
clojure 1.9.0

$ ls ~/.m2/repository/org/clojure/math.numeric-tower/0.0.4/
math.numeric-tower-0.0.4.jar       math.numeric-tower-0.0.4.pom.sha1
math.numeric-tower-0.0.4.jar.sha1  _remote.repositories
math.numeric-tower-0.0.4.pom

64bit, 4-core

### CIDER version information

```
;; CIDER 0.17.0snapshot (package: 20180111.1400), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_151
```

### Emacs version

24.5.1

### Operating system

Linux Ubuntu 16.04 LTS

**Comment by bbatsov** [comment]
Just of out curiosity - do you have the same problem with Clojure 1.8? I noticed a similar report on the Clojure mailing list today and I wonder if it has something to do with `numeric-tower` itself.

**Comment by unhandyandy** [comment]
Was that my thread?   In that case numeric-tower seems too have been
excluded since it ran fine in the lein repl.

I have used clojure 1.8, cider, and numeric-tower together successfully in
the past,  but I'll try it again tomorrow.

**Comment by bbatsov** [comment]
See https://groups.google.com/forum/?hl=en#!topic/clojure/lB9710NH8Ck

**Comment by unhandyandy** [comment]
That's mine.  It seems to be a problem with cider because the code works in the lein repl.

**Comment by bbatsov** [comment]
Is it a problem if you remove:

```:main ^:skip-aot foobar.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}}
  :bin {:name "foobar"
        :bin-path "~/bin"
        :bootclasspath false}```

**Comment by unhandyandy** [comment]
Yes, I get the same error if without those lines in project.clj.

**Comment by bbatsov** [comment]
From the continuation of the discussion in the mailing list it seems this is not a CIDER issue after all, right?

**Comment by unhandyandy** [comment]
OK, it seems to have been an emacs issue rather than a cider one, at least after tweaking a few emacs configs related to help-mode I'm no longer having the problem.  Thanks for your patience.
