### ISSUE TITLE
cider-browse-ns

### ISSUE THREAD

**Issue by qq00** [clojure-emacs/cider#2170]
1. cider-browse-ns is amazing

2. cider-browse-ns can be even better

3. Would it be possible, in the pop up mini widow that cider-browse-ns creates, set it up so that

"clicking on a line -> causes emacs to jump where the function / var is defined?"

**Comment by expez** [comment]
That key is already used to expand the documentation for that var.

You can hit <kbd>s</kbd> to see the **s**ource of the function.
