### ISSUE TITLE
exception during cider-jack-in (0.17.0snapshot) 

### ISSUE THREAD

**Issue by skat-kurt** [clojure-emacs/cider#2176]
## Expected behavior
cider-jack-in starts a repl process and connects to it without error output.

## Actual behavior
A long stacktrace is displayed. I have removed quite some lines, trying to keep the potentially relevant stuff.

```
;; ======================================================================
ERROR: Unhandled REPL handler exception processing message {:op init-debugger, :print-level 10, :print-length 10, :session ca886d01-393b-4dac-b878-81c744e0352d, :id 8}
java.io.FileNotFoundException: Could not locate clojure/java/classpath__init.class or clojure/java/classpath.clj on classpath., compiling:(cider/inlined_deps/toolsnamespace/v0v3v0_alpha4/clojure/tools/namespace/find.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)

	.............

	at cider.inlined_deps.orchard.v0v1v0_20180123v122522_8.orchard.namespace$eval2226$loading__5569__auto____2227.invoke(namespace.clj:1)
	at cider.inlined_deps.orchard.v0v1v0_20180123v122522_8.orchard.namespace$eval2226.invokeStatic(namespace.clj:1)
	at cider.inlined_deps.orchard.v0v1v0_20180123v122522_8.orchard.namespace$eval2226.invoke(namespace.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	
        .............

	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at cider.inlined_deps.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.find$eval3365$loading__5569__auto____3366.invoke(find.clj:9)
	at cider.inlined_deps.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.find$eval3365.invokeStatic(find.clj:9)
	at cider.inlined_deps.toolsnamespace.v0v3v0_alpha4.clojure.tools.namespace.find$eval3365.invoke(find.clj:9)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 158 more
```
Then a repl promt appears, but evaluating expressions gives about the same error.

## Steps to reproduce the problem
I experience this also in a newly generated blank leiningen lib project. Happens on C-c M-j (cider-jack-in). Uninstalling cider and installing the latest from melpa-stable (0.16.0 Riga) resolves the problem. Upgrading again to latest in melpa (not stable) recreates the problem.

### CIDER version information
```
;; CIDER 0.17.0snapshot (package: 20180122.2345), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_144
```
### Emacs version
25.3.1

### Operating system
Arch (Antergos)

**Comment by doubleagent** [comment]
I'm getting this too.  Started when I upgraded `cider-nrepl` to `0.17.0-snapshot` in `profiles.clj`.  If I drop back to v16 I get a warning message for version mismatch, but it does not immediately crash.

Same versions as you, except on Windows.

**Comment by cactuar** [comment]
Thank you, at least I am not crazy :-)

**Comment by cactuar** [comment]
Same here. Cider jack in started to act strange (two hours ago the error was #2175 ) and right now, after reinstalling lein, I am getting this exception.

**Comment by bbatsov** [comment]
I'm puzzled by this. Seems you're using the latest snapshots, but the dependency resolution is broken for some non-obvious reason. Might be some problem with the deps shadowing, as the failure indicates something is trying to load the non-shadowed version of `clojure.java.classpath`. @benedekfazekas any ideas?

**Comment by bbatsov** [comment]
Btw, do any of you use `clojure.tools.namespace` in your projects?

**Comment by benedekfazekas** [comment]
just discussing this with @xiongtx on clojure slack atm

**Comment by lvh** [comment]
I'm having the same issue.  The project in question doesn't papear to have clojure.java.classpath, or at least I couldn't find it via `lein deps :tree`. It does have tools.reader.

**Comment by cactuar** [comment]
My only dependency is 
:dependencies [[org.clojure/clojure "1.8.0"]]

**Comment by lvh** [comment]
@benedekfazekas Here's a thought: do the people in question have `[venantius/ultra "0.5.2"]` around? Perhaps in profiles.clj?

**Comment by lvh** [comment]
Never mind: I just removed ultra and that didn't cause it.

**Comment by cactuar** [comment]
>  Here's a thought: do the people in question have [venantius/ultra "0.5.2"] around? Perhaps in profiles.clj?

I've just deleted my .lein and .m2 directory. Do I need to look somewhere else?

**Comment by lvh** [comment]
@cactuar No, it'd be either in project.clj or in `~/.lein`.

**Comment by bbatsov** [comment]
So, to be clear this is 100% caused by recent split of `cider-nrepl` into two libraries, but it's really not obvious to my how the split can result in something like this. That's the new library https://github.com/clojure-emacs/orchard where we've started to move the non-middleware code, so we can reuse it later with without nREPL (something like this is needed to be able to support eventually the socket repl server in CIDER). 

Seems to me something got messed with the deps obfuscation with MrAnderson, but I'm puzzled as to two exactly.

**Comment by benedekfazekas** [comment]
I think this is caused by benedekfazekas/mranderson#7 I workaround could be to add `org.clojure/java.classpath` as a *not* mrandersoned dependency. The down side of this workaround would be that `cider-nrepl` unusable for project depending also on `org.clojure/java.classpath` but a different version

**Comment by benedekfazekas** [comment]
to be more precise this is not exactly as benedekfazekas/mranderson#7 but the cause is that mranderson works on "resovled" dependency tree

**Comment by benedekfazekas** [comment]
actually after playing with it a bit adding back `^:source-dep [org.clojure/java.classpath "0.2.3"]` should fix it.

**Comment by cactuar** [comment]
@benedekfazekas Adding `^:source-dep [org.clojure/java.classpath "0.2.3"]` fixes the problem

**Comment by bbatsov** [comment]
Just before I go to bed I released a new snapshot.

**Comment by bbatsov** [comment]
> to be more precise this is not exactly as benedekfazekas/mranderson#7 but the cause is that mranderson works on "resovled" dependency tree

I also thought it analyzed the deps of each package individually - won't this be more robust?

**Comment by benedekfazekas** [comment]
yeah with some drawbacks like even bigger jars for example

**Comment by xiongtx** [comment]
>  analyzed the deps of each package individually

So it _doesn't_ do this, correct?

**Comment by bbatsov** [comment]
Maybe this can be a configurable option.

**Comment by benedekfazekas** [comment]
no, it does not atm. yup could be configurable. it deffo seems I need to solve #7 at last

**Comment by bbatsov** [comment]
It seems so. ;-)

**Comment by skat-kurt** [comment]
Thanks for fixing this so quickly. I wanted to try this bug on another machine with different configuration but couldn't reproduce. Should have checked the status of this issue first ;)

**Comment by dpsutton** [comment]
Just had a bug pop up on slack. Reproduced as follows:

```clj
(defproject oztest "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.9.0"]
                 #_[org.clojure/tools.reader "1.3.2"]
                 [metasoarous/oz "1.5.2"]])
```

CIDER jack in and then `(require '[oz.core :as oz])` yields the following:

```clj
CompilerException java.lang.IllegalAccessError: reader-error does not exist, compiling:(taoensso/encore.clj:1:1) 
ERROR: Unhandled REPL handler exception processing message {:op stacktrace, :pprint-fn cider.nrepl.pprint/pprint, :print-options {:length 50, :level 50}, :session 737c8fca-853c-4537-8e09-bfe15cc71069, :id 14}
java.lang.NoClassDefFoundError: Could not initialize class clojure.tools.reader.edn__init
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.Compiler.maybeResolveIn(Compiler.java:7322)
	at clojure.core$ns_resolve.invokeStatic(core.clj:4336)
	at clojure.core$ns_resolve.invokeStatic(core.clj:4325)
	at clojure.core$ns_resolve.invoke(core.clj:4325)
	at cider.inlined_deps.orchard.v0v4v0.orchard.java$resolve_class$fn__2607.invoke(java.clj:271)
	at cider.inlined_deps.orchard.v0v4v0.orchard.java$resolve_class.invokeStatic(java.clj:271)
	at cider.inlined_deps.orchard.v0v4v0.orchard.java$resolve_class.invoke(java.clj:265)
	at cider.inlined_deps.orchard.v0v4v0.orchard.java$resolve_symbol.invokeStatic(java.clj:300)
	at cider.inlined_deps.orchard.v0v4v0.orchard.java$resolve_symbol.invoke(java.clj:287)
	at cider.nrepl.middleware.stacktrace$analyze_fn.invokeStatic(stacktrace.clj:81)

	at cider.nrepl.middleware.stacktrace$analyze_fn.invoke(stacktrace.clj:60)
```

If the tools reader is set to 1.3.2 it is fine. You can verify the versions brought in with `lein deps :tree` and `/home/dan/bin/lein update-in :dependencies conj \[nrepl\ \"0.5.3\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.20.0\"\] -- deps :tree | less`.

This is strange since i'm seeing the namespace is `cider.inlined-deps.toolsreader.v1v2v2.clojure.tools.reader` in `cider-nrepl-0.20.0-20190102.114058-1.jar`.

It seems to be the same issue here.

**Comment by benedekfazekas** [comment]
as a said on slack nrepl is not shadowed and inlined by mranderson. if you check out `cider-nrepl`s project file you can see it is not marked with `source-deps` meta

**Comment by dpsutton** [comment]
yes i agree with that. However, `^:source-dep [org.clojure/tools.reader "1.2.2"]` is marked as a source-dep. And When using cider-nrepl, the project relies on this version rather than the tools.reader `[org.clojure/tools.reader "1.3.2"]` from `com.taoensso/encore`.

My understanding is that the inlining should not affect dependency resolution. The 1.2.2 should not show up but it does.

But running `lein deps :tree` with cider-nrepl reveals that all of these inlined deps are included in the dep resolution step.
```

 [cider/cider-nrepl "0.20.0"]
   [cider/orchard "0.4.0" :exclusions [[org.clojure/clojure]]]
     [org.tcrawley/dynapath "0.2.5" :exclusions [[org.clojure/clojure]]]
   [cljfmt "0.6.1" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
     [com.googlecode.java-diff-utils/diffutils "1.3.0"]
     [org.clojure/tools.cli "0.3.7"]
     [rewrite-clj "0.6.0"]
     [rewrite-cljs "0.4.4"]
   [cljs-tooling "0.3.1" :exclusions [[org.clojure/clojure]]]
   [compliment "0.3.8" :exclusions [[org.clojure/clojure]]]
   [fipp "0.6.14" :exclusions [[org.clojure/clojure]]]
     [org.clojure/core.rrb-vector "0.0.13"]
   [mvxcvi/puget "1.0.2" :exclusions [[org.clojure/clojure]]]
     [mvxcvi/arrangement "1.1.1"]
   [org.clojure/java.classpath "0.3.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.namespace "0.3.0-alpha4" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.reader "1.2.2" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.trace "0.7.10" :exclusions [[org.clojure/clojure]]]
   [thunknyc/profile "0.5.2" :exclusions [[org.clojure/clojure]]]
```

**Comment by dpsutton** [comment]
Contrast that when running `lein deps :tree` with cider-nrepl 0.18:

```
[cider/cider-nrepl "0.18.0"]
```
