### ISSUE TITLE
cider-jack-in outside a Clojure project results in 100% processor usage

### ISSUE THREAD

**Issue by abo-abo** [clojure-emacs/cider#2177]
Using the latest CIDER with 0.16.0 middleware (0.17.0snapshot is broken right now).  Also reproducible with the 0.16.0 release of CIDER.

Like the title says, 100% processor usage as long as CIDER REPL is open. The REPL is responsive and appears to work as usual.  The issue does not happen if `project.clj` is present.

**Comment by bbatsov** [comment]
It'd be nice if you did a bit of profiling (e.g. with the Visual VM) to see what exactly is causing this spike. I assume this 100% is coming from Lein, right?

**Comment by xiongtx** [comment]
Cannot reproduce.

1. `mkdir test`
2. `cd test`
3. `touch foo.clj`
4.  `emacs --file foo.clj`
5. `htop` in terminal
6. `cider-jack-in`

![image](https://user-images.githubusercontent.com/1624090/35832719-2a79832a-0a83-11e8-909c-400223a31618.png)

On a 13-inch MacBook Pro, Early 2015.

**Comment by gonewest818** [comment]
Is this the same case as `cider-jack-in` from a `*cider-scratch*` buffer?  Because that also works, for me at least.

**Comment by abo-abo** [comment]
@xiongtx Indeed, I can't reproduce your recipe on one of my machines.

**Comment by xiongtx** [comment]
"Can't reproduce [my] recipe" meaning you get the same result I do, or still 100% CPU usage?

**Comment by abo-abo** [comment]
@xiongtx I meant that I get the same result as you. Thanks for checking.
