### ISSUE TITLE
cider-test-run-test highlighting incorrect test?

### ISSUE THREAD

**Issue by qq00** [clojure-emacs/cider#2180]
![error](https://user-images.githubusercontent.com/32815631/35389535-49583242-0195-11e8-8256-7e04d8fac977.png)

## problem

see above: the second test fails. the first test is highlighted

## replication

put cursor on the first "(", executed cider-test-run-test

**Comment by xiongtx** [comment]
Cannot reproduce.

`(is (= [1 2]))` does not fail. `(= foo)` always evaluated to true.

The second test here fails, but the correct test clause is highlighted:

![image](https://user-images.githubusercontent.com/1624090/35832558-92271916-0a82-11e8-8835-2d7cba00c8ea.png)

**Comment by gonewest818** [comment]
(sorry to hijack this but...) @xiongtx, what do you think a "can't reproduce" label for issues?

**Comment by xiongtx** [comment]
Don't we already have one? If not, would be a good idea.
