### ISSUE TITLE
[feature request] Injecting values into code with the #dbg reader macro

### ISSUE THREAD

**Issue by IGJoshua** [clojure-emacs/cider#2181]
Currently when using the debugger you can inject a value as a replacement for any given value that you have a breakpoint on. I'd like to request that we add an additional meta tag that the `#dbg` reader macro will pay attention to.
```clojure
#dbg ^{:inject nil} (slurp filename)
```
So this allows us to not change the original code, but still allow a different value to be injected while debugging, so we can test what happens when certain values are substituted at various points.
Additionally we could also make it conditional:
```clojure
#dbg ^{:inject/when {:val nil :cond true}} (slurp filename)
```

**Comment by bbatsov** [comment]
@Malabarba Any chance you can look into this or provide some guidance what needs to be done?

**Comment by Malabarba** [comment]
Hey there
I'm not sure I understand the value of this feature, but maybe I just misunderstood. Is the suggetion something equivalent to wraping the code in an `if`?
Something like `(if cond val (slurp filename))`

**Comment by IGJoshua** [comment]
@Malabarba no, it is not equivalent. The original feature request is to allow breaking on some code. That code is executed unconditionally, but the breakpoint itself pauses execution only when a particular expression returns true.
