### ISSUE TITLE
Evaluation errors result in the cursor's position being changed

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2192]
When you evaluate a form resulting in an error, the cursor gets moved to the beginning of the form in question. Likely a missing `save-excursion` somewhere. 

## Expected behavior

The cursor stays where it was.

## Actual behavior

It moves to the beginning of the form producing the error.

## Steps to reproduce the problem

Just evaluate:

```
 (let [a nil
  (filter identity [])])
```

with `C-c C-e`. 

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:56719
;; CIDER 0.17.0snapshot (package: 20180115.1350), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_131

```

### Emacs version

25.2

**Comment by DarMontou** [comment]
I'm unable to reproduce.

[nREPL] Direct connection to localhost:49619 established
GNU Emacs 25.3.1
CIDER 0.17.0snapshot (package: 20180203.535)

**Comment by xiongtx** [comment]
I can reproduce. Interesting, this doesn't happen with _all_ errors: `(/ 1 0)` does not exhibit this behavior, for example.
