### ISSUE TITLE
Usage ― how to enter cider mode automatically

### ISSUE THREAD

**Issue by matanster** [clojure-emacs/cider#2196]
Currently I only get the "Clojure" menu, but not the cider menu, from where I would start a repl session or run tests. Is this only my setup? I need to explicitly enter `cider-mode` to get it. Is this by design? can I have cider-mode automatically applied whenever working within a clojure project? I mean, that would just make sense or wouldn't it?

Should I try re-installing?

Thanks for your comments

My `.emacs` file:

> (require 'package)
> (let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
>                     (not (gnutls-available-p))))
>        (proto (if no-ssl "http" "https")))
>   ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
>   ;;(add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
>   (add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
>   (when (< emacs-major-version 24)
>     ;; For important compatibility libraries like cl-lib
>     (add-to-list 'package-archives '("gnu" . (concat proto "://elpa.gnu.org/packages/")))))
> (package-initialize)
> (custom-set-variables
>  ;; custom-set-variables was added by Custom.
>  ;; If you edit it by hand, you could mess it up, so be careful.
>  ;; Your init file should contain only one such instance.
>  ;; If there is more than one, they won't work right.
>  '(ansi-color-names-vector
>    ["#212526" "#ff4b4b" "#b4fa70" "#fce94f" "#729fcf" "#e090d7" "#8cc4ff" "#eeeeec"])
>  '(blink-cursor-mode nil)
>  '(column-number-mode t)
>  '(compilation-message-face (quote default))
>  '(cua-mode t nil (cua-base))
>  '(custom-enabled-themes (quote (sanityinc-tomorrow-night)))
>  '(custom-safe-themes
>    (quote
>     ("06f0b439b62164c6f8f84fdda32b62fb50b6d00e8b01c2208e55543a6337433a" "61003d455ba1bad9a3bf8be7342e848ca3febe899319e95a9dc3d804d9697608" "b97a01622103266c1a26a032567e02d920b2c697ff69d40b7d9956821ab666cc" default)))
>  '(font-use-system-font t)
>  '(highlight-changes-colors (quote ("#FD5FF0" "#AE81FF")))
>  '(highlight-tail-colors
>    (quote
>     (("#3C3D37" . 0)
>      ("#679A01" . 20)
>      ("#4BBEAE" . 30)
>      ("#1DB4D0" . 50)
>      ("#9A8F21" . 60)
>      ("#A75B00" . 70)
>      ("#F309DF" . 85)
>      ("#3C3D37" . 100))))
>  '(magit-diff-use-overlays nil)
>  '(pos-tip-background-color "#FFFACE")
>  '(pos-tip-foreground-color "#272822")
>  '(save-place t nil (saveplace))
>  '(show-paren-mode t)
>  '(tool-bar-position (quote bottom))
>  '(weechat-color-list
>    (unspecified "#272822" "#3C3D37" "#F70057" "#F92672" "#86C30D" "#A6E22E" "#BEB244" "#E6DB74" "#40CAE4" "#66D9EF" "#FB35EA" "#FD5FF0" "#74DBCD" "#A1EFE4" "#F8F8F2" "#F8F8F0")))
> (custom-set-faces
>  ;; custom-set-faces was added by Custom.
>  ;; If you edit it by hand, you could mess it up, so be careful.
>  ;; Your init file should contain only one such instance.
>  ;; If there is more than one, they won't work right.
>  '(default ((t (:family "Ubuntu Mono" :foundry "DAMA" :slant normal :weight normal :height 181 :width normal)))))

**Comment by bbatsov** [comment]
Yeah, that's by design. You can enable `cider-mode` automatically using `(add-hook 'clojure-mode-hook #'cider-mode)`.

**Comment by matanster** [comment]
Would there be any issue if I did that? would I not want it automatically enabled?
