### ISSUE TITLE
add elisp formatting checks in CI

### ISSUE THREAD

**Issue by gonewest818** [clojure-emacs/cider#2199]
As mentioned in #2197 it would be useful to have a basic formatting check running in CI to catch indentation issues, trailing whitespace, etc.

**Comment by gonewest818** [comment]
I'm looking at https://github.com/nschum/elisp-lint as a possible starting point, but it needs some updating.

**Comment by xiongtx** [comment]
We already run `checkdoc` and bytecompile tests. What more do we need? There isn't a standard style for Elisp the way there is for e.g. Go. And I wouldn't want these checks to frustrate new contributors.

**Comment by gonewest818** [comment]
Well, elisp-lint can confirm `indent-region`, verify indents are following `indent-tabs-mode`, no line lengths exceeding `fill-column`, no trailing whitespace, and so on.  Individual checks can be disabled.

Like I said, I'm having to adjust some things in that codebase but what's left to do is the `indent-region` check.  Right now it's flagging compat macros like `if-let*` and `when-let*` because it wants to indent them like regular functions.

**Comment by gonewest818** [comment]
Well, anyway, there are [4 pull requests pending in the elisp-lint project](https://github.com/nschum/elisp-lint/pulls) that boost the functionality enough to be configured and tested.

I ended up taking the `cljfmt` approach to indent rules, meaning I'm not trying to locate and evaluate all the macros (to get the `(declare (indent __))` forms automagically. Instead you need to configure an alist in `.dir.locals.el` with the indent rules you need.

It's fine with me if you collectively decide not to use that linter on `cider`. I'll probably adopt it for personal projects like `dimmer.el` though.

**Comment by bbatsov** [comment]
I think it might have been easier for you to create a similar package. I'm fine with the approach.

> We already run checkdoc and bytecompile tests. What more do we need? There isn't a standard style for Elisp the way there is for e.g. Go. And I wouldn't want these checks to frustrate new contributors.

@xiongtx In practice ELisp mode defines how things are supposed to be indented, so I just want to make sure that code people submit was actually indented according to the mode and clean of redundant whitespace. Not a big deal, that's why I just imagined a tiny script that applies some clean to a buffer and compares this to what was committed.

**Comment by gonewest818** [comment]
Update.

<img width="703" alt="screen shot 2018-02-09 at 2 22 09 pm" src="https://user-images.githubusercontent.com/2460918/36052968-b3d3456a-0da4-11e8-9919-4e4a01512728.png">

**Comment by gonewest818** [comment]
When I run `elisp-lint` on the current cider sources I get a ton of errors about [lines being longer than 80 columns)](https://travis-ci.org/gonewest818/cider/jobs/342177930).

I happen to be old enough to remember when 80 columns was literally how wide the green phosphor CRT was, but these days I can easily get two columns of 100 characters on my 13" Retina laptop.

Not that there's any rush on this. I'm admittedly impatient, but it looks like the maintainer of elisp-lint hasn't touched it in years. I might rename and submit my version to MELPA, and see if Steve Purcell will allow the fork.
