### ISSUE TITLE
Debugger can't instrument function using a macro

### ISSUE THREAD

**Issue by IGJoshua** [clojure-emacs/cider#2201]
I'm currently trying to debug some clojure code to read some binary files, and to do so I use this (currently buggy) function.
```clojure
(defn- read-chars
  ([file index count]
   (let [file-start-position (.position file)
         arr (char-array count)
         decoder (.newDecoder (Charset/forName "UTF-8"))
         out-buffer (createCharBuffer count)]
     (.position file index)
     (.decode decoder file out-buffer true)
     (.position file file-start-position)
     (.get out-buffer arr)
     (String. arr)))
  ([file count]
   (read-chars file (.position file) count)
   (.position file (+ (.position file) count))))
```
When I use the hotkey to instrument this function however, I get only a StackOverflowException.

## Expected behavior
Function is instrumented and can be debugged through CIDER's debugger.

## Actual behavior
StackOverflowException thrown.

## Steps to reproduce the problem
The only way that I've been able to get this to occur is with this function in my current project. And it's only this one function. When I set the `out-buffer` to `nil` instead of a new CharBuffer (allocated via a statically-imported function from lwjgl), it no longer has the issue. After playing around with it I discovered that the issue seems to be with the macro created by `import-static` from the old clojure contrib library (updated version [available on GitHub](https://github.com/baznex/imports)).

The generated macro is as follows:
```clojure
(defmacro createCharBuffer [& args]
    (list
      '.
      'org.lwjgl.BufferUtils
      (apply list 'createCharBuffer args)))
```

So to reproduce this, creating that macro may be the only reasonable way.

## Environment & Version information
Spacemacs version 0.200.13

### CIDER version information

```
;; CIDER 0.16.0snapshot (package: 20171126.150), nREPL 0.2.12
;; Clojure 1.9.0, Java 1.8.0_152
```

### Lein/Boot version

Lein 2.8.1

### Emacs version

25.2.1

### Operating system

Windows 10

**Comment by vspinu** [comment]
Well, there is little to work with here. You need to come up with reproducible example. Do you really need that `org.lwjgl.BufferUtils` or it could be something else?  How does the SO exception look like?  I presume Charset is from `java.nio.charset`.

Your macro is recursive and that's fishy. During instrumentation macros are expanded, so most likely you get finite recursion during that expansion.

**Comment by dpsutton** [comment]
Its possible that this is a bug introduced by the debugger as well. During advent of code i tried to debug a few loops and adding the debugger shifted recurs out of tail call position. I'm not saying its not the code but just that the debugger's instrumentation doesn't keep to the code semantics perfectly

**Comment by IGJoshua** [comment]
This macro actually isn't recursive since the forms within the dot form are not evaluated as normal. This is a direct interop call, not a recursive macro. However, it's possible that CIDER is treating it as recursive and expanding it when it should not be.

**Comment by Cartmanishere** [comment]
I think the problem is with the `orchard.meta/macroexpand-all` and ultimately with `clojure.walk/macroexpand-all`.

Even `clojure.walk/macroexpand-all` gives a `StackOverflowException` with @IGJoshua's example.

When using the Dot Special Form, it should be evaluated as `(. Classname-symbol (method-symbol args*))` given in the [Java Interop](https://clojure.org/reference/java_interop). But this is not the observed behavior.

I think we could change the `macroexpand-all` implementation in orchard to account for this behavior.
