### ISSUE TITLE
Break down `cider-interaction.el`

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2203]
`cider-interaction.el` is now a grab bag for a ton of random functionality. That's mostly a legacy of the fact that originally cider was just a single file and I just split into 3 files - one for the nREPL code, one for the REPL and one for the interaction functions. I planned to make this more granular, but never got to doing so, even though it's trivial and not that much of work. That's why I'm putting this ticket out there - as a reminder for myself and with the hope that someone else might pick it up and finish it. Generally functionality like tracing, code-completion, formating, evaluation, etc should get a separate source file and the smaller misc commands should likely go to `cider-mode` directly. 

//cc @gonewest818 @xiongtx @ckoparkar @dpsutton

**Comment by gganley** [comment]
Do you just want me to look at `cider-interaction` to refactor or look into the other files to see if those contain code that may also benefit from refactoring.

**Comment by bbatsov** [comment]
You can certainly do both - there are opportunities to reorganize better everywhere (it's super messy at this point), I mentioned `cider-interactions.el` only mostly because extracting things from there is clear cut and doesn't require much knowledge of the codebase in general.

**Comment by abo-abo** [comment]
@bbatsov Emacs has a bunch of features for declaring functions/variables/files as obsolete, would be nice to use them. As you see, this rename broke at least 3 packages that depend on CIDER. I notice the breakage only now thanks to an issue by @tarsius, since I don't use CIDER from MELPA.

**Comment by tarsius** [comment]
> I don't use CIDER from MELPA

Nor do I, but I have tools that rival those used by Santa Clause, so I know when an elisp maintainer has been naughty. :stuck_out_tongue_winking_eye:

**Comment by bbatsov** [comment]
> @bbatsov Emacs has a bunch of features for declaring functions/variables/files as obsolete, would be nice to use them. As you see, this rename broke at least 3 packages that depend on CIDER. I notice the breakage only now thanks to an issue by @tarsius, since I don't use CIDER from MELPA.

I think I was just moving things around and I planned to leave some dummy `cider-interaction.el` which just required `cider-eval.el` and produced some warning, but I guess I forgot to do this. :-) Is there really something to mark files as obsolete? That's the first time I hear of this.

**Comment by bbatsov** [comment]
> Nor do I, but I have tools that rival those used by Santa Clause, so I know when an elisp maintainer has been naughty. 😜

For me it's easy to figure this out - I'm naughty all the time! 😆

**Comment by abo-abo** [comment]
@bbatsov Emacs features for marking things obsolete:

- `define-obsolete-function-alias`
- `define-obsolete-variable-alias`
- move the whole file to an `obsolete/` subfolder (would work nicely for this issue)

In each case, the user will get a warning that the function/variable/file is obsolete, prompting a switch to a new way of working.
Once the users were given enough time to be annoyed by "obsolete" warnings (that don't break anything though), the obsolete aliases can be removed.

**Comment by bbatsov** [comment]
I always use obsolete aliases for things I consider API, but obviously I don't do this for things I consider implementation details. Didn't know about the `obsolete` subfolder technique - I'll take a look at this at some point.
