### ISSUE TITLE
Performance issues cider+figwheel+aggressive-indent-mode

### ISSUE THREAD

**Issue by achikin** [clojure-emacs/cider#2210]
## Expected behavior
There are no performance issues when I start Fighweel repl from cider as described [here](https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl) and turn `aggressive-indent-mode` on.
## Actual behavior
I see severe performance issues (slow typing etc) in clojurescript files when figwheel started from cider as described in previous section.
## Steps to reproduce the problem
1. Generate a simple project with clojurescript. E.g. using lein reagent template
```
lein new reagent test
```
2. Install `aggressive-indent-mode` as described [here](https://github.com/Malabarba/aggressive-indent-mode)
3. Follow [this guide](https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl) to be able to start figwheel from cider.
4. Open any cljs file in your project.
5. `M-x aggressive-indent-mode`
6. Run `M-x cider-jack-in-clojurescript` command.
7. Try to type something in your cljs file.

I've started emacs profiler to debug the situation and found out that most of the time is spent in `aggressive-indent-mode`, which in turn leverages `clojure-indent-region` which in turn uses `cider--get-symbol-indent` (**please check emacs profiler output file below**)
### CIDER version information
```
;; CIDER 0.17.0snapshot (package: 20180203.535), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_20
```
### Lein/Boot version
```
→ lein --version
Leiningen 2.8.1 on Java 1.8.0_20 Java HotSpot(TM) 64-Bit Server VM
```
### Emacs version
```
→ emacs --version
GNU Emacs 25.3.1
```
### Operating system
`MacOSX 10.13.2`

### Emacs profiler output
[profile.txt](https://github.com/clojure-emacs/cider/files/1735025/profile.txt)

**Comment by bbatsov** [comment]
It'd be good if you gathered some info on this performance problem using the built-in Elisp profiler (https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html).

**Comment by achikin** [comment]
@bbatsov profiler output is already attached to the end of the ticket. Please check `Emacs profiler output` section.

**Comment by bbatsov** [comment]
I see. Sorry about this, most people simply dump the data in the tickets. It's clear that the problem is coming from the dynamic font-locking, I guess if you disable it everything's going to be fine. 

Try setting `cider-font-lock-dynamically` to nil. I guess you have to decide what's more important for you - nice font-locking or automatic indentation. :-)

**Comment by achikin** [comment]
@bbatsov thank you very much for your help. Figwheel repl is much faster after turning `cider-dynamic-indentation` off. At least I have autocomplete, docs and go to definition now.
As for the flexible indentation - seems like it does not affect my workflow that much and I can sacrifice it. Thank you.
