### ISSUE TITLE
Scope .dir-locals.el settings to specific modes

### ISSUE THREAD

**Issue by gonewest818** [clojure-emacs/cider#2211]
In a [pull request on another project](https://github.com/gonewest818/adafruit-wisdom.el/pull/1) @tarsius called me out on a `.dir-locals.el` file that set configuration like `fill-column` using `nil` as the mode name rather than scoping those settings to a specific mode. Citing, e.g. potential for adverse effects on things like `dired` and `magit`.

Just putting a note here because the same practice occurs in CIDER and clojure-mode, and I wanted that discussion to play out where it matters more (whereas my side project has only a few dozens of downloads).

**Comment by bbatsov** [comment]
Yeah, he made a valid point. I just set those things globally usually, and I didn't notice anything bad happening, but it's probably a possibility. I'll take a closer look at the PR you referenced, but I think it's fine to limit those setting to `emacs-lisp-mode`.

**Comment by gganley** [comment]
So should all locals be assigned to emacs-lisp-mode or only visual formatting commands such as `fill-column`

**Comment by gonewest818** [comment]
I would say all of them in `emacs-lisp-mode` is fine.

**Comment by gganley** [comment]
Apollogies for polluting with references, still getting the hang of using magit / not sucking with git.

**Comment by gonewest818** [comment]
For future, if you want to avoid the references (and by the way it doesn’t feel like “pollution” to me) you can omit the “[#2211]” from your commit message until the work is done.

With git/magit you can rebase, squash, and reword commits in your branch to clean up the history before it gets merged. That’s what I tend to do with my pull requests.

**Comment by gganley** [comment]
Thank you, feedback like this is why I wanted to get into OSS.
