### ISSUE TITLE
Updated tramp.el is merging into Emacs master branch

### ISSUE THREAD

**Issue by gonewest818** [clojure-emacs/cider#2216]
Looks like the Emacs maintainers are merging a new `tramp.el` into branch master for Emacs 27, and the new version has incompatible changes.  Making a note here to go back and deal with this once the dust settles on that integration work.

```
** ELISP-LINT: check cider.el...
** Ignoring validators: fill-column, package-format
* Run byte-compile
Loading /home/travis/build/gonewest818/cider/cider-autoloads.el (source)...
In toplevel form:
cider.el:755:7:Error: reference to free variable ‘tramp-current-host’
```

**Comment by bbatsov** [comment]
I guess we should check what was it renamed to and add some conditional logic to support Emacs 27.

**Comment by gonewest818** [comment]
Here's the commit:
http://git.savannah.gnu.org/cgit/tramp.git/commit/?id=b735fd3ec9f79fde4bd9a97d560552cc274731e0

and the relevant diff:
http://git.savannah.gnu.org/cgit/tramp.git/diff/lisp/tramp.el?id=b735fd3ec9f79fde4bd9a97d560552cc274731e0

where the log message includes the following: `* tramp.el (tramp-current-method, tramp-current-user) (tramp-current-domain, tramp-current-host) (tramp-current-port): Remove.` and later on `(tramp-action-login, tramp-read-passwd): Do not set tramp-current-*.`

I haven't investigated far enough to understand the motivation, but there was a concerted effort to remove those vars.
