### ISSUE TITLE
Ambiguity concerning the PR template

### ISSUE THREAD

**Issue by gganley** [clojure-emacs/cider#2223]
Currently the [PR template](https://github.com/clojure-emacs/cider/blob/master/.github/PULL_REQUEST_TEMPLATE.md) combines two seemingly separate things: generating byte code and checkdoc warnings

> The new code is not generating bytecode or M-x checkdoc warnings

This could be interpreted as two things:

`! generating (bytecode || checkdoc) warnings`

or

`! generating (bytecode || (checkdoc warnings))`

I suggest that these are broken into two separate boxes I.e.

- [ ] The new code is not generating bytecode
- [ ] `M-x checkdoc` does not generate any warnings

**Comment by xiongtx** [comment]
"bytecode warnings" refers to [byte-compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html) warnings.

Perhaps

> The new code does not generate [byte-compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html) or [`checkdoc`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips.html) warnings

is more clear?

**Comment by gganley** [comment]
Is there a reason these two are paired? I see no reason to pair them personally.

**Comment by xiongtx** [comment]
In most cases byte-compilation and `checkdoc` warnings do not impact functionality (unlike `make test` failures).
