### ISSUE TITLE
Cljs repl check does not work

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/cider#2230]
The cljs repl checking does not work.

The way it checks for the presence of, for example, figwheel is to call `find-ns` on `figwheel-sidecar.repl-api` This namespace does not exist. However, the cljs start up requires this namespace which it does find. It seems that we need to check the classpath to see if the requirement will succeed rather than if the namespace already exists.

**Comment by dpsutton** [comment]
Probably the best way to do this is expose something in nrepl to check that a dependency is present using [jar-namespaces]
(https://github.com/clojure-emacs/orchard/blob/master/src/orchard/namespace.clj#L23) from orchard

**Comment by bbatsov** [comment]
Yes, you're right. Alternatively we can check on the classpath for those deps.

**Comment by manuel-uberti** [comment]
Is this why with the latest CIDER from MELPA selecting `Figwheel` results in: `user-error: Figwheel is not available.  Please check http://cider.readthedocs.io/en/latest/up_and_running/#clojurescript-usage`?

**Comment by bbatsov** [comment]
Yeah, that's the problem this causes. You can work around this easily by adding this to your config after loading CIDER:

```
(defun cider-check-figwheel-requirements ()
  "Check whether we can start a Figwheel ClojureScript REPL."
t)
```

I'll try to fix it as soon as possible, but I'm pretty short on time this week.

**Comment by manuel-uberti** [comment]
Great thanks, it's working now.
