### ISSUE TITLE
Can not distinguish between clj and cljs repls any more

### ISSUE THREAD

**Issue by achikin** [clojure-emacs/cider#2244]
## Expected behavior
In Spacemacs when I use `helm-mini` or standard buffer list(C-x C-b) I could clearly distinguish between clj and cljs repls because cljs repl had `CLJS` stright after `*cider-repl`
E.g. `*cider-repl CLJS project-name`
## Actual behavior
Because of the latest changes [in this line](https://github.com/clojure-emacs/cider/commit/6a7b8ba0b7574c0fcf21718448a29cbcb074dbff#diff-00bd1ee3b6816bf7f502bc824ec4a6e9L632) cljs repl has `(cljs)` at the end of a repl buffer name and `helm-mini` or standard buffer list truncate buffer names so I can't clearly understand which one of the repl buffers is cljs.
E.g. `*cider-repl long-project-name(cljs)`
![screen shot 2018-03-20 at 19 33 12](https://user-images.githubusercontent.com/611419/37668508-bdb3399c-2c75-11e8-94c7-a04f116a35d3.png)

## Steps to reproduce the problem
- Start emacs
- Update cider to the latest version
- Open any clojure file that belongs to a project
- `M-x cider-jack-in-clojurescript`
- wait for repls to start
- `C-x C-b` to open buffer list

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
CIDER 0.17.0snapshot (package: 20180319.1204), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_20
```

### Lein/Boot version

Leiningen 2.8.1 on Java 1.8.0_20 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 25.3.1

### Operating system

High Sierra 10.13.3(17D102)

**Comment by bbatsov** [comment]
Why are the buffer names truncated in this manner? I use `ido` and `ivy` and it's never a problem with them. Funny enough I changed this because for me it was hard to spot cljs buffers - I like it much more when the name appears afterwards as I see the two entries always one next to other in the buffer list. 

But I do get your point. I'm curious what others think about this. We can obviously make this customizable, but that might be an overkill. Usually like 5 people end up using some obscure customizations.

**Comment by achikin** [comment]
@bbatsov I use (almost) vanilla Spacemacs with slightly increased font size. You could easily reproduce it [from here](http://spacemacs.org/)

**Comment by manuel-uberti** [comment]
@bbatsov I too use `ivy`, and I have the problem @achikin reported only in `ibuffer` and `counsel-ibuffer`.

**Comment by bbatsov** [comment]
I know how I can reproduce this, i just wonder why people would truncate buffer names this way. :-) I'm open to ideas, but I definitely don't think the old approach was good. The only reason I tolerated it was that until recently I very rarely would spin a sibling cljs repl. Now that I've been focusing on improving the cljs support this quickly became very annoying for me. 

Btw, you know there's a command to toggle between a cljs and clj repl for the same project, right? :-)

**Comment by manuel-uberti** [comment]
@bbatsov yes, I use that all the time. TBH, I noticed the problem in `ibuffer` just because of this issue. :)

**Comment by achikin** [comment]
So, everything works for ivy users, but there are a lot of people who use helm or ibuffer.

**Comment by achikin** [comment]
@bbatsov what is so annoying in `CLJS` straight after `cider-repl?`. It clearly shows which repl is which.
Regarding to `cider-repl-switch-to-other` - I could use it in conjunction with `cider-switch-to-repl-buffer` if `cider-switch-to-repl-buffer` would open in the same window where I've called it, but it always opens in the same window it was before, which is unpredictable and makes me memorize where was it last time.

**Comment by bbatsov** [comment]
> So, everything works for ivy users, but there are a lot of people who use helm or ibuffer.

Well, looking at the screenshot from you the prefix "CLJS" is going to hide the project name completely in some cases. Frankly this seems like a bigger problem to me. 

> @bbatsov what is so annoying in CLJS straight after cider-repl?. It clearly shows which repl is which.

I think buffers to appear grouped together in ivy when I start typing `*cider-repl` and I don't like the type of the connection being if front of the project, as this look odd to me. Admitted all of this is very subjective, but I don't have any brilliant ideas about the presentation of the type.

> Regarding to cider-repl-switch-to-other - I could use it in conjunction with cider-switch-to-repl-buffer if cider-switch-to-repl-buffer would open in the same window where I've called it, but it always opens in the same window it was before, which is unpredictable and makes me memorize where was it last time.

Hmm, that's odd. Can you record some short gif and upload it here? I'd like to see what exactly happens for you.

**Comment by achikin** [comment]
> I think buffers to appear grouped together in ivy when I start typing *cider-repl and I don't like the type of the connection being if front of the project, as this look odd to me. Admitted all of this is very subjective, but I don't have any brilliant ideas about the presentation of the type.

How about using the forth column, which shows buffer-mode?
![screen shot 2018-03-21 at 20 56 39](https://user-images.githubusercontent.com/611419/37728107-75d7fa10-2d4a-11e8-8d7b-5c0cf69f7ba6.png)

> Hmm, that's odd. Can you record some short gif and upload it here? I'd like to see what exactly happens for you.

Created a separate ticket #2246

**Comment by bbatsov** [comment]
Something like `REPL[cljs]`? I've actually been thinking about this myself and it'd be very easy to implement.

**Comment by achikin** [comment]
@bbatsov How about `Clj REPL` and `Cljs REPL` if modes allow descriptions with spaces? Looks more human-readable.

**Comment by bbatsov** [comment]
I've never seen a mode with spaces in its name - I assume the problem is that this way you can know if you're looking at too mode names or one when checking the mode line. Notice "Emacs-Lisp".
