### ISSUE TITLE
cider-jack-in outside of project does not supported in recently new version

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#2249]
## Expected behavior
In an plain clojure source code file `test.clj` (*NOT in project*), then `cider-jack-in`. CIDER should be able to jack-in outside of project.

## Actual behavior
CIDER reports `user-error: Unsupported project type ‘clojure-clj’`

## Steps to reproduce the problem

In an plain clojure source code file `test.clj` (*NOT in project*), then `cider-jack-in`. CIDER should be able to jack-in outside of project.

After check out function `cider-jack-in` source code:
`cider-jack-in` does not go to jack-in outside of project, it warning with `Unsupported project type 'clojure'` Because in my buffer, variable `cider-default-repl-command` becomes `"clojure"`. but it is not in `cider--identify-buildtools-present`. I have not customized the variable `cider-default-repl-command` to `clojure`. And after yesterday upgrade of CIDER, I check out code, it already has new `cider-project-type`. But `cider-jack-in` outside of project still did not match `cider-project-type` condition match in function `cider-jack-in`. I think might a missing handling on "out side of project" ?

### CIDER version information

```
CIDER 0.17.0snapshot (package: 20180323.1903)
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
```

### Emacs version

GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.28) of 2018-03-21

### Operating system

Arch Linux

**Comment by carlosgeos** [comment]
I can reproduce. Outside a project I get `user-error: Unsupported project type ‘clojure’`.

As per https://github.com/clojure-emacs/cider/commit/01d728a077e02e02afbe2b989cd0f9b455b581d2, I think the type should be 'clojure-cli'.

Quick fix -> set `cider-default-repl-command` to `"clojure-cli"` instead of `clojure`.

**Comment by stardiviner** [comment]
Yes, @carlosgeos This setting fixed it.
