### ISSUE TITLE
[FEATURE] improve CIDER REPL [M-r] history backward search with `completing-read`

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#2252]
Recently I found some REPL inherited from `comint-mode` supports `[M-r]` to backward searching history. And CIDER supports too. But it is very non-intuitive. If it can support `completing-read`, then user can use `ivy` or `helm`. That will be great.

**Comment by NightMachinary** [comment]
It would also be great if the arrow keys worked like in shell (went through the history of entered commands).

**Comment by bbatsov** [comment]
> It would also be great if the arrow keys worked like in shell (went through the history of entered commands).

But this would not be in line with how shells/repls running in Emacs are normally behaving. I guess you can always remap the relevant keys yourself if you'd like to have such a behaviour. 

@stardiviner Yeah, I guess we can do this. I'm wondering why we haven't done it like this initially. Btw, do you know about this feature http://cider.readthedocs.io/en/latest/using_the_repl/#repl-history-browser? 

I recall one problem with the history browsing was that often the expressions there are multi-line which makes it hard to use something like ivy with them.

**Comment by stardiviner** [comment]
@bbatsov This is great enough. Thanks. I think I should close this issue. Personally I remap `[M-r]` to `cider-repl-history`.
