### ISSUE TITLE
Ability to add Continue-halting breakpoints

### ISSUE THREAD

**Issue by NightMachinary** [clojure-emacs/cider#2253]
Coming from Intellij, I really miss the ability to add 'hard' breakpoints to code where the debugger would stop at even if you have continued from a previous breakpoint. From what I gathered, to be able to step over my code, I need to set #dbg so that all forms have a breakpoint on them. Then to skip some forms I need to navigate to them, which is especially hard since the keys I normally use for navigation are taken over by the debugger (I use evil-lispy), and press 'h'. In Intellij, I just set a breakpoint where I want and can step over from that point or continue to the next breakpoint as I see fit.

**Comment by vspinu** [comment]
To clarify how this one was fixed. There are now two continue commands, one simple on `c` which stops on every breakpoint (`#break` or `#dbg`) and the other on `C` which skips all breakpoints.
