### ISSUE TITLE
strange output from nrepl logging

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/cider#2254]
## Expected behavior
the init-debugger message would contain one instance of print-length and print-level

## Actual behavior
```
(-->
  id           "8"
  op           "init-debugger"
  session      "b665f868-d469-422c-9446-9665eed946df"
  time-stamp   "2018-03-27 08:19:07.742500455"
  print-length 10
  print-length 10
  print-length 10
  print-length 10
  print-length 10
  print-length 10
  print-level  10
  print-level  10
  print-level  10
  print-level  10
  print-level  10
  print-level  10
)
```

it seems to vary based on the project. see https://github.com/clojure-emacs/cider-nrepl/issues/518 for an even worse version of this

## Steps to reproduce the problem

`lein new whatever`. jack in to the new project

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; Connected to nREPL server - nrepl://localhost:45469
;; CIDER 0.17.0-snapshot, nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_161
```

**Comment by dpsutton** [comment]
tracing through it looks like this is an artifact of the logger and not representative of the message going across

**Comment by bbatsov** [comment]
Can you elaborate on this? Of the top of my head I can't imagine how something like this can be happening.

**Comment by dpsutton** [comment]
no i can't imagine why. I didn't have much time this morning before work so i wanted to log a ticket. just leaving this here for later follow up. be nice if someone could confirm this happens for them as well. I'm not running anything crazy on my machine.
