### ISSUE TITLE
Support comment ignoring in `cider-insert-defun-in-repl`

### ISSUE THREAD

**Issue by halgari** [clojure-emacs/cider#2255]
When writing code in a namespace it's not uncommon to keep a set of forms in a comment block for on-the-fly testing (example: https://github.com/clojure/spec.alpha/blob/master/src/test/clojure/clojure/test_clojure/spec.clj#L219-L221) In some other editors evaling a "top-level" form ignores comments and "top level" refers to the highest level form excluding the comment. 

## Expected behavior
```
(comment
(+ 1 2) ;; eval-in inside this form 

)
```
=> `3`

## Actual behavior
Loads the entire `(comment ... )` form in the repl

## Steps to reproduce the problem

Run `cider-insert-defun-in-repl` inside any comment block. 

### CIDER version information
20180131.913

**Comment by halgari** [comment]
And it seems the Clojure guide just added a example video of the behavior I'd like to see: https://clojure.org/images/content/guides/repl/cursive-repl-demo.gif

https://clojure.org/guides/repl/enhancing_your_repl_workflow

**Comment by bbatsov** [comment]
I guess now that #2323 is merged we can close this ticket.
