### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by acidjunk** [clojure-emacs/cider#2261]
## Expected behavior
installes package

## Actual behavior
package-install-from-archive: http://melpa.milkbox.net/packages/cider-20150114.512.tar: Not found

## Steps to reproduce the problem
M-x package-install cider

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*
Used a clean Emacs

## Environment & Version information
Mac OS

### Lein/Boot version

2.8.1

### Emacs version
25.3

### Operating system

Mac OS High Sierra

**Comment by expez** [comment]
`M-x package-refresh-contents <RET>`

`M-x package-install cider<RET>`

As you can see from the URL, you're trying to install a package from 2015.  In other words, your list of packages is stale, or you CIDER pinned it to that specific build.  `melpa` only has the bleeding edge which is why the package isn't found.

Hope that helps!

**Comment by acidjunk** [comment]
Thanks for the quick response. New to Emacs: followed instructions from a book that came with an .emac.d folder. Now did it from scratch and it works like a charm.

**Comment by SSYH** [comment]
When I refresh contents, I see chess, chm-view, citrus-mode, cl-generic, cl-lib... but no cider :(

**Comment by dpsutton** [comment]
@SSYH which sources do you have configured? Its important that you have melpa in addition to elpa.

**Comment by SSYH** [comment]
@dpsutton - thanks for that advice. 
This page 
( http://ergoemacs.org/emacs/emacs_package_system.html ) 
turned out to be helpful.

**Comment by j-cr** [comment]
Hey, weirdly I got hit by a similar issue (this url pops out in google, thus reporting here in case anyone else gets hit by this; not sure it's an issue with cider per se).

Trying to update to cider 0.26.0: https://stable.melpa.org/#/cider
package.el shows only cider 0.25.0
Installation fails with `package-install-from-archive: https://stable.melpa.org/packages/cider-0.25.0.tar: Not found`
(package-refresh-contents obviously doesn't help)

Not sure what causes this, but for me changing the priorities (`package-archive-priorities`) around and refreshing again helped.
