### ISSUE TITLE
Live-update the *cider-inspect* buffer

### ISSUE THREAD

**Issue by it3ration** [clojure-emacs/cider#2262]
# Feature request

Hey folks, love the project, I use it every day at my job. :)

Would it be possible to add an option to live-update the `*cider-inspect*` buffer as you are stepping through an instrumented function whilst debugging? Ideally it'd have a keybinding in the `*cider-inspect*` buffer that toggles it on and off. Perhaps it should even be persistent across debugging / emacs sessions?

Cheers, -it3ration

**Comment by bbatsov** [comment]
> Ideally it'd have a keybinding in the *cider-inspect* buffer that toggles it on and off. Perhaps it should even be persistent across debugging / emacs sessions?

The problem with such a command is that it will make sense only when the debugger is running, and you can use the inspector without the debugger.

**Comment by it3ration** [comment]
Ah, didn't know that. What do you use the inspect buffer for when not debugging?

**Comment by bbatsov** [comment]
Drilling in big data structures. That's what it was initially created for, we've bolted the debugging functionality later. :-)

The idea is that you'd dump some big data structures straight into the inspector instead of in the REPL, and explore them there.

**Comment by it3ration** [comment]
Ah got it. :)
