### ISSUE TITLE
`spit`-ed data be almost omitted in CIDER nREPL

### ISSUE THREAD

**Issue by soulawaker** [clojure-emacs/cider#2267]
## Expected behavior
Entire data be stored to a file by `spit` in CIDER nREPL.

## Actual behavior
`spit`-ed data be omitted in CIDER nREPL.

## Steps to reproduce the problem
```clojure
user> (defn store-edn [path map]
             (do (spit path (with-out-str (pr map)))))

user> (store-edn some-file quite-long-map)

user> (defn read-edn [path] (read-string (slurp path)))

user> (read-edn some-file)
RuntimeException Map literal must contain an even number of forms  clojure.lang.Util.runtimeException

;;or just
user> (spit some-file quite-long-map)
user> (slurp some-file)
"{<quite-long-map contents, almost omitted>, ...}"
```

### CIDER version information
```
CIDER 0.17.0snapshot (package: 20180402.2126), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_161
```

### Lein/Boot version

Lein 2.8.1

### Emacs version

25.3.2 with Spacemacs 0.300.0

### Operating system

Elementary OS Loki 0.4.1 based Ubuntu 16.04

**Comment by bbatsov** [comment]
I don't think I understand the problem. Can you elaborate what exactly is problematic right now?

**Comment by soulawaker** [comment]
I tried to `spit` a quite long map (or a sequence contains many maps) to a file. It is nearly 600kB. But only under 60kB contents spitted to a file. I opened this file and saw that original contents almost was truncated and ellipsis mark remained in tail of the map (or sequence) as CIDER nREPL do.

**Comment by vspinu** [comment]
This used to be a consequence of *print-length*. See #2152 which seems to have been fixed.

**Comment by soulawaker** [comment]
Thanks. It worked with `(binding [*print-length* nil] (spit ...))`. But it seems to be unnatural. We need to make this distinguished..., anyway, the idea evades me right now.

**Comment by bbatsov** [comment]
Or you can just disable the default `*print-lenth*` that cider sets on REPL init. But I do agree it's somewhat odd that file operations would be affected by `*print-lenth*`.

**Comment by Macroz** [comment]
I just hit this problem today :-1:

**Comment by bbatsov** [comment]
@cichli removed the default `*print-length*` in CIDER 0.21. Perhaps your running an older version? If so up - just adjust the `*print-length*` accordingly.

**Comment by Macroz** [comment]
> @cichli removed the default `*print-length*` in CIDER 0.21. Perhaps your running an older version? If so up - just adjust the `*print-length*` accordingly.

Thanks for the tip. I'm still with `CIDER 0.21.0snapshot (package: 20190125.1339)` that gives `
Saving cider-repl-print-length: This field should contain an integer` so I put a large number there for now.
