### ISSUE TITLE
[improvement] Too little functionality in test output

### ISSUE THREAD

**Issue by Invertisment** [clojure-emacs/cider#2273]
When executing tests the output contains too little information.

It is hard to have a lot of tests without duplicating code.

## Expected behavior
0. See stacktraces or parts of the stacktraces in the test result
0. To jump to `deftest` or to failing `is` check on [enter] key press

## Actual behavior
0. Only last stacktrace frame name is printed
0. Jumps to the failing `is` call

## Steps to reproduce the problem
Create a test with `is` in a separate function.

## Versions
```
;; CIDER 0.17.0snapshot (package: 20180122.2345), nREPL 0.2.13
;; Clojure 1.8.0, Java 9.0.4
```

**Comment by Invertisment** [comment]
### Previews:
![test-code](https://user-images.githubusercontent.com/1641263/39038157-7692d1fc-448b-11e8-92dd-65febf6f75f6.png)

![screenshot at 2018-04-20 10 57 31](https://user-images.githubusercontent.com/1641263/39038477-4ba39b60-448c-11e8-9bcc-6eb32ef36420.png)

**Comment by bbatsov** [comment]
I'm not sure I get what you mean exactly. I understand that one thing is the problem with a predicate defined outside a `deftest`, but I don't quite get what's the other problem.

**Comment by Invertisment** [comment]
Yes, there are two problems
Looks like that one of them was an incompatibility with emacs 24. I use ubuntu and their package is behind. After updating I see the stack trace frame in the test results menu.

Will check about the `is` macro call outside the deftest. I think it should work the same as in the issue.
