### ISSUE TITLE
[FEATURE REQUEST] Connection switching menu

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/cider#2274]
At present, it's difficult to manipulate several nREPL connections to remote instances of the same project. It'd be awesome of just clicking on the `cider[ ... ]` entry on the mode bar would let you just pick from one of the active nREPL connections to choose the active one.

**Comment by bbatsov** [comment]
Turns when you click on the modeline you get the standard mode menus, so I'm not sure that's technically doable, but we can certainly come up with an easier way to set buffer connections.

**Comment by vspinu** [comment]
I would say that there is no need for this with the new API. With multiple connections, either switch to the desired connection REPL (evaluation operates on the most recent session) or associate (link) your connections with narrower contexts (buffers or directories).
