### ISSUE TITLE
Doesn't play well with evil-snipe

### ISSUE THREAD

**Issue by NightMachinary** [clojure-emacs/cider#2275]
evil-snipe overrides 's', and so 's' doesn't activate stacktrace when debugging.

**Comment by bbatsov** [comment]
That's not really a CIDER issue. `evil-snipe` (and similar modes) should be careful with what their binding/changing in special modes.

**Comment by NightMachinary** [comment]
@bbatsov I tested edebug, and it had no issues with evil-snipe ('s' ran `edebug-step-mode` when edebug was active.).

**Comment by NightMachinary** [comment]
@bbatsov From evil-snipe:
I'm not familiar with CIDER's debugger, but you can prevent evil-snipe from being enabled in certain major modes by adding it to evil-snipe-disabled-modes, or by adding turn-off-evil-snipe-mode to the appropriate hook. e.g.

;; NOTE: I'm guessing the major mode and hook names
(push 'cider-debug-mode evil-snipe-disabled-modes)
;; or
(add-hook 'cider-debug-mode-hook #'turn-off-evil-snipe-mode)
If you tell me what the appropriate major-mode is, I'll be happy to add it to evil-snipe-disabled-modes's default.

**Comment by bbatsov** [comment]
It's a minor mode actually - `cider--debug-mode`.

**Comment by NightMachinary** [comment]
@bbatsov The hook cider--debug-mode-hook runs both when entering and leaving debug mode. How do I differentiate between these two to disable/enable evil-snipe?

**Comment by NightMachinary** [comment]
Nevermind, I found the answer:
```
(add-hook 'cider--debug-mode-hook (lambda ()
                                      (if (bound-and-true-p cider--debug-mode)
                                          (turn-off-evil-snipe-mode)
                                        (turn-on-evil-snipe-mode))))
```
This should be added to evil-snipe layer. Can you @bbatsov do that? My last PR still hasn't been merged, so I can't open a new one.

**Comment by bbatsov** [comment]
Great! Guess we can close this then.
