### ISSUE TITLE
Experiencing tremendous slowdown when editing cljc files, 

### ISSUE THREAD

**Issue by bhauman** [clojure-emacs/cider#2281]
[slow-emacs-profile.txt](https://github.com/clojure-emacs/cider/files/1974390/slow-emacs-profile.txt)

## Expected behavior
Typing characters into a buffer should not take 0.9 seconds per character. 

## Actual behavior
Extremely slow character by character response time in the cljc file's emacs buffer. This behavior develops over time after using the buffer for 10 minutes to a half an hour. This behavior still occurs when `cider-font-lock-reader-conditionals` is set to `f`. This behavior also continues to occur if I set the buffer to a `Clojure` buffer instead of a `ClojureC` buffer.

## Steps to reproduce the problem

Edit a largish cljc (1000 lines) file for about 10 minutes and you should notice a significant slowdown.
When I'm doing this there is no ClojureScript REPL connection only a Clojure REPL connection.

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:57353
;; CIDER 0.17.0snapshot (package: 20180426.1647), nREPL 0.2.13
```

### Lein/Boot version

Using tools.deps

### Emacs version

24.5.1

### Operating system

OSX 10.12.6 (16G29)

**Comment by dpsutton** [comment]
```
- redisplay_internal (C function)                                9387  37%
 - jit-lock-function                                             6468  25%
  - jit-lock-fontify-now                                         6465  25%
   - jit-lock--run-functions                                     6464  25%
    - run-hook-wrapped                                           6464  25%
     - #<compiled 0x7b45bf9>                                     6464  25%
      - font-lock-fontify-region                                 6464  25%
       - #<lambda 0x1b708b4ab4243c4b>                            6450  25%
        - apply                                                  6344  25%
         - #<lambda 0x1b708b4ab4243c4b>                          6344  25%
          - apply                                                6284  24%
           - #<lambda 0x1b708b4ab4243c4b>                        6284  24%
            - apply                                              6239  24%
             - #<lambda 0x1b708b4ab4243c4b>                      6239  24%
              - apply                                            6238  24%
               - #<lambda 0x1b708b4ab4243c4b>                    6238  24%
                - apply                                          6235  24%
                 - #<lambda 0x1b708b4ab4243c4b>                  6235  24%
                  - let*                                         5451  21%
                   - unwind-protect                              5451  21%
                    - progn                                      5451  21%
                     - if                                        5449  21%
                      - progn                                    5449  21%
                       - cider--update-locals-for-region               5448  21%
                        - save-excursion                         5448  21%
                         - save-excursion                        5443  21%
                          - let                                  4512  17%
                           - condition-case                      3550  14%
                            - progn                              3096  12%
                             - cider--parse-and-apply-locals               3094  12%
                              - while                            3094  12%
                               - let                             3078  12%
                                - if                             2560  10%
                                 - let                           2558  10%
                                  - cider--parse-and-apply-locals               1257   4%
```
`cider--parse-and-apply-locals` and `cider--update-locals-for-region` (which calls the parse and apply locals` seem to be the culprits for me. I think this is buffer size dependent and not based on cljc. I'm in a 1781 line cljs file and experiencing the same thing

**Comment by dpsutton** [comment]
@bhauman there's a function `cider--wrap-fontify-locals` that will invoke this except 

```
      (when cider-font-lock-dynamically
        (cider--update-locals-for-region beg end))
```

I set `cider-font-lock-dynamically` to nil and i see the slowdown go away. Can you give that a shot and see if it remedies it at least partially?

**Comment by bhauman** [comment]
@dpsutton I will give this a shot

**Comment by bbatsov** [comment]
There's also `cider-font-lock-reader-conditionals` that's specific to `cljc` files, so disabling it might be another thing to try. I recall someone complaining recently that this was causing performance problems for them.

**Comment by bbatsov** [comment]
Ops, I didn't see you already check this. Forget about my comment!

**Comment by bbatsov** [comment]
@bhauman So, what happened here? 

Also - do you happen to be using `aggressive-indent-mode?

**Comment by bhauman** [comment]
I haven't had a problem since I set `cider-font-lock-reader-conditionals` to `nil`.

I think I made a mistake when I set `cider-font-lock-reader-conditionals` to `f` when it should have been `nil`?

It could be that I haven't left a buffer open long enough to get there yet.

**Comment by bhauman** [comment]
and I'm not using `aggressive-indent-mode`

**Comment by bbatsov** [comment]
> I think I made a mistake when I set cider-font-lock-reader-conditionals to f when it should have been nil?

Yeah, probably this was the problem, although I would have expected you to get some unresolved symbol error in this case. 

Guess now we know we really have to improve the performance of the regexps doing the font-locking. /cc @alvinfrancis

**Comment by alvinfrancis** [comment]
Will look into this. Colleague actually pointed this out to me the other
day but I figured it was just something else in his configuration. Was
working  fine for me, but I was on an older version.

Thanks for the heads up.

**Comment by alvinfrancis** [comment]
Having trouble replicating this.  Currently on `CIDER 0.17.0 (package: 20180508.1001) (Andalucía), nREPL 0.2.13`.  Tried out editing a fairly large cljc file of 800 lines and apart from an initial slowdown on first character insert, there were no slowdown issues at all even after waiting for 10 minutes.  I also artificially inflated the size by repeating the top level forms until it reached ~3000 lines and still no issues.

Will continue investigating but any more info would be appreciated.  I'm wondering if it is some combination of configuration that's required for the issue to show up.

**Comment by bhauman** [comment]
Hmmm did you have large sections of :clj code and :cljs code?  I.E

#?(:cljs (do  ...  half of a file of cljs ....   )))

#?(:clj (do  ...  half of a file of clj ....   )))

**Comment by alvinfrancis** [comment]
Continued investigating this with my colleague who experiences slowdown on large-ish files with short reader conditional expressions.  Could not replicate it until I tried matching his emacs build (we're both running on macOS).  I've been using the [mituharu](https://bitbucket.org/mituharu/emacs-mac/) native port, while I believe his was on the Cocoa version.  Anyway, I am experiencing a slowdown on the Cocoa version of Emacs.  Initial profiling seems to better match the profile report by @dpsutton.

Will continue investigating what's causing the difference in performance.

**Comment by bhauman** [comment]
I've been using this for as long as I can remember.

https://emacsformacosx.com/

**Comment by alvinfrancis** [comment]
Further investigation of the performance difference between the emacs apps follows:

# Steps to Reproduce

Go through these steps for both emacs apps (download from https://emacsformacosx.com/ and also build out from https://bitbucket.org/mituharu/emacs-mac)

1. Use Spacemacs (no customizations) as configuration.
2. For both emacs apps, connect to a running Leiningen REPL instance.
3. Open a CIDER scratch buffer with `cider-scratch`
4. Paste the source for [`cljs.core`](https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/core.cljc) the buffer.
5. Try typing into the cljs definition of `fn` (inside the `let` bindings form between lines 280-281).  In my testing, I input a sentence of 72 characters.

# Results

Narrowed down the problematic code path and instrumented accordingly.

## Emacs For macOSX

```
Function Name                                       Call Count  Elapsed Time  Average Time
font-lock-fontify-keywords-region                   394         7.5384160000  0.0191330355
cider-project-connections-types                     398         4.8906280000  0.0122880100
cider-find-connection-buffer-for-project-directory  398         4.8736979999  0.0122454723
clojure-project-dir                                 398         4.1959179999  0.0105425075
clojure-project-root-path                           398         4.1945379999  0.0105390402
locate-dominating-file                              1592        4.1861679999  0.0026295025
```

## Mituharu

```
Function Name                                       Call Count  Elapsed Time  Average Time
font-lock-fontify-keywords-region                   493         2.2034449999  0.0044694624
cider-project-connections-types                     493         0.4709220000  0.0009552170
cider-find-connection-buffer-for-project-directory  493         0.4530600000  0.0009189858
clojure-project-dir                                 493         0.3064590000  0.0006216206
clojure-project-root-path                           493         0.3054970000  0.0006196693
locate-dominating-file                              1972        0.3000340000  0.0001521470
```

# Observation

The `cider-project-connections-types` function call (which is used by the reader conditional font-locking), is taking much longer in the emacsformacosx version of emacs.  Not sure what's causing this.

On that note, @bhauman, can you try doing the following?  First, reproduce the slowdown (enabling `cider-font-lock-reader-conditionals`).  Then try hard-coding the returned result of `cider-project-connections-types` with something like the following:

```clj
(defun cider-project-connections-types ()
  "Return a list of types of connections within current project."
  (list "clj"))
```

Then check if there's still any slowdown.  If there isn't, then I guess I can look into improving that code path so that the font-locking will avoid calling that function.

(It should be noted that I only managed to replicate this issue by using the Spacemacs contribution.  It doesn't seem to happen when I was using my own configuration.)

**Comment by alvinfrancis** [comment]
I meant that the Spacemacs config might have something to do with it, since the issue isn't noticeable in either Emacs builds if I'm not using the Spacemacs config.

Using my own config, here are the numbers:

## Emacs For macOSX

```
Function Name                                       Call Count  Elapsed Time  Average Time
font-lock-fontify-keywords-region                   73          0.678992      0.0093012602
cider-project-connections-types                     73          0.332306      0.0045521369
cider-find-connection-buffer-for-project-directory  73          0.3302130000  0.0045234657
clojure-project-dir                                 73          0.2657769999  0.0036407808
clojure-project-root-path                           73          0.2655669999  0.0036379041
locate-dominating-file                              292         0.2644110000  0.0009055171
```

## Mituharu

```
Function Name                                       Call Count  Elapsed Time  Average Time
font-lock-fontify-keywords-region                   73          0.5631920000  0.0077149589
cider-project-connections-types                     73          0.1498389999  0.0020525890
cider-find-connection-buffer-for-project-directory  73          0.1472240000  0.0020167671
clojure-project-dir                                 73          0.0491390000  0.0006731369
clojure-project-root-path                           73          0.0489199999  0.0006701369
locate-dominating-file                              292         0.0479910000  0.0001643527
```

What strikes me is that without using the Spacemacs config, the number of calls to `font-lock-fontify-keywords-region` is an expected 73 times (in my test: 72 characters input + 1 to add a new line).  Compared to the weird number of calls in the Spacemacs config tests.

**Comment by bhauman** [comment]
Just to be clear, I'm not using spacemacs

**Comment by alvinfrancis** [comment]
@bhauman How many times does `cider--search-reader-conditionals` show up in the value of `font-lock-keywords` for you?  It's repeated for some reason when I'm running the spacemacs config.  I wonder if it's the same for yours.

**Comment by bbatsov** [comment]
Btw, I've added a small patch to `clojure-mode`, so now results from `clojure-project-dir` are cached.
