### ISSUE TITLE
cemerick.piggieback -> cider.piggieback

### ISSUE THREAD

**Issue by fl00r** [clojure-emacs/cider#2283]
## Expected behavior

cljs repl should use cider.piggieback

## Actual behavior

it uses cemerick.piggieback

https://github.com/clojure-emacs/cider/blob/master/cider.el#L681

## Steps to reproduce the problem

Launching repl causes a following exception

```
ClassNotFoundException cemerick.piggieback  java.net.URLClassLoader.findClass (URLClassLoader.java:381)
```

### CIDER version information

```
;; CIDER 0.17.0snapshot (package: 20180430.444), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_144
```

### Lein/Boot version

Leiningen 2.7.1 on Java 1.8.0_144 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

*25.2.1*

### Operating system

*MacOS 10.13.3*

**Comment by bbatsov** [comment]
An oversight on my part! Thanks for pointing it out!

**Comment by fl00r** [comment]
:*

**Comment by vspinu** [comment]
Shouldn't cider-verify-piggieback-is-present check for cider.piggiback specifically? I just came back to clojure after half a year and found out that `cemerick.piggieback/wrap-cljs-repl` works no more. From the error it's easy to guess what happened, but still.

**Comment by bbatsov** [comment]
@vspinu Technically speaking it still works, but the default configuration refers to the newer piggieback for obvious reasons. @bhauman had the great idea to just inject piggieback automatically when doing `cider-jack-in-cljs`, which is a better solution to the problem you mentioned.
