### ISSUE TITLE
[Question] How do I start figwheel in projects where a predefined function exists to start figwheel up from the Clojure repl?

### ISSUE THREAD

**Issue by NightMachinary** [clojure-emacs/cider#2289]
E.g., in https://github.com/fulcrologic/fulcro-tutorial , there is a `(user/start-figwheel '[tutorial])` that should be called from the Clojure repl and it starts the figwheel repl. If I just do a Clojure jack-in and type this command in, I'll lose my Clojure repl. If I do a clojurescript jack-in, the default config is not run.

**Comment by bbatsov** [comment]
All you need to know is in this section http://cider.readthedocs.io/en/latest/clojurescript/#starting-a-clojurescript-repl
