### ISSUE TITLE
cider-stacktrace doesn't seem to honor cider-use-tooltips

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#2291]
Hi there!

I have `cider-use-tooltips` set to nil, but I still can see `"View source at this location"` tooltips.

Relevant code - https://github.com/clojure-emacs/cider/blob/ff3bfa2642cfcd4eb5f2756280ea057dc69f8aff/cider-stacktrace.el#L698

Thanks - Victor

**Comment by bbatsov** [comment]
I didn't even remember we had tooltips here. :-) The others were configurable mostly because they added some performance overhead, but I guess it makes sense for us to be consistent (or to name the config option differently).

**Comment by bbatsov** [comment]
Btw, you can also just disable `tooltip-mode` which would turn off tooltips everywhere in Emacs.
