### ISSUE TITLE
Make the `cider-cljs-repl-types` commands cleanly customizable?

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#2292]
The ` "(do (require 'figwheel-sidecar.repl-api) (figwheel-sidecar.repl-api/start-figwheel!) (figwheel-sidecar.repl-api/cljs-repl))"` commands in https://github.com/clojure-emacs/cider/blob/ff3bfa2642cfcd4eb5f2756280ea057dc69f8aff/cider.el#L687 isn't under a defcustom so it cannot be cleanly customized.

An use case would be e.g. customizing Fighwheel startup as I used to:

```
"(do (require 'figwheel-sidecar.repl-api)
               
               (try
                 (require 'figwheel-sidecar.system)
                 (alter-var-root #'figwheel-sidecar.system/repl-function-docs (constantly \"Results: Stored in vars *1, *2, *3, *e holds last exception object\"))
                 (catch Throwable e))
               (figwheel-sidecar.repl-api/start-figwheel!)
               (figwheel-sidecar.repl-api/cljs-repl))"
``` 

(the intent is to make the initial banner more concise)

Would it be welcome if we create one defcustom per command?

Thanks - Victor

**Comment by bbatsov** [comment]
What's wrong with the proposed way of extending the defaults with `cider-register-cljs-repl-type`?

The main var is not a defcustom, but it can certainly be one. I just assumed that given the fact ideally one has to also supply a validation function it's unlikely they'll be using customize. 

We can make all the default type strings defcustoms, but that might be a bit of an overkill.

**Comment by vemv** [comment]
> What's wrong with the proposed way of extending the defaults with cider-register-cljs-repl-type?
Sounds good! I just tried it out, almost works.

Let's say I do:

```
(cider-register-cljs-repl-type
 'figwheel
 "(do (require 'figwheel-sidecar.repl-api)               
               (try
                 (require 'figwheel-sidecar.system)
                 (alter-var-root #'figwheel-sidecar.system/repl-function-docs (constantly \"Results: Stored in vars *1, *2, *3, *e holds last exception object\"))
                 (catch Throwable e))
               (figwheel-sidecar.repl-api/start-figwheel!)
               (figwheel-sidecar.repl-api/cljs-repl))"
 'cider-check-figwheel-requirements)
```

Then, `cider-cljs-repl-types` will start having two items starting with `figwheel`, which seems buggy.

**Comment by bbatsov** [comment]
Ah, guess I didn't think of that. I just assumed people would use names like `figwheel-something` in such cases. We can certainly have older records be overridden.

**Comment by vemv** [comment]
Didn't think of that either!

Perhaps we can simply add the following to the `cider-cljs-repl-types` doc:

> If you want to customize the Clojure code to be evaluated by a given type, you can register a new one with cider-register-cljs-repl-type, using a different name.

That could kill the need for modifying any code - as you prefer.
