### ISSUE TITLE
Provide a better interface to set project-only filter for stacktrace mode

### ISSUE THREAD

**Issue by caioaao** [clojure-emacs/cider#2294]
Currently we can't use positive filters on `cider-stacktrace-default-filters`. Options like `project` doesn't work here.
Also the documentation on `cider-stacktrace-default-filters` could be improved. I had to look more than I expected for the acceptable values for the variable.

**Comment by bbatsov** [comment]
I guess @dpsutton can look into this at some point, as I won't be able to tackle this myself soon.
