### ISSUE TITLE
Update docs to indicate cider-jack-in support for Clojure CLI

### ISSUE THREAD

**Issue by cbowdon** [clojure-emacs/cider#2295]
I was (very pleasantly) suprised when `cider-jack-in` worked on a deps.edn project, since the current doc/up_and_running.md says that Lein, Boot or Gradle are required. Is clj support missing from the docs because it's incomplete? Otherwise would you like a PR for this?

**Comment by bbatsov** [comment]
It's not incomplete, I just forgot to document it. :D I wouldn't mind a PR if you want to work on this. The magic code is most here https://github.com/clojure-emacs/cider-nrepl/blob/b0649ac8bcf1faa686ce9954ed4879622fdf58c3/src/cider_nrepl/main.clj
