### ISSUE TITLE
tooltip-mode always ignored

### ISSUE THREAD

**Issue by weissjeffm** [clojure-emacs/cider#2297]
## Expected behavior

Hovering the mouse over function names in clojure buffers will display tooltips when `cider-use-tooltips` and `tooltip-mode` is on.

## Actual behavior

No tooltips

## Steps to reproduce the problem

```elisp
(tooltip-mode) (setq cider-use-tooltips t)
```
Jack in.

Hover over function names in clojure buffers 

### CIDER version information

;; CIDER 0.18.0snapshot (package: 20180514.427), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_171

### Lein/Boot version
Leiningen 2.8.1

### Emacs version
GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.4.0, NS appkit-1561.20 Version 10.13.3 (Build 17D47)) of 2018-05-18

### Operating system

OS X 10.13.3

## Diagnosis

The function `cider--help-echo` misunderstands the variable `help-at-pt-display-when-idle`. In the customize buffer, that variable can be "Never", "Always", "In certain situations". `nil` is not an option. But the `cider--help-echo` function checks `(not help-at-pt-display-when-idle)` to see if help at point is enabled (because it doesn't want to do mouse-based and point-based at the same time, which makes sense. 

Adding `(setq help-at-pt-display-when-idle nil)` to my config works around this issue.

The fix should probably check to see if the value is "never" or `nil`.

**Comment by yuhan0** [comment]
Fixed by #3186
