### ISSUE TITLE
Make cider-doc and cider-javadoc smarter

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#2301]
Based on this guide https://clojure.org/guides/repl/data_visualization_at_the_repl#_dealing_with_mysterious_values_advanced described.
Current `cider-doc` and `cider-javadoc` does not show more info about `v`. I hope CIDER can be smart on this. do this automatically for user.
Is this possible to be implemented in CIDER?

**Comment by bbatsov** [comment]
Anything is doable, but I'm not certain what exactly is the expectation here - after all this article points out several different things.

**Comment by stardiviner** [comment]
Currently CIDER run `cider-doc` on `v` will get:
```
user/v
  Not documented.

user/v is defined in *cider-repl ob-clojure*.
```
If I run `cider-javadoc` on `v` will get: `user-error: No Javadoc available for v`.

In upper link described, it can use `(type v)` to get **javadoc** with `clojure.java.javadoc/javadoc`. Maybe show additional info with `clojure.reflect/reflect` is better.

**Comment by stardiviner** [comment]
Hmm, after a reconsidering, I think this might conflict with variable docstring.
Close this feature propose now.
