### ISSUE TITLE
Add insert eval and next to cider

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#2302]
In `inf-clojure` I usually like to use the function that inserts the last form to the REPL, evaluates it and then proceeds to the end of the next form.

I was wondering whether we could add it to `cider` as well.

**Comment by bbatsov** [comment]
Can you demonstrate this with a gif or something? I'm not sure I completely understand what you mean. I recall `inf-clojure` what a function to insert and eval something into the REPL, but nothing like what you describe.

**Comment by arichiardi** [comment]
I surely can tomorrow, in the meantime here is the code that does that: https://github.com/clojure-emacs/inf-clojure/blob/master/inf-clojure.el#L688

**Comment by bbatsov** [comment]
Aha, I see what you mean. I don't quite get why would you need it, though, that's why I asked for the usage sample. Most subsequent sexps would not be something you can eval by themselves, this makes sense mostly for top-level forms, especially some ordered in a particular fashion.

**Comment by arichiardi** [comment]
Yes you are completely right that the flow is very top-down and basically I could use a load file + navigating between top level forms.

However, given Clojure's reading order, it always makes sense to evaluate top down, especially whenever you are done messing with function internals and you want to test multiple `defn` together.

I still owe you a gift though.

**Comment by bbatsov** [comment]
> However, given Clojure's reading order, it always makes sense to evaluate top down, especially whenever you are done messing with function internals and you want to test multiple defn together.

Don't people typically just eval the whole namespace at this point?

**Comment by arichiardi** [comment]
Yep but it seems that this is still a useful thing to have? I haven't seen others pitching in so maybe it is just useful for me :smile:

**Comment by vspinu** [comment]
I am using such commands extensively (`eval-region-defun-or-paragraph-and-step`, `eval-outer-sexp-and-step`). Essentially an adaptation  of the tools in ESS (`ess-eval-region-or-function-or-paragraph-and-step` and `ess-eval-line-and-step`). 4 commands is all I need for "localized" evaluation:

```el
  (define-key cider-mode-map (kbd "C-M-x") 'my-cider-eval-region-or-defun-or-paragraph)
  (define-key cider-mode-map (kbd "C-c C-c") 'my-cider-eval-region-or-defun-or-paragraph-and-step)
  (define-key cider-mode-map (kbd "C-j")   'my-cider-eval-outer-sexp-and-step)
  (define-key cider-mode-map (kbd "C-M-j") 'my-cider-eval-outer-sexp)
```

[`python-x`](https://github.com/wavexx/python-x.el/blob/master/python-x.el#L323-L387) has similar functionality plus the ability to send delimited (`# ---`) sections.  

BTW, having both `C-c C-c` and `C-M-x` allocated for same command seems wasteful. C-c C-c could be stepping by default.

**Comment by bbatsov** [comment]
> BTW, having both C-c C-c and C-M-x allocated for same command seems wasteful. C-c C-c could be stepping by default.

It's our SLIME legacy. :-) Many people are attached to `C-c C-c`, so I don't think it's feasible to change this. But we do have a dedicated eval map, so we can have the other command reside there.

One of the things I find confusing about @arichiardi's request is that we wants this only for the insert to repl behaviour, although I feel it might be just as useful for regular eval (as pointed out by @vspinu).

**Comment by bbatsov** [comment]
> python-x has similar functionality plus the ability to send delimited (# ---) sections.

That's an interesting idea, btw.

**Comment by arichiardi** [comment]
@bbatsov my request was not only for inserts but I gathered from the comment in the issue I opened that it would be too much change in eval and therefore only applied in @dpsutton's code.
