### ISSUE TITLE
cider completion broken

### ISSUE THREAD

**Issue by achikin** [clojure-emacs/cider#2303]
## Expected behavior
Cider completion and jump-to-definition work

## Actual behavior
Cider completion and jump-to-definition does not work in both clj and cljs repls

## Steps to reproduce the problem
1. `cider-jack-in-clojurescript`
2. Navigate to any clojure or clojurescript namespace and try to go to definition or toggle autocomplete
Go to definition shows `No jump handler was able to find this symbol`
Autocompletion simply does not pop up or shows irrelevant data.
Cljs repl looks like this (mention `REPL[clj]`)

![screen shot 2018-05-30 at 15 49 06](https://user-images.githubusercontent.com/611419/40721047-103d3752-6421-11e8-88c9-d586b162ebcd.png)

### CIDER version information
```
CIDER 0.18.0-snapshot, nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_20
```

### Lein/Boot version
Leiningen 2.8.1 on Java 1.8.0_20 Java HotSpot(TM) 64-Bit Server VM

### Emacs version
GNU Emacs 26.1

### Operating system
![screen shot 2018-05-30 at 15 52 47](https://user-images.githubusercontent.com/611419/40721238-9b196620-6421-11e8-8d3e-62d4ae0fe0ce.png)

### A little bit of grumbling
Starting this year Cider breaks for me on every update. I file issue every time when I update packages and then spend 2-3 hours trying to get Cider back to normal. Usually it means disabling new buggy features and rewriting configs that were totally fine on previous version. Those updates does not add anything to my daily routines with cider, but tend to break functionality, that was totally fine before.

<img width="720" alt="screen shot 2018-05-30 at 16 08 34" src="https://user-images.githubusercontent.com/611419/40721996-c914e5de-6423-11e8-83ed-603831c13247.png">

I use Cider on daily basis to do my primary job and though I expect Cider to work the same way it was working yesterday.

This becomes really, really annoying.

Could you please be more careful, especially with moving/refactoring things that just work?

**Comment by achikin** [comment]
https://github.com/syl20bnr/spacemacs/issues/10774

**Comment by expez** [comment]
Closing as a bug in spacemacs.

@achikin I recommend you stop running snapshots.  The snapshots are pre-release builds and are expected to have some breakage.  `SNAPSHOT` doesn't mean the same as e.g. the `LATEST` tag in Maven, which give you the latest stable release.

Anyway, sorry for you recent issues and thank you for helping test CIDER and for taking the time to report bugs.  If nobody ran and tested the snapshots we would have significantly more bugs in the proper releases.

**Comment by achikin** [comment]
I'm sorry, I didn't realize that I use snapshots. I simply hit `Update packages` button on Spacemac's main screen. Didn't pay attention to the kind of builds it downloads. My bad.
![screen shot 2018-05-31 at 13 08 54](https://user-images.githubusercontent.com/611419/40776555-be0a2f18-64d3-11e8-9d63-752f5b120086.png)

As for the repl type - it starts normally as REPL[cljs] and then becomes REPL[clj] at some point.

Anyway you're right - there are some issues with Spacemacs + Emacs 26.1

**Comment by achikin** [comment]
As as a result of discussion in this ticket https://github.com/syl20bnr/spacemacs/issues/10777
I've switched to develop branch of Spacemacs and all the issues are gone.

**Comment by achikin** [comment]
This happened again
- Clojurescript repl has type `REPL[clj]`
- Go to definition uses `dumb jump` instead of cider
