### ISSUE TITLE
Cider classpath does not consider clojure git libs

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#2308]
## Expected behavior
The `(cider-classpath-libs)` function call should include `clojure/clojurescript`.

## Actual behavior
This does not happen if `org.clojure/clojurescript` is added as git deps in a `deps.edn` file.

## Steps to reproduce the problem
Add this to your `deps.edn` and try to jack-in ClojureScript.

```clojure
:deps {
  org.clojure/clojurescript {:git/url "https://github.com/clojure/clojurescript"
                                                  :sha "2ad14709f390e4427b30a8ec86eeb05872e5e52c"}}           
```

You will receive a ` ClojureScript is not available.  See ...` error.

This is because [here](https://github.com/arichiardi/cider/blob/master/cider-client.el#L820) we filter by extension and probably this is not what git deps add to the classpath? Haven't explored further.

### CIDER version information

`0.18.0-snapshot`

**Comment by bbatsov** [comment]
Yeah, you're right. Not sure how exactly to handle this - never used git deps myself, so it didn't even cross my mind. I wonder if there's some smarter way to get insight about the available libs than parsing the classpath...

**Comment by bbatsov** [comment]
> This is because here we filter by extension and probably this is not what git deps add to the classpath? Haven't explored further.

Please, take a look at that extensions when you have some time, as I don't use tools.deps anywhere.

**Comment by kommen** [comment]
These 3 directories are added to the classpath with ClojureScript as a git dependency:

```
"/Users/kommen/.gitlibs/libs/org.clojure/clojurescript/687caa946f27e35880a45bb7ac8894e4d066be29/src/main/clojure" 
"/Users/kommen/.gitlibs/libs/org.clojure/clojurescript/687caa946f27e35880a45bb7ac8894e4d066be29/src/main/cljs" 
"/Users/kommen/.gitlibs/libs/org.clojure/clojurescript/687caa946f27e35880a45bb7ac8894e4d066be29/resources"
```

So I guess there is no single extension we could filter by.

**Comment by kommen** [comment]
@arichiardi as #2440 is fixed now, you should be able to set ` cider-check-cljs-repl-requirements` so work around this limitation and avoid the `ClojureScript is not available` error.

**Comment by kommen** [comment]
For future reference, the limitation in cider is here: https://github.com/clojure-emacs/cider/blob/c1a38bb56df38a5a736fa4a1f2f5c65d9fb02202/cider-client.el#L270-L293

I tried to have a brief take on this, but I'm not sure what assumptions we can make about the directory layout. Should we just consider the two dirs after `/.gitlibs/libs/` as the group-id and artifact-id?

**Comment by arichiardi** [comment]
Oh nice thanks for the heads-up and I think the structure can be double checked with Alex on clojurians maybe. I think it is safe to assume what you said.

**Comment by bbatsov** [comment]
@kommen Yeah, this has to be fixed. I just ran out of time for it and forgot it after a while. Probably my approach for this was fundamentally flawed and the checks can be implemented in a much simpler fashion.

**Comment by kommen** [comment]
Thinking more about this, I recognized that with tools.deps users can also use local libs using `:local/root` coordinates, in which case there probably will be no way to infer the provided libs from classpath entries.

E.g in a deps.edn
```clojure 
{:deps
  {org.clojure/clojurescript {:local/root "/Users/kommen/work/clojurescript"}}
```

Will result in these cp entries:
```
/Users/kommen/work/clojurescript/src/main/clojure
/Users/kommen/work/clojurescript/src/main/cljs
/Users/kommen/work/clojurescript/resources
```

**Comment by arichiardi** [comment]
Uhm right...maybe we should start thinking in terms of just using the results coming from a binary with no filtering on extensions and stuff? Dunno just throwing idea out there.

**Comment by bbatsov** [comment]
Well, if no one has good suggestions I guess we can just kill this functionality altogether. Originally I added this as I wanted to warn users on common problems like missing deps, problematic deps, etc, but if we can't get this working reliably we're probably better off without it.

**Comment by puredanger** [comment]
We do have some thoughts on better ways for clj to pass info into the jvm about the libs its using. This is kind of [buried](https://github.com/clojure/tools.deps.alpha/blob/add-lib/src/main/clojure/clojure/tools/deps/alpha/libmap.clj) in the add-lib branch at the moment, but the idea is to have well-known system properties that can be used to either pass an edn lib map or a pointer to a lib file defining the libraries that were used to build the classpath. There is a possibility this could move into clojure core and would then be generically available.

**Comment by vspinu** [comment]
>  I guess we can just kill this functionality altogether. 

Dependency information is needed for sesman friendly sessions (#2483) in order to send evals in the right repl. So unless someone comes with better dep-maps, classpath seems to be the only option ATM..

**Comment by kommen** [comment]
> Dependency information is needed for sesman friendly sessions (#2483)

@vspinu it looks to me like the PR #2483 only uses the classpath itself, not the problematic function `cider-classpath-libs` at issue here. So even if we removed `cider-classpath-libs` and the corresponding `cider-library-present-p`, sesman friendly session should be fine, I think.

**Comment by vspinu** [comment]
I see. If "removal" doesn't mean the removal of the classpath middleware then everything is fine indeed.

**Comment by bbatsov** [comment]
Yeah, totally.

When I said we should remove something I was suggesting my poor attempt to check for the presence of certain libs using the classpath info. I guess this should be checked to see if some key namespaces in them can be resolved or something along those lines. E.g. we can check for `cljs.core`, `cider.piggieback`, etc.
