### ISSUE TITLE
Having trouble running `make test` in cider

### ISSUE THREAD

**Issue by zcaudate** [clojure-emacs/cider#2309]
I'm having problems running `make test`. An error occurs when I pull from the repo and run:

     Package ‘s-’ is unavailable 

## Actual behavior
>  make test

```
emacs --version
GNU Emacs 25.3.1
Copyright (C) 2017 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
cask install
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: melpa.org:443
Failed to download ‘melpa’ archive.
Contacting host: elpa.gnu.org:443
Package refresh done
Failed to download ‘gnu’ archive.
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Package ‘s-’ is unavailable
make: *** [elpa-emacs] Error 255

```

### Emacs version

25.3.1
 
### Operating system

OSX 10.13.3

**Comment by bbatsov** [comment]
That's definitely not CIDER-related. I've seen all sorts of "random" issues with package repos - often because of some SSL configuration issues. Does this work if you use `http` instead of `https` for the package repos?

**Comment by zcaudate** [comment]
I got it working on another computer but it'd still be good to figure out why it's not working how do I use http?

**Comment by dpsutton** [comment]
I've run into issues with running tests before but running 'cask install'
solved it for me. I'm not sure if that is your problem but it's worth a try

**Comment by zcaudate** [comment]
`cask install` outputs the same error

**Comment by bbatsov** [comment]
This might be useful https://blog.vifortech.com/posts/emacs-tls-fix/

Basically changing the url of package repos in your config might help, although obviously it's not advisable.

**Comment by zcaudate** [comment]
I'm still not sure what the issue is but it's working on linux so I'll just go with that for now.

**Comment by johngit22** [comment]
Keep me posted
