### ISSUE TITLE
cider-jack-in  (wrong-type-argument queue [cl-struct-queue nil nil])

### ISSUE THREAD

**Issue by boxxxie** [clojure-emacs/cider#2315]
*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable CIDER and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

*When requesting new features or improvements to existing features you can
discard the template completely. Just make sure to make a good case for your
request.*

**Remove all of the placeholder text in your final report!**

## Expected behavior
jack-in-repl started in project

## Actual behavior
Error
```
Debugger entered--Lisp error: (wrong-type-argument queue [cl-struct-queue nil nil])
  signal(wrong-type-argument (queue [cl-struct-queue nil nil]))
  queue-enqueue([cl-struct-queue nil nil] "d2:id1:111:new-session36:eeb4681b-6ed2-4f7b-918b-4fbc2ddec8c07:session36:c4304a90-d2e8-4b79-8ae4-d3c0ca8132a26:statusl4:doneee")
  nrepl-client-filter(#<process nrepl-connection<1>> "d2:id1:111:new-session36:eeb4681b-6ed2-4f7b-918b-4fbc2ddec8c07:session36:c4304a90-d2e8-4b79-8ae4-d3c0ca8132a26:statusl4:doneee")
  accept-process-output(nil 0.01)
  nrepl-send-sync-request(("op" "clone" "id" "1" "time-stamp" "2018-06-08 14:22:50.820488949") #<buffer *cider-repl financial_planning*<2>> nil nil)
  nrepl-sync-request:clone(#<buffer *cider-repl financial_planning*<2>>)
  nrepl--init-client-sessions(#<process nrepl-connection<1>>)
  nrepl-start-client-process(nil 41951 #<process nrepl-server<1>>)
  nrepl-server-filter(#<process nrepl-server<1>> "nREPL server started on port 41951 on host :: - nrepl://:::41951\n")

```
## Steps to reproduce the problem
go to clojure project file (any .clj) use command `cider-jack-in`

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### CIDER version information
cider-20180608.352

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*
no string is displayed

### Lein/Boot version
Leiningen 2.8.1 on Java 9.0.4 OpenJDK 64-Bit Server VM

### Emacs version
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-29

### Operating system
Arch (Manjaro)

**Comment by dpsutton** [comment]
This is a change in emacs bytecode (I believe). The error wounds weird because it was expecting a cl-struct-queue and instead it got a cl-struct-queue. This results from a change in how these are represented in the bytecode. Remove the .elc files in your cider directory and this should go away.

**Comment by boxxxie** [comment]
ok, i'll try that.
i ran the recompilation process, but maybe it has some unintuative behaviour

**Comment by boxxxie** [comment]
awesome, works!
thanks a lot.

**Comment by patrickaroo** [comment]
You may need to recompile files if you have a new major version of Emacs. To do so, follow the top voted answer at https://stackoverflow.com/questions/24725778/how-to-rebuild-elpa-packages-after-upgrade-of-emacs/24735377#24735377 .

**Comment by Bost** [comment]
> This is a change in emacs bytecode (I believe).

I run into this issue after https://github.com/clojure-emacs/clj-refactor.el/issues/369#issuecomment-388326195 so yes it's the bytecode and the workaround is `M-x byte-force-recompile` of your cider package directory followed by `M-x restart-emacs`.
