### ISSUE TITLE
No Company documentation with Cider

### ISSUE THREAD

**Issue by NightMachinary** [clojure-emacs/cider#2318]
Description :octocat:
Cider's documentation is working (, h h) but pressing C-h on Company's completion candidates produces No documentation available. 

The issue might be with Spacemacs: https://github.com/syl20bnr/spacemacs/issues/10854
Or Company-mode. Or whatever. I have no idea.

System Info 💻
OS: darwin
Emacs: 27.0.50
Spacemacs: 0.300.0
Spacemacs branch: added-dvorak-right-handed-to-keyboard-layout-layer (rev. 5c575adfb)
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm
Layers:
(asciidoc yaml fsharp windows-scripts javascript epub xkcd spotify twitter search-engine vimscript
          (elfeed :variables rmh-elfeed-org-files
                  (list "~/.emacs.d/private/feeds/elfeed1.org"))
          (rust :variables rust-format-on-save t)
          (haskell :variables haskell-enable-hindent t)
          semantic lsp
          (c-c++ :variables c-c++-enable-clang-support t)
          html
          (python :variables python-backend 'anaconda)
          chrome
          (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
          (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
          autohotkey kotlin helm
          (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
          emacs-lisp
          (ibuffer :variables ibuffer-group-buffers-by 'modes)
          coq emoji
          (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
          git markdown org
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          spell-checking
          (syntax-checking :variables syntax-checking-enable-tooltips t)
          (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
          version-control osx scheme
          (clojure :variables clojure-enable-fancify-symbols t))
System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.18.0snapshot (package: 20180608.352), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_152
```

### Lein/Boot version
`Leiningen 2.8.1 on Java 1.8.0_152 OpenJDK 64-Bit Server VM`

### Emacs version

27.0.50

### Operating system

macOS

**Comment by bbatsov** [comment]
Just tested it and it works for me. Have you evaluated the buffer in which you tried this with `C-c C-k` beforehand?

**Comment by kommen** [comment]
Just tried here with Spacemacs (current develop branch) and also can't reproduce this.

CIDER 0.18.1snapshot (package: 20181008.1547)
GNU Emacs 26.1 (build 1, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G1314)) of 2018-05-28
