### ISSUE TITLE
cider--restart-connection doesn't work properly when invoked outside the project dir

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2320]
## Expected behavior

`cider-restart` will restart properly all connections created by `cider-jack-in` regardless of the directory in which you've invoked the command.

## Actual behavior

It tries to start all connections in your current directory.

## Steps to reproduce the problem

1. `cider-jack-in` in some project
2. Go to some directory with no Clojure projects, open a file a there and invoke `cider-restart`
3. CIDER will restart the project in the wrong directory

Seems the problem is that the `let` binding for `default-directory` in `cider--restart-connection` is not working as expected, although I have no idea idea why. 

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.12.0snapshot (package: 20180608.352), nREPL 0.2.13
;; Clojure 1.8.0, Java 1.8.0_31
```

**Comment by vspinu** [comment]
With the new API this appears to be fixed. 

Start in one project -> move to another project -> link with `C-c C-s b/d/p` -> restart (`cider-restart` or `C-c C-s C-r` (for `sesman-restart`)) -> `C-c M-d` or `C-c C-s i` (for `sesman-info`).
