### ISSUE TITLE
CompilerException while trying to use company complete at point

### ISSUE THREAD

**Issue by dpetranek** [clojure-emacs/cider#2325]
## Expected behavior
Company displays a list of completion candidates

## Actual behavior
Company fails with this message:
> Company: backend company-capf error "Symbol’s function definition is void: CompilerException" with args (candidates def)

Here's the stacktrace from `toggle-debug-on-error`:
> Debugger entered--Lisp error: (void-function CompilerException)
> CompilerException("def" nil t)
> all-completions("def" CompilerException nil)
> completion-pcm--all-completions("" ("def" point) CompilerException nil)
> completion-basic-all-completions("def" CompilerException nil 3)
> #257 "\300�
> \2368\301\242\302\242\303\304\242$\207" [2 ("def") (CompilerException) nil (3) completion-styles-alist] 6 "\n\n(fn STYLE)"
> completion--some(#[257 "\300�
> \2368\301\242\302\242\303\304\242$\207" [2 ("def") (CompilerException) nil (3) completion-styles-alist] 6 "\n\n(fn STYLE)"] (basic partial-completion emacs22))
> completion--nth-completion(2 "def" CompilerException nil 3 nil)
> completion-all-completions("def" CompilerException nil 3)
> company-capf(candidates "def")
> apply(company-capf (candidates "def"))
> company-call-backend-raw(candidates "def")
> company--fetch-candidates("def")
> company-calculate-candidates("def")
> company--begin-new()
> company--perform()
> company-auto-begin()
> company-idle-begin(# #<window 12 on test.clj> 1662 34973)
> apply(company-idle-begin (# #<window 12 on test.clj> 1662 34973))
> timer-event-handler([t 23330 32543 238085 nil company-idle-begin (# #<window 12 on test.clj> 1662 34973) nil 685000])

## Steps to reproduce the problem
1. M-x cider-jack-in
2. Type three characters to trigger completion-at-point ("def" in this example)

## Environment & Version information
Company version: 0.9.6

### CIDER version information
;; Connected to nREPL server - nrepl://localhost:37447
;; CIDER 0.17.0 (Andalucía), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_172

### Lein/Boot version
Leiningen 2.8.1 on Java 1.8.0_172 OpenJDK 64-Bit Server VM

### Emacs version
GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.28) of 2018-04-10

### Operating system
NixOS 18.03

**Comment by bbatsov** [comment]
That works for me. Perhaps @dgutov has some idea what might be causing it.

**Comment by dgutov** [comment]
Allow me to ask a trick question: does pressing `C-M-i` result in a similar error?

**Comment by dpetranek** [comment]
Yes it does!

> Debugger entered--Lisp error: (void-function CompilerException)
>   CompilerException("" nil t)
>   all-completions("" CompilerException nil)
>   completion-pcm--all-completions("" (point) CompilerException nil)
>   completion-basic-all-completions("" CompilerException nil 0)
>   #[257 "\300
> \2368\301\242\302\242\303\304\242$\207" [2 ("") (CompilerException) nil (0) completion-styles-alist] 6 "\n\n(fn STYLE)"](basic)
>   completion--some(#[257 "\300
> \2368\301\242\302\242\303\304\242$\207" [2 ("") (CompilerException) nil (0) completion-styles-alist] 6 "\n\n(fn STYLE)"] (basic partial-completion emacs22))
>   completion--nth-completion(2 "" CompilerException nil 0 nil)
>   completion-all-completions("" CompilerException nil 0)
>   ivy-completion-in-region(#<marker at 39039 in test.clj> 39039 CompilerException nil)
>   completion-in-region(#<marker at 39039 in test.clj> 39039 CompilerException nil)
>   completion-at-point()
>   complete-symbol(nil)
>   funcall-interactively(complete-symbol nil)
>   call-interactively(complete-symbol nil nil)
>   command-execute(complete-symbol)

**Comment by dgutov** [comment]
First of all, that means it's *not my problem*. :-) Yippie.

Second, this looks suspicious: `ivy-completion-in-region`. Might be Ivy mucking something up.

**Comment by bbatsov** [comment]
Yeah, might be something to do with `ivy` indeed. Try if things work properly without it. At any rate - this certainly is not a CIDER issue.
