### ISSUE TITLE
define cider-eval-last-sexp-at-point

### ISSUE THREAD

**Issue by zcaudate** [clojure-emacs/cider#2328]
I'm hoping to have a functionality to be used for evaluating `->` and `->>` macros where:

--------

given the form:

```
(-> (+ 1 1)
    (+ 1)
    (+ 1)
    (+ 1))
```

it is possible to have evalution at subsequent steps, ie:

```
(-> (+ 1 1)| ; => 2
    (+ 1)
    (+ 1)
    (+ 1))
```
```
(-> (+ 1 1)
    (+ 1)| ;=> 3
    (+ 1)
    (+ 1))
```
```
(-> (+ 1 1)
    (+ 1)
    (+ 1)| ;=> 4
    (+ 1))
```
```
(-> (+ 1 1)
    (+ 1)
    (+ 1)
    (+ 1)|) ;=> 5
```
-------------------

The interaction would be to `move` the parenthesis forward to the point of the cursor, evaluate and then move the parenthesis back to the original position.

I tried but was a bit stuck. It'd be super useful for me if someone can implement it.

**Comment by bbatsov** [comment]
Funny enough something like this already exists. See https://github.com/clojure-emacs/cider/commit/2db31b0069caf4331100207948ca2bcbbf217dc5

What I've implemented works only for top-level forms, but obviously we can use the same approach for inner forms as well.

**Comment by zcaudate** [comment]
Oh that's awesome. Let me have a play with it.

**Comment by zcaudate** [comment]
is this the function?

```
(defun cider-read-and-eval-defun-at-point ()
  "Insert the toplevel form at point in the minibuffer and output its result.
The point is placed next to the function name in the minibuffer to allow
passing arguments."
  (interactive)
  (let* ((fn-name (cadr (split-string (cider-defun-at-point))))
         (form (format "(%s)" fn-name)))
    (cider-read-and-eval (cons form (length form)))))
```

So is it possible to change the behaviour by replacing `cider-defun-at-point` with something like `cider-current-form`?

**Comment by bbatsov** [comment]
No, the function is `cider-eval-defun-to-point`. Seems you want to create a variant of it - `cider-eval-sexp-to-point`.

**Comment by zcaudate** [comment]
I have this function, and it works

```
(defun cider-eval-sexp-to-point ()
  (interactive)
  (let* ((begin (save-excursion (up-list) (backward-list) (point)))
         (code  (buffer-substring-no-properties begin (point)))
         (code  (concat code '(41))))
    (cider-interactive-eval code)))
```

However, when I'm trying out of interactive mode, I'm getting:

<img width="816" alt="screen shot 2018-06-19 at 10 47 55 am" src="https://user-images.githubusercontent.com/1455572/41573263-703694a4-73ae-11e8-847e-c1f3d880011c.png">

is there a way to add a `;;` before the string to comment out the result before printing?
