### ISSUE TITLE
Switching ns is broken

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2330]
Doing something like `C-u C-c C-z` results in `No clj REPLs found. Have you linked a session?`. 

//cc @vspinu

**Comment by vspinu** [comment]
Works for me. You cannot just switch to arbitrary repls anymore. Switching (and all other operations) work with  linked session only. This might look restrictive at a first glance but it's a good thing. One might have 10 open projects and happily work on those without interfering with each other.

**Comment by bbatsov** [comment]
Switching to a REPL works, I get this error when I try to set the ns (with only a single repl running).
