### ISSUE TITLE
C-c M-s is bound to both `cider-selector` and `cider-connect-sibling-clj`

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider#2337]
When I introduced `C-c M-s/S` for siblings I thought that those are perfect keys because they mirror `M-j/J` and `M-c/C` combinations.  Today I discovered that  `C-c M-s` is actually bound to `cider-selector`. 

What shall we do with this?  Can we rebind the selector to `C-c M-l` ?

**Comment by bbatsov** [comment]
We've had this binding since the very beginning (and SLIME has it as well), so I'd rather not change it. 

Generally I don't like the term `sibling` that much, so maybe we can solve this by coming up with a different word there.

**Comment by xiongtx** [comment]
I think it should be fine to change. CIDER is derived from SLIME but is different enough that we should feel no obligation to maintain SLIME bindings. Keeping bindings mnemonic is more important.

**Comment by vspinu** [comment]
To me `sibling` is quite suggestive - they are all "children" of the same server. [Synonyms](http://www.thesaurus.com/browse/sibling) don't leave much hope. `brother-repl` is sexist, less intuitive but can grab the available `C-c M-b`.  

I don't think people use the selector much.  Such dispatchers are outside of cider's scope, if only because it should work globally not only in cider modes. Even within cider it works in  `cider-mode` and in the repl. So you jump to nrepl-messages, or server buffer and there ... boom, no selector.  

The name can also be better -  for instance a more specific `cider-buffer-selector` with a mnemonic `C-c M-b` binding. So, I would vote for renaming and moving on C-c M-b, or leaving unbound.

**Comment by bbatsov** [comment]
Well, I for one am extremely used to them, and I assume I'm not the only one. It's debatable whether `s` really corresponds that well to something named `connect-sibling`. Btw, can't we just fold the `connect-sibling` under `cider-connect` with a prefix argument? 

Or perhaps it's time for us to just group all the jack-in keys under some common keymap? What started as two keybindings is now 6 and probably there will be more to come.

**Comment by bbatsov** [comment]
> The name can also be better - for instance a more specific cider-buffer-selector with a mnemonic C-c M-b binding. So, I would vote for renaming and moving on C-c M-b, or leaving unbound.

Yeah, the name is definitely less than ideal. It's another copy from SLIME. I can live with such an approach.

**Comment by vspinu** [comment]
> Btw, can't we just fold the connect-sibling under cider-connect

Not easily. Prefix to `cider-connect-sibling-cljs` should itself ask for connection parameters (engine/runtime type). I expect that sibling command will be much more useful for cljs context. 

The fundamental difference between connect and connect-sibling is that the first one creates a new session, and the second doesn't. Merging all under one command would blur the distinction.

**Comment by bbatsov** [comment]
Probably we should make this more explicit in the docs and in messages displayed here and there. I'm assuming at least in the beginning the new session concept will be a bit confusing to the users.
