### ISSUE TITLE
cider-connect throws eval error: wrong type lisp "/path/to/my/project"

### ISSUE THREAD

**Issue by cbowdon** [clojure-emacs/cider#2358]
## Expected behavior
`M-x cider-connect` should connect to a running nrepl and open a buffer

## Actual behavior
`*** Eval error ***  Wrong type argument: listp, "/home/me/my/project"`

## Steps to reproduce the problem
- Start an nrepl (I have a particularly slow project so I do `cider-jack-in`, it times out and I just `cider-connect` manually).
- Connect with `M-x cider-connect`
- Error thrown, no buffer shown

### CIDER version information
```
;; CIDER 0.18.0snapshot (package: 20180628.628), nREPL 0.2.13
;; Clojure 1.9.0-alpha19, Java 1.8.0_171
```

N.B. CIDER 0.17.0 doesn't throw the error

### Lein/Boot version
Boot 2.7.2

### Emacs version
Emacs 26.1

### Operating system
openSUSE Tumbleweed KDE

## Fix/workaround
I debugged this down to `sesman.el` and fixed it with the following patch:

```
--- a/sesman.el
+++ b/sesman.el
@@ -729,9 +729,9 @@ buffers."
 (cl-defmethod sesman-relevant-context-p ((_cxt-type (eql project)) proj)
   "Non-nil if PROJ is the parent or equals the `default-directory'."
   (when (and proj default-directory)
-    (string-match-p (concat "^" (cdr proj))
-                    (expand-file-name default-directory))))
-
+    (let ((p (if (listp proj) (cdr proj) proj)))
+      (string-match-p (concat "^" p)
+                      (expand-file-name default-directory)))))
```

I have no idea if this is a good long-term fix and haven't run tests or anything, so no PR sorry. But hopefully this will help resolve the issue.

**Comment by bandresen** [comment]
This was fixed in clojure-mode in this commit: https://github.com/clojure-emacs/clojure-mode/commit/e0f1adba280dd8da0c6e4f5ab5fb234738a9005e

**Comment by cbowdon** [comment]
Perfect, thanks!
