### ISSUE TITLE
clojure-current-project: Lisp nesting exceeds ‘max-lisp-eval-depth’

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/cider#2361]
## Expected behavior
Correctly jack-in after a <kbd>C-c M-j</kbd>

## Actual behavior
This message appears: 
```
clojure-current-project: Lisp nesting exceeds ‘max-lisp-eval-depth’
```
And CIDER cannot connect.

## Steps to reproduce the problem

- create a new Clojure project
- <kbd>C-c M-j</kbd>

### CIDER version information

```
CIDER 0.18.0snapshot (package: 20180628.628)
```

### Lein/Boot version
```
Leiningen 2.8.1 on Java 1.8.0_171 OpenJDK 64-Bit Server VM
```

### System details
```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2018-06-29

Repository revision: 591bb3d90018ebbcf79e6d496ed73ef396a58887
Configured using:
--host=x86_64-debian-linux-gnu --with-modules

Emacs uptime: 5 minutes, 0 seconds
Colour theme: sanityinc-tomorrow-night
Operating system: Ubuntu 18.04 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.1
```

**Comment by anmonteiro** [comment]
also having this

**Comment by mdallastella** [comment]
I can confirm the issue with the latest MELPA version of `clojure-mode`.

**Comment by rhow93** [comment]
getting this also with CIDER `20180628.628` on emacs 26.1 for any jack-in command

**Comment by bbatsov** [comment]
I made a silly mistake in `clojure-mode`. I've pushed an updated version just now. Sorry about that!

P.S. I learned once again there's a limit to how many things I can do at the same time! :D
