### ISSUE TITLE
cider-inspect-last-expr giving char-or-string-p

### ISSUE THREAD

**Issue by ackerleytng** [clojure-emacs/cider#2368]
## Expected behavior

The nice inspector window

## Actual behavior

```
helm-M-x: Wrong type argument: char-or-string-p, ("Class" ": " ("value" "java.lang.String" 0) ("newline") "Value: " "\"2\"")
```
## Steps to reproduce the problem

I dug into cider a little bit, and I think it could be fixed by changing this function to extract the right value from `nrepl-dict`, except I'm lacking some context and hope to get some help here.

```
(defun cider-sync-request:inspect-expr (expr ns page-size)
  "Evaluate EXPR in context of NS and inspect its result.
Set the page size in paginated view to PAGE-SIZE."
  (thread-first (append (nrepl--eval-request expr ns)
                        `("inspect" "true"
                          "page-size" ,page-size))
    (cider-nrepl-send-sync-request)
    (nrepl-dict-get "value")))
```

I think the issue is that the value for key `"value"` is not a string, as expected by the inspect function.

Executing

```
(nrepl-dict-get (cider-nrepl-send-sync-request
  (append (nrepl--eval-request "(+ 1 1)\n" "user")
          '("inspect" "true" "page-size" 32)) (nth 8 (buffer-list))) "value")
```
gets me

```
("Class" ": " ("value" "java.lang.String" 0) ("newline") "Value: " "\"2\"")
```

The `nrepl-dict` I see is

```
(dict "status" ("done") "id" "27" "session" "4f974dbb-9b29-4b13-9521-8089e4f69d0c" "value" ("Class" ": " ("value" "java.lang.String" 0) ("newline") "Value: " "\"2\""))
```

### CIDER version information

```
;; CIDER 0.18.0snapshot (package: 20180629.1511), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_172
```

### Lein/Boot version

Lein 2.8.1

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.6.0, Carbon Version 158 AppKit 1561.4) of 2018-06-30

### Operating system

macOS High Sierra

**Comment by dpsutton** [comment]
hi @ackerleytng can you help me reproduce this?

I'm using
![forms](https://user-images.githubusercontent.com/6377293/42131168-248a614a-7cc1-11e8-9232-eb71bda71a22.png)

and getting back
![result](https://user-images.githubusercontent.com/6377293/42131171-2b5b414c-7cc1-11e8-8294-873883030b26.png)

I tried it on `(+ 1 1)` and got back
```
Type: java.lang.Long
Value: "2"
---
Fields: 
  "MIN_VALUE" = -9223372036854775808
  "MAX_VALUE" = 9223372036854775807
  "TYPE" = long
  "value" = 2
  "SIZE" = 64
  "BYTES" = 8
  "serialVersionUID" = 4290774380558885855

```
It seems to be working for me. I am putting my cursor right after a form and doing `M-x cider-inspect-last-sexp`.

I don't see a CIDER version listed in your report. If you are running versions off of melpa (not melpa-stable) can you make sure to upgrade to the most recent version? There have been some big changes to the internals and a few more in the last day or two to clean up some edges so maybe this just goes away?

**Comment by dpsutton** [comment]
ah apologies I see the CIDER version now.

**Comment by ackerleytng** [comment]
I just upgraded, and the issue is gone. This has been working intermittently in-between upgrades/works for a while in a certain run, and after a while, perhaps after a few long evaluations, it'll be back.

Thanks for getting back to me so quickly! 

I'll monitor this issue reopen this issue if I experience further issues. Thanks!

**Comment by ackerleytng** [comment]
Thanks for maintaining cider! I really enjoy using cider, I don't even think I'm using cider's full power!

**Comment by dpsutton** [comment]
I'm just a contributor :). I learn new things every week as well. In fact, I had never used this feature before ha
