### ISSUE TITLE
Add support for reader tags to cider-doc

### ISSUE THREAD

**Issue by j-cr** [clojure-emacs/cider#2382]
Currently, if you try to get a docstring for a [reader tag](https://clojure.org/reference/reader#tagged_literals), you'll get something like `Symbol #light not resolved`.

Clojure doesn't "officially" support docstrings for tags, but since all tags are stored in `*data-readers*` as Symbols, it's possible for library authors to add `:doc` to them and for the tooling to recognize the tags and show the docstring.

If there's no docstring on the tag (e.g. it was loaded via `data_readers.clj`), then simply showing something like that would be helpful:
```
#foo/bar
Reader tag
  Not documented.

#foo/bar refers to `my.lib.foo/bar-reader`

[back]
```

I haven't looked at the code yet and not very familiar with how cider works, but I guess this shouldn't be too hard to implement? Check if the symbol starts with `#` => look up `*data-readers*`. Let me know if you want a pull request and\or there're some caveats I'm not aware of. (By the way, I'm a fan of your work, Bozhidar! Thank you for everything you do for the clojure and emacs communities. CIDER rocks!)

Brought up by @splayemu in https://clojureverse.org/t/speck-concise-inline-function-specs/2489/14

**Comment by bbatsov** [comment]
Yep, this should be easy to implement. PRs welcome!
