### ISSUE TITLE
Missing images on readthedocs.io

### ISSUE THREAD

**Issue by j-cr** [clojure-emacs/cider#2389]
On the page
https://cider.readthedocs.io/en/latest/miscellaneous_features/#enlighten-display-local-values
these two image urls return 404:
https://cider.readthedocs.io/en/latest/miscellaneous_features/images/enlighten_disabled.png
https://cider.readthedocs.io/en/latest/miscellaneous_features/images/enlighten_enabled.png

Note that everything works on github:
https://github.com/clojure-emacs/cider/blob/master/doc/miscellaneous_features.md#enlighten-display-local-values
so I'm not sure what's the problem

**Comment by camdez** [comment]
[Further down that same page](https://cider.readthedocs.io/en/latest/miscellaneous_features/#tracing-function-execution) you'll see images loading. Seems to be the case that readthedocs.io works fine with Markdown-style images but not `<img>` tags (seemingly similar to https://github.com/jupyter/notebook/issues/2304). Hope that's helpful.

**Comment by bbatsov** [comment]
Ah, that's a bummer. RTD is certainly not great when it comes to mkdocs support, but the two alternatives (converting the docs to asciidoc or deploying directly to GH pages with mkdocs) require extra effort I haven't been able to find. It's not just things like images - just check the numbered lists here http://www.cider.mx/en/latest/clojurescript/ I have absolutely no idea what to do to make RTD render this properly. :-)

**Comment by j-cr** [comment]
@bbatsov I guess I can help with this, which route you want to go? I think the GH pages one is better - it looks like asciidoc is basically dead (all 4 online editors I was able to find simply do not work at all and seem abandoned).

**Comment by bbatsov** [comment]
Oh, sorry - I meant to say RST (the native format for RTD). See https://docs.readthedocs.io/en/latest/getting_started.html#in-restructuredtext

Generally I'd prefer to simply do this https://www.mkdocs.org/user-guide/deploying-your-docs/, but ideally setup in a way where docs are generated after each commit or something like this.

**Comment by bbatsov** [comment]
I'm also contemplating reworking the manual in https://asciidoctor.org/docs/what-is-asciidoc/#whos-using-asciidoc, but I'm not that familiar with the publishing toolchain there. Seems that it has much better markup than markdown and it supports most of the markdown markup, so a transition between the two formats should be pretty straight-forward.

**Comment by bbatsov** [comment]
Anyways, I managed to fix those images. This used to work for quite a while, I wonder what messed it up.
