### ISSUE TITLE
Specify deps.edn alias

### ISSUE THREAD

**Issue by Lokeh** [clojure-emacs/cider#2396]
## Expected behavior

That I can easily set a default collection of deps.edn aliases to use when I execute `cider-jack-in`

## Actual behavior

I am unable to set a default collection of aliases to use with `cider-jack-in`

## Steps to reproduce the problem

I have a deps.edn like so:

```clojure
{:deps {}

 :paths ["src" "resources"]

 :aliases
 {:server {:extra-deps {org.clojure/clojure {:mvn/version "1.9.0"}
                        mount {:mvn/version "0.1.12"}
                        clj-time {:mvn/version "0.14.2"}
                        tick {:mvn/version "0.3.5"}
                        ring/ring-jetty-adapter {:mvn/version "1.6.3"}
                        cheshire {:mvn/version "5.8.0"}
                        garden {:mvn/version "1.3.3"}
                        com.taoensso/timbre {:mvn/version "4.10.0"}
                        hiccup {:mvn/version "1.0.5"}
                        org.clojure/tools.reader {:mvn/version "1.3.0"}
                        clj-http {:mvn/version "3.7.0"}
                        ring/ring-core {:mvn/version "1.6.3"}
                        org.clojure/core.async {:mvn/version "0.4.474"}}}

  :client {:extra-deps {thheller/shadow-cljs {:mvn/version "2.4.24"}
                        com.taoensso/timbre {:mvn/version "4.10.0"}}}

  :client/build {:main-opts ["-m" "shadow.cljs.devtools.cli" "release" "client"]}

  :dev {:extra-deps {binaryage/devtools {:mvn/version "0.9.10"}}
        :extra-paths ["dev"]}}}
```

To avoid loading server deps while building the client-side code, I had to move them to their own alias and leave the top-level deps map blank.

I would like to be able to somehow specify a set of aliases to use with this particular project, so that `cider-jack-in` would run `clojure` with `-A:server:client:dev` added to it.

### CIDER version information

CIDER 0.18.0snapshot (package: 20180731.1750)
Clojure 1.9.0

```
;; CIDER 0.12.0snapshot (package: 20160331.421), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_31
```

### Lein/Boot version

N/A

### Emacs version

Emacs 25.3.1

### Operating system

macOS 10.12.16

**Comment by bbatsov** [comment]
I'd simply put this in `cider-clojure-cli-global-options`:

`(setq cider-clojure-cli-global-options "-A:server:client:dev")`. 

Btw, invoking `cider-jack-in` with a prefix arg will also prompt you for any extra params (e.g. `C-u C-c C-x j j`).

**Comment by Lokeh** [comment]
Thank you, I think the prefix arg (`SPACE u SPACE m '` in spacemacs) is what I'll use.

I still think having some way of indicating this for a project (maybe a key in deps.edn?) would be nice but adding the `-A:server:client:dev` is not unreasonable.

**Comment by wilkerlucio** [comment]
Is there a way to combine dir local settings with global settings? In my case, I have a global alias `:local/devtools` that I would like to always be present when jacking in, but other aliases like `dev`, `test-deps` are per project, is there a way to have a combined setup?
