### ISSUE TITLE
piggieback is not auto-injected after updating to 20180806.728

### ISSUE THREAD

**Issue by Vinai** [clojure-emacs/cider#2401]
## Expected behavior

A compatible version of `cider/piggieback` is auto-injected when using `cider-jack-in-cljs`

## Actual behavior

`cider/piggieback` is not auto-injected.

```
[nREPL] Starting server via /usr/local/bin/clojure -Sdeps '{:deps {org.clojure/tools.nrepl {:mvn/version "0.2.13"} cider/cider-nrepl {:mvn/version "0.18.0"}}}' -e '(require (quote cider-nrepl.main)) (cider-nrepl.main/init ["cider.nrepl/cider-middleware"])'...
[nREPL] server started on 61808
[nREPL] Establishing direct connection to localhost:61808 ...
[nREPL] Direct connection to localhost:61808 established
error in process filter: user-error: Piggieback is not available.  See http://docs.cider.mx/en/latest/clojurescript for details
error in process filter: Piggieback is not available.  See http://docs.cider.mx/en/latest/clojurescript for details
```

## Steps to reproduce the problem

* Run `packages-list-packages`
* Upgrade `sesman` to latest package snapshot (`20180802.920`)
* Upgrade `cider` to latest package snapshot (`20180806.728`)
* Restart emacs
* Open file in project
* Run `cider-jack-in-cljs`

`deps.edn` contains:

```edn
{:deps {org.clojure/clojurescript {:mvn/version "1.10.339"}
        com.bhauman/figwheel-main {:mvn/version "0.1.5"}
        com.bhauman/rebel-readline-cljs {:mvn/version "0.1.4"}}
 :paths ["src" "target" "resources"]}
```

### Clojure version

Clojure 1.9.0
ClojureScript 1.10.339

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29)) of 2018-07-10

### Operating system

Max OS High Sierra

## Workaround

In slack @bbatsov suggested adding piggieback to deps.edn as a workaround, which resolved the issue.

**Comment by bbatsov** [comment]
@vspinu Could this be related to your most recent changes?

**Comment by vspinu** [comment]
Quite unlikely. Nothing of that functionality has been touched. But I will check with cli today.

**Comment by bbatsov** [comment]
@vspinu A few more people reported this on Slack, so I'm reasonably certain something broke. :-) I've been traveling the past few days, so I couldn't take a look at this myself as well, though.

**Comment by vspinu** [comment]
Sorry, this one completely slipped my mind.  I think I am injecting piggyback the old way in my projects and this is why I don't see it. Will fix asap.

**Comment by vspinu** [comment]
I have looked at it and I think it has nothing to do with my recent changes. `cider-lein-jack-in-dependencies` just doesn't have the `middleware` parameter as `cider-boot-jack-in-dependencies` does. I have checked 0.17 and it's exactly the same there. Looks like it always worked for boot but never (or at least for long) for lein.

More seriously, I don't think the current design of command construction is as elegant and as parsimonious as it could be. Particularly the poor man's OOP dispatch in functions like `cider-jack-in-command` and proliferation of `cider-xyz-command`, `cider-xyz-parameters`, `cider-xyz-foo` etc are pretty confusing and don't scale well IMO. 

I think a better design would be to have a configuration plist or alist for each environment of the form `(:env 'lein :command "lein" :command-options ... :plugins ... :middlewares ...)`. Then have a couple of generics which would dispatch on this configuration list, like `cider-jack-in-resolve-command` and `cider-jack-in-command` with methods defined only for a small subset of environments which require special handling.

There are other parts which would benefit from such an OOP design; `cider-check-xyz-requirements` for example. Now that we require emacs 25, cl-generic offers quite some options in this regard.

**Comment by vspinu** [comment]
Actually I was confused.  Piggyback is injected as dependency in lein but as middleware in boot, and the regression was indeed caused by my recent changes. Will fix in a second.

**Comment by bbatsov** [comment]
Btw, I completely agree with your previous comment. The way we're current handling the command generation and injections for the different supported tools is a complete mess. I'm not quite certain if what you propose is the best approach (it would eliminate the extra config vars and would streamline the setup in general, but would make it a bit harder for end users to customize things I guess), but I'm certain we need to rework the current approach. I really hate it how some packages now inject stuff only as lein plugins and those plugins are interpreted by other build tools as deps.

**Comment by vspinu** [comment]
> would make it a bit harder for end users to customize things I guess

Not necessary. The custom interface could be made very nice and make it clear what options are available and of what type. Even if it's a simple alist type it would go a long way.

In configuration files it's slightly more complicated but I think whoever uses plain lisp for configuration should  know what they do. Having `(add-to-list `cider-lein-config '(:plugins . "blabla"))` is not much harder than setq.

There is a middle ground as well. One can have an utility which would construct a configuration alist from individual `cider-lein-jack-in-xyz` variables dynamically.
