### ISSUE TITLE
REPL Does not work outside of project

### ISSUE THREAD

**Issue by lane-s** [clojure-emacs/cider#2404]
## Expected behavior
I can evaluate code in cider-mode and in the repl buffer after using `cider-jack-in` to start a REPL, even when not inside a clojure project.

## Actual behavior
The REPL starts up successfully, but evaluating an expression in my code buffer causes is to flash, but nothing else happens. 

Entering code into the REPL just causes the cursor to move to the next line without producing any output. Pressing enter again gets me back to the prompt, but there is still no output. I am setting emacs to debug on error.

All of this is working if I jack-in to a project, but not if a just create a new .clj file anywhere.

I tried both lein and clojure-cli as the default repl command. Neither worked, but with clojure-cli I at least got an error in the nrepl buffer: `no such var m/resolve-var`. I can post the full thing if needed, but it seems maybe irrelevant if it doesn't work with lein either.

## Steps to reproduce the problem

1. Set lein as the default-repl-command
2. Create a new .clj file
3. Write a simple println expression i.e. `(println "Hello Cider")`
4. Run `cider-jack-in`
5. Evaluate the println expression in your code buffer
6. Open a REPL buffer and try evaluating an expression

### CIDER version information

;; CIDER 0.18.0snapshot (package: 20180802.1919), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_131
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
;; ======================================================================

### Lein/Boot version
Lein 2.8.1

### Emacs version
26.1

### Operating system
OSX 10.12.5 Sierra

I apologize if this is a noob problem. I read the manual and I tried my best to solve it, but for now it seems like the best thing I can do is to raise this issue.

**Comment by bbatsov** [comment]
What's the command string used to start the REPL? Do you have anything in profiles that would be injected always?

**Comment by lane-s** [comment]
The command string: `[nREPL] Starting server via /usr/local/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.13\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[com.billpiel/sayid\ \"0.0.16\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.18.0-SNAPSHOT\"\] -- repl :headless :host ::...
[nREPL] server started on 51409
[nREPL] Establishing direct connection to localhost:51409 ...
[nREPL] Direct connection to localhost:51409 established`

I'm unsure how profiles.clj works, but mine looks like this:
`{:repl {:plugins [[cider/cider-nrepl "0.17.0"]
                  [refactor-nrepl "2.3.1"]
                  [lein-cljfmt "0.5.7"]]
:dependencies [[alembic "0.3.2"]
               [org.clojure/tools.nrepl "0.2.12"]]}}
`

**Comment by bbatsov** [comment]
You're problem is caused by the `refactor-nrepl` entry there, but generally I'd remove `cider-nrepl` as well and rely only on the injection that CIDER does itself. I'm assuming that your global tools.deps also have some incompatible dep in them.

**Comment by lane-s** [comment]
I have mistakenly shared a profiles.clj that was in some other repository on my system rather than in `~/.lein`. I have no profiles.clj file in that directory. I can find any tools.deps file on my system either. Running a `lein repl` and `clj` in a terminal both work ok.

**Comment by lane-s** [comment]
I got it working after restart. I do sometimes get this error when the REPL starts, but everything seems to work ok. Thank you!

[cider-error.txt](https://github.com/clojure-emacs/cider/files/2272435/cider-error.txt)
