### ISSUE TITLE
Dynamic font locking: how to set a different face for macros

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#2405]
`cider-font-lock-dynamically` doc says:

> macro (default): Any defined macro gets the font-lock-builtin-face.

How to choose a different face instead of `font-lock-builtin-face`?

I tried to search `font-lock-builtin-face` through the codebase, but I find no relevant matches.

Thanks - Victor

**Comment by mallt** [comment]
I think this is an error in the docstring of `cider-font-lock-dynamically` indeed, since macros get the `font-lock-keyword-face` according to [this line in cider-mode.el](https://github.com/clojure-emacs/cider/blob/master/cider-mode.el#L767).

**Comment by vemv** [comment]
Not stale

**Comment by Malabarba** [comment]
Indeed, @mallt is correct, the face being used is `font-lock-keyword-face`. You can customize that directly if you want to change how macros are displayed @vemv . Just do `M-x customize-face`.

If, on the other hand, you would like to customize the macro face without customizing `font-lock-keyword-face`, then we would need some code changes. They should be pretty small changes though, if you'd like to try a PR. It's just a matter of replacing `font-lock-keyword-face` with something like `cider-macro-face`, and defining a face with that name that inherits from `font-lock-keyword-face`.

**Comment by vemv** [comment]
Thank you @Malabarba !

> defining a face with that name that inherits from font-lock-keyword-face.

> Fixing the docstring would also be nice

Yes I'd desire both. Can open PR when I have capacity

**Comment by vemv** [comment]
Will impl

**Comment by vemv** [comment]
I revisited the issue and, other than the bad docstring, which is fixed now, there doesn't seem to be a problem - I can get different coloring for function and macro calls:

![image](https://user-images.githubusercontent.com/1162994/62768061-4fe85e00-ba96-11e9-8cbf-1bb11e98052d.png)


Maybe the bad docstring had confused me back then.
