### ISSUE TITLE
[feature request] enhance Java Doc to support open local java doc

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#2406]
When I use `cider-doc` on a function, it contains a link to open JavaDoc, but it always open an online url. Sometimes computer might not accessable to Internet. Like me, I have `openjdk8-doc` package installed on Arch Linux. It will put documentations under `/usr/share/doc/java/`.
When I use `clojure.java.javadoc`'s function `javadoc`. I found it does not have local java doc path, it is empty. Unless I add manually with `(add-local-javadoc "/usr/share/doc/java8-openjdk/api/")`.

I think this should be supported in CIDER, to auto detect standard doc path in system like Linux is (`/usr/share/doc/java8-openjdk/api/`) (The version number might be different, and `java8-openjdk` folder name might be different on different platforms).
If this should not be automatically, at least should provide a `defcustom` for adding it.

**Comment by xiongtx** [comment]
Why not do it yourself? Be the change you want to see in this world.

**Comment by expez** [comment]
> Why not do it yourself? Be the change you want to see in this world.

I think that was his intention, he was just asking if this was still relevant / desirable and perhaps about how to approach it.

I believe this is still very much wanted.

>  Any idea about this?

You could put a lot of effort into this by e.g. gathering a list of all the paths on various linux distros and windows and then query the repl to get openjdk/oraclejdk and the right version number to dive into that list of possible paths, but I think the 99% solution is just a `defcustom`. 

Most of us will set that variable once per system and not worry about it for years.  If we're using a different jdk for one of our projects we can use a `.dir-locals.el` to override it.

**Comment by stardiviner** [comment]
> but I think the 99% solution is just a defcustom.
>
> Most of us will set that variable once per system and not worry about it for years. If we're using a different jdk for one of our projects we can use a .dir-locals.el to override it.

I originall have not overthinking about this complex, then discussed with someone in Slack, found it's not that simple to handle all cases automatically. So I have not idea.

I will add the `defcustom` PR code later.

**Comment by stardiviner** [comment]
After edebug on the function `cider-javadoc`, and traced down it to the basic request function. Have not found anywhere can insert a place to read an Elisp option to use to change JavaDoc path. I searched CIDER source code, did found one variable `nrepl-javadoc-local-paths`. But It's not in Emacs ELPA package `cider` code. Even I set it (which it does not defined in ELPA cider), it still does not change nrepl response's "javadoc" path. Anyone knows about this, please give me a hint.
