### ISSUE TITLE
File mode specification error: (file-missing Cannot open load file No such file or directory cider-interaction) 

### ISSUE THREAD

**Issue by NightMachinary** [clojure-emacs/cider#2407]
After updating all my packages, I get this in my startup messages:
`File mode specification error: (file-missing Cannot open load file No such file or directory cider-interaction) `
I don't know if this is causing issues (My CIDER is broken now but perhaps not for this reason ...), but I would appreciate some hints regarding what this error might be.

### CIDER version information
```
;; Connected to nREPL server - nrepl://localhost:60801
;; CIDER 0.18.0snapshot (package: 20180808.1857), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_152
```

### Lein/Boot version

Leiningen 2.8.1 on Java 1.8.0_152 OpenJDK 64-Bit Server VM

### Emacs version

27

### Operating system

macOS

**Comment by vspinu** [comment]
Old versions of cider code is loaded. Try deleting cider from MELPA folder, then restart and only then re-install.

**Comment by bbatsov** [comment]
I'll close this, as it's certainly not an issue with CIDER itself.
