### ISSUE TITLE
cider-interactive-eval does not work when switching between clj/cljs buffers

### ISSUE THREAD

**Issue by aiba** [clojure-emacs/cider#2413]
## Expected behavior

With two REPLs (clj & cljs), evaluating an expression in a clj file should automatically send it to the clj REPL, and evaluating in a cljs file should automatically send it to the cljs REPL.

## Actual behavior

The expression is always sent to whatever the most recent REPL buffer had focus.  For example, if I put the cursor in the CLJ repl, then put the cursor in a CLJS file, and type C-c C-e, it tries to evaluate in the CLJ repl, not the CLJS repl.

## Steps to reproduce the problem

Open two repls within the same project, one clj and one cljs.  Switch between .clj and .cljs files and try evaluating expressions.

Both REPLs are initiated with `cider-connect` to a running cider-nrepl server.
The cljs REPL is established by running `(figwheel-sidecar.repl-api/cljs-repl)` within a clj REPL.

## Environment & Version information

* CIDER 0.18.0snapshot (package: 20180813.1518), nREPL 0.2.13
* Clojure 1.10.0-alpha6, Java 1.8.0_162
* figwheel-sidecar 0.5.16
* GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-30
* macOS 10.13.4

## Other Notes

I traced through some of the cider-emacs function calls and I think the culprit is that `(cider-repls type 'ensure)` only returns non-nil when a repl of `type` most recently had focus, regardless of whether a repl of `type` exists for the project.

`cider-repls` calls `(sesman-ensure-session 'CIDER)`, which seems to always return only the latest REPL that had focus, not all connected REPLs as I would hope.  (Perhaps this should be filed as a bug with the sesman project?  Or should cider be making use of the optional `ctx-types` argument to `sesman-ensure-session`?)

**Comment by aiba** [comment]
Oh I see.  I didn't realize `cider-connect-sibling-cljs` caused the repls to be linked behind the scenes.  That works great for me, thanks!

**Comment by bbatsov** [comment]
@vspinu I guess I nice improvement can be adding some warning when using `cider-connect` and `cider-jack-in` for the same context again. Something like "you're about to create a separate session, but you probably meant to use x instead. Proceed?". What do you think about something like this?

**Comment by vspinu** [comment]
This could help, but when should we ask? Surely when one has a clj session already and  jacks-in cljs, but should we ask when one has a clj session and attempts a clj jack-in?

**Comment by bbatsov** [comment]
Well, I think we should always ask if there's an existing session for a project context and someone invokes a command that would create a new session for that project. I can't imagine many scenarios when you'd want to do twice clj-jack-in for the same project. Or connect twice to the same server in different sessions.
