### ISSUE TITLE
sesman requirement is out of date

### ISSUE THREAD

**Issue by jaccarmac** [clojure-emacs/cider#2414]
`sesman-browser` is used in `cider-connection.el` as of 6a9bc1cc. However, `sesman` 0.1.1 does not contain said package.

Bit me in my bleeding edge setup and is easy to fix but something to keep in mind for the next stable release of both packages.

CC @vspinu

**Comment by vspinu** [comment]
I thought melpa fetches the most recent package anyway. 0.1.1 is the minimal version required AFAIU.

**Comment by jaccarmac** [comment]
That's correct, but (at least on my setup, which is not pure MELPA), dependencies aren't easy to upgrade without removing and reinstalling. Maybe it's less of a problem for other people?

**Comment by jaccarmac** [comment]
To clarify, Quelpa will not upgrade a dependency if it meets the minimum version required by the package depending on it. I assume this is how vanilla package management works as well but have not tested it.
