### ISSUE TITLE
Ability to restart REPL session

### ISSUE THREAD

**Issue by solatis** [clojure-emacs/cider#2420]
**Is your feature request related to a problem? Please describe.**

After updating cider to a recent version, it appears that the behavior of `cider-restart` changed a bit. Where it would completely restart the repl JVM process before, it now appears to be just reconnecting to the same repl session. 

This gets mostly in the way of stateful workflows, where the current state of the repl session / jvm process is corrupted (e.g. "failed shutdown of http server, and getting a 'port already in use' on subsequent restarts") and you would just like to restart the entire process.

**Describe the solution you'd like**

Behavior of `cider-quit` and `cider-jack-in` chained together in a single command. The problem with this solution is that `cider-jack-in` requires you to have the correct file open to open a session for the right project, which is cumbersome when managing many different REPL sessions.

Would be especially great if it didn't close the emacs buffer and reused the same buffer.

**Describe alternatives you've considered**

Currently I either `kill` the lein process, or invoke `cider-quit` and `cider-jack-in` manually, but as described above, this can become a bit cumbersome when managing many different REPL sessions.

**Additional context**

Discussed in Clojurians slack prior to filing this bug report and was confirmed by @bbatsov

**Comment by bbatsov** [comment]
As I mentioned in the chat - before the introduction of sesman each connection was tracking whether it was started with jack-in or connect and restarting it factored this (namely the connections spawned with jack-in would kill the server and start it again). I assume sesman sessions currently don't track this, but maybe they should (at least optionally). Or maybe we need some dedicated commands for managing nREPL servers? At any rate - we certainly should not be restarting servers that were started outside of Emacs.

**Comment by solatis** [comment]
I have no idea why it didn't work before, but now it does; you are completely right @vspinu , this is exactly what I'm looking for, thanks.
