### ISSUE TITLE
`cider-interactive-eval` fails for a CLJ buffer when an uninitialized CLJS REPL exists

### ISSUE THREAD

**Issue by plexus** [clojure-emacs/cider#2425]
## Expected behavior

Evaluating code from a CLJ buffer goes to the CLJ REPL.

## Actual behavior

CIDER tries to use the CLJS repl, and fails to do so because it hasn't initialized yet (the browser hasn't loaded).

## Steps to reproduce the problem

- `cider-jack-in-clj&cljs`
- use a browser based CLJS REPL type like `figwheel`
- don't open a browser, so the CLJS REPL does not have a runtime to eval forms against
- open a `.clj` file
- evaluate an expression

More to the point, evaluate `(cider-repls "clj" 'ensure)`. You will notice that the CLJS REPL is shown in the list.

### CIDER version information

```
;; CIDER 0.18.0snapshot (package: 20180818.258), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_91
```

### Emacs version

GNU Emacs 27.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2018-08-21

### Operating system

Ubuntu 16.04.5 LTS

**Comment by vspinu** [comment]
Why do you consider this an incorrect behavior more concretely? You don't have a CLJS repl yet, so you cannot evaluate expressions. Just like you said yourself "the CLJS REPL does not have a runtime to eval forms against".

**Comment by plexus** [comment]
I am evaluating Clojure expressions, not clojurescript. I do have a working
Clojure repl.

**Comment by vspinu** [comment]
I see. And I presume the uninitialized CLJS is not a "working" clj repl with browser env. Sorry, cannot try at the moment.

One solution would be explicitely mark the repl with "uninitialized" type, so it won't interfere with other repls. Not sure if it's a good solution though. If CLJS upgrade fails, you still might want to use that repls as CLJ repl in order to investigate the source of the problem. So I would rather not make this change. 

In any case, if you eval a clj form it should go in both clj repls if they are part of the same session (which they should be if you use sibling connect). So in the worse case you would send one extra line to theunitialized repl.

**Comment by plexus** [comment]
This would be fine, but instead emacs freezes with no indication of what's
happening, because the code that waits for a response is stuck in an
infinite loop. This should at least have a timeout, even a C-g doesn't
help, right now you have to either kill emacs or send a SIGUSR2 (learned
this recently and now I no longer need to kill emacs several times per day).

**Comment by vspinu** [comment]
Looks like something more fundamental is going on in there. Locks should definitely not happen.

**Comment by bbatsov** [comment]
> In any case, if you eval a clj form it should go in both clj repls if they are part of the same session (which they should be if you use sibling connect). So in the worse case you would send one extra line to theunitialized repl.

Are you sure about this? I thought they were supposed to go to the mostly recently used REPL? Or this was just for the REPL selection? I bring this up mostly because it sounds a bit odd to me.

**Comment by plexus** [comment]
> Looks like something more fundamental is going on in there. Locks should definitely not happen.

``` clojure
(defun nrepl-send-sync-request (...)
  (let* (...)
    (nrepl-send-request request
                        (lambda (resp) (nrepl--merge response resp))
                        connection
                        tooling)
    (while (and (not (member "done" status))
                (not (and abort-on-input
                          (input-pending-p))))
      (setq status (nrepl-dict-get response "status"))
      ...
      (nrepl-dict-put response "status" (remove "need-input" status))
      )
    ...))
```

This while loop assumes that at some point `(lambda (resp) (nrepl--merge response resp))` will run, updating the `status` to `"done"`, but since the CLJS REPL is waiting for the browser to connect and finish its upgrade, it can't do anything. No NREPL messages go back or forth, so this loops spins for all eternity, while `status` remains `nil`.

It does seem to have a timeout built-in, I did not debug in detail why that's not kicking in. I did find that every time this happened, no matter how long I waited, when I interrupted it with `kill -USR2` it turned out to be in this loop.

> Are you sure about this? I thought they were supposed to go to the mostly recently used REPL? 

This is indeed how it behaves, it simply loops over all REPLs.

``` emacs-lisp
(cider-map-repls :auto
  (lambda (connection)
    (cider--prep-interactive-eval form connection)
    ...))
```

**Comment by vspinu** [comment]
If you have multiple repls within a session then the code ends up in all of them. Normally you have one cljs and one clj repl, and it makes sense to have multiple cljs repls with different engines if you want to test them simultaneously, but rarely two or more clj repls. 

I think this should be fixed as follows. First temporary set the type to "cljs-uninitialized", then reset it to clj or cljs in the state handler. Will PR something today.

As to the hang, that's an unrelated issue. @plexus could you please insert `(sit-for 0.01)` in that loop? Your C-g quit is not triggering exit in that loop, which is pretty strange.

**Comment by vspinu** [comment]
@plexus 

> because the code that waits for a response is stuck in an infinite loop. 

I don't see this. Eval is asyncronuous and should not be creating the hang. Something else, maybe custom setup or hook, is going on in your case.
