### ISSUE TITLE
Support for namespace-aliased keywords for specs in cider-browse-spec

### ISSUE THREAD

**Issue by jgracin** [clojure-emacs/cider#2428]
Hi!

Function cider-browse-spec does not seem to support namespace-aliased keywords.  E.g. running it on symbols `::non-empty-string` and `::ami/queue` in the following code

```
(s/def ::non-empty-string (s/and string? (comp not clojure.string/blank?)))
(s/def ::ami/queue    ::non-empty-string)
```

does not work, i.e. it fails to find the match in the spec registry.

I suppose a solution could be to change `cider-browse-spec` to use the following instead of `cider-symbol-at-point`:

```
(defun cider--spec-symbol-at-point ()
  (let ((sym (cider-symbol-at-point)))
    (if (string-prefix-p "::" sym)
        (let* ((expr (format "(read-string \"%s\")" sym))
               (response (cider-nrepl-sync-request:eval expr (cider-current-repl) (cider-current-ns))))
          (nrepl-dict-get response "value"))
      sym)))
```

I'm using Emacs 26.1 and the the following:
```
;; CIDER 0.18.0snapshot (package: 20180818.258), nREPL 0.2.13
;; Clojure 1.9.0, Java 10.0.2
```
This is what Spacemacs/devel uses, but it seems to be the same as the current CIDER master branch (9a1171b).

**Comment by jgracin** [comment]
If the above solution is generally acceptable, I could make a pull request.

**Comment by bbatsov** [comment]
Where exactly is the problem, btw? I'm a bit confused by your explanation of this. First I thought you're reporting some issue with `cider-symbol-at-point`, but looking at your patch I'm not so sure about this.

**Comment by jgracin** [comment]
The problem is that `cider-browse-spec` does not work on symbols which begin with double-colon `::`.  Spec registry contains resolved symbols so cider-browse-spec cannot find symbols starting with `::`.  I hope this is clearer.

**Comment by jgracin** [comment]
This is still not working, btw.  When the cursor is within a namespace-aliased symbol (such as `::non-empty-string` above), the completing-read in cider-browse-spec uses the candidates list with resolved namespaces (e.g. :common/non-empty-string), and the initial input is ::non-empty-string, i.e. without the namespace.

**Comment by yuhan0** [comment]
This is still an existing bug, my workaround before discovering this issue was to use macroexpand in `cider-symbol-at-point` to resolve the keyword alias:

```elisp
        (when (string-prefix-p "::" str)
          (setq str (cider-sync-request:macroexpand "macroexpand-1" str)))
```

Not sure if there's any pros or cons compared to constructing a `read-string` form and passing it to eval.

**Comment by bbatsov** [comment]
@yuhan0 Your fix seems reasonable to me. An even simpler one to be to just get the current ns and adjust the symbol without doing any backend requests.

**Comment by yuhan0** [comment]
I don't think that works out for aliased keywords like `::ami/queue`, or it would require more code to parse the ns form, figure out the alias mappings and do string manipulations. 

Delegating to the same backend that performs the actual resolutions seems like a simpler and more maintainable solution :)

**Comment by yuhan0** [comment]
Unless there's a use case for `cider-symbol-at-point` to function without an active REPL connection? The above change would still function normally without one, and only do a request in case of a `::` keyword, in which case a backend is arguably needed.

**Comment by g7s** [comment]
Hi, I want to have this functionality too. @yuhan0 where did you put the code above?

**Comment by yuhan0** [comment]
In `cider-symbol-at-point`, here's the entire function definition for you to try:  

```elisp
(defun cider-symbol-at-point (&optional look-back)
  "Return the name of the symbol at point, otherwise nil.
Ignores the REPL prompt.  If LOOK-BACK is non-nil, move backwards trying to
find a symbol if there isn't one at point."
  (or (when-let* ((str (thing-at-point 'symbol)))
        ;; resolve ns-aliased keywords
        (when (string-match-p "^::.+" str)
          (setq str (or (ignore-errors (cider-sync-request:macroexpand "macroexpand-1" str)) "")))
        (unless (text-property-any 0 (length str) 'field 'cider-repl-prompt str)
          ;; remove font-locking
          (setq str (substring-no-properties str))
          (if (member str '("." ".."))
              str
            ;; Remove prefix quotes, and trailing . from constructors like Record.
            (thread-last str
              ;; constructors (Foo.)
              (string-remove-suffix ".")
              ;; quoted symbols ('sym)
              (string-remove-prefix "'")
              ;; var references (#'inc 2)
              (string-remove-prefix "#'")))))
      (when look-back
        (save-excursion
          (ignore-errors
            (when (looking-at "(")
              (forward-char 1))
            (while (not (looking-at "\\sw\\|\\s_\\|\\`"))
              (forward-sexp -1)))
          (cider-symbol-at-point)))))
```

There are a few tweaks from my initial workaround - `ignore-errors` was necessary to prevent eldoc from throwing errors as you're typing and momentarily have an invalid keyword like `::`.

@bbatsov I'll open a PR if you agree with the approach, it seems like quite a rough hack to use macroexpand for something that's not a macroexpansion..

**Comment by bbatsov** [comment]
@yuhan0 Sure!

**Comment by yuhan0** [comment]
Oh wait, I already submitted it some months ago! 😅 
https://github.com/clojure-emacs/cider/blob/ec175e6b5b85bbad91657bc761985507380fd75f/cider-util.el#L134
I guess this issue can be closed now?

@g7s You must be running an older version of Cider, try it again after upgrading :)

**Comment by bbatsov** [comment]
:laughing:

**Comment by g7s** [comment]
@yuhan0 Thanks a lot! I will try it later today 😀

**Comment by g7s** [comment]
I am trying to make this work but unsuccessfully. Maybe I am expecting something else? This is what I am trying to achieve:

1. Open a .clj file where I use an aliased qualified keyword say `::search/page-options`
2. Move cursor over it and do `M-x cider-browse-spec`
3. Open the spec browser showing the spec `:my.app.specs.search/page-options`

Instead of 3. I get a prompt to select the spec to browse.

I am using the latest CIDER version: 20200708.629 from MELPA (tried with the latest stable also not working as I expected)

**Comment by yuhan0** [comment]
Just a guess here, but Cider needs to resolve the `::search` alias in your current namespace, which requires the ns form to first be evaluated. Try again after `cider-load-file`?

**Comment by g7s** [comment]
Nope, no luck. Did `M-x cider-load-file` but nothing changed the behaviour stays the same.

**Comment by DogLooksGood** [comment]
I have a very stupid version, but works.

```
(defun +clojure-describe-spec ()
  (interactive)
  (when-let* ((code (thing-at-point 'symbol))
              (dict (cider-nrepl-sync-request:eval
                     code
                     (car (cider-connections))
                     (cider-ns-from-form (cider-ns-form))))
              (spec (-last-item dict)))
    (cider-browse-spec spec)))
```
