### ISSUE TITLE
CIDER connection manager doesn't understand symbolic links

### ISSUE THREAD

**Issue by alexander-yakushev** [clojure-emacs/cider#2433]
If the REPL was started from a file which was open through a symbolic link, but then a file from that project but directly (not through a symlink), any CIDER command will show `No linked CIDER sessions`. Closing the buffer and then opening the same file through a symlink works fine, and CIDER commands start to work.

## Expected behavior

Any project files should be linked to the REPL, regardless of the path they were reached.

## Actual behavior

Different paths to the same file are treated differently by CIDER.

## Environment & Version information
```
;; CIDER 0.18.0snapshot (package: 20180828.1539), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_102
```

Boot 2.8.1, Emacs 26.1, MacOS

**Comment by alexander-yakushev** [comment]
Perhaps, a single call + caching could work here? And maybe there is a way to distinguish a local resource from a remote one prior to calling `file-truename`?

**Comment by vspinu** [comment]
I went for caching. Thanks for bringing this up. It was always on the back of my mind but I needed a nudge :)
