### ISSUE TITLE
cannot restart repl after killed it

### ISSUE THREAD

**Issue by ftravers** [clojure-emacs/cider#2435]
*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable CIDER and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

**Remove all of the placeholder text in your final report!**

## Expected behavior
I start a repl, works fine.  then i kill it with: `kill-this-buffer`.  then i try to start a new repl and it doesn't work.
## Actual behavior
see above, but instead of opening a repl it sends the message: `selecting deleted buffer` to the mini-buffer
## Steps to reproduce the problem
1. start repl  with: `cider-jack-in-cljs`
2. kill repl with `kill-this-buffer`
3. try to start repl  with: `cider-jack-in-cljs`.  Repl doesn't start and error message: `selecting deleted buffer` echoes in mini-buffer.

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### CIDER version information
```
;; CIDER 0.18.1snapshot (package: 20180903.2111), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_172
```

### Lein/Boot version

```
╰─➤  lein --version
Leiningen 2.8.1 on Java 1.8.0_172 OpenJDK 64-Bit Server VM
```

### Emacs version
```
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05
```

### Operating system

```
╰─➤  uname -a
Linux archlinux 4.17.12-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 3 07:16:41 UTC 2018 x86_64 GNU/Linux
```

**Comment by bbatsov** [comment]
@vspinu Guess you should take a look into this. Another person just reported something similar on Slack.

**Comment by lmccombes** [comment]
I'm having the same issue.

Cider: `CIDER 0.18.1snapshot (package: 20180903.2111)`
Lein: `Leiningen 2.7.1 on Java 1.8.0_151 Java HotSpot(TM) 64-Bit Server VM`
Emacs: `GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29)) of 2017-09-15`
OS: `macOS 10.13.6`

**Comment by zarkone** [comment]
also met this issue, except `cider-quit` doesn't help. In my case the difference is that i don't jack-in but connect.

**Comment by AndreaCrotti** [comment]
I also have the same problem actually, not not with all projects

**Comment by maxweber** [comment]
I had the same issue. I don't know Emacs Lisp very well, but this change in the file `elpa/cider-0.18.0/cider-connection.el` fixed the problem:

```
(defun cider--gather-session-params (session)
  "Gather all params for a SESSION."
  (let (params)
    (dolist (repl (cdr session))
      (when (buffer-name repl)
        (setq params (cider--gather-connect-params params repl))))
    (when-let* ((server (cider--session-server session)))
      (setq params (cider--gather-connect-params params server)))
    params))
```

I've added the `(when (buffer-name repl) ...)` Basically the problem was that `cider--gather-connect-params` was called on a killed buffer, after you have closed a cider / nrepl connection. `buffer-name` returns nil, if it is a killed buffer.

**Comment by vspinu** [comment]
I will have a look. For now you can do restart. Either `cider-restart` (`C-c M-r`) for one repl or the full session with `C-c C-s C-r` (`sesman-restart-session`).

**Comment by wandersoncferreira** [comment]
@bbatsov I reported that on slack but couldn't find the time to fill the ticket here. 
```
;; CIDER 0.18.1snapshot (package: 20180903.2111), nREPL 0.2.13
;; Clojure 1.8.0, Java 10.0.2


And @maxweber solution worked just fine for me too.

**Comment by gdanov** [comment]
I have that problem with latest cider and using clojure-cli + figwheel

**Comment by mvarela** [comment]
I'm seeing the same behavior here (Spacemacs on Emacs 27.0.50, Cider 0.18.1 Snapshot, Clojure 1.9 and 1.8)

**Comment by rymndhng** [comment]
I have encountered this issue as well, the work around is to run both `clj-quit` and `sesman-quit`.

**Comment by jiacai2050** [comment]
Same issue here.

**Comment by Bost** [comment]
```
(defun my/close-buffer ()
    (interactive)
    (if (member (current-buffer) (cider-repls))
        (cider-quit)
      (if server-buffer-clients
          (server-edit)
        (kill-this-buffer))))

;; ... and for convenience
(global-set-key (kbd "s-k") 'my/close-buffer) ;; 'winkey-k'
```
