### ISSUE TITLE
Invalid cider-repl-history file prevents cider-jack-in from working

### ISSUE THREAD

**Issue by TimoFreiberg** [clojure-emacs/cider#2436]
## Expected behavior

If the cider-repl-history file is invalid, CIDER should still work.
If CIDER could clean up invalid parts automatically, I would prefer that, but if that's impossible (or too hard), I would be fine with getting a prompt to clean it up manually.

## Actual behavior

If the cider-repl-history file is invalid, CIDER doesn't start with the relatively cryptic error message `error in process filter: cider-repl--history-read: End of file during parsing` (although Bozhidar recognized the error immediately :smile: )
To get it working again, you have to clean up/delete the file manually.

## Steps to reproduce the problem

Use [broken-cider-repl-history.txt](https://github.com/clojure-emacs/cider/files/2351750/broken-cider-repl-history.txt) as your `cider-repl-history-file`, which has a malformed expression at the end:
```
(:require [clojure.java.io :as io]
          [datascript.core :as d]
          [mdm-utils
            [service :
```
Run `cider-jack-in-clj`

### CIDER version information

CIDER 0.18.1snapshot (package: 20180903.2111)

### Emacs version

GNU Emacs 26.1

### Operating system

Arch Linux

**Comment by vspinu** [comment]
Should be easy to fix, but how the broken entries get into the history in the first place?

**Comment by TimoFreiberg** [comment]
Unfortunately I have no idea how it happened.

**Comment by bbatsov** [comment]
I'll add here what's needed to be done - we just need to catch that error and display some message prompting the user to reset their history file.

**Comment by sovelten** [comment]
I was having this problem and solved it by removing the nrepl-history file inside `.local/cache`
