### ISSUE TITLE
'Wrong type argument: commandp, cider-start-map'

### ISSUE THREAD

**Issue by dpassen** [clojure-emacs/cider#2441]
## Expected behavior
Jack into a new REPL.

## Actual behavior
Upon C-c C-x, I'm met with the error 'Wrong type argument: commandp, cider-start-map'

## Steps to reproduce the problem
Open up a Clojure file, hit C-c C-x

After successfully opening a REPL (via C-c M-j or C-c M-x cider-jack-in-clj) and then quitting the repl (C-c C-q), C-c C-x j j works as described in the documentation.

### CIDER version information
```
;; CIDER 0.18.0 (Saigon), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_74
```

### Lein/Boot version

*Leiningen 2.8.1*

### Emacs version

*26.1*

### Operating system

*OS X 10.13.6 "High Sierra"*

**Comment by vspinu** [comment]
Autoloading issue. Will have a look.
