### ISSUE TITLE
Re-use previous REPL buffer when reconnecting

### ISSUE THREAD

**Issue by borkdude** [clojure-emacs/cider#2444]
## Expected behavior

I think this was the behavior of CIDER before I upgraded to 0.18.0

I start an app that runs nREPL on port x.
I connect using `cider-connect`.
I kill the app.
I start the app again.
I connect again using `cider-connect`.

There's already an inactive REPL for this project. Re-use existing?

## Actual behavior

I start an app that runs nREPL on port x.
I connect using `cider-connect`.
I kill the app.
I start the app again.
I connect again using `cider-connect`.
A session with the same parameters exists (DocSearch/app:localhost:43851).  You can connect a sibling instead.  Proceed? (y or n)

This is annoying because then I get two REPLs while one is not active anymore.

## Steps to reproduce the problem

See previous.

## Environment & Version information

cider 0.18.0
GNU Emacs 26.1

middleware:
```
[[cider/cider-nrepl "0.18.0"]
 [refactor-nrepl "2.4.0"]]
```

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
CIDER 0.18.0 (Saigon)
GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31
```

### Lein/Boot version

boot 2.8.1

### Emacs version

26.1

### Operating system

MacOS High Sierra

**Comment by vspinu** [comment]
> I kill the app.
> I start the app again.

Between these two steps emacs tells you that the process died right? 

Will have a look.

**Comment by borkdude** [comment]
> Between these two steps emacs tells you that the process died right?

I get to see:

> [nREPL] Connection closed unexpectedly (connection broken by remote peer)

**Comment by zalky** [comment]
Also seeing this after upgrading. Missing this feature.

**Comment by borkdude** [comment]
It may be relevant to tell that I'm seeing this in a boot project but not in a leiningen project. I discovered this only when I started working on a leiningen project later on.

**Comment by vspinu** [comment]
Shall we silently re-use any connection-less repls of the same type or you would still want the "Dead REPL buffers exist; reuse?" y-or-n message?

**Comment by borkdude** [comment]
I don't have a preference for either, whatever works for you :-)

**Comment by bbatsov** [comment]
> Shall we silently re-use any connection-less repls of the same type or you would still want the "Dead REPL buffers exist; reuse?" y-or-n message?

Seems to me we should prompt for this, same as we do for jack-in similarities.

**Comment by vspinu** [comment]
Makes sense. Another question. Should we allow cljs buffers to be re-used as clj REPLs and the other way around as a last resort?

**Comment by xiongtx** [comment]
> Should we allow cljs buffers to be re-used as clj REPLs and the other way around as a last resort?

I don't think so. CLJ and CLJS don't interact.

**Comment by vspinu** [comment]
Ok. 

I have a working fix on this one but there is a tiny issue. When the buffer is re-used no new banner is inserted. This means that the original banner at the top might not have the right connection info (particularly the port).

Ok with everyone if on re-connect a new banner is inserted at the point-max?

**Comment by vspinu** [comment]
> Ok with everyone if on re-connect a new banner is inserted at the point-max?

This will affect the manual restart (either connection or the whole session), the banner will be inserted in the middle of the buffer. It doesn't seem to be worthwhile to differentiate the types of restarts in this regard.

**Comment by zalky** [comment]
Seems reasonable to put a banner back in, as long as it is still conditional on `cider-repl-display-help-banner`.
