### ISSUE TITLE
Offer option to not display any banner at all

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/cider#2445]
There's an existing `cider-repl-display-help-banner` that controls whether the _help_ banner is displayed. It'd be nice to have a customizable variable that controls whether any banner at all is displayed.

**Comment by bbatsov** [comment]
We can certainly do this, but I wonder if this won't cause some problems - e.g. you want see immediately which version of Clojure/Java/nREPL you're using. This always seemed like something desirable to me, that's why it's not currently configurable.

**Comment by bbatsov** [comment]
Another option would be a configurable banner function, which can also be a no-op, of course.

**Comment by xiongtx** [comment]
On my current Emacs (26.1), if no text is inserted before the prompt (i.e. no banner at all), the prompt doesn't show unless I `redraw-frame` 😕.

So this seems to be not as simple as adding a new customizable variable...

**Comment by xiongtx** [comment]
I'm going to close this for now as the above problem is proving tricky and it's not a high priority.
