### ISSUE TITLE
Unable to start two different repls for clj and cljs in different processes

### ISSUE THREAD

**Issue by mitchelkuijpers** [clojure-emacs/cider#2447]
## Expected behavior
```
cider-jack-in-clj
```
Choose `clojure-cli` it starts a repl and gives me a clj repl buffer.
After this run:
```
cider-jack-in-cljs
```
Choose `shadow` it starts a repl and gives me a cljs repl buffer.

## Actual behavior
```
cider-jack-in-clj
```
Choose `clojure-cli` it starts a repl and gives me a clj repl buffer.
After this run:
```
cider-jack-in-cljs
```
It asks me
```
A session with the same parameters exists (Development/raw-admin:localhost:33751).  You can connect a sibling instead.  Proceed? (y or n) y
```
I choose `y` and then it prints:
```
[nREPL] Starting server via /usr/bin/clojure -A:dev -Sdeps '{:deps {org.clojure/tools.nrepl {:mvn/version "0.2.13"} refactor-nrepl {:mvn/version "2.4.0"} cider/cider-nrepl {:mvn/version "0.18.0"}}}' -e '(require (quote cider-nrepl.main)) (cider-nrepl.main/init ["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware"])'...
```
And after that nothing happens. I also tried it the other way around so first `cider-jack-in-cljs` and then `cider-jack-in-clj` but that doesn't make a difference. It also gives me the following warning:

## Steps to reproduce the problem

Run in a mixed clj and cljs project 
1. `cider-jack-in-clj`
2. `cider-jack-in-cljs`

The cljs repl will never give a repl buffer. I also tried first starting the cljs repl and then the clj this does not seem to make a difference.

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:33751
;; CIDER 0.18.1snapshot, nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_181
```

### Emacs version
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05

### Operating system

Arch Linux, gnome-shell 2.28

**Comment by olleromo** [comment]
I have the exact same situation; I start a second repl and the first one suddenly says cider[not connected]. If I evaluate something directly in the [not connected] repl, it picks up the connection and the second repl becomes [not connected].

**Comment by vspinu** [comment]
@mitchelkuijpers
> And after that nothing happens.

"Nothing" could not happen. There must be something going in the background. At least a server buffer should be created and should give some clues of what's going on. 

> It also gives me the following warning:

You forgot to paste the warning. 

I cannot reproduce this problem and to be frank have no idea how two separate sessions could interact. The sessions are completely isolated there should be no interference whatsoever. 

In any case, as that message suggests starting a sibling is both faster and leads to an easier to manage setup. Do you have a special reason to use a separate jack in session?

@olleromo 

I don't think it's the same problem. I guess you mean that `[not connected]` is displayed in the mode-line of the other REPL. There is only one place in the code-base where this could happen. Could you please go to that `[not connected]` repl and try `M-x (cider-current-repl)`. It should throw. I would need a backtrace.

**Comment by mitchelkuijpers** [comment]
Now when I thought about it some more, the main problem is that shadow-cljs needs to add some middleware which the shadow-cljs executable does automatically. Because I just tried starting a shadow-cljs server and then do a connect-sibling-cljs-repl and then cider fails with:

```
1. Unhandled java.lang.IllegalStateException
   Can't change/establish root binding of: *nrepl-cljs* with set
```

And we rather let shadow-cljs choose which middleware to include instead of figuring them out.

**Comment by vspinu** [comment]
> But for some reason sesman or cider never pick up on it.

There is a `*nrepl server ...*` buffer lying around. Have a look inside and see if it says anything meaningful.  If repl buffer hasn't appeared that means the client was never initialized because the server failed.

**Comment by jhimanka** [comment]
I have a slight variation of this. I start clj repl, it works. I start cljs repl, it asks me about the existing buffer and whether to continue, I say yes. The cljs repl starts and works. However, the clj buffers now say "not connected" and I can't evaluate anything in clj buffers. If I go to the repl buffer, everything works normally.

**Comment by manuel-uberti** [comment]
Any update on this? I'm facing this problem in a project configured with `deps.edn` and `shadow-cljs`.

**Comment by eraad** [comment]
> Any update on this? I'm facing this problem in a project configured with `deps.edn` and `shadow-cljs`.

You may want to check [this article] for a workaround (http://manuel-uberti.github.io/programming/2018/11/14/deps-shadow-cljs/).

**Comment by manuel-uberti** [comment]
I wrote that :flushed:

**Comment by eraad** [comment]
> I wrote that 😳

I'm sorry! :) It got me moving forward!
