### ISSUE TITLE
feature request: generate test function

### ISSUE THREAD

**Issue by WorldsEndless** [clojure-emacs/cider#2448]
There is already a command which tries to find and run the test associated with the function-at-point. It would be very beneficial to the TDD workflow if there existed a similar command to create a blank of the aforementioned function, having the appropriate name and namespace and ready to be filled in.

**Comment by dpsutton** [comment]
This should be closed here and opened in clojure-mode. I don't think this needs CIDER at all and could (and should) be done there totally

**Comment by dpsutton** [comment]
I have a draft of this ready. I'll use it for a few days and update

**Comment by bbatsov** [comment]
@dpsutton We're still waiting for that clojure-mode PR. ;-)
