### ISSUE TITLE
cider test report does not show stack trace for test.chuck

### ISSUE THREAD

**Issue by flyingmachine** [clojure-emacs/cider#2449]
## Expected behavior

When I run a test that uses `com.gfredericks.test.chuck.clojure-test/checking` using `C-c C-t t`, and that test throws an exception, then the stack trace should appear in the cider test report.

## Actual behavior

The test report includes:

```
Test Summary
minimal-cider-test-report-failure.core-test

Tested 1 namespaces
Ran 1 assertions, in 1 test functions
1 failures


Results

minimal-cider-test-report-failure.core-test
1 non-passing tests:

Fail in failing-report
failure report gives error in process filter
```

The exception isn't shown. The following is added to the `*Messages*` buffer:

```
Running test failing-report in minimal-cider-test-report-failure.core-test...
minimal-cider-test-report-failure.core-test: Ran 1 assertions, in 1 test functions. 1 failures, 0 errors.
error in process filter: cider-insert: Wrong type argument: stringp, (dict "fail" ((dict)) "failing-size" 0 "num-tests" 1 "result" "clojure.lang.ExceptionInfo: boop {}" "seed" 1536864029083 "shrunk" (dict "depth" 0 "result" "clojure.lang.ExceptionInfo: boop {}" "smallest" ((dict)) "total-nodes-visited" 0))
error in process filter: Wrong type argument: stringp, (dict "fail" ((dict)) "failing-size" 0 "num-tests" 1 "result" "clojure.lang.ExceptionInfo: boop {}" "seed" 1536864029083 "shrunk" (dict "depth" 0 "result" "clojure.lang.ExceptionInfo: boop {}" "smallest" ((dict)) "total-nodes-visited" 0))
``` 

## Steps to reproduce the problem

1. `git clone https://github.com/flyingmachine/cider-test-report-failure.git`
2. jack into the project
3. Execute `C-c C-t t` for the test `minimal-cider-test-report-failure.core-test/failing-report`

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:58145
;; CIDER 0.18.0 (Saigon), nREPL 0.2.13
;; Clojure 1.9.0, Java 10.0.2
```

### Lein/Boot version

Lein 2.8.1

### Emacs version

26.1

### Operating system

macOS High Sierra 10.13.6

**Comment by mallt** [comment]
CIDER expects a message that documents a test to be a string. [clojure.test/is](https://clojuredocs.org/clojure.test/is) seems to accepts vectors and maps as `msg` as well, so it would be good if CIDER could handle these as well.

I think it would make most sense to transform the `:message` to a string in cider-nrepl. Otherwise the message is transfered to emacs as an `nrepl-dict` and then needs to be transformed in CIDER in order to print it in the test results buffer.

@bbatsov do you agree on this approach? Thanks!

**Comment by bbatsov** [comment]
> CIDER expects a message that documents a test to be a string. clojure.test/is seems to accepts vectors and maps as msg as well, so it would be good if CIDER could handle these as well.

I guess I completely missed this. :-) 

> @bbatsov do you agree on this approach? Thanks!

Yeah, I do.
