### ISSUE TITLE
Support for Lumo

### ISSUE THREAD

**Issue by Immortalin** [clojure-emacs/cider#2450]
**Is your feature request related to a problem? Please describe.**
Lumo is a clojurescript compiler that uses the V8 node.js runtime without any JVM dependencies. Currently the only repl available is inf-clojure. This creates a subpar development environment when used with traditional Clojure backend code

**Describe the solution you'd like**

Cider support for Lumo

**Describe alternatives you've considered**

`inf-clojure`

**Comment by bbatsov** [comment]
I'm afraid that support for Lumo's going to be pretty hard for a couple of reasons:

1. nREPL doesn't have a self-hosted version (yet)
2. Much of the existing middleware relies on Clojure libs that don't have self-hosted versions. 

Long story short - it's a lot of work, that I certainly don't have the time to tackle.
