### ISSUE TITLE
The cider-insert-in-repl command does not eval

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#2451]
## Expected behavior
It should eval when `cider-invert-insert-eval-p` is `t`.

## Actual behavior
It does not eval BUT it inserts the form in the buffer.

Small debugging session:

```
Result: "(def body (-> body-str js/JSON.parse api/js->body)..."
Result: nil
Result: 36007 (#o106247, #x8ca7)
Result: 36058 (#o106332, #x8cda)
Indenting region...
Text is read-only
```

I am debugging and after the following form the control flow seems gone:

```elisp
(let ((beg (point)))
      (insert form)
      (indent-region beg (point)))
```

## Steps to reproduce the problem

Call `cider-insert-last-sexp-in-repl` and try to set `cider-invert-insert-eval-p` to `t`.

### CIDER version information
latest master `7f1c5e2`

### Emacs version

*27.0.50*

**Comment by dpsutton** [comment]
I ran into this a bit ago. The indent region throws an error but I couldn't get emacs to give me the error, even with debug on error set. I cleared my repl and it then worked again. If you have a better suggestion i'm all ears but i don't even know how to get a handle on this problem at the moment.

**Comment by arichiardi** [comment]
I think I have done the same and it works again. Cannot see what the error is either, you are in the REPL buffer so why do you want to indent in there? Style?

**Comment by bbatsov** [comment]
Yep. Makes the code prettier. 

> Text is read-only

Seems to me the error is obvious - `Text is read-only`. Such code can't be indented. Now someone has to figure out what exactly are the bounds for that region as likely they are incorrect.

**Comment by arichiardi** [comment]
I have checked and the `beg` character has this:

```
Text content at position 19551:


There is an overlay here:
 From 19551 to 19578
  face                 hl-line
  priority             -50
  window               [Show]


There are text properties here:
  fontified            t

[back]
```

Does not seem read-only though, I am on a `(`.
