### ISSUE TITLE
cider-jack-in-cljs flaky behavior with figwheel.main

### ISSUE THREAD

**Issue by cjohansen** [clojure-emacs/cider#2455]
## Context

I have a project set up with deps.edn and figwheel.main. I have a `.dir-locals.el` that contain

```el
((nil
  (cider-default-cljs-repl . figwheel-main)
  (cider-figwheel-main-default-options . ":dev")
  (cljr-inject-dependencies-at-jack-in . nil)))
```

## Expected behavior

`cider-jack-in-cljs` always boots up a figwheel REPL.

## Actual behavior

`cider-jack-in-cljs` boots up a figwheel REPL once in a blue moon, but mostly it boots up a clj REPL.

## Steps to reproduce the problem

1. Check out this repo: https://github.com/cjohansen/cider-figwheel-main
2. Run `cider-jack-in-cljs` from `src/sample_app/main.cljs`
3. Observe that a clj REPL is created

I have seen jack-in successfully create a figwheel main REPL with this setup, but I cannot for the life in me make it happen again.

## Environment & Version information

```clj
{org.clojure/tools.nrepl {:mvn/version "0.2.13"}
 refactor-nrepl {:mvn/version "2.4.0"}
 cider/cider-nrepl {:mvn/version "0.18.0"}}
```

Emacs version:

``

### CIDER version information

```
;; CIDER 0.18.1snapshot (package: 20180903.2111), nREPL 0.4.4
;; Clojure 1.9.0, Java 1.8.0_131
```

### Emacs version

*26.1*

GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511))
 of 2018-05-31

### Operating system

OS X 10.12.6

**Comment by cjohansen** [comment]
Also, I tried this without the `.dir-locals.el` file. Verified that `cider-default-cljs-repl` was `nil` (with eval), and it still boots up a clj REPL. Isn't it supposed to prompt me for the kind of REPL session to start?

**Comment by cjohansen** [comment]
So... this seems to be a stupid user error. Manually invoking `M-x cider-jack-in-cljs` works fine. I've been invoking `C-c M-j`. I didn't manage to differentiate between that and `C-c M-J` (CAPITAL J)... Sigh. Sorry for this.

**Comment by bbatsov** [comment]
Btw, that's part of the reason we're phasing out those two keybindings in favour of a much more comprehensive `C-c C-x something` scheme to do jack-in/connect. There's now also `C-c M-x` that lists all the available jack-in/connect commands.
