### ISSUE TITLE
cider melpa and cider-nrepl clojars versions out of sync

### ISSUE THREAD

**Issue by kommen** [clojure-emacs/cider#2460]
The current cider version on melpa reports with `(cider-version)`: `"CIDER 0.18.1snapshot (package: 20180926.1025)"`

But on [clojars](https://clojars.org/cider/cider-nrepl) there is no `0.18.1-SNAPSHOT`, only a `0.19.0-SNAPSHOT`

In our dev setup, we match the auto-injected cider-nrepl version to the installed version of the cider package, so this  version mismatch poses a problem.

But in general, I think these versions should match, to minimize confusion.

**Comment by kommen** [comment]
Just saw a discussion related to this in the cider slack

> As noted in the release notes - we no longer keep those versions in lockstep. Using 0.18.0 is perfectly fine.

So I guess we should just auto-inject `cider-required-middleware-version` then.

**Comment by bbatsov** [comment]
> But in general, I think these versions should match, to minimize confusion.

Now that many editors are using `cider-nrepl` we can no longer match its release cycle to that of CIDER itself. Therefore the change you've noticed.

> So I guess we should just auto-inject cider-required-middleware-version then.

Yep. Or newer one, provided it doesn't feature backward incompatible changes.
