### ISSUE TITLE
cider.test: ability to focus on a single test via metadata

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#2463]
## Brief

This feature would be basically equivalent to `^:test-refresh/focus` in  https://github.com/jakemcc/lein-test-refresh/blob/1f3669d23cea20f1552ff3627957cfb3589fd3c8/README.md#built-in-test-narrowing-test-selector .

We could choose `^:cider/focus` instead as the magic keyword.

## Why

* I use a custom test definition macro instead of deftest (let's call it `my-deftest`), so individual tests aren't recognised (I can't run it individually via `Menu bar -> CIDER Interactions -> Run test`)
* So, I run `cider-test-run-ns-tests` instead (with this command, `my-deftest`s are recognised)
* But other failing tests may distract me.

Don't know if there would be a more idiomatic approach. I see there's the notion of 'filters' in cider-test.el, I guess it's closely related but `^:cider/focus` sounds to me like something that should work OOTB.

Thoughts?

Thanks - Victor

**Comment by bbatsov** [comment]
Have you seen the section on test selectors here https://docs.cider.mx/en/latest/running_tests/ ?

Seems to me you're asking just for us to add support for running some predefined selector, right? That'd be trivial to achieve.

**Comment by vemv** [comment]
Thanks for the support!

I just read the doc.

* Selectors currently have the drawback of being interactive. That's bit of too much friction - one may have to type the selector manually, which makes one think, type, make typos etc.

* OTOH, I realised that metadata or predefined filters may not be the best UI for this. Let me show you what we use at work:

![image](https://user-images.githubusercontent.com/1162994/46245712-e669de80-c3f2-11e8-9dff-3f3028568b33.png)

It compiles to a regular `clojure.test/deftest`, with a `when-foo-bar-baz--quux-happens` symbol name.
 
One cannot attach metadata to strings, therefore my original proposal was misguided.

Reading https://docs.cider.mx/en/latest/running_tests/#using-cider-test-with-alternative-test-libraries, I found out about the `:test` metadata. We do emit it (our `deftest+` uses `clojure.test/deftest`), but CIDER/clojure-mode will fail to parse things with `(clojure-find-def)`:

![image](https://user-images.githubusercontent.com/1162994/46245740-55473780-c3f3-11e8-8570-52ec9c730b25.png)

(cider-test-run-test uses clojure-find-def)

As you can see, the `deftest+` is misparsed.

I see two possible solutions:

* The existing `cider-test-run-test` could (optionally) eval the top-level form, get the Clojure var out of the evaluation result, and extract the desired symbol from it.
* Implement a new command: `cider-eval-and-run-test`. It would first evaluate the top-level form at point (i.e. the current `deftest`), then run that precise test by inspecting its `:test` metadata.

I hope I explained the scenario clearly.

**Comment by vemv** [comment]
I could solve this in my personal config cleanly, and given this is quite a corner case I should just close the issue.
