### ISSUE TITLE
'help-echo text-properties make messages less persistent

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#2472]
Hi there,

I don't use the functionality provided by `cider--help-echo`. Still, 'help-echo text properties are unconditionally added, which makes invocations to `(message...)` less persistent: the emitted message will disappear after hovering Clojure code with the mouse.

I propose that if `cider-use-tooltips` is customized to nil, this LOC https://github.com/clojure-emacs/cider/blob/e071b027c1dafea8599db8c2b039f11d9eacf994/cider-mode.el#L987 (and possibly other similar ones) isn't executed.

WDYT?

Thanks - Victor

**Comment by bbatsov** [comment]
Sounds reasonable to me.

**Comment by vemv** [comment]
Not stale

(can open a PR when I find the time)

**Comment by vemv** [comment]
Time for some elispin'
