### ISSUE TITLE
Issues with content-type mechanism

### ISSUE THREAD

**Issue by plexus** [clojure-emacs/cider#2479]
CIDER recently shipped with the ability to render e.g. images inline in the REPL. On the cider-nrepl side this relies on two new middlewares, `slurp` and `content-type`, and on the Emacs side there's an extra handler you can pass to `nrepl-make-response-handler` that, when set, can handle responses that contain a `:content-type` + `:body`.

I think this is a great feature, but it could stand to be improved. This is a meta-issue for things that I think need to be addressed.

- Currently only works when directly evaluating in a REPL buffer (partially addressed [here](https://github.com/clojure-emacs/cider/pull/2476))

CIDER has many different ways of eval'ing things, in a REPL, in a buffer, in a buffer but with result going to the REPL buffer, in a buffer but result going to a popup window, results being inserted, with or without pretty-printing, etc. We should give some thought to how this feature should behave in these different scenarios.

- Acts on files regardless of the content-type

Currently when you do `(io/file "big-binary-blob")`, then that blob will be slurped and inserted into the REPL buffer. Same for instances of `URL`/`URI`, they will be fetched and inserted. Some smarter content-type handling would be good there. Unknown types should render the `:value` as before, rather than the `:body`.

- Not extensible

Currently `java.io.File`, `java.net.URI`, `java.net.URI` and `java.awt.Image` are handled. These are hard coded. People should be able to extend this to other types. This is addressed in this PR: https://github.com/clojure-emacs/cider-nrepl/pull/548

**Comment by bbatsov** [comment]
> CIDER has many different ways of eval'ing things, in a REPL, in a buffer, in a buffer but with result going to the REPL buffer, in a buffer but result going to a popup window, results being inserted, with or without pretty-printing, etc. We should give some thought to how this feature should behave in these different scenarios.

Yeah, absolutely. I think that a good approach would be to show images in a dedicated buffer (or maybe even inline overlays) when they are the result of interactive evaluation operations. 

> Currently when you do (io/file "big-binary-blob"), then that blob will be slurped and inserted into the REPL buffer. Same for instances of URL/URI, they will be fetched and inserted. Some smarter content-type handling would be good there. Unknown types should render the :value as before, rather than the :body.

Yep, I completely agree. 

> Currently java.io.File, java.net.URI, java.net.URI and java.awt.Image are handled. These are hard coded. People should be able to extend this to other types. This is addressed in this PR: clojure-emacs/cider-nrepl#548

@arrdem also pointed this out in the initial implementation, but then we agreed that having something beats having nothing and we'd extend this down the road. It's great to see you tackling this!

On a general note - we really need someone to own this feature and drive it forward. @arrdem has been pretty busy lately and for me it's unlikely that I'll do much on the CIDER front before the end of the year. I'm hoping that at some point once this feature is mature enough we can actually promote it to nREPL itself. This definitely seems to me like something that can be a core middleware (or two) one day.

**Comment by plexus** [comment]
> On a general note - we really need someone to own this feature and drive it forward. @arrdem has been pretty busy lately and for me it's unlikely that I'll do much on the CIDER front before the end of the year. I'm hoping that at some point once this feature is mature enough we can actually promote it to nREPL itself. This definitely seems to me like something that can be a core middleware (or two) one day.

I'd like to spend some time on this but I'm not going to make big promises about it. I'll start by submitting incremental improvements and see where it goes from there. I just stepped away from the consultancy I was doing to spend more time on Lambda Island, which has been a little abandoned lately. I need to weigh out my priorities here. I also have [Kaocha](https://github.com/plexus/kaocha) where I'm hoping to keep some momentum. That said I can see that CIDER is understaffed and I'd like to get a bit more involved, so this could be a good way in.

**Comment by bbatsov** [comment]
No big promises needed. :-) We're all quite busy, so I'd gladly take any help we could get - not matter how small it might be.
