### ISSUE TITLE
Reimport classes without restarting the REPL

### ISSUE THREAD

**Issue by jonasseglare** [clojure-emacs/cider#2480]
**Is your feature request related to a problem? Please describe.**

I have a big mixed Clojure/Java Leiningen project for computer vision that I develop using CIDER. High-performance parts are implemented in Java. Until now, I have been using the ```lein-virgil``` plugin that automatically recompiles the Java source code and then reloads all namespaces and reimports the classes. Unfortunately, this approach is not robust, it does not seem to work with all recent JDK versions and frequently the ```cider-jack-in``` command fails when the ```lein-virgil``` plugin is used. So I have deactivated the ```lein-virgil``` plugin and I am looking for a different workflow now.

So currently, after editing a Java source file from emacs, I first do
```(shell-command "lein javac")```
followed by
```(sesman-restart)```

This seems to work well, but unfortunately it is a bit slow and I lose the state in my REPL session.

**Describe the solution you'd like**

I would like a command ```cider-ns-reimport``` that reimports all the classes of the current namespace without having to restart the REPL.

**Describe alternatives you've considered**

Alternative I:
Using ```lein-virgil```. This approach does not always work, as explained in the problem formulation.

Alternative II:
Using ```(shell-command "lein javac")``` followed by ```(sesman-restart)```. This approach works, but harms the productivity a bit because it involves the restart of a REPL session.

Alternative III:
I also considered using the Janino Java library to dynamically compile and load classes from within Clojure, but it is limited. For instance, I don't see how I could break up my Java code in multiple files that refer each other.

**Additional context**

No additional context.

**Comment by bbatsov** [comment]
I'd be happy to add something like this, but I'm not sure what exactly should be the semantics of this re-import. Do we need just to evaluate `import` or is there more to this?

**Comment by jonasseglare** [comment]
Thank you for the rapid reply. Just evaluating import will not solve it. Once a class has been imported, it is cached somewhere I believe and importing it again will likely used the cached version.

I dug a bit deeper in how [Virgil](https://github.com/ztellman/virgil) is implemented. As previously explained, what is problematic is its use as a Leiningen *plugin* which seems to cause the ```cider-jack-in``` command to fail for a project that I am working on. But after reading the source code of Virgil, I thought that I could still use it to get the behaviour that I want without using it as a Leiningen plugin. So I wrote some helper code and wrapped it up in [this repository](https://github.com/jonasseglare/rejavanate). There is a README.md that explains my workflow. In short, when I am working on a project in a CIDER session, I just have to hit ```Ctrl + F12``` and all the Java code is recompiled and reimported. 

I still have to see if the approach that I came up with really works well, but so far it seems to work. This makes this issue that I submitted not so urgent, now that I might have an approach that works for me. But nevertheless, I can imagine there might still be those who would appreciate this functionality to be part of Cider.

**Comment by arrdem** [comment]
I'm surprised to hear that `lein-virgil` has a problematic interaction with cider, I'm a heavy user of both (as I think is ztellman) and haven't had issues with it. CIDER will almost certainly not incorporate any `virgil` like features, unless `virgil` becomes part of `cider-nrepl` or `orchard`.

The JVM spec defines class reloading to NOT invalidate or update any existing instances of classes with the same class name. This is why `defrecord` and `deftype` can be so squirrely - in order to achieve the same reloading semantics that clojure's Vars provide for fns, all classes and fns which reference a reloaded class have to be reloaded. Which is the behavior which Virgil implements, using an appropriate inspection of loaded classes to form a dependency graph for reloading.

It's not possible to implement the desired behavior without such an analysis - more details on the problems you mention using CIDER and Virgil at once would be the best way to move forwards here.

**Comment by jonasseglare** [comment]
This is maybe a bit off-topic as it regards mainly Virgil, but it is worth noting that the project where I failed to ```cider-jack-in``` was one Leiningen mixed Java/Clojure project that linked to other mixed Java/Clojure Leiningen projects using so called [checkout dependencies](https://github.com/technomancy/leiningen/blob/stable/doc/TUTORIAL.md#checkout-dependencies). For smaller projects that are not that complex, Virgil appears to work great. Unfortunately, I have not had time to properly look into it except observing that, when I turn of the ```lein-virgil``` plugin, ```cider-jack-in``` properly works. Ideally, I would like to come up with the smallest possible setup that can properly reproduce the issues with ```cider-jack-in``` and Virgil and then continue the discussion from there on the Virgil Github issue page.

So from this discussion it seems to me that it is unlikely that CIDER will be able to reimport freshly compiled Java code and that it might be better to understand why ```cider-jack-in``` appears to fail for me when using ```lein-virgil```.
