### ISSUE TITLE
exception during cider-jack-in (0.18.0snapshot)

### ISSUE THREAD

**Issue by sdledesma** [clojure-emacs/cider#2486]
## Expected behavior
cider-jack-in starts a repl process and connects to it without error output.

## Actual behavior
Exception and big stack trace. The problem occurs whether I try cider-jack-in or cider-connect to a previously started REPL.

The relevant (at least to me) parts of the exception are:
SEVERE: Unhandled REPL handler exception processing message {:op init-debugger, :print-level 10, :print-length 10, :session b8d7dede-86ec-490e-ac8c-f1a042c43034, :id 8}
java.lang.ClassNotFoundException: clojure.tools.reader.reader_types.SourceLoggingPushbackReader, compiling:(cider/inlined_deps/toolsreader/v1v3v0/clojure/tools/reader.clj:1:1)

I'm also attaching a file with the full stack trace.  

[stacktrace.txt](https://github.com/clojure-emacs/cider/files/2480845/stacktrace.txt)

This problem didn't occur until I updated my emacs packages and prelude this morning.

## Steps to reproduce the problem

From the command line:
run 
lein update-in :dependencies conj \[nrepl\ \"0.4.5\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.4.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.19.0-SNAPSHOT\"\] -- repl :headless :host localhost
and then try to run cider-connect.

From Emacs:
run cider-jack-in from a clojure file.

## Environment & Version information

GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian
running prelude.

### CIDER version information

;; Connected to nREPL server - nrepl://localhost:38159
;; CIDER 0.18.1snapshot (package: 20181014.2104), nREPL 0.2.12
;; Clojure 1.9.0, Java 1.8.0_181

### Lein/Boot version

Leiningen 2.6.1 on Java 1.8.0_161 GraalVM 1.0.0-rc1

### Emacs version

GNU Emacs 25.2.2

### Operating system

Linux VB-mint 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sdledesma** [comment]
I would like to add that I also get a similar exception after that first one if I try to compile my source files.

**Comment by daaku** [comment]
I also ran into this after I upgraded cider last night, but only on one of my projects. Fortunately it has an incredibly simple `project.clj` which might be useful to help diagnose the issue:

```clj
(defproject myproject "0.1.0-SNAPSHOT"
  :dependencies [[net.cgrand/xforms "0.18.2"]
                 [org.clojure/clojure "1.9.0"]
                 [org.clojure/data.csv "0.1.4"]])
```

**Comment by bbatsov** [comment]
I've reverted the tools.reader dep to an older version which seems to work fine. Fetching the latest `cider-nrepl` snapshot for clojars should solve the problem all of you experienced.
