### ISSUE TITLE
comment after a form at end of buffer tries evaluating last atom of comment

### ISSUE THREAD

**Issue by mfiano** [clojure-emacs/cider#2487]
## Expected behavior

Form is evaluated

## Actual behavior

Last atom of comment is attempted to be evaluated

## Steps to reproduce the problem

Put any form, followed by a comment at the end of a buffer. It's important that no newline in the buffer appears after this line. Something like the following:

```clojure
(do "foo") ;; this is a test
```
Then attempt to compile the form with `C-c C-c`, *not* `C-x C-e`.

## Environment & Version information

Doom Emacs. Latest from develop branch, along with latest CIDER from master (e6dcdfece93f4450f99c0645071d87ef1f1eea74).

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.18.1snapshot, nREPL 0.4.5
;; Clojure 1.9.0, Java 1.8.0_181
```

### Lein/Boot version

N/A

### Emacs version

26.1

### Operating system

Arch Linux

**Comment by vspinu** [comment]
I don't see any problems with `cider-eval-defun-at-point` (what do  you have on C-c C-c?). Could you please describe the issue in more detail? The title is not very informative.

**Comment by mfiano** [comment]
`C-C C-c` is `cider-eval-defun-at-point`. The issue is if there is an inline comment at the end of a line on the *last* line of a file, with that file not having a new line character at EOF. For example, attempting to eval this:

(example!)[https://files.michaelfiano.com/images/screenshots/img-20181016102639.png]

Results in: `Unable to resolve symbol: bar in this context`

**Comment by vspinu** [comment]
Don't see it :/

**Comment by dpsutton** [comment]
I'm unable to replicate this.

`(print "foo") ;; random` with point anywhere on this line, including in the comment at the end.

**Comment by hlissner** [comment]
I am able to reproduce this in vanilla Emacs. It is caused by `clojure-backward-logical-sexp` (which `cider-defun-at-point` uses to ascertain the starting boundary of the form). It doesn't expect the form to end on the same line as EOB (i.e. no trailing newline).

Here is how I can reproduce it:

```elisp
(require 'clojure-mode)
(require 'cider)
(add-hook 'clojure-mode-hook #'cider-mode)
(message
 "%s %S\n%s %S"
 "With trailing newline:"
 (with-temp-buffer
   (clojure-mode)
   (insert "(print \"foo\") ;; bar\n") 
   (cider-defun-at-point))
 
 "Without trailing newline:"
 (with-temp-buffer
   (clojure-mode)
   (insert "(print \"foo\") ;; bar") 
   (cider-defun-at-point)))
```

The output:

```
With trailing newline: "(print \"foo\") ;; bar
"
Without trailing newline: "bar"
```

**Comment by dpsutton** [comment]
hmm. I wonder why its not triggering for me. I'm running a clojure-mode that includes a pending PR here that affects beginning of defun: https://github.com/clojure-emacs/clojure-mode/pull/493

Can you tell me what your clojure-mode version is? This beginning of defun stuff is hard to get straight when it comes to what it expects, interactions with paredit, etc.

**Comment by mfiano** [comment]
`(clojure-mode-display-version)` reports "clojure-mode (version 5.8.2)"
