### ISSUE TITLE
Not an nREPL dict error when running tests

### ISSUE THREAD

**Issue by vitvakatu** [clojure-emacs/cider#2488]
## Expected behavior
I follow [this tutorial](http://clojure-doc.org/articles/tutorials/emacs.html) without issues.

## Actual behavior
When trying to run tests with "C-c C-t p" or "C-c C-t t" I get an error in minbuffer:
```
Not an nREPL dict
````

## Steps to reproduce the problem
Create new project as in [tutorial](http://clojure-doc.org/articles/tutorials/emacs.html). 
```
This time it will succeed, so try running the tests with C-c C-t t(i.e M-x cider-test-run-test) and you should get a test report buffer showing some failure information:
````
^ place where everything goes wrong

Changing versions to more actual doesn't work (CIDER 0.18 and Clojure 1.9.0)

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:60981
;; CIDER 0.18.1snapshot (package: 20181014.2104), nREPL 0.2.12
;; Clojure 1.9.0, Java 1.8.0_181
```

### Lein/Boot version

Leiningen 2.8.1 on Java 1.8.0_181 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

26.1

### Operating system

Windows 10

**Comment by vspinu** [comment]
Can you get a stacktrace on this one? (`M-x toggle-debugg-on-error`).

**Comment by vitvakatu** [comment]
@vspinu Thank you for a quick response. 
I enabled stacktrace and made the same sequence of actions to reproduce - but it works as desired!
I think it was an issue with some PATH-related things, because I've rebooted my machine recently.
