### ISSUE TITLE
Association lost when using `cider-jack-in` with more than one project

### ISSUE THREAD

**Issue by daaku** [clojure-emacs/cider#2489]
## Expected behavior

Expecting multiple separate projects to be able to `cider-jack-in` and have the project files maintain the repl association.

## Actual behavior

One instance of a jacked in repl works as expected, upon opening a second one, the first one loses it's association.

## Steps to reproduce the problem

1. Create 2 projects
2. `cider-jack-in` in the first project, it works as expected.
3. `cider-jack-in` in the second project, the new repl works as expected.
4. Go to file opened in step 2 and try to reload the ns. Note the repl association is lost.

### CIDER version information

```
;; CIDER 0.18.1snapshot (package: 20181014.2104), nREPL 0.2.12
;; Clojure 1.9.0, Java 10.0.1
```

### Lein/Boot version

Leiningen 2.8.1

### Emacs version

26.1

### Operating system

maOS Mojave 10.14

**Comment by vspinu** [comment]
I cannot reproduce this. What doe the `C-c C-s i` and `C-c C-s C-w` show? 

Do you recognize anything of what has been discussed in #2447? Looks very similar.

**Comment by daaku** [comment]
I swear I reproduced it 3 times, but I can no longer reproduce it! Sorry, and thanks for looking into it!

(I force upgraded my cider-nrepl snapshot to fix another issue, maybe fixed this too?..)
