### ISSUE TITLE
cider-jack-in failing with "Symbol’s function definition is void: sesman-linked-sessions"

### ISSUE THREAD

**Issue by dvelitchkov** [clojure-emacs/cider#2491]
## Expected behavior
cider-jack-in just works

## Actual behavior
cider-jack-in errors out with `Symbol’s function definition is void: sesman-linked-sessions`

## Steps to reproduce the problem
M-x cider-jack-in

### CIDER version information
l0.18.0

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.18.0 (Saigon), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_181
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
```

### Emacs version
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-28

### Operating system
Ubuntu 18.04

This is probably something really stupid and simple, but my google-fu is failing. I'm also a LISP/Clojure/Emacs noob, so apologies in advance. 

Vanilla Emacs, installed latest packages through Emacs' package manager. Nothing crazy. 

CIDER is attempting to call `sesman-linked-sessions` which doesn't exist in Sesman, seems like it was replaced by `sesman--linked-sessions` which should be ok since the new function is aliasing the old one here - https://github.com/vspinu/sesman/blob/14475d8192a785568a23f274f7715b1509da93ea/sesman.el#L976

Yet for whatever reason that alias isn't working on my machine. I changed the function call to `sesman--linked-sessions` in cider.el and voila - `cider-jack-in` works!

The fact that the alias isn't working and me being the first to discover this leads me to believe it's not a real bug but something silly I'm just not seeing on my end.

**Comment by manuel-uberti** [comment]
I am not able to reproduce this, with latest  CIDER from MELPA.

**Comment by kinleyd** [comment]
I can reproduce this error with sesman v. 0.3.2. I've had to revert to git tag v.0.3 to regain cider functionality.

**Comment by dvelitchkov** [comment]
Phew. Glad I'm not the only one. Out of curiosity - shouldn't the `define-obsolete-function-alias` call in Sesman prevent this from happening? General ELISP question perhaps.

**Comment by kinleyd** [comment]
There was an [issue](https://github.com/vspinu/sesman/issues/11) at the sesman repo which says that the issue was resolved and that we'd just have to wait till the update reaches Melpa. However, that was 4 days ago and the issue remains - could the update take that long to reach Melpa?

**Comment by vspinu** [comment]
Both cider and sesman are up to date in MELPA. You must be using an older version locally. New cider doesn't use `sesman-linked-sessions` anymore.

**Comment by kinleyd** [comment]
Ah yes, just checked my init.el - I'm on Melpa Stable, having left Melpa some years ago. So I'll just wait till the fix percolates there. In the meantime I'm just using a workaround mentioned on [Reddit](https://www.reddit.com/r/Clojure/comments/9owlxx/emacs_sesman_package_problem/)

**Comment by vspinu** [comment]
Arh, this makes sense. I have  just pushed a new version tag to sesman to avoid issues with melpa stable.

**Comment by kinleyd** [comment]
Thanks Vitalie, much appreciated!
