### ISSUE TITLE
Do a require before cider-repl-set-ns

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#2495]
Hi folks!

I have been bitten by some problem that is not related directly but triggered some thoughts on `cider-repl-set-ns`. At the moment it sends a `in-ns`, which means that if the code has not required the ns before, in Clojure it will create an empty namespace - which is never what you want to do - and in ClojureScript, depending on the REPL type, might generate weird error messages like `[:did-not-find...your namespace...]` in shadow-cljs.

Would it be too breaking for folks to send something like `(require 'namespace) (in-ns 'namespace)` instead?

Or have another command for doing that (that I would use all the time :smile:) ?

Thanks!

**Comment by bbatsov** [comment]
Perhaps we can change this. I don't remember why we chose `in-ns`, but I assume we did it to avoid potential errors on missing namespaces. Perhaps that's another thing we can make configurable?

**Comment by arichiardi** [comment]
Ah right, a defcustom there would be good.
