### ISSUE TITLE
Leverage nREPL's built-in pprint support

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2496]
We recently added pprint support to nREPL and this ticket is mostly a reminder that we have to implement support for this in CIDER. It's going to replace the `cider-nrepl` pprint middleware in the long run. 

Details - https://nrepl.xyz/nrepl/design/middleware.html#_pretty_printing
nREPL PR - https://github.com/nrepl/nrepl/pull/59

**Comment by arichiardi** [comment]
Was checking this, the first link is 404 but I found it in the docs.

**Comment by bbatsov** [comment]
Link updated.
