### ISSUE TITLE
Option to find definition in same window

### ISSUE THREAD

**Issue by simon-katz** [clojure-emacs/cider#2499]
When I hit M-. or similar to find a definition, if the buffer containing the definition is already being displayed in another window of the current frame, CIDER switches to that window.

I find this annoying. I prefer that the current window always be used.

Would it be possible to have an option for this?

FWIW, I have a hack that gives me what I want. It arranges for `cider-jump-to` to call `switch-to-buffer` instead of `pop-to-buffer`:

```
(defvar *nomis/cider-jump-to/reuse-selected-window?* nil)

(let* ((advice-name '-nomis/cider/replace-pop-to-buffer-within-cider-jump-to))
  (advice-add 'cider-jump-to
              :around
              (lambda (orig-fun &rest args)
                (let* ((*nomis/cider-jump-to/reuse-selected-window?* t))
                  (apply orig-fun args)))
              `((name . ,advice-name)))
  (advice-add 'pop-to-buffer
              :around
              (lambda (orig-fun buffer &rest other-args)
                (if *nomis/cider-jump-to/reuse-selected-window?*
                    (switch-to-buffer buffer nil t)
                  (apply orig-fun buffer other-args)))
              `((name . ,advice-name))))
```

**Comment by mallt** [comment]
Removing the `display-buffer-reuse-window` action function [in the `cider-jump-to` function](https://github.com/clojure-emacs/cider/blob/master/cider-common.el#L143) should result in the desired behavior.

I guess the action functions could be controlled by a new customization variable, but then the behavior would be changed for all occurences of the `cider-jump-to` function and not only for the `cider-find-var` command.

**Comment by simon-katz** [comment]
I think customization of the action functions would give me what I want.

BTW, maybe I should have mentioned that M-. in an Emacs Lisp buffer does do what I want.

**Comment by agzam** [comment]
interestingly I have an opposite problem. Docstring for `cider-find-var` states: 
```
A prefix of ‘-‘ or a double prefix argument causes
the results to be displayed in a different window.
```
but I am failing to make it appear in other window. It's always in the same window.

**Comment by agzam** [comment]
Well, I submitted a tiny PR - locally it fixes things for me: opens in the same window by default, opens in the other window with prefix arg. https://github.com/clojure-emacs/cider/pull/2583

**Comment by simon-katz** [comment]
I've created a PR to address this at https://github.com/clojure-emacs/cider/pull/2757
