### ISSUE TITLE
cider-jack-in-clj&cljs issue

### ISSUE THREAD

**Issue by achikin** [clojure-emacs/cider#2504]
## Expected behavior
Both clj and cljs repls process input correctly
## Actual behavior
`clj` repl hangs on any command. `[==   ]` "progress bar" is running indefinitely, no output produced.
## Steps to reproduce the problem
1. Open Emacs
2. Open project file
3. run `cider-jack-in-clj&cljs`
4. Switch to `clj` repl
5. Type any command e.g. `(+ 1 1)`
6. No output produced, "progress bar" spins indefinitely

This does not happen if I use `cider-jack-in` instead of `cider-jack-in-clj&cljs`

### UPD:
1. run `cider-jack-in-clj`
2. repl runs ok
3. run `cider-jack-in-cljs`
4. clj repl stops working after cljs repl starts

### UPD2:
1. run `cider-jack-in-clj`
2. repl runs ok
3. run `cider-connect-sibling-clojurescript`
4. clj repl stops working after cljs repl starts

### UPD3:
Tried to switch to `figwheel-main` instead of `figwheel` as a cljs repl type. Got a message `Figwheel-main is not available. Please check [cider docs link]`

### UPD4: 
Managed to set up `figwheel-main`. The same issue persists - as soon as `cljs` repl starts - `clj` repl hangs.

### CIDER version information
```
 CIDER 0.19.0snapshot (package: 20181030.2222), nREPL 0.2.12
 Clojure 1.9.0, Java 1.8.0_20
```

### Lein/Boot version
Leiningen 2.8.1 on Java 1.8.0_20 Java HotSpot(TM) 64-Bit Server VM

### Emacs version
GNU Emacs 26.1

### Operating system
MacOS Mojave 10.14.1

**Comment by malchmih** [comment]
Same here

**Comment by vspinu** [comment]
There is a similar issue opened somewhere, also with fighweel. Till a simple  project where this could be reproduced emerges I don't think there are hopes for fixing this.

**Comment by arichiardi** [comment]
@achikin can you reproduce with https://github.com/bhauman/figwheel-main/blob/master/README.md#try-figwheel-with-flappy-bird

I was using that without glitches with cider master last weekend.
In case you do, another thing that could be beneficial to see is the `$HOME/.lein/profile.clj`

**Comment by achikin** [comment]
@arichiardi let me try. I think I forgot to mention that it's Spacemacs.

**Comment by achikin** [comment]
@arichiardi I've re-installed Spacemacs and everything works as expected.
Reproducible builds ¯ \ _ (ツ) _ / ¯

**Comment by stevematdavies** [comment]
Is there a solution for this?
