### ISSUE TITLE
Trimming of maps in Cider causes evaluation of code to fail

### ISSUE THREAD

**Issue by didibus** [clojure-emacs/cider#2507]
## Expected behavior
Running

```clj
(edn/read-string
   (prn-str
    (let [map-size 101]
      (zipmap (range 0 map-size) (range 0 map-size)))))
```

Should return a map of 101 elements.

## Actual behavior
In Cider, it instead throws 

> RuntimeException Map literal must contain an even number of forms  clojure.lang.Util.runtimeException (Util.java:221)

This bug only happens inside Cider. Running this code in a normal Clojure REPL like lein repl with nRepl works as expected.

The reason it fails in Cider is that Cider trims the map as soon as it gets above 100 elements. Thus the map becomes unbalanced:

```clj
{10 10, 18 18, 105 105, 52 52, ...}
```
These `...` are inserted by Cider when the map gets above 100 elements. You can see this by running:

```clj
(edn/read-string
   (prn-str
    (let [map-size 100]
      (zipmap (range 0 map-size) (range 0 map-size)))))
```

Which will return a map of 100 elements as normal.

It appears somehow that ciders modifies the string returned by `prn-str`, and makes it so that the edn map literal inside it is unbalanced, due to trimming.

## Steps to reproduce the problem

Just run:

```clj
(edn/read-string
   (prn-str
    (let [map-size 101]
      (zipmap (range 0 map-size) (range 0 map-size)))))
```

Inside a Cider repl.

### CIDER version information

```
;; CIDER 0.19.0snapshot (package: 20181030.2222), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_192
```

### Lein/Boot version

*Leiningen 2.8.1 on Java 1.8.0_192 OpenJDK 64-Bit Server VM

### Emacs version

*GNU Emacs 25.1.1 (x86_64-redhat-linux-gnu, X toolkit, Xaw3d scroll bars) of 2016-10-19

### Operating system

* Linux

**Comment by bbatsov** [comment]
CIDER sets `*print-length*` to 100 by default. Tweak this or set it to `nil` and it will be business as usual.

**Comment by didibus** [comment]
Hum, that explains how the behavior affected Clojure code evaluation. Wouldn't there be a better way for Cider to limit the size of outputs from nRepl which wouldn't affect Clojure code evaluation?

If you see my example, nothing actually gets printed to Cider.

I understand Cider does this because Emacs performance on large prints is bad, and also maybe just good UX to not print huge things by default. But in a situation like my code snippet, it actually causes bugs in the code that arn't actually there.

So I wonder if instead of using print-length, nRepl couldn't just be made to trim the string it returns. So nothing in my code would break standard Clojure assumptions.

Regards

**Comment by bbatsov** [comment]
Yeah, that's perfectly possible now. It just wasn't so possible when the workaround was added. :-) I can add a ticket on nREPL's end, but I'm overwhelmed with work, so I can't make any promises I'll get to it in the foreseeable future. Hopefully someone will pick it up.

**Comment by bbatsov** [comment]
See https://github.com/clojure-emacs/cider/issues/1115#issuecomment-374487527 and https://github.com/clojure-emacs/nrepl/nrepl/issues/75.

**Comment by didibus** [comment]
Thanks, I don't think its a super high priority for now. I know you've been helping a bunch on many Clojure projects. Much appreciated! My employer isn't very OSS friendly, so I can't help much more then by reporting issues, writing blog posts, and helping out others unfortunately.

**Comment by bbatsov** [comment]
This behaviour was changed in CIDER 0.21. Now it no longer sets `*print-length*` by default.
