### ISSUE TITLE
Cider-find-dwim should jump to keyword

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#2508]
Hello folks!

This is not a problem per se but something I find a bit not straightforward to understand.
Basically when I call `cider-find-dwim` on a keyword, I expect it to use `cider-find-keyword`.

I have to keep this distinction in my head at them moment while the `-dwim` command suggests it should handle whatever I mean :smile: 

Not a blocker, not a thing even maybe :smile:

**Comment by bbatsov** [comment]
I think we simply added `cider-find-keyword` at some later point and forgot to updated `cider-find-dwim`. That should be easy to address.

**Comment by arichiardi** [comment]
It looks like also `cider-find-ns` should be put in there. Just scanned the code for understanding a bit how it works

**Comment by arichiardi** [comment]
I think this one should be kept open....but I am biared
