### ISSUE TITLE
cider doesn't recognize shadow-cljs projects

### ISSUE THREAD

**Issue by vigilancetech-com** [clojure-emacs/cider#2509]
The cider documentation ( https://cider.readthedocs.io/en/latest/up_and_running/#setting-up-a-clojure-project-optional ) says that one should be set up a project with either lein, boot, or clj (tools.dep).  Shadow-cljs projects should also be recognized (in that respect, I guess this is a feature request instead of a bug).
## Expected behavior
when using a shadow-cljs project cider doesn't give a warning message that there isn't a project
## Actual behavior
gives the warning message
## Steps to reproduce the problem
$ mkdir myproj
$ cd myproj
$ shadow-cljs init
edit your files to create an app (e.g. https://github.com/shadow-cljs/examples/tree/master/electron )
compile/watch your app ala:
$ shadow-cljs watch app
bring up cljs file in your app w/emacs and M-x cider-connect-cljs
select the defaults.   Enter 'app' for build-id
C-z to switch to the REPL
observe the error message(s)
## Environment & Version information

any version

### CIDER version information

any version

### Lein/Boot version
n/a but any version of shadow-cljs

### Emacs version
any version
### Operating system
any

**Comment by bbatsov** [comment]
shadow-cljs is supported now. Don't remember when exactly did we do this, though.
