### ISSUE TITLE
Restrict auto jump to reflection warnings in the current project only

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider#2514]
Currently, when `*warn-on-reflection*` is true and `cider-atuo-jump-to-error` is non-nil, each time some external code with reflections (notably cider-nrepl itself) is loaded the user is faced with a pop-up buffer in that foreign project.   

I think a meaningful solution would be to auto-jump only to locations in the current project only.

**Comment by arichiardi** [comment]
Is a warning considered an error? I would say that is for me kind of twisted?

**Comment by vspinu** [comment]
Those warnings are highlighted in stderr face and cider treats them as errors.
