### ISSUE TITLE
Cider-doc does not show spec in ClojureScript

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#2523]
## Expected behavior
The `cider-doc` buffer should show:

```
Spec:

arguments  : (s/cat 
              :i integer?)
returns    : any?

Browse spec

user/my-foo is defined in *cider-repl git/fonda:localhost:44699(clj)*.
```

## Actual behavior
It does not, only the docstring is showing up.

## Steps to reproduce the problem

Open a ClojureScript repl and connect it to cider then:

```clojure
(defn my-foo [i] (inc i))
(require '[cljs.spec.alpha :as s])
(s/fdef my-foo :args (s/cat :i integer?))
```

At this point you can `cider-doc` on the `my-foo` symbol and notice that there is no spec section.

### CIDER version information

```
;; 0.19.0-snapshot (latest master)
;; Clojure 1.10.0-beta6
```

### Tooling version

*Shadow 2.7.4*

### Emacs version

*27.0.50*

**Comment by arichiardi** [comment]
This is the communication happening "over the wire":

```elisp
(-->
  id         "18"
  op         "info"
  session    "954e1774-10d9-4762-b77a-9b12d562c3bb"
  time-stamp "2018-11-17 18:44:14.690829021"
  ns         "cljs.user"
  symbol     "cljs.user/my-foo"
)
(<--
  id           "18"
  session      "954e1774-10d9-4762-b77a-9b12d562c3bb"
  time-stamp   "2018-11-17 18:44:14.699634378"
  arglists-str "[i]"
  column       40
  file         "cljs/user.cljs"
  line         1
  name         "my-foo"
  ns           "cljs.user"
  status       ("done")
)
```

It seems that `cljs-tooling` is not returning - has never probably been? - the things that `cider-doc` expect in order to display the spec.

**Comment by arichiardi** [comment]
To be more precise the spec is added [here](https://github.com/clojure-emacs/orchard/blob/master/src/orchard/meta.clj).

**Comment by bbatsov** [comment]
> It seems like orchard is the part that for Clojure adds the :spec key to the info map: https://github.com/clojure-emacs/orchard/blob/master/src/orchard/info.clj

Yeah, that's true. The info functionality has different implementations for Clojure and ClojureScript.

> Now, either I copy things to cljs-tooling 👎 or we decide on a strategy on how to start migrating cljs-tooling to orchard 👍 😄 😄 🎉

I'm fine with either approach. I guess the copying will be easier to do in the short-term.
