### ISSUE TITLE
"Error from syntax checker clojure-cider-eastwood: Done with no errors"

### ISSUE THREAD

**Issue by zilti** [clojure-emacs/cider#2525]
## Expected behavior

The check runs fine.

## Actual behavior

The editor becomes nearly unusable after `cider-jack-in` due to the error with clojure-cider-eastwood.

## Steps to reproduce the problem

`cider-jack-in`

### CIDER version information

```
;; CIDER 0.19.0snapshot, nREPL 0.4.5
;; Clojure 1.9.0, Java 1.8.0_181
```

### Lein/Boot version

Boot 2.8.2

### Emacs version

26.1

### Operating system

OpenSUSE Tumbleweed

**Comment by bbatsov** [comment]
That should be reported in https://github.com/clojure-emacs/squiggly-clojure
