### ISSUE TITLE
3 callbacks of async nrepl-request:eval

### ISSUE THREAD

**Issue by kostafey** [clojure-emacs/cider#2530]
```lisp
(nrepl-request:eval "(+ 1 2)"
                    (lambda (x) (message "Result: %s" (nrepl-dict-get x "value")))
                    (cider-current-connection))
=>
;; "85"
;; Result: 3
;; Result: nil [2 times]
```
So, it's 3 callbacks of `nrepl-request:eval`. 
The first with a result `"value"`, and then 2 without.
What is a reason for that?

**Comment by mallt** [comment]
The nREPL server sends multiple responses for an `eval` operation. Apart from the response containing the value, there can also be a response containing the status f.ex. (`done` in this case).

You can find more info about the nREPL responses in the [message section of the nREPL manual](https://nrepl.xyz/nrepl/design/overview.html#_responses).

In the `*nrepl-messages*` buffer you can find more details about the responses the nREPL server is sending to CIDER.

**Comment by bbatsov** [comment]
I guess we can close this one.
