### ISSUE TITLE
cider-find-var: can't jump to symbol definition

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/cider#2534]
## Expected behavior

When using `cider-find-var` (<kbd>M-.</kbd>) on a symbol, I expect to "jump" to its definition anywhere in the project.

## Actual behavior

Using `cider-find-var` on a symbol shows `Symbol: ` in the echo area:

- if  I immediately press <kbd>RET</kbd>, I get `Symbol ‘’ not resolved`
- if I type the name of the symbol, for instance `alfresco-node`, and then press <kbd>RET</kbd>, I get `Symbol ‘alfresco-node’ not resolved`

## Steps to reproduce the problem

In a Clojure project, jack-in with <kbd>C-c C-x j j</kbd> and try using `cider-find-var` for a symbol in the same namespace as the namespace you are visiting, or in a different namespace. 

The result is the one pointed out in the section `Actual behaviour` above.

### CIDER version information

```
;; CIDER 0.19.0snapshot (package: 20181128.1311), nREPL 0.2.12
;; Clojure 1.9.0, Java 1.8.0_191
```

### System information

```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2018-12-04

Repository revision: f745cf8c438cdb258bc1a37b617749d1c84e688e
Configured using:
--host=x86_64-debian-linux-gnu --with-modules host_alias=x86_64-debian-linux-gnu

Emacs uptime: 3 hours, 52 minutes, 14 seconds
Colour theme: sanityinc-tomorrow-night
Operating system: Ubuntu 18.04.1 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.3
```

## Side notes

[dumb-jump](https://github.com/jacktasia/dumb-jump) actually lets me jump to the symbol definition.

**Comment by vspinu** [comment]
I see this mostly when the the namespace form hasn't been evaluated yet. `C-c M-n e` helps. An year ago this was not required AFAICR.

**Comment by manuel-uberti** [comment]
No luck in my case. I tried evaluating all the namespaces in my project, but I still can't jump to the 
definition of the symbol at point.

**Comment by bbatsov** [comment]
> I see this mostly when the the namespace form hasn't been evaluated yet. C-c M-n e helps. An year ago this was not required AFAICR.

Nothing related to this has been changed in a very long time (at least not intentionally).

> No luck in my case. I tried evaluating all the namespaces in my project, but I still can't jump to the
definition of the symbol at point.

Can you share with us the nREPL message exchange. It will make pretty clear what's going on.

**Comment by manuel-uberti** [comment]
I restarted Emacs and did another try with `nrepl-toggle-message-logging` but now I am not able to reproduce it. 

Could you please leave this open and let me do other tries? If I'm still not able to reproduce the error I'll close the issue.

Sorry for the noise.

**Comment by manuel-uberti** [comment]
Now it happened. This is the output of in `*nrepl-messages`:
```
(-->
  id         "16"
  op         "info"
  session    "60a8674e-9f1e-4704-b785-624a1b31439e"
  time-stamp "2018-12-05 07:59:50.051196904"
  ns         "gaypa-docs.apis.routes.activities"
  symbol     "alfresco-node"
)
(<--
  id         "16"
  session    "60a8674e-9f1e-4704-b785-624a1b31439e"
  time-stamp "2018-12-05 07:59:50.063465099"
  status     ("done" "no-info")
)
```

**Comment by vspinu** [comment]
> Nothing related to this has been changed in a very long time (at least not intentionally).

Now I often need to `C-c M-n M-e` on various occasions. A year ago (I had a 10 months break from Clojure) I didn't even know the shortcut key; it was almost never needed. Will check this up next time I am bugged by it.

**Comment by bbatsov** [comment]
Hmm, now that I think about it there's a chance that this was broken when I was refactoring `cider-interaction.el`, as it used to live there. 

The relevant functionality is controlled by `cider-auto-track-ns-form-changes` and now lives in `cider-eval.el`. If I have some time I'll debug it as well. Historically CIDER required people to manually keep track of their ns form being in sync with the REPL state, but I added this auto-tracking at some point, as many people coming from non-Lisp backgrounds were confused they needed to eval the `ns` before evaluating anything else.

**Comment by stathissideris** [comment]
`cider-find-var` seems to work on files that explicitly belong to my project, but it starts failing as soon as I jump to code that belongs to a dependency. I tried evaluating with `cider-load-buffer` (as suggested in the thread above) and I get `user-error: No linked CIDER sessions`.

Both functionalities used to work (`cider-find-var` and eval-ing, in a buffer that belongs to a dependency of the project), in fact I have used the eval in order to "inject" code into dependencies by turning off read only mode in the buffer, changing the code slightly (mostly to add some logging) and doing `cider-load-buffer`.

Could this be a regression connected to the stricter concept of CIDER of what buffer is related to which REPL connection?

**Comment by stathissideris** [comment]
Same goes for `cider-toggle-trace-var` -- it no longer works from within source files of dependencies:

```
user-error: ‘cider-toggle-trace-var’ requires the nREPL op "toggle-trace-var".  Please, install (or update) cider-nrepl 0.18.0 and restart CIDER
```

**Comment by vspinu** [comment]
Most likely your dependency is not detected. Would be good to know the reason. See if `C-c C-s C-i` displays the session which you need. You can always link current project to any session with `C-c C-s l` but this should work smoothly for the dependencies. The relevant code is in `sesman-friendly-session-p` method of cider.  Is this lein? There is a known issue with clj-cli classpath entries (#2533).

**Comment by manuel-uberti** [comment]
I haven't experienced this in the last week, so I'm not sure whether you want keep this open or not. 

Feel free to close it. :)

**Comment by vspinu** [comment]
@stathissideris, right. I understood your problem, I just was hoping that you could debug `sesman-friendly-session-p` in `cider-connection.el` and figure out why your dependency is not detected.

**Comment by cch1** [comment]
I am seeing the same behavior as @stathissideris

**Comment by manuel-uberti** [comment]
Is this still an issue for anyone? I haven't seen the error popping up recently, so I was wondering if this can be closed.

**Comment by stathissideris** [comment]
It has worked correctly for me in the more recent versions.
