### ISSUE TITLE
Question: opening *cider-error* in the same-window 

### ISSUE THREAD

**Issue by carlosgeos** [clojure-emacs/cider#2536]
Hello everyone !

I have many buffer names included in `display-buffer-alist`, for example:

```elisp
("\\*Help\\*" display-buffer-same-window)
```

so that buffers with that name open in the same window. However:

```elisp
(cider-error-buffer display-buffer-same-window)
```
(I've tried with the string "\\*cider..." too and other regexes)

doesn't seem to work. Is there something special about the way cider opens up the cider-error buffer ?  Could `cider-auto-select-error-buffer` help ?

**Comment by mallt** [comment]
You should be able to force the display of cider popups in the same window by setting the `pop-up-windows` variable to `nil` (this will cause [the inhibit-same-window entry](https://github.com/clojure-emacs/cider/blob/master/cider-popup.el#L71) to be nil).

This change won't be restricted to the cider-error buffer however, all cider popups will be affected by this. To control the cider-error buffer specifically I think a new customization variable would have to be added.

**Comment by carlosgeos** [comment]
Yep, that works thanks !

I can make pop ups the exception by using `display-buffer-pop-up-window` as well (it ignores `pop-up-windows`)
