### ISSUE TITLE
bug in use of `sesman-friendly-session-p`

### ISSUE THREAD

**Issue by daaku** [clojure-emacs/cider#2538]
## Expected behavior

Opening a file in an already running emacs session with `emacsclient` should work as expected.

## Actual behavior

Instead, we get an error, here's the stack trace:

```
compare-strings(nil 0 0 "/Users/naitik/workspace/posh-todo/src/cljs/posh_todo/client.cljs" 0 0 nil)
string-prefix-p(nil "/Users/naitik/workspace/posh-todo/src/cljs/posh_todo/client.cljs")
#f(compiled-function (path) #<bytecode 0x443e9331>)(nil)
#f(compiled-function (elt) #<bytecode 0x443e9345>)(nil)
mapc(#f(compiled-function (elt) #<bytecode 0x443e9345>) (nil "target/" "test/" "test/" "src/" "src/" nil))
seq-do(#f(compiled-function (elt) #<bytecode 0x443e9345>) (nil "target/" "test/" "test/" "src/" "src/" nil))
seq-find(#f(compiled-function (path) #<bytecode 0x443e9331>) (nil "target/" "test/" "test/" "src/" "src/" nil))
#f(compiled-function (system session) #<bytecode 0x40c70499>)(CIDER ("workspace/sb:localhost:55261" #<buffer *cider-repl workspace/sb:localhost:55261(clj)*>))
apply(#f(compiled-function (system session) #<bytecode 0x40c70499>) CIDER ("workspace/sb:localhost:55261" #<buffer *cider-repl workspace/sb:localhost:55261(clj)*>))
sesman-friendly-session-p(CIDER ("workspace/sb:localhost:55261" #<buffer *cider-repl workspace/sb:localhost:55261(clj)*>))
#f(compiled-function (ses) #<bytecode 0x443e92a1>)(("workspace/sb:localhost:55261" #<buffer *cider-repl workspace/sb:localhost:55261(clj)*>))
#f(compiled-function (elt) #<bytecode 0x443e92d9>)(("workspace/sb:localhost:55261" #<buffer *cider-repl workspace/sb:localhost:55261(clj)*>))
mapcar(#f(compiled-function (elt) #<bytecode 0x443e92d9>) (("workspace/sb:localhost:55261" #<buffer *cider-repl workspace/sb:localhost:55261(clj)*>)))
#f(compiled-function (function sequence) #<bytecode 0x40affe6f>)(#f(compiled-function (elt) #<bytecode 0x443e92d9>) (("workspace/sb:localhost:55261" #<buffer *cider-repl workspace/sb:localhost:55261(clj)*>)))
apply(#f(compiled-function (function sequence) #<bytecode 0x40affe6f>) #f(compiled-function (elt) #<bytecode 0x443e92d9>) (("workspace/sb:localhost:55261" #<buffer *cider-repl workspace/sb:localhost:55261(clj)*>)) nil)
seq-map(#f(compiled-function (elt) #<bytecode 0x443e92d9>) (("workspace/sb:localhost:55261" #<buffer *cider-repl workspace/sb:localhost:55261(clj)*>)))
seq-filter(#f(compiled-function (ses) #<bytecode 0x443e92a1>) (("workspace/sb:localhost:55261" #<buffer *cider-repl workspace/sb:localhost:55261(clj)*>)))
sesman--friendly-sessions(CIDER sort)
sesman-current-session(CIDER)
cider-repls(cljs nil)
cider-current-repl()
cider-connected-p()
redisplay_internal\ \(C\ function\)()
```

## Steps to reproduce the problem

1. Start emacs with `(server-mode t)`
2. Open a file in project A
3. `cider-jack-in` and start a repl
4. Go to the terminal and open a file from project B using `emacsclient`

### CIDER version information

```
;; CIDER 0.19.0snapshot (package: 20181210.1201), nREPL 0.5.2
;; Clojure 1.10.0-RC4, Java 11.0.1
```

### Build Tool

The `cider-preferred-build-tool` for the project was `clojure-cli` which is how the repl was started by cider.

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31

### Operating system

macOS 10.14.1

**Comment by daaku** [comment]
Oh, I realized I wasn't clear -- this only happens when the repl for a project is running. Otherwise things work as expected. It's the logic trying to find the friendly session that seems to have a bug, which I'm guessing has an early return when there isn't a session running at all.

**Comment by vspinu** [comment]
Looks like a duplicate of #2533.

**Comment by genmeblog** [comment]
I have exactly the same problem. When I try to access any file from the other project I'm getting this error and Cider looks ruined. Every evaluation results this error. The only help is to restart Emacs.

Setup on Cygwin. CIDER 0.20.0snapshot (package: 20190102.812), nREPL 0.5.3, Clojure 1.10.0, Java 1.8.0_66. Emacs 26.1.

What is important in my case. JVM sees paths in Windows style. Emacs/Cider uses Unix style. 
Maybe this is the case?

**Comment by genmeblog** [comment]
ok found that `(mapcar #'file-name-directory)` returns list of `nil`. `classpath` is full of Windows paths but Cygwin version of `file-name-directory` expects Unix paths... Should I issue a separate ticket for that. 
Cider has already function `cider-to-nrepl-filename-function` which takes care of Cygwin case and converts paths to proper ones. It is unused now.
