### ISSUE TITLE
Debug bindings with evil-mode

### ISSUE THREAD

**Issue by Vurp** [clojure-emacs/cider#2540]
**Is your feature request related to a problem? Please describe.**

I use cider in combination with evil-mode. It works fine in general
but no debug bindings will work when combining evil-mode (normal
state) with cider-debug.

**Describe the solution you'd like**

I am fine with some configuration in my init file, its just that I
have not figured out how to do so yet.

**Describe alternatives you've considered**

As a workaround I temporarily disable evil-mode (or switch to
emacs-state using evil-mode terminology) when using cider-debug.

**Additional context**

The following workaround works for edebug-mode but not with
cider-debug:

```emacs-lisp
(add-hook 'edebug-mode-hook 'evil-normalize-keymaps)
```

I am sorry if this is the wrong place to ask for help, but I thought
this is an issue others may have had and I thought it could be good to
collect everything related to cider in the issue tracker.

**Comment by rpkarlsson** [comment]
Sounds to me like evil-collection could be what you're looking for?
https://github.com/emacs-evil/evil-collection/blob/master/evil-collection-cider.el#L99
https://github.com/emacs-evil/evil-collection

**Comment by Vurp** [comment]
Thank you! Yes evil-collection is certainly another workaround. I did figure out how to do it without external packages:

    (evil-make-intercept-map cider--debug-mode-map 'normal)
