### ISSUE TITLE
File `autoload.el`, needed to generate autoloads, is missing.

### ISSUE THREAD

**Issue by zilti** [clojure-emacs/cider#2545]
File `autoload.el` is missing from the master branch, making it impossible to properly install cider manually. This also makes it impossible to install via el-get.

Why Cask is needed to call a simple elisp file is beyond me, as well...

**Comment by bbatsov** [comment]
That file is auto-generated when installing via `package.el`. I'm not familiar with `el-get`, but I assume it should generate autoloads automatically as well.
