### ISSUE TITLE
[Discuss] How to let CIDER make use of Clojure docker image?

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#2552]
This is a discuss, but in order to keep records down, and might help other people. So I record it here. I know there is a channel `#cider/#emacs` on Slack. I will post this link over there.

I want to use different version and environment of Clojure. There is an official Clojure Docker image. https://hub.docker.com/_/clojure

I'm thinking how to use Clojure image's binary and REPL in Emacs, and CIDER.

There are some ways can access Docker image as I know:

- running container which started Clojure REPL, user can attach it with Emacs package `docker.el`.
- use Emacs package `docker-tramp.el` and `docker.el` to access clojure container binary commands like `clojure`, `clj` etc. So that Emacs use them as executable command path. Like CIDER has customize option `cider-clojure-cli-command`. I tried following, but failed.
```elisp
(add-to-list 'exec-path "/docker:clojure:/usr/local/bin/")
(setq cider-clojure-cli-command "/docker:clojure:/usr/local/bin/clojure")
```

- run the clojure image to expose the ip:port to host system. So that Emacs can access the Docker container just like host system local. I don't know how to do that yet.

Anyone have suggestion and solution? Welcome to add. (This might could add to Wiki, when the discussion is almost) Thanks for viewing.

**Comment by stardiviner** [comment]
I found CIDER has an variable to keep connection records. Could be used in upper mentioned case.

Like this:
```elisp
(setq cider-known-endpoints
  '(("host-a" "10.10.10.1" "7888")
    ("host-b" "7888")))
```

**Comment by stardiviner** [comment]
- use CIDER remote host SSH support to SSH into Docker container
- Use CIDER transparent TRAMP support to use Emacs package `docker-tramp.el` to open files on container, then `cider-jack-in-*`, CIDER could transparently handling this.

**Comment by stardiviner** [comment]
> Dependencies are installed into volumes. So Emacs can't have access to them.

I'm confused on this. Dependencies are installed into volumes, but Emacs CIDER connect to container started `clojure -Acider` alias. So if `clojure -Acider` should be able to access all dependencies in container. Add project dependencies into a container `deps.edn` file?

Can Docker access host system's `.m2/` dependencies? So that Docker will be a bridge between Emacs CIDER and host system dependencies.

**Comment by zilti** [comment]
We have Maven and tools like Boot and Leiningen, why on earth would Docker be even necessary here? Just because it's trendy?

**Comment by darkleaf** [comment]
@stardiviner 
> I'm confused on this.

REPL is started inside a docker container. This process have access to container file system 
with container related paths. Lock at volumes section:

```yml
    volumes:
      - ".:${PWD}:cached" # cached - MacOS option
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
```

`$PWD` is `/User/darkleaf/projects/project` for example. So the project sources are
available in the same path inside container . 
It's make sense. REPL can send to Emacs some path and that path is container related. 
Emacs can't get a file on host file system if paths are inconsistent.
So I use `${PWD}`.

Later I used to mount `.m2` and `.gitlibs` from host file system. 
I use Docker for Mac and it's host volumes are slow.  So I switched to container volumes.

**Comment by stardiviner** [comment]
@darkleaf I see. Thanks.

@zilti switch Java version, Clojure version is simpler on Docker? and It's cleaner. Easy to package image then share, simpler to reproduce environment issue. I admit Leiningen and Boot (I have not use it myself) is great. Still thanks for your advice.

**Comment by bbatsov** [comment]
Seems you've sorted this out, so I'll close this ticket.
