### ISSUE TITLE
CIDER does not honor `:extra-paths` setting in deps.edn.

### ISSUE THREAD

**Issue by johanatan** [clojure-emacs/cider#2554]
## Expected behavior
CIDER honors :extra-paths in deps.edn.

## Actual behavior
CIDER does not honor :extra-paths in deps.edn.

## Steps to reproduce the problem
1) Add an `:extra-paths` section to your deps.edn.
2) Jack into the project with CIDER.
3) M-x cider-classpath.
4) Notice that the classpath does not include the paths you referenced in 1).

## Environment & Version information
Java 18.0_45

### CIDER version information
0.18.0

### Emacs version
25.1.1

### Operating system
Mac OS X

**Comment by bbatsov** [comment]
CIDER simply runs the `clj` script, so it does what `clj` would do.
