### ISSUE TITLE
Paths processing on Cygwin environment

### ISSUE THREAD

**Issue by genmeblog** [clojure-emacs/cider#2556]
## Expected behavior
This bug is connected to the #2538 but after a little bit of debug I (probably) found the main reason for my case.

CIDER/nREPL should work on Cygwin or other mixed environment with mixed path conventions (Windows vs Unix).
It wasn't a problem till current version (0.19.0)

## Actual behavior
After switching to sesman it looks like conversion between cygwin paths and window paths are missed. 
This also can be general issue in other cases where paths are processed jointly by nREPL and Cider.

Emacs and Cygwin are using unix-like paths ie. /home/user/file etc. JVM and nrepl are using Windows paths. So, because of that this line fails: https://github.com/clojure-emacs/cider/blob/v0.19.0/cider-connection.el#L438
`file-name-directory` expects unix-like-path but `classpath` is filled by Windows paths

Cygwin version of Emacs has two functions `cygwin-convert-file-name-to-windows` and `cygwin-convert-file-name-from-windows`. The former is already wrapped in Cider (`cider-to-nrepl-filename-function` in `cider-eval.el`)

## Steps to reproduce the problem
Reproducing is similar to #2538 
Under Cygwin
1. run `lein repl`
2. run Emacs
3. open any clj file from the project
4. `cider-connect`
5. open any clj file from different project (even opening ~/.lein/profiles.clj causes a problem)
6.  try to evaluate anything from your project (constantly calls `sesman-friendly-session-p` and fails)

### CIDER version information

```
;; CIDER 0.20.0snapshot (package: 20190102.812), nREPL 0.5.3
;; Clojure 1.10.0, Java 1.8.0_66
```

### Lein/Boot version

Leiningen 2.8.3 on Java 1.8.0_66 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-unknown-cygwin, GTK+ Version 3.22.28) of 2018-05-28

### Operating system

Windows 10, Cygwin

**Comment by genmeblog** [comment]
I use following workaround to have it working. In function `sesman-friendly-session-p`  I replace

```
(mapcar #'file-name-directory)
```

with

```
(mapcar #'cygwin-convert-file-name-from-windows)
(mapcar #'file-name-directory)
(mapcar #'cygwin-convert-file-name-to-windows)
```

This is of course not desired solution.

**Comment by genmeblog** [comment]
any news on this?

**Comment by bbatsov** [comment]
Unfortunately no. I've been pretty short on time lately and I guess the same goes for @vspinu as well.

**Comment by vspinu** [comment]
Yerh. I was snowballed with some personal stuff in the past 3-4 months :(

@genmeblog I am not using cygwin but from your description, it seems that the right solution would be to transform the classpath to unix-like paths not the other way around. Either directly in `cider-sync-request:classpath` or as part of sesman-firendly-session-p. 

Would the following do it?

```clj

(defvar cider-from-nrepl-filename-function
  (with-no-warnings
    (if (eq system-type 'cygwin)
        #'cygwin-convert-file-name-from-windows
      #'identity))
  "Function to translate nREPL namestrings to Emacs filenames.")


(defun cider-sync-request:classpath ()
  "Return a list of classpath entries."
  (cider-ensure-op-supported "classpath")
  (thread-first '("op" "classpath")
    (cider-nrepl-send-sync-request)
    (nrepl-dict-get "classpath")
    (mapcar cider-from-nrepl-filename-function)))
```

**Comment by vemv** [comment]
https://github.com/clojure-emacs/cider/releases/tag/v0.23.0 (released some months later after this issue was reported) introduced `cider-path-translations`. It's most popular for Docker usage, but it seems to fit perfectly for the described use case.

As of CIDER master (soon to be 1.8.0), cider-path-translations are used within 'friendly session' calculation.

For that reason (and also due to age), I'll close this issue. But do feel free to continue the conversation if the suggested approach didn't work.

Cheers - V
