### ISSUE TITLE
cider nrepl version mismatch: 0.2.12 vs 0.4.4

### ISSUE THREAD

**Issue by ckonstanski** [clojure-emacs/cider#2559]
When trying to start cider with `cider-jack-in-clojurescript` I get the following error. It only started happening very recently. I upgraded java on my system since the last time cider worked from an older 1.8 version to the new one listed below. I upgraded cider with `list-packages`, but no change in behavior.

WARNING: CIDER requires nREPL 0.4.4 (or newer) to work properly
         More information.
WARNING: CIDER requires cider-nrepl to be fully functional. Many things will not work without it!
         More information.

I followed the "More Information" link to here:
https://docs.cider.mx/en/latest/troubleshooting/#cider-complains-of-the-cider-nrepl-version

It said to remove all references to nrepl in my project files. I did that. No change.

I cleaned out my .m2 directory and did a `lein clean` / `lein cljsbuild once` from a shell. This pulled in nrepl 0.4.4 and 0.5.3. Cider still throws the error.

See cider version information below for an odd reference to nrepl 0.2.12. Since I removed all references to nrepl from my project, I don't understand why cider reports this version and then says it doesn't like it.

### CIDER version information
;; CIDER 0.20.0snapshot (package: 20190105.745), nREPL 0.2.12
;; Clojure 1.10.0, Java 1.8.0_191

### Lein/Boot version
Leiningen 2.8.1 on Java 1.8.0_191 OpenJDK 64-Bit Server VM

### Emacs version
app-editors/emacs-26.1-r3:26

### Operating system
4.20.0-gentoo
Gentoo Base System release 2.6

**Comment by bbatsov** [comment]
You need Leiningen 2.8.3.

**Comment by ckonstanski** [comment]
That solved it.
