### ISSUE TITLE
Cider code completion with company mode hangs badly.

### ISSUE THREAD

**Issue by wusticality** [clojure-emacs/cider#2562]
## Expected behavior

When referencing imported java classes in Clojure using `cider` and `company-mode`, candidates should show up responsively.

## Actual behavior

Typing each character hangs for several seconds while updating the candidates list. Each time, I get the following message in the `*Messages*` buffer:

`Error running timer ‘company-echo-show’: (error "Company: backend company-capf error \"Sync nREPL request timed out (op eldoc ns game.window symbol GLFW/glfwInit)\" with args (meta GLFW/glfwInit)")`

## Steps to reproduce the problem

Create a new project with `Lein`, and grab `LWJGL` version `3.2.1`. Try to import a module like `org.lwjgl.glfw.GLFW`. With any luck, you will see delays of several seconds with each character press.

### Company version

`0.9.9`

### CIDER version information

```
;; CIDER 0.20.0snapshot (package: 20190107.2136), nREPL 0.5.3
;; Clojure 1.9.0, Java 1.8.0_121
```

### Lein/Boot version

`Leiningen 2.8.3 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM`

### Emacs version

`GNU Emacs 26.1 (build 1, x86_64-apple-darwin18.0.0) of 2018-08-19`

### Operating system

`OSX Mojave`

Note that this is a new MBP with 32 gigs of ram, everything else is fast.

**Comment by dpsutton** [comment]
```

**Comment by bbatsov** [comment]
Can you paste the related info from `*nrepl-messages*`? (see http://www.cider.mx/en/latest/troubleshooting/#missing-nrepl-messages-buffer if you don't have it)

**Comment by wusticality** [comment]
I started a fresh `Emacs` to try and keep the log short, you can see the errors at the end. I've uploaded it as a file as it's 5k or so lines with the errors expanded. Here's the log:

[nrepl-messages.log](https://github.com/clojure-emacs/cider/files/2735455/nrepl-messages.log)

Thanks, hope this helps!

**Comment by cichli** [comment]
I think there is a linking issue with `liblwjgl.dylib`. Could you try running a plain `lein repl` in your project and evaluate the following form twice?

```clojure
(Class/forName "org.lwjgl.glfw.GLFW")
```

It looks like what is happening is that the eldoc middleware ultimately calls `Class/forName` on this class. The first time, an `UnsatisfiedLinkError` is thrown (implying the linking issue mentioned above). Further calls to `Class/forName` on this class result in a `NoClassDefFoundError` being thrown.


First call:
```
(<--
  id         "7"
  session    "c3e5de24-4b8f-48ac-a510-962e9d70a0fa"
  time-stamp "2019-01-08 00:44:05.266156000"
  err        "[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
ERROR: Unhandled REPL handler exception processing message {:op eldoc, :ns game.window, :symbol GLFW, :session c3e5de24-4b8f-48ac-a510-962e9d70a0fa, :id 23}
"
)
(<--
  id         "7"
  session    "c3e5de24-4b8f-48ac-a510-962e9d70a0fa"
  time-stamp "2019-01-08 00:44:05.268269000"
  err        "java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
	at org.lwjgl.system.Pointer.<clinit>(Pointer.java:28)
	at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:673)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at cider.inlined_deps.orchard.v0v4v0_20190104v162910_9.orchard.java$class_info_STAR_$fn__8313.invoke(java.clj:164)
```

Subsequent calls:
```
(<--
  id         "7"
  session    "c3e5de24-4b8f-48ac-a510-962e9d70a0fa"
  time-stamp "2019-01-08 00:44:05.350936000"
  err        "ERROR: Unhandled REPL handler exception processing message {:op eldoc, :ns game.window, :symbol GLFW, :session c3e5de24-4b8f-48ac-a510-962e9d70a0fa, :id 25}
"
)
(<--
  id         "7"
  session    "c3e5de24-4b8f-48ac-a510-962e9d70a0fa"
  time-stamp "2019-01-08 00:44:05.352491000"
  err        "java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at cider.inlined_deps.orchard.v0v4v0_20190104v162910_9.orchard.java$class_info_STAR_$fn__8313.invoke(java.clj:164)
```


`UnsatisfiedLinkError` and `NoClassDefFoundError` are both subclasses of `LinkageError`. In `orchard.info/class-info` we only catch `Exception`s. I will open a PR there 

The eldoc errors themselves are due to `orchard.info/class-info` blowing up trying to resolve `org.lwjgl.glfw.GLFW`. It's only catching `Exception` when it should also apparently catch (at least) `LinkageError` and `NoClassDefFoundError`. The former is thrown the first time we try to initialize the class; the latter is thrown every subsequent attempt. I will open a PR there to address this.

See https://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.2 for a far more exhaustive discussion of what is actually going on during class loading/initialisation.

**Comment by cichli** [comment]
Didn't mean to close this automatically like that; I'll reopen until the fix has made its way downstream.

**Comment by wusticality** [comment]
Hey @cichli, I'm so glad that you found the problem! I've attached the log that you requested below:

[forName.log](https://github.com/clojure-emacs/cider/files/2747309/forName.log)

**Comment by cichli** [comment]
Thanks for the quick response. We can fix the hanging in CIDER by catching those `LinkingError`s, but I think there is still an issue with your project. You need to do one of the following suggested in the error message:
```
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
```
But you might find more useful help about this on the LWJGL issue tracker. I am just guessing at this point :-).

**Comment by wusticality** [comment]
Hey @cichli / @bbatsov, do you know when this change will make it to `melpa` (if not already)? Just pulled all the latest packages but the issue seems to remain, just trying to make sure I have this change locally.
