### ISSUE TITLE
cider jack-in fails with Symbol’s function definition is void: record

### ISSUE THREAD

**Issue by bumbker** [clojure-emacs/cider#2573]
Expected behavior 
 launch cider repl buffer 

 Actual behavior   
fails with:  Symbol’s function definition is void: record

Steps to reproduce the problem
M-x cider-jack-in

Environment & Version information
CIDER version information
0.20.0

Include here the version string displayed when
CIDER's REPL is launched.

[nREPL] Starting server via /home/ron/bin/lein update-in :dependencies conj \[nrepl\ \"0.5.3\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.20.0\"\] -- repl :headless :host localhost...
[nREPL] server started on 44265
[nREPL] Establishing direct connection to localhost:44265 ...
[nREPL] Direct connection to localhost:44265 established
error in process filter: nrepl-start-client-process: Symbol’s function definition is void: record
error in process filter: Symbol’s function definition is void: record
Emacs version
"GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21)
 of 2017-09-22, modified by Debian"

Operating system
Linux Mint 19

**Comment by bbatsov** [comment]
Hmm, if I had to guess I’d speculate that you might have a syntax error in the project you’re starting CIDER in. Can this be the case?

**Comment by cichli** [comment]
> Hmm, if I had to guess I’d speculate that you might have a syntax error in the project you’re starting CIDER in. Can this be the case?

`Symbol’s function definition is void: record` is an elisp error though, right?

@bumbker could you do `M-x toggle-debug-on-error` and try again, then paste the resulting stacktrace here?

**Comment by bbatsov** [comment]
Ah, yeah. It’s a elisp error of course. My bad!

**Comment by bumbker** [comment]
Ok I did M-x toggle-debug-on-error and got this:
Debugger entered--Lisp error: (void-function record)
  record(queue nil nil)
  nrepl-start-client-process("localhost" 44041 #<process nrepl-server> #[257 "\301\300!\207" [(:project-dir "~/clojure-noob/" :jack-in-cmd "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost" :host "localhost" :port 44041 :project-dir "~/clojure-noob/" :server #<process nrepl-server> :server-command "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost" :repl-init-function nil :repl-type clj :session-name nil) cider-repl-create] 3 "\n\n(fn _)"])
  cider-nrepl-connect((:project-dir "~/clojure-noob/" :jack-in-cmd "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost" :host "localhost" :port 44041 :project-dir "~/clojure-noob/" :server #<process nrepl-server> :server-command "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost" :repl-init-function nil :repl-type clj :session-name nil))
  cider-connect-sibling-clj((:project-dir "~/clojure-noob/" :jack-in-cmd "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost") #<buffer *nrepl-server ~/clojure-noob:localhost*>)
  #[257 "\301\300\"\207" [(:project-dir "~/clojure-noob/" :jack-in-cmd "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost") cider-connect-sibling-clj] 4 "\n\n(fn SERVER-BUFFER)"](#<buffer *nrepl-server ~/clojure-noob:localhost*>)
  nrepl-server-filter(#<process nrepl-server> "nREPL server started on port 44041 on host localhost - nrepl://localhost:44041\n")

**Comment by bumbker** [comment]
now i'm getting this one instead
user-error: ‘cider-jack-in’ requires the nREPL op "classpath" (provided by cider-nrepl)
I'll try reinstalling everything and get back to you

**Comment by bumbker** [comment]
reinstalled and did M-x toggle-debug-on-error M-x cider-jack-in and got this
Debugger entered--Lisp error: (void-function record)
  record(queue nil nil)
  nrepl-start-client-process("localhost" 41399 #<process nrepl-server> #[257 "\301\300!\207" [(:project-dir "~/clojure-noob/" :jack-in-cmd "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost" :host "localhost" :port 41399 :project-dir "~/clojure-noob/" :server #<process nrepl-server> :server-command "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost" :repl-init-function nil :repl-type clj :session-name nil) cider-repl-create] 3 "\n\n(fn _)"])
  cider-nrepl-connect((:project-dir "~/clojure-noob/" :jack-in-cmd "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost" :host "localhost" :port 41399 :project-dir "~/clojure-noob/" :server #<process nrepl-server> :server-command "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost" :repl-init-function nil :repl-type clj :session-name nil))
  cider-connect-sibling-clj((:project-dir "~/clojure-noob/" :jack-in-cmd "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost") #<buffer *nrepl-server ~/clojure-noob:localhost*>)
  #[257 "\301\300\"\207" [(:project-dir "~/clojure-noob/" :jack-in-cmd "/home/ron/bin/lein update-in :dependencies conj \\[nrepl\\ \\\"0.6.0\\\"\\] -- update-in :plugins conj \\[cider/cider-nrepl\\ \\\"0.21.1\\\"\\] -- repl :headless :host localhost") cider-connect-sibling-clj] 4 "\n\n(fn SERVER-BUFFER)"](#<buffer *nrepl-server ~/clojure-noob:localhost*>)
  nrepl-server-filter(#<process nrepl-server> "nREPL server started on port 41399 on host localhost - nrepl://localhost:41399\n")

**Comment by bumbker** [comment]
then after Toggle out of debug on error I got the other again
user-error: ‘cider-jack-in’ requires the nREPL op "classpath" (provided by cider-nrepl)
then I restarted Emacs and tried cider-jack-in and got the original:
error in process filter: Symbol’s function definition is void: record

**Comment by bumbker** [comment]
Incidintly I'm following instructions in Clojure for the Brave and True book except my Cider is from this in my .emacs.d init file: 
(add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)

**Comment by dpsutton** [comment]
Did you install this from the repo that Brave and True has online? It contains compiled elc files from 4 years ago. I've seen issues with queue in particular that the bytecode has changed over the years. These problems occur when someone updates their emacs version but attempts to use the same byte compiled code.

Can you wipe out any and all traces of CIDER from elpa and then install it in the normal way with `m-x package-install [ret] CIDER`? This--i think-- should solve your woes.

**Comment by bumbker** [comment]
Also when I restarted emacs before (which reinstalled cider) It warned me about the record function not defined.

**Comment by bumbker** [comment]
Nope  I did what you said and still got:
error in process filter: Symbol’s function definition is void: record
when you say wipe out all traces of cider do you mean in archives too?

**Comment by bumbker** [comment]
Never mind I've discovered prelude now.  Very nice.  Installed cider and it works. Where's the .el file where
I can increase the font size?

**Comment by bbatsov** [comment]
Any file you put under `personal` will do.
