### ISSUE TITLE
Export documentation as epub / pdf

### ISSUE THREAD

**Issue by gypsydave5** [clojure-emacs/cider#2574]
**Is your feature request related to a problem? Please describe.**

When I click on either of the export options for PDF or epub on the documentation, it exports a five-page document.

**Describe the solution you'd like**

Make the epub/epub export work - somehow. I'll take a look at it myself.

**Describe alternatives you've  #considered**

Make it so it doesn't offer the option to export the documentation for now.

**Additional context**

May be related to #1977

**Comment by bbatsov** [comment]
I guess you’ve hit some upstream bug with readthedocs. Unfortunately their support for MkDocs is pretty basic/flaky. I hope that one day we’ll move over the docs to something more flexible like AsciiDoc + Antora (that’s what powers nREPL.org), but that’s a lot of work and I consider it a low priority. If you’d like to tackle this or debug the problem with RTD, that’d be great.

**Comment by bbatsov** [comment]
It seems that RTD simply doesn't support exports when you're using MkDocs. The documents you download are simply stubs from when the accounts was created and was using Sphinx by default (which supports this).
