### ISSUE TITLE
Documentation bug about slack channel

### ISSUE THREAD

**Issue by rnikander** [clojure-emacs/cider#2584]
Documentation says: 

> We've got an official Clojurians Slack - #cider. This is usually be best way to get a handle on some of the maintainers and interact with other CIDER users. The channel is very active!

(https://cider.readthedocs.io/en/latest/about/support/)

But if you follow the link to https://clojurians.slack.com, the page says:

> Don't have an account on this workspace yet? Contact the workspace administrator for an invitation

If the docs suggest people use slack, then they should tell how get a login to use slack.

**Comment by dpsutton** [comment]
good point!

If you need an invite you can go here: [https://clojurians.herokuapp.com/](https://clojurians.herokuapp.com/) 

but thanks for this suggestion either way!

**Comment by dpsutton** [comment]
ps, would love a PR with some verbiage of how to improve it for your fellow developers if you are interested.

https://github.com/clojure-emacs/cider/blob/master/doc/about/support.md is the file that site is based on

**Comment by rnikander** [comment]
Here it is. I simply added your line to the relevant paragraph. Hopefully I did the PR right. It's a been a long time (if ever) since I created a PR for another repository. 

https://github.com/clojure-emacs/cider/pull/2585
