### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2592]
Mostly a reminder to cut a new release targeting nREPL 0.6. Seems there are no blocking issues and we can move forward with the release, but that decision will be up to @cichli. 

There are a couple of open PRs that might be nice to include in the next release, but I don’t think that any of them is something really important, so we might play it safe and just cut what we currently have.

**Comment by cichli** [comment]
Sure, I can cut a release this evening. Do you have a codename for the next development version?

**Comment by bbatsov** [comment]
It’s already there - New York.

**Comment by bbatsov** [comment]
My bad - the next dev version should be named Lima.

**Comment by cichli** [comment]
https://github.com/clojure-emacs/cider/releases/tag/v0.21.0 🎆 

GNU ELPA is down so the CI is failing. I'll run it again once it's back up.
