### ISSUE TITLE
Initial namespace not being set in the cider-repl after upgrade to 0.21.0

### ISSUE THREAD

**Issue by jsrodrigues** [clojure-emacs/cider#2593]
This is my Environment:
;; Connected to nREPL server - nrepl://localhost:63995
;; CIDER 0.21.0 (New York), nREPL 0.6.0
;; Clojure 1.10.0, Java 1.8.0_201
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;

Seems like with the upgrade from cider 0.20.0, the initial namespace is not being set

In my project.clj, I have 
  :main ^:skip-aot my.init.ns 
But, I still get dropped into the user ns in the cider repl.

I also tried
  :repl-options {:init-ns my.init.ns}

But that doesn't seem to work either

**Comment by cichli** [comment]
Thanks for the report, and sorry for the regression.
