### ISSUE TITLE
REPL corrupted after cider-jack-in-clj

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/cider#2600]
## Expected behavior

<kbd>C-c C-x j j</kbd> should show the REPL buffer with the banner and the prompt.

## Actual behavior

<kbd>C-c C-x j j</kbd> shows an empty REPL buffer:

![screenshot](https://user-images.githubusercontent.com/8199224/53323739-49e33400-38df-11e9-9e9d-1c1bb4159fab.png)

## Steps to reproduce the problem

- install latest CIDER from MELPA
- create a directory called `test-project`
- add a deps.edn file with this content:
```
{:deps {org.clojure/clojure {:mvn/version "1.10.0"}}
 :paths ["src"]}
```
- add a simple file `test-project/src/core.clj`:
```
(ns test-project.core)
```
- <kbd>C-c C-x j j</kbd>

### CIDER version information

CIDER 0.22.0snapshot (package: 20190222.2021)

### Environment information

```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2019-02-24

Repository revision: 975893b229072aa1b5565cc1a73987fa83ed5b21
Configured using:
--host=x86_64-debian-linux-gnu --with-modules

Emacs uptime: 23 minutes, 44 seconds
Colour theme: sanityinc-tomorrow-night
Operating system: Ubuntu 18.04.2 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.3
```

**Comment by manuel-uberti** [comment]
After further testing: using <kbd>M-x cider-repl-clear-buffer</kbd> brings the prompt back, so even though I'm not seeing the initial CIDER banner I can still work with the REPL.

**Comment by cichli** [comment]
Thanks for the detailed report! It looks like the contents of the buffer are scrolled out of view (your modeline says `(10,6)`) – recentering with `C-l` should bring it into view. This is almost definitely caused by dc80d871eeacdb1c37434c4b17f9af77968d4c22.

**Comment by mbuczko** [comment]
as mentioned on a slack, replacing following lines in cider-repl.el (in cider-repl-init function):
```
(when-let ((window (get-buffer-window)))
      (set-window-point window (point-max)))
```
with:
```
(recenter (- -1 (max 0 scroll-margin)))
```
solves the problem for me. it acutally mimicks pressing `C-l`.

**Comment by manuel-uberti** [comment]
Thank you, @cichli.
