### ISSUE TITLE
Option to not print Value for Spec assertion failures

### ISSUE THREAD

**Issue by mjmeintjes** [clojure-emacs/cider#2604]
**Is your feature request related to a problem? Please describe.**

I'm working with a big data structure, and when I have a spec assertion failure it hangs emacs and cider. 

I'm assuming that it is because of the Value: section of the *cider-error* buffer that is way to large.

**Describe the solution you'd like**

Have an option to not print the Value section of the Spec assertion failed  *cider-error* buffer, or hide the value row so that it is not printed, or limit it. 

Or, make it work with the configured print-fn.

**Describe alternatives you've considered**

- I've tried setting nrepl.middleware.print/*print-fn* to a custom fn, but it does not seem to have any effect on the stacktrace window.
- I've tried setting nrepl.middleware.caugh/*caught-fn* to a custom fn, but it does not seem to have any effect on the stacktrace window.
- Setting cider-show-error-buffer to nil solves the problem, but it means I dont get the cider error buffer anymore. This is what I'm currently doing.

**Additional context**
cider-version - CIDER 0.22.0snapshot

```
  (require '[clojure.spec.alpha :as s])
  (set! *print-length* 10)
  (s/check-asserts true)
  (s/assert int? (range 10000))
```
gives

*cider-error* buffer:
```
1. Unhandled clojure.lang.ExceptionInfo
   Spec assertion failed.

         Spec: #function[clojure.core/int?]
        Value: (0
                1
                2
                3
                4
                5
                6
....
                9999)

     Problems: 

         failed: int?
```

In the repl the following is printed:
```
(0 1 2 3 4 5 6 7 8 9 ...) - failed: int?
```

When I increase range to 1000000 it just hangs emacs.

**Comment by bbatsov** [comment]
This seems related to https://github.com/clojure-emacs/cider-nrepl/issues/609 I think it needs to be addressed in the stacktrace middleware, as we originally didn't account for such data appearing in the stackframes. //cc @cichli @jeffvalk
