### ISSUE TITLE
Support wrapping cider-*-command with env vars

### ISSUE THREAD

**Issue by RickMoynihan** [clojure-emacs/cider#2605]
**Is your feature request related to a problem? Please describe.**

It would be useful to be able to wrap a REPL started via `cider-jack-in` with some environment vars.  The various commands like`cider-lein-command` must be executables on the file system, so you can't set them to things like `"env FOO=bar BAR=baz lein"` which was my first instinct.

It would be great to be able to configure these env vars also via `.dir-locals.el`.  It's worth mentioning a workaround is to use `eval` and `setenv` in `.dir-locals.el` like this:

```elisp
((nil . ((eval . (progn (setenv "FOO" "bar")
                                   #... 
)))))
```

However this is problematic because `setenv` is side effecting not buffer/project-local, so if you run multiple projects they can stomp over each others settings.

**Describe the solution you'd like**

It would be nice to be able to set `lein-cider-command` etc to arbitrary command strings e.g. `"env FOO=bar BAR=baz lein`, so you can safely set these per project.  Though it's probably better doing this via a new option.

**Comment by vemv** [comment]
`cider-lein-command` (and Clojure CLI / etc equivalents) are defcustoms that you can alter globally or on a per-project basis (by using .dir-locals.el)

Since that is a good solution, and becase it's been 4+y , I'm closing this issue.

Cheers - V
