### ISSUE TITLE
Pretty Printer Errors when jacking in without cider-nrepl

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/cider#2608]
Discovered this behavior using [nippy](https://github.com/ptaoussanis/nippy). The middleware would erroneously report that it was using Clojure 1.5 rather than the 1.10 specified in the dev profile and would omit injecting cider-nrepl when jacking-in.

## Expected behavior

Starting up a project without cider-nrepl should not cause errors.

## Actual behavior

```elisp
(-->
  id                             "4"
  op                             "eval"
  session                        "e7c66316-10e8-4f7e-816e-0a75abb23603"
  time-stamp                     "2019-03-21 07:33:46.164452679"
  code                           "(clojure.core/apply clojure.core/require clojure.main/repl-requires)"
  column                         1
  content-type                   "true"
  file                           "*cider-repl clojure/nippy:localhost:46861(clj)*"
  inhibit-cider-middleware       "true"
  line                           10
  nrepl.middleware.print/options (dict ...)
  nrepl.middleware.print/print   "cider.nrepl.pprint/pprint"
  nrepl.middleware.print/quota   1048576
  nrepl.middleware.print/stream? "1"
)
(<--
  id                           "4"
  session                      "e7c66316-10e8-4f7e-816e-0a75abb23603"
  time-stamp                   "2019-03-21 07:33:46.264820002"
  nrepl.middleware.print/error "Couldn't resolve var cider.nrepl.pprint/pprint"
  status                       ("nrepl.middleware.print/error")
)
```
## Steps to reproduce the problem

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

Just crank up nippy as detailed above. Nippy specifies Clojure 1.5 in deps and 1.10 in the dev profile but the cider-nrepl plugin sees 1.5 and considers the Clojure version too low. This has been [fixed awaiting merge](https://github.com/clojure-emacs/cider-nrepl/pull/603). In the meantime, cider-nrepl is not injected leading to these unresolved vars relating to pretty printing.

### CIDER version information

;; CIDER 0.22.0snapshot, nREPL 0.6.0
;; Clojure 1.10.0, Java 1.8.0_201

**Comment by bbatsov** [comment]
I see a few potential solution for this:

* Bundling some default pprint function with nREPL
* Inlining it CIDER's code, as a fallback
* Disabling pretty-printing if the printer is not present

@cichli Any preferences?
