### ISSUE TITLE
Evaluationg forms does not advance output in the REPL window

### ISSUE THREAD

**Issue by mathpunk** [clojure-emacs/cider#2610]
## Steps to reproduce the problem

In a Clojure file, with the cider-repl buffer visible, use any of the `cider-send-...` functions, excluding the `...-focus` functions. I used a brand new project created with `lein new` and added no dependencies.

## Expected behavior
The form is evaluated; there is new output in the cider-repl buffer; the cursor remains where you were; and if the output extends past where the bottom of the window was, the new bottom of the window is the end of the new output

## Actual behavior
The form is evaluated; there is new output; the cursor remains. However, the window is unchanged. In particular, if the new output heads off the bottom of the window, the window stays fixed, and you can't see the new output until you switch to the repl and advance the cursor to the bottom yourself.

### CIDER version information

```
CIDER 0.22.0snapshot (package: 20190321.2129)
Clojure 1.10.0, Java 1.8.0_202 OpenJDK 64-Bit Server VM
```

### Lein/Boot version

`Leiningen 2.9.1`

### Emacs version

`GNU Emacs 26.1 (with spacemacs)`

### Operating system

`Linux 4.19.30-1-MANJARO`

**Comment by mathpunk** [comment]
I did not have luck with jr0cket's proposed `(add-hook 'cider-repl-mode-hook '(lambda () (setq scroll-conservatively 101)))` but maybe the solution is in the neighborhood.

**Comment by bbatsov** [comment]
We'll figure it out.

**Comment by bpiel** [comment]
@mathpunk Did you ever figure this out? thanks

**Comment by bpiel** [comment]
For posterity: I ended up putting this in my emacs config, which seems to work.

```
(define-key cider-repl-mode-map (kbd "C-c C-l")
  '(lambda ()
     (interactive)
     (cider-repl-clear-buffer)
     (setq-local scroll-conservatively 101)))
```
