### ISSUE TITLE
make CIDER support two dot operator methods completion

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#2612]
Now CIDER has already support methods completion for single dot operator. But it does not support for two dots operator yet.
Like this:
```clojure
(.. (java.util.Date.) |toString (|endsWith "2019"))
```
Here is an example where `|` is the place of point.

**Comment by bbatsov** [comment]
@alexander-yakushev Seems this is something that has to be tackled in `compliment`, right?

**Comment by alexander-yakushev** [comment]
I've opened an issue in Compliment.

**Comment by alexander-yakushev** [comment]
Tracked in alexander-yakushev/compliment#64.
