### ISSUE TITLE
cider-jack-in function definition is void

### ISSUE THREAD

**Issue by chris-dierdorff** [clojure-emacs/cider#2613]
cider doesn't show in list of available packages. It is listed in ~/.emacs.d/init.el.

**Comment by bbatsov** [comment]
How did you install it?

**Comment by chris-dierdorff** [comment]
I installed it from a link in the book Clojure for the Brave and True ( https://github.com/flyingmachine/emacs-for-clojure/ ). At this point, I've run package-refresh contents and package-install cider. These were both successful, however, I am getting the void function error when running cider-jack-in.

It's possible that I'm running the command incorrectly, however, I open emacs, then C-x f to open a core.clj file in my lein app. Then, i run cider-jack-in and get the error.

**Comment by xiongtx** [comment]
cc @flyingmachine

@chris-dierdorff Can you go to `cider.el` and `eval-buffer`? Is there any error?

**Comment by chris-dierdorff** [comment]
I opened cider.el in the emacs and ran M-x eval-buffer. I didn't get any errors or any other kind of info.

**Comment by bbatsov** [comment]
Well, I guess if it's an autoload generation problem you can either reinstall CIDER or just add `(require 'cider)` to Emacs config and this should address at least the jack-in part.
