### ISSUE TITLE
Red squiggly in source buffer is gone with Clojure 1.10

### ISSUE THREAD

**Issue by slipset** [clojure-emacs/cider#2614]
## Expected behavior
Whenever I do `C-c C-c` with a form that has an error, I get a red squiggly in my source buffer indicating where the error is. 
## Actual behavior
I’m not getting the red squiggly, but I get a rather friendly message in the `*cider-repl..*` buffer telling me that I have an error somewhere in my source file 
## Steps to reproduce the problem
Create a project with Clojure 1.10, jack-in, create a form with an error in it, evaluate it with `C-c C-c`. You will not have a red squiggly under the form with error, but you will get a message in the `*cider-repl ...*` buffer

## Environment & Version information
Any recent version of Cider, Clojure 1.10.

## Additional information 
The messages I get in the repl are: for 1.10
```
Syntax error compiling at (core.clj:10:3).
      Unable to resolve symbol: somthing in this context
```
Wheras for 1.9.0 it’s
```
CompilerException java.lang.RuntimeException: Unable to resolve symbol: somthing in this context, compiling:(/Users/erik/Documents/github.com/refactor-nrepl-ns-kw-bug/src/foo/core.clj:10:3)
``` 

So a good starting point would be to look at  this regex here:
https://github.com/clojure-emacs/cider/blob/master/cider-eval.el#L300

**Comment by bbatsov** [comment]
Yeah, you're right. That's broken because of the new message format.

**Comment by slipset** [comment]
So it seems like
```emacs-lisp
(defvar cider-compilation-regexp '("Syntax error compiling at (\\(.*?\\):\\([[:digit:]]+\\):\\([[:digit:]]+\\))"
				 1 2 3))
```
works (at least for me (on my computer)). This does, however pose the question of backwards compatibility. If we simply change `cider-compilation-regexp` to this regex, then people working with older clojure versions will loose the red squiggly. 

This leaves us with (at least) three options
1) Simply use this regex, and hope the population of devs using versions earlier than 1.10 is small and diminishing quickly
2) Make a monstrosity of a regex to cater for both
3) Make several entries in `compilation-error-regexp-alist-alist` and `compilation-error-regexp-alist`

I feel that my emacs-lisp-fu leaves me at 1), and I'd need very clear guidance if you want to go for 2) or 3)

**Comment by bbatsov** [comment]
Hmm, seems we dropped the ball on the original issue https://github.com/clojure-emacs/cider/issues/2443 I'll put it here for posterity as I shared some thoughts about solving the problem there.
