### ISSUE TITLE
Eval in buffer and pretty-print result in REPL as output

### ISSUE THREAD

**Issue by stathissideris** [clojure-emacs/cider#2617]
**Is your feature request related to a problem? Please describe.**

The workflow I’d like to try is typing long multi-line expressions in a .clj file and eval+pretty-print their results in the REPL where the results accumulate.

**Describe the solution you'd like**

I would like a function that is similar to `cider-pprint-eval-last-sexp-to-repl` but instead of inserting the result into the REPL as *input*, I would like it to be inserted as pretty-printed output instead. If the eval'ed expression is also added as if it was typed in the prompt of the REPL I think it would be even more usable (because then you'd see alternating input and output and it would be easier to follow what was executed and in what order) but I’d be happy with just the outputs.

**Describe alternatives you've considered**

I saw that something similar would be possible with getting the results in a popup buffer, but I prefer to see a “log” of results which accumulate.

**Additional context**

This mockup shows what the result of running this new command might look like. My cursor is on the left in `dev.clj`, and I've just ran the new command, which resulted in my s-exp being added as input in the REPL prompt and the result of the expression being pretty-printed just below.

![Screenshot 2019-03-29 at 15 20 06](https://user-images.githubusercontent.com/162007/55235452-3efd2580-5236-11e9-8e7f-1e67c0359708.png)

**Comment by paulojean** [comment]
I was planning to do this, but I realised that [`cider-insert-last-sexp-in-repl`](https://github.com/clojure-emacs/cider/blob/master/cider-mode.el#L269) already accepts an argument that will evaluate the sexp after sending it to the repl (resulting in something similar to what is shown in the screenshot).

**Comment by suvratapte** [comment]
Hi @bbatsov and @stathissideris ,

As @paulojean has mentioned, `C-u cider-insert-last-sexp-in-repl` already does what is requested in this issue.

Do we still want to have a separate function for doing this?
If yes, please take a look at this: https://github.com/suvratapte/cider/commit/c177120ff243e032ee6e120e46ac4cccefc07991#diff-3f8317548fccd07e43ee8e69be1b3171

Should I create a pull request with this?

**Comment by bbatsov** [comment]
I've added a small remark to your commit. In general it seems we need to have more of the special function behaviors added to menu bars and documented properly at docs.cider.mx.

**Comment by suvratapte** [comment]
Okay, I will do that. Thanks! :)

**Comment by stathissideris** [comment]
Hello again, `cider-insert-last-sexp-in-repl` does indeed do what I was asking about, but it leaves the REPL cursor in its original position. That means that after a few evaluations the screen gets completely filled and any new expressions and results move beyond the bottom of the frame. Is there any way to add `advice` some function in order to get the buffer to scroll as the results of `cider-insert-last-sexp-in-repl` get added to it? I tried `follow-mode` but it didn't seem to do the trick.

**Comment by holtzermann17** [comment]
Here's something that works for my current setup, you can modify it to suit your need; I can't say it's pretty!

```lisp
(defun cider-recenter (&rest args)
  (interactive)
  (other-frame 1)
  (goto-char (point-max))
  (recenter -2)
  (other-frame -1))

(define-key cider-mode-map (kbd "s-e")
  #'(lambda () (interactive)
     (advice-add 'make-progress-reporter :override (lambda (&rest args)))
     (save-window-excursion (cider-insert-last-sexp-in-repl 1))
     (cider-recenter)
     (advice-remove 'make-progress-reporter (lambda (&rest args)))))
 ```
![Screenshot from 2021-06-01 13-49-59](https://user-images.githubusercontent.com/179958/120326133-4b7edc00-c2e0-11eb-9f29-aef6d902d49d.png)

**Comment by Quezion** [comment]
For anyone reading through -- the above commit with `cider-insert-and-eval-last-sexp-in-repl` was never merged. You still need to make this customization in your own init.el.

Here's the user level code that worked for me to override the default `cider-eval-last-sexp` C-x C-e

```el
(defun cider-insert-and-eval-last-sexp-in-repl (&rest args)
  "Insert the expression preceding point in the REPL buffer and eval."
  (interactive)
  (cider-insert-in-repl (cider-last-sexp) t))

(define-key cider-mode-map (kbd "C-x C-e") #'cider-insert-and-eval-last-sexp-in-repl)
```
* Copied from upstream at [this gist](https://gist.github.com/Quezion/4e18ec42126c8810b7ef23d40a934ec7)
