### ISSUE TITLE
Cider debugger hangs on infinite lazy sequences

### ISSUE THREAD

**Issue by yuhan0** [clojure-emacs/cider#2621]
## Expected behavior
Using the debugger to step through intermediate forms which produce infinite lazy sequences should not cause Cider to hang indefinitely. 

## Actual behavior
The debugger attempts to realize the entire lazy sequence when displaying it, the user cannot continue past that point and has to interrupt the evaluation with `C-c C-b`.

## Steps to reproduce the problem
- Evaluate the form
```clojure
(let [n 5]
  #dbg
  (take (inc n) (repeat n)))
```
- Press `n` a couple of times when the debugger is activated to step past the intermediate forms
- Upon reaching the form `(repeat n)` which produces an infinite lazy sequence, it hangs indefinitely with no way to step past it to the finite result (via `take`)

### CIDER version information
```
;; CIDER 0.22.0snapshot (package: 20190331.2014), nREPL 0.6.0
;; Clojure 1.10.0, Java 12
```

### Lein/Boot version
-NA-
### Emacs version
26.1
### Operating system
OS X 10.14.4 "Mojave"

**Comment by Malabarba** [comment]
Odd. Cider generally avoids printing sequences indefinitely. It could be something in your config, or it could be some pretty-printing change on our side.

What do you see printed if you evaluate `(repeat 1)` with `C-x C-e`?

**Comment by yuhan0** [comment]
It displays a finite sequence of (1 1 1 1 ...) truncated at *print-length*.
All the cider-eval and cider-inspect commands work fine with infinite seqs, it's only the debugger which behaves this way.

**Comment by bbatsov** [comment]
Likely we forgot to pass some print params to the eval commands used by the debugger. This should be a relatively simple fix once someone gets to investigate the problem.
