### ISSUE TITLE
Cider REPL will print an infinite amout of data on return and freeze emacs

### ISSUE THREAD

**Issue by SlightlyCyborg** [clojure-emacs/cider#2624]
## Expected behavior
```
user> (generate-really-large-datastructure)
user> ["Lorem" "ipsum" "dolor" "sit" ... "id" "est" "aborum"] 
```
## Actual behavior
```
user> (generate-really-large-datastructure)
user> ["Lorem" "ipsum" "dolor" <emacs freezes>

```
## Steps to reproduce the problem
`user> (take 5000000 (repeatedly (fn [] "asdf")))`

**Comment by bbatsov** [comment]
What's your CIDER and nREPL versions? I can't imagine how you could be running into those problems if you're on CIDER (New York) and nREPL 0.6. See https://metaredux.com/posts/2019/04/01/new-york-new-york.html for details.

**Comment by bbatsov** [comment]
I can't reproduce this with the latest CIDER and nREPL. The result starts streaming and I easily interrupt it with `C-c C-c`.
