### ISSUE TITLE
NS aware command history

### ISSUE THREAD

**Issue by fhalde** [clojure-emacs/cider#2625]
**Have ns aware command history**

Whenever I do a `cider-repl-set-ns` back and forth, I'd really like to scroll over only those expressions that I ran when I was in the particular ns. It's kind of frustrating to go through all the unnecessary commands that I ran in a different ns which probably will not even work in the newer ns's that I go into

**Have a command history on per ns basis**

We can solve this issue had we kept a history of command on a per ns level

**Comment by bbatsov** [comment]
Implementing this won't be hard, but I'm not sure if many people want/need this behaviour. Frankly speaking - unless someone else tackles this, it's very unlikely it's happening any time soon.
