### ISSUE TITLE
Using cider-find-dwim to jump into functions ending with !/?

### ISSUE THREAD

**Issue by gsnewmark** [clojure-emacs/cider#2629]
When you use `cider-find-dwim` over a var ending with `!`/`?` it doesn't jump into it right away, but prompts user to input full var name in a separate minibuffer prepopulated with the var under the point, but with trimmed trailing `!`/`?`. For example, if you run `cider-find-dwim` over `(ns/function! arg0 arg1)` it will ask `Jump to: ns/function` (note, without the trailing `!`). Is it an intended behavior?

`cider-find-var` behaves differently in such cases and jumps into such vars right away without any additional user input.

This question (bug?) was first mentioned in the [Doom Emacs discussion](https://github.com/hlissner/doom-emacs/issues/1360).

**Comment by bbatsov** [comment]
The problem seems to be here:

```
(defun cider--find-dwim-interactive (prompt)
  "Get interactive arguments for jump-to functions using PROMPT as needed."
  (if (cider--prompt-for-symbol-p current-prefix-arg)
      (list
       (cider-read-from-minibuffer prompt (thing-at-point 'filename)))
    (list (or (thing-at-point 'filename) ""))))  ; No prompt.
```

Notice that the thing at point is interpreted as a filename, not a symbol. Not sure what would be the best approach here, though.
