### ISSUE TITLE
Warn if lein < 2.9.0

### ISSUE THREAD

**Issue by dl1ely** [clojure-emacs/cider#2630]
Accidently, i tried using cider with lein 2.8.1 (default version when installed through apt on Linux Mint). Because of the group-id/artifact-id change of nrepl, the dependency injection on the `lein` command line for nrepl 0.6.0 does not work when doing `cider-jack-in`, because loading `org.clojure/tools.nrepl` seems to have precedence over `nrepl/nrepl`. Even adding the `nrepl/nrepl` dependency in `~/.lein/profiles.clj` as described in the troubleshooting section does not help. The repl buffer is rightfully complaining that i should at least use nrepl 0.4.4, but the root cause (failed dependency injection because of outdated lein version) stays hidden, because the commandline displayed in the minibuffer when doing `cider-jack-in` clearly states the nrepl/nrepl 0.6.0 dependency.

After finding the root cause (and noticing the minimum lein version requirement in the cider documentation) and updating to lein 2.9.1 everything worked smooth.

It would be very helpful when the repl buffer would warn me about my outdated `lein` version instead of or additionally to the warning about the outdated nrepl version. I guess this could be done by calling `lein version` and parsing the output when the nrepl version is detected to be too old. Unfortunately i cannot provide a PR because i am lacking elisp knowledge.

**Comment by bbatsov** [comment]
You're making a good point, but running `lein version` is crazy slow, so we should do something else. I'm open to suggestions.

**Comment by timvisher** [comment]
Don't know how much of a hack you'd think this would be but I checked every version since 2.5.3 (the version I'm stuck on) and they all have a well-formed `export` statement in the script. You could just check that. It's what controls which version of the jar is run.

```
vagrant@taps-tvisher1:~/git/leiningen$ while read -r tag; do curl -s -L https://github.com/technomancy/leiningen/raw/"$tag"/bin/lein | grep -F -- 'export LEIN_VERSION='; done < <(git tag --contains 2.5.3)
export LEIN_VERSION="2.5.3"
export LEIN_VERSION="2.6.0"
export LEIN_VERSION="2.6.1"
export LEIN_VERSION="2.7.0"
export LEIN_VERSION="2.7.1"
export LEIN_VERSION="2.8.0"
export LEIN_VERSION="2.8.0-RC1"
export LEIN_VERSION="2.8.1"
export LEIN_VERSION="2.8.2"
export LEIN_VERSION="2.8.3"
export LEIN_VERSION="2.9.0"
export LEIN_VERSION="2.9.1"
```

**Comment by dl1ely** [comment]
Not an expert on how lein works, but is this env variable available in the repl process and thus somehow visible to cider?

Other thought: Does the output of the `lein repl` call contain the lein version and could be parsed?

**Comment by timvisher** [comment]
No it's not available outside the script. Cider would need to parse it out of the script by hand. At least AFAICT.

**Comment by dl1ely** [comment]
Given that `lein version` only needs to be executed when there is an "error-like" condition anyway (outdated nrepl), and not regularly, i am not sure the added time to execute that check really is a problem.

**Comment by bbatsov** [comment]
I brought this up because ideally we'd check for this before we actually start a server and get some weird results. After the server is running checking for the lein version is easy, but I don't think that's what we want to do in this scenario.

**Comment by dl1ely** [comment]
Well, i thought it would be handled like the warning about the outdated nrepl version. So still offer the (potentially limited) repl functionality, but improve the specificity of the warning to give a clearer hint how to fix the problem. If it should be checked beforehand efficiently, then i see no other way as to parse the shell script. But that gives me an uneasy feeling because of brittleness, and Windows needs to be considered, too…

**Comment by vemv** [comment]
I'll close this issue, mostly due to age. I also don't necessarily think it should be CIDER's concern to guard for the status of external tools.

Because we try for our Changelog to be as informative as possible, and also because we try to avoid breaking changes as much as possible, the need for this detection should be increasingly rare.

A simple PR would be most likely welcome, though.

Cheers - V
