### ISSUE TITLE
CIDER Tests take ages and fail on emacs 27 

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider#2634]
On emacs 27 cider-jack-in-clj&cljs takes 4 minutes :

```
cider-jack-in-clj&cljs
  detects existing project  FAILED (4.02m)
```

and it gets stuck in apparent infloop on 

```
nrepl-server-buffer-name
  when nrepl-hide-special-buffers is t
    returns the name of the server buffer, which hides it in buffer changing commands
```
Emacs 26 works fine. 

Does anyone see this?

**Comment by bbatsov** [comment]
Yeah, I've seen this as well on the CI. No idea why, though. It also seems this test fails if `lein` is not installed. Clearly something's wrong with it and we should fix it or disable it.

**Comment by bbatsov** [comment]
See also #2603.
