### ISSUE TITLE
Investigating using Algolia DocSearch for documentation search

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/cider#2641]
## Problem

[CIDER documentation](https://docs.cider.mx/cider/index.html) is no longer searchable after the [switch to AsciiDoc and Antora](https://metaredux.com/posts/2019/05/29/cider-mx-reloaded.html).

## Proposed solution

Use [Algolia DocSearch](https://community.algolia.com/docsearch/) to provide a search box.

**Comment by bbatsov** [comment]
I've submitted a request to join DocSearch.

> Please be patient, it can take a few days.

Now I remembered why I dropped this last time around. :D

**Comment by bbatsov** [comment]
Done.

**Comment by danielcompton** [comment]
<img width="1325" alt="Screenshot of Safari (21-10-19, 7-53-33 AM)" src="https://user-images.githubusercontent.com/811954/67164518-f8d90080-f3d7-11e9-8d2d-2754fd886007.png">

I think this might be because docsearch is setup to filter on version 22:

```html
<script type="text/javascript">
docsearch({
  apiKey: '1f3d78fd63fcb687dcc1312aab02a2de',
  indexName: 'cider',
  inputSelector: '#search-input',
  algoliaOptions: { 'facetFilters': ["version:0.22.0"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
```

**Comment by bbatsov** [comment]
My bad. I broke this when I cut the new release. It's a pity you can't look in a range of versions.
