### ISSUE TITLE
REPL times out in fresh spacemacs on fresh leiningen project

### ISSUE THREAD

**Issue by SleakSchniek** [clojure-emacs/cider#2645]
## Expected behavior
jack into project and evaluate expressions

## Actual behavior
    nrepl-send-sync-request: Sync nREPL request timed out
Total blocker for using cider.

## Steps to reproduce the problem
Create fresh lein project. Open source file in fresh develop branch spacemacs. Cider jack-in. Evaluate (+ 1 1).

## Environment & Version information

Develop branch of Spacemacs, commit 37dcecbec

### CIDER version information
    CIDER 0.22.0snapshot (package: 20190606.923) 
    Leiningen 2.9.1 on Java 1.8.0_211 Java HotSpot(TM) Client VM
    Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode, sharing)

### Lein/Boot version

    Leiningen 2.9.1 on Java 1.8.0_211 Java HotSpot(TM) Client VM

### Emacs version

GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-17

### Operating system

Microsoft Windows 10 Home Version  10.0.17763 Build 17763

**Comment by bbatsov** [comment]
Usually this happens when there's some error during the nREPL server start. What happens if you paste the cider-jack-in command-line string into a shell? 

Did this break recently for you?

**Comment by SleakSchniek** [comment]
Hi Bozhidar, thanks for helping.
Do you mean to paste this into the shell? 

> [nREPL] Starting server via "c:/Users/user/leiningen-1.5.2-win/lein/lein.bat" update-in :dependencies conj ^"[nrepl \^"0.6.0\^"]^" -- update-in :plugins conj ^"[cider/cider-nrepl \^"0.22.0-beta3\^"]^" -- repl :headless :host localhost...

It says the syntax is wrong and I'm not sure how to turn this into a proper command.

I reinstalled java, leiningen and spacemacs after an unrelated issue with windows and havn't been able to get it to work since.

**Comment by bbatsov** [comment]
@SleakSchniek You have an ancient version of Leiningen (1.5.2). You need 2.9.1 or newer.

**Comment by bbatsov** [comment]
> Leiningen 2.9.1 on Java 1.8.0_211 Java HotSpot(TM) Client VM

But I see you've reported a different version here. I'm confused. :-)

**Comment by SleakSchniek** [comment]
Okay, there must have been some wrong reference with the lein versions. My version was 2.9.1 for sure. Anyhow I reinstalled leiningen and that solved my issue.

Thanks for pointing me to that.
