### ISSUE TITLE
cider-evaluate-buffer fails with intra-project references :invalid-ns

### ISSUE THREAD

**Issue by WorldsEndless** [clojure-emacs/cider#2664]
## Expected behavior
Using `C-c C-k` evaluates a cljs buffer the same way as a clj buffer

## Actual behavior
Error is produced like 
https://gist.github.com/WorldsEndless/57f84d1d4117da34626c744b4d6d25f1

I have been unable to find a full-stack code base in which this error does not occur. Evaluate-buffer in cljs always fails unless there are no internal `:require` in the ns. 

## Steps to reproduce the problem
1. `git clone https://github.com/WorldsEndless/reformation.git`
2. emacs reformation/test/cljs/reformation/core_front.cljs
3. `M-x cider-jack-in-clj&cljs`
4. Optional: in clj repl, `(start)`
5. in core_front.cljs buffer (or any other), `C-c C-k`

### CIDER version information
```
;; Connected to nREPL server - nrepl://localhost:45689
;; CIDER 0.21.0 (New York), nREPL 0.6.0
;; Clojure 1.10.1, Java 11.0.3
```

### Emacs version
GNU Emacs 26.1 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.4)

### Operating system
OpenSUSE Tumbleweed

**Comment by dpsutton** [comment]
Can you give a simpler repro? A thing that stands out is that you are putting things inside of `test` but its not clear to me that test is on your classpath. 

I also see this from figwheel's docs:
> If you want to serve the HTML file that will host your application from figwheel's built in server, then the output directory has to be in a directory that can be served by the static webserver. The default for the webserver root is "resources/public" so your output files need to be in a subdirectory of "resources/public" unless you change the webserver root. For now the webserver root has to be in a subdirectory of resources.

Having your resources served from test/... for css and html might be problematic. 

Can you give me instructions on how to connect with figwheel? I'm going to localhost:3449 and seeing:
![image](https://user-images.githubusercontent.com/6377293/60308965-12c67300-9911-11e9-8948-25ef345f3ed4.png)

I'm not sure I see an entrypoint for your clj backend either to create the resources. Happy to help you dig through once i can run your app though.

**Comment by WorldsEndless** [comment]
It should provide you a message upon following through step 4, telling you that the server has been launched on port 3000; then browse to `http://localhost:3000` and you'll see the page

**Comment by dpsutton** [comment]
I've added the following to `project.clj` and it works fine for me:

`:source-paths ["src" "test" "test/clj" "test/cljc" "test/cljs"]` Its unable to find the files on the classpath because the namespaces don't align with their location on disk.

**Comment by WorldsEndless** [comment]
@dpsutton completely right! Adding the cljs path works great. I was slow to look in the project.clj, because I thought I would have much larger problems than just `C-c C-k` failing if it wasn't being read; I didn't think I'd have a front-end to view at all. Figwheel seemed to be glossing over the fact that my sourcepaths were incomplete. How is this? Why wasn't the entire cljs portion of the app completely failing?
