### ISSUE TITLE
cljr-create-fn-from-example breaks if arg calls .. macro

### ISSUE THREAD

**Issue by anantpaatra** [clojure-emacs/cider#2680]
Trying this in a simple `figwheel-main` project with `deps.edn`.

Steps to reproduce:

`clj -A:new figwheel-main namespace/project`

Jack in with `C-u C-c M-J` and add `-R:fig` to the beginning of the command.

Choose `figwheel-main` and then `dev` (no colon).

Open the source file and type:

```clojure
(foo (.. bar))
```
On symbol `foo`, invoke `cljr-create-fn-from-example`. Expected:

```clojure
(defn- foo [arg0]
  )

(foo (.. bar))
```

Get error `cljr--guess-param-name: Wrong type argument: char-or-string-p, nil`.

`CIDER 0.22.0snapshot (package: 20190718.1550)`
`GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-24`

**Comment by bbatsov** [comment]
This should be reported here https://github.com/clojure-emacs/clj-refactor.el
