### ISSUE TITLE
Install Clojure layer with Spacemacs has bug !

### ISSUE THREAD

**Issue by MrMic** [clojure-emacs/cider#2684]
When installing clojure layer in Spacemcs, I got:
- queue-0.2 : Bad request or mispell packge

## Steps to reproduce the problem

Standard installation of layer in Spacemcs.
- clojure

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

Clojure 1.10.1

### Lein/Boot version
Leiningen 2.9.1 on Java 1.8.0_131 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 26.2 with Spacemacs

### Operating system

Mac OSX Mojave 10.14.5

**Comment by acrive82** [comment]
On MacOSX 10.14.5 from clean Emacs installation (26.2), same issue. 

_Package 'queue-0.2' is unavailable_

**Comment by bbatsov** [comment]
I see the package is still available via https://elpa.gnu.org/packages/queue.html

If you're ELPA repo is enabled (which happens by default) you should be good. Maybe you experienced some connectivity issue with the repo? Reloading your package archive might help with that. (`M-x package-refresh-contents`)

**Comment by MrMic** [comment]
Does not solve anything, unfortunately.
What is weird, is that on Linux everything is OK.

**Comment by jr0cket** [comment]
@MrMic Is this with Spacemacs `master` or `develop` branch?

I recommend using the Spacemacs `develop` branch as it has the latest fixes and version of CIDER.

**Comment by MrMic** [comment]
Just try it, but many packages unavailable now.
Worse than ever.
I will keep the stable branch.
The issue still not fixed. What is weird, is that with Linux everything just installed fine.
But with Mac OSX, not.
I have installed:

brew info emacs
emacs: stable 26.2 (bottled), HEAD
GNU Emacs text editor

Do I need another emacs distribution? and which one?

**Comment by jr0cket** [comment]
I had a Mac from work for several years and used https://emacsformacosx.com/ without any problem with the Spacemacs `develop` branch.

If you are using the Spacemacs `master` branch, then docs recommend homebrew https://github.com/syl20bnr/spacemacs#macos

```
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus
$ brew linkapps emacs-plus
```

The `develop` branch suggests a few options for installing Emacs on MacOSX
https://github.com/syl20bnr/spacemacs/tree/develop#macos

I would certainly recommend the `develop` branch for Clojure development (as there have been a number of fixes and improvements that are not in `master` yet
https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop#clojure

**Comment by MrMic** [comment]
Test all of this and that does NOT fix anything.
If you do NOT have a tested solution to this issue, plz 
do NOT answer anymore and make me lose my time.
Let someone who has fixed this bug, answer.

Bug still NOT fixed: Clojure layer cannot be installed on 
Mac OSX.

**Comment by bbatsov** [comment]
I'm not involved with Spacemacs at all and such a problem should be reported on Spacemacs issue tracker.

**Comment by harrybournis** [comment]
I had the same issue, I opened the `queue.el` file in my elpa directory and it was empty. I copied and pasted the content from the [repo](http://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/packages/queue) and now it works fine. 

That's a weird bug, I don't think I had any errors while downloading packages, some issue with elpa maybe?

**Comment by MrMic** [comment]
> I had the same issue, I opened the `queue.el` file in my elpa directory and it was empty. I copied and pasted the content from the [repo](http://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/packages/queue) and now it works fine.
> 
> That's a weird bug, I don't think I had any errors while downloading packages, some issue with elpa maybe?

You can fix the bug with reading this:
https://github.com/syl20bnr/spacemacs/issues/12535

In fact, I have opened this bub on spacemacs bug list and someone give me the solution.

**Comment by stevematdavies** [comment]
This issue is not spacemacs, I have the latest emacs 26.2 on Ubuntu (not spacemacs) and the error remains. There currently appears to be no fix (or motivation for documenting one simply)

**Comment by yangjiannan2018** [comment]
i upgrade to emacs26.3 solved.
