### ISSUE TITLE
Cannot show javadoc of core JDK classes on JDK 9+

### ISSUE THREAD

**Issue by jumarko** [clojure-emacs/cider#2687]
**UPDATE 2**: for now, there seem to be consistent issues with at least:
- `cider-javadoc` -> adds an extra "java.base" javadoc url path segment which leads to 404 NOT FOUND error
- `cider-doc` doesn't show proper javadoc for newer(?) JDK classes (e.g. `java.lang.Module`)

**UPDATE**:  It must be something in my `./lein/profiles.clj` - when I remove them it works. I'll try to find out what's causing that.

I can't display javadoc for core classes like `java.lang.String` even though JDK sources are available.

It works when I use JDK 8.
If I use anything more recent (tested with JDK 9 and 11) then it doesn't work.

Perhaps related to https://github.com/clojure-emacs/cider/issues/2686

##  Expected behavior

When invoking `cider-javadoc` the javadoc for the `String` class should be displayed:

![image](https://user-images.githubusercontent.com/1083629/62793343-a9ba4980-bad1-11e9-8818-cce8028eb77b.png)

## Actual behavior

Javadoc is not shown:
![image](https://user-images.githubusercontent.com/1083629/62793452-f00fa880-bad1-11e9-8997-10bfed43529d.png)

## Steps to reproduce the problem

* set java version to JDK 11 (perhaps using `jenv`)
* run `cider-jack-in`
* type `String` into the REPL/buffer and try to show javadoc

### CIDER version information

```
CIDER 0.22.0snapshot (package: 20190808.1659), nREPL 0.6.0
Clojure 1.10.1, Java 11.0.2
```

### Lein/Boot version

```
lein -v
Leiningen 2.9.1 on Java 11.0.2 OpenJDK 64-Bit Server VM
```

### Emacs version

25.3.1

Using Spacemacs

![image](https://user-images.githubusercontent.com/1083629/62792549-d1101700-bacf-11e9-860b-f7a8070fcf4e.png)

### Operating system

Mac OS X 10.14.5

**Comment by bbatsov** [comment]
> UPDATE: It must be something in my ./lein/profiles.clj - when I remove them it works. I'll try to find out what's causing that.

What's in your profiles? //cc @jeffvalk

**Comment by jumarko** [comment]
There are quite a few things in my profiles.clj although I commented out many of them yesterday. The current version is here: https://github.com/jumarko/clojure-experiments/blob/master/lein-profiles.clj.

Unfortunately, I'm now not so sure that it's completely caused by the presence of profiles.clj.
It seems that it works even when I'm using my current profiles.clj (at least on https://github.com/jumarko/lein-sample) for things like `java.lang.String` or `java.lang.Number`.
However, it doesn't seem to work for newer classes like `java.lang.Module`.

Moreover, the `cider-javadoc` seems to be broken for (at least) JDK 11.
`clojure.java.javadoc/javadoc` works without problems; e.g.
```
(javadoc String)
;;=> opens proper docs: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html
```
However, invoking `cider-javadoc` yields https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java.base/java/lang/String.html which returns NOT FOUND (extra "java.base" segment in the middle of the URL path)

**Comment by bbatsov** [comment]
Hmm, that's pretty weird as we actually have a bunch of unit tests for URLs for different JDK versions - see https://github.com/clojure-emacs/orchard/blob/master/test/orchard/java_test.clj#L199

**Comment by jeffvalk** [comment]
Regarding the original issue: Is there anything at play that would affect classloaders?

The JDK sources are dynamically loaded by `orchard.java`; if something causes `src.zip` to be loaded by a classloader that is too low in the hierarchy, its contents won't be visible on the classpath when `orchard.java.parser` looks for a particular class' source file. (This is only a potential issue on JDK9+; prior to that, classloaders at the top of the hierarchy were de facto dynamic.)

**Comment by jumarko** [comment]
@bbatsov those tests look correct but I think the problem is in the [`info/javadoc-info`](https://github.com/clojure-emacs/cider-nrepl/blob/691fc2c16eb2b3267e4679941fdb46fccce0b0f9/src/cider/nrepl/middleware/info.clj#L45) function is called on the result which adds the extra "java.base" segment to the url path in the [`resolve-javadoc-function`](https://github.com/clojure-emacs/orchard/blob/master/src/orchard/java.clj#L348).

More specifically, when I tested it with "java.base/java/util/Random.html#nextLong()" it went to the path of [dereferencing the `javadoc/*remote-javadocs*`](https://github.com/clojure-emacs/orchard/blob/master/src/orchard/java.clj#L367) which for `*core-java-api*` returns and JDK 11 returns this url:  `"https://docs.oracle.com/en/java/javase/11/docs/api/java.base/"` - notice that "java.base" prefix is already there:

```
orchard.info> (javadoc-info "java.base/java/util/Random.html#nextLong()")
;;=>
{:javadoc
"https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java.base/java/util/Random.html#nextLong()"}

```

**Comment by jumarko** [comment]
@jeffvalk 
I'm not sure I can answer your question.
But perhaps it's more related to https://github.com/clojure-emacs/cider/issues/2686 ?

I've updated the description to state two things (`cider-javadoc` not working for JDK 11 and `cider-doc` not working for classes like `java.lang.Module`). 
I'd say let's ignore my issues with `cider-doc` and core java.lang classes (at least until I can figure out what exactly is causing the issues or come up with a solid reproducer).

**Comment by jeffvalk** [comment]
> notice that "java.base" prefix is already there

That appears to be true, and hence broken. `clojure.java.javadoc/*remote-javadocs*` returns wrong URLs for any JDK class not in the `java.base` module. This includes a lot of common classes (e.g. `java.sql.*`, `java.util.logging.*`, etc).

**Comment by bbatsov** [comment]
Yeah, I think we should just replicate this in orchard. I think this will be pretty simple. Might also be a good idea to open an upstream issue report in Clojure.

**Comment by jumarko** [comment]
Asked for clarification of the upstream lib behavior here: https://ask.clojure.org/index.php/8422/clojure-javadoc-javadoc-fails-javadoc-classes-outside-module

**Comment by dpsutton** [comment]
https://github.com/clojure-emacs/orchard/pull/84

fixes this. I've also got a [jira ticket](https://clojure.atlassian.net/browse/CLJ-2560) to add a doc url for java 13. Can add a backport for this while we wait if desired.
