### ISSUE TITLE
Cider injected dependencies don't properly exclude Clojure, and thus bring in the wrong version

### ISSUE THREAD

**Issue by didibus** [clojure-emacs/cider#2692]
I have a specific scenario, I'm not sure which projects to report the issue too.

Basically, for reasons I won't explain, the version of Clojure my lein project uses is defined as a resource. It gets added to the classpath, but my project.clj does not declare any dependency on Clojure.

When I cider-jack-in-clj, Cider will add sayid and refactor-nrepl, both of which lack an exclusion on Clojure, and because of that, lein will include their specified Clojure version on the classpath. This causes a conflict in that I want to use the Clojure Jar on my classpath that is added through a resource, not the version sayid or refactor-nrepl brings.

I'm thinking they should both change their project.clj to exclude Clojure, but I'm unsure.

Here's the `lein deps :tree`

```
Possibly confusing dependencies found:
[com.billpiel/sayid "0.0.17"] -> [org.clojure/clojure "1.7.0"]
 overrides
[refactor-nrepl "2.5.0-SNAPSHOT"] -> [nrepl "0.5.3"] -> [nrepl/bencode "1.0.0"] -> [org.clojure/clojure "1.8.0"]

Consider using these exclusions:
[refactor-nrepl "2.5.0-20190723.094516-2" :exclusions [org.clojure/clojure]]

 [cider/cider-nrepl "0.22.0-beta8"]
 [clojure-complete "0.2.5" :exclusions [[org.clojure/clojure]]]
 [com.billpiel/sayid "0.0.17"]
   [org.clojure/clojure "1.7.0"]
   [org.clojure/tools.namespace "0.2.11"]
   [org.clojure/tools.reader "1.3.0-alpha3"]
   [tamarin "0.1.2"]
 [nrepl "0.6.0"]
 [refactor-nrepl "2.5.0-20190723.094516-2"]
```

Regards

**Comment by bbatsov** [comment]
That's not really a Cider issue as refactor-nrepl and sayid are technically 3rd party deps, but it's definitely a problem and we'll need to revise the deps of the plugins.

**Comment by bbatsov** [comment]
I've updated the deps in `sayid` and `refactor-nrepl` accordingly, but I still have to cut new releases for them.

**Comment by bbatsov** [comment]
I cut a sayid release, but `refactor-nrepl` will have to wait. I guess we can close this ticket.
