### ISSUE TITLE
Completion breaks repl

### ISSUE THREAD

**Issue by mgrbyte** [clojure-emacs/cider#2693]
When attempting any symbol completion in the repl, a stack trace is printed after a short delay (2-5 seconds on my machine)

## Expected behaviour
Symbol completes.

## Actual behavior
The spinning icon appears, then after about a second, a stack trace is emitted.

## Steps to reproduce the problem
Run: `C-c M-j` (`cider-jack-in`) or `C-c M-c` (`cider-connect`)
Require a namespace (e.g `(require '[clojure.string :as str])`
Type `(str/repl` and then hit  `<TAB>`

Relevant lines from the Emacs `*Messages*` buffer:
```
[nREPL] Starting server via /usr/local/bin/clojure -Sdeps '{:deps {acyclic/squiggly-clojure {:mvn/version "0.1.9-SNAPSHOT"} nrepl {:mvn/version "0.6.0"} cider/cider-nrepl {:mvn/version "0.22.0-beta10"}}}' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware"]'
[nREPL] server started on 39445
[nREPL] Establishing direct connection to localhost:39445 ...
[nREPL] Direct connection to localhost:39445 established
Entering debugger...
```

Files attached with clojure and emacs stack traces.
[clj-stacktrace_cider-0.22snapshot.txt](https://github.com/clojure-emacs/cider/files/3509131/clj-stacktrace_cider-0.22snapshot.txt)
[emacs-stacktrace_cider0.22snapshot.txt](https://github.com/clojure-emacs/cider/files/3509134/emacs-stacktrace_cider0.22snapshot.txt)

### CIDER version information

```
;; CIDER 0.22.0snapshot (package: 20190815.1933), nREPL 0.6.0
;; Clojure 1.9.0, Java 1.8.0_222
```

### Lein/Boot version
N/A (Using clojure-cli tools version `1.10.1.458`

### Emacs version

GNU Emacs 26.2.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-06-19

### Operating system
Ubuntu 18.04.3 LTS

**Comment by bbatsov** [comment]
See https://github.com/clojure-emacs/cider-nrepl/issues/635 I'll revert CIDER to the previous cider-nrepl beta for the time being.

**Comment by mgrbyte** [comment]
Thanks! :+1: , apologies for the duplicate ticket/wrong repo! (I did search first, remember the nrepl project was separate).
