### ISSUE TITLE
Apply some SEO to cider.mx 

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2695]
The big problem is that right now Google search thinks that the domain should target just Mexico users and I couldn't find a way to tell it to target international users as well. As a result the official site can't discovered at all, but you'll get a million references to the legacy cider.readthedocs.io. 

I'd really appreciate some help with this, as I know next to nothing about SEO. Anyways, I did learn a valuable lesson - fun domain names might cause problems for you down the road. :) If we can't figure out what to do with the current domain I'll probably move cider under some more traditional domain like `.org` or `.net`.

**Comment by dpsutton** [comment]
I asked my friend who does a bit of SEO. He said the number one thing is the lack of https. Google heavily discounts not https websites in search results.

**Comment by bbatsov** [comment]
@dpsutton But both `cider.mx` and `docs.cider.mx` have https.

**Comment by danielcompton** [comment]
One thing which could help is either:

1. 301 permanent redirecting all https://cider.readthedocs.io links to their counterparts in the cider.mx documentation. This doesn't look like it's possible yet https://github.com/readthedocs/readthedocs.org/issues/2267.
2. Marking cider.mx as the [rel="canonical"](https://support.google.com/webmasters/answer/139066?hl=en) source in all of the readthedocs.io pages.
3. Some hackier approaches client-side https://stackoverflow.com/questions/40501719/how-to-redirect-readthedocs-web-pages-to-other-website.

One possibility is that Google has seen `cider.mx` be created with a bunch of duplicate content from `cider.readthedocs.io` and assumed that `cider.mx` was just a spammer/copier.

> The big problem is that right now Google search thinks that the domain should target just Mexico users and I couldn't find a way to tell it to target international users as well.

Is this what you see in Google Webmaster Tools? When you access Google from Mexico does cider.mx come up in the search results? They have a [report](https://support.google.com/webmasters/answer/6059209) which can tell you about the language targeting they are doing. [Managing multi-regional and multilingual sites](https://support.google.com/webmasters/answer/182192?hl=en) has some more suggestions from Google on this, setting [hreflang](https://support.google.com/webmasters/answer/189077) to English _might_ help you break out of this, but maybe not.

Sorry if I'm just repeating things you've already researched and come across!

**Comment by bbatsov** [comment]
The report says:

> Your site's domain is currently associated with the target: Mexico

The problem is I don't see any way in the search console to change this. 

>  setting hreflang to English might help you break out of this, but maybe not.

I'll try this at some point, but I was hoping I could just instruct google to ignore the domain targeting in the search console. As usual Google don't fail to disappoint with the confusing UX of their tools. :D 

> One possibility is that Google has seen cider.mx be created with a bunch of duplicate content from cider.readthedocs.io and assumed that cider.mx was just a spammer/copier.

That's an interesting theory. I didn't think of something like this. Perhaps I can just delete the old site and simplify my life. :D

**Comment by danielcompton** [comment]
I did a little bit more reading, and I suspect that `.mx` may be "hard-coded" to geo-target to Mexico.

From https://moz.com/blog/guide-to-international-seo

> Choosing the URL structure of your language extensions is totally up to you. If you are focusing on language targeting only, **don’t use a ccTLD. Those are meant for targeting a specific country, not a language. ccTLDs automatically geo-target and that selection cannot be changed.**

I'm not really sure if there is a way out of this. Rather than sink many hours into wrestling the bear, I think the easy way out is to find a global domain name that is available.

**Comment by danielcompton** [comment]
Apparently there is/was a checkbox for international targeting in the search console, but I'm guessing that is missing for the .mx domain.

![Int-Targeting](https://user-images.githubusercontent.com/811954/64470034-66b2cb00-d190-11e9-90bf-cf84b24a43f6.png)

https://nubodigital.com/seo-google-domain-multiple-languages/

**Comment by bbatsov** [comment]
Yeah, indeed it's missing. Oh, well - I guess I'll have to think of some other domain then - e.g. `mx-cider.org`. Lesson learned - don't try to be too original. 😄 

Thanks for the help!

**Comment by danielcompton** [comment]
No problem, there will still need to be redirects setup from Readthedocs, I’m happy to help with that once you find the new domain.

**Comment by ahungry** [comment]
"CIDER is the Clojure(Script) Interactive Development Environment that Rocks! CIDER extends Emacs with support for interactive programming in Clojure."

In both DuckDuckGo and Google results, the first result is the github page (DDG shows the Github summary line and Google shows the first part of the readme).

Since the tag line is a little redundant (interactive programming in clojure repeated twice essentially) maybe it would be pertinent to include a link straight to the docs right in the tag line?

"CIDER is the Clojure(Script) Interactive Development Environment that Rocks!  Read more about CIDER here: https://cider.mx"

Then the proper doc link will be in the first and second slot results on both engines.

**Comment by bbatsov** [comment]
That's a good idea, but it won't solve the problem that the content in `docs.cider.mx` won't appear in the search results.
