### ISSUE TITLE
in-ns does not work for multiple namespace switches

### ISSUE THREAD

**Issue by tejasbubane** [clojure-emacs/cider#2696]
## Expected behavior

`in-ns` should work with multiple namespaces.

## Actual behavior

`in-ns` does not work in following scenarios:

```clojure
(in-ns 'foo)
(def cheese ["Mozzerella", "Gowda"])
(in-ns 'core)
```

1. `cider-jack-in` without project.
`Namespace 'foo' not found`

2. `cider-jack-in` with project - works first, fails for second `in-ns`
`Namespace 'core' not found`

## Steps to reproduce the problem

Create file `xyz.clj` with content

```clojure
(in-ns 'foo)
(def cheese ["Mozzerella", "Gowda"])
(in-ns 'core)
```

`C-x-C-e` on the in-ns expressions.

### CIDER version information

`20190828.1604` from melpa

```
;; Connected to nREPL server - nrepl://localhost:54751
;; CIDER 0.22.0snapshot (package: 20190828.1604), nREPL 0.6.0
;; Clojure 1.10.0, Java 12
```

### Lein/Boot version

Leiningen 2.9.1 on Java 12 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 26.2

### Operating system

macOS Mojave Version 10.14.4

**Comment by bbatsov** [comment]
That's closely related to `clojure-mode` and how it detects the current namespace. I think it just makes an assumption there's one ns form per buffer, as dealing with `in-ns` was painful. I haven't touched this code in a long time and I don't remember the current behaviour well.
