### ISSUE TITLE
Clearing output of output does not clear outputs

### ISSUE THREAD

**Issue by davidpham87** [clojure-emacs/cider#2697]
Hello,

I tried to clear the output of the repl with `C-c M-o` and I get the message `;;output cleared` just above last line, but the buffer is not cleared. I use `cljs` with shadow-cljs if this can provide any help.

```
;; CIDER 0.22.0snapshot (package: 20190816.1111), nREPL 0.6.0
;; Clojure 1.10.1, Java 11.0.4
```

**Comment by bbatsov** [comment]
I guess you actually mean `C-c C-o`, right? Without a prefix the command clears the output of the last evaluation. With a prefix it clears everything in the buffer (`C-u C-C C-o`).

**Comment by davidpham87** [comment]
Thanks a lot! Solves the issue perfectly! :-)
