### ISSUE TITLE
REPL pending forever

### ISSUE THREAD

**Issue by whitemuu** [clojure-emacs/cider#2701]
I update cider to the latest version.

connect way more fast than before, only several seconds.

```
;; Connected to nREPL server - nrepl://localhost:56622
;; CIDER 0.22.0 (package: 20190901.1056) (São Paulo), nREPL 0.6.0
;; Clojure 1.10.0, Java 1.8.0_172
...
WARNING: No Clojure project was detected. The
refactor-nrepl middleware was not enabled. (You can mute this
warning by customizing `cljr-suppress-no-project-warning'.)
```

When I type something in REPL and hit return, It's pending forever.

then I observe(MacOS):
- main process nearly 100%
- no Java process running at all

**Comment by whitemuu** [comment]
I tweaked something before all of this

changed `cider-required-middleware-version` from `0.22.1` to `0.22.0`, cuz I didn't see a version `0.22.1` in the repository🤔

**Comment by bbatsov** [comment]
There's something wrong with clojars and I couldn't push cider-nrepl 0.22.1. For the time being I've updated CIDER to use 0.22.0 by default. Hopefully the clojars issue will be addressed soon.

**Comment by bbatsov** [comment]
The missing version is on clojars now. Sorry about this!
