### ISSUE TITLE
0.22.1 uninstallable from melpa-stable

### ISSUE THREAD

**Issue by jwr** [clojure-emacs/cider#2702]
It appears that cider-0.22.1 is marked as "incompat" when using melpa-stable. I think this is because it depends on `parseedn-0.1` which does not seem to be available from melpa-stable.

`GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6)
 of 2019-08-27`

using

`(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/") t)`

**Comment by bbatsov** [comment]
Ops! My bad - I had forgotten to push the `parseedn` release tag. 🤦‍♂ The package is available now.
