### ISSUE TITLE
Ignore the patch version of cider-nrepl when doing a required version check

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2705]
Today you'd get a warning if `cider-required-middleware-version` is 0.22.1 and you're on cider-nrepl 0.22.2. I think it'd be best if we just ignored the patch segment of the version while doing this comparison.

**Comment by jgerman** [comment]
This is my first time looking at the Cider code but I think this is pretty straightforward. 

If the patch is dropped from `cider-required-middleware-version`:

`(defconst cider-required-middleware-version "0.22")`

and use `string-prefix-p` in the check:

```
 ((not (string-prefix-p cider-required-middleware-version middleware-version))
      (cider-emit-manual-warning "troubleshooting.html#_cider_complains_of_the_cider_nrepl_version"
                                 "CIDER %s requires cider-nrepl %s+, but you're currently using cider-nrepl %s. The version mismatch might break some functionality!"
                                 cider-version cider-required-middleware-version middleware-version)))))
```

If that's acceptable I can put together a PR.

**Comment by bbatsov** [comment]
It can't be done this way, as we also use the same version number to tell CIDER which `cider-nrepl` to load. It'd be adjust only the code that handles the warning. Emacs has a bunch of functions for comparing versions that will help with this.

**Comment by jgerman** [comment]
I ran into that issue immediately after posting this when I tried to cider-jack-in instead of cider-connect. :) 

I'll dig a little deeper.
