### ISSUE TITLE
cider-selector with a non clojure buffer/repl selected produces error: "Wrong type argument: stringp, nil"

### ISSUE THREAD

**Issue by ahungry** [clojure-emacs/cider#2707]
I did some fast debugging last week on this, and it seems to be with how it's calling sesman to get the active sessions.

I think CIDER should work around this, as the behavior appears well defined at the sesman level (given an active buffer, give linked sessions).

However, the Common Lisp variant of this with SLIME and slime-selector works regardless of what buffer the user is currently in (it has a jump to last visited lisp file, and a jump to last visited REPL feature).

I think this would make the CIDER selector much more useful, if a single hotkey could jump back to the last visited clojure file or clojure repl if the current file returns no matches.

**Comment by bbatsov** [comment]
I guess we can close this one, as it was fixed by #2711.
