### ISSUE TITLE
Support to jack in / start repl without a project?

### ISSUE THREAD

**Issue by ahungry** [clojure-emacs/cider#2712]
Is there anyway to start a REPL without a project?  Just something equivalent to `clj` with perhaps some elisp specifiable arguments for dependencies etc.? 

If not, I think such a feature would allow users to more easily tinker with Clojure(script) in an environment better than the shipped `clj` utility (especially if it also auto-started a cider-scratch buffer as well).

**Comment by bbatsov** [comment]
Yeah, `cider-jack-in` works just fine outside projects as well. It will use `clj` to spin the nREPL server and connect to it.

**Comment by weipe** [comment]
> With a little tweak, you can also execute such file as a regular script.

This works for me, for the script above:
`$ BOOT_JVM_OPTIONS="-cp ." BOOT_CLOJURE_VERSION=1.8.0 ./hello.boot`

**Comment by ahungry** [comment]
Very cool, thanks
