### ISSUE TITLE
Navigating to deftype doesn't work from constructor

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/cider#2721]
From clojurescript, navigating to source on `(MapEntry. 1 2 nil)` doesn't work. However, if you add a space to separate the `.` it does

Seems like it would be simple to check for a trailing period and then reissue the navigation command. From documentation about [the reader](https://clojure.org/reference/reader)

> Symbols begin with a non-numeric character and can contain alphanumeric characters and *, +, !, -, _, ', ?, <, > and = (other characters may be allowed eventually).

It seems safe to assume that periods are not valid constituents of a symbol so we can safely check and navigate to the underlying deftype or defrecord by trimming it.

**Comment by bbatsov** [comment]
Yeah, that should be a simple fix. Probably there's also a way to reject dots by tweaking the syntax table in clojure-mode.
