### ISSUE TITLE
Option to fail fast and capture output on tests

### ISSUE THREAD

**Issue by ccann** [clojure-emacs/cider#2736]
It would be useful to be able to configure CIDER to fail fast (like eftest or kaocha) when running tests for, e.g. a particular namespace, or the entire project. Specifically, stop running tests after 1 test fails/errors out.

Relatedly, it would be great if it were possible to configure CIDER to capture the output of tests instead of printing to the REPL. Once tests have run, spit the output of the failed tests to the REPL, or to a new buffer, or even to the test-report buffer.

I've considered using something like https://github.com/magnars/kaocha-runner.el to provide what I'm looking for but the test reporting isn't as well integrated aesthetically as CIDER's is and I don't want to lose that, but I do want fail-fast.

**Comment by bbatsov** [comment]
This seems like a duplicate of a pretty old ticket - see https://github.com/clojure-emacs/cider/issues/696. We still need some volunteer to make the necessary changes so tests are run one by one which would enable fail fast and better feedback.
