### ISSUE TITLE
Chose a license for the documentation portal

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2740]
I was recently asked about this and I realized we never chose a license for the docs portal. 

Some options are outline here - https://www.dreamsongs.com/IHE/IHE-50.html I'm leaning towards the GNU FDL, but there are also some concerns about it https://www.debian.org/vote/2006/vote_001 (at least for version 1.2). 

@clojure-emacs/cider Let me know if someone has ideas on the subject.

**Comment by danielcompton** [comment]
Mozilla’s docs distinguish between code snippets (public domain) and documentation (Creative Commons) - https://developer.mozilla.org/en-US/docs/MDN/About. Something like that might be good to make sure people have certainty about the licensing on any snippets they copy from the docs. 

I’d agree with Debian’s assessment of the FDL. Creative Commons, GPL, or MIT all make sense here. GPL for docs would be similar to the current licensing.

**Comment by bbatsov** [comment]
Thanks for the feedback!

**Comment by iarenaza** [comment]
Just my 0.02 euros on this. Many people have been discouraging code licenses (like MIT and GPL) for documentation for some time now. The thinking is that those licenses have some code-specific features that don't translate too well to documentation and other kinds of creative works (pictures, movies, etc.).

**Comment by jr0cket** [comment]
I use the "Creative Commons Attribution Share-Alike 4.0 International" license for all my documentation and published works.

The have a license builder if you want different options on the license, there are a few clear choices you can make
https://creativecommons.org/share-your-work/

**Comment by dpsutton** [comment]
don't know how important this issue is but it might be a good one to reopen and just pick a license.

**Comment by bbatsov** [comment]
Well, unless people have objectives, let's go with Creative Commons.

**Comment by jr0cket** [comment]
The beta version of the creative commons  license builder is nice, I used that for all my websites and for code I share publicly

https://chooser-beta.creativecommons.org/

**Comment by danielcompton** [comment]
Creative Commons sounds good, I’d suggest any code snippets are licensed public domain to avoid clouding their use.
