### ISSUE TITLE
Can't go to java class definition

### ISSUE THREAD

**Issue by arthurborisow** [clojure-emacs/cider#2745]
## Expected behavior
I am thrown to the source code of the method
## Actual behavior
<img width="827" alt="Screenshot 2019-11-08 at 16 33 01" src="https://user-images.githubusercontent.com/786034/68484247-9429fc80-0245-11ea-8886-cf097c20c475.png">
It throws error `Unexpected archive: /usr/lib/jvm/openjdk-8/src.zip`
## Steps to reproduce the problem

1. lein new test-cider
2. emacs . (with installed prelude and enabled clojure module)
3. go to `src/test_cider/core.clj`
4. add line `(.toUpperCase "somestring")`
5. `cider-jack-in`
6. Move point to `.toUpperCase`
7. Press <kbd><M-.></kbd>. Chose either String or Character. It doesn't show any documentation
8. Go to repl
9. Enter any code which will throw error
10. Stack trace comes out
11. Click on `java.lang.Thread/run`
12. It show error in minibuffer

### CIDER version information

```
;; CIDER 0.24.0snapshot (package: 20191103.1528), nREPL 0.6.0
;; Clojure 1.10.0, Java 12
```

### Lein/Boot version

Leiningen 2.9.1 on Java 12 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

26.3

### Operating system

OS X 10.15 "Catalina"

**Comment by EmmanuelOga** [comment]
I was seeing a similar problem on my [Windows 10] setup. I tracked it to [this function](https://github.com/clojure-emacs/cider/blob/6ad997e7f35a303757d15d5498e567182678163c/cider-util.el#L780-L799), and then I realized that jdk sources variable was not properly set on my system.

That path [can be adjusted as documented here](https://docs.cider.mx/cider/config/basic_config.html#_use_a_local_copy_of_the_java_source_code).

**Comment by EmmanuelOga** [comment]
Some additional notes for Windows 10 users and maybe other systems. I use powershell on all `$ shell` calls.

### Locating the java version used and the source folder.

I have many JDKs so I forgot which one I was running. The command `$ where.exe java.exe` should show the folder for the current JDK. The path should match the output of `cat Env:\JAVA_HOME` or strange things may happen. I followed the [advice to unzip the sources as documented on cider instructions](https://docs.cider.mx/cider/config/basic_config.html#_use_a_local_copy_of_the_java_source_code). I simply found a file `src.zip` that looked like the right one and unzipped that on an arbitrary folder.

### Setting the path

I tried using .dir-locals.el but I couldn't make it work for some reason. In the end I resorted to setting the config on `~/.emacs.d/init.el`, which worked fine. The setup looked something like this:

```lisp
(setq cider-jdk-src-paths '("C:/java/jdk-13.0.1+9/source"
                              "C:/java/jdk-13.0.1+9/source/java.base"))
```
Note that the paths can be supplied as forward slashes, which worked fine for me (as opposed as double-escaping the slashes, that for some reason did not work).

Also note that I added not one but two directories: the zip I used did not work out of the box for java base files, until I added the `java.base` subdir also. I suspect I will have to keep adding new directories from time to time if something fails. I'm not sure why this is needed, it may be a quirk of the particular JDK and src.zip folder I'm using (OpenJDK J9).

### Error: "Unzip" command is missing

Some sources are located on **jar** or a **zip** files, so cider will need the `unzip` program. This is not available on Windows 10 out of the box, but it can be installed through [chocolatey](https://chocolatey.org/). Once chocolatey is setup, a simple `choco install unzip` will do the trick. Installing unzip manually it is also possible but more tedious.

### Other sources

If I get it right cider will also look at the classpath to locate sources, so its is possible that for other dependencies, a `######-source.jar` could be added to the maven dependencies using whatever dep conf you are using (lein, deps, boot, etc). I haven't have to do this myself yet.

**Comment by bbatsov** [comment]
@EmmanuelOga Good tips for Windows users. We should add some of them to the docs.
