### ISSUE TITLE
Evaluation indicators too subtle?

### ISSUE THREAD

**Issue by jr0cket** [clojure-emacs/cider#2748]
The evaluation indicators in the fringe do not stand out very clearly and many people are unaware of this very useful feedback because they do not notice them.

I have found the evaluation indicators in the fringe particularly difficult to spot using either of the Spacemacs themes.  They are almost invisible on the spacemacs-light theme

Currently, `lightgreen` is used with light themes and `darkgreen` is used for dark themes.  Could these values be swapped?  That may make the indicators more obvious.

https://github.com/clojure-emacs/cider/blob/master/cider-overlays.el#L132

I would be happy to test out alternatives if there is a way to set the foreground colour, preferably setting that in the `init.el` or `.spacemacs` file than creating a fork of the CIDER package.

**Comment by jr0cket** [comment]
Using `helm-faces`, selecting `cider-fringe-good-face` and clicking customize button seems a good way to experiment, as colours can be applied immediately.

With spacemacs-light and spacemacs-dark themes, the following stand out more.

`LimeGreen` #32cd32 works well on a dark background
`DarkGreen` #006400 works well on a light background

**Comment by dpsutton** [comment]
can you throw up some screenshots? ideally with light and dark modes?

**Comment by jr0cket** [comment]
Tested on the following themes with positive results, although light themes still seem a little faint
spacemacs-dark, spacemacs-light, adwaita, dichromancy, leuven, whiteboard.

Will add some screenshots of the changes soon.  In the mean time you can see how faint the existing colour is in this video https://youtu.be/o4Q-K3lzBRY?t=2132

Thank you.

**Comment by jr0cket** [comment]
Spacemacs light and dark themes with suggested values for fringes

![spacemacs-dark-evaluation-indicators](https://user-images.githubusercontent.com/250870/68954898-d2cb3400-07bc-11ea-956c-38c4fe261e81.png)
![spacemacs-light-evaluation-indicators](https://user-images.githubusercontent.com/250870/68954899-d363ca80-07bc-11ea-9d73-9ab133b41ac9.png)

**Comment by jr0cket** [comment]
An alternative would be to use a solid bar as a marker, or thicker lines, rather than very thin lines which blend into the background more readily.

**Comment by bbatsov** [comment]
How would this look? 

Generally we wanted this to be something subtle and non-intrusive when the feature was introduced. I'm thinking that probably we never documented it anywhere, so I doubt that many people ever realized what those markers are about. :-)

**Comment by jr0cket** [comment]
Everyone I asked about the evaluation indicators had never noticed them, so
it seems you succeeded in unobtrusiveness :)

The indicators are an excellent feature.

I tell people about them, but I also keep forgetting they are there,
especially when I switched to a light theme.

I think clj-kondo fringe indicators also makes the evaluation indicators
less visible, as they themselves are so visible.

I don't find the clj-kondo indicators or the git diff indicators
distracting.

Having the ability to customise for each theme would be valuable.  I am
suggesting the default colours should be more noticable so people are aware
of their existence.

Green seems a good colour of choice for the evaluation indicators.   Using
a dark green for a light theme (and vice versa) is a simple way to do this.

This still makes it a bit subtle on all the light themes I tried.  The
dashed line for the indicator blends into the light background.  A solid
line should be clearer.

An option to switch them off if distracting seems a sensible approach.

I have not yet discovered how to change appearance of the indicator except
for the colour, so haven't had chance to test any alternative design.

Thank you.

**Comment by jcaw** [comment]
I've opened a PR with screenshots at #2751

**Comment by jr0cket** [comment]
One final point of note about the Fringe indicators.  With Emacs version 26 onwards, the position of the line numbers and the fringe have swapped.

Emacs 26 now uses native line numbers, meaning the line numbers are now part of the main text area instead of being in the margin.  This means the evaluation indicators are much further way from the code.

Before Emacs 26, the fringe markers were right next to the opening paren of the evaluated code and so a little easier to notice.  Now they are further away from the code, they are much harder to spot in their original colour and design.

Thank you.

**Comment by jr0cket** [comment]
The PR mentioned in this request seems to have been abandoned.  If the approach in that PR is acceptable, I can raise a new PR and fix the issues mentioned.

However, one issue raised was to have a unique fringe marker.  I have not been able to find the code that defines the current marker, so haven't been able to experiment.  Only the solid like really stands out for me so far, especially with the fringe moved to the left of the line numbers.

Another option would be to have the fringe highlighted for every line of the evaluated expression, rather than just the first line.  Again, I looked at the code for a while in cider-overlays.el but didn't understand how the current fringe is put at the start of the expression, as the code only talks about `end`.

**Comment by bbatsov** [comment]
@jr0cket Feel free to take this over. 

> However, one issue raised was to have a unique fringe marker. I have not been able to find the code that defines the current marker, so haven't been able to experiment. Only the solid like really stands out for me so far, especially with the fringe moved to the left of the line numbers.

I think all such code is in `cider-overlays.el`. 

> Another option would be to have the fringe highlighted for every line of the evaluated expression, rather than just the first line. Again, I looked at the code for a while in cider-overlays.el but didn't understand how the current fringe is put at the start of the expression, as the code only talks about end.

Probably that'd be a bit too much, as the fringe will glow like a Xmas tree in this case.

**Comment by jr0cket** [comment]
Closing as I no longer find this feature useful.  The change in Emacs line numbers puts this marker too far away from the code to be noticeable even if a more bolder icon is used.
