### ISSUE TITLE
eldoc error on windows

### ISSUE THREAD

**Issue by finalpatch** [clojure-emacs/cider#2752]
cider: 0.23
emacs : 27.0.50
clojure: 1.9.0

  Show: Project-Only All 
  Hide: Clojure Java REPL Tooling Duplicates  (28 frames hidden)

  This is an unexpected CIDER middleware error.
  Please submit a bug report via `M-x cider-report-bug`.

  If these stacktraces are occurring frequently, consider using the
  button(s) below to suppress these types of errors for the duration of
  your current CIDER session. The stacktrace buffer will still be
  generated, but it will "pop under" your current buffer instead of
  "popping over". The button toggles this behavior.

 Suppress eldoc-error 

1. Unhandled java.nio.file.InvalidPathException
   Illegal char <:> at index 4:
   file:/C:/Users/final/.m2/repository/overtone/overtone/0.10.6/overtone-0.10.6.jar!/overtone/core.clj

    WindowsPathParser.java:  182  sun.nio.fs.WindowsPathParser/normalize
    WindowsPathParser.java:  153  sun.nio.fs.WindowsPathParser/parse
    WindowsPathParser.java:   77  sun.nio.fs.WindowsPathParser/parse
          WindowsPath.java:   94  sun.nio.fs.WindowsPath/parse
    WindowsFileSystem.java:  255  sun.nio.fs.WindowsFileSystem/getPath
                Paths.java:   84  java.nio.file.Paths/get
             classpath.clj:  122  cider.nrepl.inlined-deps.orchard.v0v5v3.orchard.java.classpath/classpath-file-relative-path
             classpath.clj:  114  cider.nrepl.inlined-deps.orchard.v0v5v3.orchard.java.classpath/classpath-file-relative-path
                  info.clj:  162  cider.nrepl.inlined-deps.orchard.v0v5v3.orchard.info/info*
                  info.clj:  143  cider.nrepl.inlined-deps.orchard.v0v5v3.orchard.info/info*
                  info.clj:   61  cider.nrepl.middleware.info/info
                  info.clj:   50  cider.nrepl.middleware.info/info
                  info.clj:   74  cider.nrepl.middleware.info/eldoc-reply
                  info.clj:   72  cider.nrepl.middleware.info/eldoc-reply
        error_handling.clj:  160  cider.nrepl.middleware.util.error-handling/eval1991/fn
              MultiFn.java:  233  clojure.lang.MultiFn/invoke
                  info.clj:   85  cider.nrepl.middleware.info/handle-info
                  info.clj:   84  cider.nrepl.middleware.info/handle-info
                  Var.java:  385  clojure.lang.Var/invoke
                 nrepl.clj:  181  cider.nrepl/wrap-info/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  363  cider.nrepl/wrap-resource/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  291  cider.nrepl/wrap-out/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  375  cider.nrepl/wrap-spec/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  420  cider.nrepl/wrap-trace/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  438  cider.nrepl/wrap-tracker/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
               session.clj:  272  nrepl.middleware.session/session/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                server.clj:   18  nrepl.server/handle*
                server.clj:   15  nrepl.server/handle*
                server.clj:   27  nrepl.server/handle/fn
                  core.clj: 2022  clojure.core/binding-conveyor-fn/fn
                  AFn.java:   18  clojure.lang.AFn/call
           FutureTask.java:  266  java.util.concurrent.FutureTask/run
   ThreadPoolExecutor.java: 1149  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  624  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  819  java.lang.Thread/run

**Comment by bbatsov** [comment]
@jeffvalk Seems we have some unhandled error in `orchard.java.classpath`. Can you take a look at it?

**Comment by finalpatch** [comment]
apparently there's this "file:/" got added to the beginning of the path and caused the java path parser to fail.

**Comment by finalpatch** [comment]
So I tracked this down to `var-meta`, where it calls `maybe-add-file` then `canonical-source` to get the path for a namespace.  In my case it is 
```
boot.user> (orchard.namespace/canonical-source 'overtone.core)
#object[java.net.URL 0xf8cf4bb9 "jar:file:/C:/Users/final/.m2/repository/overtone/overtone/0.10.6/overtone-0.10.6.jar!/overtone/core.clj"]
```
here you can see the "file:/" which later caused the problem.

**Comment by finalpatch** [comment]
Not sure if this is the best way to fix it but this change does it for me
https://github.com/clojure-emacs/orchard/pull/78

**Comment by finalpatch** [comment]
Another eldoc error case:

1. Unhandled java.nio.file.InvalidPathException
   Illegal char <*> at index 0: *cider-repl
   Desktop/play.overtone:localhost:58015(clj)*

This time it seems it's trying to get the path of a function defined in the REPL
