### ISSUE TITLE
Debugger support for 'break on exception'

### ISSUE THREAD

**Issue by alendit** [clojure-emacs/cider#2754]
**Is your feature request related to a problem? Please describe.**

It's helpful to examine the state of the program at the moment when something exceptional occurs. Stacktraces alone don't provide enough information, like the value of the variables at the exception time.

**Describe the solution you'd like**

An option to set a breakpoint on exception, similar to SLBD (or even GDB or node debugger).

**Describe alternatives you've considered**

Wrapping the point of exception in a try-form and setting breakpoint on except. Kind of works, but only (1) in your own source code (not on exceptions thrown in libraries) (2) only after you known the position in the code which throws.

**Additional context**

I'm sure that this is a very common request and that there is some really good technical reason, why it wasn't implemented here. But I didn't find any issues tracking it, so I though I'll make one.

**Comment by bbatsov** [comment]
@Malabarba can you share some thoughts what would it take to implement this? I don't recall if we've discussed it in the past, but I know that people ask about this from time to time.

**Comment by Malabarba** [comment]
There are two ways I could see this feature going:

- Debug the exception wherever it happens, as close to the throw statement as possible.
- Mark one or more functions for debugging, and enter the debugger when an exception happens during the execution of those functions (the place of the debugging would be the place inside those functions that caught the exception).

The first item I have no idea how to do. The second item can be done by defining a new breakpoint macro. 

The debugger works by walking around the code and wrapping anything that looks interesting in a breakpoint macro that will do a number of things (pause excution, ask for user input , etc). You can invoke the instrumenter with a different macro, which wraps the code in a try  catch block and will only ask for user input if it catches an exception.

**Comment by alendit** [comment]
I found it useful to start cider with `(setenv "JAVA_OPTS" "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044")` and connect with a remote debugger. I used IDEA, since I am not sure if `dap-mode` supports breaking on exceptions. It's not ideal and far cry from the SLDB experience, but can help to find the causes of strange exceptions.

**Comment by yuhan0** [comment]
Could the stale bot config be changed to exclude issues with "help wanted" and "bug" tags? 

Closing stale issues only decreases their visibility, I've seen a few outstanding bug reports that have been closed by stalebot and they don't turn up in a default search of the issues - once I almost ended up filing a duplicate bug report because of this.

**Comment by lyderichti59** [comment]
Hey, is there any news on this one ? What would it take to implement it ? I would really love to have such a feature
