### ISSUE TITLE
Autocomplete doesn't work for the automatic REPL variables (*1, *2, *3)

### ISSUE THREAD

**Issue by alendit** [clojure-emacs/cider#2755]
## Expected behavior

`(.$ *1)` with the caret position at `$` should return the autocompletion list for the value in `*1`.

## Actual behavior

`(.$ *1)` returns a generic list of all functions in namespace.

## Steps to reproduce the problem

1. `(java.lang.String. "asdf")` `# C-M-x`
2. ` (.$ *1)`

### CIDER version information

```
;; CIDER 0.24.0snapshot (package: 20191103.1528), nREPL 0.6.0
;; Clojure 1.10.0, Java 11.0.5
```

### Lein/Boot version

Lein 2.9.1

### Emacs version

26.3

### Operating system

OS X Catalina

**Comment by bbatsov** [comment]
How is what you described specific to `*1`? We don't really factor in the type of the receiver object anywhere in the completion currently. @alexander-yakushev Please, correct me if I'm wrong.

**Comment by alendit** [comment]
`(def x (java.lang.String. "asdf"))` and then `(.$ x)` works just as you would expect, i.e. it give the list of java methods.
