### ISSUE TITLE
Keyboard shortcuts not highlighted on Debugger help page

### ISSUE THREAD

**Issue by joncol** [clojure-emacs/cider#2761]
## Expected behavior

Keyboard bindings should be properly highlighted in the documentation.

## Actual behavior

On the page https://docs.cider.mx/cider/debugging/debugger.html, the keyboard shortcuts are not highlighted. See attached screenshot:
![wrong](https://user-images.githubusercontent.com/194062/69889128-a00e5900-12ef-11ea-9afe-59c507e0733a.png)

## Steps to reproduce the problem

Just go to: https://docs.cider.mx/cider/debugging/debugger.html.

## Environment & Version information

Browser: Chrome Version 78.0.3904.108.

### Operating system

Arch Linux

**Comment by bbatsov** [comment]
That's for spotting this!
