### ISSUE TITLE
Can clojuredocs-edn-export be hosted  by CIDER team?

### ISSUE THREAD

**Issue by liquidz** [clojure-emacs/cider#2762]
@bbatsov 
Currently [clojuredocs-export-edn](https://clojuredocs-edn.netlify.com/) is hosted by my private account on [netlify](https://www.netlify.com).
- c.f.
  - #2663 
  - https://github.com/liquidz/clojuredocs-export-edn

And in the current billing period, bandwidth may exceed. (reached 50% 5 days ago)
![2019-11-30 17 22 10 app netlify com 036934029b31](https://user-images.githubusercontent.com/6941/69897992-8d029400-1396-11ea-8a35-b0b035a3f24c.png)

GitHub Pages also have a [100GB bandwidth limitation](https://help.github.com/en/github/working-with-github-pages/about-github-pages#guidelines-for-using-github-pages), so is it possible to host export-edn on the CIDER team side?

I can buy extra bandwidth([$20/100GB](https://www.netlify.com/pricing/)) provisionally, so it would be happy to consider it.

**Comment by bbatsov** [comment]
Sure. I'd be happy to for us to cover the expense for running it. I guess we'll need to transfer the project to `clojure-emacs` and then you can tell me how exactly to deploy it.

**Comment by liquidz** [comment]
@bbatsov Thanks! I'm glad to hear that!
To transfer this project, could you add a temporal permission to create public repositories on `clojure-emacs`?
![image](https://user-images.githubusercontent.com/6941/69906963-49983c00-140f-11ea-85f6-98d08a900703.png)

> you can tell me how exactly to deploy it.

I added exact steps to README :)
https://github.com/liquidz/clojuredocs-export-edn#how-to-deploy-to-netlify

BTW do you have a team in Netlify?
https://docs.netlify.com/accounts-and-billing/team-management/team-owned-sites/#transfer-sites-between-teams
If you have and can add me as a temporal member, I can also transfer `clojuredocs-edn` site to your team.

**Comment by bbatsov** [comment]
> To transfer this project, could you add a temporal permission to create public repositories on clojure-emacs?

I've actually made you a permanent member of the team working on `cider-nrepl` and `orchard`. :-) You should be able to transfer the repo now. 

> BTW do you have a team in Netlify?

I haven't used it yet, but I'll create a team now.

**Comment by bbatsov** [comment]
I just signed up, so I guess you can transfer the project there to `bbatsov` as well.

**Comment by liquidz** [comment]
@bbatsov 
> I've actually made you a permanent member of the team working on cider-nrepl and orchard. :-) You should be able to transfer the repo now.

Thanks! But `You don’t have the permission to create public repositories on clojure-emacs` error is still there.

> I just signed up, so I guess you can transfer the project there to bbatsov as well.

It seems to need asking in a forum to transfer site.
* https://github.com/netlify/ask-netlify/issues/47#issuecomment-546873640
* https://community.netlify.com/t/site-transfer-to-new-owner/5070

Did you sign up with `bozhidar@batsov.com`?
I'll ask to transfer site in the forum.

**Comment by liquidz** [comment]
> But You don’t have the permission to create public repositories on clojure-emacs error is still there.

Sorry! I didn't join the organization.
I just transfered repo.

**Comment by bbatsov** [comment]
> Did you sign up with bozhidar@batsov.com?

`bozhidar.batsov@gmail.com`

**Comment by liquidz** [comment]
@bbatsov I requested to transfer my site to your account.
I communicated with support members, so I think it will be transfered shortly.
https://community.netlify.com/t/site-transfer-request/5748

**Comment by liquidz** [comment]
@bbatsov I received a message of transfering completion.
Could you confirm your netlify account?

**Comment by bbatsov** [comment]
@liquidz Seems we're good. Now you just have to tell me where to attach this billing, as all I could find was to upgrade my account to pro for 50$/month and I guess we're trying to do something else.

**Comment by liquidz** [comment]
@bbatsov Thanks!

In current billing cycle, it seems the site's bandwidth is belongs to my team even if the site is transferred.
![20191207_214016](https://user-images.githubusercontent.com/6941/70374829-88138680-193a-11ea-90e3-f3980629840b.jpg)

And extra bandwidth seems to be applied automatically when it exceed the plan's limit.

https://www.netlify.com/blog/2019/02/26/netlify-and-bandwidth/
> Extra bandwidth can be purchased in blocks of 100GB/mo for $20 each. Starting in April, these charges will automatically be applied as you consume bandwidth beyond your plan limits.

So there seems to be nothing you can do in this billing cycle(Nov 10 to Dec 10).

**Comment by bbatsov** [comment]
I guess we can close this one.
