### ISSUE TITLE
Unclear indentation specification example

### ISSUE THREAD

**Issue by joncol** [clojure-emacs/cider#2763]
## Expected behavior

I was expecting to make sense of the last example at:
https://docs.cider.mx/cider/indent_spec.html#_examples

## Actual behavior

I didn't make any sense of the following:

![q](https://user-images.githubusercontent.com/194062/69901692-19a45680-1385-11ea-9846-46dcedd368ce.png)

```
The first arg has an indent spec of , which means all forms inside the first arg have an indent spec of [:defn].
```
Is this a typo or is it intentional? It says that the first arg has an empty indent spec? Can this be made any clearer, perhaps?

**Comment by yuhan0** [comment]
Looking at the raw .adoc file, the actual spec is `[1 [[:defn]] :form]`, and it's an issue with the markup renderer attempting to do variable substitution with the `[[]]` syntax.

I'm not too familiar with Asciidoc, but it looks like either literal syntax or backslash escaping would work here:
```
`+[1 [[:defn]] :form]+`
`[1 \[[:defn]] :form]`
```
