### ISSUE TITLE
Use ciders eval to auto complete keys in hash maps.

### ISSUE THREAD

**Issue by olymk2** [clojure-emacs/cider#2770]
**Is your feature request related to a problem? Please describe.**

You don't get auto complete on keys in a map, understandably 

**Describe the solution you'd like**

A way to inject keys into the current document, so your editors buffer based auto complete kicks in.

**Describe alternatives you've considered**

Not sure of other ways this could be achieved

**Additional context**

Basically I was thinking could we hook into ciders eval test if the result is a map run (keys map) on the result then union into a comment block at the top of the buffer.

````
;; keys one four three six two

(defun fetch-comment-key-lookups () 
  (beginning-of-buffer) 
  (search-forward ";; keys ") 
  (split-string  (buffer-substring-no-properties 
                  (point) 
                  (line-end-position))))


(defun insert-updated-key-lookups (key-list)
  (save-excursion (let ((new-keys (delete-dups (append (split-string (fetch-comment-key-lookups))
                                                       key-list)))) 
                    (beginning-of-buffer) 
                    (search-forward ";; keys ") 
                    (kill-line) 
                    (insert  (mapconcat 'identity new-keys " ")))))
````

This seems like a really nice feature to have, is it possible to do something like this, I know cider is written to be extendable, I would not know where to start or if this is something you think would be handy to have in cider, perhaps there are other solutions to this problem ?

**Comment by bbatsov** [comment]
I'm a bit confused as to what exactly you're suggesting. Can you share some example illustrating the desired behaviour?
