### ISSUE TITLE
cider-pprint-eval-last-sexp doesn't pprint in clojurescript

### ISSUE THREAD

**Issue by ftravers** [clojure-emacs/cider#2776]
## Expected behavior
cider-pprint-eval-last-sexp, should pretty print.

## Actual behavior
it just prints, no carriage returns for long lists, etc...

## Steps to reproduce the problem

With data: 

```
[{:a-very-long-key 132423423423423423}
 {:a-very-long-key 132423423423423423}]
|
```

and cursor at position |, run command `cider-pprint-eval-last-sexp`, and output is:

```
[{:a-very-long-key 132423423423423423}
 {:a-very-long-key 132423423423423423}]
|
 [{:a-very-long-key 132423423423423420} {:a-very-long-key 132423423423423420}] 
```

when it should be:

```
[{:a-very-long-key 132423423423423423}
 {:a-very-long-key 132423423423423423}]
|
 [{:a-very-long-key 132423423423423420} 
  {:a-very-long-key 132423423423423420}] 
```

### CIDER version information

```
;; CIDER 0.24.0snapshot (package: 20200101.839), nREPL 0.6.0
;; Clojure 1.10.1, Java 10.0.2

```

### Emacs version
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29

### Operating system

╰─$ uname -a
Linux ss9 5.4.6-arch3-1 #1 SMP PREEMPT Tue, 24 Dec 2019 04:36:53 +0000 x86_64 GNU/Linux

**Comment by ak-coram** [comment]
This is probably related to #2667
