### ISSUE TITLE
cider-jack-in-clj can't find cider-nrepl

### ISSUE THREAD

**Issue by hackeryarn** [clojure-emacs/cider#2780]
## Expected behavior

I expect `cider-jack-in-clj` and `cider-jack-in-cljs` to connect without errors.

## Actual behavior

Every time I connect, I get the below message:

```
WARNING: CIDER requires cider-nrepl to be fully functional. Some features will not be available without it!
```

## Steps to reproduce the problem

This is a fresh install and I tried runnin jack-in without manually requring `cider/cider-nrepl`, as suggested in the guide. When that failed, I also tried to set it manually in my project's `:dev` profile and in the `:repl` profile inside `~/.lein/profiles.clj`. None of these methods made any difference

### CIDER version information

```
;; CIDER 0.24.0snapshot (package: 20200109.1720), nREPL 0.6.0
;; Clojure 1.10.1, Java 1.8.0_232
```
`cider-nrepl` version that gets included with jack in is 0.23.0-SNAPSHOT. Version 0.24.0-SNAPSHOT to match `cider` version doesn't seem to exist. 

### Lein/Boot version

lien: 2.9.1

### Emacs version

26.3

### Operating system

Pop!_OS 19.10 (Essentially Ubuntu 19.10)

**Comment by dpsutton** [comment]
Hi fellow pop os user! Can you provide a bit of information? When you jack in, the repl should have the startup command printed out. Can you put that startup command here?

I'm also a bit suspicious that it doesn't work when you include cider-nrepl manually in the project. Is there anything special with this project? Docker involved or remote machines?

**Comment by hackeryarn** [comment]
Absolutely. Here is the command jack-in tries to run:

```
/usr/local/bin/lein update-in :dependencies conj \[nrepl\ \"0.6.0\"\] -- update-in :dependencies conj \[cider/piggieback\ \"0.4.2\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.23.0-SNAPSHOT\"\] -- repl :headless :host localhost
```

Nothing too weird going on. It is primarily a cljs project, but nothing crazy going on with the environment.

Here is a snippet from my dev profile. The only thing I found strange is that I had include `piggieback` and `tools.nrepl` to get the cljs build to work correctly.

```
{:dev
   {:dependencies [[figwheel "0.5.19"]
                   [figwheel-sidecar "0.5.19"]
                   [cider/piggieback "0.4.2"]
                   [binaryage/devtools "0.9.10"]
                   [org.clojure/tools.nrepl "0.2.13"]]
    :plugins [[lein-figwheel "0.5.19"]
              [lein-kibit "0.1.6"]
              [jonase/eastwood "0.3.5"]
              [lein-bikeshed "0.5.2"]
              [lein-pprint "1.2.0"]]
    :source-paths ["dev"]
    :repl-options {:nrepl-middleware [cider.piggieback/wrap-cljs-repl]}
  ```

**Comment by dpsutton** [comment]
try getting rid of that acient tools.nrepl. CIDER brings it along on its own but the tools.nrepl 0.2.13 and nrepl 0.6.0 will conflict

**Comment by hackeryarn** [comment]
Good call! That actually really sped up my repl's build time, but still the same message...

**Comment by hackeryarn** [comment]
I also noticed another issue. Even though the repl is running, if I try to send stuff to it I get:

```
No cljs REPLs found in current session "project/clj:localhost:44413" 
```

That address does match the repl address that's running too.

**Comment by hackeryarn** [comment]
Thanks for all the help @dpsutton. The Issue was in my `project.clj` after all. The default build had `:implicits false`. I fixed the issue by adding `:implicits true` to by `:dev` profile.
