### ISSUE TITLE
jack-in-clj&cljs should ask for two build tools if present

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/cider#2786]
**Is your feature request related to a problem? Please describe.**

Imagine a project with lein on the backend and shadow-cljs on the frontend. You would like to be able to run `cider-jack-in-clj&cljs` and be up and running on both front and backends. However, this workflow only asks for which buildtool you would like to use once rather than twice.

You can separately jack-in-clj choosing lein and then jack-in-cljs choosing shadow-cljs.

**Describe the solution you'd like**

Perhaps we could ask for clj buildtool and cljs buildtool if multiple are present rather than once.

**Describe alternatives you've considered**
i haven't really considered other possibilities. We could try to infer that shadow-cljs is always cljs so lein and shadow-cljs are the only choices for front and backend but this probably adds extra code and assumptions that will be annoying when this is not desired.

**Additional context**

**Comment by bbatsov** [comment]
The problem with your proposal is that if you use two different tools you'd end up with two different nREPL servers and if effect your Clojure and ClojureScript REPLs will be completely detached. I guess in such cases it's better to just do two separate jack-ins, anyways.

**Comment by dpsutton** [comment]
oh good point. i didn't realize it was for sharing the same underlying connection.
