### ISSUE TITLE
cider-jack-in doesn't load java classes?

### ISSUE THREAD

**Issue by ackerleytng** [clojure-emacs/cider#2790]
## Expected behavior

`cider-jack-in` and then `cider-load-buffer` should load the buffer's code and all dependencies

## Actual behavior

Some dependency doesn't seem to be loaded

## Steps to reproduce the problem

Create two files

`src/core.clj`

```
(ns example
  (:require [cljfx.api :as fx]))
```

`deps.edn`

```
{:deps
 {cljfx {:mvn/version "1.6.2"}}}
```

Open `src/core.clj` in emacs, then do `cider-jack-in` and `cider-load-buffer`.

I'm seeing

```
1. Caused by java.lang.ClassNotFoundException
   javafx.event.EventHandler

       URLClassLoader.java:  471  java.net.URLClassLoader/findClass
   DynamicClassLoader.java:   69  clojure.lang.DynamicClassLoader/findClass
<... elided ...>
```

If I were to start the repl on a terminal instead, with 

```
clojure -Sdeps '{:deps {cider/cider-nrepl {:mvn/version "0.22.4"}}}' -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]" 
``` 

And then do `cider-connect`, the same source files load fine.

## Environment & Version information

+ Arch Linux, 5.4.14-arch1-1

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.23.0 (Lima), nREPL 0.6.0
;; Clojure 1.10.1, Java 11.0.6
```

### Lein/Boot version

Using tools.deps

### Emacs version

GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-30

*E.g. 24.5* (use <kbd>M-x emacs-version</kbd> to check it if unsure)

### Operating system

+ Arch Linux, 5.4.14-arch1-1

**Comment by bbatsov** [comment]
I'll try to reproduce this tomorrow, but in general I can't see how something like this might be happening (especially given the fact that in both cases the REPL is started with the same command).

**Comment by ackerleytng** [comment]
Thanks! Could it be something to do with the directory in which the command is run? How do I check which directory this command is run?
