### ISSUE TITLE
Setting *print-meta* to true does not cause metadata to be printed in CIDER repl

### ISSUE THREAD

**Issue by jhacksworth** [clojure-emacs/cider#2791]
## Expected behavior

Setting `*print-meta*` to `true` in a CIDER repl should cause metadata to be printed.

## Actual behavior

Metadata is only printed for vars.

## Steps to reproduce the problem

Run `M-x cider-jack-in-clj` without a project to get to a CIDER repl, then try the following. Note that metadata is not printed when evaluating `xs`, but it does get printed for `#'xs`:

```clojure
user> (set! *print-meta* true)
true
user> (with-meta [1 2 3] {:foo "bar"})
[1 2 3]    ;; <--- MISSING METADATA
user> (def xs (with-meta [1 2 3] {:foo "bar"}))
^{:line 50, :column 7, :file "*cider-repl ~:localhost:59980(clj)*", :name xs, :ns #namespace[user]} #'user/xs
user> xs
[1 2 3]    ;; <--- MISSING METADATA
user> #'xs ;; <--- VAR METADATA IS PRINTED --v
^{:line 50, :column 7, :file "*cider-repl ~:localhost:59980(clj)*", :name xs, :ns #namespace[user]} #'user/xs
```

Compare with the output from a bare `$ lein repl` started from a shell, where `*print-meta*` works as expected:

```clojure
user=> (set! *print-meta* true)
true
user=> (with-meta [1 2 3] {:foo "bar"})
^{:foo "bar"} [1 2 3] 
user=> (def xs (with-meta [1 2 3] {:foo "bar"}))
^{:line 1, :column 1, :file "NO_SOURCE_PATH", :name xs, :ns #object[clojure.lang.Namespace 0x12bda6a "user"]} #'user/xs
user=> xs
^{:foo "bar"} [1 2 3]
user=> #'xs
^{:line 1, :column 1, :file "NO_SOURCE_PATH", :name xs, :ns #object[clojure.lang.Namespace 0x12bda6a "user"]} #'user/xs
```

### CIDER version information

Output when running a CIDER repl:

```
;; CIDER 0.24.0snapshot, nREPL 0.6.0
;; Clojure 1.10.0, Java 12
```

### Lein/Boot version

Lein version:

```
$ lein version
Leiningen 2.9.1 on Java 12 OpenJDK 64-Bit Server VM
```

### Emacs version

Emacs 26.3

### Operating system

MacOS "Mojave" 10.14.6

**Comment by jhacksworth** [comment]
This appears to be [due to a bug](https://clojure.atlassian.net/browse/CLJ-1445) in `clojure.pprint/pprint`, which is the default pretty-printing function in CIDER.

According to https://docs.cider.mx/cider/usage/pretty_printing.html

> [Set `cider-print-fn` to] `nil` to defer to nREPL to choose the printing function. This will use the bound value of `nrepl.middleware.print/*print-fn*`, which defaults to the equivalent of `clojure.core/pr`.

After trying:

```elisp
(setq cider-print-fn nil)
```

I got the same output as I did in the bare `$ lein repl`, with proper printing
of the metadata.

**Comment by bbatsov** [comment]
Thanks for following up here! Probably it makes sense to update the docs to mention this.

**Comment by jhacksworth** [comment]
@bbatsov Thanks for adding the documentation and a big thanks for your extensive contributions to open source! 🍻

**Comment by bbatsov** [comment]
You're welcome! 🍻
