### ISSUE TITLE
`make test` issue related to buttercup

### ISSUE THREAD

**Issue by FiV0** [clojure-emacs/cider#2799]
`make test` fails with 
```
cask exec buttercup -L . -L ./test/utils/
Spies can only be created in ‘before-each’
Makefile:68: recipe for target 'test' failed
make: *** [test] Error 255
```

I think this might be related to https://github.com/jorgenschaefer/emacs-buttercup/issues/122
as this was closed recently.  @bbatsov you also commented in that thread. 

### CIDER version information

```
;; CIDER 0.24.0 (package: 20191103.1528) (India), nREPL 0.6.0
;; Clojure 1.10.0, Java 11.0.6
```

### Lein/Boot version

not relevant

### Emacs version

26.3

### Operating system

Ubuntu 18.04

**Comment by bbatsov** [comment]
Yeah, this definitely seems related. We'll probably have to update the tests to account for the upstream changes in buttercup.

**Comment by bbatsov** [comment]
Fixed in https://github.com/clojure-emacs/cider/pull/2804
