### ISSUE TITLE
error in process filter: Clojure-only operation requested in a ClojureScript buffer. 

### ISSUE THREAD

**Issue by zendevil** [clojure-emacs/cider#2805]
When I hit C-c C-k in the ClojureScript buffer, I get the following, at which point emacs hangs for a second: "error in process filter: Clojure-only operation requested in a ClojureScript buffer. "

**Comment by bbatsov** [comment]
What's the entire stacktrace? Loading a buffer is not a Clojure-only operation, so it seems to me something else got invoked.

**Comment by zendevil** [comment]
In *Messages* I just get the sole line. Is there another stack trace? Where do I find it?

**Comment by kolharsam** [comment]
@zendevil try using the `cider-stacktrace-mode` to see the entire stacktrace while evaluating expressions on your REPL. Use this [doc](https://docs.cider.mx/cider/usage/navigating_stacktraces.html), to help you navigate through this mode.
