### ISSUE TITLE
#1971 closed by bot but still a problem

### ISSUE THREAD

**Issue by pdenno** [clojure-emacs/cider#2806]
I would like to reopen #1971 but I don't see how. (Reading a bit, I probably am not allowed). My comment in that issue from yesterday provides an example map that demonstrates the bug.

**Comment by bbatsov** [comment]
Nobody expressed interest in tackling this for a very long time and the ticket is low on my todo list. I can reopen it, but this doesn't change the fact that we need someone willing to work on it.

**Comment by pdenno** [comment]
I am not that much of a elisp programmer, but I'd be willing to give it a try. Do you think I am correct in assuming that it is clojure-mode.el? I hit the bug 10 times a day and it seems to be due to using '|' in strings.

```
(defun clojure-string-start (&optional regex)
  "Return the position of the \" that begins the string at point.
If REGEX is non-nil, return the position of the # that begins the
regex at point.  If point is not inside a string or regex, return
nil."
  (when (nth 3 (syntax-ppss)) ;; Are we really in a string?
    (save-excursion
      (save-match-data
        ;; Find a quote that appears immediately after whitespace,
        ;; beginning of line, hash, or an open paren, brace, or bracket
        (re-search-backward "\\(\\s-\\|^\\|#\\|(\\|\\[\\|{\\)\\(\"\\)")
        (let ((beg (match-beginning 2)))
          (when beg
            (if regex
                (and (char-before beg) (eq ?# (char-before beg)) (1- beg))
              (when (not (eq ?# (char-before beg)))
                beg))))))))```

**Comment by bbatsov** [comment]
Yeah, you're on the right track. I'll close this ticket and reopen the original one, though, so that all the relevant convo is in the same place.
