### ISSUE TITLE
NullPointerException when autocompleting in Clojurescript

### ISSUE THREAD

**Issue by glittershark** [clojure-emacs/cider#2808]
Using shadow-cljs with tools.deps and the following middleware:
```clojure
:middleware [refactor-nrepl.middleware/wrap-refactor
             cider.nrepl/cider-middleware
             cider.piggieback/wrap-cljs-repl]
```

With the following deps:
```clojure
{cider/cider-nrepl {:mvn/version "0.23.0-SNAPSHOT"}
 cider/piggieback {:mvn/version "0.4.2"}
 refactor-nrepl {:mvn/version "2.5.0-SNAPSHOT"}}
```

```

  Show: Project-Only All 
  Hide: Clojure Java REPL Tooling Duplicates  (95 frames hidden)

  This is an unexpected CIDER middleware error.
  Please submit a bug report via `M-x cider-report-bug`.

  If these stacktraces are occurring frequently, consider using the
  button(s) below to suppress these types of errors for the duration of
  your current CIDER session. The stacktrace buffer will still be
  generated, but it will "pop under" your current buffer instead of
  "popping over". The button toggles this behavior.

 Suppress complete-error 

1. Unhandled java.lang.NullPointerException
   (No message)

    complete_for_nrepl.clj:  119  cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.complete-for-nrepl/node-env?
    complete_for_nrepl.clj:  106  cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.complete-for-nrepl/node-env?
    complete_for_nrepl.clj:  126  cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.complete-for-nrepl/ensure-suitable-cljs-is-loaded/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  665  clojure.core/apply
                  core.clj: 1973  clojure.core/with-bindings*
                  core.clj: 1973  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    complete_for_nrepl.clj:  123  cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.complete-for-nrepl/ensure-suitable-cljs-is-loaded
    complete_for_nrepl.clj:  121  cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.complete-for-nrepl/ensure-suitable-cljs-is-loaded
    complete_for_nrepl.clj:  181  cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.complete-for-nrepl/handle-completion-msg!
    complete_for_nrepl.clj:  164  cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.complete-for-nrepl/handle-completion-msg!
    complete_for_nrepl.clj:  202  cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.complete-for-nrepl/complete-for-default-cljs-env
    complete_for_nrepl.clj:  195  cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.complete-for-nrepl/complete-for-default-cljs-env
    complete_for_nrepl.clj:  232  cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.complete-for-nrepl/complete-for-nrepl
    complete_for_nrepl.clj:  227  cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.complete-for-nrepl/complete-for-nrepl
              complete.clj:   15  cider.nrepl.middleware.complete/cljs-complete
              complete.clj:   11  cider.nrepl.middleware.complete/cljs-complete
              complete.clj:   23  cider.nrepl.middleware.complete/complete
              complete.clj:   17  cider.nrepl.middleware.complete/complete
              complete.clj:   34  cider.nrepl.middleware.complete/complete-reply
              complete.clj:   33  cider.nrepl.middleware.complete/complete-reply
        error_handling.clj:  160  cider.nrepl.middleware.util.error-handling/eval45350/fn
              MultiFn.java:  234  clojure.lang.MultiFn/invoke
              complete.clj:   46  cider.nrepl.middleware.complete/handle-complete
              complete.clj:   45  cider.nrepl.middleware.complete/handle-complete
                  Var.java:  388  clojure.lang.Var/invoke
                 nrepl.clj:  117  cider.nrepl/wrap-complete/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  363  cider.nrepl/wrap-resource/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  401  cider.nrepl/wrap-test/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  167  cider.nrepl/wrap-format/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  420  cider.nrepl/wrap-trace/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  467  cider.nrepl/wrap-xref/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  449  cider.nrepl/wrap-undef/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  391  cider.nrepl/wrap-stacktrace/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  457  cider.nrepl/wrap-version/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  244  cider.nrepl/wrap-macroexpand/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  103  cider.nrepl/wrap-apropos/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  300  cider.nrepl/wrap-profile/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
    interruptible_eval.clj:  144  nrepl.middleware.interruptible-eval/interruptible-eval/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
               nrepl04.clj:  288  shadow.cljs.devtools.server.nrepl04/shadow-init/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  137  cider.nrepl/wrap-debug/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  163  cider.nrepl/wrap-enlighten/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  375  cider.nrepl/wrap-spec/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:   95  cider.nrepl/wrap-slurp/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  257  cider.nrepl/wrap-ns/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
            middleware.clj:  214  refactor-nrepl.middleware/wrap-refactor/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  337  cider.nrepl/wrap-refresh/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  181  cider.nrepl/wrap-info/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
             load_file.clj:   81  nrepl.middleware.load-file/wrap-load-file/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
     fake_piggieback04.clj:   55  cider.piggieback/wrap-cljs-repl/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  438  cider.nrepl/wrap-tracker/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:   83  cider.nrepl/wrap-content-type/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
     fake_piggieback04.clj:   31  cemerick.piggieback/wrap-cljs-repl/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
               nrepl04.clj:  235  shadow.cljs.devtools.server.nrepl04/cljs-load-file/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  291  cider.nrepl/wrap-out/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
               nrepl04.clj:  214  shadow.cljs.devtools.server.nrepl04/cljs-eval/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
               nrepl04.clj:  196  shadow.cljs.devtools.server.nrepl04/cljs-select/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  200  cider.nrepl/wrap-inspect/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                caught.clj:   97  nrepl.middleware.caught/wrap-caught/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  482  cider.nrepl/wrap-clojuredocs/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 print.clj:  234  nrepl.middleware.print/wrap-print/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  111  cider.nrepl/wrap-classpath/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
               session.clj:  326  nrepl.middleware.session/add-stdin/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
               session.clj:  272  nrepl.middleware.session/session/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
               nrepl04.clj:  386  shadow.cljs.devtools.server.nrepl04/start/fn
                server.clj:   18  nrepl.server/handle*
                server.clj:   15  nrepl.server/handle*
                server.clj:   27  nrepl.server/handle/fn
                  core.clj: 2030  clojure.core/binding-conveyor-fn/fn
                  AFn.java:   18  clojure.lang.AFn/call
           FutureTask.java:  266  java.util.concurrent.FutureTask/run
   ThreadPoolExecutor.java: 1149  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  624  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  748  java.lang.Thread/run

```

**Comment by eccentric-j** [comment]
@glittershark Were you able to fix this? I'm having the exact same issue.
On cider-nrepl 0.25.0 alpha.

**Comment by bbatsov** [comment]
Use the follow config:

```
(setq cider-enhanced-cljs-completion-p nil)
```

See https://docs.cider.mx/cider/0.24/cljs/configuration.html#_enhanced_completion for details. //cc @rksm

**Comment by eccentric-j** [comment]
Thanks @bbatsov

**Comment by glittershark** [comment]
Is the root issue here that suitable isn't getting installed? I wonder if adding it to the shadow middleware would fix it as well

**Comment by bbatsov** [comment]
I think the root problem has to do with the fact that shadow doesn't use `piggieback` and its eval middleware interacts poorly with `clj-suitable`. I don't recall any bug reports for using suitable with something else (e.g. figwheel). @rksm can tell you more about this.

**Comment by rksm** [comment]
So we have a separate handler for shadow-cljs (https://github.com/rksm/clj-suitable/blob/master/src/main/suitable/complete_for_nrepl.clj#L207) that used to work just fine but maybe something has changed. I'm a bit pressed for time right now but I'll see if I can look into that over the weekend.

**Comment by eccentric-j** [comment]
Going through the stack trace it seems to point to https://github.com/rksm/clj-suitable/blob/master/src/main/suitable/complete_for_nrepl.clj#L116.

It seems to me that:

```clojure
(-> renv
    class
    .getName
    (string/replace #".*Delegating" ""))
```

Should also use some-> like

```clojure
(some-> renv
        class
        .getName
        (string/replace #".*Delegating" ""))
```

However, I can't tell if I'm treating the cause or a symptom of a larger problem.

**Comment by eccentric-j** [comment]
🤔further inspection makes me think I'm wrong. 

`complete-for-shadow-cljs` does not appear in the stack trace. Instead, it looks like it's using `complete-for-default-cljs-env` because `(shadow-cljs? msg)` returns false?

**Comment by bbatsov** [comment]
And probably that's the root cause of the issue! Thanks for digging into this!

**Comment by joestrkr** [comment]
I am having a similar issue but with a slightly different stacktrace.

`complete_for_nrepl.clj:  217  cider.nrepl.inlined-deps.suitable.v0v3v5.suitable.complete-for-nrepl/complete-for-shadow-cljs
complete_for_nrepl.clj:  207  cider.nrepl.inlined-deps.suitable.v0v3v5.suitable.complete-for-nrepl/complete-for-shadow-cljs
complete_for_nrepl.clj:  231  cider.nrepl.inlined-deps.suitable.v0v3v5.suitable.complete-for-nrepl/complete-for-nrepl
complete_for_nrepl.clj:  227  cider.nrepl.inlined-deps.suitable.v0v3v5.suitable.complete-for-nrepl/complete-for-nrepl
		  complete.clj:   40  cider.nrepl.middleware.complete/complete
		  complete.clj:   30  cider.nrepl.middleware.complete/complete
		  complete.clj:   54  cider.nrepl.middleware.complete/complete-reply
		  complete.clj:   53  cider.nrepl.middleware.complete/complete-reply
	error_handling.clj:  160  cider.nrepl.middleware.util.error-handling/eval20790/fn
		  MultiFn.java:  234  clojure.lang.MultiFn/invoke
		  complete.clj:   66  cider.nrepl.middleware.complete/handle-complete
		  complete.clj:   65  cider.nrepl.middleware.complete/handle-complete
			  Var.java:  388  clojure.lang.Var/invoke
			 nrepl.clj:  132  cider.nrepl/wrap-complete/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  504  cider.nrepl/wrap-clojuredocs/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  420  cider.nrepl/wrap-test/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  196  cider.nrepl/wrap-info/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
interruptible_eval.clj:  157  nrepl.middleware.interruptible-eval/interruptible-eval/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
		 load_file.clj:   81  nrepl.middleware.load-file/wrap-load-file/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  152  cider.nrepl/wrap-debug/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  178  cider.nrepl/wrap-enlighten/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
		   session.clj:  351  nrepl.middleware.session/add-stdin/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  182  cider.nrepl/wrap-format/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  126  cider.nrepl/wrap-classpath/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  471  cider.nrepl/wrap-undef/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  384  cider.nrepl/wrap-resource/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  265  cider.nrepl/wrap-macroexpand/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  321  cider.nrepl/wrap-profile/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  410  cider.nrepl/wrap-stacktrace/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  118  cider.nrepl/wrap-apropos/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  278  cider.nrepl/wrap-ns/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
   piggieback_impl.clj:  362  cider.piggieback/wrap-cljs-repl/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  312  cider.nrepl/wrap-out/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  442  cider.nrepl/wrap-trace/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:   98  cider.nrepl/wrap-content-type/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  215  cider.nrepl/wrap-inspect/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			caught.clj:   97  nrepl.middleware.caught/wrap-caught/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:   28  shadow.cljs.devtools.server.nrepl/shadow-init/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
		nrepl_impl.clj:  222  shadow.cljs.devtools.server.nrepl-impl/handle
		nrepl_impl.clj:  210  shadow.cljs.devtools.server.nrepl-impl/handle
			 nrepl.clj:   40  shadow.cljs.devtools.server.nrepl/middleware/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  110  cider.nrepl/wrap-slurp/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  479  cider.nrepl/wrap-version/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  358  cider.nrepl/wrap-refresh/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  460  cider.nrepl/wrap-tracker/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 print.clj:  234  nrepl.middleware.print/wrap-print/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
		   session.clj:  297  nrepl.middleware.session/session/fn
		middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
			 nrepl.clj:  138  shadow.cljs.devtools.server.nrepl/start/fn
			server.clj:   19  nrepl.server/handle*
			server.clj:   16  nrepl.server/handle*
			server.clj:   36  nrepl.server/handle/fn
			  core.clj: 2030  clojure.core/binding-conveyor-fn/fn
			  AFn.java:   18  clojure.lang.AFn/call
	   FutureTask.java:  264  java.util.concurrent.FutureTask/run
ThreadPoolExecutor.java: 1128  java.util.concurrent.ThreadPoolExecutor/runWorker
ThreadPoolExecutor.java:  628  java.util.concurrent.ThreadPoolExecutor$Worker/run
		   Thread.java:  834  java.lang.Thread/run

`

**Comment by bbatsov** [comment]
@joestrkr See https://github.com/rksm/clj-suitable/issues/15 This problem should not exist in CIDER's `master`, btw.

**Comment by joestrkr** [comment]
@bbatsov Thanks. I guess the end result is the same as using `(setq cider-enhanced-cljs-completion-p nil)`?

**Comment by bbatsov** [comment]
The end result is the same, but this problem could not be suppressed with the config as due to the changes in shadow-cljs, suitable was blowing up when this namespace got required.

**Comment by Ramblurr** [comment]
> @joestrkr See [rksm/clj-suitable#15](https://github.com/rksm/clj-suitable/issues/15) This problem should not exist in CIDER's `master`, btw.

I am using cider 0.26, specifically  from commit 9e117c2ff34b7a63eee87c8bfa93a800bb94add5, and I'm still experiencing this error.

After adding `(setq cider-enhanced-cljs-completion-p nil)` the issue seems resolved.

My reading of the above comments suggests that I shouldn't need to set this variable.. but maybe I mis understood. If so, please excuse the noise.

**Comment by bbatsov** [comment]
As you can see there's no branching anymore https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/complete.clj#L29 in the completion middleware, so I can't imagine how the setting can have any effect for you.

**Comment by Ramblurr** [comment]
:weary: .. because of course I wasn't running the version of cider I thought I was. My apologies.

**Comment by bbatsov** [comment]
No worries!

**Comment by glittershark** [comment]
This is working for me
