### ISSUE TITLE
cider-find-var and cider-find-resource unable to work for finding Java source code on Windows emacs.

### ISSUE THREAD

**Issue by CanftIn** [clojure-emacs/cider#2809]
### Actual behavior
I work on windows, though I have added
 `  (setq cider-jdk-src-paths '("C:/Program Files/Java/jdk1.8.0_171/src"))
` 
into `dotspacemacs/user-config ()` of spacemacs config and install `ag` on Windows, 
the command `,-g-g` and  `,-g-r` not working on me to goto java source code.

The `src` path is the fold where I extract src.zip.
I have no idea where the problem is.
![image](https://user-images.githubusercontent.com/26135447/75330047-a3e45400-58bb-11ea-8ddb-eb5c3764aad7.png)
![image](https://user-images.githubusercontent.com/26135447/75331036-04c05c00-58bd-11ea-93d5-351c816c6485.png)
### Expected behavior
After command `,-g-g` jump to Java source code in the window.

**Comment by jr0cket** [comment]
@CanftIn I took a different approach with a `deps.edn` project https://practicalli.github.io/spacemacs/navigating-code/java-definitions.html

This works for me on Ubuntu Linux.  I don't have windows, so unfortunately cant test, but if you are using a `deps.edn` project it may be worth trying.

**Comment by CanftIn** [comment]
@jr0cket Hi, Thanks for your respond. To be frank, I have noticed your blog before. But I'm just trying it just now.
Yes, It works. I use leiningen to build a project. By adding 
```clojure
(defproject clojure-repl "0.1.0"
  :description "clojure repl"
  :url "http://canftin.com"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.0"]
                 [org.clojure/core.match "1.0.0"]]
  :repl-options {:init-ns clojure-repl.core}
  :java-13-source
  {:extra-deps
   {java-sources {:local/root "C:/Program Files/ava/jdk-13.0.2/lib/src.zip"}}}
  )
```
to `project.clj`. And set up `.dir-locals.el` from your helping code. I can jump to java class source code. And the linux environment WSL also works.

By the way, is there a way to highlight the Java class in clojure file like the picture below? In my file, Java class just looks white color.
Thanks again.
![image](https://user-images.githubusercontent.com/26135447/77284799-7ba91300-6d0a-11ea-8128-f349f620ef26.png)

**Comment by bbatsov** [comment]
> By the way, is there a way to highlight the Java class in clojure file like the picture below? In my file, Java class just looks in white color.

Older version of `clojure-mode` did this, but the syntax-highlighting was unreliable and I removed it at some point.
