### ISSUE TITLE
cider-jack-in-cljs clojure fails on shadow-cljs+deps.edn with "missing instance"

### ISSUE THREAD

**Issue by Quezion** [clojure-emacs/cider#2812]
Attempting to start `cider-jack-in-cljs` via `clojure-cli` in a shadow-cljs project that's using deps.edn causes the CLJS REPL to fail to start.

I have included an example repo to demonstrate this issue at https://github.com/Quezion/re-frame-react-native/tree/demo-cider-deps-clj-err

Note that cider-jack-in-cljs works if you simply select the `shadow-cljs` option with the `shadow` REPL, though this requires the host computer to have `shadow-cljs` installed. The project will also run at command line via `clj -A:shadow-cljs watch app` (albiet without any nREPL injection.)

You may need to run `npm install && cd react-native && npm install` after installing the example repo to get the javascript dependencies.

## Expected behavior

`C-u M-x cider-jack-in-cljs` boots into a functional CLJS nREPL after selecting `clojure-cli` and launching the `:app` build with the alias `-A:shadow-cljs`

## Actual behavior

All test paths give this error as the CLJS REPL loads up the `:app` build:

```
1. Unhandled clojure.lang.ExceptionInfo
   missing instance
   {}
               runtime.clj:   11  shadow.cljs.devtools.server.runtime/get-instance!
               runtime.clj:    8  shadow.cljs.devtools.server.runtime/get-instance!
                   api.clj:  125  shadow.cljs.devtools.api/worker-running?
                   api.clj:  123  shadow.cljs.devtools.api/worker-running?
                   api.clj:  222  shadow.cljs.devtools.api/watch
                   api.clj:  216  shadow.cljs.devtools.api/watch
                   api.clj:  220  shadow.cljs.devtools.api/watch
                   api.clj:  216  shadow.cljs.devtools.api/watch
                      REPL:    1  user/eval22211
                      REPL:    1  user/eval22211
             Compiler.java: 7177  clojure.lang.Compiler/eval
             Compiler.java: 7166  clojure.lang.Compiler/eval
             Compiler.java: 7132  clojure.lang.Compiler/eval
                  core.clj: 3214  clojure.core/eval
                  core.clj: 3210  clojure.core/eval
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   79  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  142  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  171  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  170  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  748  java.lang.Thread/run
```

## Steps to reproduce the problem

1. "C-u M-x cider-jack-in-cljs"
 1a. select project folder
 1b. press enter on default nREPL server command
     "repl -s watch refresh repl -s watch refresh"
 1b. select clojure-cli
 1c. press space and add alias "-A:shadow-cljs" to nREPL server command
     The full server command is included below:
     > nREPL server command: -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware", "cider.piggieback/wrap-cljs-repl"]' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware", "cider.piggieback/wrap-cljs-repl"]' -A:shadow-cljs
2. Prompt "Select ClojureScript REPL type": select shadow
3. Prompt "Select shadow-cljs build": enter/select app

For additional repro steps & output, please see this file included in the demo repository. https://github.com/Quezion/re-frame-react-native/blob/demo-cider-deps-clj-err/cider-repro.txt

### CIDER version information

```
;; CIDER 0.24.0 (India), nREPL 0.6.0
;; Clojure 1.10.1, Java 1.8.0_221
```

### Lein/Boot version

*E.g. Lein 2.6.1* (skip this when you didn't start the nREPL server
using Lein or Boot)

### Emacs version

*GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.2.0)*

### Operating system

*OS X 10.14.6 "Mojave"*

**Comment by dpsutton** [comment]
minimal repro: https://github.com/dpsutton/shadow-with-deps

The two important bits that distinguish this from a standard shadow-cljs project is `:deps true` in shadow-cljs.edn and the deps are in `deps.edn`.

This is a bog standard shadow-cljs app that is managed by deps rather than shadow-cljs. The difficulty lies in that the user or tooling is responsible for starting up shadow-cljs server.

This can be accomplished by starting up the process with the shadow [middleware](https://shadow-cljs.github.io/docs/UsersGuide.html#_embedded_nrepl_server) included:

    /usr/local/bin/clojure -Sdeps '{:deps {nrepl {:mvn/version "0.6.0"} cider/piggieback {:mvn/version "0.4.2"} cider/cider-nrepl {:mvn/version "0.24.0"}}}' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware", "cider.piggieback/wrap-cljs-repl", "shadow.cljs.devtools.server.nrepl/middleware"]'

Then from the repl we have only to start the server and then proceed as normal:

```clj
;; Connected to nREPL server - nrepl://localhost:64852
;; CIDER 0.25.0snapshot, nREPL 0.6.0
;; Clojure 1.10.0, Java 1.8.0_202
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
;;  Startup: /usr/local/bin/clojure -Sdeps '{:deps {nrepl {:mvn/version "0.6.0"} cider/piggieback {:mvn/version "0.4.2"} cider/cider-nrepl {:mvn/version "0.24.0"}}}' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware", "cider.piggieback/wrap-cljs-repl", "shadow.cljs.devtools.server.nrepl/middleware"]'
;;
;; ClojureScript REPL type: shadow
;; ClojureScript REPL init form: (do (require '[shadow.cljs.devtools.api :as shadow]) (shadow/watch :app) (shadow/nrepl-select :app))
;;
Execution error (ExceptionInfo) at shadow.cljs.devtools.server.runtime/get-instance! (runtime.clj:11).
missing instance
user>
user> (require '[shadow.cljs.devtools.server :as server])
nil
user> (server/start!)
Feb 27, 2020 8:51:37 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.7.3.Final
Feb 27, 2020 8:51:37 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.7.3.Final
Feb 27, 2020 8:51:37 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 2.3.2.Final
shadow-cljs - HTTP server available at http://localhost:3000
shadow-cljs - server version: 2.8.83 running at http://localhost:9631
shadow-cljs - nREPL server started on port 65233
:shadow.cljs.devtools.server/started
user> (require '[shadow.cljs.devtools.api :as shadow])
nil
user> (shadow/watch :app)
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (155 files, 1 compiled, 0 warnings, 3.77s)
:watching
user> (shadow/nrepl-select :app)
To quit, type: :cljs/quit
[:selected :app]
cljs.user>
```

The `Execution error` above is from the standard startup command for shadow not finding a running server. We then start it with `(shadow.cljs.devtools.server/start!)` and then invoke the normal startup routine to get a repl.

**Comment by dpsutton** [comment]
It seems the difficulties are:

- if we are a lein or deps managed shadow project, we need to get the middleware injected. Shadow provides a main function to do so but we need our own main function to run. Combining these two is difficult.
- in this managed project we need to start the server before doing the standard build select
- we need a good workflow to prompt for this workflow. we can't just assume when there's two build tools available but don't want to pester the user
- how many people actually work this way?

**Comment by ozFri** [comment]
The "official" re-frame template is set up this way,
https://github.com/day8/re-frame-template

**Comment by FiV0** [comment]
I found the following solution in a proprietary project I have access to which I adapted a bit. Add the following to your `.dir-locals.el`.
```el
((nil . ((cider-clojure-cli-global-options . "-A:dev")
         (cider-default-cljs-repl . custom)
         (cider-custom-cljs-repl-init-form . "(do (user/cljs-repl))")
         (eval . (progn
                   (make-variable-buffer-local 'cider-jack-in-nrepl-middlewares)
                   (add-to-list 'cider-jack-in-nrepl-middlewares "shadow.cljs.devtools.server.nrepl/middleware"))))))
```
in `deps.edn` you do 
```clj
 :aliases
 {:dev
  {:extra-paths ["dev"]
   :extra-deps
   {binaryage/devtools {:mvn/version "0.9.11"}
    cider/piggieback {:mvn/version "0.4.2"}
    thheller/shadow-cljs {:mvn/version "2.8.95"}
    }}}
```
and finally add a this code to `dev/user.clj`
```clj 
(ns user
  (:require [shadow.cljs.devtools.api :as shadow]
            [shadow.cljs.devtools.server :as server]))

(defmacro jit [sym]
  `(requiring-resolve '~sym))

(defn cljs-repl
  ([]
   (cljs-repl :app))
  ([build-id]
   (server/start!)
   (shadow/watch build-id)
   (loop []
     (println "Trying to connect")
     (when (nil? @@(jit shadow.cljs.devtools.server.runtime/instance-ref))
       (Thread/sleep 1000)
       (recur)))
   ((jit shadow.cljs.devtools.api/nrepl-select) build-id)))
```
this should make `shadow-cljs` work with `cider-jack-in-cljs` and the `clojure-cli` option. 
@dpsutton maybe you can add that to the example repo you created. When I find the time I might also add an option to the docs.

**Comment by FiV0** [comment]
Actually realized that all the looping is unnecessary as `shadow/watch` only returns when the compilation finished so you only need something like.
```clj
(defn cljs-repl
  ([]
   (cljs-repl :app))
  ([build-id]
   (server/start!)
   (shadow/watch build-id)
   (shadow/nrepl-select build-id)))
```
