### ISSUE TITLE
Comment behavior 

### ISSUE THREAD

**Issue by cassc** [clojure-emacs/cider#2817]
Line comment not working as expected in older versions. I am not sure if this is related to Cider, please forgive me if I am wrong. 

## Expected behavior
Type `;;` in front of `:x-func`  should comment out `:x-func [#()]` and add a line break after the s-expression

```clojure
{:esc {:view   :program-stat
       :x-func [#()]}}
```
## Actual behavior

Note the s-expression is broken:

```clojure
{:esc {:view   :program-stat
       ;;:x-func [#()]}}
```

### CIDER version information

I tried Cider v0.24.0 stable and v0.25.0-SNAPSHOT both on emacs-prelude.

**Comment by bbatsov** [comment]
That's something that should be addressed in `clojure-mode`, as it's not related to CIDER.

**Comment by cassc** [comment]
Thank you! I reported the issue to [clojure-mode](https://github.com/clojure-emacs/clojure-mode/issues/554)
