### ISSUE TITLE
Warning overwriting value of cider-switch-to-repl-after-insert-p by aliasing to cider-switch-to-repl-on-insert

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#2824]
Hi there, I have a warning here, not a big deal and I can try to have a look at in my free time but I wanted to report it.

Additional piece of info, I am using `cider` in a `use-package` clause.

## Expected behavior
It should not show the warning.

## Actual behavior
It shows the warning.

## Steps to reproduce the problem
Start up emacs with a (compiled) cider version.

Compiled here simply means calling `make`.

### CIDER version information
`master`

### Emacs version
*28.0.50*

**Comment by vemv** [comment]
Our changelog stated:

> * Add new defcustom `cider-switch-to-repl-on-insert`: Set to prevent cursor from going to the REPL when inserting a form in the REPL with the insert-to-repl commands. Replaces obsoleted `cider-switch-to-repl-after-insert-p`

`cider-switch-to-repl-after-insert-p` does not exist anymore.
