### ISSUE TITLE
explore nested expressions in child frame

### ISSUE THREAD

**Issue by andreyorst** [clojure-emacs/cider#2830]
Seen this feature in [Jason Gilman talk](https://www.youtube.com/watch?v=buPPGxOnBnk) about `proto-repl` Atom package. It allows you to explore nested maps, vectors, lists in pop-up window, which I think is quite useful. Emacs has [child-frames](https://www.gnu.org/software/emacs/manual/html_node/elisp/Child-Frames.html), hideshow-mode, and clickable fringe, which I think are the ingredients for this feature.

I will not go for really complex example, so here's a simple map, and we `assoc-in` new value to a nested map in it. Here's what cider displays:

![image](https://user-images.githubusercontent.com/19470159/79065441-feddd900-7cb8-11ea-95f5-a122710f2e9e.png)

This indeed usable, but `proto-repl` takes this concept further:

![image](https://user-images.githubusercontent.com/19470159/79065672-db1b9280-7cba-11ea-8423-b9919d858e81.png)

And I think it makes perfect sense to truncate such output if we provide feature to explore it:

![image](https://user-images.githubusercontent.com/19470159/79065502-63993380-7cb9-11ea-9b5a-f70b24560a2b.png)

There are many different packages that provide interactive stuff through child frames, like [lsp-ui](https://github.com/emacs-lsp/lsp-ui):

![image](https://user-images.githubusercontent.com/19470159/79065566-ff2aa400-7cb9-11ea-9c80-6a65ce1a515a.png)

This popup can be scrolled with mouse, focused and resized. Or [company-posframe](https://github.com/tumashu/company-posframe):

![image](https://user-images.githubusercontent.com/19470159/79065591-46b13000-7cba-11ea-83f1-9a50a47072e4.png)

These are two child frames side by side, we can interact with both by using specific keybindings.

---

Sorry if I missed feature request for this feature, I've searched with `proto` and `proto-repl` queries and found only 1 closed issues that is related to `proto-repl`:

- https://github.com/clojure-emacs/cider/issues/1689

**Comment by bbatsov** [comment]
Have you seen CIDER's inspector (https://docs.cider.mx/cider/0.24/debugging/misc.html#_inspecting_values)?

**Comment by andreyorst** [comment]
No, I haven't. This is quite close to what I've seen in proto-repl. Maybe an option could be added so instead of creating new window inspector could be shown in child frame instead of that overlay? For example if the value is large and truncated

**Comment by bbatsov** [comment]
> inspector could be shown in child frame instead of that overlay? For example if the value is large and truncated

You'll have to expand on this, as I don't understand what do you mean by a child frame. A different frame with a single window for the inspector?

**Comment by andreyorst** [comment]
> You'll have to expand on this, as I don't understand what do you mean by a child frame. A different frame with a single window for the inspector?

Sorry, I don't know how I can elaborate more. I've provided link to Emacs manual describing child frames as:

> Child frames are objects halfway between windows (see Windows) and “normal” frames. Like windows, they are attached to an owning frame. Unlike windows, they may overlap each other—changing the size or position of one child frame does not change the size or position of any of its sibling child frames.

and 2 last screenshots with child frames in use. First screenshot uses child frame to display documentation gathered from LSP. This frame can be resized with mouse, scrolled, and so on, but is on top of Emacs. Second uses 2 childframes, one for completions and the second one for documentation.

These frames are real X windows on top of Emacs.

Cider uses overlay to display evaluation result, which if fine until we get large data structure. I think it will be good idea to truncate everything pretty hard so it won't display multiline overlays, and provide inspector via child frame without needing to create new split.

Here's screenshot of what I mean. Instead of this:  
![image](https://user-images.githubusercontent.com/19470159/80278009-a3214000-86fb-11ea-9c62-96d2e28df4f9.png)

Cider could do this:  
![image](https://user-images.githubusercontent.com/19470159/80277990-7d943680-86fb-11ea-904c-830d6fe1893a.png)

This child frame was created with [posframe](https://github.com/tumashu/posframe) library, but can be done without it. Many packages use posframe, but some, like lsp-ui provide their own code for this freature.

**Comment by andreyorst** [comment]
@bbatsov sorry to ask you here, maybe you've stated this somewhere, but what's the action from issue author is expected when **[@stale](https://github.com/marketplace/stale)** bot marks an issue as stale?

I mean, there are such situations when the issue was reported by someone, but the discussion faded either because issue no longer happens, or because user turned away from using the package, and since the issue is not affecting anyone else it can safely be closed, but there's no one to do it. This is a good case for stale bot to close the issue, but in case of this particular issue, the discussion is kinda unfinished. Is it expected to bump such issues, or should we create new instead?

I understand that you have limited time, and can't answer every question, or every feature request, and I'm not sure if bumping is good or bad, since I'm still interested in this feature. I'm currently planning to explore and implement the solution, but the question is if this is a welcomed feature to CIDER or should be external package?

**Comment by bbatsov** [comment]
> @bbatsov sorry to ask you here, maybe you've stated this somewhere, but what's the action from issue author is expected when @stale bot marks an issue as stale?

Technically speaking any activity on the ticket will remove the "stale" label. 

> I mean, there are such situations when the issue was reported by someone, but the discussion faded either because issue no longer happens, or because user turned away from using the package, and since the issue is not affecting anyone else it can safely be closed, but there's no one to do it. This is a good case for stale bot to close the issue, but in case of this particular issue, the discussion is kinda unfinished. Is it expected to bump such issues, or should we create new instead?

Yeah, that's on me. Sorry about that!

> I understand that you have limited time, and can't answer every question, or every feature request, and I'm not sure if bumping is good or bad, since I'm still interested in this feature. I'm currently planning to explore and implement the solution, but the question is if this is a welcomed feature to CIDER or should be external package?

It'd be a welcome addition to CIDER. 

> This child frame was created with posframe library, but can be done without it. Many packages use posframe, but some, like lsp-ui provide their own code for this freature.

Child frames and postframe look interesting. I wasn't aware of this feature at all until you brought it up. I see that's only available in Emacs 27, though, but that won't be an issue as we can market this as an optional feature. I also assume this doesn't work on Windows at all.

**Comment by vemv** [comment]
I'll close this issue as it isn't quite specific.

OP also stated he hadn't tried the Inspector at the time. Giving it a fair try would seem proportionate, before considering alternatives.

The Inspector is always subject to feedback, and in fact it has received some love recently.

Cheers - V
