### ISSUE TITLE
Could CIDER provide an xref backend instead of hijacking `M-.` and `M-,`?

### ISSUE THREAD

**Issue by stig** [clojure-emacs/cider#2831]
**Is your feature request related to a problem? Please describe.**

I'm frustrated with the way CIDER hijacks `M-.` in all clojure-mode buffers, even for projects where you don't connect to CIDER. I don't always want to connect to CIDER to navigate projects efficiently.

**Describe the solution you'd like**

I would love for CIDER to provide an xref backend instead of hijacking `M-.`, similar to how `clojure-lsp` does. 

My hope is that this would mean xref would present results both from CIDER and `clojure-lsp`, and other backends.

**Describe alternatives you've considered**

A simpler (though less ideal) fix would perhaps be to fall back to `xref-find-definitions` if there's no CIDER connection for the project.

**Additional context**

**Comment by bbatsov** [comment]
Yeah, we can certainly do this. CIDER predates the existence of `xref` in Emacs, which is the reason for the current state of affairs. I meant to play with xref a few times, but never got to doing so. It's mostly a matter of finding time.

**Comment by bbatsov** [comment]
@stig Btw, are there some packages implementing this outside of Emacs that I can take a look at? Or any documentation on the subject?

**Comment by stig** [comment]
I didn't find any documentation, but I appear to have four packages that implements it, according to documentation for `xref-backend-definitions`:

```
[...]
Implementations:

((backend (eql xref-lsp)) identifier) in ‘lsp-mode.el’.

Undocumented

((backend (eql etags)) symbol) in ‘etags.el’.

Undocumented

((backend (eql elisp)) identifier) in ‘elisp-mode.el’.

Undocumented

```

**Comment by bbatsov** [comment]
I've started work on this a while ago, but it turned out to be more involved than I anticipated and I've paused it for now. I plan to revisit this down the road, but anyone's welcome to beat me to it. :-)

**Comment by bbatsov** [comment]
Here's some useful reference https://github.com/pythonic-emacs/anaconda-mode/commit/39b1cf88c8c459901630d248d6135d8644075648

**Comment by jiacai2050** [comment]
@bbatsov Any news for this?

**Comment by bbatsov** [comment]
No progress. I've been pretty busy lately.

**Comment by jiacai2050** [comment]
@bbatsov I would like to try submit a PR to fix this, maybe in two/three weeks.

**Comment by juszczakn** [comment]
This isn't working for me, for some reason. I keep getting the prompt `Visit tags table (default TAGS): /some/path/...`

I'm going to try debugging it, but I'm not really much of an elisp guru /shrug
