### ISSUE TITLE
Keybindings in company-active-map don't work

### ISSUE THREAD

**Issue by teichholz** [clojure-emacs/cider#2832]
## Expected behavior
Most keys in company-active-map to execute the function bound to it. For example for C-n and C-p to navigate the candidates.

## Actual behavior
The (evil) insert-mode bindings are used. 

## Steps to reproduce the problem
Call upon company-complete to get the candidates. Try to interact with them via the keybindings. 

### CIDER version information

```
;; CIDER 0.25.0snapshot, nREPL 0.7.0
;; Clojure 1.10.0, Java 1.8.0_232

```

### Lein/Boot version
Leiningen 2.9.1 on Java 1.8.0_232 OpenJDK 64-Bit Server VM

### Emacs version
Doom Emacs, Emacs 26.3

### Operating system
Manjaro linux

**Comment by bbatsov** [comment]
Probably that's something to do with the extra config in Doom Emacs, as for me those keybindings work jus fine.

**Comment by yuhan0** [comment]
https://github.com/hlissner/doom-emacs/issues/1335

**Comment by teichholz** [comment]
The only fix I found is to rebind them all the time via the company hooks, as suggested in one post of   hlissner/doom-emacs#1335.  Thanks for the link, helped a ton.
