### ISSUE TITLE
Cannot connect to nrepl server using nrepl.transport/edn

### ISSUE THREAD

**Issue by plperron** [clojure-emacs/cider#2837]
## Expected behavior

Cider should connect to nREPL server and communicate using edn transport.

## Actual behavior

Cider fails to stay connected to server.

```
[nREPL] Establishing direct connection to localhost:39483 ...
[nREPL] Direct connection to localhost:39483 established
helm-M-x-execute-command: Sync nREPL request timed out (op clone id 1)
```

## Steps to reproduce the problem

Create the 3 following files in a folder:

``` bash
$ tree -a
.
├── deps.edn
├── foo.clj
└── .nrepl.edn
```

``` bash
$ cat deps.edn 
{:paths ["."]
 :deps {org.clojure/clojure {:mvn/version "1.10.1"}}
 :aliases {:nREPL
           {:main-opts ["-m" "nrepl.cmdline"]
            :extra-deps
            {nrepl/nrepl {:mvn/version "0.7.0"}}}}}
```

``` bash
$ cat .nrepl.edn 
{:bind         "localhost"
 :transport    nrepl.transport/edn}
```

``` bash
$ cat foo.clj
(ns foo)
(defn bar []
  42)
(comment
  (bar))
```

Create a nREPL server 

``` bash
$ clojure -A:nREPL
nREPL server started on port 39483 on host localhost - nrepl+edn://localhost:39483
```

Use `cider-connect-clj` (C-c M-c) to connect on localhost along with the port specified by the nREPL server. The emacs console should print the error shown above in the expected behavior section.

Changing `.nrepl.edn` from `:transport    nrepl.transport/edn` to  `:transport    nrepl.transport/bencode` and following the same procedure works.

### CIDER version information

```
cider-20200420.735
nrepl 0.7.0
Clojure 1.10.1, 
Java openjdk version "11.0.7" 2020-04-14
```

### Emacs version

GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-16

### Operating system

Ubuntu 18.04.4 LTS

**Comment by bbatsov** [comment]
CIDER currently supports only nREPL's bencode transport. Implementing the EDN transport is doable, now that we have `parseedn`, but it's not really on my roadmap. Still, if someone wants to tackle it I'd be happy to help them with it.

**Comment by plperron** [comment]
Thanks for the swift response. I have been curious to discover the orchard for a while. This change seems simple enough as a stepping stone to introduce elisp and cider ecosystems.

1) I'll start with getting minimally familiar with the code;
2) I'll propose a plan and listen to your feedbacks;
3) I'll implement the solution.

**Comment by bbatsov** [comment]
Sounds good to me! 

Basically all that's needed is teaching `nrepl-client.el` about EDN - the logic that currently encodes/decodes bencode messages should be augmented with EDN support. The only tricky part is how to figure out which transport the server is using when connecting to it - perhaps we can just assume bencode and add provisions to select the transport manually if needed.
