### ISSUE TITLE
Krell REPL type?

### ISSUE THREAD

**Issue by dotemacs** [clojure-emacs/cider#2841]
**Is your feature request related to a problem? Please describe.**

Krell https://github.com/vouch-opensource/krell has it's own REPL that needs to have dependencies loaded as per:
https://github.com/vouch-opensource/krell/wiki/nREPL-Piggieback-Cider

To use it, you can do the following:

```emacs-lisp
(setq cider-custom-cljs-repl-init-form
      "(require '[clojure.java.io :as io]
         '[clojure.edn :as edn]
         '[cider.piggieback]
         '[krell.api :as krell]
         '[krell.repl])
(def config (edn/read-string (slurp (io/file \"build.edn\"))))
(krell/build config)
(apply cider.piggieback/cljs-repl (krell.repl/repl-env) (mapcat identity config))")
```
<kbd>M-x cider-jack-in-cljs</kbd>
When prompted for the REPL type provide `custom`.
Then once the connection to iPhone/Android simulator is established, the REPL starts to work.

**Describe the solution you'd like**

This is not a feature request, but rather a discussion.

Should there be a `cider-cljs-repl-type` of `krell`, so that the users can specify it and the above dependencies loaded in for them, much like it's done for figwheel, node, shadow...

What your thoughts/feels about this? Thanks

**Comment by dotemacs** [comment]
Clarification: "has it's own REPL" - the REPL is standard, but the extra dependencies are required.

**Comment by bbatsov** [comment]
> Should there be a cider-cljs-repl-type of krell, so that the users can specify it and the above dependencies loaded in for them, much like it's done for figwheel, node, shadow...

I don't see why not.

**Comment by dotemacs** [comment]
> > Should there be a cider-cljs-repl-type of krell, so that the users can specify it and the above dependencies loaded in for them, much like it's done for figwheel, node, shadow...
> 
> I don't see why not.

Beautiful, I'll bite and take this. Thanks

**Comment by dotemacs** [comment]
I got the changes here, it works:

https://github.com/dotemacs/cider/tree/krell-repl

I want to have:
- some other CIDER users giving it a spin first
- tests

**Comment by KaterMikesch** [comment]
Great stuff. Any news on this? Help needed?

**Comment by dotemacs** [comment]
If you want to test it, that would be great @KaterMikesch 

But otherwise it's pretty much done, feature wise.

It'll only be down to code style issues.

**Comment by dotemacs** [comment]
Created the PR: https://github.com/clojure-emacs/cider/pull/2861

**Comment by KaterMikesch** [comment]
Manual installing this fork as described in "Hacking on Cider" is needed right? Let me see ...

**Comment by dotemacs** [comment]
@KaterMikesch that's right, thanks

**Comment by KaterMikesch** [comment]
Upon `cider-jack-in-cljs` I don't get asked which type of repl should be instantiated. Instead I get the following error message. What can that be?

> error in process sentinel: Could not start nREPL server: Error building classpath. Unable to compare versions for org.clojure/clojurescript: {:mvn/version "1.8.51", :deps/manifest :mvn} and {:git/url "https://github.com/clojure/clojurescript.git", :sha "7ca05517af2fdf698e5f1f23ac38dc45bb5d51e9", :deps/manifest :deps, :deps/root "/Users/axel/.gitlibs/libs/org.clojure/clojurescript/7ca05517af2fdf698e5f1f23ac38dc45bb5d51e9"}

**Comment by dotemacs** [comment]
I'm not sure what exactly you're doing, maybe list out every single step?

I'm asking this because I tested it and had some other people look at it
and it worked without an issue.

**Comment by KaterMikesch** [comment]
Unfortunately, I keep getting this error message:

> [nREPL] Starting server via /usr/local/bin/clojure -Sdeps '{:deps {nrepl {:mvn/version "0.8.0-alpha1"} cider/piggieback {:mvn/version "0.5.0"} refactor-nrepl {:mvn/version "2.5.0"} cider/cider-nrepl {:mvn/version "0.25.3-SNAPSHOT"}}}' -m nrepl.cmdline --middleware '["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware", "cider.piggieback/wrap-cljs-repl"]'
> error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Error building classpath. Unable to compare versions for org.clojure/clojurescript: {:mvn/version "1.8.51", :deps/manifest :mvn} and {:git/url "https://github.com/clojure/clojurescript.git", :sha "538dbe8133895c56f7da84609bcd696c85aa925c", :deps/manifest :deps, :deps/root "/Users/axel/.gitlibs/libs/org.clojure/clojurescript/538dbe8133895c56f7da84609bcd696c85aa925c"}
> 

How can I solve this problem?

**Comment by dotemacs** [comment]
> How can I solve this problem?

In order to solve this problem, it would be good to be able to reproduce it.

To reproduce it, try this: list out every single step that you're performing.

Also the contents of your project, preferably available publicly.

**Comment by KaterMikesch** [comment]
To have it clean, I started with a clean krell tutorial example (AwesomeProject). 
Then I opened core.cljs of that project in Emacs and issued `M-x cider-jack-in-cljs`. Next comes the mentioned error message. 
I have nothing in .clojure/deps.edn.

**Comment by dotemacs** [comment]
@KaterMikesch once you checked out my branch of cider, did you eval every single file in that branch?

Because I suspect that you could be invoking the old instance of cider still loaded by your emacs instance.

**Comment by dotemacs** [comment]
@KaterMikesch I just had a look.

The issue was that the project was pulling in a version of ClojureScript from git while cider piggieback 0.5 was pulling a version of ClojureScript too. From your output above:

> Unable to compare versions for org.clojure/clojurescript: {:mvn/version "1.8.51", :deps/manifest :mvn} and {:git/url "https://github.com/clojure/clojurescript.git", :sha "538dbe8133895c56f7da84609bcd696c85aa925c", :deps/manifest :deps, :deps/root "/Users/axel/.gitlibs/libs/org.clojure/clojurescript/538dbe8133895c56f7da84609bcd696c85aa925c"}

One way that I got this to run was by invoking the startup manually like below (and excluding a version of ClojureScript for piggieback):

```
$ /usr/local/bin/clojure -Sdeps '{:deps {nrepl {:mvn/version "0.8.0-alpha1"} 
cider/piggieback {:mvn/version "0.5.0" :exclusions [org.clojure/clojurescript]} 
refactor-nrepl {:mvn/version "2.4.0"} cider/cider-nrepl {:mvn/version "0.25.3-SNAPSHOT"}}}' 
-m nrepl.cmdline --middleware '["refactor-nrepl.middleware/wrap-refactor", 
"cider.nrepl/cider-middleware", "cider.piggieback/wrap-cljs-repl"]'
```

**Comment by KaterMikesch** [comment]
Thanks a lot for looking into it.

**Comment by Schmoho** [comment]
I'm so sorry if this is inappropriate to ask here,
but I seem to be having the exact same issue and I don't understand exactly what you meant by your response @dotemacs

**Comment by Schmoho** [comment]
So sorry if this is inappropriate to ask here, but I seemed to be having the exact same problem.
So I tried to run the startup you proposed,
but after starting the app I only get a never ending sequence of 
```
[Sun Oct 25 2020 01:40:32.339]  LOG      An error occurred with client socket: failed to connect to /192.168.0.108 (port 5001) from /:: (port 36269): connect failed: ECONNREFUSED (Connection refused)
[Sun Oct 25 2020 01:40:35.384]  LOG      An error occurred with client socket: failed to connect to /192.168.0.108 (port 5001) from /:: (port 41373): connect failed: ECONNREFUSED (Connection refused)
```
with changing from-ports.

I guess this is probably not really a Cider issue, but it's basically where your discussion so far has left me and I don't understand why this is happening at all + google is really noisy with unrelated stuff
