### ISSUE TITLE
Newbie question: cider-jack-in doesn't work in core.clj file of a new lein project

### ISSUE THREAD

**Issue by paladfn** [clojure-emacs/cider#2846]
*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable CIDER and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

**Remove all of the placeholder text in your final report!**

## Expected behavior
In core.clj, I type M-x cider-jack-in and an nREPL opens.

## Actual behavior
[nREPL] Starting server via /home/paladfn/bin/lein update-in :dependencies conj \[nrepl\ \"0.7.0\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.5.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.25.0-alpha1\"\] -- repl :headless :host localhost
[nREPL] server started on 36293
[nREPL] Establishing direct connection to localhost:36293 ...
[nREPL] Direct connection to localhost:36293 established
error in process filter: run-hooks: Symbol’s function definition is void: cider-turn-on-eldoc-mode
error in process filter: Symbol’s function definition is void: cider-turn-on-eldoc-mode

afterwards, in core.clj, try M-x cider-jack-in. I get the response: This is not a REPL or SERVER buffer; is there an active REPL?

## Steps to reproduce the problem
very simple example with a starter project created by 'lein new app'

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### CIDER version information
setup emacs today (May 19th, 2020)

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.12.0snapshot (package: 20160331.421), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_31
```

### Lein/Boot version

*E.g. Lein 2.6.1* (skip this when you didn't start the nREPL server
using Lein or Boot)

### Emacs version

*E.g. 24.5* (use <kbd>M-x emacs-version</kbd> to check it if unsure)

### Operating system

*E.g. Fedora 23, OS X 10.11 "El Capitan", Windows 10, etc*
Ubuntu 19.10 amd64

**Comment by bbatsov** [comment]
I guess you never made it to the REPL buffer, right? (as I see you got error during startup)

> error in process filter: run-hooks: Symbol’s function definition is void: cider-turn-on-eldoc-mode
error in process filter: Symbol’s function definition is void: cider-turn-on-eldoc-mode

Why do you have such hooks? Those functions were removed quite a while ago.
