### ISSUE TITLE
WARNING: CIDER 0.23.0 requires cider-nrepl 0.22.4, but you're currently using cider-nrepl 0.24.0.

### ISSUE THREAD

**Issue by WorldsEndless** [clojure-emacs/cider#2847]
## Expected behavior
Running latest CIDER and latest CIDER-NREPL in a project jack-in works without warnings

## Actual behavior
WARNING: CIDER 0.23.0 requires cider-nrepl 0.22.4, but you're currently using cider-nrepl 0.24.0. The version mismatch might break some functionality!

However, I am actually using cider 0.24.0 according to `cider-version` (see below)

## Steps to reproduce the problem
`cider-jack-in-clj&cljs`

### CIDER version information
```
;; CIDER 0.24.0 (Lima), nREPL 0.6.0
;; Clojure 1.10.1, Java 1.8.0_232
```

### Lein/Boot version

Leiningen 2.9.1 on Java 1.8.0_232 OpenJDK 64-Bit Server VM

### Emacs version

GNU Emacs 26.3 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.12)

### Operating system

Linux OpenSUSE Tumbleweed (rolling distro)

**Comment by WorldsEndless** [comment]
Also, the "More information" repl link 404s to https://docs.cider.mx/cider/0.23.0/troubleshooting.html#_cider_complains_of_the_cider_nrepl_version

**Comment by bbatsov** [comment]
> Running latest CIDER and latest CIDER-NREPL in a project jack-in works without warnings

I'm puzzled. You say you're running the latest CIDER (0.24), but you get warnings that seem to be from CIDER 0.23. I can't imagine how this can be happening.

**Comment by WorldsEndless** [comment]
I agree to the confusion -- as I noticed when making the report, the version of Cider the initial info says when I jack in, compared to what the error says, is a mis-match. I've tried `lein clean` and anything else I can think of to clear my cache, but don't know why it seems to be mis-evaluating my versions.

**Comment by bbatsov** [comment]
How did you install CIDER?

**Comment by WorldsEndless** [comment]
`(use-package cider :ensure t)`

**Comment by bbatsov** [comment]
From MELPA Stable?

**Comment by WorldsEndless** [comment]
Just double-checked: yes.

**Comment by kolharsam** [comment]
@WorldsEndless you could also check your `~/.lein/profiles.clj`?

Does it contain anything like so?

 ```clojure
{:repl {:plugins [[cider/cider-nrepl "0.23.0"]]}}
```
If not, then you could still try using this perhaps?

**Comment by WorldsEndless** [comment]
The error seems to have gone away; it was some assortment of cache clearances and software updates, probably. Sorry I don't know more details.
