### ISSUE TITLE
cider-jump-to puts cursor in awkward position in the navigated-to buffer window

### ISSUE THREAD

**Issue by mrrodriguez** [clojure-emacs/cider#2850]
I have observed that `cider-jump-to` which is called from `cider-find-var` seems to now always put the cursor/point on the last line of the buffer it navigates into. The line is not centered. So it means my point is really low in the buffer and I always forget and can’t find it.

I do not remember this being the case in the past. It used to be I believe centered on the line that was navigated to.

I’m on 0.25.0snapshot of cider, but I think it's been around for a while now.

I typically deal with it by immediately calling `recenter-top-bottom` in the newly navigated to buffer so that my cursor (point) is in a predictable place that I can find.

Ideally, cider would jump into a new buffer and do something like center point in the middle of the buffer or perhaps at the top. I think the worst place for cursor/point to end up is the last line of the buffer - and this is typically what I'm seeing.

**Comment by bbatsov** [comment]
> I have observed that cider-jump-to which is called from cider-find-var seems to now always put the cursor/point on the last line of the buffer it navigates into. The line is not centered. So it means my point is really low in the buffer and I always forget and can’t find it.

Same problem here. :-) 

> I do not remember this being the case in the past. It used to be I believe centered on the line that was navigated to.

I guess it has been like this for a very long time. 

> Ideally, cider would jump into a new buffer and do something like center point in the middle of the buffer or perhaps at the top. I think the worst place for cursor/point to end up is the last line of the buffer - and this is typically what I'm seeing.

Agreed. I'll just have it centered. I doubt anyone would dislike this - if so I can make it configurable.

**Comment by mrrodriguez** [comment]
Thanks for the quick response and update!
