### ISSUE TITLE
Indented code cannot be debugged in-source

### ISSUE THREAD

**Issue by yuhan0** [clojure-emacs/cider#2852]
## Expected behavior
Executing cider-debug-defun-at-point (C-u C-M-x) should work in source for forms in an indented comment block when `clojure-toplevel-inside-comment-form` is true.
```
(comment
  (inc (inc 0))
  )
```

More generally, this occurs when evaluating any  indented form tagged with #dbg

```
(do
  #dbg (str (inc 0)) ;; cider-eval-last-sexp here
  ...)
```

## Actual behavior
The source "cannot be found" and a temporary debug buffer is created.

## Steps to reproduce the problem
place cursor at | and eval last sexp
```
(do
  #dbg (str (inc 0)) | 
  ...)
```

## Solution

After some detective work I found the underlying issue to be the difference in column indexing between Emacs (0-indexed) and Clojure (1-indexed).

The outgoing conversion to 1-indexing happens in `cider-interactive-eval`, using the function `cider-column-number-at-pos`, so nrepl messages are sent as 1-indexed columns.
https://github.com/clojure-emacs/cider/blob/1911c474baefa1ef0f50274c7035a46949249d58/cider-util.el#L757

However for incoming responses, this line in cider-nrepl causes **only** toplevel forms (column = 1) to be converted to 0-indexing , and no further processing is done client-side.
https://github.com/clojure-emacs/cider-nrepl/commit/7660eb7698b0a708d2e4f6badf5e9afb3a300c4e#diff-0d65c570bef3dbf4640690a252e06f28R340

When column != 1 this causes an off-by-one error and the cider-debug code thinks the source has been edited.

I think the proper solution to this would be to remove the above line in cider-nrepl and offset the 1-indexed response in Emacs. This may break other clients, in particular Calva.

### CIDER version information
```
;; CIDER 0.25.0snapshot, nREPL 0.7.0
;; Clojure 1.10.1, Java 14.0.1
```
### Emacs version

26.3

### Operating system

macOS 10.14

**Comment by yuhan0** [comment]
if the above solution looks alright I can open PRs in both repos to fix it.

**Comment by bbatsov** [comment]
Yeah, I think the proposed solution is reasonable.

**Comment by bbatsov** [comment]
//cc @PEZ

**Comment by PEZ** [comment]
Thanks for the heads-up! I'll consult with @bpringe about wether Calva is vulnerable, and how we can mitigate. When will the change in cider-nrepl be released?

**Comment by bbatsov** [comment]
I did it already - 0.25.2.

**Comment by bpringe** [comment]
I believe I accounted for this in Calva already, maybe even accidentally :smile:. I tested Calva with this scenario with cider-nrepl before 0.25.2 and with it and it works as expected. :tada:

**Comment by bbatsov** [comment]
Great!
