### ISSUE TITLE
cider REPL ignores print-method

### ISSUE THREAD

**Issue by jimka2001** [clojure-emacs/cider#2856]
## Expected behavior
The behavior from the clj REPL is that a record (defined with `defrecord`) should print according to the `print-method` method if there is one.

In short cider should respect `print-method` in the default REPL printing behavior.

## Actual behavior

It seems like the behavior of cider is to ignore `print-method`.

## Steps to reproduce the problem

This issue may be reproduced by entering the following in the repl.

```
(defrecord Foo [x])
(defmethod print-method 'Foo [v w]  (.write w (format "#<Foo x=%s>" (:x v))))
(map->Foo {:x 100})
```

At this point the string `#<Foo x=100>` should be printed rather than `{:x 100}`.

If you try to reproduce this in the clj REPL, you'll see the correct string printed `#<Foo x=100>`

### CIDER version information

```
;; CIDER 0.24.0 (India), nREPL 0.6.0
;; Clojure 1.10.0, Java 11.0.7
```

### Emacs version
GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02

### Operating system
macOS 10.15.4 (19E287) Catalina

**Comment by jimka2001** [comment]
A workaround is to set the following emacs variable
```
(setq cider-repl-use-pretty-printing nil)
```

However, this does not seem like a good long term workaround, as it completely disables cider's print handling, as I understand.

**Comment by bbatsov** [comment]
I wonder what's causing this, as CIDER simply delegates to whatever pprint library the user has selected and uses `clojure.pprint` by default. Do you get the same problem with `fipp` or `zprint`?

**Comment by jimka2001** [comment]
Hi bbatsov,  Sorry I don't understand your question.  I'm supposing the question was directed at me.  What are fipp and zprint?        

Were you able to reproduce my problem?     Or is it unique to my environment? 
My intent was that it should be very easy to reproduce, i.e., simply copy/paste three expressions into the cider repl.

**Comment by bbatsov** [comment]
> What are fipp and zprint?

Pretty-printing libraries, alternatives to the built-in `clojure.pprint`. See https://docs.cider.mx/cider/0.25/usage/pretty_printing.html for more details.

> Were you able to reproduce my problem? Or is it unique to my environment?

That's what I get:

```
#user.Foo{:x 100}
```

It seems correct to me.

**Comment by jimka2001** [comment]
what value of `cider-repl-use-pretty-printing` are you using?   The default one, or have you changed it to `nil`?

**Comment by bbatsov** [comment]
Pretty-printing is enabled, `cider-print-fn` is `pprint`.

**Comment by jimka2001** [comment]
My value of `cider-repl-use-pretty-printing` is `t`, and value of `cider-print-fn` is `'pprint`.
And I get the record printed as `{:x 100}` despite the `print-method`.

**Comment by jimka2001** [comment]
As far as I understand, this is still an outstanding bug.

**Comment by daemianmack** [comment]
<details>
<summary>Version information</summary>

### CIDER version information

;; CIDER 1.6.0 (Buenos Aires), nREPL 1.0.0
;; Clojure 1.10.1, Java 11.0.13

### Lein / Clojure CLI version

Clojure CLI version 1.10.3.1075

### Emacs version

GNU Emacs 30.0.50

### Operating system

OS X 13.1 

### JDK distribution

openjdk version "11.0.13" 2021-10-19 LTS

</details>

I'm still seeing this bug. 

The issue seems related to [this conditional](https://github.com/clojure-emacs/cider/blob/master/cider-repl.el#L1001-L1002) around var `cider-repl-use-pretty-printing` -- disabling that conditional, so that we always merge the two middlewares, "fixes" the bug, though I imagine the right solution is likely not that simple.
