### ISSUE TITLE
cider-jack-in-clj: Could not start nREPL server

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/cider#2862]
## Expected behavior

`cider-jack-in-clj` works as expected, popping up a REPL.

## Actual behavior

```
[nREPL] Starting server via /usr/local/bin/clojure -Sdeps '{:deps {nrepl {:mvn/version "0.8.0-alpha2"} cider/cider-nrepl {:mvn/version "0.25.3-SNAPSHOT"}}}' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware"]'
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Syntax error compiling at (nrepl/middleware/lookup.clj:46:9).
```

## Steps to reproduce the problem

Try to `cider-jack-in-clj` into a Clojure project (it happens with both `deps.edn` and `lein`, FWIW).

### CIDER version information

CIDER 0.26.0snapshot
openjdk 11.0.7 2020-04-14

### Lein/Boot version

Leiningen 2.9.3 on Java 11.0.7 OpenJDK 64-Bit Server VM

### System information
GNU Emacs 28.0.50

Master branch commit:
  7c177ecb8407633e624cd7e12a0c0d12b8990c32
  New command: project-kill-buffers

Configured with the following options:
  --host=x86_64-debian-linux-gnu
  --with-modules
  --with-imagemagick
  --with-harfbuzz

Running on:
  Ubuntu 20.04 LTS
  GNOME Shell 3.36.1 (x11)
  GTK+ Version 3.24.18, cairo version 1.16.0

**Comment by manuel-uberti** [comment]
One more thing: reverting to `60c7d2670cbea18ec2c29e80d99190c9671b7085` fixes it for me.

**Comment by bbatsov** [comment]
Just fixed this. Yesterday I had pushed a bad nREPL release. Sorry about that!

**Comment by manuel-uberti** [comment]
No problem at all, it works as expected now. Thank you for fixing it so quickly!
