### ISSUE TITLE
running cider-jack-in throws a ClassNotFoundException

### ISSUE THREAD

**Issue by gantz-giraffe** [clojure-emacs/cider#2863]
## Expected behavior: 
Running cider-jack-in properly injects dependencies, connects to nrepl, and is usable as normal.

## Actual behavior: 
CIDER appears to manage to connect to the localhost instance, but immediately throws the following error (I'm abridging it to the sections that are ostensibly the important bits, but if it would be helpful to submit the entire error report just let me know):

> > ERROR: Unhandled REPL handler exception processing message {:nrepl.middleware.print/stream? 1, :nrepl.middleware.print/print cider.nrepl.pprint/pprint, :nrepl.middleware.print/quota 1048576, :nrepl.middleware.print/buffer-size 4096, :nrepl.middleware.print/options {:right-margin 70}, :op init-debugger, :session cfc624f0-31c3-489c-ae95-d520dd3eb07c, :id 6}
Syntax error compiling at (cider/nrepl/inlined_deps/orchard/v0v5v10/orchard/java/parser.clj:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7648)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	........ (skipping a bunch of lines here)
        at cider.nrepl.inlined_deps.orchard.v0v5v10.orchard.java.parser$eval3525$loading__6721__auto____3526.invoke(parser.clj:1)
	at cider.nrepl.inlined_deps.orchard.v0v5v10.orchard.java.parser$eval3525.invokeStatic(parser.clj:1)
	at cider.nrepl.inlined_deps.orchard.v0v5v10.orchard.java.parser$eval3525.invoke(parser.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7636)
	... 190 more

## Steps to reproduce the problem

1. Install CIDER from melpa
2. Add 

> (require 'cider)

 to emacs init file.

3. Open a source file within a Clojure project generated by Lein

4. Run M-x cider-jack-in

### CIDER version information

;; CIDER 0.26.0snapshot (package: 20200618.622), nREPL 0.8.0-alpha3
;; Clojure 1.10.1, Java 9.0.1

### Lein/Boot version

Lein 2.93

### Emacs version
26.3

### Operating system

Windows 10

**Comment by bbatsov** [comment]
The errors seems to indicate some problem related to your Java version. Are you really using Java 9?

**Comment by gantz-giraffe** [comment]
It seems I am. It's my understanding that lein 2.8.0 uses JDK 11, yes? Which I do have installed, and it's the version set to my JDK_HOME environment variable as well. Am I missing something, or should I defer this issue to the Leiningen repo?

**Comment by bbatsov** [comment]
You can try removing that JDK 9 and see what's going to happen. Haven't used Windows in ages, so I'm not sure the JDK_HOME was ignored for you. Perhaps setting JAVA_HOME as well might solve this?

**Comment by gantz-giraffe** [comment]
Alright so basically I just had to update Java from the control panel, and had not done that in far too long without realizing. Embarassing mistake, case closed
