### ISSUE TITLE
Consider replacing Cask with Eldev

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#2864]
Mostly a note to myself, as Cask seems to be close to abandonware these days. See https://github.com/doublep/eldev

@doublep has provided some example projects here https://github.com/doublep/eldev#example-projects Seems it's not hard to set this up.

**Comment by doublep** [comment]
If you want, I can create a PR for this.

**Comment by bbatsov** [comment]
@doublep That'd be great!
