### ISSUE TITLE
swiper (re-search-forward) complains about regular expression too big when cider connection is active

### ISSUE THREAD

**Issue by qleguennec** [clojure-emacs/cider#2866]
Not certain this is strictly an issue with cider.

## Expected behavior with cider connection inactive
1. `debug-on-entry re-search-forward`
2. `M-x swiper`
Result:
```
* re-search-forward("(\\(?:.*/\\)?\\(?:clj->js\\|js-\\(?:>clj\\|delete\\|obj\\)..." 6731 t)
  font-lock-fontify-keywords-region(1 6731 nil)
  font-lock-default-fontify-region(1 6731 nil)
  font-lock-fontify-region(1 6731)
  #f(compiled-function (fun) #<bytecode 0x15822f56d551>)(font-lock-fontify-region)
  run-hook-wrapped(#f(compiled-function (fun) #<bytecode 0x15822f56d551>) font-lock-fontify-region)
  jit-lock--run-functions(1 6731)
  jit-lock-fontify-now(1 31364)
  font-lock-ensure()
  swiper-font-lock-ensure()
  swiper--candidates()
  swiper(nil)
  counsel-grep-or-swiper()
  funcall-interactively(counsel-grep-or-swiper)
  call-interactively(counsel-grep-or-swiper nil nil)
  command-execute(counsel-grep-or-swiper)
```

## Steps to reproduce the problem (with cider connection active)
Seems to only happen on large files? Not sure. Note this happens 2 times, then at the third swiper invocation, it works fine. I can `revert-buffer` to make the error appear again.

Note that the debugger output for `re-search-forward` is different than the previous one, even though the buffer is the same and hasn't been edited since the first invocation. 

1. `cider-jack-in-cljs`
2. `toggle-debug-on-error`
3. `M-x swiper`
Debug-on-error output:
```
Debugger entered--Lisp error: (invalid-regexp "Regular expression too big")
  re-search-forward("\\_<\\(analis-desktop\\.\\(?:data\\(?:-browse\\.\\(?:gene..." 23541 t)
  font-lock-fontify-keywords-region(2236 23541 nil)
  font-lock-default-fontify-region(2683 23541 nil)
  apply(font-lock-default-fontify-region 2683 23541 nil)
  #f(compiled-function (beg end &rest rest) #<bytecode 0x15830dba1829>)(2683 23541 nil)
  font-lock-fontify-region(2683 23541)
  #f(compiled-function (fun) #<bytecode 0x15830d5224a1>)(font-lock-fontify-region)
  run-hook-wrapped(#f(compiled-function (fun) #<bytecode 0x15830d5224a1>) font-lock-fontify-region)
  jit-lock--run-functions(2683 23541)
  jit-lock-fontify-now(1 23541)
  font-lock-ensure()
  swiper-font-lock-ensure()
  swiper--candidates()
  swiper(nil)
  counsel-grep-or-swiper()
  funcall-interactively(counsel-grep-or-swiper)
  call-interactively(counsel-grep-or-swiper nil nil)
  command-execute(counsel-grep-or-swiper)
```

### CIDER version information

```
;; CIDER 0.26.0snapshot, nREPL 0.8.0-alpha3
;; Clojure 1.10.1, Java 13.0.2
```

### Lein/Boot version

Leiningen 2.9.3 on Java 13.0.2 OpenJDK 64-Bit Server VM

### Emacs version

GNU Emacs 27.0.91 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-06-19

### Operating system

Archlinux

**Comment by bbatsov** [comment]
I'm guessing that's related to how the dynamic font-locking in CIDER works - it basically keeps updating the font-locking regular expressions in clojure-mode to include all known font-lockable symbols in a particular namespace. One workaround would be to disable dynamic font locking - see this page for details https://docs.cider.mx/cider/0.25/config/syntax_highlighting.html

**Comment by qleguennec** [comment]
That fixed it, thanks:
```
  (add-hook 'cider-repl-mode-hook (lambda! (setq cider-font-lock-reader-conditionals nil)))
  (add-hook 'cider-mode-hook (lambda! (setq cider-font-lock-reader-conditionals nil)))
```

Leaving this issue open in case you think it should be fixed.

**Comment by bbatsov** [comment]
You can set those variables directly. There's not need to do so in a hook.

**Comment by qleguennec** [comment]
After further testing, it seems like the bug occurs less often but still happens on large files (~+300 lines in my case)

**Comment by bbatsov** [comment]
You might try:

```
(setq cider-font-lock-dynamically '(macro core))
```

or 

```
(setq cider-font-lock-dynamically nil)
```

**Comment by qleguennec** [comment]
`(setq cider-font-lock-dynamically '(macro core))` solved the issue, thanks.
