### ISSUE TITLE
Whitespace at beginning of file (before `ns` macro) causes forms to not be evaluated in file's namespace.

### ISSUE THREAD

**Issue by eihli** [clojure-emacs/cider#2877]
## Expected behavior

Whitespace to not affect how the file gets evaluated. 

## Actual behavior

`(cider-eval-buffer)` runs fine and works as expected. But after evaluating the buffer and then trying to evaluate a form inside the buffer, an error is thrown.

```
1. Caused by java.lang.RuntimeException
   No such namespace: string
```

## Steps to reproduce the problem

Notice the single blank space at the beginning of the first line.

```clojure
 (ns com.example
   (:require [clojure.string :as string]))

(def -main
  (println (string/blank? "")))
```

Start a REPL and evaluate the buffer. All good. Evaluate the `-main` form. Error is thrown, `string` not in namespace.

### CIDER version information

```
;; CIDER 0.24.0snapshot, nREPL 0.8.0-alpha5
;; Clojure 1.10.1, Java 1.8.0_242
```

Other middlewares/deps.

```
;;  Startup: /usr/local/bin/clojure -A:dev:cider-nrepl -Sdeps '{:deps {nrepl {:mvn/version "0.6.0"} refactor-nrepl {:mvn/version "2.5.0-SNAPSHOT"} cider/cider-nrepl {:mvn/version "0.23.0"}}}' -m nrepl.cmdline --middleware '["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware"]'
WARNING: CIDER 0.24.0-snapshot requires cider-nrepl 0.23.0, but you're currently using cider-nrepl 0.24.0. The version mismatch might break some functionality!
```

### Emacs version

27.0.90

### Operating system

Arch Linux

**Comment by bbatsov** [comment]
That's probably a bug in `clojure-mode`'s `clojure-find-ns` function.
