### ISSUE TITLE
Cider mode is not automatically activated when nREPL runtime has type Babashka

### ISSUE THREAD

**Issue by carlosgeos** [clojure-emacs/cider#2882]
# Expected behavior

`cider-mode` is automatically activated when running `cider-connect-clj` and connecting to a Babashka nrepl

## Actual behavior

It doesn't, because the babashka nREPL does not have the `'clojure` type, and it never gets to `(cider-enable-on-existing-clojure-buffers)`

https://github.com/clojure-emacs/cider/blob/ff27d811e0c8eb0da55044b8e7bf044feecb5a97/cider-connection.el#L368-L377

https://github.com/clojure-emacs/cider/blob/ff27d811e0c8eb0da55044b8e7bf044feecb5a97/cider-connection.el#L296-L309

## Steps to reproduce the problem

Run a babashka nREPL. Connect to it with `cider-connect-clj`. There is no `C-c C-c` 🙃

Obviously if one has the following hook active, there is no problem. But it is nice to have the `cider` minor mode activated automatically. 

```
(add-hook 'clojure-mode-hook #'cider-mode)
```

### CIDER version information

```
CIDER 0.26.0snapshot (package: 20200718.1908)
```

### Emacs version

```
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-19
```

### Operating system

Windows 98 Second Edition

## PR

I can submit PR with a solution, either by: 

1.- Dropping the check, and running the code for all runtimes (might break stuff for generic ?)
2.- Adding babashka as a valid one, or even creating a "clojure-like" list of runtimes that pass this check

**Comment by bbatsov** [comment]
> Windows 98 Second Edition

 :rofl: 

I think the best solution would be to move enabling the minor mode outside of this block of code and have a different check for it.

> 2.- Adding babashka as a valid one, or even creating a "clojure-like" list of runtimes that pass this check

Just keep in the mind the runtime in question here is the nREPL server, so nothing else can really work with features specific to the Clojure nREPL implementation. So, `clojure-like` can be used in some contexts (e.g. using clojure-mode, evaluating clojure code, etc), but not to check for the runtime.
