### ISSUE TITLE
When I fix the test and I rerun it the test still fails.

### ISSUE THREAD

**Issue by diegosanchez** [clojure-emacs/cider#2884]
## Expected behavior

After fixing the test I rerun it then it should pass. 

## Actual behavior

When I rerun the test with the code fixed, the test fails. 

## Steps to reproduce the problem

1. Create a brand-new project using command: `lein new app my-stuff`
2. Open `emacs`, and the created project and run `cider-jack-in` command.
3. Run test (the test should fail).
4. Fix code.
5. Rerun the test. 

### CIDER version information

```
;; CIDER 0.26.0snapshot (package: 20200718.1908), nREPL 0.8.0-alpha5
;; Clojure 1.10.0, Java 11.0.8
```

### Lein/Boot version

_Ommited because these server is launched with `cider-jack-in`_

### Emacs version

GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-19

Leiningen 2.9.1 on Java 11.0.8 OpenJDK 64-Bit Server VM

### Operating system

Linux Arch, Linux tao 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64 GNU/Linux

**Comment by bbatsov** [comment]
Did you re-evaluate the test before running the tests again? Failure to do so would result in your problem.

**Comment by diegosanchez** [comment]
Thanks @bbatsov! 

The way I deal with the "stale" test is:
1. re-evaluate the function test (`cider-eval-defun-at-point`)
2. re-run the test using `cider-test-rerun-failed-tests` or `cider-test-run-project-tests`.

Is there a way to re-evaluate the code at `cider-test-rerun-failed-tests` time?

**Comment by diegosanchez** [comment]
@bbatsov 
Is there a way to re-evaluate the code at `cider-test-rerun-failed-tests` time?

**Comment by bbatsov** [comment]
Currently no.
