### ISSUE TITLE
eldoc disappears when opening structure

### ISSUE THREAD

**Issue by lgrapenthin** [clojure-emacs/cider#2885]
# Expected behavior
eldoc does not disappear

## Actual behavior
eldoc disappears

## Steps to reproduce the problem

Invoke a loaded function and in any argument position, open a map, vector - eldoc disappears. 

I suppose this problem has always been present. Just today I noticed that it already became a habit of mine to skip out of the current structure to see eldoc again. Especially when invoking a function that declares a destructured map arg, its an interruption not to see the :keys list anymore.

### Cider version
0.26.0

### Emacs version

26.3

**Comment by bbatsov** [comment]
I don't quite understand the problem, so some example would be useful.

**Comment by bbatsov** [comment]
Yeah, it seems that within any paired delimiter eldoc doesn't work properly. Must have been like this forever, as I haven't changed this in a very long time.

**Comment by lockie** [comment]
I'm not sure this is the same issue, but eldoc hint keeps disappearing for me as well. I've recorded the gif to illustrate:

![](https://i.imgur.com/Gx7IBoE.gif)

Notice how the hint disappears right after I press space after the function name.
I'm using Emacs 27.2 on Linux with Cider 1.2.0 (reported as 20220105.613 by Emacs).

**Comment by vemv** [comment]
@lockie shouldn't you wrap `reduce` in parens? Else whatever you're typing will have nothing to do with `reduce`, so eldoc is correct in not telling you about it

**Comment by lockie** [comment]
@vemv The behaviour with the parenthesis is exactly the same.

**Comment by vemv** [comment]
Say the cursor (`|`) is here `(reduce +|)`, should eldoc tell you about `reduce` or `+`?

The point is, as soon as the cursor has gone beyond `reduce`, telling what to eldoc already becomes a more complex 'parsing' problem.

I think that we can have an explicit keyboard binding that displays the eldoc on demand, following some heuristics. CIDER might already have something like that idk, personally I use something bespoke.

**Comment by lockie** [comment]
Oh, in my case Cider won't even bother itself with a `+` :sweat_smile: 
![](https://i.imgur.com/krVDuhL.gif)

I kind of miss eldoc behaviour provided by [eglot](https://github.com/joaotavora/eglot) in e.g. `python-mode`, when the hint stays as long as you type function parameters:
![](https://i.imgur.com/oeWy6Xo.gif)

> CIDER might already have something like that idk, personally I use something bespoke.

Do you mind sharing relevant bits of `init.el`?

**Comment by vemv** [comment]
Thanks for the input!

> Do you mind sharing relevant bits of init.el?

It's too custom to be meaningfully shared. However it doesn't seem too different from https://github.com/clojure-emacs/cider/blob/master/cider-doc.el . Those cider-doc functions seem to render the doc to a dedicated buffer, but one can also use the echo area, which can work just fine for rendering multi-line, syntax colored strings:

_Doc_

![image](https://user-images.githubusercontent.com/1162994/148561315-15ae2827-42ad-4811-bb40-4802d363dcdb.png)

_Source_

![image](https://user-images.githubusercontent.com/1162994/148561692-1b030c96-e7d1-41f3-b77d-9a8b3289cd23.png)

So a motivated contributor might have luck either hacking cider-doc to render to the echo area, **or** to fix eldoc to behave as people have expressed in this thread (which might have its complications e.g. the mentioned ambiguity between `reduce` and `+` in `(reduce +|)`)

I'd love to be able to contribute those hacks myself but atm, as mentioned my personal setup is not something that one can just extract.

**Comment by bbatsov** [comment]
>  Those cider-doc functions seem to render the doc to a dedicated buffer, but one can also use the echo area, which can work just fine for rendering multi-line, syntax colored strings:


There are no eldoc functions that render eldoc to a dedicated buffer. CIDER simply implements the standard Emacs eldoc API.

**Comment by bbatsov** [comment]
Ah, you're talking about `cider-doc` - my bad, I was thinking of `cider-eldoc`. `cider-doc` we can render pretty much anywhere, and I still want us to add support to display it inline or in a popup at some point.
