### ISSUE TITLE
cider-find-var on java code works every other time in Emacs 28

### ISSUE THREAD

**Issue by andreyorst** [clojure-emacs/cider#2887]
I was looking why CIDER jumps to the Clojure code without any issues, but can't jump to the Java sources, even if everything seem to be configured correctly. I've read #2819 (I'm unsure if this is the same issue, as I can't repro it in Emacs 26.3 or 27.1-rc2), #2745 also seems a bit different, and still was unable to achieve expected behaviour. Well, this is strange, but I've finally figured out that this is not the issue with my config, and something with CIDER itself. And this is really weird thing.

Here's a zip archive with minimal `repro-init.el`, and a sample project to test on: 
[repro.zip](https://github.com/clojure-emacs/cider/files/5043045/repro.zip)

## Problem description

`cider-find-var` pointed at Java code *works* but only sometimes.

I can't describe it better, but it feels that **it's just random**.

## Steps to reproduce the problem

- `unzip repro.zip -d cider_bug && cd cider_bug`
- `emacs -q -l repro-init.el repro/src/repro/core.clj`
- <kbd>C-c</kbd> <kbd>M-j</kbd>
- put point on `Executors/newFixedThreadPool`, and press <kbd>M-.</kbd>
- repeat until it works...

If you lucky, you'll jump to Java sorces. If not, you can restart Emacs, and try again, and some times it works. Here's a recording of me doing this:

https://asciinema.org/a/Es7NsyVlj0yZKyazpOsMvt6LJ

It took me 8 Emacs restarts until it finally did the thing.
## Expected behaviour

Consistent jumps to Java source code.

### CIDER version information

```
;; CIDER 0.26.0 (package: 20200805.827) (Nesebar), nREPL 0.8.0                  
;; Clojure 1.10.1, Java 1.8.0_262   
```

### Lein/Boot version

`Leiningen 2.9.3 on Java 1.8.0_262 OpenJDK 64-Bit Server VM`

### Emacs version
Tested with:
- Self compiled GNU Emacs 28.0.50 from `feature/native-comp` branch - does **not** work
  Configured using:
   ```
  'configure --with-nativecomp --without-pop --prefix=/home/andreyorst/.local/emacs --bindir=/home/andreyorst/.local/bin '--program-transform-name=s/^ctags$/ctags.emacs/''
  ```
- Self compiled GNU Emacs 28.0.50 from `master` branch - does **not** work
  configuration flags are the same.
- Emacs 26.3 - works
- Emacs 27.1-rc2 - also works
### Operating system

Fedora 32

**Comment by bbatsov** [comment]
I rarely test CIDER with Emacs pre-releases, mostly because things there tend to change too dynamically. Recently we had done one change for Eldoc on Emacs 28, then something else got changed and this broke again. Fun times. :-)

**Comment by andreyorst** [comment]
I'm actively using `nativecomp` branch (https://akrl.sdf.org/gccemacs.html), as it makes everything work much faster, and thus I'm locked inside the most recent Emacs. However this issue doesn't seem to be caused by recent changes, as it didn't work for me from the moment I've started using CIDER, which was several months ago, but I was thinking that this is due to wrong configuration.

**Comment by bbatsov** [comment]
> I'm actively using nativecomp branch (https://akrl.sdf.org/gccemacs.html), as it makes everything work much faster, and thus I'm locked inside the most recent Emacs. 

Got it. 

> However this issue doesn't seem to be caused by recent changes, as it didn't work for me from the moment I've started using CIDER, which was several months ago, but I was thinking that this is due to wrong configuration.

It'd be great if you can send here the nREPL message log from a case when this work and doesn't work for you. I'll check out your repro steps when I can myself, but those logs would definitely be helpful as well.

**Comment by andreyorst** [comment]
will do in a couple of days

**Comment by andreyorst** [comment]
Sorry for the delay (gosh, 20 days already, I've thought only 4 days passed). Here are messages:

[does-not-work.txt](https://github.com/clojure-emacs/cider/files/5166825/does-not-work.txt)
[work.txt](https://github.com/clojure-emacs/cider/files/5166826/work.txt)

Repro recipe is still actual, however it seems that now it works more often, though not always.

**Comment by andreyorst** [comment]
[Nice](https://www.reddit.com/r/emacs/comments/j9hi9x/an_example_of_why_bug_reports_and_feature/)

**Comment by andreyorst** [comment]
> Sorry for the delay (gosh, 20 days already, I've thought only 4 days passed). Here are messages:
> 
> [does-not-work.txt](https://github.com/clojure-emacs/cider/files/5166825/does-not-work.txt)
> [work.txt](https://github.com/clojure-emacs/cider/files/5166826/work.txt)
> 
> Repro recipe is still actual, however it seems that now it works more often, though not always.

**Comment by andreyorst** [comment]
I've tested this on the 1.2 release and it seems to work now. Closing, thanks!

**Comment by bbatsov** [comment]
A problem that solves itself - my favorite kind. :-)
