### ISSUE TITLE
[nREPL] Starting server ... Invalid number: 0.8.0

### ISSUE THREAD

**Issue by Glademist** [clojure-emacs/cider#2890]
## Expected behavior
Start nRepl in eMacs through cider-jack-in on a lein created app project

## Actual behavior
Prints out an error in Messages and does not start anything.

## Steps to reproduce the problem
lein new app test
C-x C-f ~/src/test/core.clj
M-x cider-jack-in

## Environment & Version information
Cider 0.26.0
Clojure 1.10.1
Java 11.0.8

### CIDER version information
```
[nREPL] Starting server via "c:/Javalibs/lein.bat" update-in :dependencies conj ^"[nrepl \^"0.8.0\^"]^" -- update-in :plugins conj ^"[cider/cider-nrepl \^"0.25.3\^"]^" -- repl :headless :host localhost
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: java.lang.NumberFormatException: Invalid number: 0.8.0
```
### Emacs version
26.3

### Operating system
Windows 10 PRO

**Comment by bbatsov** [comment]
What's your Lein version?

**Comment by Glademist** [comment]
Hello. Sorry for not posting that.

Leiningen 2.9.4 on Java 11.0.8 Java HotSpot(TM) 64-Bit Server VM

However i just tried to install Clojure for Visual Code and it produces very similar error, but with different number, a 0.6.4 in that case. So i believe it is a specific system issue. Found another post in visual code troubleshooting and they couldnt help him. So it is probably something wrong with the installation of either of the parts.  

So.. i think it probably is not a problem of Cider. But either leiningen or java or clojure installation. :( Sorry about that.

**Comment by bbatsov** [comment]
I'm assuming it's some problem with Powershell and how it parses the command-line params. I'm assuming you'll get the same error if you just paste the command-line string to powershell directly. I'm not a Windows users, so unfortunately I can't test this myself and see what exactly is going on.

**Comment by Glademist** [comment]
So.. I fixed the issue. 
1 - First i removed the powershell installed Clojure Tools for Windows.
2 - I removed JAVA 11 JDK and keep the JAVA 8.261.
2 - I changed my path for leiningen (lein.bat) from C:\Javalibs\ to C:\Javalibs
3 - It works. No error.

It works as intended now.
