### ISSUE TITLE
cider-auto-select-error-buffer option ignored? 

### ISSUE THREAD

**Issue by iansinnott** [clojure-emacs/cider#2892]
I did a quick search of the code and didn't see any check on `cider-auto-select-error-buffer`. I'm wondering if it is accidentally ignored.

---

## Expected behavior

When an error is thrown, the error buffer does not gain focus. Cursor remains in the buffer it was in.

## Actual behavior

When an error is throw cursor jumps to the error buffer.

## Steps to reproduce the problem

```
;; In emacs config
(setq cider-auto-select-error-buffer nil)
```

```
;; In a clojure file eval something that throws, like
(/ 1 0)
```

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.26.1 (package: 20200814.1540) (Nesebar), nREPL 0.8.0
;; Clojure 1.10.1, Java 14.0.1
```

### Lein/Boot version

```
Leiningen 2.9.4 on Java 14.0.1 OpenJDK 64-Bit Server VM
```

### Emacs version

```
GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2020-08-12
```

### Operating system

OSX 15 (Catalina)

**Comment by bbatsov** [comment]
The option is used here https://github.com/clojure-emacs/cider/blob/master/cider-eval.el#L290

This code hasn't been changed in years, as far as I can tell.

**Comment by iansinnott** [comment]
Well, maybe it's something else in my config. I'm new to all this elisp so I'll just assume that's the case for now.
