### ISSUE TITLE
Let CIDER support ignore-case completion in company-mode

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/cider#2895]
**Is your feature request related to a problem? Please describe.**

Not related to problem.

**Describe the solution you'd like**

When I type `(.tou`, I hope CIDER completion in company-mode can support case-insenstive completion. So it can complete `(.toUpperCase` like candidates. Typing uppercase character with pressing the `Shift` key is annonying.

**Comment by bbatsov** [comment]
I guess fuzzy completion can help you to some extent https://docs.cider.mx/cider/0.26/usage/code_completion.html#fuzzy-candidate-matching

**Comment by stardiviner** [comment]
This `cider-company-enable-fuzzy-completion` can reduce typing, no really solved my problem. Is it simple to support ignore-case for CIDER? Emacs has a built-in option `completion-ignore-case` do this. `company-mode` support this option too. In company-mode source code, it call backend with ignore-case option like this `(company-call-backend 'ignore-case)` in `company.el` file.

**Comment by bbatsov** [comment]
I'm not sure how complex this would be, as the backend is case-sensitive, so I can't imagine that it'd be enough only do change something on company's side. It's probably not a lot of work, but when you factor all the backends that CIDER supports it's not little either.

**Comment by stardiviner** [comment]
Here is a related issue in company-mode, reference here for mark.

https://github.com/company-mode/company-mode/issues/364

**Comment by stardiviner** [comment]
I bisected my Emacs config with `bug-hunter-init-file`. I found `company-box-mode`'s frontend `company-box-frontend` caused this problem. Now I can use ignore-case on `(java.lang.System`.

Then I realized another problem. `(java.lang.System/getProperty` can't be completed by `(java.lang.System/getp`. This might related to company-mode prefix calculation mechanism.

**Comment by stardiviner** [comment]
Don't let bot close this issue.

**Comment by stardiviner** [comment]
Gentle ping about this supporting.

**Comment by bbatsov** [comment]
PRs welcome. I doubt I'll get to this ticket any time soon, as I've got quite the backlog of other tickets to address.

**Comment by stardiviner** [comment]
Hard for me to implement. Well, not bad to take a try, at least can check out the CIDER source code internal. If I write some bad code, hope can get some help from you. 😄

**Comment by bbatsov** [comment]
Sure!

**Comment by vemv** [comment]
You'd first have to create an issue/PR in https://github.com/alexander-yakushev/compliment , then everything would become easy CIDER side.

Worth noting, with each release compliment and cider are getting more and more accurate and featureful.

So with each CIDER release, you'll get fewer (more accurate) completion candidates, therefore you will rarely need workarounds like case-insentivity so much.

For your example, you'd write `.to` and only get candidates for `String`. So no need to type `u` or `U` 😄

**Comment by stardiviner** [comment]
<img width="2152" height="488" alt="Image" src="https://github.com/user-attachments/assets/e91abaf0-ab27-4702-9943-89508cad7796" />

Today, I reviewed this old issue, seems it working case-insensitive now. (I have not proposed this issue on `compliment` issues) If `compliment` has not implement this, maybe this is because Emacs `orderless` etc packages (I have not check my Emacs config in depth).

Update reply here just for a note.
