### ISSUE TITLE
implement cider-eval-enclosing-form

### ISSUE THREAD

**Issue by xificurC** [clojure-emacs/cider#2899]
**Is your feature request related to a problem? Please describe.**

I'm often with the cursor inside a form I'd like to evaluate. Typically in rich comments I edit an argument and want to try reevaluating the wrapping form. If it's in the middle of the `(comment)` block I need to go to the beginning of the next line (evil/vim curse, can't put cursor past last character) and run `cider-eval-last-sexp`.

**Describe the solution you'd like**

Ideally I'd want to stay where I am with the cursor and run the parenthesized expression that encloses it. Finding the enclosing paren is done by searching for the first opening paren to the left. The function could be easily enriched by searching for the second highest enclosing paren via `universal-argument`.

**Describe alternatives you've considered**

I've looked through all `cider-eval-*` functions and found none that meet my needs. Maybe I'm just blind though :)

Another option that would cover 80-90% of my use cases would be if `cider-eval-defun-at-point` would treat `(comment)` blocks as special and thought of each inner form as a separate toplevel form.

**Additional context**

**Comment by bbatsov** [comment]
> Another option that would cover 80-90% of my use cases would be if cider-eval-defun-at-point would treat (comment) blocks as special and thought of each inner form as a separate toplevel form.

I thought @dpsutton already implemented something like this a while ago. 

> Ideally I'd want to stay where I am with the cursor and run the parenthesized expression that encloses it.

`cider-eval-sexp-at-point` doesn't work for you?

**Comment by xificurC** [comment]
Let `|` be the cursor. Then for
```clojure
(comment (+ 2| 3))
```
`cider-eval-defun-at-point` returns `nil`

 `cider-eval-sexp-at-point` returns `2`

I want to evaluate the `(+ 2 3)` part and get `5` as the result.

**Comment by dakra** [comment]
@xificurC did you `(setq clojure-toplevel-inside-comment-form t)` ?

**Comment by xificurC** [comment]
Hi @dakra , no, since I didn't know of that variable. Surprisingly (to me at least) it's in clojure and not cider.

I'd still consider the original suggestion, but I'll play around with this and see it fills my use cases. Thanks!

**Comment by bbatsov** [comment]
> Surprisingly (to me at least) it's in clojure and not cider.

Because the logic for sexp boundaries lives in `clojure-mode`.

**Comment by esciafardini** [comment]
`(setq clojure-toplevel-inside-comment-form t)` - this causes an issue of muddying your global namespace though.  I thought the point of doing defs within a comment block was to prevent that state?  

Pretty new to Clojure, so this comment may be off base.

**Comment by esciafardini** [comment]
I may be wrong, but with `(setq clojure-toplevel-inside-comment-form t)` - it seems to effect the current namespace, functions and definitions are stored within the NS of the function you are in.  

I thought the point of running code in the rich comment block was to avoid this?

**Comment by vemv** [comment]
Given it has a fix/workaround, I'll close this issue.

PRs (accompanied by a convincing pitch) most welcome!
