### ISSUE TITLE
more differentiated faces for debug mode "actions menu line"

### ISSUE THREAD

**Issue by dadinn** [clojure-emacs/cider#2905]
# Observed

The top line in debug mode (describing the possible actions and key-bindings) is blending into the code-blocks.

# Expected

It would be preferable to have an inverse colour scheme used for these faces (black background, white text, and maybe red/orange underlined letters for key-bindings), so that it would be easier to visually differentiate it from the rest of the code buffer.

# Versions used

OS: Debian 10 (Buster)
Emacs: 27.1
Cider: 0.26.1
cider-nrepl: 0.25.3

**Comment by bbatsov** [comment]
A screenshot would be welcome here as well.

**Comment by dadinn** [comment]
Apologies, it turns out the issue was with my theme not loading correctly.
Actually, the key-bindings are highlighted/underlined well even under the default theme.
Nevertheless, an inverse background/foreground face for the actions menu line might still be preferable.

**Comment by dadinn** [comment]
this is how it looks under [monokai](https://github.com/kevinsawicki/monokai) theme:
https://pasteboard.co/JvaMG6a.png

**Comment by dadinn** [comment]
Duplicate of #2904

**Comment by dadinn** [comment]
any update on this?
