### ISSUE TITLE
No REPL buffer opens after a `cider-jack-in-cljs` is run

### ISSUE THREAD

**Issue by ftravers** [clojure-emacs/cider#2906]
## Expected behavior

I do a `cider-jack-in-cljs` and a separate REPL buffer is created.

## Actual behavior

I do a `cider-jack-in-cljs` and a separate REPL buffer is NOT created.

## Steps to reproduce the problem

When I do a `cider-jack-in-cljs` I don't get a separate REPL, the REPL
goes into the 

    *nrepl-server <project-name>:localhost*  

buffer, instead of opening up a separate normal REPL buffer.  Not sure
what I'm doing wrong.  The following are the actual
project files I'm using.  This is a deps/clojure cli project, not
leiningen.  It's a clojurescript project.

This is the only buffer that gets created, it's name is:

    *nrepl-server <project-name>:localhost*~

and it's contents are: 

    2020-10-08 10:50:21.881:INFO::main: Logging initialized @6908ms to org.eclipse.jetty.util.log.StdErrLog
    [Figwheel] Compiling build fe_dev to "target/public/cljs-out/fe_dev-main.js"
    [Figwheel] Successfully compiled build fe_dev to "target/public/cljs-out/fe_dev-main.js" in 2.24 seconds.
    [Figwheel] Watching paths: ("src") to compile build - fe_dev
    [Figwheel] Starting Server at http://localhost:9500
    [Figwheel] Starting REPL
    Prompt will show when REPL connects to evaluation environment (i.e. a REPL hosting webpage)
    Figwheel Main Controls:
              (figwheel.main/stop-builds id ...)  ;; stops Figwheel autobuilder for ids
              (figwheel.main/start-builds id ...) ;; starts autobuilder focused on ids
              (figwheel.main/reset)               ;; stops, cleans, reloads config, and starts autobuilder
              (figwheel.main/build-once id ...)   ;; builds source one time
              (figwheel.main/clean id ...)        ;; deletes compiled cljs target files
              (figwheel.main/status)              ;; displays current state of system
    Figwheel REPL Controls:
              (figwheel.repl/conns)               ;; displays the current connections
              (figwheel.repl/focus session-name)  ;; choose which session name to focus on
    In the cljs.user ns, controls can be called without ns ie. (conns) instead of (figwheel.repl/conns)
        Docs: (doc function-name-here)
        Exit: :cljs/quit
     Results: Stored in vars *1, *2, *3, *e holds last exception object
    Opening URL http://localhost:9500
    ClojureScript 1.10.773
    cljs.user=> 

In the `*messages*` buffer I get:

    [nREPL] Starting server via /usr/bin/clojure -M:dev -Sdeps 
    '{:deps 
       {me.raynes/fs             {:mvn/version "1.4.6"}
        compliment               {:mvn/version "0.3.6"}
        com.cemerick/pomegranate {:mvn/version "0.4.0"}
        org.tcrawley/dynapath    {:mvn/version "0.2.5"}
        nrepl                    {:mvn/version "0.8.2"}
        cider/piggieback         {:mvn/version "0.5.1"}
        refactor-nrepl           {:mvn/version "2.5.0"}
        cider/cider-nrepl        {:mvn/version "0.25.3"}}
       }' 
    -m nrepl.cmdline
    --middleware 
    '["refactor-nrepl.middleware/wrap-refactor",
      "cider.nrepl/cider-middleware", 
      "cider.piggieback/wrap-cljs-repl"]' 

PROJECT FILES:

---

    ╭─fenton@ss9 ~/projects/supps2 ‹heroku-work*› 
    ╰─$ tree          
    .
    |-- deps.edn
    |-- .dir-locals.el
    |-- fe_dev.cljs.edn
    `-- src
        `-- supps
            `-- core.cljs

deps.edn:

    {:deps {org.clojure/clojure {:mvn/version "1.10.1"}
            org.clojure/clojurescript {:mvn/version "1.10.773"}
            com.bhauman/figwheel-main {:mvn/version "0.2.11"}
            reagent/reagent {:mvn/version "1.0.0-alpha2"}}
    
     :paths ["src" "resources" "target"]
    
     :aliases {:dev {:main-opts
                     ["--main" "figwheel.main"
                      "--build" "fe_dev"
                      "--repl"]}}}

.dir-locals.el:

    ((nil . ((cider-clojure-cli-global-options . "-M:dev"))))

fe_dev.cljs.edn:

    {:main supps.core}

src/supps/core.cljs:

    (ns supps.core
      (:require
       [reagent.core :as r]
       [reagent.dom :as rdom]))
    
    (def click-count (r/atom 0))
    
    (defn counting-component []
      [:div
       "The atom " [:code "click-count"] " has value: "
       @click-count ". "
       [:input {:type "button" :value "Click me!"
                :on-click #(swap! click-count inc)}]])
    
    (rdom/render
     [counting-component]
        (.-body js/document))

## Environment & Version information

Clojure: 1.10.1
Java: 14.0.2

### CIDER version information

CIDER 1.0.0snapshot (package: 20200916.1152)

### Emacs version

Emacs Version: "27.1"

### Operating system

Linux: 5.8.13-arch1-1

**Comment by bbatsov** [comment]
Do you see somewhere in all the messages something like:

```
nREPL server started on port 40943 on host 127.0.0.1 - nrepl://127.0.0.1:40943
```

**Comment by ftravers** [comment]
no i don't see that anywhere.

**Comment by bbatsov** [comment]
That's the message you'd get when nREPL started successful and it's also the message that CIDER expects in the text output to figure out the server has started and to connect to it. What happens if you run the `clj` command in a shell? Do you get an nREPL server running then?

**Comment by ftravers** [comment]
Yes, same, when I run the command that cider executes, in a terminal, there is no line that contains: "nREPL server started on ..."

    ╭─fenton@ss9 ~/projects/supps ‹heroku-work*› 
    ╰─$ /usr/bin/clojure -A:dev -Sdeps '{:deps {me.raynes/fs {:mvn/version "1.4.6"} compliment {:mvn/version "0.3.6"} com.cemerick/pomegranate {:mvn/version "0.4.0"} org.tcrawley/dynapath {:mvn/version "0.2.5"} nrepl {:mvn/version "0.8.2"} cider/piggieback {:mvn/version "0.5.1"} refactor-nrepl {:mvn/version "2.5.0"} cider/cider-nrepl {:mvn/version "0.25.3"}}}' -m nrepl.cmdline --middleware '["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware", "cider.piggieback/wrap-cljs-repl"]'
    
    WARNING: When invoking clojure.main, use -M
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    [Figwheel] Compiling build fe_dev to "target/public/cljs-out/fe_dev-main.js"
    [Figwheel] Successfully compiled build fe_dev to "target/public/cljs-out/fe_dev-main.js" in 1.255 seconds.
    [Figwheel] Watching paths: ("src") to compile build - fe_dev
    [Figwheel] Starting Server at http://localhost:9500
    [Figwheel] Starting REPL
    Prompt will show when REPL connects to evaluation environment (i.e. a REPL hosting webpage)
    Figwheel Main Controls:
              (figwheel.main/stop-builds id ...)  ;; stops Figwheel autobuilder for ids
              (figwheel.main/start-builds id ...) ;; starts autobuilder focused on ids
              (figwheel.main/reset)               ;; stops, cleans, reloads config, and starts autobuilder
              (figwheel.main/build-once id ...)   ;; builds source one time
              (figwheel.main/clean id ...)        ;; deletes compiled cljs target files
              (figwheel.main/status)              ;; displays current state of system
    Figwheel REPL Controls:
              (figwheel.repl/conns)               ;; displays the current connections
              (figwheel.repl/focus session-name)  ;; choose which session name to focus on
    In the cljs.user ns, controls can be called without ns ie. (conns) instead of (figwheel.repl/conns)
        Docs: (doc function-name-here)
        Exit: :cljs/quit
     Results: Stored in vars *1, *2, *3, *e holds last exception object
    Opening URL http://localhost:9500
    ClojureScript 1.10.773
    cljs.user=>
