### ISSUE TITLE
Provide ability to customise cljfmt code formatting

### ISSUE THREAD

**Issue by BrunoBonacci** [clojure-emacs/cider#2907]
**Describe the solution you'd like**

It should be possible to provide a custom formatting configuration for cider-nrepl/cljfmt.
The cljfmt configuration format is described here:

https://github.com/weavejester/cljfmt#configuration

The desired solution should have a `defcustom` variable where the configuration can be provided.

**Describe alternatives you've considered**

A workaround to this solution is to use an `after-save-hook` as described here:

https://github.com/dzer6/cljfmt-graalvm

However, in this case, the two formatters (cider, external cljfmt) will keep fighting each other causing an awful user experience.

**Comment by bbatsov** [comment]
> However, in this case, the two formatters (cider, external cljfmt) will keep fighting each other causing an awful user experience.

How come? Unless you trigger manually `cljfmt` in CIDER it won't be invoked. Keep in mind that the default indentation engine is actually written in Emacs Lisp. 

As mentioned in the chat solving this issue is not particularly complex. Seems we already added the ability to pass configuration to the middleware op responsible for invoking `cljfmt`, but we never implemented this in the client.

**Comment by BrunoBonacci** [comment]
So I guess it is fighting against the (elisp) Indentation engine.
Is there any way I can control/customise the behaviour of that one?

The issue I have is that the indentation works differently depending on whether you are connected to the repl or not.
If you are connected to the REPL and you have evaluated the namespace then things like `:style/indent` are respected;
while if the repl isn't running or the namespace isn't evaluated the indentation doesn't know about the `:style/indent`
value, so for obvious reasons, it will indent the forms differently.
If you add things like `aggressive-indent-mode` then the behaviour is even more bizarre. Forms start jumping left or right based on whether the engine has evaluated that form or not.

I'd like to replace the current behaviour with something that is a bit more deterministic and it works the same whether the repl  has evaluated a form or not.

**Comment by bbatsov** [comment]
You can just disable dynamic (REPL-powered) indentation if you don't rely on it https://docs.cider.mx/cider/0.26/config/indentation.html Alternative you can completely override the indentation logic of `clojure-mode` and provide whatever implementation you want. CIDER simply hooks into it and adds new indentation rules there dynamically when connected.

**Comment by BrunoBonacci** [comment]
Thanks for the link. I'll see if I can achieve what want with the configuration described there.

However, I still think that this ticket stands. Having the possibility to configure the `cljfmt` indentation rules is a nice-to-have feature.

**Comment by bbatsov** [comment]
Yeah, I agree.
