### ISSUE TITLE
Avoid focusing the cider-inspect window

### ISSUE THREAD

**Issue by qleguennec** [clojure-emacs/cider#2909]
I always have a `*cider-inspect*` buffer open and I would like to avoid having to switch back to my `clojure-mode` window whenever I inspect a new value. `*cider-inspect*` window should not be focused by default or an custom variable should control that behavior.

**Comment by mallt** [comment]
I think you should be able to get that behavior by changing the `t` on this line to `nil`:
https://github.com/clojure-emacs/cider/blob/master/cider-inspector.el#L310

**Comment by bbatsov** [comment]
Yep, although it will be best to make this a `defcustom`. The assumption was that normally you invoke the inspector and start drilling down the data, but I guess some people do things differently.
