### ISSUE TITLE
Compilation fails with "Containing expression ends prematurely"

### ISSUE THREAD

**Issue by skuro** [clojure-emacs/cider#2911]
## Expected behavior
`cider-eval-last-sexp` and `cider-load-buffer` happily compile valid clojure code

## Actual behavior

```
Debugger entered--Lisp error: (scan-error "Containing expression ends prematurely" 23 24)
  scan-sexps(23 1)
  forward-sexp(1)
  clojure-forward-logical-sexp()
  clojure--find-ns-in-direction(backward)
  clojure-find-ns()
  cider-ns-form()
  cider-load-buffer()
  funcall-interactively(cider-load-buffer)
  call-interactively(cider-load-buffer nil nil)
  command-execute(cider-load-buffer)
```

## Steps to reproduce the problem

- create a new blank project (I used [`clj-new`](https://github.com/seancorfield/clj-new))
- jack in
- open a clojure source file at `src/buggy.clj`
- just have `(ns buggy)` as the content of the file
- `C-c C-k`

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 0.26.1 (Nesebar), nREPL 0.8.0
;; ------ 8< --- snip --- 8< --------
;; Clojure 1.10.2-alpha2, Java 11.0.8
;;  Startup: /usr/local/bin/clojure -Sdeps '{:deps {nrepl {:mvn/version "0.8.0"} refactor-nrepl {:mvn/version "2.5.0"} cider/cider-nrepl {:mvn/version "0.25.3"}}}' -m nrepl.cmdline --middleware '["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware"]'
```

### Lein/Boot version

N/A (used clojure CLI)

### Emacs version

26.3

### Operating system

Ubuntu 20.04 LTS

**Comment by skuro** [comment]
Note that if I place the cursor at the end of the `ns` form and hit `C-x e` it fails similarly with 

```
Debugger entered--Lisp error: (scan-error "Containing expression ends prematurely" 23 24)
  scan-sexps(23 1)
  forward-sexp(1)
  clojure-forward-logical-sexp()
  clojure--find-ns-in-direction(backward)
  clojure-find-ns()
  cider-ns-form()
  cider--prep-interactive-eval("(ns dutch-meetup.buggy)\n" #<buffer *cider-repl Meetup/futoshiki:localhost:46563(clj)*>)
  #f(compiled-function (connection) #<bytecode 0x1e174f5>)(#<buffer *cider-repl Meetup/futoshiki:localhost:46563(clj)*>)
  mapcar(#f(compiled-function (connection) #<bytecode 0x1e174f5>) (#<buffer *cider-repl Meetup/futoshiki:localhost:46563(clj)*>))
  cider-map-repls(:auto #f(compiled-function (connection) #<bytecode 0x1e174f5>))
  cider-interactive-eval(nil nil (1 25) (("nrepl.middleware.print/quota" 1048576) ("nrepl.middleware.print/print" "cider.nrepl.pprint/pr" "nrepl.middleware.print/stream?" nil)))
  cider-eval-last-sexp(nil)
  funcall-interactively(cider-eval-last-sexp nil)
  call-interactively(cider-eval-last-sexp nil nil)
  command-execute(cider-eval-last-sexp)
```

**Comment by bbatsov** [comment]
Hmm, I can't reproduce this. Both commands works just fine in buffer with only a namespace in it for me.

**Comment by skuro** [comment]
I'm trying to isolate the error, I'm fairly sure there's some configuration or interaction with other packages that triggers the issue. So far I have an interesting data point to consider: the above error comes from an `emacs-client` session attached to a running `emacs --daemon`. Now, if I

- start `emacs-q`
- `C-x C-f` my `init.el`
- `C-x h` + `M-x eval-region` (`eval-buffer` doesn't work for some [esoteric reasons](https://github.com/weirdNox/org-noter/issues/77))

The error disappears. I would assume that the emacs configuration after starting the debug instance as described above would be equivalent to what my daemon is running, but apparently there's enough differences to cause such a different behavior. I noticed that many other CIDER features seem broken on my daemon instance, e.g. `cider-doc` only works if my REPL `*ns*` is the same namespace of the buffer file, `C-u C-c C-z` doesn't set the namespace, etc.

Would you have any hint where can I look to understand what makes CIDER drunk on my environment? Happy to move the conversation elsewhere if this turns out to be a "doesn't work only on my computer" sort of a thing

**Comment by skuro** [comment]
Alright, it seems I had some dirty state hidden somewhere in some trash bins. The following seemed to have "fixed" the issue:

```shell
rm -R ~/.emacs.d/var/backup/* ~/.emacs.d/var/auto-save/sessions/*
```

all in all those folders contained about 500 files, hard to tell precisely what was in there that tainted the system.
