### ISSUE TITLE
"Find fn references" does not work

### ISSUE THREAD

**Issue by johbra** [clojure-emacs/cider#2915]
Looking for fn references (using a Clojurescript real) yields the following exception:

  Show: Project-Only All 
  Hide: Clojure Java REPL Tooling Duplicates  (12 frames hidden)

  This is an unexpected CIDER middleware error.
  Please submit a bug report via `M-x cider-report-bug`.

  If these stacktraces are occurring frequently, consider using the
  button(s) below to suppress these types of errors for the duration of
  your current CIDER session. The stacktrace buffer will still be
  generated, but it will "pop under" your current buffer instead of
  "popping over". The button toggles this behavior.

 Suppress fn-refs-error 

1. Unhandled java.lang.Exception
   No namespace: dep.model.modul found

                  core.clj: 4162  clojure.core/the-ns
                  core.clj: 4369  clojure.core/ns-resolve
                  core.clj: 4359  clojure.core/ns-resolve
                  core.clj: 4359  clojure.core/ns-resolve
                  xref.clj:   21  cider.nrepl.middleware.xref/fn-refs-reply
                  xref.clj:   20  cider.nrepl.middleware.xref/fn-refs-reply
        error_handling.clj:  160  cider.nrepl.middleware.util.error-handling/eval2174/fn
              MultiFn.java:  234  clojure.lang.MultiFn/invoke
                  xref.clj:   29  cider.nrepl.middleware.xref/handle-xref
                  xref.clj:   28  cider.nrepl.middleware.xref/handle-xref
                  Var.java:  388  clojure.lang.Var/invoke
                 nrepl.clj:  489  cider.nrepl/wrap-xref/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                server.clj:   19  nrepl.server/handle*
                server.clj:   16  nrepl.server/handle*
                server.clj:   36  nrepl.server/handle/fn
                  core.clj: 2030  clojure.core/binding-conveyor-fn/fn
                  AFn.java:   18  clojure.lang.AFn/call
           FutureTask.java:  264  java.util.concurrent.FutureTask/run
   ThreadPoolExecutor.java: 1128  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  628  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  834  java.lang.Thread/run

The namespace dep.model.modul does exist in file named model.cljc.

**Comment by bbatsov** [comment]
That functionality is Clojure-specific, but it seems I forgot to make this explicit in the code.

**Comment by johbra** [comment]
if I try the same using a Clojure repl I get the same error message

**Comment by bbatsov** [comment]
Did you evaluate the ns in question?

**Comment by johbra** [comment]
Perhaps I didn't.

New shot:
Two of my loaded namespaces:
  dep.model.lehrveranstaltung
  dep.model.modul
The function mussModulUnterrichtetWerdenFuer-inQuartal? is defined dep.model.modul and used in dep.model.lehrveranstaltung. But looking for fn references yields the answer:
No references found for "mussModulUnterrichtetWerdenFuer-inQuartal?" in currently loaded namespaces.
But I get no exception anymore.

Both namespaces are defined in clic-files.

**Comment by bbss** [comment]
I'm seeing the same error after updating from I think some version of cider 25 in my ClojureScript projects. Tried both melpa stable and 20201020..1058 .

**Comment by bbatsov** [comment]
@bbss Your problem seems unrelated, so it'd be best to report it separately. It seems there's some unhandled NPE in the cider-nrepl `eldoc` middleware op.

**Comment by bbss** [comment]
My mistake, had mismatched nrepl middleware in the projects. Thanks!

**Comment by vemv** [comment]
We're fixing all xref-related stuff in the upcoming CIDER release.
