### ISSUE TITLE
Failing linter checks on CI and locally on several files

### ISSUE THREAD

**Issue by jr0cket** [clojure-emacs/cider#2918]
## Expected behavior
Pull requests should pass tests if their own specific changes pass `eldoc lint` run locally.

 
## Actual behavior
`cider-connection.el` and `cider-doc.el` files fail on  CircleCI and `cider-pkg.el` additionally fails locally (`cider-pkg.el` does not seem to be included in the checks run on CircleCI

## Steps to reproduce the problem
Install eldev binary on your computer
https://github.com/doublep/eldev#installation

Clone the clojure-emacs/cider project

Run the lint command of eldev, from the root of the cloned clojure-emacs/cider project
```
eldev lint
```

### CIDER version information
From `cider-version`:
CIDER 1.0.0snapshot (package: 20200930.1242)

From `cider-display-connection-info`:
```
CLJ four-clojure@localhost:46803 (Java 11.0.8, Clojure 1.10.1, nREPL 0.8.2)
```
### Emacs version
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2020-09-19

### Operating system

Ubuntu Linux 20.04

**Comment by bbatsov** [comment]
Finally fixed this today.
