### ISSUE TITLE
<M-x cider-view-manual> jumps to Page Not Found

### ISSUE THREAD

**Issue by gmlewis** [clojure-emacs/cider#2921]
Sorry if this is already known, but I'm trying Clojure and Cider for the first time, and the repl says:

```
Type <M-x cider-view-manual> to view it.
```

but when I do this, it jumps to: https://docs.cider.mx/cider/0.26.1/
which says "Page Not Found".

**Comment by bbatsov** [comment]
That's a bug that was recently fixed on the `master`. The manual urls don't have the patch version in them, so it's just https://docs.cider.mx/cider/0.26
