### ISSUE TITLE
cider-jack-in-cljs with figwheel-main opens clj REPL.

### ISSUE THREAD

**Issue by recholsknauber** [clojure-emacs/cider#2925]
Thank you for all your hard work on CIDER! My project template for the below is at: 
https://github.com/recholsknauber/cljs-project-template

## Expected behavior
At cider-jack-in-cljs with figwheel-main, open a cljs repl with available figwheel and cljs commands.

## Actual behavior
cider-jack-in-cljs successfully connects figwheel and compiles a dev build, but REPL starts in *pending cljs* and reverts to clj, resulting in a lack of access to figwheel and cljs commands.

## Steps to reproduce the problem
cider-jack-in-cljs on cljs project created with
`lein new figwheel`

*pending cljs* at cider-jack-in-cljs
![image](https://user-images.githubusercontent.com/20304644/97806705-dd6f1b00-1c11-11eb-94fe-def00f1fc518.png)

Reverts to clj REPL, unable to run figwheel and other cljs commands.
![image](https://user-images.githubusercontent.com/20304644/97806785-3939a400-1c12-11eb-8f37-a2943d8a921f.png)

`(in-ns 'cljs.user)`
![image](https://user-images.githubusercontent.com/20304644/97806773-2626d400-1c12-11eb-8a0c-9381e734d8f1.png)

## Environment & Version information
Emacs, latest Figwheel
![image](https://user-images.githubusercontent.com/20304644/97806596-4904b880-1c11-11eb-9f19-10f3ddd823e6.png)

![image](https://user-images.githubusercontent.com/20304644/97806574-15299300-1c11-11eb-8d3e-5513b1e32456.png)

### Lein/Boot version
![image](https://user-images.githubusercontent.com/20304644/97806610-676ab400-1c11-11eb-81ab-c28c07c54228.png)

### Emacs version
![image](https://user-images.githubusercontent.com/20304644/97806640-8bc69080-1c11-11eb-81f1-5f531aad92ab.png)

### Operating system
Windows 10

**Comment by bbatsov** [comment]
Check your deps tree to see if something isn't pulling an older version of Piggieback. This is the usual cause of such a problem, as the REPL type check in cider-nrepl is a simple check for the presence of Piggieback.

**Comment by recholsknauber** [comment]
Thanks for your help.
I'm currently using the latest piggieback "0.5.2"
`
;; Using PowerShell
(defun run-powershell ()
  "Run powershell"
  (interactive)
  (async-shell-command "c:/windows/system32/WindowsPowerShell/v1.0/powershell.exe -Command -"
               nil
               nil))
`

**Comment by bbatsov** [comment]
@recholsknauber Did you manage to sort this out?
