### ISSUE TITLE
.nrepl.edn middleware not honored

### ISSUE THREAD

**Issue by xificurC** [clojure-emacs/cider#2927]
## Expected behavior
Creating an `.nrepl.edn` with `{:middleware [my/middleware]}` injects the middleware when running `cider-jack-in-clj`.
## Actual behavior
It doesn't.
## Steps to reproduce the problem
Create a `.nrepl.edn` file with contents `{:middleware [my/middleware]}` at the root of the project, right next to `deps.edn`.
### CIDER version information
```
;; CIDER 1.0.0snapshot (package: 20201108.816), nREPL 0.8.2
;; Clojure 1.10.1, Java 11.0.6
```
### Emacs version
26.3
### Operating system
ubuntu 18.04

**Comment by zmedelis** [comment]
Same here. I get the following in *Messages* 
```
[nREPL] Starting server via /usr/local/bin/clojure 
    -Sdeps '{:deps {nrepl {:mvn/version "0.8.2"} refactor-nrepl {:mvn/version "2.5.0"} cider/cider-nrepl {:mvn/version "0.25.4"}}}' 
    -m nrepl.cmdline --middleware '["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware"]'
```
The middleware in project local or global *nrepl.edn* is not being picked up.

Running `0.200.13@27.1 (spacemacs)`

**Comment by bbatsov** [comment]
I'm wondering how something like this might happen, as this file is read is directly by nREPL and has nothing to do with CIDER. I'll have to check the nREPL code, but my guess is that the command-line params overwrite whatever is the config and are not merged with it, which makes sense to me, but then again - I wrote this code. :D

**Comment by bbatsov** [comment]
Yeah, it seems I was right https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/cmdline.clj#L262

**Comment by zmedelis** [comment]
Trying to run reveal as described here https://vlaaad.github.io/reveal/#nrepl-based-editors
Given this what would you recommend to do?

**Comment by bbatsov** [comment]
If you want to rely on the config file you'll have to update the command-line options passed by CIDER. See https://docs.cider.mx/cider/0.26/basics/up_and_running.html#customizing-the-jack-in-command-behavior for details.

**Comment by zmedelis** [comment]
Good, that works. Thanks @bbatsov !

**Comment by xificurC** [comment]
@bbatsov 
> If you want to rely on the config file

I just want to configure this per project, somewhere, persistently, so that I don't have to manually write the jack-in command. Where would you store it?

**Comment by bbatsov** [comment]
I'd change the jack-in command via `.dir-locals.el`. See https://docs.cider.mx/cider/0.26/config/project_config.html for details

**Comment by xificurC** [comment]
Which variable? As a workaround I already have

```clojure
(cider-jack-in-nrepl-middlewares . ("cider.nrepl/cider-middleware" "vlaaad.reveal.nrepl/middleware"))
```

but that triggers an "unsafe variable" warning in every buffer. I'm sure that can be turned off somehow but that doesn't seem like the recommended path?

**Comment by dmg46664** [comment]
I'm also trying to run Reveal. I haven't got there yet in terms of what I need to fill in, but I'm finding the following post _revealing_ in terms of what the bits and pieces are. 
http://jr0cket.co.uk/2019/07/CIDER-jack-in-to-Clojure-CLI-projects-from-Spacemacs.html

Wish someone had posted a solution here verbatim (or that it just picked up the `.nrepl.edn` file). If I manage to get it working I'll post the solution here.

**Comment by dmg46664** [comment]
Found it easier to run and inject from the command line and connect using cider after, so jacking in will have to wait.

**Comment by henryw374** [comment]
Could someone post a step by step solution  involving `.dir-locals.el`  please?

**Comment by bbatsov** [comment]
Героям слава!

Can you post here the command string generated by CIDER? It should give us a good idea about what went wrong. Might also be a good idea to file a separate ticket about this, so it'd get more visibility.

**Comment by manenko** [comment]
Oh, probably I was unclear in my post :) I have no issues with CIDER. I was replying to @henryw374 's [message](https://github.com/clojure-emacs/cider/issues/2927#issuecomment-981792086) where he asks for 'step by step solution involving .dir-locals.el'.

**Comment by bbatsov** [comment]
I read `The following setup works for me:` as `The following setup doesn't work for me:`! 😆
