### ISSUE TITLE
How to link a cljc buffer with both clj and cljs repls?

### ISSUE THREAD

**Issue by qleguennec** [clojure-emacs/cider#2928]
It's not entirely clear for me in the documentation. Here's my issue in details:

- Project A (according to projectile), clj, in project/clj/
- Project B (according to projectile), cljs, in project/cljs/
- Project C (according to projectile), cljc, in project/cljc/

When I evaluate something in the cljc project, I would like it to be evaluated within both clj and cljs repls.
How can I do that?

**Comment by nivekuil** [comment]
I get that behavior automatically after `cider-jack-in-clj&cljs` or `cider-connect-clj&cljs`.

**Comment by qleguennec** [comment]
In the cljc project?

**Comment by nivekuil** [comment]
Yeah, e.g. in a cljc file with both repl connected to the project, C-c C-p will eval and print the form from both repls in one buffer.
