### ISSUE TITLE
Switch between CLJ and CLJS REPLs seems to need improvement

### ISSUE THREAD

**Issue by jmckitrick** [clojure-emacs/cider#2931]
**Is your feature request related to a problem? Please describe.**

cider-repl-switch-to-other gives me an error message when I try it.

There is a FIXME in the code referring to a need to implement cycling for multiple REPLs in a session.

When I'm in a CLJ REPL and hit C-c M-o, the message 'No other REPL in current session' when there is in fact a CLJS REPL I'd like to switch to.

I'm willing to help work on the code solution for this issue.

**Comment by bbatsov** [comment]
How did you start the two REPLs?

**Comment by jmckitrick** [comment]
@bbatsov I'd like to help work on this. I use both REPLs at my current job, and my current workflow is to hit C-x b and enter '-repl' to select the CLJ or the CLJS REPL, then C-x b to the buffer of the file I'm working on.

**Comment by jmckitrick** [comment]
I'm using it in 2 use cases:
1. At work, we start front and back end with `cli -M:dev` and I've added the necessary dependencies for CIDER.
So after it starts the back end server and the shadow server, I first run cider-connect-clj and then cider-connect-cljs and select shadow and the correct build that I want.
I get both REPLs, and all the CIDER features, but I have to do that extra work to switch the REPL connection when I go from CLJ files to CLJS files.

2. In my other project, I use the 'out of the box' commands with Leiningen to cider-jack-in-clj and then cider-jack-in-cljs to get the same basic result.

**Comment by bbatsov** [comment]
> There is a FIXME in the code referring to a need to implement cycling for multiple REPLs in a session.

That's something else, that's unrelated to your problem. Namely, one can have 1 CLJ REPL and 2 CLJS REPLs and for that the current comamnd needs to be adjusted. I doubt this is a common setup, though. 

 `cider-repl-switch-to-other` requires sibling REPLs that are part of the same sesman session to work. See https://docs.cider.mx/cider/0.26/usage/managing_connections.html for details. In the examples you gave you're starting two independend sesman sessions, that's why this command is not working for you.

**Comment by jmckitrick** [comment]
On one of these projects, when I connect to CLJS, it asks if I want to create a sibling connection and I say 'yes'. But `cider-repl-switch-to-other` still does not seem to work. Wouldn't that qualify as a sibling connection?

**Comment by jmckitrick** [comment]
Would it make sense to implement some kind of feature that accomplishes what I’m trying to do? If I have both CLJ and CLJS buffers and correspondings REPLs open, I switch to a buffer ending in ‘-repl’ and either matching clj or cljs. Then I switch back to the buffer of corresponding code. This reconnects that buffer to the correct nrepl. I do this each time I switch between front and back end.

**Comment by jmckitrick** [comment]
@bbatsov Is this a feature that would make sense? Is it something I could help with?

**Comment by jmckitrick** [comment]
@bbatsov Is there any interesting in implementing this feature? Would it be useful to anyone else?

**Comment by bbatsov** [comment]
Sorry about the slow responses. I'm crazy busy and I don't have time to catch up with everything. I'm starting to think that the problem you describe is probably the same bug that's discussed here https://github.com/clojure-emacs/cider/issues/2946, so if you want to troubleshoot what's wrong currently with the sessions that'd be great.
