### ISSUE TITLE
How to eval sexp in clojure-mode with cider and write result in current buffer

### ISSUE THREAD

**Issue by Pfedj** [clojure-emacs/cider#2933]
For example I have the code:
```
(println "foo")
```
With `cider-pprint-eval-last-sexp-to-comment` I can eval the code and get
```
(println "foo") ;; nil
```
in clojure buffer and also it print `foo` in cider-repl buffer.

I would like to get something like this in the current buffer:
```
(println "foo") ;; nil foo
```
How can I do this?

**Comment by bbatsov** [comment]
That's not currently supported (although it's possible in general) and I doubt it will ever be, as we can wait when exactly the output has finished printing (as you can continue to get some output after you've received the result for some evaluation - e.g. from a background thread). There's also the problem that when you have a combination of a bigger value and lots of output combining them can be very tricky.

**Comment by Pfedj** [comment]
I can see that it's not a good idea to do this in the general case. But I would like to explain in more detail what I want to do.
I would like to copy several `def` definitions to a separate buffer, `eval` this buffer, and view how the values of these variables change. I think this can be useful when debugging. It is also possible to crop variables for printing.
