### ISSUE TITLE
eldoc-mode disabled, global-eldoc-mode ignored.

### ISSUE THREAD

**Issue by convexstrictly** [clojure-emacs/cider#2934]
I upgraded to emacs 27.1 and cider 20201122.1448.  For some reason, eldoc-mode is always nil before and after jack-in.  global-eldoc-mode is t.  However until I enable eldoc-mode, I don't see any function signatures in the minibuffer.  

System Information
```
;; CIDER 1.0.0snapshot (package: 20201122.1448), nREPL 0.8.3
;; Clojure 1.10.1, Java 13

Linux desktop 4.4.0-194-generic #226-Ubuntu SMP Wed Oct 21 10:19:36 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

I even reduced my .emacs to just the following lines to ensure it wasn't some side-effect of some other configuration that was causing these problems.

```
(package-initialize)
(add-to-list 'package-archives 
	     '("melpa" . "http://melpa.org/packages/")
	     '("marmalade" . "http://marmalade-repo.org/packages/"))

(eval-when-compile
  (require 'use-package))
```

**Comment by bbatsov** [comment]
I'm guessing this might be something to do with the eldoc setup function:

```
(defun cider-eldoc-setup ()
  "Setup eldoc in the current buffer.
eldoc mode has to be enabled for this to have any effect."
  ;; Emacs 28.1 changes the way eldoc is setup.
  ;; There you can have multiple eldoc functions.
  (if (boundp 'eldoc-documentation-functions)
      (add-hook 'eldoc-documentation-functions #'cider-eldoc nil t)
    (setq-local eldoc-documentation-function #'cider-eldoc))
  (apply #'eldoc-add-command cider-extra-eldoc-commands))
```

I'll investigate this further when I can.

**Comment by bbatsov** [comment]
Btw, I can't reproduce this issue on Emacs 27. Everything works fine for me with only `global-eldoc-mode` enabled.

**Comment by pdbrown** [comment]
I noticed this too, on Emacs 28: Before cider starts, clojure-mode buffers don't have eldoc as expected. Once cider is running, new buffers enable eldoc, also as expected. But after starting cider, we run `cider-enable-on-existing-clojure-buffers`, which does `cider-eldoc-setup` but doesn't retrigger `turn-on-eldoc-mode`.
