### ISSUE TITLE
Use fully qualified names for dependencies 

### ISSUE THREAD

**Issue by jr0cket** [clojure-emacs/cider#2942]
The Clojure CLI tools requires the names of library dependencies to be fully qualified.

When cider-jack-in-clj is started with a deps.edn configuration, the generated command line included an unqualified nrepl dependency

```
/usr/local/bin/clojure -Sdeps '{:deps {nrepl {:mvn/version "0.8.3"} cider/cider-nrepl {:mvn/version "0.25.4"}}}' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware"]'
```

Until nrepl is deployed with a fully qualified name, the approach is to use a repeated name, e.g. `nrepl/nrepl`

**Comment by bbatsov** [comment]
> Until nrepl is deployed with a fully qualified name

But nREPL's fully qualified name is `nrepl/nrepl`, so I'm not sure what's there to deploy.

**Comment by jr0cket** [comment]
Okay, so then the code in cider that assembles the command line is faulty as its only using `nrepl`

**Comment by bbatsov** [comment]
I just fixed this. The code wasn't faulty, but rather the dep was declared in its short form as back then this wasn't an issue.
