### ISSUE TITLE
NPE on eldoc

### ISSUE THREAD

**Issue by emil0r** [clojure-emacs/cider#2944]
![Screenshot 2020-12-11 at 09 47 22](https://user-images.githubusercontent.com/49733/101882215-dedb1e00-3b95-11eb-8a1f-ca4c953b58d1.png)

Not sure what triggers it. I'm using shadow-cljs, connecting to the nREPL via cider-connect.

**Comment by bbatsov** [comment]
Just be some unhandled NPE in the eldoc cider-nrepl middleware, but without the stacktrace (I see you've hidded the tooling frames) it's very hard to tell where exactly.
