### ISSUE TITLE
"error in process filter: Symbol’s function definition is void: seq-contains-p" java classpath

### ISSUE THREAD

**Issue by qeshi** [clojure-emacs/cider#2951]
## Expected behavior
I'm trying to start cider-jack-in

## Actual behavior
Cider jack in doesn't start. It just gives me the error 

`"error in process filter: Symbol’s function definition is void: seq-contains-p" java classpath
`
## Steps to reproduce the problem

With a clean emacs, I just removed the emacs.d folder, then install Prelude with `$ curl -L https://git.io/epre | sh` 

Add the prelude-modules and uncomment the (require 'prelude-clojure)    

In a clojure project, M-x cider-jack-in

I manage to get it to work if I change the file 
`~/.emacs.d/elpa/cider-20201216.1330/nrepl-client.el`

From 
`1262               (specialq (lambda (pair) (seq-contains-p '("id" "op" "session" "time-stamp") (car pair))))`
To
`1262               (specialq (lambda (pair) (seq-contains '("id" "op" "session" "time-stamp") (car pair))))`

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

## Environment & Version information
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-16

### CIDER version information
CIDER 1.0.0snapshot (package: 20201216.1330)
[nrepl/nrepl\ \"0.8.3\"\] 
[cider/cider-nrepl\ \"0.25.5\"\] 
[org.clojure/clojure "1.10.1"] 
java version "1.8.0_201"   
Leiningen 2.9.5 on Java 1.8.0_201 Java HotSpot(TM) 64-Bit Server VM

**Comment by bbatsov** [comment]
I'm guessing that updating `seq.el` to its latest version from ELPA should solve this. I had to change the function as the old name was generating a warning on Emacs 27.

**Comment by genmeblog** [comment]
I have the same problem when toggling message logging. `seq` is in 2.22 version.
