### ISSUE TITLE
cider-repl-mode fails with "non-empty :arglists attr-map"

### ISSUE THREAD

**Issue by redraiment** [clojure-emacs/cider#2952]
Reproduce method in cider 0.26.1:

1. Define function (or macro, multimethod etc.) with non-empty `:arglists`
2. Type the function name, then it will fails with below error messages

![image](https://user-images.githubusercontent.com/932074/103000415-ffc44b80-4565-11eb-9673-96faaf63657a.png)

**Comment by dpsutton** [comment]
Your arglists is of the wrong shape. As the plural name implies, it is a sequence of arglists, not a single arg vector. You need to have `'[[x]]`. 

```clojure
(:arglists (meta #'assoc))
([map key val] [map key val & kvs])

(defn foo [x])
-> #'user/foo
(:arglists (meta #'foo))
-> ([x])
```
