### ISSUE TITLE
[syntax highlighting] functions highlighted as vars

### ISSUE THREAD

**Issue by andreyorst** [clojure-emacs/cider#2953]
I've disabled function highlighting, to bring color intensity a bit down by changing `cider-font-lock-dynamically`.
By default it is set to this:
```emacs-lisp
'(macro core function var)
```

And I get the usual highlighting:

![image](https://user-images.githubusercontent.com/19470159/103033597-d8747b00-4573-11eb-8300-b7dfff14f005.png)

However if I remove `core` and `function` from this setting:
```emacs-lisp
(setq cider-font-lock-dynamically '(macro var))
```

I get the following result after I load file:

![image](https://user-images.githubusercontent.com/19470159/103033523-a7944600-4573-11eb-859a-770cd9030b54.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/19470159/103033735-33a66d80-4574-11eb-910a-3e1ab87c6803.png)

## Steps to reproduce the problem

1. Download [bug.zip](https://github.com/clojure-emacs/cider/files/5736985/bug.zip), extract and run Emacs with provided minimal `init.el`:

  ```
  $ unzip bug.zip
  $ cd bug
  $ emacs -q -l repro-init.el bug.clj
  ```
2. Jack in: <kbd>Ctrl-c</kbd><kbd>Alt-j</kbd><kbd>y</kbd>
3. Load `bug.clj` file with <kbd>Ctrl-c</kbd><kbd>Ctrl-k</kbd>

This results into the following highlighting:

![image](https://user-images.githubusercontent.com/19470159/103034303-a237fb00-4575-11eb-8953-72ca615b257e.png)

### CIDER version information

```
;; CIDER 1.0.0snapshot (package: 20201216.1330), nREPL 0.8.3
;; Clojure 1.10.1, Java 11.0.9.1
```

### Emacs version

GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13) of 2020-12-23

### Operating system

Fedora 33

**Comment by bbatsov** [comment]
So, to summarize you don't want the var highlighting, right? 

Does this disappear if you do `(setq cider-font-lock-dynamically '(macro))`? I have a feeling the fact that pretty much everything is a var might be messing things up.

**Comment by andreyorst** [comment]
> So, to summarize you don't want the var highlighting, right?

Umm, not quite. I do want dynamic vars to be highlighted, it is useful feature, I just don't want functions to be highlighted **as** vars. Removing `var` from `cider-font-lock-dynamically` surely removes highlighting, but that's not what I'm after.

> I have a feeling the fact that pretty much everything is a var might be messing things up.

If CIDER can properly highlight functions, maybe this info can be used to unhighlight those? Or when highlighting a var check if it is a function var, if this even makes sense..

**Comment by bbatsov** [comment]
Yeah, my point was that probably the bug is related to the current definition of var. I don't remember this code well anymore, but I'll review it when I can. If you'd like to take a stab at this you can start here https://github.com/clojure-emacs/cider/blob/4b6c0e9936d125102c2dd0bb1dedbd80fb4907a6/cider-mode.el#L751

**Comment by bbatsov** [comment]
In particular:

```
(cond ((and do-macro (nrepl-dict-get meta "macro"))
                              (push sym macros))
                             ((and do-function (or (nrepl-dict-get meta "fn")
                                                   (nrepl-dict-get meta "arglists")))
                              (push sym functions))
                             (do-var (push sym vars)))
```

I guess the bug is obvious here - if the function highlighting is not enabled everything becomes a var. Depending on your perspective this can be an issue or a feature. :-) I wonder why `println` didn't get the same treatment, though. Anyways, it seems that's going to be relatively simple to address.

**Comment by andreyorst** [comment]
>  wonder why println didn't get the same treatment, though

Perhaps because it is handled by `core` highligting separately. I've pushed a naive solution, hope this is enough
