### ISSUE TITLE
eval cmds fail with "Wrong number of arguments"

### ISSUE THREAD

**Issue by mobileink** [clojure-emacs/cider#2954]
## Expected behavior

cider-eval-last-sexp should eval the last sexp

## Actual behavior

`apply: Wrong number of arguments: #[(&optional arg1 arg2 arg3) "ÀÁ\"" [clojure-quick-repls-set-connection nil] 3], 4`

## Steps to reproduce the problem

Follow the example [Using Figwheel](https://docs.cider.mx/cider/cljs/figwheel.html) or [Node.js repl](https://docs.cider.mx/cider/cljs/other_repls.html#node-js-repl)

deps.edn:
```
{:deps {org.clojure/clojure {:mvn/version "1.10.1"}
        org.clojure/clojurescript {:mvn/version "1.10.773"}
     ;; I get the same results with or without figwheel
        ;; com.bhauman/figwheel-main {:mvn/version "0.2.12"}
        ;; com.bhauman/rebel-readline-cljs {:mvn/version "0.1.4"}
        }
 :paths ["src" "target" "test"]
 }
```

src/obazl/core.cljs:
```
(ns obazl.core)
(println "This text is printed from src/obazl/core.cljs. Go ahead and edit it and see reloading in action.")
(defn multiply [a b] (* a b))
```

emacs config:  I use `use-package` instead of package.el.  init.el contains `(use-package cider :ensure t)`

The jack-in works. I get a cljs repl buffer where I can evaluate forms.  `cider-load-file` works, it prints to the cljs repl buffer.  But `cider-eval-last-sexp` and `cider-eval-region` throw the error.

### CIDER version information

```
;; CIDER 0.26.1 (Nesebar), nREPL 0.8.0
;; Clojure 1.10.1, Java 11.0.5
```

### Emacs version

GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2020-08-12

### Operating system

MacOS Catalina 10.15.7

**Comment by mobileink** [comment]
Followup note: I'm trying to reproduce with a clean emacs init.el containing just:

```
(eval-when-compile
  (require 'use-package))

(use-package cider
  :ensure t
  :pin melpa-stable)
```

Result: `(error "Archive ’melpa-stable’ requested for package ’cider’ is not available.")`

**Comment by mobileink** [comment]
Ok, it works with a minimal emacs config, so obviously there is something in my init.el that annoys cider.  No idea what at this point.

Strong suggestion: the install instructions suggest that merely running `package-list` etc. is sufficient to install cider, which does not seem to be the case.  It would be helpful if you would provide an indication the package.el must be configured to talk to melpa etc.

Second suggestion: add an item to the troubleshooting list telling the user having problems how to run cider with a minimal emacs configuration, in order to determine whether problems are caused by emacs packages.

**Comment by bbatsov** [comment]
Your error seems to be coming from this legacy package https://github.com/symfrog/clojure-quick-repls

**Comment by bbatsov** [comment]
And good points about the suggestions. I'll address those in the docs.
