### ISSUE TITLE
Clojuredocs hints not working; huge stack trace errors outputted constantly in Cider repl

### ISSUE THREAD

**Issue by csulpizi** [clojure-emacs/cider#2962]
I do not know if this has been reported or if this is an issue on my end, or an issue with the clojuredocs host, but this is currently preventing me from using Cider.

## Expected Behaviour
Let's say I want to use the fn `+`. When I type in `(+ ` cider should give me hints for the arg-lists of `+` in the mini-buffer at the bottom

## Actual Behaviour
Instead, cider spits out a ton of errors in the console:
```
ERROR: Unhandled REPL handler exception processing message {:op eldoc, :ns my.ns, :symbol constantly, :session f429aa7b-d660-4626-afd6-32c11b72719f, :id 18}
java.io.FileNotFoundException: https://clojuredocs-edn.netlify.app/export.compact.edn
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1915)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
... stack trace continues for a couple hundred lines
```

## Steps to reproduce the problem
This has been happening consistently as described above since December 20th or so. As far as I know nothing has changed. I can reproduce it simply by starting to type any function into the repl

### CIDER version information
;; Connected to nREPL server - nrepl://localhost:60634
;; CIDER 1.1.0snapshot (package: 20210104.915), nREPL 0.6.0
;; Clojure 1.10.1, Java 12.0.2

### Emacs version
26.3

### Operating system
OSX Mojave 10.14.16

**Comment by bbatsov** [comment]
Hmm, this problem should happen only with an old version of the cider-nrepl middleware, as the newer ones don't download anything. How are you starting CIDER?

**Comment by csulpizi** [comment]
The issue seems to be resolved on my end. I updated CIDER a few days ago, but I guess I had never actually rebooted my machine. When I started it up this morning it's working fine as expected. Thanks!
