### ISSUE TITLE
nREPL doesn't work on Windows

### ISSUE THREAD

**Issue by Prometheus77** [clojure-emacs/cider#2963]
Expected behavior:

When editing a .clj file in Clojure-mode, `cider-jack-in-clj` should start the REPL.

Observed behavior:

`cider-jack-in-clj` throws an error: Could not start nREPL server: java.lang.NumberFormatException: Invalid number: 0.8.3

More details here:

https://stackoverflow.com/questions/65566706/error-in-process-sentinel-could-not-start-nrepl-server-java-lang-numberformate

**Comment by StargazeSparkle** [comment]
I have experienced this same issue having installed cider today on W10.

https://user-images.githubusercontent.com/66642904/103757568-f49a0280-4fde-11eb-8c52-484c32936681.mp4

**Comment by bbatsov** [comment]
I guess that's some peculiarity of the Windows command-line, but I'm not familiar with it. @PEZ any ideas?

**Comment by PEZ** [comment]
We have reports from some Windows users about quoting issues. Seems to be related to Leiningen and how it is invoked. Very fuzzy so far, but just the latest days there seem to be hope. Check this out https://github.com/BetterThanTomorrow/calva/issues/387

**Comment by CloseToZero** [comment]
A quick and dirty fix (works on commit 68bc5e39):
```emacs-lisp
(when (eq system-type 'windows-nt)
    (define-advice cider--list-as-lein-artifact (:override (list &optional exclusions))
      "Add missing double quotes around the version string for cmd/PowerShell."
      (shell-quote-argument
       (format "[%s \"%S\"%s]" (car list) (cadr list) (cider--lein-artifact-exclusions exclusions)))))
```
I guess the double quotes added by `shell-quote-argument` may be eaten by lein.bat, I'm not sure.

**Comment by omarpta** [comment]
I'm facing the same problem:

```
cmd.exe /d /c lein update-in :dependencies conj [nrepl,"0.8.3"] -- update-in :plugins conj [cider/cider-nrepl,"0.26.0"] -- update-in [:repl-options,:nrepl-middleware] conj '["cider.nrepl/cider-middleware"]' -- with-profile +uberjar repl :headless
```

![calva02](https://user-images.githubusercontent.com/5091444/119998455-17857d00-bfa7-11eb-8b19-aa7843377c09.PNG)

![calva01](https://user-images.githubusercontent.com/5091444/119998542-2cfaa700-bfa7-11eb-9e8d-e573e4a785dc.PNG)

**Comment by PEZ** [comment]
This could be a big in the java.exe bring used. Check `where java` and if that turns something with Oracle and something with `javapath` in it, then that is the problem. And the solution is then to use another java.

**Comment by omarpta** [comment]
Yes, I just installed the OpenJDK 11 and everything is working now. Thanks

**Comment by PEZ** [comment]
Thanks for confirming. Then it is this bug: https://bugs.openjdk.java.net/browse/JDK-8266473
