### ISSUE TITLE
Showing evil mode in cider prompt

### ISSUE THREAD

**Issue by introom** [clojure-emacs/cider#2965]
This will become especially useful under cider repl.   The evil mode indicator in the modeline is too far to look at.

**Comment by bbatsov** [comment]
I'm not sure I understand what exactly do you have in mind, so more details would be useful.

**Comment by introom** [comment]
[N]some-ns >
[I]some-ns >
N (normal) and I(insert) will change based on the evil mode.

**Comment by bbatsov** [comment]
Got it. Something like this should be easy to do, although the changes could be reflected only for new prompts. We can't toggle this for a prompt that has been already displayed.

**Comment by alvinfrancis** [comment]
I feel like this is too specific to warrant an addition in cider.  There's already the `cider-repl-prompt-function` for customization (thought admittedly it wouldn't work on its own), and would rely more on evil-mode than cider logic.  Anyway, feels more like a personal configuration sort of thing. In which case, something like the following could work:

``` lisp
(defun +clojure|cider-repl-evil-hook ()
  (when (and
         (string-prefix-p ;; cider-repl-emit-prompt will trigger on current focused buffer
          "*cider-repl"
          (buffer-name (window-buffer (selected-window))))
         (not (eq evil-previous-state evil-next-state)))
    (cider-repl-emit-prompt (current-buffer))))

(defun +clojure--cider-repl-prompt-evil (namespace)
  (format "[%s] %s> "
          (upcase (substring (symbol-name evil-next-state) 0 1))
          namespace))

(setq cider-repl-prompt-function #'+clojure--cider-repl-prompt-evil)

(add-hook 'cider-repl-mode-hook
          (lambda ()
            (add-hook 'evil-normal-state-entry-hook #'+clojure|cider-repl-evil-hook nil t)
            (add-hook 'evil-insert-state-entry-hook #'+clojure|cider-repl-evil-hook nil t)
            (add-hook 'evil-visual-state-entry-hook #'+clojure|cider-repl-evil-hook nil t)))
```

This would customize the prompt function to show the evil-mode state.  And it would trigger a new prompt to be emitted when the evil-mode state changes.

**Comment by bbatsov** [comment]
> I feel like this is too specific to warrant an addition in cider.

Agreed. I guess your snippet brings closure this ticket. Thanks!
