### ISSUE TITLE
Complex print options should be converted to edn

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#2966]
## Expected behavior

I expect cider to convert `cider-print-options` before sending them to backends.

For instance convert `t` to Clojure boolean `true` in case `zprint`'s `color?` option.

## Actual behavior

At `nrepl` startup I see an error, depending on the option I pass. For instance for color it tells me that `t` or `true` is not a boolean.

## Steps to reproduce the problem

Set the following:

```
(setq cider-print-fn 'zprint)
(setq cider-print-options '(("color?" t)))
```

### CIDER version information

Latest `HEAD`

As a workaround you can `(setq cider-print-options nil)` and use `$HOME/.zprint.edn` instead.

**Comment by bbatsov** [comment]
> For instance convert t to Clojure boolean true in case zprint's color? option.

That's hard to do, given how in Emacs Lisp there are no booleans. We might add some special handling for symbols like booleans, though.
