### ISSUE TITLE
Show inline docs at point like lispy and quick-peek

### ISSUE THREAD

**Issue by MicahElliott** [clojure-emacs/cider#2968]
It would be great if it were easier to see see docs right at point without a new window or invoking completion. Presently, the two ways to see docs are:

- `cider-clojuredocs` to pop open a new window
- go to end of fn and invoke company for a completion that will pop up just the docstring

Both of those are great, but for quickest lookups, we could do what [lispy](https://github.com/abo-abo/lispy#ide-like-features) and [quick-peek](https://github.com/cpitclaudel/quick-peek) do with an inline doc. See the screenshots/gifs on both of those.

This actually [works with lispy already](https://github.com/abo-abo/lispy/blob/master/lispy-inline.el#L241), but it's a heavy way to get this (and lispy does many other opinionated things), and is flaky IME.

My proposal is to slide up or down the code to fit the fn signature and short docstring (not the long clojuredocs) right into view.

Maybe quick-peek could be leveraged for this.

Or maybe there's already a simple way to get this info with company with a single keystroke?

**Comment by bbatsov** [comment]
This is a duplicate of an old issue https://github.com/clojure-emacs/cider/issues/1982 I'm open to the idea, but I never needed this, so my incentive to tackle it was pretty low.

Company does show the documentation for the current candidate in the minibuffer. Btw, the documentation is also visible when you hover over a symbol with the mouse.

**Comment by MicahElliott** [comment]
Thanks @bbatsov! The Minibuffer functionality is great and is probably fine for this if it could expand to show the fn description too. But it's fancy about highlighting current arg, so maybe there's more to adding there than I was guessing.

And I still like the idea of showing inline (I realized when I tried flycheck-inline recently) a little better. Sorry for the dupe! Feel free to close if you prefer.

**Comment by dpsutton** [comment]
i've wanted this for a while and even played around with some of the popup libraries for emacs to accomplish this. my memory was that they all had limitations and weirdness. I wish there was something built in to emacs that was rock solid that was a "popup". I'm not sure which computer might have the patch laying around but i'll see if i can find it.

annoying things i remember are off by one errors when displaying strings such that the last character of each line was put on a new line by itself, no easily dismissable, etc.

**Comment by MicahElliott** [comment]
The lispy implementation is really nice. But is entwined with its other parts.

Something related to what you may be thinking about, @dpsutton: it'd be nice to strip out the docstring noise that shows up in the help.

![Screen Shot 2021-01-15 at 2 11 08 PM](https://user-images.githubusercontent.com/159047/104783857-ced9cf80-573b-11eb-9293-e92eca8b6bc5.png)

There I get annoyed with the useless "Added in 1.0", "is defined in", and "[back]".

**Comment by MicahElliott** [comment]
Here's the (hacky) rudiments to get quick-peek to show the paragraph. If this isn't a terrible approach, I'll try making a PR.

```elisp
(quick-peek-show (nth 10 (cider-var-info (thing-at-point 'word 'no-properties))))
```

![Screen Shot 2021-01-15 at 4 23 33 PM](https://user-images.githubusercontent.com/159047/104791029-0f424900-574e-11eb-9da9-73b42003bb12.png)

Or at least it's a recipe for anyone who wants to put a binding for this and `quick-peek-hide` in their `.init.el`.

**Comment by bbatsov** [comment]
As you wish. My preference would be to avoid adding deps to CIDER if they won't be used extensively, as each dep is a form of liability that might bite you down the road. I'm assuming that `quick-peek` is just some simple overlay hack this can easily be implemented directly in CIDER.

**Comment by MicahElliott** [comment]
Here's a simple way to do the inlining that I'm satisfied with.
```elisp
;; Quick-Peek for Cider
;; https://github.com/clojure-emacs/cider/issues/2968
(require 'quick-peek)
(defvar my-cider-inline-docs-opened-p nil
  "Toggle to support an inline help being open (expanded) or not.")
(defun my-cider-inline-docs-toggle ()
  "Show a fn's docstring paragraph inline."
  (interactive)
  (if my-cider-inline-docs-opened-p
      (progn
	(setq my-cider-inline-docs-opened-p nil)
	(quick-peek-hide))
    (progn
      ;; If not on a word, will get an error
      (quick-peek-show
       (replace-regexp-in-string
	"^ +" ""
	(nth 10 (cider-var-info (thing-at-point 'word 'no-properties)))))
      ;; So set this only when above succeeds
      (setq my-cider-inline-docs-opened-p t))))
;; (key-chord-define-global "CD" 'my-cider-inline-docs-toggle)
```

![Screen Shot 2021-01-16 at 6 18 21 AM](https://user-images.githubusercontent.com/159047/104814508-2e7bbd80-57c4-11eb-9bf9-ca1ed24ead7d.png)

Totally understand not wanting a new dep. FWIW, [quick-peek](https://github.com/cpitclaudel/quick-peek/blob/master/quick-peek.el) is ~200 SLOC and has just a `cl-lib` requirement. It has a few customizations that I'd guess CIDER wouldn't care too much about:

- the ugly green default bars can be changed or elimated (just do the latter)
- the bg color can be set (just use gray as in screenshot?)
- inline doc above or below (just default to above)

It can also flexibly open several inlines at a time, which I don't personally find useful. Code for that could go away too, and be replaced with the toggle logic I put above.

So if we pull just the overlay code out of quick-peek, I'd think it's a couple dozen lines of elisp. I might try to tackle that at some point, or hope someone else will. But for today, I'm going to just use the fn I posted here.

**Comment by bbatsov** [comment]
Sounds like a plan to me. :-)

**Comment by MicahElliott** [comment]
FWIW, I've been using this quick-peek approach for a few months now and I use it constantly, almost always before `cider-clojuredocs` (though `cider-clojuredocs` is still amazing and essential). Also has me wanting to make sure I've written docstrings for more fns ans nss.

**Comment by vemv** [comment]
Personally I show docs in the echo area:

![image](https://user-images.githubusercontent.com/1162994/133942432-c4ba8542-cb3b-4d8e-8c6e-43777e76c386.png)

I think it especially makes sense for Emacs which has a limited support for widgets (I do use company-mode FWIW, for completions).

Docs being longer than completions deserve a place that can accommodates them scalably. I had tried a couple popup libraries over the years but they never read as nicely as the would in other IDEs.

I'll contribute this feature to cider.el one day.
