### ISSUE TITLE
nrepl 0.8.3 conflicting with 0.6.0 on cider-jack-in when using `:pedantic?` in leiningen project

### ISSUE THREAD

**Issue by dparis** [clojure-emacs/cider#2973]
## Expected behavior
Running `cider-jack-in` for a leiningen project with `:pedantic? :abort` configured should successfully start a REPL process.

## Actual behavior
Running `cider-jack-in` for a leiningen project with `:pedantic? :abort` configured results in the following error message:

```
error in process sentinel: Could not start nREPL server: Tried to load nrepl version 0.6.0 but 0.8.3 was already loaded.
Possibly confusing dependencies found:
[refactor-nrepl "2.5.0"] -> [nrepl "0.6.0" :exclusions [org.clojure/clojure]]
 overrides
[cider/cider-nrepl "0.25.8"] -> [nrepl "0.8.3" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[cider/cider-nrepl "0.25.8" :exclusions [nrepl]]

Aborting due to :pedantic? :abort
```

## Steps to reproduce the problem
1. Create new leiningen app: `lein new app cider-test-app`
2. Add `:pedantic? :abort` to project.clj
3. Using latest version of cider on melpa (I pulled `1.1.0snapshot (package: 20210126.1430)` within spacemacs) attempt to initiate a `cider-jack-in` for that project

### CIDER version information

Cider version from melpa:  `1.1.0snapshot (package: 20210126.1430)`

Starting without `:pedantic? :abort`:

```
REPL-y 0.4.4, nREPL 0.8.3
Clojure 1.10.1
```

### Lein/Boot version

Leiningen 2.9.5, installed via homebrew

### Emacs version

GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H15)) of 2021-01-08

### Operating system

Mac OS X Catalina (10.15.7)

**Comment by dparis** [comment]
This has only started happening this morning after an emacs package upgrade. My previous cider version wasn't giving this error within the same project, and I'm _pretty_ sure my last package upgrade before today was fairly recent, probably within the last week or two. I saw this issue from 2019 which seemed potentially similar:  https://github.com/clojure-emacs/refactor-nrepl/issues/283

**Comment by bbatsov** [comment]
`refactor-nrepl` rarely gets any love these days and it probably needs a dep update. I don't personally use it, so I rarely pay it any attention - I just do the bare minimum of maintenance there to keep the boat afloat. 

The warnings seems legit, although this has been the situation for a very long time (cider-nrepl depending on a newer nREPL that refactor-nrepl), so I can't understand why you'd get an error just now.
