### ISSUE TITLE
cider-jack-in with clojure-cli on windows doesn't work

### ISSUE THREAD

**Issue by jpathy** [clojure-emacs/cider#2980]
`clojure-cli` installed using https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows .

Quoting seems wrong for the following line. 
https://github.com/clojure-emacs/cider/blob/b82fd1cbee7ecac05939ab0d5009d700d1cc21eb/cider.el#L574

I changed it to 
````
(apply-partially #'format "%s")
````
It seems to work.

**Comment by bbatsov** [comment]
I thought on Windows this was supposed to be using powershell and encoded there to avoid the quoting issues. Personally, I just use WSL and everything works great with it.

**Comment by bbatsov** [comment]
From the docs:

> To use cider-jack-in with tools.deps on Windows set the cider-clojure-cli-command to "powershell". This happens by default if you are on Windows and no clojure executable is found. Using "powershell" will Base64 encode the clojure launch command before passing it to PowerShell and avoids shell-escaping issues.

**Comment by jpathy** [comment]
With base64 encoding decoded following command gets passed to powershell: 
````
> clj -Sdeps '{:deps {refactor-nrepl {:mvn/version ""2.5.0""} cider/cider-nrepl {:mvn/version ""0.25.8""}} :aliases {:cider/nrepl {:main-opts [""-m"" ""nrepl.cmdline"" ""--middleware"" ""[\""cider.nrepl/cider-middleware\""]""]}}}' -M:cider/nrepl
Error while parsing option "--config-data {:deps {refactor-nrepl {:mvn/version \"2.5.0\"} cider/cider-nrepl {:mvn/version \"0.25.8\"}} :aliases {:cider/nrepl {:main-opts [\"-m\" \"nrepl.cmdline\" \"--middleware\" \"[\"cider.nrepl/cider-middleware\"\"]\"]}}}": java.lang.RuntimeException: EOF while reading string

It seems that the quoting is unnecessary for `--middleware` https://docs.cider.mx/cider-nrepl/usage.html#via-clj .

**Comment by scottdw** [comment]
I can confirm that the fix proposed by @jpathy works for powershell on windows and has no ill effects with bash on linux (fedora 33).

From a correctness stand point the docs indicate that the `middleware` parameter value should be a vector of var names not strings regardless of how they should be escaped if they were to be strings or how they were formatted in previous versions of cider.

**Comment by bbatsov** [comment]
Got it. PR welcome then!
