### ISSUE TITLE
Don't rebind M-. register xref backend instead

### ISSUE THREAD

**Issue by andreyorst** [clojure-emacs/cider#2987]
## Expected behavior

Packages such as [dumb-jump](https://github.com/jacktasia/dumb-jump) remain to work when CIDER fails to find something.

## Actual behavior
Dumb jump is enabled like this:

``` emacs-lisp
(add-hook 'xref-backend-functions #'dumb-jump-xref-activate)
```

However CIDER rebinds <kbd>M-.</kbd> key making all other xref options inaccessible. This also prevents from such thigns as prefixing `M-.` with numeric args to make it open definition in other windows.

### CIDER version information

```
;; CIDER 1.1.0snapshot, nREPL 0.8.3
;; Clojure 1.10.1, Java 11.0.10
```

### Emacs version

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13, cairo version 1.16.0) of 2021-01-17

### Operating system

Fedora 33

**Comment by bbatsov** [comment]
Yeah, I plan to get there at some point. If someone wants to see this faster - PRs are welcome!

**Comment by stig** [comment]
This is a duplicate of #2831, which has some more information.

**Comment by andreyorst** [comment]
oh, wasn't able to find it. Closing as duplicate then
