### ISSUE TITLE
Debugger doesn't ignore commented out expressions

### ISSUE THREAD

**Issue by dadinn** [clojure-emacs/cider#2996]
I am getting a really confusing behaviour when using the Cider debugger on a code with commented out blocks.
The debugger seems to stop on expressions inside the commented out block, yet it does things which are outside the block.

## Expected behavior

I am trying to debug into the following piece of code (a minimal example):

```
#dbg
(defn test-function []
  #_
  (let [a (java.lang.System/currentTimeMillis)]
    (println "This should have never happened!" a))
  (let [b (java.lang.System/currentTimeMillis)]
    (println "This is what I want to see!" b))
  (let [c (java.lang.System/currentTimeMillis)]
    (println "Let's finish this, alright!" c)))
```

I would expect the debugger to ignore the first `let` block commented out by the `#_` reader macro,
and stop first only at the second `let` block, so I could step through the rest of the code from there,
to execute the remaining `println` expressions. 

## Actual behavior

The debugger seems to stop first at the `println` statement inside the commented out `let` block.
Seemingly I can step through all the expressions in the commented out block twice, yet the lines which get printed out by the `println` statement are:
```
This is what I want to see! 1616675364833
Let's finish this, alright! 1616675369010
```

Even though the results seem correct, the experience was rather confusing. I definitely thought the debugger is showing something the wrong way.

## Steps to reproduce the problem

As written above

### CIDER version information

```
;; CIDER 1.0.0snapshot, nREPL 0.8.3
;; Clojure 1.10.2, Java 1.8.0_275
```

### Lein/Boot version

`Leiningen 2.9.5 on Java 1.8.0_275 OpenJDK 64-Bit Server VM`

### Emacs version

`25.1.1`

### Operating system

Debian 9.13 (Stretch)

**Comment by yuhan0** [comment]
I have a workaround for this on my local copy of Cider, but the debugger's implementation of "coordinates" is still rather buggy and locates incorrect forms in other situations. 

A simpler repro: (`M-x cider-eval-defun`, `n`)
```clj 
#dbg
(let [a 3]
  #_(inc a)
  (dec a))
```

Expected:
```clj
#dbg
(let [a 3]
  #_(inc a)
  (dec a)) [=> 2]
```

Actual:
```clj
#dbg
(let [a 3]
  #_(inc a) [=> 2]
  (dec a))
```


I never got around to investigating it more closely - will submit my fix for now.

**Comment by bbatsov** [comment]
Initially it was pretty hard to deal with `#_` so we mostly ignored those cases, and afterwards we never revisitted this. I guess that's part of the reason I never use `#_`. :D

**Comment by dadinn** [comment]
`#_` is cool shit, and it's biggest benefit is using it on code in-heavy-development, just like when you would use `#dbg` the most.

For example you can easily comment out an expression, and when you look through your git changes it doesn't mess everything up with indentation like a `comment` block does. 

So I would say the best use-case for `#_` is together with `#dbg` :/
