### ISSUE TITLE
cider-jack-in-cljs cannot find npx shadow-cljs

### ISSUE THREAD

**Issue by lljr** [clojure-emacs/cider#3001]
## Expected behavior
`M-x cider-jack-in-cljs` should start shadow-cljs
## Actual behavior
`user-error: The npx shadow-cljs executable isn’t on your ‘exec-path’`
## Steps to reproduce the problem
create a project with shadow-cljs. Go to shadow-cljs.edn. Run `M-x cider-jack-in-cljs`.

## Environment & Version information
Emacs 27.1. 

### CIDER version information
1.0.0

I have exec-path-from-shell installed and this in the very end of my init.el
```
    (exec-path-from-shell-copy-env "PATH")
    ;; example of setting env var named “path”, by appending a new path to existing path
    (setenv "PATH"
      (concat
        "/home/wario/.nvm/versions/node/v14.2.0/bin/" ";"
       (getenv "PATH")
      )
    )
```

I copied from this archived chat: https://clojurians-log.clojureverse.org/cider/2020-04-29

### Emacs version
27.1
### Operating system
Ubuntu 20.04

**Comment by lljr** [comment]
I should add I'm using NVM to install and manage node.

**Comment by bbatsov** [comment]
Is it also in your `exec-path` variable?

**Comment by lljr** [comment]
hey @bbatsov ! thanks for the quick reply. It's not in `exec-path`, which is what is weird about it... It's supposed to add it with 
```
 (setenv "PATH"
      (concat
        "/home/wario/.nvm/versions/node/v14.2.0/bin/" ";"
       (getenv "PATH")
      )
    )

```
but when I inspect `exec-path` with `C-h v exec-path` I get 
```
("/home/wario/.guix-profile/bin/" "/home/wario/.guix-profile/sbin/" "/home/wario/.local/bin/" "/home/wario/.local/bin/" "/home/wario/bin/" "/home/wario/.guix-profile/bin/" "/home/wario/.guix-profile/sbin/" "/home/wario/.guix-profile/bin/" "/home/wario/.guix-profile/sbin/" "/home/wario/.config/guix/current/bin/" "/home/wario/.local/bin/" "/usr/local/sbin/" "/usr/local/bin/" "/usr/sbin/" "/usr/bin/" "/sbin/" "/bin/" "/usr/games/" "/usr/local/games/" "/snap/bin/" "/gnu/store/62xfj3bfvjjzr8wd46q788hp1nbq5a0z-emacs-27.1/libexec/emacs/27.1/x86_64-pc-linux-gnu/")
```

**Comment by dakra** [comment]
I think `exec-path` is initialized from then `PATH` environment variable only at startup of Emacs.

To change it later, maybe try something like:
```emacs-lisp
(add-to-list 'exec-path "/home/wario/.nvm/versions/node/v14.2.0/bin/")
```

**Comment by lljr** [comment]
@dakra interesting. When I have only     `(exec-path-from-shell-initialize)` I get the `user-error: The npx shadow-cljs executable isn’t on your ‘exec-path’` error but when I have both 
```
(exec-path-from-shell-initialize)
    (add-to-list 'exec-path "/home/wario/.nvm/versions/node/v14.2.0/bin/")
``` 

I get this error: 
```
error in process sentinel: Could not start nREPL server: /usr/bin/env: ‘node’: No such file or directory
```

**Comment by bbatsov** [comment]
The first is a message from CIDER (it tries to check if the command it will run is on the path or not), the second is from the shell itself.

**Comment by dpsutton** [comment]
When I've had these issues, the best way to get quick feedback is to open up an eshell buffer `m-x eshell` or `C-x m` i believe. Then do `which node` and `which npx` and `which npm`. As soon as these can find the executables you should be in the clear.

**Comment by lljr** [comment]
So I see where my issue is. I can add `    (add-to-list 'exec-path "/home/wario/.nvm/versions/node/v14.2.0/bin/")` and it will show in `exec-path`. However,  `    (exec-path-from-shell-copy-env "PATH")` will not work anymore so it will throw `error in process sentinel: Could not start nREPL server: /usr/bin/env: ‘node’: No such file or directory`.  If I have only  `   (exec-path-from-shell-copy-env "PATH")` then the previous error will not be thrown but the npx shadow-cljs will appear. How do I solve this issue so that all my stuff is added to path and exec-path copies PATH correctly in Emacs?

**Comment by lljr** [comment]
I went over and read the docs at https://github.com/purcell/exec-path-from-shell. You see, at the bottom it reads

> Follow best practice by setting your environment variables so that they are available to both interactive and non-interactive shells. In practical terms, for most people this means setting them in ~/.profile, ~/.bash_profile, ~/.zshenv instead of ~/.bashrc and ~/.zshrc.


I had my NVM variable set up in `.bashrc` so after I moved it to `.bash_profile` it worked. 


Then I wrote this in my `init.el`

```elisp
    (exec-path-from-shell-copy-env "PATH")
    (exec-path-from-shell-initialize)
```
