### ISSUE TITLE
Default tab-complete does not work

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/cider#3005]
## Expected behavior

`TAB`-complete works as described in the [docs](https://docs.cider.mx/cider/usage/code_completion.html#standard-completion).

## Actual behavior

Nothing happens when I press `TAB`.

## Steps to reproduce the problem

-  emacs -Q
- `M-x package-initialize`
- visit a Clojure file (e.g., I used my [utils.clj](https://github.com/manuel-uberti/boodle/blob/master/src/clj/boodle/utils.clj))
- Jack-in with `C-c C-x j j` (I had to press `RET` on `clojure-cli` for that specific file)
- `C-c C-k`
- Try to tab-complete (e.g., in that file at line 17 I typed `(jf/` and pressed `TAB`)

### CIDER version information

```
;; CIDER 1.1.0snapshot (package: 20210416.1915), nREPL 0.8.3
;; Clojure 1.10.3, Java 11.0.10
```

### Lein/Boot version

I am using `clj` with `deps.edn`.

### Emacs version

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.18, cairo version 1.16.0) of 2021-04-18 (commit `2822246b5d8154d0166e17ffd28a1d85b57d68aa`)

### Operating system

Ubuntu 20.04

**Comment by manuel-uberti** [comment]
FTR, I bumped into this when testing Corfu, see https://github.com/minad/corfu/issues/8

**Comment by bbatsov** [comment]
Without special configuration it's `M-TAB`, not `TAB` (but this doesn't work in many window managers). If this doesn't work - I assume something related to completion got changed in Emacs 28.

**Comment by manuel-uberti** [comment]
`M-TAB` switch windows here on GNOME, you're right.

**Comment by manuel-uberti** [comment]
With `(setq tab-always-indent 'complete)` everything works. Sorry for the noise.

**Comment by bbatsov** [comment]
No worries. I've updated the docs with more details in case someone else gets confused by this.
