### ISSUE TITLE
Jump to Java bytecode

### ISSUE THREAD

**Issue by andreyorst** [clojure-emacs/cider#3007]
Hi! I would like to know if it is possible to jump to Java bytecode, not Java sources?

I'm currently using [jdecomp](https://github.com/xiongtx/jdecomp) Emacs package which is able to decompile Java bytecode via different decompilers, like CFR, Fernflower, and Procyon. Since a lot of libraries are downloaded without sources, but the bytecode is always there it would be nice if we were able to jump at least to it, similarly how Intellij Idea does. Emacs can easilly open `.jar` archives and view class files, so this seems like a good alternative when library sources are not available.

**Describe the solution you'd like**

CIDER resolves the Java method name and finds respecting `.class` file on the class path.
Then CIDER uses something like Fernflower to decompile this `.class` bytecode, and scrolls the buffer to the method definition.

**Describe alternatives you've considered**

CIDER resolves the method name and finds respecting `.class` file on the class path.
Then the file is manually decompiled with external plugin, like jdecomp.

**Additional context**

This is very useful feature in Intellij Idea when working with Java code, and it works even with the Clojure code when working in Cursive. Something like this will bring CIDER more on par feature wise with Intellij Idea

**Comment by bbatsov** [comment]
> Hi! I would like to know if it is possible to jump to Java bytecode, not Java sources?

Currently that's possible, as least not directly. There's a CIDER extension that can do this, though - https://github.com/bsless/clj-decompiler.el/blob/master/clj-decompiler.el, based on @alexander-yakushev's awesome library. I plan to integrate this with CIDER directly down the road, but this requires time I currently don't have.

**Comment by andreyorst** [comment]
> There's a CIDER extension that can do this

I've though that this is a clojure specific decompiler, which will not work with Java libraries. W often have some Java libraries, which don't have sources in them and I had to install this jdecomp plugin specifically to read at least something quickly.

So just to make sure, will clj-decompiler work with Java libraries?

**Comment by bbatsov** [comment]
No idea. It's using `procyon` internally, so I guess it might work. Maybe, however, `jdecomp` is better for your use-cases. 

> Since a lot of libraries are downloaded without sources
You can try https://github.com/threatgrid/clj-experiments/tree/master/resolve-java-sources-and-javadocs for the missing sources. I hear it works very good.

**Comment by andreyorst** [comment]
> You can try https://github.com/threatgrid/clj-experiments/tree/master/resolve-java-sources-and-javadocs for the missing sources.

Yeah, I'm aware of this, but it's not always possible to download library sources. This is why I think that CIDER could resolve method's class and open respecting `.jar` and the `.class` file from it it in Emacs buffer, decompiling it by ittself of with the help of external package. CIDER already can open `.jar` archives to jump to the source, this is very similar feature that jumps to the `.class` if the source is not to be found.
