### ISSUE TITLE
company-mode now supports icons, but CIDER's backend needs adjusting

### ISSUE THREAD

**Issue by andreyorst** [clojure-emacs/cider#3017]
Company mode recently added new feature, which provides icons in the popup. CIDER's backend doesn't yet return icon information back to company, and company displays no icons, when connected to CIDER.

As @dgutov mentioned in the https://github.com/company-mode/company-mode/issues/1102#issuecomment-841711072, CIDER needs some adjusting to make icons work.

**Comment by bbatsov** [comment]
I might look into this in a couple of weeks, but I assume it's pretty simple, so anyone's more than welcome to beat me to it.
