### ISSUE TITLE
CIDER 1.1.1 Can't Handle Errors Without Stack Traces

### ISSUE THREAD

**Issue by timvisher** [clojure-emacs/cider#3022]
## Expected behavior
Be able to eval `(< 1 nil)` and get a reasonable stack trace.

## Actual behavior
CIDER panics with `*Messages*`

```
error in process filter: cider-stacktrace-render-frame: Format specifier doesn’t match argument type
error in process filter: Format specifier doesn’t match argument type
```

and a Stacktrace buffer like

```
1. Unhandled java.lang.NullPointerException
   (No message)
```

## Steps to reproduce the problem

1. Open a clojure file against a JVM _without_ `-XX:-OmitStackTraceInFastThrow` passed.
2. Insert `(< 1 nil)`
3. Whack `M-x cider-eval-last-sexp RET`

This can be fixed by passing `-XX:-OmitStackTraceInFastThrow` to the underlying JVM via the appropriate channel.

For instance:

```
$ cat deps.edn
{:deps
 …
 :aliases {:dev {:jvm-opts ["-XX:-OmitStackTraceInFastThrow"]}}}
```

Followed by `M-0 M-x cider-jack-in RET` and appending`:dev` to the CL like

```
jack-in command: /usr/local/bin/clojure … -M:cider/nrepl:dev`
```

### CIDER version information

```
;; CIDER 1.1.1 (Plovdiv), nREPL 0.8.3
;; Clojure 1.10.3, Java 16.0.1
```

### `clojure` version

```
$ clojure --version
Clojure CLI version 1.10.3.855
```

### Emacs version

```
GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0) of 2021-03-25
```

### Operating system

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G9216
```

**Comment by bbatsov** [comment]
I'm not sure what's the best behaviour in such scenarios, as some stack frames seem to be missing. I recall this problem has been around for ages, but we never decided on the best approach to tackle it. E.g.:

- adding the JVM opt automatically on jack-in
- displaying some more informative message that the stacktrace is looking offf
- try to somehow salvage the situation and display some stacktrace in CIDER

**Comment by timvisher** [comment]
_Personally_ speaking I think adding that option by default seems like a great addition. I can't think of any interactive development situation where I _wouldn't_ want it on, but maybe I'm not thinking of something common?

**Comment by timvisher** [comment]
I don't know nearly enough about the stack trace processing code but is it possible to somehow handle this case in the code that's emitting the

```
error in process filter: cider-stacktrace-render-frame: Format specifier doesn’t match argument type
error in process filter: Format specifier doesn’t match argument type
```
messages?

While I think that it makes sense to add the JVM option by default it's actually those messages that make it _feel_ like a bug in CIDER to me. If I just got a stack trace without a trace but CIDER wasn't raising errors I think that might be slightly better?

**Comment by timvisher** [comment]
Also I guess I should've linked the discussion in #cider :) https://clojurians.slack.com/archives/C0617A8PQ/p1624726767180000

Alex Miller even says that he's personally fixed this issue in Clojure several times.

**Comment by yuhan0** [comment]
I just got around to looking at this - turns out that change was for something else entirely! Sorry for any confusion 😓 

The issue is in `cider-stacktrace-render-frame` - when this 'optimization' happens the argument `frame` is nil and further destructuring it into nils causes the formatting string error.

I agree with the discussion in #3023 that we should just check for this and point users to the relevant troubleshooting page, instead of setting any JVM option by default.

Here's what it might look like:
![image](https://user-images.githubusercontent.com/22216124/131682539-272bc0cc-7655-4c4f-ab1f-67ac44bc97e6.png)

If that's ok I'll submit a PR :) But first the website should be updated to reflect the commit linked above https://github.com/clojure-emacs/cider/commit/2f9bec5131dc3f06caeb9fdb36249f5d299104f4

**Comment by vemv** [comment]
A PR SGTM (FWIW!)

I'd make sure to have at least one CI job run without the sensitive flag (i.e. probably duplicatting the entire matrix would be overkill)

**Comment by vemv** [comment]
My thinking is that creating a test for the `<` just covers one specific bug.

By running a whole CI job with an alt flag set up, we implicitly exercise a _lot_ of code for that flag value.

**Comment by bbatsov** [comment]
My point was mostly that there are almost no integration tests in CIDER that check something against a real nREPL server. The tests typically stub the nREPL replies. That's why I didn't see why we'd run the tests with/without this JVM flag.

**Comment by timvisher** [comment]
This is what OSS is all about. I submit an issue and offer to do the work and then someone else beats me to it and makes my life better.

Thanks everyone! :-D

**Comment by vemv** [comment]
> My point was mostly that there are almost no integration tests in CIDER that check something against a real nREPL server. 

I just realised now that we're not in the cider-nrepl repo 🤦‍♂️ sorry for the noise.

**Comment by vemv** [comment]
I wonder though how things are handled cider-nrepl side. There might be gains to be made especially for clients other than cider.el.
