### ISSUE TITLE
Problem starting cider in clj/cljs `(cl-no-applicable-method map-into ((right-margin 80)) hash-table)`

### ISSUE THREAD

**Issue by shegeley** [clojure-emacs/cider#3029]
Starting cider with `cider-jack-in-clj` or `cider-jack-in-cljs` in clojure (lein) or clojurescript (shadow-cljs) project.
## Expected behavior
Normal startup.
## Actual behavior
`Error (nrepl-connected-hook): Error running hook "cider--connected-handler" because: (cl-no-applicable-method map-into ((right-margin 80)) hash-table)`
## Environment & Version information
- GNU Emacs 27.2 - Doom v3.0.0-alpha (grafted, HEAD -> develop, origin/develop, origin/HEAD 6678f38 2021-08-06 03:50:33 -0400)
- Nix 2.3.14, NixOS 
### Versions information
- CIDER 1.2.0 snapshot
- Nrepl 0.8.3 (from `~/clojure/deps.edn`, right?)
- Clojure 1.10.3
- Openjdk 16 2021-03-16
- Leiningen 2.9.6

**Comment by shegeley** [comment]
Workaround.
Pinned cider to v1.1.1
```
(package! cider :pin "8b3dabe")
```
Works as expected now.

**Comment by bbatsov** [comment]
Hmm, that's weird, as there are just 3 meaningful commits after 1.1.1 and no one else reported a similar problem.

**Comment by gspringtech** [comment]
I have exactly the same problem.
Same versions of CIDER and nREPL. 
Map.el was recently updated - changes to "map-into".
https://github.com/emacs-mirror/emacs/commits/master/lisp/emacs-lisp/map.el

**Comment by gspringtech** [comment]
The changes that cause this problem are in the map-into functions (CIDER calls map-merge which uses map-into).
Prior to this update, the types used for comparison were not quoted:
```
- (cl-defmethod map-into (map (_type (eql hash-table)))
+ (cl-defmethod map-into (map (_type (eql 'hash-table)))
```

I changed all the map-into functions (list, alist, plist, hash-table) back to the unquoted form and restarted emacs - now CIDER loads correctly again. (but I don't know what else might be broken.)

Is this a CIDER issue, or something that needs to go upstream?

**Comment by bbatsov** [comment]
Seems to me like something that has to be fixed in `map.el`, as clearly those changes are breaking some clients. //cc @NicolasPetton

**Comment by j-shilling** [comment]
> I have exactly the same problem.
> Same versions of CIDER and nREPL.
> Map.el was recently updated - changes to "map-into".
> https://github.com/emacs-mirror/emacs/commits/master/lisp/emacs-lisp/map.el

Yeah I was able to work around this by pinning map.el to 896384b.

**Comment by shegeley** [comment]
For some reason after I pinned cider 3 days ago the problem raised again. Might be I don't understand the Doom ecosystem. 
I tried lots of different combinations of doom/upgrade and doom/build. I also tried to pin map.el but had no success.

**Comment by shegeley** [comment]
I was not able to properly pin map package, so I just copypasted the content of "8b3dabe" into it. Works well for now.

**Comment by shegeley** [comment]
Seems like I was unaware of Doom Emacs internal structure. After I grepped all the "cache" files in `~/.emacs.d` and deleted them the map package was able to pin properly on `doom sync`. 
Sorry for leaving too many messages on this issue related to my inability to handle doom internal problem.

**Comment by j-shilling** [comment]
@shegeley At least for me, straight wasn't pulling from the main repository, but from it's own mirror of that repo, so all the commit hashes were different. I looked at the git logs my local `map.el` and pinned the corresponding commit, which for me turned out to be `bb50dba`:

```
(package! map :pin "bb50dba")
```

**Comment by WorldsEndless** [comment]
Reproduced and verified @j-shilling . Thanks for the work-around.

**Comment by filipewvandrade** [comment]
Doom Emacs user here, I just have a fresh installation from doom today and had this issue too.
As the workaround suggested, I added to my `packages.el`
```
(package! map :pin "bb50dba")
```
and run `doom sync -u` to re-sync packages, and the cider jackin started to work

**Comment by MrJazzPotato** [comment]
Just upgraded my emacs to v28.1 and got the error `error in process filter: No applicable method: map-into, (("nrepl.middleware.print/stream?" "1")), (hash-table :test equal)`, I'm on spacemacs, where can I pin the `map.el` package? Is it in `.spacemacs`?
