### ISSUE TITLE
TAB-completion in REPL breaks when there is unclosed brackets in stdout

### ISSUE THREAD

**Issue by yurii-tov** [clojure-emacs/cider#3030]
## Expected behavior
     Pressing the TAB key successfully completes the symbol after the cursor

## Actual behavior
     When you press TAB the cursor moves to the beginning of the line

## Steps to reproduce the problem
      - Run `M-x cider-jack-in`
      - Run command `(println "Oops(")`
      - Type in an expression: `(fre`
      - Hit TAB key
      - Cursor jumps at start of a line, no completion happens

### CIDER version information

```
  ;; CIDER 1.2.0snapshot (package: 20210729.521), nREPL 0.8.3
  ;; Clojure 1.10.1, Java 1.8.0_272
```

### Lein/Boot version

Leiningen 2.9.5 on Java 1.8.0_272 OpenJDK 64-Bit Server VM

### Emacs version

GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu) of 2021-06-05

### Operating system

CentOS Linux release 7.9.2009 (Core)

https://user-images.githubusercontent.com/45265225/128717983-a1943e7d-cf3c-4643-a29a-0f1273836025.mp4

**Comment by vemv** [comment]
Interesting bug, thanks!

It might help to use Paredit in the repl buffer, so that you never see `(input` as you're typing. Have you tried that?

Cheers - V

**Comment by bbatsov** [comment]
I think paredit won't help, as the problem is caused by specific output that confuses the parsing of expressions in the REPL.
