### ISSUE TITLE
Unpredictable behaviour with cider-use-xref, if LSP is also used.

### ISSUE THREAD

**Issue by deejayem** [clojure-emacs/cider#3045]
The new cider-use-xref functionality is great, but the behaviour is unpredictable when lsp is also being used, depending on which order the CIDER and LSP backends appear in `xref-backend-functions`.

## Expected behavior
Probably undefined. I'm not sure anything can be done about this, other than add some documentation about it.

## Actual behavior
Depending on which backend function appears first in `xref-backend-functions`, either CIDER or LSP will be used for xrefs. Sometimes the behaviour between the two is a little different, e.g. with `xref-find-references`, IIRC LSP will pick up references to baz in `(ns foo (:require [bar :refer [baz]]))`, whereas CIDER will not find these, but only the places where baz is called. (No big deal, although the CIDER behaviour is preferable, IMO).

## Steps to reproduce the problem
- Use both CIDER and LSP together, with the default configuration (`cider-use-xref` and `lsp-enable-xref` set to true).
- Add `lsp` to `clojure-mode-hook`, open a Clojure file, and run `cider-jack-in-clj`.
- Use some xref command, e.g. `xref-find-references`, and depending on the order of `xref-backend-functions`, either CIDER or LSP will be used. On two difference machines, I have seen LSP being used one one, and CIDER on the other.

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 1.2.0snapshot (package: 20210902.1412), nREPL 0.9.0-beta1
;; Clojure 1.10.1, Java 1.8.0_302
```

### Lein/Boot version

Lein 2.9.6

### Emacs version

27.2

### Operating system

Latest macOS and latest Ubuntu

**Comment by bbatsov** [comment]
Seems to me that documenting this should be a reasonable solution for most people. Plus, I can't think anything else that we can do here. 😆

**Comment by vemv** [comment]
> Use both CIDER and LSP together, with the default configuration (cider-use-xref and lsp-enable-xref set to true).

This seems inherently prone to conflicts, doesn't it? You're telling two large pieces of functionality to take over the same third-party feature.

I'd suggest only using functions such as `xref-pop-marker-stack` which have no ambiguity (whoever `push`ed last has priority). Other functionality like `xref-find-references` seems more error-prone.

I'd use the CIDER equivalent defun directly instead.

**Comment by deejayem** [comment]
> > Use both CIDER and LSP together, with the default configuration (cider-use-xref and lsp-enable-xref set to true).
> 
> This seems inherently prone to conflicts, doesn't it? You're telling two large pieces of functionality to take over the same third-party feature.

Yes, although that seems to be how xref-backend-functions is designed to work (try each thing in the list in turn, and use the first one that works). It's also the default configuration for CIDER and lsp to integrate with this functionality now. For my part, (for most things) I like to use the functionality from CIDER, and have LSP as a fallback, e.g. if I just want to quickly check something in a project, without starting CIDER.

I think adding this to the lsp-mode-hook makes sure that the CIDER version is always used first:
```
(defun xref-prefer-cider ()
    (when (and lsp-mode
               (eq 'lsp--xref-backend (car xref-backend-functions))
               (memq 'cider--xref-backend xref-backend-functions))
      (remove-hook 'xref-backend-functions 'cider--xref-backend 'local)
      (add-hook 'xref-backend-functions 'cider--xref-backend nil 'local)))
```
Although there might be a better way (and a better hook to use - lsp has lots of them!).

**Comment by bbatsov** [comment]
> This seems inherently prone to conflicts, doesn't it? You're telling two large pieces of functionality to take over the same third-party feature.

I think the assumption is that in most cases the functions would be complementary - if one doesn't return you try the next one and so on. I assume that lsp-mode/eglot are the biggest source of such conflicts given their pretty universal nature. @dgutov Any suggestions for how to force which `xref` backend to be used in such cases? Obviously manually playing with the list of hooks will work, but it seems a bit ugly.

**Comment by dgutov** [comment]
Well, it's a hook.

The APPEND argument has been renamed in recent Emacs versions to DEPTH, with associated functionality. Either the user's snippet can use a specific depth to force one of the backends to go first, or Cider could have a defcustom which chooses said depth. It will default to 0, but the user could set it to -1, for example.

**Comment by deejayem** [comment]
I could be wrong, but my impression from previous experiments (and https://www.gnu.org/software/emacs/manual/html_node/elisp/Setting-Hooks.html) is that add-hook with a depth still doesn't do anything if the function is already there. It only affects what happens when the function hasn't already been added to the hook. I.e. you can use it to control the order when adding, but not to re-order.

For that reason, the defcustom approch seems preferable - once the function is already there it's more work to re-order.

**Comment by dgutov** [comment]
> is that add-hook with a depth still doesn't do anything if the function is already there

Right.

But that still allows you to remove a few lines from `xref-prefer-cider`. Or indeed introduce a defcustom in Cider.

**Comment by deejayem** [comment]
@bbatsov how's this PR? I wouldn't be surprised if the naming and documention can probably be improved.
