### ISSUE TITLE
Can connect to running Lein repl instance, but cider-jack-in hangs.

### ISSUE THREAD

**Issue by cloudbuck3t** [clojure-emacs/cider#3051]
Hi, I'm using CIDER 1.2.0snapshot
I'm not sure how to check the nREPL version but cider-jack-in is apparently trying to use 0.9.0-beta2 of nrepl.

If I open up a terminal window and run `lein repl` in a Clojure project, I can then `M-x connect` to it from within emacs.  Unfortunately cider-jack-in simply hangs.  This started happening after I installed `clojure-lsp` this morning.  Not sure if that's related.

**Comment by bbatsov** [comment]
Start with https://docs.cider.mx/cider/1.1/troubleshooting.html Some logs would be helpful to pinpoint the problem.

**Comment by cloudbuck3t** [comment]
Thanks @bbatsov !  I just started with a clean .emacs.d/init.el file and reinstalled prelude and clojure-lsp and the repl works now.  I think I was missing the package `use-package` 🤷   Thanks a ton for your hard work, really appreciate it.  (=
