### ISSUE TITLE
Error `(void-function parseclj-alist)` after recent update

### ISSUE THREAD

**Issue by rrudakov** [clojure-emacs/cider#3059]
## Expected behavior

No errors are reported after performing `cider-clj-jack-in` command.

## Actual behavior

The following error is thrown:

```emacs-lisp
Debugger entered--Lisp error: (void-function parseclj-alist)
  parseclj-alist(:token-type :lparen :form "(" :pos 1)
  apply(parseclj-alist :token-type :lparen :form "(" :pos 1 nil)
  parseclj-lex-token(:lparen "(" 1)
  parseclj-lex-next()
  parseclj-parser(parseedn-reduce-leaf parseedn-reduce-branch ((:tag-readers)))
  parseedn-read(nil)
  parseedn-read-str("(ws180.http.endpoints.v1-ipready-test \"OK\" ws180.h...")
  cljr--maybe-nses-in-bad-state((dict "ast-statuses" "(ws180.http.endpoints.v1-ipready-test \"OK\" ws180.h..." "id" "10" "session" "6e69aaf1-d5ba-4ad8-99e4-dc5a9297cb14" "status" ("done")))
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_141>((dict "ast-statuses" "(ws180.http.endpoints.v1-ipready-test \"OK\" ws180.h..." "id" "10" "session" "6e69aaf1-d5ba-4ad8-99e4-dc5a9297cb14" "status" ("done")))
  nrepl--dispatch-response((dict "ast-statuses" "(ws180.http.endpoints.v1-ipready-test \"OK\" ws180.h..." "id" "10" "session" "6e69aaf1-d5ba-4ad8-99e4-dc5a9297cb14" "status" ("done")))
  nrepl-client-filter(#<process nrepl-connection> "d12:ast-statuses5824:(ws180.http.endpoints.v1-ipre...")

```

### CIDER version information

```
;; CIDER 1.2.0snapshot (package: 20210929.1032), nREPL 0.9.0-beta2
;; Clojure 1.10.3, Java 16.0.2
```

### Lein/Boot version

Leiningen 2.9.7 on Java 16.0.2 OpenJDK 64-Bit Server VM

### Emacs version

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-09-22

### Operating system

Linux 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64 GNU/Linux

**Comment by rrudakov** [comment]
Not directly related to CIDER but the same error is thrown when I'm trying to execute `cljr-add-missing-libspec` command. Also auto-import after entering `/` doesn't work anymore.

```emacs-lisp
Debugger entered--Lisp error: (void-function parseclj-alist)
  parseclj-alist(:token-type :lparen :form "(" :pos 1)
  apply(parseclj-alist :token-type :lparen :form "(" :pos 1 nil)
  parseclj-lex-token(:lparen "(" 1)
  parseclj-lex-next()
  parseclj-parser(parseedn-reduce-leaf parseedn-reduce-branch ((:tag-readers)))
  parseedn-read(nil)
  parseedn-read-str("({:name sqly.core, :type :ns})")
  cljr--call-middleware-to-resolve-missing("sql/")
  cljr-add-missing-libspec()
  funcall-interactively(cljr-add-missing-libspec)
  command-execute(cljr-add-missing-libspec)
```

**Comment by plexus** [comment]
Thanks for the report, this has been fixed in parseclj, but it seems you are not getting the latest version. I opened #3060 to make sure we get the right version. Meanwhile you can try to get your package manager to install the current version (1.0.2) of parseclj/parseedn.

**Comment by plexus** [comment]
Looking into it, there's actually still an issue due to parseedn only requiring part of parseclj.

**Comment by rrudakov** [comment]
@plexus thanks for looking into it, just for the information, I have the following versions installed:
```
  parseclj                       20210928.730   dependency            Clojure/EDN parser
  parseedn                       20210927.706   dependency            Clojure/EDN parser
```
and no updates are available.

**Comment by plexus** [comment]
Keep an eye on the build for #3059, that should tell us if this is fixed now or not.

**Comment by rrudakov** [comment]
Tests failed with the same error: `error: (void-function parseclj-alist)`

**Comment by rrudakov** [comment]
I've just updated `parseclj` and `parseedn` packages and the error is gone. So I think this issue is solved?
