### ISSUE TITLE
Consider changing dead repl prompt text

### ISSUE THREAD

**Issue by lread** [clojure-emacs/cider#3076]
**Thanks!**
First, thank you for cider. It is magnificently useful and I so appreciate all the hard work!

**Is your feature request related to a problem? Please describe.**
For a while I have been mystified by the `dead REPL` prompt, an example:
```
A dead REPL *cider-repl borkdude/api-diff:localhost:60172(clj)* exists.  Reuse? (y or n)
```

I did not understand what it was asking me to reuse.
At one point I thought it might be a process.  I know, so naive!
Sometimes I answered y, other times n.
When I finally took the time to look it up, I learned I am being asked if I want to reuse a buffer. A buffer! Oh!

I can't imagine I'm alone in my:
1. laziness in not looking up what this prompt means
2. being confused by this

**Describe the solution you'd like**
Include the word `buffer` after `Reuse`:
```
A dead REPL *cider-repl borkdude/api-diff:localhost:60172(clj)* exists.  Reuse buffer? (y or n)
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by vemv** [comment]
Relatedly, could we reduce choice via a defcustom?

Generally users expect things to 'just work' aka Don't Make Me Think :)
