### ISSUE TITLE
Emacs with Cider on Windows 11: The `:extra-paths` entry in `deps.edn` seems to be ignored

### ISSUE THREAD

**Issue by cmiles74** [clojure-emacs/cider#3079]
## Expected behavior

My thinking is that I could open the `deps.edn` file in the root of the project with Emacs, invoked the `jack-in` command and then be able to `require` namespaces from the source code listed in the `:extra-paths` key of that `deps.edn` file. 

```clojure
{:aliases
 {:cider/nrepl
  {:extra-paths ["development/src"]
   :extra-deps {org.clojure/clojure {:mvn/version "1.10.3"}
                org.clojure/tools.deps.alpha {:mvn/version "0.12.1003"}}}}}
```

## Actual behavior

This doesn't seem to be the case.

```
user> (require '[sample :as s])
Execution error (FileNotFoundException) at user/eval16285 (REPL:43).
Could not locate sample__init.class, sample.clj or sample.cljc on classpath.
```

If I start a REPL from the `clojure` tool, it does appear to work as expected.

```shell
C:\Users\twitc\source\repos\cider-clj-tools> clojure -M:cider/nrepl
Clojure 1.10.3
user=> (require '[sample :as s])
nil
user=> (sample/hello "Bob")
Hello there, Bob
nil
user=>
```

I freely admit that there's a lot going on here and there could be something simple that I'm doing wrong. This is the first Clojure project I've worked on that is using the Clojure CLI and Deps tools; I've spent time reading the documentation but I definitely could be missing something.

If it's at all helpful, this is the clear text command that Cider is using to start the REPL.

```
clojure -Sdeps ’{:deps {nrepl/nrepl {:mvn/version ""0.9.0-beta3""} com.billpiel/sayid {:mvn/version ""0.1.0""} refactor-nrepl/refactor-nrepl {:mvn/version ""3.0.0-alpha13""} cider/cider-nrepl {:mvn/version ""0.27.2""}} :aliases {:cider/nrepl {:main-opts [""-m"" ""nrepl.cmdline"" ""--middleware"" ""[com.billpiel.sayid.nrepl-middleware/wrap-sayid,refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]""]}}}’ -M:cider/nrepl
```

## Steps to reproduce the problem

A sample project is available at...
* https://github.com/cmiles74/cider-clj-tools

### CIDER version information

```
;; Connected to nREPL server - nrepl://localhost:63844
;; CIDER 1.2.0snapshot (package: 20211013.2024), nREPL 0.9.0-beta3
;; Clojure 1.10.3, Java 11.0.12
```

### Emacs version

```
GNU Emacs 28.0.50 (build 1, x86_64-w64-mingw32)
```

### Operating system

Windows 11

**Comment by dpsutton** [comment]
I think there's an obvious issue that explains all of this.

Your alias is called `:cider/nrepl` with extra paths. When CIDER jacks in, it adds its own dependencies under an alias called `:cider/nrepl`. Only one can exist and its the one that is from CIDER. If you rename your alias it should work. Can you let us know if this works?

In the meantime, perhaps we could rename this injected profile to something less likely to be shadowed? `:cider__nrepl/injected` or something?
