### ISSUE TITLE
CIDER SSH tunnel to use a random unused port if supposed port is already in use

### ISSUE THREAD

**Issue by anonimitoraf** [clojure-emacs/cider#3085]
**Is your feature request related to a problem? Please describe.**
I work with multiple remote machines. These remote machines run nREPL on the same port. I'd like to be able to maintain connections to these machines at the same time.

I've tried `nrepl-force-ssh-for-remote-hosts` (and also tried `nrepl-use-ssh-fallback-for-remote-hosts`) but I've noticed that if the port is already in use (port-forwarding one of the remote machines running nREPL), `cider-connect` continues anyways.

My workaround at the moment is defining different port forwards in my SSH config then connect CIDER to localhost. Drawback of this is that I have to remember which localhost ports map to which remote machines.

**Describe the solution you'd like**
I would like CIDER to use an unused localhost port if a port is already in use.

**Comment by vemv** [comment]
PR welcome, we can re-open if someone volunteers
