### ISSUE TITLE
cider-macroexpand-1 doesn't behave as clojure.core/macroexpand-1

### ISSUE THREAD

**Issue by diegovdc** [clojure-emacs/cider#3095]
## Expected behavior
A badly written anaphoric macro that shouldn't compile.
```clj
(defmacro on-event
  "Simply passes the `:keys` to the function"
  [f-body]
  `(fn [{{:keys [index dur dur-ms] :as data} :data}]
     (let [at-index #(wrap-at index %)] ~f-body)))
     
(on-event (at-index [1 2 3]))
```
Calling `(on-event (at-index [1 2 3]))` will throw an error.

## Actual behavior
Macro gets compiled:
```clj
(fn [{{:as data, :keys [index dur dur-ms]} :data}]
  (let [at-index #(wrap-at index %)] (at-index [1 2 3])))
```

The output of `clojure.core/macroexpand-1` is different:
```clj
(clojure.core/fn
 [{{:as my-ns/data,
    :keys
    [my-ns/index
     my-ns/dur
     my-ns/dur-ms]}
   :data}]
 (clojure.core/let
  [my-ns/at-index
   (fn*
    [p1__36684__36685__auto__]
    (my-ns/wrap-at
     my-ns/index
     p1__36684__36685__auto__))]
  (at-index [1 2 3])))
```

## Steps to reproduce the problem
Run `cider-macroexpand-1` on the next form:
```clj
(on-event (at-index [1 2 3]))
```
vs 
```clj
(macroexpand-1 '(on-event (at-index [1 2 3])))
```
## Environment & Version information
Linux Mint 20, Emacs 26
### CIDER version information
```
;; CIDER 1.2.0snapshot (package: 20210524.832), nREPL 0.8.3
;; Clojure 1.10.1, Java 11.0.11
```
### Lein/Boot version
Leiningen 2.9.1 on Java 11.0.11 OpenJDK 64-Bit Server VM
### Emacs version
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian

### Operating system
Linux Mint 20

**Comment by vemv** [comment]
```diff
-(macroexpand-1 (on-event (at-index [1 2 3])))
+(macroexpand-1 '(on-event (at-index [1 2 3])))
```

One should generally macroexpand quoted forms, perhaps that explains things?

**Comment by diegovdc** [comment]
Oh you are right @vemv.

Anyways, the expansion is not the same in both cases.

I am going to update the issue with the actual `macroexpand-1` output.

**Comment by vemv** [comment]
We can revisit this issue at some point later - right now it doesn't seem to represent a huge practical problem.

cider-nrepl's macroexpand (https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/macroexpand.clj) does not simply delegate to clojure.core's macroexpand so small quirks are to be expected.
