### ISSUE TITLE
cider-print-fn is not respected/used

### ISSUE THREAD

**Issue by RobertARandolph** [clojure-emacs/cider#3103]
## Preface

I may be misunderstanding the note on this page: https://docs.cider.mx/cider/1.1/usage/pretty_printing.html

Based on the note, it is unclear to me if this page is up to date for Cider 0.21, or if this page is obsolete as of 0.21. A quick glance at Cider's code seems to indicate that this page is obsolete and that I should not be using `cider-print-fn`.

If this is obsolete, is there an alternative emacs-based solution?

## Expected behavior

`(setq cider-print-fn "pprint")` results in Cider eval-pprint commands to print results using `clojure.pprint/pprint`.

Any value of `cider-print-fn` is ignored.

## Actual behavior

The value of `nrepl.middleware.print/*print-fn*` is always used.

## Steps to reproduce the problem

`(setq cider-print-fn "pprint")` in emacs.

Start a clojure REPL.

Use `cider-pprint-eval-defun-to-comment` (or any other `pprint-eval` command).

The printer bound to `nrepl.middleware.print/*print-fn*` will be used regardless of what `cider-print-fn` is set to.

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 1.2.0snapshot (package: 20211218.1157), nREPL 0.9.0
;; Clojure 1.10.0, Java 1.8.0_192
```

### Emacs version

28.0.90

### Operating system

macOS 12.1

**Comment by bbatsov** [comment]
> Based on the note, it is unclear to me if this page is up to date for Cider 0.21, or if this page is obsolete as of 0.21. A quick glance at Cider's code seems to indicate that this page is obsolete and that I should not be using cider-print-fn.

It's the other way around - that's the "modern" way of doing pretty-printing in CIDER. :-) Notice that you can't use a random function here, all the defaults are defined in `cider-nrepl` and you need to define something that has the same interface. See https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/pprint.clj

**Comment by bbatsov** [comment]
Perhaps it has higher precedence? I don't remember. I do see that you get `pr` if you provide something that fails to resolve https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/middleware/print.clj#L223

**Comment by RobertARandolph** [comment]
Aha! https://github.com/clojure-emacs/cider/blob/master/cider-client.el#L337

So part of the mystery is that the documented options are symbols, not strings. `(setq cider-print-fn 'fipp)` does work.

Unsure why setting it to a string of a fully qualified function taking an object and writer isn't working for me. That may be a separate issue.
