### ISSUE TITLE
Use lein without bootclasspath optimization

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#3106]
## Context

cider uses enrich-classpath, which uses fipp, which requires `clojure.instant`, which can't be loaded under the bootclasspath approach.

This is reflected here: https://github.com/brandonbloom/fipp/issues/60#issuecomment-470468952

## Proposal

Always run lein prefixed by `LEIN_USE_BOOTCLASSPATH=no`, which I have verified that improves things.

(A full fix for the issues expressed here https://clojurians.slack.com/archives/C0617A8PQ/p1640101913375900 would also have to bump rrb-vector, see https://github.com/brandonbloom/fipp/pull/79)

**Comment by bbatsov** [comment]
What do you need `fipp` for? Perhaps we can just replace it with something else that doesn't have deps?

**Comment by vemv** [comment]
fipp shines in that it's fast and scalable, whereas `pprint`ing huge values can easily cause issues.
