### ISSUE TITLE
wrong-type-argument when jacking into a REPL

### ISSUE THREAD

**Issue by dpassen** [clojure-emacs/cider#3113]
## Expected behavior

cider-jack-in-clj spawns a new REPL

## Actual behavior

REPL starts up but CIDER fails to connect due to a wrong-type-argument

## Steps to reproduce the problem

M-x cider-jack-in-clj or C-c C-x j j 

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### CIDER version information

REPL fails to launch so:
```
Package cider is installed.

     Status: Installed in ‘cider-20211228.1132/’ (unsigned). Delete
    Version: 20211228.1132
     Commit: 42958551cf306bb3579e8669e8c2da922331bdba
```

### Emacs version

GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.6.0, Carbon Version 164 AppKit 2022.6) of 2021-11-16

### Operating system

macOS Monterey 12.1

## Debug Log

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("-snapshot" nil nil)
  cider--version()
  cider-repl--clojure-banner()
  cider-repl--banner()
  cider-repl--insert-banner()
  cider-repl-init(#<buffer *cider-repl apps/bowling-scorer:localhost:53565(clj)*> #f(compiled-function () #<bytecode 0x1ffcb88388d9>))
  cider--connected-handler()
  run-hooks(nrepl-connected-hook)
  nrepl-start-client-process("localhost" 53565 #<process nrepl-server> #f(compiled-function (_) #<bytecode 0x1ffca9e020f5>) nil)
  cider-nrepl-connect((:project-dir "~/apps/bowling-scorer/" :jack-in-cmd "/usr/local/bin/clojure -Sdeps '{:deps {nrepl/nrepl..." :host "localhost" :port 53565 :project-dir "~/apps/bowling-scorer/" :server #<process nrepl-server> :server-command "/usr/local/bin/clojure -Sdeps '{:deps {nrepl/nrepl..." :repl-init-function nil :repl-type clj :session-name nil))
  cider-connect-sibling-clj((:project-dir "~/apps/bowling-scorer/" :jack-in-cmd "/usr/local/bin/clojure -Sdeps '{:deps {nrepl/nrepl...") #<buffer *nrepl-server apps/bowling-scorer:localhost*>)
  #f(compiled-function (server-buffer) #<bytecode 0x1ffcc9cab409>)(#<buffer *nrepl-server apps/bowling-scorer:localhost*>)
  nrepl-server-filter(#<process nrepl-server> "nREPL server started on port 53565 on host localho...")
```

**Comment by dpassen** [comment]
Also happens when starting the REPL outside of CIDER and connecting to it. Debug log:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("-snapshot" nil nil)
  cider--version()
  cider-repl--clojure-banner()
  cider-repl--banner()
  cider-repl--insert-banner()
  cider-repl-init(#<buffer *cider-repl apps/credit-card-processor:localhost:54074(clj)*> #f(compiled-function () #<bytecode 0x1ff261d58831>))
  cider--connected-handler()
  run-hooks(nrepl-connected-hook)
  nrepl-start-client-process("localhost" 54074 nil #f(compiled-function (_) #<bytecode 0x1ff269d22a69>) nil)
  cider-nrepl-connect((:project-dir "~/apps/credit-card-processor/" :host "localhost" :port 54074 :repl-init-function nil :session-name nil :repl-type clj))
  cider-connect-clj(nil)
  funcall-interactively(cider-connect-clj nil)
  #<subr call-interactively>(cider-connect-clj nil nil)
  apply(#<subr call-interactively> cider-connect-clj (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> cider-connect-clj nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (cider-connect-clj nil nil))
  call-interactively(cider-connect-clj nil nil)
  command-execute(cider-connect-clj)
```

**Comment by dpassen** [comment]
The root cause appears to be `cider-version` being nil.

```
cider-version is a variable defined in ‘cider.el’.
Its value is nil

  This variable may be risky if used as a file-local variable.

Documentation:
The current version of CIDER.
```

**Comment by vemv** [comment]
Doesn't ring a bell to me. Maybe something went wrong while cutting a release? @bbatsov 

If this blocks you, you might have luck by temporarily setting it to e.g. `"1.2.0"`

**Comment by dpassen** [comment]
@vemv Setting `cider-version` manually works for both me and a coworker.

**Comment by vemv** [comment]
Cheers. The CI build has been red today so I assume the fix for that will also be the fix for this issue.

**Comment by bbatsov** [comment]
I've made some changes today to remove the `pkg-info` dependency, so I guess that's related to them. I can't imagine how the version can be `nil`, though, as it's extracted from `cider.el` itself. See https://github.com/clojure-emacs/cider/blob/master/cider.el#L97

**Comment by vemv** [comment]
Here's a sample failure https://app.circleci.com/pipelines/github/clojure-emacs/cider/1056/workflows/2e94ef14-3754-4eeb-ab54-e364af6dff0d/jobs/4832

**Comment by bbatsov** [comment]
One guess that I have is that you didn't byte-compile CIDER or you're using native compilation and `eval-when-compile` doesn't work properly there.

**Comment by dpassen** [comment]
I'm on 27.2 - so no native compilation for me. My coworker is using native compilation, however.

**Comment by bbatsov** [comment]
I just removed `eval-when-compile` with the hope that this might fix the problem, although according to the docs it should work properly even if you never byte-compile the code. Let's say I'm puzzled by the problem, but if it comes to this I can just hardcode the version.

**Comment by ikappaki** [comment]
Hi @dpassen,

out of curiosity, what is the `cider-version` generated in your compiled `~/.emacs.d/elpa/cider-20211228.1132/` file? for example I get 1.2.0 as expected:

```emacs-mode
#@31 The current version of CIDER.
(defconst cider-version "1.2.0" (#$ . 1240))
```

Hi @bbatsov,

I've noticed that `cider-version` is defined both as a `defconst` in `cider.el` and `defvar` in `cider-util.el`, could this be causing an undefined behaviour?

Thanks

**Comment by dpassen** [comment]
```
#@31 The current version of CIDER.
(defconst cider-version nil (#$ . 1240))
```

**Comment by ikappaki** [comment]
> ```
> #@31 The current version of CIDER.�
> (defconst cider-version nil (#$ . 1240))
> ```

Thanks, how did you upgrade to the latest cider btw? I assume via the standard `package-list` `RET` `U` `RET` `x` path?

What if you recompile that file with `byte-compile-file`, is the version set correctly this time? I can't seem to  reproduce the issue on my mac.

**Comment by dpassen** [comment]
package.el via leaf.el -- recompiling that file worked

**Comment by ikappaki** [comment]
> First, I upgraded via package-list-packages, yes. Then I cleared out my .emacs.d/elpa directory and allowed it to be installed via package.el via leaf.el

Would you mind sharing the `leaf.el` setup you have used to do this? Thanks

**Comment by dpassen** [comment]
https://github.com/dpassen/dotfiles/blob/02011e378cc8530aa959b78fc5f41d35341ef505/emacs.d/init.el#L190-L205

**Comment by dpassen** [comment]
With 20211228.1734:
```
#@31 The current version of CIDER.
(defconst cider-version (byte-code "\302\206	!\207" [load-file-name buffer-file-name lm-version] 2) (#$ . 1240))
```

**Comment by dpassen** [comment]
and
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("-snapshot" nil nil)
  cider--version()
  cider-repl--clojure-banner()
  cider-repl--banner()
  cider-repl--insert-banner()
  cider-repl-init(#<buffer *cider-repl apps/deriving-transducers:localhost:56421(clj)*> #f(compiled-function () #<bytecode 0x1fe4d9c51da9>))
  cider--connected-handler()
  run-hooks(nrepl-connected-hook)
  nrepl-start-client-process("localhost" 56421 #<process nrepl-server> #f(compiled-function (_) #<bytecode 0x1fe4d9d9b791>) nil)
  cider-nrepl-connect((:project-dir "~/apps/deriving-transducers/" :jack-in-cmd "/usr/local/bin/clojure -Sdeps '{:deps {nrepl/nrepl..." :host "localhost" :port 56421 :project-dir "~/apps/deriving-transducers/" :server #<process nrepl-server> :server-command "/usr/local/bin/clojure -Sdeps '{:deps {nrepl/nrepl..." :repl-init-function nil :repl-type clj :session-name nil))
  cider-connect-sibling-clj((:project-dir "~/apps/deriving-transducers/" :jack-in-cmd "/usr/local/bin/clojure -Sdeps '{:deps {nrepl/nrepl...") #<buffer *nrepl-server apps/deriving-transducers:localhost*>)
  #f(compiled-function (server-buffer) #<bytecode 0x1fe4d9d88765>)(#<buffer *nrepl-server apps/deriving-transducers:localhost*>)
  nrepl-server-filter(#<process nrepl-server> "nREPL server started on port 56421 on host localho...")
```

**Comment by bbatsov** [comment]
> I've noticed that cider-version is defined both as a defconst in cider.el and (twice as a) defvar in cider-util.el, could this be causing an undefined behaviour?

This shouldn't be the problem. The `defvar` in `cider-util.el` serves only to suppress a compiler warning (as `cider-util` can't require `cider.el`).

**Comment by ikappaki** [comment]
> https://github.com/dpassen/dotfiles/blob/02011e378cc8530aa959b78fc5f41d35341ef505/emacs.d/init.el#L190-L205

i.e.
```emacs-lisp
(leaf cider
    :ensure t
    :custom ((cider-font-lock-dynamically . nil)
             (cider-mode-line-show-connection . nil)
             (cider-ns-save-files-on-refresh . t)
             (cider-prompt-for-symbol . nil)
             (cider-repl-display-help-banner . nil)
             (cider-repl-pop-to-buffer-on-connect . nil)
             (cider-save-file-on-load . t)
             (cider-use-fringe-indicators . nil))
    :defvar cider-repl-history-file
    :defun (clojure-project-dir . clojure-mode)
    :defer-config (setq cider-repl-history-file
                        (expand-file-name
                         ".cider-repl-history"
                         (clojure-project-dir))))
```

Can't see anything suspicious with the `leaf` setup, the `:ensure t` directive expands to normal [package.el calls](https://github.com/conao3/leaf.el#package-ensure-keywords):

i.e.
```emacs-lisp
(cort-deftest-with-macroexpand leaf/handler-package
  '(
    ;; simple :ensure expandion example
    ((leaf macrostep :ensure t)
     (prog1 'macrostep
       (leaf-handler-package macrostep macrostep nil)))

    ;; `leaf-handler-package' expansion example.
    ;; If `macrostep' is installed, set it as a selected package;
    ;; otherwise try to install it.
    ;; If installation fails, update local cache and retry to install.
    ((leaf-handler-package macrostep macrostep nil)
     (if (package-installed-p 'macrostep)
         (package--update-selected-packages '(macrostep) nil)
       (unless (assoc 'macrostep package-archive-contents)
         (package-refresh-contents))
       (condition-case err
           (package-install 'macrostep)
         (error
          (condition-case err
              (progn
                (package-refresh-contents)
                (package-install 'macrostep))
            (error
             (display-warning 'leaf
                              (format "In `macrostep' block, failed to :package of macrostep.  Error msg: %s"
                                      (error-message-string err)))))))))))
```

thus it doesn't seem to be the root cause of the issue.

Hi @bbatsov, the package.el `package-get-version` appears to employ another element to test for the filename with `byte-compile-current-file`, which seems to be set as desired in the tests I conducted with byte compilation:

```emacs-lisp
(defun package-get-version ()
 ;;; ...
  ;; Hack alert!
  (let ((file
         (or (if (boundp 'byte-compile-current-file) byte-compile-current-file)
             load-file-name
             buffer-file-name)))
  ;;...))
```

perhaps you could try adding that to the list? I believe the latest version without the `eval-when-compile` is broken.

Thanks,

**Comment by bbatsov** [comment]
I've hardcoded the version just now, so it should be OK for the time being. I remain puzzled why something that should be so basic is actually so complex. I'll ask on emacs-devel how is this supposed to be used exactly.

**Comment by lrustand** [comment]
This error is still here in 2024. The version seems to be set correctly here, but the error comes regardless.
