### ISSUE TITLE
cider-clojure-cli-aliases enhancements - all execution opts and remove duplicate colon

### ISSUE THREAD

**Issue by practicalli-john** [clojure-emacs/cider#3125]
**Is your feature request related to a problem? Please describe.**

Currently CIDER will [remove the `-A` and `-M` execution option flags from `cider-clojure-cli-aliases`](https://github.com/clojure-emacs/cider/blob/master/cider.el#L633-L637), typically defined in a `.dir-locals.el` file for a Clojure CLI project.

Clojure CLI has several executions options: `-A` `-M` `-P` `-T` and `-X`

It seems prudent to remove all of these flags, otherwise they are included as part of the final command.  In some basic tests, this doesnt seem to cause an actual issue, although look very strange in the logs

When an execution option flag is not included in `cider-clojure-cli-aliases, an extra `:` appears in the resulting jack-in command line.  Although this does not affect the results of the command, it is confusing in the logs

**Describe the solution you'd like**

To remove the other execution options, I believe the regex would be as follows ([cider.el line 636](https://github.com/clojure-emacs/cider/blob/master/cider.el#L633-L637))
```lisp
(if cider-clojure-cli-aliases
     ;; remove exec-opts flags -A -M -P -T or -X from cider-clojure-cli-aliases to be concatenated
    ;; with cider/nrepl to ensure cider/nrepl comes last
    (format ":%s" (replace-regexp-in-string "^-\\(A\\\|M\\|P\\|T\\|X\\):" "" cider-clojure-cli-aliases))
    "")
```

To resolve the dual colon the format command initial argument should change from `":%s"` to `"%s"` and the colon removed from the end of the regex pattern.  So both updates would look as follows

```lisp
(if cider-clojure-cli-aliases
    ;; remove exec-opts flags -A -M -P -T or -X from jack-in-aliases to be concatenated
    ;; with cider/nrepl to ensure cider/nrepl comes last
    (format "%s" (replace-regexp-in-string "^-\\(A\\\|M\\|P\\|T\\|X\\)" "" cider-clojure-cli-aliases))
    "")
```

It also seems prudent to update the defcustom `cider-clojure-cli-aliases` description ([cider.el line 158](https://github.com/clojure-emacs/cider/blob/master/cider.el#L158-L166))
```lisp
(defcustom cider-clojure-cli-aliases
  nil
  "A list of aliases to include when using the clojure cli.
Alias names should be of the form `:foo:bar`.
Leading \"-A\" \"-M\" \"-P\" \"-T\" or \"-X\" will be stripped as
these are concatenated into the \"-M[your-deps]:cider/nrepl\" form."
  :type 'string
  :safe #'stringp
  :package-version '(cider . "1.1"))
```

If these sound sensible, I can raise a PR.

**Describe alternatives you've considered**

I am happy to discus any alternatives, although I cant think of anything

**Additional context**

I have tested this change by updating the code in the cider.el file from the package downloaded by Emacs.  It has been tested with a `.dir-locals.el` file using the different exec-opts flags in `cider-clojure-cli-aliases` and with multiple aliases without a flag.  All tests gave expected results.

**Comment by dpsutton** [comment]
These both sound sensible to me

**Comment by puredanger** [comment]
-P does not take aliases, so you'll never see -P:foo

**Comment by puredanger** [comment]
Maybe that's covered by the second change.

Are there supposed to be 3 \'s after the A in the regex (vs 2 \'s after the others)?

**Comment by practicalli-john** [comment]
I agree that its very unlikely that `-P` would be used, but I though it may we worth including if it was added it by mistake.  However, I think that's very unlikely scenario though, so I'll remove -P from the regex.

Good catch about the triple slash, removing it still works in my tests.

I'll create a PR from this feedback, thanks.
