### ISSUE TITLE
Fail to jack in when cider.enrich-classpath is enabled for large projects

### ISSUE THREAD

**Issue by huahaiy** [clojure-emacs/cider#3136]
> ⚠️ Preferred workaround: https://github.com/clojure-emacs/cider/issues/3136#issuecomment-1016104099

> Less preferred workaround: https://github.com/clojure-emacs/cider/issues/3136#issuecomment-1016076568

---

## Expected behavior

Able to jack in when using lein.

## Actual behavior

Jack in fails with error:

`java.io.IOException: Cannot run program "java" (in directory "/project-directory"): error=7, Argument list too long`

## Steps to reproduce the problem

Construct a project.clj file with huge number of dependencies, as it is the case in our product (sorry, I cannot supply our project.clj), run the same command line as what cider runs when jacking-in:

`lein update-in :dependencies conj \[nrepl/nrepl\ \"0.9.0\"\] -- update-in :plugins conj \[refactor-nrepl/refactor-nrepl\ \"3.2.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.28.0\"\] -- update-in :plugins conj \[mx.cider/enrich-classpath\ \"1.6.2\"\] -- update-in :middleware conj cider.enrich-classpath/middleware -- repl :headless :host localhost`

The error above is produced. 

Removing `-- update-in :plugins conj \[mx.cider/enrich-classpath\ \"1.6.2\"\] -- update-in :middleware conj cider.enrich-classpath/middleware`, REPL starts correctly without error.

### CIDER version information

;; CIDER 1.3.0-snapshot (package: 20220113.610), nREPL 0.9.0
;; Clojure 1.10.3, Java 17.0.1

### Lein/Boot version

Leiningen 2.9.5 on Java 17.0.1 OpenJDK 64-Bit Server VM

### Emacs version

GNU Emacs 27.1

### Operating system

Ubuntu 20.04.3 LTS

**Comment by vemv** [comment]
Thanks much for the report! Very appreciated.

Probably that's something that can be tweaked at OS level, will investigate.

In the meantime you can disable Enrich: https://github.com/clojure-emacs/cider/blob/8bb67174ffa0cd7ae01f544926b4ed5a17965d76/cider.el#L431

**Comment by vemv** [comment]
Could you run `getconf ARG_MAX` or such a command in your machine to find out the maximum number of args a given command it accepts?

Is the command **itself** what is failing...?

i.e. if you insert:

```
lein update-in :dependencies conj \[nrepl/nrepl\ \"0.9.0\"\] -- update-in :plugins conj \[refactor-nrepl/refactor-nrepl\ \"3.2.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.28.0\"\] -- update-in :plugins conj \[mx.cider/enrich-classpath\ \"1.6.2\"\] -- update-in :middleware conj cider.enrich-classpath/middleware -- repl :headless :host localhost
```

in a terminal, will it fail no matter what, in any project, right at the OS level?

**Comment by huahaiy** [comment]
Correct. It fails at OS level, i.e. when run the command in OS shell.
```
$ getconf ARG_MAX
2097152
```

**Comment by vemv** [comment]
Thanks!

The command itself doesn't look that long. It doesn't spawn internally any new process either.

So it's a pretty unfortunate situation that was never observed in macOS or Ubuntu builds or in various real-world usages.

Could you check if playing with `ulimit` fixes the issue? See https://unix.stackexchange.com/a/45584

This debugging would be very much appreciated - there's a lot of work behind enrich-classpath.

**Comment by huahaiy** [comment]
The error is reporting that the argument is too long for `java`, so my guess is that it is the argument that lein eventually constructs to pass to java is too long. This of course is the result of the enrichness this plugin does?

**Comment by vemv** [comment]
Got it, yes, that's a useful insight.

For context, I've used enrich-classpath in a professional project which 100K+ LOC.

enrich-classpath's CI also exercises its plugin over a variety of real-world projects (each submodule here: https://github.com/clojure-emacs/enrich-classpath/tree/8751d73f809d6207c34b1c1c3e78082daff626ac/integration-testing).

So generally the approach is OK, but yes, it's not impossible that a given computed classpath can be really long for certain projects.

Could you check if `ulimit` will make a difference? Apparently `ulimit` will immediately change the output of `getconf ARG_MAX` so that's a way of checking whether it's headed on the right direction to begin with.

**Comment by huahaiy** [comment]
Getting a larger ARG_MAX, e.g. 2097152000, by setting a larger ulimit, does not seem to work. The same error occurs. Since this is a java.io.Exception, I think the limit is in JVM.

**Comment by vemv** [comment]
Thanks for the attempt!

I don't think the limit is in the JVM, else it would have been caught in CI.

The JVM tries to be OS agnostic in general.

A plausible explanation is that custom ulimit settings won't be inherited from JVM to JVM.

(Note that Lein works by using a JVM to calculate how the final JVM will be created)

Will think of what can be done.

**Comment by huahaiy** [comment]
CI probably does not have a large enough project to trigger this error. I can live with having this plugin disabled for now. Thank you for responding promptly.

**Comment by vemv** [comment]
Perhaps as a workaround, setting this in your project.clj or ~/profiles.clj will work:

```clj
;; (:enrich-classpath is a top-level key)
:enrich-classpath {:classifiers #{"sources"}}
```

What this accomplishes is only adding sources, but not javadocs. This effectively halves the classpath that enrich-classpath will add.

Would you be so kind to give it a spin? From a terminal it should suffice, as before.

**Comment by huahaiy** [comment]
Yes, this workaround works. Thanks!

**Comment by vemv** [comment]
That's very good to know. Might add the workaround if I don't come up with something better.

In case you hadn't heard much of the project before, it's described here: https://metaredux.com/posts/2021/12/22/cider-1-2-nice.html

I see you're using `Ubuntu 20.04.3 LTS`. So as the blog post says, you'll want a command similar to `sudo apt install openjdk-11-source openjdk-11-doc` (but for jdk17) to be able to also navigate to JDK sources.

I hope you can give good use to CIDER's newer Java offerings - they tend to particularly be useful in large projects like yours!

**Comment by huahaiy** [comment]
Sounds cool. I will certainly try them out. Thank you very much for all the wonderful work that you guys do for cider.

**Comment by vemv** [comment]
I gave the topic some thought and probably there's not much we can do without altering Leiningen itself, which is a possibility, but probably creating a PR and then expecting users to upgrade Leiningen isn't exactly ideal.

As mentioned I think the issue is that that ulimit cannot be set via a simple `ulimit -s <2x the current size>`  because that won't persist when Lein does its thing across 2 JVMs.

So maybe you could try if setting a permanently higher value works? https://linuxhint.com/permanently_set_ulimit_value/

I think this should be reproducible in CI by setting an artificially low ulimit. Either way if you can generously try out that sometime in the week, that would be again much appreciated 🍻.

Either way, happy we've documented a couple workarounds so far.

**Comment by vemv** [comment]
Hi there, enrich-classpath 1.9.0 fixes this, via its [:shorten](https://github.com/clojure-emacs/enrich-classpath/tree/v1.9.0#shorten) option.

Here's how to try it out:

```diff
-:enrich-classpath {:classifiers #{"sources"}}
+:enrich-classpath {:shorten true}
```

It is important to remove the :classifiers config since that was a workaround - if it's kept it will work either way.

Also, enrich-classpath has to be 1.9.0. Today's CIDER master snapshot includes it (it can MELPA up to a couple hours to pick it up).

If you can try it out, that would be greatly appreciated since that extra confirmation would increase my confidence for changing the `:shorten` default to `true`.

Cheers - V

**Comment by huahaiy** [comment]
Unfortunately, this does not work. 
```
/usr/bin/lein update-in :dependencies conj \[nrepl/nrepl\ \"0.9.0\"\] -- update-in :dependencies conj \[refactor-nrepl/refactor-nrepl\ \"3.3.2\"\] -- up\
> date-in :plugins conj \[com.billpiel/sayid\ \"0.1.0\"\] -- update-in :plugins conj \[refactor-nrepl/refactor-nrepl\ \"3.3.2\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.\
> 28.1\"\] -- update-in :plugins conj \[mx.cider/enrich-classpath\ \"1.9.0\"\] -- update-in :middleware conj cider.enrich-classpath/middleware -- repl :headless :host localhost
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Compiling ClojureScript...
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at clojure.lang.RT.classForName(RT.java:2212)
	at clojure.lang.RT.classForName(RT.java:2221)
	at clojure.lang.RT.loadClassForName(RT.java:2240)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.lang.RT.<clinit>(RT.java:338)
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.valueOf(Integer.java:999)
	at clojure.core$fn__8516.invokeStatic(core.clj:7067)
	at clojure.core$fn__8516.invoke(core.clj:7057)
	at clojure.core__init.load(Unknown Source)
	at clojure.core__init.<clinit>(Unknown Source)
	... 9 more
Subprocess failed (exit code: 1)
```

**Comment by vemv** [comment]
Thanks for trying it out!

Are you sure it has to do? I've never seen that. Maybe it's missing a port number for the repl? Or perhaps it has do do with the `Compiling ClojureScript...` bit? (which enrich-classpath is unconcerned with)

Does the error disappear/change if you remove/downgrade enrich-classpath from that command?

**Comment by vemv** [comment]
Additional note, this is the code that is failing https://github.com/clojure/clojure/blob/clojure-1.10.3/src/clj/clojure/core.clj#L7057-L7074

I tried `lein with-profile -user update-in :dependencies conj \[nrepl/nrepl\ \"0.9.0\"\] -- update-in :dependencies conj \[refactor-nrepl/refactor-nrepl\ \"3.3.2\"\] -- update-in :plugins conj \[com.billpiel/sayid\ \"0.1.0\"\] -- update-in :plugins conj \[refactor-nrepl/refactor-nrepl\ \"3.3.2\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.28.1\"\] -- update-in :plugins conj \[mx.cider/enrich-classpath\ \"1.9.0\"\] -- update-in :middleware conj cider.enrich-classpath/middleware -- repl :headless :host localhost` in an empty project with a variety of `clojure` versions and it always works

**Comment by huahaiy** [comment]
The above error appears as soon as  `:shorten true` is added and `:classifiers #{}` is removed. Everything else is the same.

**Comment by vemv** [comment]
Thanks!

This sums it up well:

> The above error appears as soon as :shorten true is added and :classifiers #{} is removed. Everything else is the same.

However I can't repro it, neither in daily usage or over Enrich's comprehensive test matrix which exercises a variety of large/real-world projects.

If you could generously try to bisect the issue, that would be greatly appreciated.

I'd do it like this:

* remove other Lein plugins, one by one
  * specifically, whatever is causing `Compiling ClojureScript...` to be printed?
* remove :dependencies, one by one

Cheers - V

**Comment by vemv** [comment]
Hmmm never mind, can repro after futher expanding our CI suite.

**Comment by vemv** [comment]
I could fix the specific project where I could repro via:

```diff
-  :dependencies [[org.clojure/clojure        "1.7.0"]
+  :dependencies [[org.clojure/clojure        "1.10.3"]
```

Will see what can be improved.
