### ISSUE TITLE
Figwheel is silent since the lastest release

### ISSUE THREAD

**Issue by qleguennec** [clojure-emacs/cider#3137]
## Expected behavior

`cider-jack-in-cljs`, select fighweel-main, then :dev build.
Compilation starts, I expect to see figwheel output like "Compilation started", any errors, etc.

## Actual behavior

I'm not seeing any figwheel output.

## Environment & Version information

- Linux hal 5.13.19-2-MANJARO #  1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux
- emacs version "28.0.60"
- Leiningen 2.9.8 on Java 11.0.13 OpenJDK 64-Bit Server VM
- cider "1.3.0-snapshot"

**Comment by vemv** [comment]
This behavior was observed in https://clojurians.slack.com/archives/C0617A8PQ/p1639644016331700

The tldr was:

> To summarise: `(require 'figwheel.main)` sets up its own logger. If this is done too early, it is set up to print somewhere CIDER doesn't look. Postponing the require to after CIDER is ready fixes all these issues. I would say this is a figwheel issue, not a CIDER-issue.

cc/ @magnars which might be able to contribute newer insights.

**Comment by qleguennec** [comment]
@vemv 

Thank you for your quick answer. Indeed, when I `cider-jack-in-clj` + manually `(require 'figwheel.main)`, the issue disappears.

I have this warning, though:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I am satisfied with this solution.

**Comment by vemv** [comment]
Cheers.

`SLF4J: Defaulting to no-operation (NOP) logger implementation` shows up in every other Clojure app - it goes beyond what CIDER can do! :)

**Comment by magnars** [comment]
Here's my workaround. It's not pretty.

setup-clojure.el
```elisp
;; work around logging issues, figwheel-main vs cider ... fight!
(defun cider-figwheel-workaround--boot-up-cljs ()
  (format "(boot-up-cljs %s)" cider-figwheel-main-default-options))

(cider-register-cljs-repl-type 'boot-up-cljs #'cider-figwheel-workaround--boot-up-cljs)
```

.dir-locals.el
```elisp
((nil
  (cider-default-cljs-repl . boot-up-cljs)))
```

user.clj
```clj
(ns user
  (:require [figwheel.main]
            [figwheel.main.logging :as fml]) ;; pun intended
  (:import [java.util.logging Level ConsoleHandler]))

(defn refresh-figwheel-logger []
  (doto fml/*logger*
    (.removeHandler (first (.getHandlers fml/*logger*)))
    (.addHandler (doto (ConsoleHandler.)
                   (.setFormatter fml/fig-formatter)
                   (.setLevel Level/ALL)))))

(defn cljs [build]
  (refresh-figwheel-logger)
  (figwheel.main/start build))

(defn boot-up-cljs [build]
  (print "Hang on, your Figwheel build" build "will start rolling pretty soon.")
  (flush)
  (Thread/sleep 3000) (print " 3...") (flush)
  (Thread/sleep 2000) (print " 2...") (flush)
  (Thread/sleep 2000) (println " 1...")
  (Thread/sleep 2000)
  (cljs build))
```

**Comment by vemv** [comment]
haha the alias :D

Did you manage to get any feedback from the Figwheel maintainers?

Would love for everyone to have a better default experience.

**Comment by magnars** [comment]
To be honest, I looked at the 98 open issues and 8 open pull requests and decided to work around it and move on with my life. I know a thing or two about open source fatigue, so no criticism to the maintainers of figwheel-main, to be clear.

**Comment by vemv** [comment]
Yeah no issue I guess (that's another `;; pun intended`)

Probably it is reasonable for us to only have limited support for software that isn't so maintained nowadays, so documenting a workaround as we did here seems enough.
