### ISSUE TITLE
CIDER nrepl client can fail the ansi colorisation process in the REPL output

### ISSUE THREAD

**Issue by ikappaki** [clojure-emacs/cider#3153]
## Expected behavior

CIDER should be able to colorize REPL output consisting of valid ansi color control characters (aka [SGR sequences](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters)).

## Actual behavior

CIDER can produce SGR characters verbatim, instead of using the code to colorize rest of the output stream.

## Steps to reproduce the problem

Jack in to an empty deps.edn file, and repeatedly print out the 0 to 9 preceded by the bold intensity SGR seq (i.e `ESC [ 1 m`):
```clojure 
user> (doseq [i (range 500)] (print (format "\u001b[1m%d" (mod i 10))))
```
Somewhere midway in the below, the SGR control sequence is printed verbatim (look for `�[1m9`):

```
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678[1m9012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
```

### CIDER version information

```
;; CIDER 1.2.0 (Nice), nREPL 0.9.0
;; Clojure 1.10.3, Java 17
```

### Emacs version

GNU Emacs 27.2 (build 1, x86_64-w64-mingw32) of 2021-03-26

### Operating system

*Windows 10*

----

The issue is a side effect of the #1813 workaround put in place sometime ago to fix #1794 whereby the cider nrepl client was stop printing output on stray ESC characters, caused by what is now known as [bug#53808](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=53808) and fixed in Emacs 29. The cider fix is flushing out verbatim any residual ansi control seq caught up between nrepl output fragments, and thus when the output is send in chunks by the REPL, it is likely that the control chars will leak out.

PR for Emacs versions < 29 to follow.

Thanks

**Comment by vemv** [comment]
https://github.com/clojure-emacs/cider/pull/3154
