### ISSUE TITLE
Sideeffect checking `cider--xref-backend`

### ISSUE THREAD

**Issue by ericdallo** [clojure-emacs/cider#3170]
When doom runs `(xref-find-backend)` to find current xref backend, cider gives a error: `No linked CIDER sessions`. xref backend functions should not have side-effects like that, this is making doom's code not be able to check for other backends like lsp making users need to jack in repl to use doom's lsp find-definition for example even if not using cider find definition.

## Expected behavior
`(cider--xref-backend)` not throw any side effects like checking if repl is available.

## Actual behavior
`(cider--xref-backend)` checks if repl is available, throwing a error message if not.

## Steps to reproduce the problem

`M-x (cider--xref-backend)` with a repl not enabled in a project.

### CIDER version information

```
;; CIDER 1.3.0 (Ukraine), nREPL 0.9.0
;; Clojure 1.11.0, Java 11.0.12
```

### Emacs version

28.0.91

### Operating system

NixOS

**Comment by vemv** [comment]
Looks like the `ensure` argument is being passed to `cider-current-repl` when calling this:

https://github.com/clojure-emacs/cider/blob/1e27eba570d265bc27317dc2a8f8c98d8b5414e0/cider-find.el#L233-L238

**Comment by ericdallo** [comment]
Yes, here exactly:
https://github.com/clojure-emacs/cider/blob/65a23e54227e3575f5a909dcfbdbbaef70d1438b/cider-client.el#L166

**Comment by vemv** [comment]
PR welcome adding extra arguments and/or wrapped functions here and there, wdyt?

It would be particularly appreciated from that the implicit QAing (I don't use xref for instance, so can't QA this atm)

**Comment by ericdallo** [comment]
Proposal [here](https://github.com/clojure-emacs/cider/pull/3171) @vemv
