### ISSUE TITLE
cider-connection-message-fn is not used

### ISSUE THREAD

**Issue by benjamin-asdf** [clojure-emacs/cider#3172]
cider 1.3
When you start a repl - no connection message. 

user space fix: 
```elisp
(add-hook
 'cider-connected-hook
 (lambda ()
   (message
    (funcall
     cider-connection-message-fn))))
 ```

**Comment by bbatsov** [comment]
Ouch, it seems we broke this years ago and no one has noticed it until now. 🤦‍♂️

**Comment by bbatsov** [comment]
Finally fixed https://github.com/clojure-emacs/cider/commit/814f72f44c6452a32dc5ff2002c6ea07ac866ca3
