### ISSUE TITLE
Enable `read-only-mode` if jumping to a `~/.gitlibs` file

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#3174]
If one jumps to a `~/.gitlibs` file, generally it shouldn't be easily modified - it's not particularly clean and can mean hard-to-debug issues for everyone involved (e.g. users, library authors, tooling authors)

So I'd propose that whenever one jumps to a file located within `~/.gitlibs`, `read-only-mode` was enabled.

Savvy users could always `M-x read-only-mode` to undo that effect, just like they'd do when jumping to a .jar file.

Agreed? @bbatsov

**Comment by bbatsov** [comment]
Seems like going a bit too far IMO. I normally wouldn't expect a tool like CIDER to affect whether I can edit some file or not. I can imagine some people being quite surprised by this behavior.

**Comment by vemv** [comment]
Let's keep it simple then :-)
