### ISSUE TITLE
byte-compilation warnings: custom-declare-variable docstring wider than 80 chars

### ISSUE THREAD

**Issue by ikappaki** [clojure-emacs/cider#3191]
## Expected behavior
No byte-compilation warnings when byte-compiling.

## Actual behavior

A few docstrings warning like the following:

```
            In toplevel form:
             nrepl-client.el:113:1: Warning: custom-declare-variable
                 `nrepl-use-ssh-fallback-for-remote-hosts' docstring wider than 80
                 characters
```

## Steps to reproduce the problem

`eldev -dtT compile`, which also breaks the CI eldev-lint action (which also invokes the byte compiler).

### CIDER version information

latest master

### Emacs version

Emacs 28.1

### Operating system

all

PR to follow.

**Comment by vemv** [comment]
https://github.com/clojure-emacs/cider/pull/3192
