### ISSUE TITLE
Enable cider-ns-browser to show private vars via toggle

### ISSUE THREAD

**Issue by MicahElliott** [clojure-emacs/cider#3200]
**Problem**: It seems good practice to mark your non-public vars as `^:private` (including fns from `defn-`). But then `cider-ns-browser` (a very useful view) doesn't show them. And it's still useful to document private vars.

**Solution**: Enable the private vars to be shown, with their docstrings. Could be a toggle command like `a` (for "show All") in the map (https://github.com/clojure-emacs/cider/blob/master/cider-browse-ns.el#L53).

Should probably still _not_ show vars marked as `^:deprecated`.

**Comment by bbatsov** [comment]
Should be a relatively simple change, so PRs welcome!
