### ISSUE TITLE
Support for debug adapter protocol

### ISSUE THREAD

**Issue by bhougland18** [clojure-emacs/cider#3211]
**Is your feature request related to a problem? Please describe.**  

I would like to use an editor that doesn't have the ability to use Cider (helix editor), but the editor does come with the ability to plug in a repl that uses the debug adapter protocol.

**Describe the solution you'd like**

A way for Cider to communicate using the DAP "standard", similar to a language server protocol.

**Describe alternatives you've considered**

Still exploring my options .

**Additional context**

https://microsoft.github.io/debug-adapter-protocol/

**Comment by bbatsov** [comment]
Unless we find some person interested in working on this, it's quite unlikely it will happen.

**Comment by vemv** [comment]
> Unless we find some person interested in working on this, it's quite unlikely it will happen.

This.

I'll close the issue - it helps us keep things tractable.
