### ISSUE TITLE
xref-find-definitions: Not a Tramp file name

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/cider#3235]
## Expected behavior

`M-.` on a symbol required from another namespace takes me to that name space to check its definition.

## Actual behavior

`M-.` prints the following message:

```
tramp-error: Not a Tramp file name: "<path-to-file>"
```

## Steps to reproduce the problem

- emacs -Q
- `M-x package-initialize`
- jack-in into a Clojure project (I used [this](https://git.sr.ht/~manuel-uberti/boodle)) with `C-c C-x j j`
- visit a namespace (I visited [this one](https://git.sr.ht/~manuel-uberti/boodle/tree/main/item/src/clj/boodle/api/aims.clj))
- hit `M-.` on function you are using which belongs to a different namespace (e.g., I used `aims/select-by-id`)

### CIDER version information

```
;; CIDER 1.5.0-snapshot (package: 1.5.0snapshot.0.20220731.52230), nREPL 0.9.0
;; Clojure 1.11.1, Java 11.0.16
```

### Lein / Clojure CLI version

Clojure CLI version 1.11.1.1105

### Emacs version

GNU Emacs 29.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2022-08-05

### Operating system

Ubuntu 22.04.1 LTS

### JDK distribution

OpenJDK 11.0.16

**Comment by andreyorst** [comment]
I believe I have the same issue but with `cider-connect-clj`:

    tramp-error: Not a Tramp file name: "<path/to/project/root>"

Emacs version is `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2022-08-08` Emacs was checked out at `9b661ff1a8e0fc3fc809a42a187356d6cb5ad2c9`

**Comment by andreyorst** [comment]
This fixed the issue for me:

```patch
From 825156d87b0f11930773ae3d9e735ff6eb81a2ef Mon Sep 17 00:00:00 2001
From: Andrey Listopadov <andreyorst@gmail.com>
Date: Mon, 8 Aug 2022 12:35:48 +0300
Subject: [PATCH] fix CIDER TRAMP integration

---
 cider-common.el | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/cider-common.el b/cider-common.el
index c0e81324..981f4482 100644
--- a/cider-common.el
+++ b/cider-common.el
@@ -263,7 +263,8 @@ otherwise, nil."
   (let* ((buffer (or buffer (current-buffer)))
          (name (replace-regexp-in-string "^file:" "" name))
          (name (concat (cider-tramp-prefix buffer) name)))
-    (if (tramp-handle-file-exists-p name)
+    (if (and (tramp-file-name-p name)
+             (tramp-handle-file-exists-p name))
         name)))
 
 (defun cider--server-filename (name)
-- 
2.36.1
```

**Comment by bbatsov** [comment]
The proposed fix looks good to me.
