### ISSUE TITLE
disable the 'cider-random-words-of-inspiration' feature

### ISSUE THREAD

**Issue by lsh-0** [clojure-emacs/cider#3238]
**Is your feature request related to a problem? Please describe.**

I find the little messages that pop up with `cider-jack-in` aggravating. Definitely not inspiring. 

**Describe the solution you'd like**

This cringeworthy uwu lameness should be opt-in, but I'd settle for opting-out.

**Describe alternatives you've considered**

Tolerance, but it's there every time I need to do work, multiple times a session.

**Additional context**

* https://github.com/clojure-emacs/cider/blob/dd4c555fd88834581306ac54f1aaefe2b0efec99/cider-util.el#L619-L698

**Comment by vemv** [comment]
https://github.com/clojure-emacs/cider/blob/9577dbbdae8cffe023442427b97f963b4447983a/cider.el#L1712-L1718

**Comment by lsh-0** [comment]
I was able to remove the message with this in my `.emacs`:

    (remove-hook 'cider-connected-hook 'cider--maybe-inspire-on-connect)

**Comment by bbatsov** [comment]
That's also documented here https://docs.cider.mx/cider/config/basic_config.html#message-displayed-on-connect

> This cringeworthy uwu lameness should be opt-in, but I'd settle for opting-out.

Oh, well - it's impossible to please everyone, that's why almost everything in CIDER is configurable.

**Comment by lsh-0** [comment]
> That's also documented here https://docs.cider.mx/cider/config/basic_config.html#message-displayed-on-connect

Thank you for the link.

> Oh, well - it's impossible to please everyone

I'm old and grumpy and I suspect these sorts of things bug me more than it would a younger crowd, but I doubt anyone opened a feature request for inspirational messages to be displayed. That isn't to say adding it was right or wrong, popular or unpopular, simply that it's fakeness rankles me multiple times a day and I *genuinely appreciate* being pointed to the option where it can be turned off. Thanks, guys.
