### ISSUE TITLE
with cider-auto-select-error-buffer set to nil when an exception is thrown it still unexpectedly selects the cider-error buffer. 

### ISSUE THREAD

**Issue by drewverlee** [clojure-emacs/cider#3241]
## Expected behavior

With cider-auto-select-error-buffer set to nil when an exception is thrown it **won't** select/focus the cider-error buffer. 

## Actual behavior

With cider-auto-select-error-buffer set to nil when an exception is thrown it does select/focus the cider-error buffer. 

## Steps to reproduce the problem

1. throw an exception from a clojure project. e.g evaling (/ 0 0)

### CIDER version information

CIDER 1.5.0-snapshot (package: 20220810.1514)

repl output:
```
;; Connected to nREPL server - nrepl://localhost:34233
;; CIDER 1.5.0-snapshot (package: 20220810.1514), nREPL 0.9.0
;; Clojure 1.11.1, Java 17.0.4
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
;;  Startup: /usr/local/bin/clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.9.0"} cider/cider-nrepl {:mvn/version "0.28.5"} refactor-nrepl/refactor-nrepl {:mvn/version "3.5.5"}} :aliases {:cider/nrepl {:main-opts ["-m" "nrepl.cmdline" "--middleware" "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"]}}}' -M:cider/nrepl

```

### Clojure CLI version

Clojure CLI version 1.11.1.1155

### Emacs version

emacs version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-08-14

### Operating system

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

### JDK distribution

openjdk version "1.8.0_342"
OpenJDK Runtime Environment (build 1.8.0_342-8u342-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)

(though i believe i get this on java 17 as well)

**Comment by bbatsov** [comment]
I quickly checked the relevant code and I see we haven't changed anything in 6 years there. I'm wondering if this is something to do with your snapshot Emacs version.

**Comment by bbatsov** [comment]
I tried reproducing this locally with Emacs 28 and the option works as expected. Now I'm even more certain that's something to do with Emacs 29.

**Comment by vemv** [comment]
Feel free to re-open if you perceive it again (and you're using CIDER 1.9.0+)

We've reworked errors enough that the issue might have disappeared on its own.
