### ISSUE TITLE
nrepl-extract-ports doesn't return information about provenance of different ports

### ISSUE THREAD

**Issue by pmooser** [clojure-emacs/cider#3244]
A change was made in CIDER so that `nrepl-extract-ports` will look not only for a .nrepl-port file in the root of the project, but also in various other places such as the .shadow-cljs subdirectory. This means that for my workflow of doing a `M-x cider-connect`, if it finds multiple nrepl ports, I can no longer usefully just use TAB to autocomplete and get the proper port number - I have to go read the contents of the port file manually so I can know which port to use. 

It would be great if CIDER could somehow allow me to distinguish between (for example) a shadow-cljs nrepl port and one in the root directory of my project. I think the goal should be to have the user never have to go read those files manually to know the port number.

**Comment by vemv** [comment]
I'm consolidating this one with https://github.com/clojure-emacs/cider/issues/3400
