### ISSUE TITLE
Make `cider-map-repls` configurable

### ISSUE THREAD

**Issue by robert-stuttaford** [clojure-emacs/cider#3248]
**Is your feature request related to a problem? Please describe.**

When I eval forms in a `.cljc`-backed buffer with both a clj and cljs repl connected, the form is evaluated in both. Sometimes I am evaluating forms that only one can use. I'd like to switch to clj-only or cljs-only or back to auto arbitrarily.

**Describe the solution you'd like**

To be able to control `:auto` here when in a `.cljc`-backed buffer. 
https://github.com/clojure-emacs/cider/blob/90561f1ce426a142a89bbe72fb89aab756ffe2b4/cider-eval.el#L1514

**Describe alternatives you've considered**

I can handle this OK with clj-only; just don't connect a cljs repl. But I always want both repls connected when working with cljs, and so I have no solution for this there.

**Comment by vemv** [comment]
This was implemented in https://github.com/clojure-emacs/cider/pull/3387

It's available in CIDER master (Melpa non- `Stable`). Or CIDER 1.8.0 which we plan to release soon!
