### ISSUE TITLE
Reusing dead REPL can sometimes lead to REPL being unusable

### ISSUE THREAD

**Issue by OlegTheCat** [clojure-emacs/cider#3254]
## Expected behavior
Upon loading, the REPL is ready to use

## Actual behavior
REPL becomes broken and is not editable.

## Steps to reproduce the problem
1. Start a REPL.
2. Kill the corresponding nrepl buffer.
3. Now we have a REPL with a message `*** Closed on ... ***` -> in this buffer move a cursor to the begging of the buffer.
4. Start a new REPL and agree to reuse a dead REPL.

### CIDER version information

```
;; CIDER 1.2.0 (Nice), nREPL 0.9.0
;; Clojure 1.10.3, Java 1.8.0_322
```

### Lein / Clojure CLI version

Boot 2.8.3

### Emacs version

GNU Emacs 27.2 (build 1, aarch64-apple-darwin21.3.0, NS appkit-2113.30 Version 12.2 (Build 21D49)) of 2022-02-09

### Operating system

Mac OS 12.6 (M1 processor).

### JDK distribution

openjdk version "1.8.0_322"

**Comment by benjamin-asdf** [comment]
I am killing dead repls instead and never regret it. 

```elisp
(defun mm/cleanup-cider-repls-and-do-not-reuse (&rest _)
  (let ((repls (seq-filter
		(lambda (b)
		  (with-current-buffer
		      b
		    (and (derived-mode-p
			  'cider-repl-mode)
			 (not (process-live-p
			       (get-buffer-process b))))))
		(buffer-list))))
    (mapc #'kill-buffer repls)
    '()))

(advice-add #'cider--choose-reusable-repl-buffer :override #'mm/cleanup-cider-repls-and-do-not-reuse)
```
