### ISSUE TITLE
Bazel support?

### ISSUE THREAD

**Issue by cfclrk** [clojure-emacs/cider#3256]
I work on some clojure projects that are built with [bazel][1]. Currently, cider doesn't have support for bazel projects.

I've started a branch to add some support for bazel projects in cider here: https://github.com/cfclrk/cider/tree/bazel-support. (Currently, it's a small, easy change! Cider is so nice!)

I thought I'd open an issue to:

- see if there's any interest in this feature
- provide a place for anyone to add thoughts or ideas about bazel support in cider

[1]: https://bazel.build/

**Comment by bbatsov** [comment]
Sorry for the slow response! Somehow I totally missed this feature. I'm not familiar with Bazel, but given the simple nature of adding support for it that'd be fine by me. 

PR welcome!

**Comment by vemv** [comment]
PRs certainly welcome!

I'll close the issue because it's been a while. It doesn't particularly help us to keep issues open for things we don't personally plan to work on.
