### ISSUE TITLE
Add argument to cider-jack-in to allow specification of profiles

### ISSUE THREAD

**Issue by hugoduncan** [clojure-emacs/cider#327]
When starting a repl for a project, it is useful to be able to specify profiles that should be used.

I'm not sure how this would interact with the current prefix argument that allows specification of the project.

**Comment by Kejia** [comment]
why cannot i use _cider-jack-in-with-profile_ now?

**Comment by abcdw** [comment]
I'm not sure, but maybe developers thinks that `cider-lein-parametrs` variable is enought for such task.

http://stackoverflow.com/questions/18304271/how-do-i-choose-switch-leiningen-profiles-with-emacs-nrepl

**Comment by bbatsov** [comment]
Exactly.

**Comment by bherrmann7** [comment]
Huh...  I'm running emacs25 with cider from melpa, but it wont let me set cider-lein-parametrs ... variable doesnt exist

**Comment by xiongtx** [comment]
@bherrmann7 The variable is `cider-lein-parameters`. You're missing an `e` in `parametrs`.

**Comment by bherrmann7** [comment]
@xiongtx Thanks, I corrected my comment.   I was trying to set the correct value.   It seems like emails doesnt like you to set variables that arent already in existance.   Perhaps something like make-variable instead of set ?

**Comment by xiongtx** [comment]
Where are you trying to set it? In your init file? You may need to first `(require 'cider)` to load the customizable variable.

**Comment by bherrmann7** [comment]
@xiongtx Thanks again for taking the time.   So, I'm doing exactly this on ubuntu 17.04,
     $  emacs
      I TYPE: M-x
      I TYPE: set-variable<RET>
      Emacs prompts: Set Variable:
      I TYPE: cider-lein-parameters<RET>
      Emacs says: [No Match]

**Comment by xiongtx** [comment]
Try this:

1. Start Emacs
2. In `*scratch*` buffer, type `(require 'cider')`, put cursor after `)`, and `eval-last-sexp` (`C-x C-e`).
3. `set-variable`...`cider-lein-parameters`

**Comment by bherrmann7** [comment]
Thanks @xiongtx That did work!

**Comment by xiongtx** [comment]
Cool, so put `(require 'cider)` in your init file before the part where you set `cider-lein-parameters`. Or [`use-package`](https://github.com/jwiegley/use-package) if you're into that.

**Comment by jiacai2050** [comment]
I add a function to my emacs init script to deal with this issue, see:
- https://github.com/clojure-emacs/cider/issues/744#issuecomment-376742771
