### ISSUE TITLE
Feature req: Add integration tests

### ISSUE THREAD

**Issue by ikappaki** [clojure-emacs/cider#3274]
Change issues do not usually manifest themselves unitl tested at a hight level with they tools they are used with.

There's no integration tests currently available in CIDER so that any changes can be tested at a high level, e.g. jacking in to a clojure cli deps.clj project. They may test localy, but only for certain featuers and certain architecture, thus perhaps introducing bugs in the codebase without use being aware. 

**Describe the solution you'd like**

Introduce a new test command that will invoke the integration tests. The first integration test can be jacking-in to all supported project types. The tests are added to CI.

**Describe alternatives you've considered**

Running integration manually for one architecture with what I think is suffucinent for the problem at hand. This is very subjective and might miss crucial points changed with the commit.

**Additional context**

I'm about to introduce support for `nbb` and would like to ensure that I haven't broken anything else at the jack in level.

I have created a prototype that appears to work:

1. A new test options is introduced, `eldev test --test-type integration` that will invoke the integration tests, everything else works exactly as before.
2. An integration test has been written to jack in to clojure tools project and test basic interaction. 
3. GH worfklow action to install project tools and test across macos, ubuntu and windows.

Happy to take this forward, please let me know of your thoughts.

**Comment by bbatsov** [comment]
I'd welcome work in this direction - the main reason this didn't happen so far was lack of time and plenty of gaps in the test coverage in general. Even at the unit level most of the code base is untested.

**Comment by bbatsov** [comment]
I think we can close this now.
