### ISSUE TITLE
Error in process filter: ClojureScript is not available when jack'ing in to shadow

### ISSUE THREAD

**Issue by ikappaki** [clojure-emacs/cider#3277]
## Expected behavior

Able to jackin to shadow 

## Actual behavior

```
error in process filter: cider-verify-clojurescript-is-present: ClojureScript is not available.  See https://docs.cider.mx/cider/basics/clojurescript for details
```

## Steps to reproduce the problem

1. Install `nodejs`, and `shadow-cljs` with `npm install shadow-cljs -g`
2. Create a an empty `shadow-cljs.edn` and a basic `package.json` in a new directory
_shadow-cljs.edn_
``` clojure
{}
```
_package.json_
```json
{"dependencies":
 {"shadow-cljs": "^2.20.13"}}
```
2. Run `npm install`.
3. Open `shadow-cljs.edn` in Emacs, and `cider-jack-in-cljs`, select `shadow` for ClojureScript REPL type and `node-repl` for the shadow-cljs build.
4. The above error is returned.

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 1.6.0-snapshot (package: 1.6.0-snapshot), nREPL 1.0.0
;; Clojure 1.11.1, Java 17.0.5
```

### Lein / Clojure CLI version

shadow-cljs@2.16.8

### Emacs version

28.1

### Operating system

MS-Windows

### JDK distribution

Oracle

This is most likely due to https://github.com/clojure-emacs/cider/pull/3272 cc @benjamin-asdf

**Comment by bbatsov** [comment]
In the mean time you can set `cider-check-cljs-repl-requirements` to `nil` as a workaround for this.

**Comment by bbatsov** [comment]
I'm also wondering if we should not kill this functionality at some point. It was mostly meant to to prevent people from trying to run something without the necessary deps and provide them with more meaningful error messages, but a few years down the road I'm somewhat doubtful that this really added much value.

**Comment by benjamin-asdf** [comment]
@bbatsov My suggested fix for now is to check both, demunge for nbb and ```(cider-library-present-p "cljs.core")``` for "normal".

**Comment by bbatsov** [comment]
@benjamin-asdf Your proposed fix seems reasonable to me.

**Comment by bbatsov** [comment]
@benjamin-asdf Are you going to submit this as a PR?

**Comment by pieterbreed** [comment]
For what it's worth; the suggested work-around does not work for me.

**Comment by benjamin-asdf** [comment]
@pieterbreed you can check with this version. I am pretty sure that is a fix.

**Comment by pieterbreed** [comment]
@benjamin-asdf indeed, thank you!
