### ISSUE TITLE
Evaluation hangs in cider-jack-in if paredit-mode enabled in repl buffer

### ISSUE THREAD

**Issue by mindbat** [clojure-emacs/cider#3288]
## Expected behavior

After running `cider-jack-in`, and typing `(+ 2 2)` at the prompt, then hitting enter, the expression is evaluated and the buffer displays the return value of `4` before giving a new prompt.

## Actual behavior

Repl buffer hangs indefinitely after hitting enter to evaluate any expression.

## Steps to reproduce the problem

1. Install Emacs 28.2 via homebrew.
2. Install `cider` via MELPA.
3. Install `paredit` via MELPA.
4. Install `lein` and use `lein new` to create a new project.
5. Run `emacs <name of core.clj file in new project>` to open the clj file
6. Run `cider-jack-in`
7. In the repl buffer, run `paredit-mode` to turn on paredit mode.
8. At the repl prompt, enter `(+ 2 2)` and hit enter.

_Note: On my system, if I do not turn on paredit-mode in the repl buffer, everything works normally._

### CIDER version information

```
 ;; Connected to nREPL server - nrepl://localhost:53570
 ;; CIDER 1.5.0 (Strasbourg), nREPL 0.9.0
 ;; Clojure 1.11.1, Java 19.0.1
 ;;     Docs: (doc function-name)
 ;;           (find-doc part-of-name)
 ;;   Source: (source function-name)
 ;;  Javadoc: (javadoc java-object-or-class)
```

### Lein / Clojure CLI version

`Leiningen 2.9.10 on Java 19.0.1 OpenJDK 64-Bit Server VM`

### Emacs version

28.2

### Operating system

MacOS 12.6.1

### JDK distribution

```
java version "19.0.1" 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)
```

**Comment by rrudakov** [comment]
The new version of paredit map RET key to `paredit-RET` command. You can either unset this key in `paredit-mode-map` or use `C-RET` in REPL buffer.

**Comment by mindbat** [comment]
> The new version of paredit map RET key to paredit-RET command

@rrudakov Ah, that explains why I've not had this issue before 😊 

You're right, rebinding the `RET` key via `(define-key paredit-mode-map (kbd "RET") nil)` in my `init.el` file fixed it 👍

**Comment by bbatsov** [comment]
I've noticed a few people running in this problem on Slack, so I'm wondering if we should mention it somewhere in the docs. Not that anyone will read them, but still... 😆

**Comment by mindbat** [comment]
>  I'm wondering if we should mention it somewhere in the docs. 

@bbatsov +1 😀 

Happy to raise a PR for that. Looking over the docs, it seems like the `Commonly Encountered Problems` section of the [troubleshooting doc](https://github.com/clojure-emacs/cider/blob/master/doc/modules/ROOT/pages/troubleshooting.adoc) might be a good spot to mention this?

**Comment by bbatsov** [comment]
@mindbat Yeah, that's a good place for this. Also this - https://docs.cider.mx/cider/additional_packages.html#paredit
