### ISSUE TITLE
Remove cider-*-global-options (part of the jack-in command)

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#3295]
We've got a ton of those configuration options (`e.g. `cider-lein-, but I think we don't really need them as there's nothing inherently different between `cider-*-parameters` and `cider-*-global-options`. I think that's just legacy from the earliest days of `cider-jack-in` which was modeled for Lein initially. E.g.:

```
(defcustom cider-lein-global-options
  nil
  "Command global options used to execute Leiningen (e.g.: -o for offline)."
  :type 'string
  :safe #'stringp)
```

It seems initially we wanted to separate the REPL task from the rest of the command invocation, but in hindsight this seems pointless and it just adds a point of confusion for people who now have to wonder which config to modify exactly. I think we'll be better off without this extra complexity. 

I'm opening this issue now because #3275 reminded me about this problem.

**Comment by bbatsov** [comment]
To be clear - my plan is to deprecate those right away and remove them in CIDER 2.0.

**Comment by callmetushar123** [comment]
@bbatsov I new to open source can you guide me on what to do here?

**Comment by bbatsov** [comment]
Sure. It's just a matter of marking those as obsolete and folding them with `cider-*-parameters`. I think they are essentially unused anyways (and have like one usage in codebase each), so at the end that'd be mostly a documentation change.  

Now we'll just deprecate them and we'll delete them in CIDER 2.0.
