### ISSUE TITLE
Inject docstrings into completion candidates

### ISSUE THREAD

**Issue by MicahElliott** [clojure-emacs/cider#3319]
I'd like to be able to see docstrings as part of the completion candidates. Other completers (`M-x`, elisp functions/symbols, etc) are able to show docstrings, so why not cider too?

"But sometimes docstrings are too big to show in a completion!" Yes, but truncating at 100 chars or a first sentence works well, and even encourages docstrings to have a meaningful and concise short first sentence. (example below)

I was able to hack docstrings into view by calling `(lax-plist-get (cider-eldoc-info symbol) "docstring")` inside `cider-annotate-symbol`, but this got way too slow and caused other issues (with further typing and up/down).

So I _think_ the solution is to inject docstrings in along with the `ns` and `type` that's done in `cider-client :: cider-sync-request:complete`. Those come out looking like:
```
;; Present
... (dict candidate dissoc ns clojure.core type function) ...
;; Future, with docstrings
... (dict candidate dissoc ns clojure.core type function docstring "Returns a new map of the same ...") ...
```
Then it's a one-time injection (I think) that I'm hoping will be fast enough. But I'm not sure if it's ok to be shoving significantly more data into the `complete op` in `cider-nrepl-send-sync-request`. What do you think?

Another approach would be to just look up and shove the docstrings into the return of `cider-sync-request:complete` (near `(nrepl-dict-get dict "completions")`). That way the change surface would be minimal (only cider-client.el and cider-completion.el), but I haven't tried testing the slowdown of that.

_(Another related issue is getting docstrings (and existing annotations) to work with [Marginalia](https://github.com/minad/marginalia). I have it working and turns out it's a small/easy change (though not perfect alignment). I can create another ticket for that if it's agreeable to implement this ^^^ ticket.)_

Note that this is not a Marginalia ticket. The request still applies to the normal annotations.

## Examples

See also:
- [vertico](https://github.com/minad/vertico) -- vertical completion system
- [corfu](https://github.com/minad/corfu) -- in-place completer with docstring showing

Example with Marginalia cider-completing `map<tab>`:
![2023-02-03-0820_scrot](https://user-images.githubusercontent.com/159047/216640082-4233855f-4b30-4216-80eb-2ec770d84f67.png)

Example with Marginalia of `M-x cider`
![2023-02-03-0821_scrot](https://user-images.githubusercontent.com/159047/216642510-8b5646e5-0a9f-4f7e-ab70-d5b1e7c15030.png)

Example without Marginalia, still nice!
![2023-02-03-0829_scrot](https://user-images.githubusercontent.com/159047/216642337-cb38c672-0cfc-4d83-81fb-1fb5d9711b7a.png)

**Comment by bbatsov** [comment]
I think we already do something similar for company-mode (see https://github.com/clojure-emacs/cider/blob/master/cider-completion.el#L282), but I guess the other tools have different APIs. Should be pretty straightforward to implement. 

> Then it's a one-time injection (I think) that I'm hoping will be fast enough. But I'm not sure if it's ok to be shoving significantly more data into the complete op in cider-nrepl-send-sync-request. What do you think?

I guess ideally the client should be able to specify exactly what extra metadata interests them for the completion candidates to prevent bloating the response for no good reason. Seems the current API already allows this, btw https://nrepl.org/nrepl/1.0/ops.html#completions (I assume the cider-nrepl API is the same as I made them more or less the same in the past).

**Comment by vemv** [comment]
Corfu already uses our docstring-related tech. That happens simply beucase Corfu observes Company's "API" which we do implement.

(grep `company` within Corfu to verify my claim)

Feel free to re-open the issue, but indicating a specific stack you intend to support. Chances are that we already do - perhaps we can improve documentation, if that helps.

Cheers - V
