### ISSUE TITLE
cider REPL ignores print-method

### ISSUE THREAD

**Issue by daemianmack** [clojure-emacs/cider#3326]
Bug #2856 is still present, though the original ticket was closed for staleness. 

I've updated the original report with my current `Environment & Version information`.

## Expected behavior

The behavior from the clj REPL is that a record (defined with defrecord) should print according to the print-method method if there is one.

In short cider should respect print-method in the default REPL printing behavior.

## Actual behavior

It seems like the behavior of cider is to ignore print-method.

## Steps to reproduce the problem

This issue may be reproduced by entering the following in the repl.

```
(defrecord Foo [x])
(defmethod print-method 'Foo [v w]  (.write w (format "#<Foo x=%s>" (:x v))))
(map->Foo {:x 100})
```
At this point the string `#<Foo x=100>` should be printed rather than `{:x 100}`.

If you try to reproduce this in the clj REPL, you'll see the correct string printed `#<Foo x=100>`

### CIDER version information

;; CIDER 1.6.0 (Buenos Aires), nREPL 1.0.0
;; Clojure 1.10.1, Java 11.0.13

### Lein / Clojure CLI version

Clojure CLI version 1.10.3.1075

### Emacs version

GNU Emacs 30.0.50

### Operating system

OS X 13.1 

### JDK distribution

openjdk version "11.0.13" 2021-10-19 LTS

## Observation
The issue seems related to [this conditional](https://github.com/clojure-emacs/cider/blob/master/cider-repl.el#L1001-L1002) around var `cider-repl-use-pretty-printing` -- disabling that conditional, so that we always merge the two middlewares, "fixes" the bug, though I imagine the right solution is likely not that simple.

**Comment by yuhan0** [comment]
I don't think this is a bug - clojure.pprint uses its own dispatch multifn which you'll have to define manually in addition to `print-method`. 

```clj
(defmethod clojure.pprint/simple-dispatch Foo [v w] ...)
```

A little annoying but I read somewhere that it's intentionally designed to be separate from regular `print` customizations.

There's also a mistake in the example code given - `'Foo` should not be quoted in the call to defmethod.

**Comment by bbatsov** [comment]
@yuhan0 I think you're right. We should probably mention this in the docs.

**Comment by daemianmack** [comment]
Thanks, I missed simple-dispatch as a factor here.

This behaves as desired (note, no writer arg received)...

```
(defmethod clojure.pprint/simple-dispatch Foo [v] ...)
```
