### ISSUE TITLE
run tests from babashka repl session

### ISSUE THREAD

**Issue by judepayne** [clojure-emacs/cider#3329]
I'm using Cider with babashka very smoothly.
One additional point of integration it would be great to see (or perhaps already exists? I can't find documentation) would be running tests from within emacs with the standard `C-c C-t n` key combination.

I have the cognitect test runner set up as per Michael Borkent's instructions [here](https://blog.michielborkent.nl/babashka-test-runner.html) so that I can run them from a bb.edn task from the command line. Could anybody explain how to test the next step for fuller integration with Cider?

**Comment by bbatsov** [comment]
For this test functionality to work, BB's nREPL server will have to implement `cider-nrepl`'s test ops. //cc @borkdude

**Comment by bbatsov** [comment]
That's the middleware in question https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/test.clj and that's the API of the main op that's needed https://docs.cider.mx/cider-nrepl/0.26/nrepl-api/ops.html#test-var-query

**Comment by borkdude** [comment]
Thanks! Maybe this is something that @benjamin-asdf would also be interested in to help with?

**Comment by borkdude** [comment]
@judepayne You can just execute tests from the REPL though with `clojure.test` itself:

```
(test/run-tests)
(test/run-test my-ns/my-test)
(my-ns/my-test)
```

I hardly rely on any external tooling for this myself although I probably should.

**Comment by judepayne** [comment]
Thanks @borkdude. It's just that `C-c C-t n` is so ingrained!

**Comment by benjamin-asdf** [comment]
@judepayne 

```elisp
(defun my-cider-run-current-ns-tests ()
  (interactive)
  (cider-sync-tooling-eval
   (with-output-to-string
     `((test/run-test ,(cider-current-ns))))))
````

assuming `test`   is   loaded in your current cider session, then you could have a function like this.

**Comment by judepayne** [comment]
Thanks @benjamin-asdf. Going in my init.el

**Comment by borkdude** [comment]
You could just fully qualify `test/` into `clojure.test/`

**Comment by vemv** [comment]
This issue would seem best tracked in e.g. https://github.com/babashka/babashka.nrepl .

You can always check out https://github.com/clojure-emacs/cider-nrepl/blob/97e8b253585b24acfc0de5487f97ebaf091762b3/src/cider/nrepl/middleware/test.clj for getting an idea of how the test middleware works, and what may have to be adapted bb side.

(I'm simply trying to help by not keeping an expectation of this feature getting spontaneously implemented)

Cheers - V
