### ISSUE TITLE
Cider will not jack-in

### ISSUE THREAD

**Issue by triclops200** [clojure-emacs/cider#3332]
## Expected behavior
cider-jack-in actually starts a repl and jacks in
## Actual behavior
I get this error message
```
error in process sentinel: Could not start nREPL server:   File "<string>", line 1
    /home/vhoyle/bin/lein update-in :dependencies conj \[nrepl/nrepl\ \"1.0.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.30.0\"\] -- repl :headless :host localhost
SyntaxError: ('code: /',)
 ("exited abnormally with code 1")

```
## Steps to reproduce the problem

I run cider-jack-in in a lein project.

## Environment & Version information
6.1.12-gentoo-x86_64 #1 SMP PREEMPT_DYNAMIC Tue Mar 14 18:36:49 EDT 2023 x86_64 AMD Ryzen 7 5800H with Radeon Graphics AuthenticAMD GNU/Linux

### CIDER version information
cider-20230405.731

### Lein / Clojure CLI version

Leiningen 2.10.0

### Emacs version
GNU Emacs 28.3 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.6) of 2023-03-14

### Operating system

Gentoo Linux
### JDK distribution

Java 1.8.0_312 OpenJDK 64-Bit Server VM

**Comment by triclops200** [comment]
It hangs. I see the problem. I'm using xonsh shell for my system and this is trying to call into the shell instead of calling lein directly.

**Comment by bbatsov** [comment]
@triclops200 So, does this mean that you've tweaked the command for your shell and we can close the ticket?
