### ISSUE TITLE
Cider in Doom Emacs for Logseq Plugin works in mini buffer but not in .cljs file

### ISSUE THREAD

**Issue by DeepReef11** [clojure-emacs/cider#3357]
## Expected behavior

After launching cider-jack-in-cljs, the cider-eval commands should execute the command from the cljs file in the REPL mini buffer.

## Actual behavior

The cider-eval commands doesn't work at all but yanking and pasting to the REPL mini buffer works. The REPL connects properly to the plugin but won't eval from the editor.

## Steps to reproduce the problem

1) Install Emacs then Doom Emacs, enable lsp in :tools and clojure in :lang in the `init.el` file in the config folder `~/.doom.d/ ` then reload `SPCE h r r`.

2) Add cider repl deps in shadow-cljs.edn.
```
:dependencies [
  [cider/cider-nrepl "0.30.0"]
  [cider/piggieback "0.5.1"]
  ]
```

3) Use cider-jack-in-cljs from `M-x` in a file in the cljs project.

4) Reload plugin in logseq (first have to upload it within logseq by selecting the projects folder from the plugin menu).

5) Verify that it is working by sending the following command in the mini bugger `(js/logseq.App.showMsg "It is working!")`

6) In a cljs file, try to send the same command from cider with ` M-x ` `cider-eval-defun-at-point` then select `shadow-cljs`, `shadow`, `:app`, visit browser? No.

## Environment & Version information

Here's the repo I'm using:
https://github.com/DeepReef11/logseq-plugin-cljs-garden-calendar

### CIDER version information

Here's what display in the mini buffer. Version 1.7.0 snapshot.

```
shadow-cljs - socket connect failed, server process dead?
shadow-cljs - HTTP server available at http://localhost:8080
shadow-cljs - server version: 2.16.2 running at http://localhost:9630
shadow-cljs - nREPL server started on port 8702
;; Connected to nREPL server - nrepl://localhost:8702
;; CIDER 1.7.0-snapshot (package: 1.7.0-snapshot), nREPL 1.0.0
;; Clojure 1.10.3, Java 18.0.2-ea
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
;;  Startup: ~/.nvm/versions/node/v20.1.0/bin/npx shadow-cljs -d nrepl/nrepl:1.0.0 -d cider/cider-nrepl:0.30.0 -d refactor-nrepl/refactor-nrepl:3.6.0 -d cider/piggieback:0.5.2 server
;;
;; ClojureScript REPL type: shadow
;; ClojureScript REPL init form: (do (require '[shadow.cljs.devtools.api :as shadow]) (shadow/watch :app) (shadow/nrepl-select :app))
;;
WARNING: CIDER requires cider-nrepl to be fully functional. Some features will not be available without it! (More information)
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (157 files, 0 compiled, 0 warnings, 2.23s)
To quit, type: :cljs/quit
;; => [:selected :app]shadow.user> 
cljs.user> 

```

### Lein / Clojure CLI version

None?

### Emacs version

GNU Emacs 27.1
Doom Core 3.0.0-pre
Doom modules 23.03.0-pre

### Operating system

Ubuntu 22.04

### JDK distribution

openjdk version "18.0.2-ea" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2-ea+9-Ubuntu-222.04)
OpenJDK 64-Bit Server VM (build 18.0.2-ea+9-Ubuntu-222.04, mixed mode, sharing)

**Comment by bbatsov** [comment]
Just to be clear - things work as expected without Logseq, right?

**Comment by DeepReef11** [comment]
I haven't tried on anything else. Is there a simple shadow-cljs project that I could test?

Because the mini buffer works with logseq. I think it may have something to do with emacs, since eval commands launched within that mini buffer doesn't work either.

**Comment by DeepReef11** [comment]
According to a user, [this repo[(https://github.com/tiensonqin/logseq-cljs-playground) works (there's a video showing that it clearly works).When I do the same, it does exactly the same as with my repo (won't work from cljs file). This user is using Emacs 29.0.92. Maybe it as to do with my doom emacs config?

**Comment by DeepReef11** [comment]
Interesting. With that project I get something written beside the line but it doesn't seems to be the right thing. I always get => nil.

I have `(println (+ 1 1))`. I tried evel-defun-at-point and list-at-point at different place in that line, I always get => nil. I'm pretty sure this is not correct.

**Comment by DeepReef11** [comment]
Actually, I get No available JS runtime... I did npm i, yarn, I tried to launch the script as mentioned but I get server already running. THe page is opened with this message: `shadow-cljs - Stale Output! Your loaded JS was not produced by the running shadow-cljs instance. Is the watch for this build running?`

**Comment by DeepReef11** [comment]
Ok, it is working actually.. sorry!

**Comment by DeepReef11** [comment]
All right, it works! Just needed to replace the `:nrepl {...}`with
```
:nrepl
 {:middleware
  [cider.nrepl/cider-middleware
   cider.piggieback/wrap-cljs-repl
   refactor-nrepl.middleware/wrap-refactor]
  :port 50655}

  ```
  In shadow-cljs.edn , run `yarn` in the project, `cider-jack-in-cljs` and then in the cljs file, `M-x` `cider-eval-defun-at-point`.

  Thanks a lot!
