### ISSUE TITLE
Don't jump to useless locations when `cider-auto-jump-to-error` is `t`

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#3381]
When `cider-auto-jump-to-error` is `t`, the following behavior is reproducible:

<img width="573" alt="image" src="https://github.com/clojure-emacs/cider/assets/1162994/fd7ad672-b5b1-4671-83e3-933d269a0328">

It doesn't seem useful to jump to the ns form. If anything it should jump to `something`, which would essentially be a no-op.

**Comment by practicalli-john** [comment]
also reported in April https://github.com/clojure-emacs/cider/issues/3331
