### ISSUE TITLE
Commented code seems to sabotage Cider buffer evaluation

### ISSUE THREAD

**Issue by UnchartedSystems** [clojure-emacs/cider#3388]
I noticed this problem while I was trying to evaluate a namespace to require clojure.core.async to test some throwaway code.

If I evaluate this buffer:
```clojure
(ns test
  (:require [clojure.core.reducers :as r]
            [clojure.core.async :as a]))

;; (go
;;   (dotimes [_ 10]
;;     (dosync
;;       (println "read, foo:" @foo "bar:" @bar))
;;     (Thread/sleep 1000)))
```
I get the error message:
 `error in process filter: Scan error: "Unbalanced Parentheses", 214, 1`  

If I remove the commented code, the buffer evaluates without error and I can write working code with the required namespaces. 

Here is my deps.edn
```edn
{:deps
 {org.clojure/core.async {:mvn/version "1.6.673"}}}
```

My environment:
Pop!_OS 22.04 LTS
Doom Emacs 28.1
CIDER 1.7.0-snapshot (package: 1.7.0-snapshot), nREPL 1.0.0
Clojure 1.10.3, Java 18.0.2.1
openjdk 18.0.2.1 2022-08-18

**Comment by vemv** [comment]
I couldn't repro this.
