### ISSUE TITLE
Warning message on Emacs startup: Package assoc is obsolete!

### ISSUE THREAD

**Issue by adityaathalye** [clojure-emacs/cider#339]
Hello, I just started using nRepl and noticed "Package assoc is obsolete!" appears, in the echo area, when Emacs (24.3) starts.

I found a couple of instances of usage of `assoc' in nrepl.el. A friend suggested I should report it to you. These are the locations:

https://github.com/kingtim/nrepl.el/blob/master/nrepl.el#L694

https://github.com/kingtim/nrepl.el/blob/master/nrepl.el#L2858

Best,
Aditya.

**Comment by k0d3x** [comment]
Search in you .emacs you should have link to old file trouble.
I had the same trouble find ~/.emacs.d/ -name "*.el" -exec grep -H "(require 'assoc)" {} \; give me the file to rm ... but if you let the request in the .emacs package assoc will continue to be.
(trouble with speedbar and gnus-desktop-notify)
have fun

**Comment by apostolou** [comment]
thank you, it did the job for me when I removed the line (require 'assoc) from tagedit.el file.
