### ISSUE TITLE
Make more stacktraces clickable

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#3415]
If I eval `*e` in the REPL, the stacktrace I will see embedded will not be clickable, unlike stacktraces that come from a CIDER error hander.

I can see why we probably never had this feature: inspecting all repl output is expensive and uncertain.

However, one can think of a sensible approach:

* cider-nrepl side, if a given repl output is an instance of Throwable, mark it as such
* cider side, we observe that flag, and only then try to add clickable properties to the output string.

Thoughts? @bbatsov

**Comment by bbatsov** [comment]
I think it'd be much better to have explicit functionality to display the last stacktrace (some interactive command) - this will reduce a lot of complexity.

**Comment by vemv** [comment]
SGTM!

I assume we have nothing like that already?

Perhaps we have the primitives, one could eval `*e`, then `cider-request:log-analyze-stacktrace`?

(cc/ @r0man - this might interest you)

**Comment by bbatsov** [comment]
Frankly - I don't remember. I know we have something similar to display the last result in the inspector. (e.g. `cider-inspect-last-result`).

**Comment by vemv** [comment]
> I think it'd be much better to have explicit functionality to display the last stacktrace 

To expand on that, ideally one could choose how it would be displayed:

* dedicated `*cider-stacktrace*` buffer
* print `*e` to the repl buffer, with propertized (clickable) strings

Personally I would use the latter (I generally don't like popup buffers), but hopefully both would be easy to suppoty.

**Comment by vemv** [comment]
Hmm, I had customized `cider-show-error-buffer nil` for a long time.

(I do use the error buffer though while running tests, so I'm no stranger to it)

Setting it back to `'always` can be good enough.

Still, I feel that ideally, evaluating `*e` on the repl would get you clickable stacktrace items. This would result in more ways to get interactivity. And I tend to dislike popup buffers.

But perhaps it's not worth the effort right now.
