### ISSUE TITLE
Cider Connection Issue with Babashka nrepl-server

### ISSUE THREAD

**Issue by Adek06** [clojure-emacs/cider#3443]
I use babashka nrepl-server as server and Cider as client.

I started nrepl-server according to this document and then cider-connect-clj to localhost:1667 in emacs.

But I get the following error:

```
[nREPL] Establishing direct connection to localhost:1667 ...
[nREPL] Direct connection to localhost:1667 established
error in process filter: cider-get-ns-name: Wrong number of arguments: #<subr clojure-find-ns>, 1
error in process filter: Wrong number of arguments: #<subr clojure-find-ns>, 1
```

I only have one line of code in my file

```
# t.clj
(def x 1)
```

To prove that it's only a cider problem. I used the calva plugin on vscode and it works fine

## Expected behavior

no error

## Actual behavior

get error

```
[nREPL] Establishing direct connection to localhost:1667 ...
[nREPL] Direct connection to localhost:1667 established
error in process filter: cider-get-ns-name: Wrong number of arguments: #<subr clojure-find-ns>, 1
error in process filter: Wrong number of arguments: #<subr clojure-find-ns>, 1
```

## Steps to reproduce the problem

1. run `bb nrepl-server`
2. open clojure file with emacs
3. run `cider-connect-clj` and input localhost:1667
4. get error

### CIDER version information

- openjdk 19.0.1 2022-10-18
- Clojure CLI version 1.11.1.1208
- CIDER 1.8.0-snapshot (package: 20230828.1813)

### babashka version

babashka v1.0.169

### Emacs version

GNU Emacs 30.0.50 (build 1, x86_64-apple-darwin22.2.0, NS appkit-2299.30 Version 13.1 (Build 22C65)) of 2023-08-08

### Operating system

macos 13.1 (22C65)

### JDK distribution

- openjdk 19.0.1 2022-10-18

**Comment by vemv** [comment]
> Wrong number of arguments: #<subr clojure-find-ns>, 1

clojure-find-ns now takes 1 optional argument.

Please check you are using the clojure-mode version required by cider, remove .elc artifacts, and try again.

Cheers - V

**Comment by Adek06** [comment]
> > Wrong number of arguments: `#<subr clojure-find-ns>`, 1
> 
> clojure-find-ns now takes 1 optional argument.
> 
> Please check you are using the clojure-mode version required by cider, remove .elc artifacts, and try again.
> 
> Cheers - V

It works for me, thanks!
