### ISSUE TITLE
rollback cider-xref-source to use cider-jump-to

### ISSUE THREAD

**Issue by zcaudate** [clojure-emacs/cider#3453]
The new `cider-xref` namespace is breaking my current workflow.

I noticed that `cider-xref-source` is using the old `cider-jump-to` command but `cider-xref-fn-refs` does not. Is there a hack to use `cider-jump-to` instead of the `fn-refs` op code?

**Comment by zcaudate** [comment]
`(defcustom cider-use-xref nil "NO XREF FOR CIDER")` works for me. cheers.

**Comment by bbatsov** [comment]
I also think there's some confusion between `cider-xref.el` (this file is mostly about CIDER's own implementation of find references) and the integration with Emacs's xref functionality (which is implemented in terms of `cider-xref.el`).
