### ISSUE TITLE
how to test op codes in repl?

### ISSUE THREAD

**Issue by zcaudate** [clojure-emacs/cider#3454]
is there a way of being able to test the cider.nrepl namespace by sending it an op code and getting a response? 

something like this?

```
(cider.nrepl/op-command 
   {"op" "fn-refs"
    "ns"   'clojure.core
    "sym"  'set})
```

**Comment by vemv** [comment]
Yes,

* First (optional but very recommendable), customize `nrepl-log-messages` to t. Not only it will help you inspect the request/response cycles for your requests, but it also can help debug any future issues you may encounter.
  * After setting it, inspect a buffer named `*nrepl-messages blah*`
* Now, you can invoke `cider-nrepl-send-sync-request`. There are many existing examples within this repo.

Cheers - V

**Comment by zcaudate** [comment]
is there any way to test an op code within the repl instead of emacs?

**Comment by vemv** [comment]
Yes:

* Type e.g. `cider.nrepl.middleware.classpath` in a Clojure buffer
  * You can find others at https://github.com/clojure-emacs/cider-nrepl/tree/master/src/cider/nrepl/middleware
* Jump to it, `M-.`
* Locate the most relevant function
* Invoke it: with `(classpath-reply {})`

I do that on the regular.

I don't immediately know how to invoke cider-nrepl over nrepl using pure clojure. Guess there's https://nrepl.org/nrepl/1.0/index.html .  Normally for me it's either an Elisp full-stack request, or a Clojure invocation without nrepl involved.
