### ISSUE TITLE
Jump-to-definition doesn't work in Babashka 

### ISSUE THREAD

**Issue by daveliepmann** [clojure-emacs/cider#3456]
The [CIDER for Babashka](https://docs.cider.mx/cider/platforms/babashka.html#differences-with-clojure) docs imply that vars defined by the running program should support jump-to-definition:

>Built-in vars (e.g. `clojure.core/map`) don’t have definition location metadata. In practice this means you can’t navigate to their definitions in CIDER.

However, this appears not to be the case. [Clojurians thread](https://clojurians.slack.com/archives/C0617A8PQ/p1694108621229699)

## Expected behavior
I expect to be able to define a var and then jump to its definition from any of its usage sites.

## Actual behavior
Jump to definition does not work for any var, whether built-in or defined locally.

## Steps to reproduce the problem
<img width="961" alt="Screenshot 2023-09-08 at 09 32 31" src="https://github.com/clojure-emacs/cider/assets/974443/ae8619b6-f1b2-4a3d-a597-f23f9cb0ed5d">

1. [terminal] `bb nrepl-server`
2. [emacs] <kbd>M-x</kbd> `cider-connect`
3. 
```clojure
(ns reproduction)
(def foo 1) ;; => #'reproduction/foo
foo ;; => 1
```
4. with cursor on the latter `foo`, <kbd>M-.</kbd> --> instead of jumping to definition, minibuffer displays "Visit tags table..." prompt

### CIDER version information

*Include here the version string displayed when
CIDER's REPL is launched. Here's an example:*

```
;; CIDER 1.7.0 (Côte d'Azur), babashka.nrepl 0.0.6-SNAPSHOT
;; Babashka 1.3.181
```

### Lein / Clojure CLI version

n/a

### Emacs version

GNU Emacs 28.2 (build 1, aarch64-apple-darwin22.1.0, Carbon Version 169 AppKit 2299) of 2022-12-10

### Operating system

macOS Ventura/13.5.1 (22G90)

### JDK distribution
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

**Comment by borkdude** [comment]
When hitting nREPL limitations with babashka, you can now use `bb print-deps` to print out a deps.edn map and just use the regular JVM tooling for development.

You can maybe even write some elisp to add `-Sdeps $(bb print-deps)` to the CIDER clojure-cli arguments automatically

**Comment by vemv** [comment]
Got it.

Anyway, assuming that babashka doesn't implement cider-nrepl ops as analyzed by @iarenaza , then it is to be expected that most things won't work.

We have some fallbacks though, as reflected in this issue: https://github.com/clojure-emacs/cider/issues/2611

Apparently, this is what is supported as of today:

- [x] completion
- [x] jump to definition
- [x] doc
- [x] eldoc
- [ ] running tests 

So in theory, jump to definition [is supported](https://metaredux.com/posts/2020/06/15/nrepl-0-8-evolving-the-protocol.html).

Maybe at some point we had a regression / oversight that omitted these fallbacks.

**Comment by vemv** [comment]
After the fix, I could see jump-to-def working _without_ cider-nrepl with:

* `M-x cider-find-var` 
* `M-x xref-find-definition`

That should be all needed for bb compat. I saw that bb already implements the relatively new `lookup` op.

Available in CIDER master, and as a MELPA snapshot within a couple hours.

**Comment by iarenaza** [comment]
I think you need a recent version of `clojure-mode`. There were some changes around `clojure-find-ns` recently, where the number of parameters changed.

**Comment by daveliepmann** [comment]
You're absolutely right, @iarenaza, thank you. 

At least on my machine, M-. on vars defined locally now jumps to the top of the buffer/`ns` form, not their definition. Could I perhaps still be missing something? 

```
;; Connected to nREPL server - nrepl://localhost:1667
;; CIDER 1.8.0-snapshot, babashka.nrepl 0.0.6-SNAPSHOT
;; Babashka 1.3.181
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
WARNING: Can't determine Clojure version.  The refactor-nrepl middleware requires clojure 1.8.0 (or newer)WARNING: clj-refactor and refactor-nrepl are out of sync.
Their versions are 3.6.0 and n/a, respectively.
You can mute this warning by changing cljr-suppress-middleware-warnings.
user> 
```

**Comment by vemv** [comment]
Please `setq nrepl-log-messages t` prior to starting the repl, repro the issue and then paste the `*nrepl-messages <your repl>*` in a gist.

(If I had to guess, there's a difference between the expected and actual format of bb's `lookup` response format)

**Comment by daveliepmann** [comment]
> Please `setq nrepl-log-messages t` prior to starting the repl, repro the issue and then paste the `*nrepl-messages <your repl>*` in a gist.

https://gist.github.com/daveliepmann/c4fc9e4ee0e10296e1144a031afad5ea

**Comment by vemv** [comment]
Thanks much!

As seen in the last request/respons cycle, your cider.el requested for `op "info"` about `books`, and bb replied with:

```
(<--
  id           "23"
  session      "eaddb3f9-9be9-4c7a-82c1-3229aada4ca2"
  time-stamp   "2023-09-12 10:29:21.766390000"
  arglists-str ""
  file         "/Users/daveliepmann/src/knowuro/knowuro-cljd/bb/import_books..."
  line         1
  name         "books"
  ns           "import-books"
  status       ("done")
)
```

It says the `line` is 1. There's nothing we can do about that - feel free to raise an issue in the adequate repo.
