### ISSUE TITLE
CIDER nREPL does not work in Emacs 29.1

### ISSUE THREAD

**Issue by aurbital** [clojure-emacs/cider#3459]
## Expected behavior
`M-x cider-jack-in` launches repl

## Actual behavior
The first time running `M-x cider-jack-in` produces the error `Package cl is deprecated` and no repl launches. Subsequent attempts to run `M-x cider-jack-in` produces the error `Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2)`

Attempts to start a leiningen repl using `lein repl` and then running `M-x cider-connect` produces the same set of responses from emacs as above.

Please note: this is my first time attempting to run a CIDER nREPL. I've never successfully gotten a CIDER nREPL to run on my machine.

## Steps to reproduce the problem
My init.el was downloaded from here: [](https://github.com/flyingmachine/emacs-for-clojure/), which pulls cider from melpa-stable. This file was downloaded yesterday 2023 Sept 9 

## Environment & Version information

Emacs: 29.1-1
Leiningen: 2.10.0
Java 20.0.2 OpenJDK 64-Bit Server VM
CIDER: ? whatever was downloaded from melpa-stable as of 2023 Sept 9
OS: macOS Ventura 13.4.1

**Comment by vemv** [comment]
Hi! Thanks for the report.

> Eager macro-expansion failure:

Sometimes these go away by removing .elc files before starting Emacs.

You can try:

    cd ~/.emacs.d; find . -type f -name "*.elc" -exec rm {} +

> My init.el was downloaded from here

Looks like you intented to include a link which is missing.

> Please note: this is my first time attempting to run a CIDER nREPL. I've never successfully gotten a CIDER nREPL to run on my machine.

Given this, could you please try Emacs 28, just to discard some possibilities?

I'd recommend https://emacsformacosx.com/ because it's a very vanilla build. You can run the underlying .app file without replacing your installed Emacs.

**Comment by aurbital** [comment]
Oops the link didn't paste properly, it's this: [https://github.com/flyingmachine/emacs-for-clojure/](https://github.com/flyingmachine/emacs-for-clojure/)

I just tried using Emacs 28 on a different Mac computer (different OS), same problem, I get the error `Package cl is deprecated` and no nREPL starts. A second attempt gives the error `Wrong number of arguments: (3 . 4), 2`

Emacs: 28.2
Leiningen 2.9.8
Java 18.0.1.1 OpenJDK
OS: macOS Catalina 10.15.7

So Emacs 28 doesn't work either

**Comment by vemv** [comment]
Thanks!

https://github.com/flyingmachine/emacs-for-clojure/ suggests downloading a .zip file which contains an `elpa` directory. This is both highly unidiomatic, and problematic.

`~/.emacs.d/elpa` should always be created and populated by your package manager. I'd also recommend deleting it when switching Emacs versions.

So, please check if it's possible to:

* quit emacs, delete ~/.emacs.d/elpa, start again, see the packages being downloaded
* use https://github.com/flyingmachine/emacs-for-clojure/ in an alternative way
* use some other emacs setup.

I'll close this issue as it's not CIDER-related, however I'll be happy to help within my capacity.

**Comment by aurbital** [comment]
deleting ~/.emacs.d/elpa did the trick! Thank you! `M-x cider-jack-in` works now!

**Comment by vemv** [comment]
Cheers - enjoy!
