### ISSUE TITLE
Re-run failed tests from cider-test-report buffer doesn't work

### ISSUE THREAD

**Issue by rrudakov** [clojure-emacs/cider#3484]
## Expected behavior

I can re-run failed tests from `*cider-test-report*` buffer by pressing `f` key (or `M-x cider-test-rerun-failed-tests`).

## Actual behavior

Error:
```
Debugger entered--Lisp error: (void-variable retest?)
  #f(compiled-function (conn) #<bytecode -0x16bd72cae8c95d4b>)(#<buffer *cider-repl Work/adgoji-campaign-server-proto:localhost:60409(clj)*>)
  cider-map-repls(:clj-strict #f(compiled-function (conn) #<bytecode -0x16bd72cae8c95d4b>))
  cider-test-execute(:non-passing)
  cider-test-rerun-failed-tests()
  funcall-interactively(cider-test-rerun-failed-tests)
  command-execute(cider-test-rerun-failed-tests)
```

## Steps to reproduce the problem

1. Write a simple test which fails
2. Run it using `C-c C-t C-t`
3. Go to `*cider-test-report*` buffer
4. Press `f`

### CIDER version information

```
;; CIDER 1.8.0-snapshot (package: 20230926.1139), nREPL 1.0.0
;; Clojure 1.11.1, Java 17.0.8.1
```

### Lein / Clojure CLI version

Clojure CLI 1.11.1

### Emacs version

*GNU Emacs 29.1.50 (build 1, aarch64-apple-darwin22.6.0, NS appkit-2299.70 Version 13.5.2 (Build 22G91)) of 2023-09-11* 

### Operating system

*MacOS 13.5.2 (22G91)*

### JDK distribution

```
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Homebrew (build 17.0.8.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.8.1+0, mixed mode, sharing)
```

**Comment by vemv** [comment]
Thanks! Will check it out as we speak.

**Comment by rrudakov** [comment]
vemv ***@***.***> writes:

> Fixed on master, or in the MELPA snapshot to be visible within a 
> couple hours.
>
> Cheers - V

Thank you!
--
Best regards, Roman
