### ISSUE TITLE
Error notifications missing

### ISSUE THREAD

**Issue by samhedin** [clojure-emacs/cider#3487]
A while ago cider/emacs stopped giving me as useful error notifications as it did before. I tried to debug my init.el but couldn't find anything (I guess this is on the Emacs side and not cider).
For example, evaluating
`(defn foo [] undefined-thing)`
creates a red line under the expression and jumps the marker to the start. However, there is no error information. I can see the error info in the repl buffer or by calling `cider-jump-to-compilation-error` which shows it in the modeline:
```
Syntax error compiling at (dev/user.clj:37:1).
Unable to resolve symbol: undefined-thing in this context
```
but it used to show up as a nice popup right in the buffer. I miss the nice popup.

## Steps to reproduce the problem
Unfortunately, I don't have much to say here.
We have discussed the issue on Slack and I'm apparently not the only one with the issue. However, none of us are sure what we did to make it stop working. I don't even remember when it started, maybe a few weeks ago. 

### CIDER version information
```
;; CIDER 1.8.0-snapshot (package: 20230927.1218), nREPL 1.0.0
;; Clojure 1.11.1, Java 17.0.8
```

### Lein / Clojure CLI version
clj deps 

### Emacs version
29.1

### Operating system
Fedora 38

### JDK distribution

```
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment (Red_Hat-17.0.8.0.7-1.fc38) (build 17.0.8+7)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.8.0.7-1.fc38) (build 17.0.8+7, mixed mode, sharing)
```

I realize that this report isn't very helpful for debugging, I'm doing my best to figure out more details.

**Comment by rrudakov** [comment]
I also noticed this problem after switching to MELPA version of CIDER.

**Comment by vemv** [comment]
Hi!

I suspect I know what you're talking about, but please kindly confirm:

* If I type `(/ 2 0)` in the .clj buffer and hit `M-x eval-sexp-at-point`, the `*cider-error*` buffer with a stacktrace pops up
  * is `*cider-error*`what you call "error notifications"? Does it have the same kind of contents that you find missing?
* If I type `(defn foo [] undefined-thing)` in the .clj buffer and hit `M-x eval-sexp-at-point`, `*cider-error*` does not pop up
  * Note however that the REPL buffer will print: `Syntax error compiling at (src/haystack/parser/aviso.cljc:13:1). Unable to resolve symbol: undefined-thing in this context`

**Comment by samhedin** [comment]
> Hi!
> 
> I suspect I know what you're talking about, but please kindly confirm:
> 
> * If I type `(/ 2 0)` in the .clj buffer and hit `M-x eval-sexp-at-point`, the `*cider-error*` buffer with a stacktrace pops up
>   
>   * is `*cider-error*`what you call "error notifications"? Does it have the same kind of contents that you find missing?

From what I remember, there have always been two ways to present errors: One is this *cider-error* buffer, which is showing in this case, and another is the popup that is now missing. 
I don't know what made an error go into the error buffer or the popup, but they've peacefully co-existed in the past. I'd be as happy with just the buffer, I think, as long as the feedback is easily accessible.

> * If I type `(defn foo [] undefined-thing)` in the .clj buffer and hit `M-x eval-sexp-at-point`, `*cider-error*` does not pop up

>   * Note however that the REPL buffer will print: `Syntax error compiling at (src/haystack/parser/aviso.cljc:13:1). Unable to resolve symbol: undefined-thing in this context`

Correct!

**Comment by vemv** [comment]
> and another is the popup that is now missing.

I don't know what that popup is.

What kind of info did it tend to show?

> Correct!

If you miss `*cider-error*` in particular, the change is intentional because of the introduction of `defcustom cider-clojure-compilation-error-phases`. Please refer to its [documentation](https://docs.cider.mx/cider/usage/dealing_with_errors.html) for understanding the nature of the change, and feel free to set it to nil if that feels better for your workflow!

**Comment by samhedin** [comment]
> > and another is the popup that is now missing.
> 
> I don't know what that popup is.
> 
> What kind of info did it tend to show?

Now that you refer to compile vs runtime errors, I think that might have been it. Runtime errors caused the error buffer to show up while compile time errors gave a behavior similar to setting `(setq cider-show-error-buffer nil)`.

> If you miss `*cider-error*` in particular, the change is intentional because of the introduction of `defcustom cider-clojure-compilation-error-phases`. Please refer to its [documentation](https://docs.cider.mx/cider/usage/dealing_with_errors.html) for understanding the nature of the change, and feel free to set it to nil if that feels better for your workflow!
That was it, thank you!

**Comment by bbatsov** [comment]
> I don't know what that popup is.

@vemv See https://github.com/clojure-emacs/cider/pull/3148

**Comment by vemv** [comment]
Got it.

Probably the 'popup' (the red overlay shown in https://github.com/clojure-emacs/cider/issues/3487) can be displayed for compile-time errors.

Probably the original logic of #3487 should be updated to take into account not only `cider-show-error-buffer` but also the `phase`.

**Comment by bbatsov** [comment]
Yeah, I think that'd be a nice way of solving this, as I think the "popup" fits well with the shorter error messages and many people prefer inline buffer popups instead of messages the minibuffer or showing dedicated buffers.

**Comment by vemv** [comment]
CIDER `master` / `20230930.737` bundles the fix.

You may now un-customize `cider-clojure-compilation-error-phases`(if you don't wish to see stacktraces for compile-time exceptions) and the red overlay will still be visible.

The intended behavior is that either a stacktrace or the red overlay will be visible (not both, not none).

Finally, we also now don't uselessly jump to the first line on the buffer for compilation errors, as it could sometimes happen.

Cheers - V

**Comment by magnars** [comment]
I get the red overlay when running `cider-eval-last-sexp`, but not when running `cider-load-buffer`. What would be a good solution for the latter?

**Comment by vemv** [comment]
I've created https://github.com/clojure-emacs/cider/issues/3495 for keeping track of this from a blank slate.

(PRs much welcome btw)
