### ISSUE TITLE
Finer-grained opt-in to overlays

### ISSUE THREAD

**Issue by daveliepmann** [clojure-emacs/cider#3522]
I'm thankful for CIDER 1.8.0's improved use of Clojure 1.10+ error reporting features. One way I'd like to leverage this change is to get short/non-stacktrace error messages as an overlay, _without_ changing the behavior of 1. stacktrace/_\*cider-error\*_-opening errors or 2. normal evaluation. 

That is, my dream scenario is:

1. successful/uneventful form evaluation, e.g. `(range 100)` --> no overlay, see result in minibuffer
2. early-phase error (reading, macroexpansion, compilation), e.g. `:::5` or `(def 5)` --> error overlay
3. late-phase error, e.g. `(throw (ex-info "boom" {:a "a"}))` --> open _\*cider-error\*_ with stacktrace, no overlay

Because `cider-use-overlays` is coarse-grained, it seems 1 and 2 are currently incompatible. Would it be possible to get more fine-grained config here?

Cheers and thanks

(relevant [clojurians thread](https://clojurians.slack.com/archives/C0617A8PQ/p1697390114500909))

**Comment by vemv** [comment]
Thanks!

It seems feasible. `defcustom cider-use-overlays` currently accepts `'both`, `t`, or `nil`.

We could add a `errors-only` option, which would be like `t`. Errors show in the repl in all cases, so we don't need `both-errors-only`, `t-errors-only`, etc.

**Comment by daveliepmann** [comment]
Cool!

> Errors show in the repl in all cases, so we don't need `both-errors-only`, `t-errors-only`, etc.

This doesn't matter to me because I don't mind if situation 2 (early-phase errors) show in both minibuffer and the overlay, but I can't speak to the preferences of others. As long as 1, 2, and 3 are separately configurable I'm satisfied.

**Comment by vemv** [comment]
We have https://github.com/clojure-emacs/cider/pull/3524 in transit, feel free to chime in
