### ISSUE TITLE
Close an existing SSH tunnel before creating a new one with cider-connect

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#3537]
### Discussed in https://github.com/clojure-emacs/cider/discussions/3536

<div type='discussions-op-text'>

<sup>Originally posted by **JMacLulich** October 18, 2023</sup>
I have had this problem for a long long time.

And with GPT-4 I finally got motivated enough to try and solve it.

My problem is when I cider-connect to a remote host via SSH it creates a tunnel -- that's fine.

Every subsequent connect to a different host uses the _same_ tunnel which is tunneling to the first host.

It's so very annoying, I have to manually tear down the tunnel and re-establish it to connect to the right remote host.

I wanted a cider function that would look for existing SSH connections on the same port and tear them down so that a new one to the right remove host is established.

GPT-4 got me this far, but the var `cider--connections` is not defined (as is maybe others) and I don't know how ot proceed from here.

Any advice would be great (my emacs lisp is very basic, because I've actively tried to avoid it).

p.s. if possible I would love it to to host auto-completion the same way `cider-connect` already does, but `cider-known-hosts` seems to be `nil`.

```lisp
(defun cider-connect-and-close-existing ()
  "Connect to a REPL, closing existing connections on the same port."
  (interactive)
  (if (boundp 'cider-known-hosts)
      (let ((hostname (completing-read "Host: " cider-known-hosts))
            (port (read-number "Port: " 7777))) ; Change the default port to 7777
        (let ((existing-connections (seq-filter
                                     (lambda (connection)
                                       (and (equal (cider--remote-host connection) hostname)
                                            (equal (cider--remote-port connection) port)))
                                     (cider--connections))))
          (dolist (conn existing-connections)
            (message "Closing existing connection to %s:%s" hostname port)
            (cider--close-connection conn)))
        (cider-connect-clj hostname port))
    (message "cider-known-hosts is not available, define your own list of known hosts.")))

(global-set-key (kbd "C-c C-o") 'cider-connect-and-close-existing)
```

</div>

**Comment by vemv** [comment]
@JMacLulich - why is reusing the tunnel problematic?

**Comment by JMacLulich** [comment]
@vemv 

Because, currently this happens:
 1. cider-connect <remote host-1> ....no SSH connection currently exists, create a new one.
 2. cider-quit 
 3. cider-connect <remote host-2> ...existing ssh connection exists, use that,
 4. I'm now connected back to host-1 instead of host-2.

And to make it worse, I _think_ I'm connected to host-2 but I'm not, there's nothing telling me otherwise.

**Comment by vemv** [comment]
Got it, thanks.

**Comment by vemv** [comment]
From my understanding of `defun nrepl-connect`, permanently customizing `nrepl-force-ssh-for-remote-hosts` to `t` would suffice - mind to check?

My reasoning is that:

* `nrepl--ssh-tunnel-connect` appears to be correctly implemented - always creates a new tunnel given a different host/port pair
* Under the default `nrepl-force-ssh-for-remote-hosts` value (`nil`), this logic is triggered: https://github.com/clojure-emacs/cider/blob/f85d5c17043a430d0bb730c6637fba52f5a7f94f/nrepl-client.el#L551-L552 so if there was an active tunnel around, it will be implicitly used by `(nrepl--direct-connect host port 'no-error)`.

**Comment by vemv** [comment]
@JMacLulich feel free to continue the conversation
