### ISSUE TITLE
"Error in ‘cider-repl--state-handler’: (wrong-number-of-arguments #<subr clojure-find-ns> 1)"

### ISSUE THREAD

**Issue by zilti** [clojure-emacs/cider#3543]
## Expected behavior

`cider-jack-in-clj&cljs` jacks in without errors

## Actual behavior

`cider-jack-in-clj&cljs` jacks in, starts both REPLs, but gives the following error:

```
Error in ‘cider-repl--state-handler’: (wrong-number-of-arguments #<subr clojure-find-ns> 1)
```

## Steps to reproduce the problem

Jack in with the following .dir-locals.el:

```emacs-lisp
((nil . ((fill-column . 80)
         (cider-clojure-cli-aliases . ":env/dev:env/test:enable-server")
         (cider-preferred-build-tool . clojure-cli)
         (cider-default-cljs-repl . custom)
         (cider-custom-cljs-repl-init-form . "(do (user/cljs-repl))")
         (eval . (progn
                   (make-variable-buffer-local 'cider-jack-in-nrepl-middlewares)
                   (add-to-list 'cider-jack-in-nrepl-middlewares "shadow.cljs.devtools.server.nrepl/middleware")))
         )))
```

### CIDER version information

```
;; CIDER 1.8.3 (Geneva), nREPL 1.0.0
;; Clojure 1.11.1, Java 11.0.20.1
```

### Lein / Clojure CLI version

Clojure 1.11.1.1347

### Emacs version

GNU Emacs 29.1 with the latest DOOM

### Operating system

openSUSE Tumbleweed

### JDK distribution

```
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+0-suse-2.2-x8664)
OpenJDK 64-Bit Server VM (build 11.0.20.1+0-suse-2.2-x8664, mixed mode)
```

**Comment by vemv** [comment]
Sounds like you need to update clojure-mode as well

**Comment by zilti** [comment]
Oh, so I guess I have to wait a bit for the deps in DOOM to catch up :) Might also have something to do with Lispy, I noticed the same error appearing when I wanted to insert parentheses in certain places.

**Comment by vemv** [comment]
It probably all boils down to upgrading clojure-mode. I'd create an issue in Doom but it has so many issues/PRs that it doesn't look like I would be helping.

Probably it's feasible to bump things reliably (with Git tags representing stable releases).

The full list of relevant software to be bumped is: cider, cider-nrepl, clojure-mode, clj-refactor.el, refactor-nrepl, company-mode, parseedn.

**Comment by zilti** [comment]
I updated the dependencies and created a pull request at doomemacs: https://github.com/doomemacs/doomemacs/pull/7515
