### ISSUE TITLE
 Sesman linking not respected

### ISSUE THREAD

**Issue by lgrapenthin** [clojure-emacs/cider#3545]
Since the original thread (https://github.com/clojure-emacs/cider/issues/3097) was closed unexpectedly further discoveries are contributed here:

- Debugging cider-repls in cider-connection.el made apparent that `cider-merge-sessions` needs to be set to 'project' or 'host' for the desired behavior to work
- Apparently the var exists since version 1.5, maybe it would have resolved the original problem?

Some considerations:
- Should it be expected that two `cider-connect` connections (clj/cljs) of one project do not work out of the box?
- and related: Is nil then good default `cider-merge-session`

**Comment by vemv** [comment]
This is not a proper issue report. I'll keep it open in good faith, but please edit it to report the problem objectively (only describe the problem, not a diagnostic), from scratch, following the template, with a project that I can run.

Analyses/suggestions may be welcome but please try to separate them from the actual issue report.

Thanks - V
