### ISSUE TITLE
Inspector: (feature request) Syntax highlighting for the java methods

### ISSUE THREAD

**Issue by anonimitoraf** [clojure-emacs/cider#3546]
First of all, I want to say that the CIDER inspector is awesome! Can't live without it.

**Is your feature request related to a problem? Please describe.**

I find it hard to grok the methods list when they are long, have a lot of arguments and/or there are a lot of them.

For example:

<img width="600" alt="image" src="https://github.com/clojure-emacs/cider/assets/15933322/4db35046-2773-4e94-bef8-3f37b151ad87">

**Describe the solution you'd like**

It would be nice to have Java syntax highlighting for the method names, arguments, etc.

**Describe alternatives you've considered**

I currently have a very (very) hacky solution that adds highlighting via overlays

```elisp
(defvar ++ov-cider-inspector-keywords)
(defvar ++ov-cider-inspector-method-names)
(defvar ++ov-cider-inspector-method-param-lists)
(defun ++ov-cider-inspector ()
  (ov-clear)
  (let ((case-fold-search nil))
    (setq ++ov-cider-inspector-keywords (ov-regexp "^public\\|private\\|protected\\|final\\|native\\|static$")
     ++ov-cider-inspector-method-names (ov-regexp "\\([a-zA-Z0-9.$]\\)+(")
      ++ov-cider-inspector-method-param-lists (ov-regexp "(\\([][<>a-zA-Z0-9.$,]*\\))?")))
  (ov-set ++ov-cider-inspector-keywords 'face `(:foreground ,(doom-color 'magenta)))
  (ov-set ++ov-cider-inspector-method-names 'face `(:foreground ,(doom-color 'red)))
  (ov-set ++ov-cider-inspector-method-param-lists 'face `(:foreground "white")))
```

but even this gives me something very basic:

<img width="600" alt="image" src="https://github.com/clojure-emacs/cider/assets/15933322/02b03562-2fbd-4f1b-a336-20a6723c8205">

**Comment by vemv** [comment]
This is the snippet I use for similar use cases:

```lisp
(defun vemv/to-java-string (s)
  "Returns a propertized string with Java syntax coloring"
  (with-temp-buffer
    (insert s)
    (java-mode)
    (font-lock-ensure)
    (buffer-string)))
```

Feel free to give it a try.

Besides, I noticed in your screenshot another point of improvement. Created https://github.com/clojure-emacs/orchard/issues/198

**Comment by anonimitoraf** [comment]
Thanks for sharing. What does your workflow look like with that snippet?

**Comment by vemv** [comment]
Mmm, if you don't have it easy to plug that function somewhere, let's just wait till a PR lands.

Should be soon enough.

**Comment by anonimitoraf** [comment]
Awesome, thanks!

**Comment by vemv** [comment]
Cheers, the Melpa snapshot should be available later tonight.

We will also cut a stable release with other Inspector goodies 🔎
