### ISSUE TITLE
Error not conveyed when using `cider-pprint-eval-last-sexp`

### ISSUE THREAD

**Issue by danielneal** [clojure-emacs/cider#3553]
## Expected behavior

When an expression is evaluated using `C-c C-p` `(cider-pprint-eval-last-sexp)`, the user should be alerted that there is an error, either via an overlay or an error buffer. 

## Actual behavior

The `*cider-result*` buffer is shown, but it's empty. The error is printed to the REPL. 

## Steps to reproduce the problem

Evaluate an expression that has an error e.g. `(let [x])` using `C-c C-p`

### CIDER version information

CIDER 1.8.4-snapshot (package: 1.8.3), nREPL 1.0.0
Clojure 1.11.1, Java 11.0.13

### Lein / Clojure CLI version

Clojure CLI version 1.11.1.1413

### Emacs version

29.1

### Operating system

Mac OS Ventura 13.5.2

### JDK distribution

openjdk version "11.0.13" 2021-10-19

**Comment by vemv** [comment]
Done!

Expect a new snapshot (and stable release, probably) within a few hours.

Cheers - V

**Comment by danielneal** [comment]
Awesome, thanks @vemv , that's going to greatly improve my daily experience :)
