### ISSUE TITLE
Streamline navigating from `*cider-error*` to the inspector

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#3565]
## Context

`*cider-error*` shows ex-data when displaying a given exception. Said ex-data can be intrincate, and therefore jumping to the Inspector is a natural thing to want.

Currently, if I press `RET`, nothing will happen (other than `newline: Buffer is read-only: #<buffer *cider-error*>`)

## Proposal

When hitting `RET`, the given exception should be inspected.

## Notes

`*cider-error*` can have N `cause`s. `RET` ing each cause should inspect a different object.

It probably would be idea to store in a var (e.g. `cider.nrepl.middleware.ex/xxx`) the current exception being shown in `*cider-error*`, given that it doesn't necessarily corresponds to `*e`.

**Comment by rrudakov** [comment]
Maybe instead of `RET` it could be `p` (the same way it's done in debugger)? Hitting `RET` on a stacktrace item jumps to the location, I guess it might be confusing.

**Comment by vemv** [comment]
Both considerations sound right to me 👍 - thanks

**Comment by vemv** [comment]
Besides from `p` I'm making this simply clickable - good gateway drug to bring more users to the Inspector
