### ISSUE TITLE
BREAKING Cider error: cider-get-ns-name: Wrong number of arguments

### ISSUE THREAD

**Issue by WorldsEndless** [clojure-emacs/cider#3566]
## Expected behavior
cider starts/operates without issue

## Actual behavior
Upon trying to access a Clojure file after cider-jack-in, I cannot proceed past the following error.

## Steps to reproduce the problem

1. cider-jack-in-clj
2. cider-load-buffer (`C-c C-k`)

Error: 
```lisp
cider-get-ns-name: Wrong number of arguments: ((clojure-mode-abbrev-table paredit-mode paredit-version paredit-space-for-delimiter-predicates font-lock-end font-lock-beg calculate-lisp-indent-last-sexp t) nil "Return the namespace of the current Clojure buffer.
Return the namespace closest to point and above it.  If there are
no namespaces above point, return the first one in the buffer.
```

## Environment & Version information
- GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)

### CIDER version information
- CIDER 1.10.0 (Sant Cugat), but also tried the latest git pull

```
;; Connected to nREPL server - nrepl://localhost:44983
;; CIDER 1.10.0 (Sant Cugat), nREPL 1.0.0
;; Clojure 1.10.1, Java 19.0.2
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
;;  Startup: /home/torysa/.guix-profile/bin/lein update-in :dependencies conj \[nrepl/nrepl\ \"1.0.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.42.1\"\] -- repl :headless :host localhost
```

### Lein / Clojure CLI version

*Leiningen 2.10.0 on Java 19.0.2 OpenJDK 64-Bit Server VM*

### Emacs version

*GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)*

### Operating system
*Linux GUIX*

### JDK distribution

*openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+-adhoc..source)
OpenJDK 64-Bit Server VM (build 19.0.2+-adhoc..source, mixed mode, sharing)*

**Comment by vemv** [comment]
Please try upgrading clojure-mode as well

Thanks - V

**Comment by WorldsEndless** [comment]
I actually did two tgings. Before I saw @vemv comment I tried a `lein clean`. Then I also upgraded clojure mode. Now, sure enough, the error is gone! Thanks!

**Comment by vemv** [comment]
🍻!

**Comment by rnadler** [comment]
FWIW: If you're using Doom emacs and `:lang Clojure` and want the latest Cider, add the following to your `package.el`:
```
(unpin! cider)
(unpin! clojure-mode)
```

**Comment by adrech** [comment]
^ consider `(unpin! :lang clojure)` as an alternative, described here:
https://github.com/doomemacs/doomemacs/blob/986398504d09e585c7d1a8d73a6394024fe6f164/lisp/doom-packages.el#L616
In theory, that would ensure that all involved packages are compatible (I haven't tried, not using Doom).

**Comment by rnadler** [comment]
@adrech Nice. Need to use `(unpin! (:lang clojure))` for just the clojure lang though.

**Comment by vxe** [comment]
Hi can someone elaborate on the coupling between cider and clojure-mode, I've wasted a lot of time chasing this down this bug and if the two projects are going to be out of sync with each other I intend to pin both package versions to avoid break on update scenarios.

**Comment by vemv** [comment]
I'd constructively invite you to not consider the time 'wasted'. What can be learned:

* some errors are quite easily findable on Github / Clojurians Slack
* certain habits have to be performed when upgrading deps, especially if using Git instead of MELPA
  * we always assume that depending on library x.y.z guarantees that that minimum version will be used, and not a lower one. 
  * Everything else is the job of your package manager of choice - if it's not working, report a bug there.

Thanks - V
