### ISSUE TITLE
lein.sh should not hardcode `~/.emacs.d`

### ISSUE THREAD

**Issue by slotThe** [clojure-emacs/cider#3572]
Currently, lein.sh [hardcodes](https://github.com/clojure-emacs/cider/blob/master/lein.sh#L20) `~/.emacs.d` in case any errors are reported by `lein` and puts an error file there. This seems like the wrong thing to do, as the user's config itself does not need to reside there. Judging from the `mkdir -p ~/.emacs.d`, that much is known. It can, however, result in extremely surprising behaviour, as Emacs still prefers those paths. By this I mean that even though one might use XDG-like conventions, the mere existence of a `~/.emacs.d` directory will push Emacs towards using that as the place for the config—once hit by a `lein` error, the user will be greeting by a completely vanilla instance upon restart!

I *guess* one could do `emacs --batch --eval "(princ user-emacs-directory)"`. I'm not sure how hacky this is (well, really I know :); either way, there is probably at least one good way to get the correct directory.

**Comment by vemv** [comment]
Thanks for a sensible issue report!

We already honor XDG [JVM side](https://github.com/clojure-emacs/enrich-classpath/issues/47) so it would be no issue to also do it Elisp side.

This should be improved early in the week.

Cheers - V

**Comment by slotThe** [comment]
Well that was fast; thank you so much!

**Comment by vemv** [comment]
🍻!

Happy to have users opting in to enrich-classpath - other feedback welcome anytime.
