### ISSUE TITLE
CIDER does not work with Java 21

### ISSUE THREAD

**Issue by jmyreen** [clojure-emacs/cider#3594]
## Expected behavior

A working CIDER.

## Actual behavior

A whole load of error messages.

## Steps to reproduce the problem

Install OpenJDK 21 and make it default.

## Environment & Version information

Arch Linux, up to date CIDER. OpenJDK 21.

### CIDER version information
Unable to get this information when running on OpenJDK 21. On OpenJDK 11 the following is reported:

;; Connected to nREPL server - nrepl://localhost:43311
;; CIDER 1.13.0-snapshot (package: 20231127.825), nREPL 1.0.0
;; Clojure 1.11.1, Java 11.0.21

### Lein / Clojure CLI version

Leiningen 2.10.0
Clojure CLI version 1.11.1.1386

### Emacs version

30.0.50 from the master branch on 2023/11/25.

### Operating system

Arch Linux.

### JDK distribution

openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9)
OpenJDK 64-Bit Server VM (build 11.0.21+9, mixed mode)

**Comment by vemv** [comment]
I've been using JDK 21 for about a month. Please generously:

* make sure you're using a 'dev' JDK (that is, [with sources included](https://docs.cider.mx/cider/troubleshooting.html#navigation-to-jdk-sources-doesnt-work))
* share all stacktraces you find;
* make sure you can repro the issue in a minimal project;
* share the custom repo if a minimal project _does_ work.

Thanks - V
