### ISSUE TITLE
I have developed a simple way to search Clojure symbols with CIDER; merge into this package or keep separate?

### ISSUE THREAD

**Issue by enzuru** [clojure-emacs/cider#3598]
Hi, I developed a way to search Clojure symbols with CIDER and `completing-read`:

https://github.com/enzuru/completing-read-cider

This allows you to search through Clojure symbols like you can do with Emacs Lisp symbols with Ivy, vert&co, etc. The only requirements are CIDER.

My plan was to publish this as a separate extension for each major Lisp IDE (Geiser + SLY + CIDER), but MELPA wanted me to see if I could submit them upstream instead:

https://github.com/melpa/melpa/pull/8850#issuecomment-1853495227

Is CIDER interested in having this functionality, or should I maintain a separate package?

**Comment by vemv** [comment]
Hi, thanks for creating the discussion!

I'm not sure I understand the use case, mind to expand?

`completing-read` normally is a tool for accomplishing something else - it's not a end user intent in itself.

**Comment by enzuru** [comment]
@vemv very simply, I can search a Clojure symbol that is defined by name, and then select it to get documentation. With something like Ivy or Vert&co (which puts completing-read on steroids), I can fuzzy search said name.

Picture attached.
![cider](https://github.com/clojure-emacs/cider/assets/723711/41356fb1-0da7-40af-8592-cab02e320806)

**Comment by enzuru** [comment]
@vemv very simply, I can search a Clojure symbol that is defined by name, and then select it to get documentation. With something like Ivy or Vert&co (which puts completing-read on steroids), I can fuzzy search said name. Here is a pictur
![cider](https://github.com/clojure-emacs/cider/assets/723711/c0cbe577-1abc-459f-953f-491cb213c25e)
e

**Comment by vemv** [comment]
Hmm, I can `M-x cider-doc`, type "red", trigger completion, and see:

<img width="762" alt="image" src="https://github.com/clojure-emacs/cider/assets/1162994/c136c997-18a8-42b8-b92c-2c424cfd2ab6">

Then the following pops up:

<img width="815" alt="image" src="https://github.com/clojure-emacs/cider/assets/1162994/21ecd757-3b51-4f0c-a053-04c9e93d84d8">

Probably that `*Completions*` buffer can be customized by users for Ivy/etc to be used instead.

Let me know if that workflow isn't sufficient to replicate what you built - we'd welcome a PR that optionally made it richer.

**Comment by vemv** [comment]
A simpler workflow is typing "red", triggering autocompletion with `TAB` or a similar keybinding, and letting a framework like company-mode show the doc:

<img width="715" alt="image" src="https://github.com/clojure-emacs/cider/assets/1162994/e1081426-c3b9-4abd-872a-11a083bbb1e3">

**Comment by enzuru** [comment]
@vemv yeah, swapping out completing-read (which is what the completion frameworks do) does not change the `cider-doc`, which I am guessing is using separate completion machinery?

I agree there are other ways to search, I was just trying to search in the same way I search Emacs Lisp.

**Comment by vemv** [comment]
cider-doc is defined honoring a `cider-prompt-for-symbol-function` defcustom, like so:

https://github.com/clojure-emacs/cider/blob/25c51fd4b1246801ba3fa15c57b44d860772417c/cider-doc.el#L287-L298

Note that it receives `#'cider-doc-lookup` as an argument.

By customizing `cider-prompt-for-symbol-function` you should have all it takes for a custom UX, with docs displayed inline.

Let us know how it works for you. I'll close the issue for now, but feel free to keep the conversation going!

We'd always welcome further customization options or perhaps, if no changes are needed, a "how to" in our usual manual.

Cheers - V
