### ISSUE TITLE
`cider--error-phase-of-last-exception` can call itself when the cider-nrepl middleware is faulty

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/cider#3605]
One thing I've noticed with recent reports is that whenever the cider-nrepl `analyze-stacktrace` op was faulty, `cider--error-phase-of-last-exception` would enter into a recursion loop.

Worth investigating

**Comment by bbatsov** [comment]
> whenever the cider-nrepl analyze-stacktrace op was faulty

Faulty how?

**Comment by vemv** [comment]
For instance:

* Running an older Clojure
* Having 1M files in resources

Those two are unrelated but resulted in the same symptoms.

**Comment by vemv** [comment]
Can repro by:

* modifying the `analyze-stacktrace` mw to throw an exception
* evaling an expr, but not from the repl, but inline instead (`cider-eval-sexp-at-point`)

So this should be specific to its eval handler (there are a few eval handlers that call `cider--error-phase-of-last-exception`)
