### ISSUE TITLE
Update cheatsheet

### ISSUE THREAD

**Issue by katomuso** [clojure-emacs/cider#3674]
I want to update cheatsheet to match the latest version of the official cheatsheet (v55). Right now, it kind of looks like v43 of the official cheatsheet, but there are a lot of little differences here and there, so it is hard to compare and update it to the latest version. For example, there are unrelated functions such as `nil?`, `some?`, `identical?` in the section with number test functions, while functions such as `number?`, `rational?`, `integer?` are not there.

What do you think about making it identical to the latest official cheatsheet, so it will be easier to maintain in the future? If you want to keep the current differences, I can just do a little cleanup and add the changes from the latest version.

**Comment by bbatsov** [comment]
> What do you think about making it identical to the latest official cheatsheet, so it will be easier to maintain in the future? If you want to keep the current differences, I can just do a little cleanup and add the changes from the latest version.

I'd be fine with updating it, so PRs are most welcome! Frankly, I don't even recall how we fetched the data back in the day. Probably it just came from the legacy Emacs package that CIDER absorbed at some point. (seee https://github.com/clojure-emacs/clojure-cheatsheet)

**Comment by katomuso** [comment]
Yeah, probably the author based it on the official cheatsheet, but changed the structure a little. So, to be sure, would it be better to add the changes from the official cheatsheet on top of the current one or to transform the latest version of the official cheatsheet into CIDER cheatsheet format and replace the current one?

**Comment by katomuso** [comment]
For the record, we can find data from which the official cheatsheet is generated at https://github.com/clojure/clojure-cheatsheets/blob/master/src/clj-jvm/src/generator/generator.clj (`cheatsheet-structure`). I think it will even be possible to write some tool that transforms that data into a simplified CIDER format.

**Comment by bbatsov** [comment]
> Yeah, probably the author based it on the official cheatsheet, but changed the structure a little. So, to be sure, would it be better to add the changes from the official cheatsheet on top of the current one or to transform the latest version of the official cheatsheet into CIDER cheatsheet format and replace the current one?

Whatever works best for you. Probably some simple data transforming tool will be the best long-term solution.

**Comment by katomuso** [comment]
Got it, I'm going to give it a try.
