### ISSUE TITLE
In CLJC mode, C-x C-e evaluates against multiple REPLs simultaneously 

### ISSUE THREAD

**Issue by lgrapenthin** [clojure-emacs/cider#3675]
Reading from the source code, this appears more like a "feature".  I have decided to file it as a bug, because I consider it unexpected behavior.  Further reasoning below.

Steps to reproduce:
- Connect both to clj REPL and a cljs REPL in the same project.  Consider setting `cider-merge-sessions` to `project` for that to work (not a default setting).
- Open a CLJC file that is loaded/required in both REPLs
- C-x C-e an expression.  You will see that CIDER sends the expression to both REPLs and then the results will compete in a flashing on the screen, **where the last one wins and the first one can't be read anymore.**

Why this is bad?
1) It prevents one from effectively studying the result of one of the REPLs.  The results can be widely different, especially when evaluating against state of the respective environment.
2) A user has no control to choose which REPL he wants to evaluate against

Workarounds:
- Change major mode of cljc file to clojurescript-mode or clojure-mode
- Use REPL by hand
- Close other REPL

Recommended solution:
- When more than one REPL is associated with a CLJC buffer, the user should be able to choose which REPL to evaluate against.  
- If there is a real usecase for evaluating against multiple REPLs simultaneously, this should not be the default behavior 
- Evaluating simultaneously against multiple REPLs should only be supported if the results can be presented in a way they can be read, distinguished and understood in the context of the REPL they are coming from.

**Comment by vemv** [comment]
There's https://github.com/clojure-emacs/cider/commit/be224e37

Feel free to continue a possible discussion
