### ISSUE TITLE
Rename private functions in `cider-docstring.el` to have proper prefix

### ISSUE THREAD

**Issue by katomuso** [clojure-emacs/cider#3710]
Currently, docstring-specific private functions in `cider-docstring.el` have a global prefix (such as `cider--render-pre`, `cider--string-rstrip-newlines`, `cider--fragments-to-s`, etc.). What do you think about renaming them to have the proper `cider-docstring` prefix?

**Comment by bbatsov** [comment]
That doesn't matter much to me. On one hand consistency is good, but on another - long function names impede readability a bit. I keep dreaming of having real namespaces in Elisp.

**Comment by katomuso** [comment]
I understand your concerns, but I think that it can actually improve readability as it becomes obvious that those functions belong to a particular package and serve a specific purpose. Also, as far as I understand, this is really old code (I can't even find how old using `git log`) and it will be nice to refactor it a bit along with prefixing names properly.

**Comment by bbatsov** [comment]
It's not a big deal to me either way, so feel free to change this.

**Comment by vemv** [comment]
I don't mind a lot about this, however I wouldn't bother with it.

There a lot of better uses of our time - we're not short of bugs, big and small!

We're always happy to receive contributions, but the best ones tend to solve real problems users face.

Those also build a lot of trust for future interactions.

**Comment by katomuso** [comment]
Well, there is already a lot of stuff in CIDER and it still grows. I think it's important to refactor old code that hasn't been touched for 10 years. Maybe we can even make the whole `cider-docstring.el` package a couple of functions, which can reside in `cider-doc.el`. I'm not sure because it's hard to make sense of it now.
