### ISSUE TITLE
Unable to boot cider off a fresh corgi install?

### ISSUE THREAD

**Issue by shellandbull** [clojure-emacs/cider#3715]
## Expected behavior

Invoking `cider-jack-in-clj` to boot a `cider` server 

## Actual behavior

The error `Symbol’s value as variable is void: cider-clojure-cli-parameters` happens. Here's what I see on screen on debug mode

<img width="727" alt="Screenshot 2024-06-13 at 8 43 45 AM" src="https://github.com/clojure-emacs/cider/assets/3522106/e614db59-714f-4cf9-b450-d41038bf8be4">

## Steps to reproduce the problem

- Install `emacs` via `homebrew`
- Install Corgi https://github.com/corgi-emacs/corgi
- Open any `.clj` file
- Run the command `cider-jack-in-clj`

## Environment & Version information

```
1,7 GHz Quad-Core Intel Core i7
```

### CIDER version information

`CIDER 1.5.0-snapshot (package: 1.5.0-snapshot)`

### Lein / Clojure CLI version

`Clojure CLI version 1.11.2.1446`

`Leiningen 2.11.2 on Java 21.0.2 OpenJDK 64-Bit Server VM`

💡 my project uses `deps.edn`

### Emacs version

```
GNU Emacs 29.3
Copyright (C) 2024 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

### Operating system

Macbook Sonoma 14.5 

### JDK distribution

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

**Comment by vemv** [comment]
The variable was removed a few years ago

> Removed cider-clojure-cli-parameters due to clojure-cli jack-in changes.

https://github.com/clojure-emacs/cider/blob/105da319b09a436552f1b3c6194cbbc833017dd2/CHANGELOG.md#110-2021-04-22

Feel free to continue the conversation - we'll be happy to assist.

**Comment by shellandbull** [comment]
@vemv thanks for the quick response! I guess a PR to corgi is somewhat overdue?

How can I fix this? the code fails exactly [here](https://github.com/corgi-emacs/corgi-packages/blob/c0406ba6cf128e561b22e2c201801f8d59f8a66c/corgi-clojure/corgi-clojure.el#L162-L166)

```
;; Most annoying JVM "feature" of all time
;; https://docs.cider.mx/cider/troubleshooting.html#empty-java-stacktraces
(defun corgi/around-cider-jack-in-global-options (command project-type)
  (if (eq 'clojure-cli project-type)
      (concat cider-clojure-cli-parameters
              " -J-XX:-OmitStackTraceInFastThrow")
    (funcall command project-type)))
```

**Comment by bbatsov** [comment]
Hmm, `cider-clojure-cli-parameters` still exists, so I'm a bit puzzled right now.

**Comment by bbatsov** [comment]
```(defcustom cider-clojure-cli-parameters
  nil
  "Params passed to clojure cli to start an nREPL server via `cider-jack-in'."
  :type 'string
  :safe #'stringp
  :package-version '(cider . "1.8.0"))
```

What's your CIDER version?

**Comment by vemv** [comment]
Yes was looking at that, `cider-clojure-cli-parameters` was reintroduced in CIDER 1.8.0 🌀

**Comment by bbatsov** [comment]
Ah, seems the problem is the use of the ancient CIDER 1.5. An upgrade to a recent version will solve this.

**Comment by vemv** [comment]
corgi-packages depends on cider as of https://github.com/clojure-emacs/cider/commit/68974c9fb6ee6e95a4568c46a9c4371b24d2f0e9 which is definitely old

**Comment by shellandbull** [comment]
@vemv / @bbatsov thanks you both for being so quick - is it safe to say an upgrade to `cider` is long overdue?

**Comment by bbatsov** [comment]
1.15

**Comment by shellandbull** [comment]
<img width="1297" alt="Screenshot 2024-06-13 at 12 20 58 PM" src="https://github.com/clojure-emacs/cider/assets/3522106/75f443d5-ca38-46ad-a424-11fb4d1947c2">

it was always 1.15

**Comment by shellandbull** [comment]
I reinstall the package and I can now boot a cider REPL

Syntax highlighting is gone and the error I get now is:

`failed to define function cider--setup-menu-for-clojure-major-mode`

**Comment by vemv** [comment]
Are you able to obtain a stacktrace?

You should by running `M-x toggle-debug-on-error` beforehand

**Comment by shellandbull** [comment]
![Screenshot 2024-06-13 at 1 09 57 PM](https://github.com/clojure-emacs/cider/assets/3522106/f84fe557-7bbb-4ae8-9eeb-23e91a74c5c1)

It feels as if corgi needs some changes to accommodate new versions of cider? I only have about 2 weeks of experience with clojure so I'm finding this a bit hard to untangle

**Comment by vemv** [comment]
It looks like a good idea to bump clojure-mode as well - most likely it's old as well

After that, please quit emacs, remove all .elc file within your Emacs dir, retry

**Comment by shellandbull** [comment]
https://github.com/clojure-emacs/cider/blob/105da319b09a436552f1b3c6194cbbc833017dd2/cider-mode.el#L552 the function seems to be real in this codebase

it looks like `cider-mode` succeeds when invoked

but invoking `clojure-mode` fails

**Comment by vemv** [comment]
If you're the first person to upgrade Corgi to use cider latest, you may be uncovering some sort of uncompatibility, IDK.

You may have luck asking about `failed to define function` errors in Clojurians Slack #emacs

**Comment by shellandbull** [comment]
@vemv I don't think I am specifying a newer version, I downloaded the software as-is. I might be luckier if I just ask other people with a non broken version of corgi what version of the packages they're using

**Comment by vemv** [comment]
Alright

btw although I sympathize with Corgi, if corgi-packages points at such old versions https://github.com/corgi-emacs/corgi-packages/blob/c0406ba6cf128e561b22e2c201801f8d59f8a66c/corgi-versions.el#L6 then it might be a hint that it's not as active as we'd wish.

I've had a good experience syncing changes with Doom folks

**Comment by shellandbull** [comment]
@vemv I started with spacemacs, it was too heavy and ate so much ram

I found corgi which seemed so much lighter and I was very happy with but it looks like every "flavour" of emacs has a different issue that requires manual fixing, to the point where I feel like giving up and just use python over clojure and a standard setup

**Comment by vemv** [comment]
Doom appears to have a focus on efficiency - I've heard good feedback from Clojure peers at workplaces or OSS teams, over the years.

Then there's @bbatsov's own Prelude, although less vim-y I think 😄

**Comment by shellandbull** [comment]
@vemv I know someone with corgi on their setup and its pretty fast/reusable. I'll ask them about versions and what not - could you please open an issue on corgi citing the stuff that needs updating? I'd do it myself but I can barely understand any of the code in this case

**Comment by vemv** [comment]
Sure, will cc/ you
