### ISSUE TITLE
Remove all code related to sideloading

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#3717]
nREPL removed support for the failed experimental sideloading functionality and we should follow-up by removing the code from CIDER as well. 

See https://github.com/nrepl/nrepl/pull/335 for details.

**Comment by bbatsov** [comment]
Ops, seems I had forgotten about this issue and I opened #3733 as well. 🤦

**Comment by alexander-yakushev** [comment]
-207 🎉
