### ISSUE TITLE
Remove support for sideloading

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#3733]
Sideloading was removed in nREPL 1.3 and we should clean up CIDER's code accordingly. The only open issue is whether to delete both sideloading and `add-middleware` or only sideloading code, as they are kind of related and `add-middleware` won't work anyways if we kept it. So, probably we should just kill everything and restore `add-middleware` if we ever get it to work on nREPL's side. @alexander-yakushev What do you think about this?

**Comment by bbatsov** [comment]
The code in question is mostly here https://github.com/clojure-emacs/cider/blob/master/cider-eval.el#L208

**Comment by alexander-yakushev** [comment]
`add-middleware` still exists in nREPL, but I guess it's of no use here in CIDER without the sideloading. I'd say nixing it and restoring in the future is a reasonable way to go.

**Comment by bbatsov** [comment]
Agreed.
