### ISSUE TITLE
Error after enabling `cider` completion style

### ISSUE THREAD

**Issue by rrudakov** [clojure-emacs/cider#3749]
## Expected behavior

`cider` completion style works without errors.

## Actual behavior

Error:
```
completion--in-region-1: Wrong type argument: listp
```
in the echo area and in the `*Messages*` buffer.

## Steps to reproduce the problem

1. Start `emacs -q`
2. Evaluate:
```emacs-lisp
(package-initialize)
(require 'cider)
(cider-enable-cider-completion-style)
```
3. jack-in to a clojure project.
4. type something and try to use `complete-symbol` or `C-M-i`.

The feature was introduced in the recent PR - https://github.com/clojure-emacs/cider/pull/3746

### CIDER version information

```
;; CIDER 1.16.0 (Kherson), nREPL 1.3.0
;; Clojure 1.12.0, Java 23
```

### Lein / Clojure CLI version

Clojure CLI 1.12

### Emacs version

30

### Operating system

macOS

### JDK distribution

openjdk version "23" 2024-09-17
OpenJDK Runtime Environment Homebrew (build 23)
OpenJDK 64-Bit Server VM Homebrew (build 23, mixed mode, sharing)

### Stack trace

```
Debugger entered--Lisp error: (wrong-type-argument listp #("print" 0 1 (type "function" ns "clojure.core")))
  completion--do-completion(#<marker at 231 in app.clj> 235)
  completion--in-region-1(#<marker at 231 in app.clj> 235)
  #f(compiled-function (start end collection predicate) #<bytecode 0x1edeb26f2986a456>)(#<marker at 231 in app.clj> 235 #f(compiled-function (prefix pred action) #<bytecode -0x971aca080484915>) nil)
  apply(#f(compiled-function (start end collection predicate) #<bytecode 0x1edeb26f2986a456>) (#<marker at 231 in app.clj> 235 #f(compiled-function (prefix pred action) #<bytecode -0x971aca080484915>) nil))
  #f(compiled-function (funs global args) #<bytecode 0x1802ed4d7104dedc>)(nil nil (#<marker at 231 in app.clj> 235 #f(compiled-function (prefix pred action) #<bytecode -0x971aca080484915>) nil))
  completion--in-region(#<marker at 231 in app.clj> 235 #f(compiled-function (prefix pred action) #<bytecode -0x971aca080484915>) nil)
  completion-in-region(#<marker at 231 in app.clj> 235 #f(compiled-function (prefix pred action) #<bytecode -0x971aca080484915>) nil)
  completion-at-point()
  complete-symbol(nil)
  funcall-interactively(complete-symbol nil)
  command-execute(complete-symbol)
```

### Screenshot

<img width="1918" alt="image" src="https://github.com/user-attachments/assets/4b04587a-7e12-4da2-a15b-faf5a58c3fe4">

**Comment by alexander-yakushev** [comment]
Jeez, I've been using this for quite some time locally, didn't expect a blunder right away. I'll take a look.
