### ISSUE TITLE
Installation fail: https://elpa.gnu.org/packages/transient-0.7.7.tar: Not found

### ISSUE THREAD

**Issue by BluePyTheDeer251** [clojure-emacs/cider#3755]
When trying to install it says it cannot find the package "transient", version 0.7.7, which doesn't exist (the repo says it is 0.7.6)

OS: Arch Linux

Emacs version: 29.4

How to replicate:

Use a new computer (or a VM) with emacs installed (without cider)

Open emacs and try to install cider (after configuring init.el for MELPA)

If it says it couldn't find transient you recreated the error.

**Comment by bbatsov** [comment]
Try `M-x package-refresh-contents` first. Probably your local package DB is out of sync.

**Comment by BluePyTheDeer251** [comment]
Thanks, problem solved
