### ISSUE TITLE
Implement HTTP transport

### ISSUE THREAD

**Issue by technomancy** [clojure-emacs/cider#39]
nREPL uses bencode by default but can also be made to work over other protocols like HTTP: https://github.com/cemerick/drawbridge/

**Comment by martinraison** [comment]
I'm also very interested in this

**Comment by bbatsov** [comment]
@martinraison PRs welcome. :-) I'd love to see this supported in CIDER, but it's really low on our list of priorities.

**Comment by martinraison** [comment]
I doubt I can find time to do that at the moment, but if I ever get to it I'll let you know. An intermediary solution I was thinking of was to setup a nrepl server that proxies all my requests through http. Far less elegant but that could do the trick for my needs.

**Comment by jconti** [comment]
Still no hope on this one?

**Comment by jconti** [comment]
Actually cannot [drawbridge](https://github.com/cemerick/drawbridge) be configured in cider?

**Comment by bbatsov** [comment]
The problem is not the server. The problem is that you have to add support to CIDER for http communication. Basically all code using bencode directly should be touched by such a change and that's why no one has been very eager to work on this.

**Comment by dpsutton** [comment]
@jconti if you want to hack around on it, there's basically a single function that is where it bencodes the info and sends it off:

```
(defun nrepl-send-request (request callback connection)
  "Send REQUEST and register response handler CALLBACK using CONNECTION.
REQUEST is a pair list of the form (\"op\" \"operation\" \"par1-name\"
\"par1\" ... ). See the code of `nrepl-request:clone',
`nrepl-request:stdin', etc.
Return the ID of the sent message."
  (with-current-buffer connection
    (when (and (not (lax-plist-get request "session"))
               nrepl-session)
      (setq request (append request (list "session" nrepl-session))))
    (let* ((id (nrepl-next-request-id connection))
           (request (cons 'dict (lax-plist-put request "id" id)))
           (message (nrepl-bencode request)))
      (nrepl-log-message request 'request)
      (puthash id callback nrepl-pending-requests)
      (process-send-string nil message)
      id)))
```

if you added http calls there you are half way there instead of the process send string. On the other side, you'd need a new filter that just watches for incoming info and then hooks that info up against the pending requests in a dictionary. I think this return side will be much more difficult. Also, since we no longer have a process in the buffer, you'll need to check if the http requests are still going, etc.

**Comment by bbatsov** [comment]
> Also, since we no longer have a process in the buffer, you'll need to check if the http requests are still going, etc.

Well, that's actually going to be pretty simple given the fact he'll just have an http connection. At least for non-streaming responses. At least there are a ton of http libraries, so all of the communication plumbing will come for free.

**Comment by jconti** [comment]
I think I will give this a try. Recently I found this little project which looks like it approaches the problem from a different perspective: https://github.com/malyn/lein-catapult

**Comment by holtzermann17** [comment]
@jconti Did you have any luck with that?

I have tried today -- I created a fork of `lein-catapult` with contemporary dependencies swapped in, and when I try to connect I get this:

```
$ lein catapult http://USER:PASS@127.0.0.1:8080/repl
:repositories detected in user-level profiles! [:user] 
See https://github.com/technomancy/leiningen/wiki/Repeatability
Retrieving com/github/holtzermann17/lein-catapult/4fa2f909f334d2094b2885567f0f036da3518820/lein-catapult-4fa2f909f334d2094b2885567f0f036da3518820.pom from jitpack
Listening on port  33853 ; connected to Drawbridge.
nREPL connection accepted.
>>> {:op clone, :id 388}
>>> {:op clone, :id 389}
>>> {:op describe, :session ba6f45c9-8bc1-4e9b-8bf6-85c51fa10aec, :id 390}
<<< {:id 390, :session ba6f45c9-8bc1-4e9b-8bf6-85c51fa10aec, :aux {:current-ns user}, :ops {:describe {}, :eval {}, :load-file {}, :stdin {}, :clone {}, :interrupt {}, :close {}, :ls-sessions {}}, :versions {:nrepl {:major 0, :minor 6, :incremental 0, :version-string 0.6.0}, :clojure {:major 1, :minor 10, :incremental 0, :version-string 1.10.0}, :java {:major 11, :minor 0, :incremental 6, :version-string 11.0.6}}, :status [done]}
>>> {:file *cider-repl system-test/exchange:localhost:33853(clj)*, :nrepl.middleware.print/quota 1048576, :nrepl.middleware.print/print cider.nrepl.pprint/pprint, :op eval, :column 1, :line 1002, :id 391, :code (clojure.core/apply clojure.core/require clojure.main/repl-requires), :content-type true, :inhibit-cider-middleware true, :nrepl.middleware.print/stream? 1, :nrepl.middleware.print/options {:right-margin 70}, :session ba6f45c9-8bc1-4e9b-8bf6-85c51fa10aec}
```

Cider show that it is still trying to connect.  Maybe it is close to working though, given that it got that far?
