### ISSUE TITLE
Residual JVM After Quitting

### ISSUE THREAD

**Issue by drguildo** [clojure-emacs/cider#390]
Whenever I quit emacs or run nrepl-quit I get an orphaned JVM process remaining.

Attached should be an image showing the emacs process tree after running nrepl-jack-in.

I also tested with CIDER 20131018.1553 from a fresh .emacs.d with just cider/clojure-mode and had the same problem.

![nrepl-jvm-bug](https://f.cloud.github.com/assets/9282/1368493/d08c324e-39a4-11e3-984c-f4cd46e802ea.png)

**Comment by bbatsov** [comment]
Closing this as there's not much we can do about it.

**Comment by mattiasw2** [comment]
I do not really understand why this issue was closed. It is a big problem, and it is not solved in Emacs 24.5 for Windows.

I currently use this workaround in .emacs

````
(defun my-kill-java ()
  (interactive)
  (cider-interactive-eval "(System/exit 0)")
  )

(defun turn-on-my-clojure-commands ()
   :
    (define-key clojure-mode-map (kbd "C-c q") 'my-kill-java)

  )

(add-hook 'clojure-mode-hook 'turn-on-my-clojure-commands)

````

**Comment by bbatsov** [comment]
It's closed because it's not a cider issues, it's an Emacs issue.

**Comment by mattiasw2** [comment]
Ok, but maybe we should at least tell users about a workaround? The hanging java-processes will kill the machine, and a generic command like "pskill java" will also kill databases like datomic and cassandra.

**Comment by bbatsov** [comment]
> Ok, but maybe we should at least tell users about a workaround? The hanging java-processes will kill the machine, and a generic command like "pskill java" will also kill databases like datomic and cassandra.

I'd normally just inspect all Java processes and kill the relevant ones. As repl restarts are uncommon I don't think this is major issue anyways.

> How do I set the command for the repl too, i.e. what is the clojure-repl-mode-map called?

`cider-repl-mode-map`.

**Comment by jconti** [comment]
I think doing (shutdown-agents) lets the jvm quit by itself on windows.  I think it is the windows JVM that starts some non-server thread that then blocks the normal exit.  I wish I could recall what project I read this information in (maybe Nightcode, maybe ring-jetty, not sure).

**Comment by mattiasw2** [comment]
I have solved it by calling (System/exit 0) from within the repl.

I added a command to .emacs

```
(defun my-kill-java ()
  (interactive)
  (cider-interactive-eval "(System/exit 0)")
  )
```

     (define-key cider-repl-mode-map (kbd "C-c C-q") 'my-kill-java)

**Comment by jconti** [comment]
I've fussed with the code a bit. The solutions above using cider-interactive-eval block and sometimes leave orphaned cider interaction buffers. The following code has made my repl shutdown nicely reliable:

```elisp
(defun my-kill-java ()
  (interactive)
  (cider-nrepl-send-unhandled-request
   (list "op" "eval"
         "code" "(do 
                   (.start 
                     (Thread. 
                       (fn [] 
                         (Thread/sleep 5000)
                         (shutdown-agents)
                         (System/exit 0)))) 
                  nil)"))
  (cider-quit 'QUIT-ALL))
```

**Comment by bbatsov** [comment]
Supposedly @benedekfazekas fixed this recently with https://github.com/benedekfazekas/cider/commit/7cd9c7032f6c65869d5a1ba1e4292f4375585cf2

**Comment by jconti** [comment]
I saw that, but did not think to test it.  I will test and confirm.  Thank you!

**Comment by jconti** [comment]
The fix looks good to me.
