### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#399]
It'd be really nice if we had a proper project logo Obviously I don't have the skills required to create a decent logo, otherwise I would have done it by now :-)

I'm turning to cider's users, who might have some sense of art and the skills required to create a good looking logo. :-) I'm thinking of something that has ties to cider, Emacs and Clojure, but alternative suggestions are also welcome. Perhaps a bottle with some purplish liquid (reference to Emacs) in it and a sticker inspired by Clojure's logo? 

Please submit your ideas here. In case we get several nice suggestions we'll have a vote for the "official logo".

Thanks in advance to everyone who decides to help!

**Comment by emaphis** [comment]
Lol, In some parts of the US, warm alcoholic cider is called "apple jack".
