### ISSUE TITLE
cider caches all output of an evaluation before writing to the REPL buffer

### ISSUE THREAD

**Issue by cemerick** [clojure-emacs/cider#421]
(FYI, I'm on 0.2.0alpha here at the moment (still letting emacs-live handle my config), so my apologies if this has been addressed on HEAD.  Tracing `cider-eval`, it seems to bottom out in `nrepl-client` without touching any of the `-sync` variants, so hopefully that is the case.)

Following up on an nREPL user report that they weren't seeing output from some evaluations that returned very large data structures, I ran this set of expressions, all sent in a single line / request (put on separate lines for readability):

```clojure
(set! *print-length* nil)
(set! *print-level* nil)
(def t (System/currentTimeMillis))
(repeat n [{:a 1 :b 2 :c 3} 7 8 9 "hi"])
(- (System/currentTimeMillis) t)
```

across three different environments: `lein repl` in a fairly vanilla project, a bare-terminal clojure.main REPL, and via nrepl.el.

With `n` of 1e5, I got timings of:

lein repl: 10.4s
clojure.main: 7.8s
nrepl.el: 11.2s

These timings each scaled up ~linearly with an `n` of 1e6, which is good.  What's bad is that nrepl.el appears to cache _all_ output before displaying anything (which was the problematic behaviour reported by the aforementioned user).  In contrast, both the clojure.main REPL and `lein repl` start streaming output very quickly (there is a ~1s delay before seeing the first output from the latter, but I'm much less concerned about that).

**Comment by cichli** [comment]
If you want the result to be streamed back to the REPL, the best workaround is to enable `cider-repl-use-pretty-printing`. This will also mean the evaluation can be interrupted before the message with the `value` slot is even returned - it's likely that emacs is getting bogged down either decoding the `value` slot or trying to render it all on a single line.
