### ISSUE TITLE
Add a function which returns the nrepl connection corresponding to a file

### ISSUE THREAD

**Issue by philc** [clojure-emacs/cider#453]
I edit multiple clojure projects in Emacs at once, and when evaling code in a file, I always want to use the project's nrepl connection, even if it's not the current default connection. `cider-switch-to-relevant-repl-buffer` can find the project's nrepl buffer, which is helpful, but it also switches focus to that buffer, which isn't what I want. Rather than customizing this function, it would be nice to be able to cleanly use the non-UI related functionality of that function.

Please build ui-related functions like `cider-switch-to-relevant-repl-buffer` on top of reusable building blocks. This will make it easy for others to make use of those building blocks for some work flows. To illustrate this point, here are two functions I've put together which I think are natural building blocks for some functions in cider.el. I'd rather cider.el expose these functions than having these live in my .emacs, and separating some of cider's UI logic from the underlying utility methods may improve the codebase.

    ;; Based on `cider-switch-to-relevant-repl-buffer` in cider.el.
    (defun nrepl-connection-for-buffer (buffer)
      "Returns either the corresponding nrepl buffer for the given buffer, or a string error message."
      (if (not (cider-connected-p))
          "No active nREPL connection."
        (let ((project-directory (nrepl-project-directory-for (nrepl-current-dir))))
          (if project-directory
              (let ((buf (car (-filter
                               (lambda (conn)
                                 (let ((conn-proj-dir (with-current-buffer (get-buffer conn)
                                                        nrepl-project-dir)))
                                   (when conn-proj-dir
                                     (equal (file-truename project-directory)
                                            (file-truename conn-proj-dir)))))
                               nrepl-connection-list))))
                (if buf
                    (get-buffer buf)
                  "No relevant nREPL connection found."))
            "No project directory found."))))

    (defun with-nrepl-connection-of-current-buffer (f)
      (let ((result (nrepl-connection-for-buffer (current-buffer))))
        (if (stringp result)
            (message result)
          (progn
            (cider-make-connection-buffer-the-current-connection result)
            ;; We could also restore the previous connection after we're done.
            (funcall f)))))

And all of my keybindings are of this form:

    (lambda () (interactive) (with-nrepl-connection-of-current-buffer 'cider-eval-expression-at-point))

Let me know what you think about refactoring the code a bit a long these lines, and I can submit a pull request which decompose a few functions into smaller, reusable chunks.

**Comment by Peeja** [comment]
It would make sense in my head to keep track of a "current" (default) connection for a buffer, just as there's now a default connection globally. (Ideally, I'd actually want everything in Cider to use *that* connection, and to see that connection in the modeline. `cider-rotate-default-connection` could then operate locally to rotate the *project*'s connection.)

**Comment by bbatsov** [comment]
> I'd actually want everything in Cider to use that connection, and to see that connection in the modeline

This is pretty much the case even now. After the ton of recent changes we did recently this ticket is obsolete (the current connection is determined from the current buffer anyways).

**Comment by Malabarba** [comment]
And for the record, the function to use is `(cider-current-connection)`.

**Comment by Peeja** [comment]
Oh, awesome, I'm just behind the times, then. Glad to hear it! :)
