### ISSUE TITLE
cider-jack-in not working (0.5.0)

### ISSUE THREAD

**Issue by dkincaid** [clojure-emacs/cider#459]
When I C-c M-j from a clojure-mode buffer I just get a blank _cider-repl_ buffer and a message in the minibuffer that says "Connecting to nREPL on localhost:47023

Pressing enter in that blank buffer gives the following:

Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  cider-repl--input-complete-p(nil 1)
  cider-repl-return(nil)
  call-interactively(cider-repl-return nil nil)

If I launch "lein repl" inside the project on the command line I am able to connect from cider to that running repl.

cider version is 0.5.0 (package: 20140124.1009)

**Comment by base698** [comment]
Broken for me using M-x cider-jack-in

**Comment by Malabarba** [comment]
@base698 it's probably a separate issue. Could you file a new issue with some description and a backtrace. (you can turn on backtraces with `M-x toggle-debug-on-error`).
