### ISSUE TITLE
cider-load-current-buffer always prompts to save the file if modified

### ISSUE THREAD

**Issue by cemerick** [clojure-emacs/cider#469]
I find this very annoying, as I'm frequently reloading a file interleaved with evaluating expressions, loading tests, or simply watching behaviour in another terminal or in a browser that automatically picks up the changes I'm loading in.

Would a patch that adds an option to control this prompting be accepted?

**Comment by danielcompton** [comment]
For future searchers, this has been [renamed](https://github.com/clojure-emacs/cider/commit/f42b26202fb8ae2df32f31e8a6ac93e697c48ae6#diff-e39c33031dc8d3e78b32ebee83293cd6R103) from `cider-prompt-save-file-on-load` to `cider-save-file-on-load` in CIDER [0.15.0](https://github.com/clojure-emacs/cider/releases/tag/v0.15.0).
