### ISSUE TITLE
The nrepl buffer doesn't scroll output into view after cider-find-and-clear-repl-buffer

### ISSUE THREAD

**Issue by philc** [clojure-emacs/cider#473]
Steps to repro:

1. Pull up two splits: a clj file and its nrepl buffer
2. Eval something in the clj buffer which prints to stdout
3. Invoke `cider-find-and-clear-repl-buffer`
4. Eval something again, and note that the nrepl buffer does not scroll the output into view.

I would expect the clojure process's output to be visible in the nrepl buffer without having to scroll it. As a workaround, I switch to the nrepl buffer, scroll up, and this puts the nrpel buffer in a state where future output will be visible.

**Comment by bbatsov** [comment]
@philc Is this still an issue?

**Comment by mtnygard** [comment]
I had a similar issue with scrolling, I traced it down to linum-mode which I had enabled via global-linum-mode. I disabled linum-mode for REPL buffers and no longer had any scrolling trouble.

**Comment by lotuc** [comment]
I encountered the similar problem, but trace down to issue #3219, just set `cider-repl-display-output-before-window-boundaries` to `t` if needed.
