### ISSUE TITLE
logging ends up in *nrepl* buffer instead of *cider*

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider#524]
With  `(use 'clojure.tools.logging)` 

```
  (info "blabla")
```

ends up in `*nrepl*` buffers instead of `*cider*`.

I have the following `log4j` configuration in `src/log4j.properties`:

```
log4j.rootLogger=DEBUG, stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.EnhancedPatternLayout
log4j.appender.stdout.Threshold=DEBUG
log4j.appender.stdout.layout.ConversionPattern=[%d{yyyy-mm-dd HH:mm:ss}{America/Los_Angeles}]%5p -- %m%n
```

 The problem doesn't occur with lein repl. Any ideas of how to redirect the output?

**Comment by iku000888** [comment]
@vspinu Thanks for reporting this issue. Saved me from confusion!
(And yes I do like that it get printed to the nrepl buffer as well.)

**Comment by henryw374** [comment]
did anyone work out how to configure logging to `*cider*` buffer?

**Comment by bbatsov** [comment]
@henryw374 See https://docs.cider.mx/cider/1.1/usage/code_evaluation.html#change-the-output-destination That works only if you're using `cider-nrepl`, though. If you search around there are several tickets where this is discussed in more details.

**Comment by henryw374** [comment]
thank you!
