### ISSUE TITLE
error in process filter: Wrong type argument: integerp, nil

### ISSUE THREAD

**Issue by noprompt** [clojure-emacs/cider#624]
I get this error whenever I type `#_`. Emacs will lock up and I'll have to type <kbd>C-g</kbd> to regain control. This showed up when I moved from `0.6.0` to `0.7.0alpha (package: 20140613.736)`. My `*Messages*` buffer contains the following:

```
error in process filter: cider-stacktrace-cycle-cause: Wrong type argument: integerp, nil
error in process filter: Wrong type argument: integerp, nil
```

Edit: Fix order of error messages

**Comment by siscia** [comment]
I do get the exact same error without autocomplete enabled.

Emacs version 24.5.1
Init: https://gist.github.com/siscia/f910e79a2998512d7265
