### ISSUE TITLE
cider-connect fails on first try

### ISSUE THREAD

**Issue by julienfantin** [clojure-emacs/cider#671]
I've had this issue for a while, where the first `cider-connect` invocation always hangs for a while and eventually errors with `error in process filter: Quit`, but the next invocation goes through.

```
CIDER 0.7.0snapshot (package: 20140721.1252) (Java 1.7.0_60, Clojure 1.6.0, nREPL 0.2.3, cider-nrepl 0.7.0-snapshot)
GNU Emacs 24.4.50.1 (x86_64-apple-darwin14.0.0, NS appkit-1326.11 Version 10.10 (Build 14A298i))
```

**Comment by agarman** [comment]
I am getting this error again:

Starting nREPL server via lein repl :headless...
...
nREPL: Direct connection established
progn: Sync nREPL request timed out (op describe id 3)

**Comment by agarman** [comment]
Issue was caused by nrepl-middleware being added.

Add the following to the leiningen profiles.clj to reproduce:
   :repl-options {
    :nrepl-middleware [io.aviso.nrepl/pretty-middleware]
  }

**Comment by neverfox** [comment]
@agarman Yes, that's what did it to me too. Did you find a solution?

**Comment by agarman** [comment]
@neverfox I didn't; I stopped using that middleware.

**Comment by neverfox** [comment]
@agarman Same. Instead I just inject `(install-pretty-exceptions)`.

**Comment by mattiasw2** [comment]
I have a similar problem, but instead I get 
      

> error in process filter: Wrong number of arguments: (0 . 0), 1

the first time from Emacs. The second time I succeed (I have get some zoombie java-processes I need to kill).
I am using Windows.

*Messages* looks like this:

> Parinfer extension lispy: It seems Lispy is not installed!
For information about GNU Emacs and the GNU system, type C-h C-a.
Making completion list...
Parinfer extension lispy: It seems Lispy is not installed!
Parinfer: Paren Mode, use C-, to switch to Indent Mode.
Making nrepl-create-client-buffer-function local to *nrepl-server sss4* while let-bound!
Making nrepl-use-this-as-repl-buffer local to *nrepl-server sss4* while let-bound!
Starting nREPL server via "c:/bin/lein.bat" update-in :dependencies conj ^"[org.clojure/tools.nrepl \^"0.2.12\^" :exclusions [org.clojure/clojure]]^" -- update-in :plugins conj ^"[cider/cider-nrepl \^"0.15.0-SNAPSHOT\^"]^" -- repl :headless...
nREPL server started on 51861
[nREPL] Establishing direct connection to localhost:51861 ...
[nREPL] Direct connection established
error in process filter: Wrong number of arguments: (0 . 0), 1 [2 times]
Mark set [2 times]

**Comment by PlumpMath** [comment]
error in process filter: nrepl-send-sync-request: Sync nREPL request timed out (op eval code
