### ISSUE TITLE
Cider documentation and navigation commands are non-standard and inefficient  

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/cider#699]
CIDER's documentation and navigation commands should not immediately act on symbol at point. The current behavior suffers from multiple flaws on which I elaborate with an example.

Assume you have typed `(reduce fun my-coll|)` where `|` denotes the cursor. Now you want the documentation for `reduce`. You automatically press `C-c C-d C-d` and you get an error because the doc for `my-coll` doesn't exist. You have a choice now, navigate to `reduce` and invoke the help again, or `C-u C-c C-d C-d`. Both of these choices enforce bad habits and increase cognitive burden. For some reason I tend to choose the first option, which is the worst.

So here is my personal list of why the current situation is bad:

- It makes you think hard before you invoke the command "Is the current symbol available? Is the current symbol that I need? Shall I press C-u or not?" most often you end up calling help twice.
  
- It enforces a bad habit of navigating to the symbol (I hate this one the most). 

- Most of the time you don't care about the symbol at point and you just want to quickly navigate to the doc/sourse/location independently of the current symbol, buffer or other contextual elements.
  
- It is inconsistent with standard emacs and documentation systems in other IDEs which ask the user before the jump.

- As it pops the choice menu only sometimes, depending on the complex context,  it feels aleatory, and thus goes against the principle of least surprise. 

- It creates conceptual problems. Are the doc commands acting on symbol, or on user input? What is the meaning of doc commands in other context than the code buffers? Does it make sense to have doc commands in docview buffers? Should the they act on a buffer in docview or on a symbol at point? Note, that all of these problems are automatically sorted out if you adopt an "act on user input" paradigm.

All of the above is simply because CIDER wants to be efficient and to avoid one <kbd>RET</kbd> press. But  instead it makes you feel that it "stays in your way".

The fix is to investigate the symbols at point and _always_ propose them as defaults. In the example above, both `reduce` and `my-coll` must be at the top of the completion list (in that order), so that people who are using IDO can see both of them and quickly select one of those or anything else.

(EDIT: added two more points)

**Comment by EricGebhart** [comment]
Here's a pull request to fix this.
https://github.com/clojure-emacs/cider/pull/1031

**Comment by danskarda** [comment]
Hi,

I would appreciate if you make this change optional or provide two kinds of functions (immediate and with prompt), which user can bind according his preferences.

It really disturbs my flow. I am used to point cursor to place in question and then press `M-.` to jump immediately to definition. I am sure where my "locus of attention" is and what I want to accomplish. However Cider now asks me - are you really, really sure? Which is kind of annoying for me and probably for other users as well. Emacs `elisp-find-definition` also works this way (no redundant questions).

I understand that exact behaviour depends on user long time habits (to prompt or not to prompt). Please support them, but do not impose them.

Thank you,
Dan

**Comment by vspinu** [comment]
> Emacs elisp-find-definition also works this way (no redundant questions).

Do you mean `find-definition`? If so, then it behaves like all other emacs completion functions, prompting first.

The inconvenience with the current implementation is that it doesn't provide completions like other emacs functions do. Hope it will be implemented soon.

**Comment by malcolmsparks** [comment]
+1 for not making commands ido-specific.

**Comment by bbatsov** [comment]
> +1 for not making commands ido-specific.

ido-specific? There's nothing ido-specific in the entire CIDER.

**Comment by malcolmsparks** [comment]
That's what I meant - I was indicating that there are people (like me) who don't use ido and so it's great that CIDER remains independent from it.

**Comment by bbatsov** [comment]
> That's what I meant - I was indicating that there are people (like me) who don't use ido and so it's great that CIDER remains independent from it.

And it will. I just didn't understand how this change relates to ido at all. Sure the prompt might look better with ido (arguably), but Emacs uses this convention all over the place, which was the reason this discussion started.

> It really disturbs my flow. I am used to point cursor to place in question and then press M-. to jump immediately to definition. I am sure where my "locus of attention" is and what I want to accomplish. However Cider now asks me - are you really, really sure? Which is kind of annoying for me and probably for other users as well. Emacs elisp-find-definition also works this way (no redundant questions).
> 
> I understand that exact behaviour depends on user long time habits (to prompt or not to prompt). Please support them, but do not impose them.

Sure, I understand your frustration and I was certain not everyone would like this change. (see the PR in question). We'll make this customizable one way or another. Obviously both approaches have their merits.

**Comment by dgutov** [comment]
@bbatsov You might want to read this discussion: http://lists.gnu.org/archive/html/emacs-devel/2015-04/msg01130.html

**Comment by bbatsov** [comment]
Thanks for the heads up. I probably will.
