### ISSUE TITLE
Supporting clojure.test/with-test

### ISSUE THREAD

**Issue by giorgio-v** [clojure-emacs/cider#707]
Would it be possible to extend Cider to support the `clojure.test/with-test` macro? 

Basically, I’d like to run tests defined in this way, too:
```
(test/with-test
  (defn hello [name]
    (str "Hello, " name))
  (is (= (hello "Brian") "Hello, Brian"))
  (is (= (hello nil) "Hello, ")))
```

Right now, these are not loaded because they are attached as meta data to the functions.

**Comment by bbatsov** [comment]
Btw, @jeffvalk any plans to work on this?

**Comment by jeffvalk** [comment]
I hadn't thought about it...but now that I am, I'm not sure why this doesn't work as is. I'll look at it.

**Comment by bbatsov** [comment]
Great!

**Comment by Malabarba** [comment]
>  I'm not sure why this doesn't work as is. I'll look at it.

My guess would be that `with-tests` adds the tests to the function metadata, which is on the current namespace. However, CIDER only ever runs tests from one namespace. So if there's also a namespace called `current.namespace-test`, then CIDER is only going to run tests from the latter.

Just a guess, though. :-)

**Comment by jeffvalk** [comment]
@Malabarba Yep, seems likely. If that's the case, running tests with `suppress-inference` should pick these up. And if that's true, this issue is already resolved.

**Comment by bbatsov** [comment]
Maybe. :-) Although we might have to account for tests being in the same namespace and in a test namespace (which shouldn't be hard to do).

**Comment by bbatsov** [comment]
Did someone check this?

**Comment by jeffvalk** [comment]
@bbatsov Yes. @Malabarba is right. And the forthcoming (very soon!) commit to add #1226 will close this issue.

**Comment by derekchiang** [comment]
@jeffvalk sorry if I missed something obvious, but how is this issue fixed?  As in, how exactly do I run the tests defined with `with-tests`?

**Comment by bbatsov** [comment]
`with-tests` adds some metadata that CIDER uses to know if something is a test that needs to be run or not. You can just use its functionality to run the tests in the current namespace.

**Comment by derekchiang** [comment]
@bbatsov but how exactly do you run the tests?  Neither `cider-test-run-ns-tests` nor `cider-test-run-test` works.

**Comment by bbatsov** [comment]
`C-c C-t C-n` has to be invoked with a prefix argument (`C-u`) to suppress namespace inference. Otherwise it will try to find some test namespace. Not sure why `cider-test-run-test` is not working for you, though. If a var has the right metadata it should work. Please, file a ticket for this.

**Comment by bbatsov** [comment]
Ah, I forgot about something - http://cider.readthedocs.io/en/latest/running_tests/

```If your individual tests are not defined by deftest or defspec, CIDER will not recognize them when searching for a test at point in cider-test-run-test. You can customize the variable  cider-test-defining-forms to add additional forms for CIDER to recognize as individual test definitions.
```
