### ISSUE TITLE
Rework the REPL to use comint

### ISSUE THREAD

**Issue by shosti** [clojure-emacs/cider#709]
This is a really small thing, but the current behavior for the CIDER repl is to always scroll to show maximum output. I don't really like this behavior, and it would be nice if it were configurable (I'm currently hacking around it by redefining `cider-repl--show-maximum-output`—let me know if there's already another way to turn this behavior off). A `cider-repl-show-maximum-output` variable would probably be enough, although it might be nice to have some more configuration options à la `comint`—what are your thoughts? (Also, are there any plans to eventually base `cider-repl-mode` off of `comint-mode`?) I'd be happy to put together a PR for this.

**Comment by bbatsov** [comment]
This important ticket is still looking for a volunteer to tackle it.

**Comment by GordonGustafson** [comment]
@vspinu did you have any unfinished work on this I should look at if I decide to take a crack at this? Or should I start by looking at ielm source and the comint documentation?

**Comment by johnbendi** [comment]
What about @shosti the OP who promised a PR?

**Comment by bbatsov** [comment]
I think that nobody actually got anywhere with this task, so @GordonGustafson can definitely start from scratch.

**Comment by vspinu** [comment]
@GordonGustafson, I haven't done anything concrete.

**Comment by shosti** [comment]
@GordonGustafson yeah, never got around to looking at this (as you can probably surmise).

**Comment by johnv02139** [comment]
I think basing it off of comint is a great idea, but for the record, for the main complaint, I added a defcustom in January, cider-repl-scroll-on-output, which can be set to nil to avoid the irritating scrolling.  I didn't see this issue at the time.

Is any work ongoing here to use comint?

**Comment by bbatsov** [comment]
To my knowledge no one is working on this, so without a volunteer to push it forward it's not going to happen any time soon.

**Comment by vspinu** [comment]
I am not even convinced that it's worth anymore Comint is old and rigid which makes it hard to build a richer interfaces on top of it. So, IMO, if there is ever an effort in this direction, it should be better spent on building a new comint system from scratch.

**Comment by johnv02139** [comment]
I would agree it doesn't seem worth reimplementing.  I think your (@vspinu) original message made more sense, i.e., "use comint customization variables."  I would think we could use the variables and emulate the behavior without sharing implementation.

**Comment by bbatsov** [comment]
OK, I'll close this ticket then. We've got more important tasks to do anyways.
