### ISSUE TITLE
Stacktrace buffer improvements

### ISSUE THREAD

**Issue by hugoduncan** [clojure-emacs/cider#714]
Firstly, the new stacktrace buffer is in general a huge improvement, over the last release!

a) I would like however to be able to see exception messages for all causes by default.  At present the nearest thing possible is to set `cider-stacktrace-cause-visibility` in a `cider-stacktrace-mode` hook.  With the detail levels currently defined, it is however impossible to display only the message (which is usually at most a few lines), and not the data (which can be voluminous).  Would it be possible to put the message and data in different levels?  I'm not sure if it would be best to move the message to level 0, or to add a new level for it on it's own.  I also think that this behaviour deserves a defcustom rather than relying on hooks.

b) When viewing the a cause, would it be possible to make pressing `RET` cycle the detail level?

c) When an exception is displayed, the point is currently set to the end of the buffer.  Is this intentional?  Libraries can go to some lengths to wrap exceptions with meaningful messages, which often means that the outer exception (at the top of the buffer) is the most informative

I'm also wondering what will happen when there are more than 10 causes -- guess I'll find out sooner or later.

**Comment by bbatsov** [comment]
@jeffvalk Are we going to do something about this or not?

**Comment by jeffvalk** [comment]
Yeah. It's reasonable.

**Comment by gganley** [comment]
Has this been fixed at some point between 2016 and now? Commands such as `cider-stacktrace-cycle-cause-{1-5}` exist now, was that the point of this issue?
