### ISSUE TITLE
Allow jumping to source file,line and column for compilation errors

### ISSUE THREAD

**Issue by tbatchelli** [clojure-emacs/cider#715]
When a compilation error happens, the error message from the compiler contains the file, line and column of the error. This appears on the stacktrace buffer, but I couldn't find any way to jump from the stacktrace to the actual error, as the offending source does not appear in any of the frames.

The feature request would be to identify compilation errors and get the information about the file and position within the file from the error message. Then turn that information into a link to the right buffer and position within the buffer.

Here is an example:

```

  Show: Clojure Java REPL Tooling Duplicates All  (47 frames hidden)

2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling:
   /Users/tbatchelli/dev/palletops/admin-user-crate/src/pallet/crate/admin_user/admin_user.clj:249:41

                 Compiler.java: 7137  clojure.lang.Compiler/load
                          REPL:    1  user/eval18774
                 Compiler.java: 6703  clojure.lang.Compiler/eval
                 Compiler.java: 6666  clojure.lang.Compiler/eval
                      core.clj: 2927  clojure.core/eval
                      main.clj:  239  clojure.main/repl/read-eval-print/fn
                      main.clj:  239  clojure.main/repl/read-eval-print
                      main.clj:  257  clojure.main/repl/fn
                      main.clj:  257  clojure.main/repl
                   RestFn.java: 1096  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   56  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  624  clojure.core/apply
                      core.clj: 1862  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   41  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  171  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                      core.clj: 2402  clojure.core/comp/fn
        interruptible_eval.clj:  138  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
       ThreadPoolExecutor.java: 1145  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  615  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run

1. Caused by java.lang.RuntimeException
   Invalid token: sudoers/

                     Util.java:  221  clojure.lang.Util/runtimeException
               LispReader.java:  316  clojure.lang.LispReader/interpretToken
               LispReader.java:  209  clojure.lang.LispReader/read
               LispReader.java: 1147  clojure.lang.LispReader/readDelimitedList
               LispReader.java:  972  clojure.lang.LispReader$ListReader/invoke
               LispReader.java: 1138  clojure.lang.LispReader/readDelimitedList
               LispReader.java: 1081  clojure.lang.LispReader$MapReader/invoke
               LispReader.java: 1138  clojure.lang.LispReader/readDelimitedList
               LispReader.java: 1081  clojure.lang.LispReader$MapReader/invoke
               LispReader.java: 1138  clojure.lang.LispReader/readDelimitedList
               LispReader.java:  972  clojure.lang.LispReader$ListReader/invoke
               LispReader.java: 1138  clojure.lang.LispReader/readDelimitedList
               LispReader.java:  972  clojure.lang.LispReader$ListReader/invoke
               LispReader.java:  183  clojure.lang.LispReader/read
                 Compiler.java: 7126  clojure.lang.Compiler/load
                          REPL:    1  user/eval18774
                 Compiler.java: 6703  clojure.lang.Compiler/eval
                 Compiler.java: 6666  clojure.lang.Compiler/eval
                      core.clj: 2927  clojure.core/eval
                      main.clj:  239  clojure.main/repl/read-eval-print/fn
                      main.clj:  239  clojure.main/repl/read-eval-print
                      main.clj:  257  clojure.main/repl/fn
                      main.clj:  257  clojure.main/repl
                   RestFn.java: 1096  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   56  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  624  clojure.core/apply
                      core.clj: 1862  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   41  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  171  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                      core.clj: 2402  clojure.core/comp/fn
        interruptible_eval.clj:  138  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
       ThreadPoolExecutor.java: 1145  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  615  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run
```

**Comment by expez** [comment]
ping @jeffvalk :)

**Comment by bbatsov** [comment]
Anyone willing to work on this?

**Comment by j-mckitrick** [comment]
Hey Bug @bbatsov 

We met at ClojureConj last year.  This would be my first task on Cider, but if you think it could be done with a little coaching, I'm willing to give it a shot.

**Comment by bbatsov** [comment]
Sure thing!

**Comment by j-mckitrick** [comment]
So.... after the obvious RTFM/Wiki/Developers setup stuff, where should I
start?

**Comment by bbatsov** [comment]
https://github.com/clojure-emacs/cider/blob/master/cider-stacktrace.el#L149

Simply put you need to implement a command that would fetch the location at point (on Return & mouse click) and take you to this file/line/column. You can see something similar here https://github.com/clojure-emacs/cider/blob/master/cider-browse-ns.el#L50

**Comment by j-mckitrick** [comment]
My first thought is to use a regex to get the line number, and go to the
location from there.  But I'm sure it's not that simple.  What else do I
need to be aware of?

**Comment by bbatsov** [comment]
Actually, probably it's as simple as this (unless there's some metadata attached to all stack frames). Without consulting the code I can't be sure. @jeffvalk How does this sound to you?

**Comment by jeffvalk** [comment]
@expez Sorry I didn't see your earlier ping! :)

@bbatsov Yes, this should be pretty simple indeed. In fact, there's a cleaner way than digging it out with a regex.

@j-mckitrick The code you want is [here](https://github.com/clojure-emacs/cider-nrepl/blob/1e3de74c06e154b9fb57a81f07b01deb698f988d/src/cider/nrepl/middleware/stacktrace.clj#L106). The way it works now, `analyze-cause` is called on each `Exception`, returning a map of its info; then `extract-location` is called on that map.

If you either return the `Exception` object in the map, or reverse the order in which those functions are called [here](https://github.com/clojure-emacs/cider-nrepl/blob/1e3de74c06e154b9fb57a81f07b01deb698f988d/src/cider/nrepl/middleware/stacktrace.clj#L142), you can update the `extract-location` function to also grab the file `.source` and `.line` fields directly from the [CompilerException](https://github.com/clojure/clojure/blob/35563c1d64406ce9c57e93a3d1d83cbd0a21bbab/src/jvm/clojure/lang/Compiler.java#L6554). (As an aside, the compiler has column info too, but doesn't expose it. I always found that odd.) Thanks for picking this up!

**Comment by jeffvalk** [comment]
Following up on that aside -- if you want to jump to the column, not just the line (which would be quite helpful for compiler exceptions), you will need to use a regex. In this case, ignore the implementation details above. The `extract-location` function is the only thing you'll need to update.

**Comment by j-mckitrick** [comment]
So now the next questions....  I checked the Wiki, and I don't see any
instructions for development setup.  I'm running the ELPA version of CIDER,
and the 0.10.0 snapshot of cider-nrepl.  It looks like I might need to make
changes in both CIDER and the backend as well.

**Comment by bbatsov** [comment]
Nothing special is needed. Just start CIDER as usual and make changes to the Elisp (and/or middleware) code you've cloned separately. When you evaluate something you've changed in the Elisp or Clojure code it will simply replace whatever was loaded until then. The classic interactive Lisp workflow.

**Comment by j-mckitrick** [comment]
So according to this
<https://github.com/clojure/clojure/blob/35563c1d64406ce9c57e93a3d1d83cbd0a21bbab/src/jvm/clojure/lang/Compiler.java#L6554>
the column of the exception is not actually included retained in the Java
object for the CompilerException.  I assume we won't be changing Clojure
itself to add the column, correct?  ;-)

**Comment by bbatsov** [comment]
You're right. :-)

**Comment by j-mckitrick** [comment]
So that means we need to go with the original approach, which will use only
.source and .line, correct?

**Comment by bbatsov** [comment]
Yep.

**Comment by j-mckitrick** [comment]
So it seems the source, line and column are actually embedded in the
message from the exception:

https://github.com/clojure/clojure/blob/35563c1d64406ce9c57e93a3d1d83cbd0a21bbab/src/jvm/clojure/lang/Compiler.java#L6741
