### ISSUE TITLE
No stack trace or output when a test throws an Exception

### ISSUE THREAD

**Issue by moea** [clojure-emacs/cider#731]
``` clojure
(deftest example
  (throw (Exception.)))
```

When invoked with `cider-test-run-tests` causes the following minibuffer message: `error in process filter: End of buffer`.  This is with Cider `20140812.953`, and cider-nrepl `0.8.0-SNAPSHOT` (also `0.7.0-SNAPSHOT`, and a version I built from yesterday's head revision).

I'm running Emacs `24.4.50`.  A colleague is seeing this behaviour with `24.3`.  

When I `toggle-debug-on-error`, I rather get the message `save-excursion: End of buffer`, with no stacktrace or anything (I'm pretty new to Emacs, I don't know if this is helpful).

This sounds pretty similar to #648 - though the fix for that issue doesn't seem to help.

**Comment by jacobemcken** [comment]
I think I've experience this when loading a test namespace and the deleting a `deftest`. Afterwards I would get the error `error in process filter: End of buffer`.
Reinserting the `deftest` makes the above error go away.

Using `CIDER 0.8.2 (Java 1.8.0_31, Clojure 1.6.0, nREPL 0.2.6)`
I hope this observation can be of use :smile:
