### ISSUE TITLE
Restore clojure-test-mode jump-between-tests-and-code behavior

### ISSUE THREAD

**Issue by ikbrunel** [clojure-emacs/cider#734]
`cider-test.el` defines `C-c C-t` as `cider-test-jump`, where `clojure-test-mode` had `clojure-jump-between-tests-and-code`.

I'd like to implement a but of elisp to provide `cider-jump-between-tests-and-code` using `cider-test-infer-test-ns` and the `clojure-test-mode` `clojure-in-tests-p` pattern. Would anyone else find this useful, and is there support for restoring `C-c C-t` to the old behavior?

**Comment by arichiardi** [comment]
Cause of (this)[https://github.com/dnaumov/midje-mode/issues/34] as well.
@bbatsov Please, can you point me to ```projectile```'s way to do this so that I can see if it's worth change ```midje-mode``` ?

**Comment by bbatsov** [comment]
See https://github.com/bbatsov/projectile/blob/master/projectile.el#L1617

We'll probably need to have two types of `lein` projects - `lein-test` and `lein-midje` (we have something similar for Rails).

**Comment by arichiardi** [comment]
Ok great I am checking, it should be the same suffix as normal tests, but I will need to apply [this commit](https://github.com/luckykevin/midje-mode/commit/795d0c0e0650ce352cd9ac94704a0b8405d66fb9) instead.

**Comment by arichiardi** [comment]
No ok, I need to replace, the functionality [here](https://github.com/dnaumov/midje-mode/blob/master/clojure-jump-to-file.el). I guess I just need to add what you say @bbatsov.
What about tests and contributions? I am not very familiar about ```projectile``` and ```elisp``` but this looks a very easy fix...

**Comment by arichiardi** [comment]
Implemnted @ bbatsov/projectile#758
