### ISSUE TITLE
Weird `read-line` behaviour

### ISSUE THREAD

**Issue by luxbock** [clojure-emacs/cider#736]
I'm using the latest snapshot version of cider. When I run `(read-line)` in the REPL, I get prompted for input, after which the function hangs and I have to use `C-c C-c` to abort it. The next time I cal `(read-line)` again the function returns immediately with the input I gave it the last time around. 

If I repeat the same thing in a REPL launched by `lein repl` in the console then everything works as expected.

**Comment by freckletonj** [comment]
weird, I'm having this same error in the most recent cider right now, but not `lein repl`.

restarting cider repl...

at first glance, it's working in cider's repl...
and from a file...

weird. restarting helped, but I thought I'd at least echo that I still experienced the same error 1.5 yr later!

Thanks for Cider btw, I love it!

**Comment by p-adams** [comment]
I am also getting the same error.

**Comment by sabjohnso** [comment]
I am experiencing the same problem under certain conditions: `read-line` reads input correctly from input until I use `C-c C-c` to abort evaluation of `read-line`.  Following that, `read-line` behaves as reported by luxbock. 

---version info---
emacs 24.5.1
CIDER 0.15.0snapshot (package: 20161201.757), nREPL 0.2.12
Clojure 1.8.0, Java 1.8.0_112
