### ISSUE TITLE
Stack Traces in *cider-error* buffer don't honor background color, hard to read with dark themes

### ISSUE THREAD

**Issue by tbatchelli** [clojure-emacs/cider#742]
See this:
![_cider-repl_127_0_0_1_](https://cloud.githubusercontent.com/assets/27665/4003280/2184fa62-2975-11e4-96e3-e7b45f57d935.png)
I have tried to change the background on cider-stacktrace-face but it's not honored.

**Comment by agzam** [comment]
Do you guys know how can I change background of exception messages. In Obsidian color theme they look pretty lame
![screenshot]
(http://i.imgur.com/RrqfCe3.png)

**Comment by expez** [comment]
> In Obsidian color theme they look pretty lame

The maintainer of the Obisidian color theme might be better able to answer this question.  IIRC we just re-use `font-lock-warning-face` for this purpose.
