### ISSUE TITLE
customize indentation

### ISSUE THREAD

**Issue by johnbendi** [clojure-emacs/cider#747]
How can I customize the indentation behavior of cider to give me something like :

``` lisp
(dom/div nil
  (dom/p nil))
```

rather than :

``` lisp
(dom/div nil
         (dom/p nil))
```

Is there a way of making cider aware of it's context when indenting, something I can easiily customize?

**Comment by danielsz** [comment]
Isn't there a way to achieve this with the new indent policy on var metadata?

https://github.com/clojure-emacs/cider/commit/851724e247c95c3d083b451f4b3e6093b031df5d

**Comment by Malabarba** [comment]
@danielsz The ideal way would be to define the dom functions with the :style/indent metadata directly in the library. This way everyone using cider (and eventually other editors) would have the right indentation. That's as simple as writing something like 

```clj
(defn div 
  {:style/indent 1} 
  [args...] 
  ...) 
```

If that's not an option (if the maintainer of the library doesn't want to do this), then you (the user) can still customize this on your project by changing the metadata of these functions yourself. If memory serves, you can do that by using `alter-var-metadata` somewhere in the code.

**Comment by danielsz** [comment]
@Malabarba Thank you.

In the case of the dom tags provided by Om, it is a bit daunting.
The tags are defined in a vector: 
```clojure
(def tags
  '[a
    abbr
    address
    area
    ...])
```

Then macros transform those:

```clojure
(defn ^:private gen-react-dom-fn [tag]
  `(defn ~tag [opts# & children#]
     (.apply ~(symbol "js" (str "React.DOM." (name tag))) nil
       (cljs.core/into-array
         (cons opts# (cljs.core/map om.util/force-children children#))))))

(defmacro ^:private gen-react-dom-fns []
  `(do
     ~@(clojure.core/map gen-react-dom-fn tags)))
```

I'm not sure how to proceed.

**Comment by Malabarba** [comment]
> This looks nice:
> 
> ```clj
> (defn ^:private gen-react-dom-fn [tag]
>   `(defn ~tag [opts# & children#]
>      {:style/indent 1}
>      (.apply ~(symbol "js" (str "React.DOM." (name tag))) nil
>        (cljs.core/into-array
>          (cons opts# (cljs.core/map om.util/force-children children#))))))
> ```

I think the first thing to do is to open a PR over at OM politely explaining what this does. The developer might just be OK with adding it.

The `:style/indent` spec is only going to be useful if people use it, so we should start spreading the word. :-)

> But I don't know how to override that function outside of the library. 

If this doesn't get added directly to the library, I think you can do the following directly in your code:

```clj
(map #(alter-meta! (second %) assoc :style/indent 1)
     (ns-publics 'om.dom))
```

though I didn't test it in ClojureScript.

**Comment by levitanong** [comment]
> ```clj
(map #(alter-meta! (second %) assoc :style/indent 1)
     (ns-publics 'om.dom))
```

Is unlikely to work (or ever work) because of https://groups.google.com/forum/#!topic/clojure/IYopjj922IU

😢

**Comment by Liverm0r** [comment]
cider-format-buffer seems to ignore style/indent metadata
