### ISSUE TITLE
Evaluating multiple sexps that throw leads to garbled stacktrace

### ISSUE THREAD

**Issue by hugoduncan** [clojure-emacs/cider#753]
It is sometimes expedient to enter mutliple sexps at once at the repl.  This leads to a garbled stacktrace if more than one of the sexps throws.

e.g. evaluating the following in a single line at the repl causes two "1" causes and a stacktrace as exception message:

```clj
(throw (ex-info "hello" {})) (throw (ex-info "there" {}))
```

**Comment by bbatsov** [comment]
@jeffvalk ping :-)

**Comment by jeffvalk** [comment]
@bbatsov So I've been, um, less than timely on this. :-) Mea culpa. The past few months have had me doing everything but writing code. Such is life in a start-up. I'll carve out some time shortly.

**Comment by bbatsov** [comment]
@jeffvalk Gotcha. I've changed jobs recently myself and have had little time for OSS projects lately.
