### ISSUE TITLE
cider-test-run-tests fails to run tests unless tests are in a -test.clj file

### ISSUE THREAD

**Issue by hugoduncan** [clojure-emacs/cider#784]
When trying to run clojure.test tests in a namespace that doesn't end in `-test`, `cider-test-run-tests` tries to locate the namespace named by the current buffer with `-test` appended.

This makes it unusable in such buffers.   `leiningen`'s tests do not follow this expected naming scheme for example.

**Comment by nicolasGuillouet** [comment]
ok, fine but how do you customize it ? I would like the same behavior as before : running the current test file with ```C-c ,```

**Comment by nicolasGuillouet** [comment]
```(setq cider-test-infer-test-ns (lambda (ns) ns))``` is the best way ?

**Comment by bbatsov** [comment]
> (setq cider-test-infer-test-ns (lambda (ns) ns)) is the best way ?

Looks good to me, although by doing this you won't be able to run the tests from ns they are related to.

**Comment by nicolasGuillouet** [comment]
I agree, perhaps it should be more useful to run from the related ns. I did like this because the previous behavior ...
Thanks

**Comment by felipegmarques** [comment]
Hi, I'm trying to set my `cider-test-infer-test-ns`, but I'm not sure where I should do. I'm using spacemacs.

Thanks, and sorry for the basic question.
