### ISSUE TITLE
cider-jack-in fails with `error in process filter: error during connect: connection timed out`

### ISSUE THREAD

**Issue by jauhien** [clojure-emacs/cider#794]
Subj., while cider-connect works.

cider-connect works both for extern repl and repl started by failed cider-jack-in.

How can I debug cider to give you some usefull output?

Cider version: 0.7.0, installed from melpa-stable. The same error occured with snapshots installed from melpa.

**Comment by agarman** [comment]
I'm getting this error as of March 6, 2015

From *Messages*
Starting nREPL server via lein repl :headless...
nREPL server started on 50774
nREPL: Establishing direct connection to localhost:50774 ...
nREPL: Direct connection established
error in process filter: progn: Sync nREPL request timed out (op describe id 3)
error in process filter: Sync nREPL request timed out (op describe id 3)

Using leiningen 2.5.1
Cider 0.8.1

**Comment by agarman** [comment]
Issue was caused by nrepl-middleware being added.

Add the following to the leiningen profiles.clj to reproduce:
   :repl-options {
    :nrepl-middleware [io.aviso.nrepl/pretty-middleware]
  }
