### ISSUE TITLE
Clojurescript hook

### ISSUE THREAD

**Issue by danielsz** [clojure-emacs/cider#798]
Hi,

I'm writing an Emacs minor mode that makes sense only for Clojurescript. 
Is there a hook I can use for this case?

**Comment by bbatsov** [comment]
Totally forgot about this ticket. Adding a hook based on the filename would be easy indeed, and I guess it has to be run only if there's actually a clojurescript connection present. @cichli, perhaps you'd like to take a stab at this?

**Comment by expez** [comment]
closing in favor of creating a major-mode for `cljs` derived from `clojure-mode`.
