### ISSUE TITLE
trampoline from cider

### ISSUE THREAD

**Issue by johnbendi** [clojure-emacs/cider#835]
Please how can I do trampoline from cider? I already tried setting the environment variable `$LEIN_FAST_TRAMPOLINE='y'` but leiningen still hangs around in memory. What is the right way to do this when using cider to start leiningen. I also tried putting `:eval-in :trampoline` in project.clj which made cider throw errors.

**Comment by michaelmrose** [comment]
How about adding trampoline to cider-lein-parameters

**Comment by eggsyntax** [comment]
@bbatsov I know this is a closed issue, but can you tell me what command `C-u C-c M-j` is bound to? Alternately, and much more generally useful, is there a way, from evil mode, to find out what a key sequence would be bound to *if* you were in holy mode? Thanks!

**Comment by dpsutton** [comment]
@eggsyntax 
    (defun cider-load-buffer-and-switch-to-repl-buffer (&optional set-namespace)
      "Load the current buffer into the matching REPL buffer and switch to it.
    When SET-NAMESPACE is true, we'll also set the REPL's ns to match that of the
    Clojure buffer."
      (interactive "P")
      (cider-load-buffer)
      (cider-switch-to-repl-buffer set-namespace))

is the function its bound to. It just loads buffer and if prefix sets the namespace to the newly loaded buffer

**Comment by eggsyntax** [comment]
Hey @dpsutton! LOL at the PS -- anytime :). Thanks for the info.

**Comment by bbatsov** [comment]
I aimed for `cider-jack-in`, which asks you for the command to invoke with a prefix argument.

**Comment by eggsyntax** [comment]
Oh, ok, that makes sense. Thanks!
