### ISSUE TITLE
cider-repl not showing all output

### ISSUE THREAD

**Issue by cschol** [clojure-emacs/cider#906]
; CIDER 0.8.2snapshot (package: 20141128.907) (Java 1.7.0_65, Clojure 1.6.0, nREPL 0.2.6)

I am running the "Hello World" example from the Langohr [website](http://clojurerabbitmq.info/articles/getting_started.html) when executing `(-main)`.

Using `lein repl` everything works as expected and the `[consumer] Received a message...` message is shown in the console.

Using `cider` the `println` statements (`[main] Connected...`, `[main] Disconnecting...`) are shown, but the output from the handler (`[consumer] Received...`) is not shown in the `*cider-repl-messenger*` buffer. However, the output is present in the `*nrepl-server-messenger*` buffer.

Is there any reason why the output from the handler is not shown in the `*cider-repl-messenger*` buffer?

**Comment by creese** [comment]
Having the same issue. Output from the consumer shows up in the server buffer but not in the repl. I'm using the topic exchange example described here:
http://clojurerabbitmq.info/articles/getting_started.html#weathr:-many-to-many

If I want the repl to display this output, is a fix needed for cider, or is there something I can change in the code?

**Comment by bbatsov** [comment]
This has to be fixed in cider. See [this lengthy discussion](https://github.com/clojure-emacs/cider/pull/818) for more details.

**Comment by bbatsov** [comment]
This was fixed in 0.10 with the introduction of the `out` nREPL middleware.
