### ISSUE TITLE
I would like to automatically do the namespace setting on jack-in

### ISSUE THREAD

**Issue by nicferrier** [clojure-emacs/cider#919]
Why do I have to do cider-jack-in and then C-c M-n? My fingers hurt. I just want to do one thing and have it setup. If I switch files maybe I'd be happy to change the namespace.

It seems this is a matter of getting nrepl to understand where it came from. It seems doable to me but it also seems obvious. Which makes me think there's a reason it hasn't been done?

**Comment by nicferrier** [comment]
So I still don't know how to do this and am looking to emacs to make it happen again.

**Comment by bbatsov** [comment]
cider-jack-in will prompt for the command to execute when invoked with a prefix argument.

**Comment by pbostrom** [comment]
@nicferrier Here is some elisp to do what you want:
```elisp
(defun cider-ji-and-switch-ns ()
  (interactive)
  (cider-jack-in)
  (add-hook 'nrepl-connected-hook
    (lambda ()
      (cider-switch-to-last-clojure-buffer)
      (cider-repl-set-ns (cider-current-ns))
      (cider-switch-to-repl-buffer))))
```
Then I mapped this to C-c M-y:
`(define-key clojure-mode-map (kbd "C-c M-y") 'cider-ji-and-switch-ns)`

**Comment by bbatsov** [comment]
@pbostrom I think it'd be better if something like this was implemented in terms of a config option. Something similar can be done about jumping from a source file to the REPL in general, but I'm not sure how many people have a "compatible" workflow.

**Comment by vspinu** [comment]
> Here is some elisp to do what you want:

Please use `cider-connected-hook` instead of nrepl hook for such things. Nrepl will son be used for other projects besides cider. 

Also hooks are better to be added outside interactive functions.

**Comment by bbatsov** [comment]
@expez Booting to the REPL of the current buffer would be somewhat useful, so I was actually planning to do this some day.
