### ISSUE TITLE
Boot build tool compatibility

### ISSUE THREAD

**Issue by pandeiro** [clojure-emacs/cider#920]
The `cider-jack-in` command, hallowed be its name (and shortcut), will unfortunately **not** boot up a REPL and attach a client to it in projects that use [Boot](http://boot-clj.com/) instead of Leiningen. This is unsurprising, given the predominance of lein, but boot support would be nice and, looking into it, the issues at play are simple and mostly confined to nrepl-client.el. Basically, they are:

1. `nrepl-project-directory-for` needs to recognize `build.boot` in addition to `project.clj` files.
2. `nrepl-server-filter` would need to adjust its regex to accept both lein's "nREPL server started on..." and boot's "nREPL server listening..." outputs

This would enable barebones support, with users using customization to specify "boot" as `cider-lein-command` and "repl -s wait" as `cider-lein-parameters`.

However... in the future, perhaps **detection by cider for the appropriate defaults for those values on a per-project basis** would be convenient to end users.

Question: would a pull request to implement the two immediate simple changes above be welcome? Or, is there any orientation in general on this question?

Thanks

**Comment by bbatsov** [comment]
@cichli Yeah, that'd be great.

@pandeiro Any progress with this?

**Comment by pandeiro** [comment]
@bbatsov I've got a branch with boot support working and the existing tests passing.

I haven't added any tests b/c I couldn't find `cider-jack-in` specific tests to expand. (TBH I could use some help with that, if you find it necessary.)

My work is [here](https://github.com/pandeiro/cider/commit/180467981a6ef8eeadd6e0802bb4a51e8183f1ed). Let me know if I should submit the PR as-is or if it needs more work, please?

**Comment by pandeiro** [comment]
@cichli Not sure how that would work, exactly... Would cider, if boot were detected, inject something into build.boot? That seems heavy on the magic to me.

Isn't the recommended method, a `$HOME/.profile.boot` with the cider-nrepl dependency, akin to `$HOME/.lein/profiles.clj`, good enough? No?

Or is there another way I'm not seeing?

**Comment by pandeiro** [comment]
@bbatsov Looking at your line comments now; there is one further issue -- anecdotally it seems some projects have a project.clj and build.boot to facilitate use with either tool. Don't know how prevalent that is/will become, but how would you propose dealing with that? Ie, should cider maybe somehow allow the user to specify the jack-in command to use, as C-u cider-jack-in currently allows the user to select a project? Thoughts?

**Comment by bbatsov** [comment]
If both files are present we should prompt the user for input.

On Tuesday, January 13, 2015, Murphy McMahon <notifications@github.com>
wrote:

> @bbatsov <https://github.com/bbatsov> Looking at your line comments now;
> there is one further issue -- anecdotally it seems some projects have a
> project.clj and build.boot to facilitate use with either tool. Don't know
> how prevalent that is/will become, but how would you propose dealing with
> that? Ie, should cider maybe somehow allow the user to specify the jack-in
> command to use, as C-u cider-jack-in currently allows the user to select a
> project? Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/920#issuecomment-69823894>.
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by pandeiro** [comment]
OK that would be a completing read for 'lein' or 'boot'?

**Comment by bbatsov** [comment]
Yep.

On Wednesday, January 14, 2015, Murphy McMahon <notifications@github.com>
wrote:

> OK that would be a completing read for 'lein' or 'boot'?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/920#issuecomment-69829875>.
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com
