### ISSUE TITLE
Cannot jump to tests from test report

### ISSUE THREAD

**Issue by llasram** [clojure-emacs/cider#921]
Invoking `cider-test-jump` from the test report (as default-bound to `t`) does not jump to the test.  Instead it just always yields the message 'Symbol SYMBOL not resolved', where SYMBOL is whatever symbol is under point.

Commit b1304515 appears to have broken non-interactive calls to `cider-jump-to-var`, where `cider-test-jump` seems to contain the only such instance in CIDER proper.  I'm willing to write a PR to fix this, but I'm not sure which is correct approach: (1) fix `cider-jump-to-var` to once more support non-interactive invocation, (2) fix `cider-test-jump` to e.g. use `cider--jump-to-loc-from-info` directly, or (3) both.

Thanks!

**Comment by bbatsov** [comment]
@llasram How's that PR coming along? :-)

**Comment by llasram** [comment]
Opened.  I was looking into Emacs integration testing, but then the US holiday season ended and I'm back to my primary projects.  So no integration tests yet, but at least this feature restored.

**Comment by bbatsov** [comment]
Guess we can open a separate ticket dedicated to integration tests. I think the `clj-refactor` has some (and it has a similar structure - elisp + middleware), so we can borrow a bit of know-how from them.

**Comment by expez** [comment]
Actually we never could get integration tests with ecukes to work.  We're mocking out responses from the middleware instead, which is far less useful imo.  

My recommendation is to stay away from ecukes and just write integration tests using `ert`.
