### ISSUE TITLE
jump doesn't work in prefix vectors

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#925]
Let `|` indicate the cursor:

```clj
(ns refactor-nrepl.test-namespace
  (:require [clojure.test :refer :all]
            [refactor-nrepl.ns
             [clean-ns :refer [clean-ns read-ns-form]]
             [he|lpers :refer [get-ns-component]]]
            [refactor-nrepl.ns.pprint :refer [pprint-ns]])
  (:import java.io.File))
```

If I try to jump to the `helpers` namespace I'm out of luck.  I took a quick look at how to fix this, but there are no obvious extension points for this.  I'm not sure we should encumber `cider-symbol-at-point` with `cider-in-prefix-vector-p` and `cider-add-prefix-vector-prefix`.

Is this even worth fixing?

\<aside\>
why have `cider-jump-to-var` and `cider-jump-to-resources` instead of a `cider-jump-dwim`?  Surely we can spot the difference between a resource and a var and reduce the cognitive load for the user slightly?
\</aside\>

\<aside\>
Would it be possible to underline resources we've successfully found on the classpath?  Intellij does this for java sources to help you catch spelling errors and to indicate that a jump point is available.
\</aside\>

**Comment by bbatsov** [comment]
> Is this even worth fixing?

Not sure how complex such a fix might be.

> why have cider-jump-to-var and cider-jump-to-resources instead of a cider-jump-dwim? Surely we can spot the difference between a resource and a var and reduce the cognitive load for the user slightly?

Yeah, guess something like this makes sense. One less keybinding is one less keybinding. On the other hand we have to consider alternative usages of such commands (e.g. prompting for var/resource).

> Would it be possible to underline resources we've successfully found on the classpath? Intellij does this for java sources to help you catch spelling errors and to indicate that a jump point is available.

It will be possible, but it will require a timer going though all the strings from time to time. Not sure how much value would there be in such a feature.

**Comment by expez** [comment]
After the changes to the jump functionality a while back, where the thing at point is used as the candidate suggestion instead of the trigger for the jump, I no longer see the need for this.  Furthermore we've added `cider-jump-to-ns` which is a much better solution to this problem, than moving the cursor into the ns form an attempting to jump.

**Comment by Malabarba** [comment]
I'm confused. I've always used jump to Var for everything. What does it not work on?

**Comment by expez** [comment]
@Malabarba  In the OP you can see I had the cursor on the `helpers` namespace and attempted to jump.  Back in the day you wouldn't get a prompt, it would just fail when it couldn't jump to a symbol named `helpers`.
