### ISSUE TITLE
Company:Back-end company-capf error

### ISSUE THREAD

**Issue by CraneHuang** [clojure-emacs/cider#933]
I use company-mode (0.8.7) in cider.Every time I restart the cider repl and type some codes,the emacs will be stuck for a while and then it works well.And sometime there's an error that's "back-end company-capf error".For more,you can see the picture below:
![2014-12-23 08 27 35](https://cloud.githubusercontent.com/assets/5162826/5575519/30a53c1c-901a-11e4-8e3d-d94346c90b32.png)
for more,I use Ubuntu 14.04LTS and emacs 24.4.
BTW , I had reported the issue to the Company repo , the maintainer told me report it here.

**Comment by bbatsov** [comment]
Please, share with us your CIDER version info as well.

**Comment by CraneHuang** [comment]
CIDER 0.8.2   company 0.8.7

**Comment by bbatsov** [comment]
Can you reproduce this on the latest 0.9-snapshot?
