### ISSUE TITLE
Namespace not found upon evaluation attempt 

### ISSUE THREAD

**Issue by aaelony** [clojure-emacs/cider#938]
I had an older version of cider-nrepl running fine but was presented with a warning that "required nREPL ops are not supported".  So, to remedy this, I created a ~/.lein/profiles.clj file (because there wasn't one yet) and saved the file with 
```{clojure}
{:user {:plugins [[cider/cider-nrepl "0.8.2"]]}}
```
I then installed CIDER, launched it, but found that C-x C-e failed to evaluate clojure code.  After much digging, I found that M-x cider-load-buffer, then things evaluate once again with C-x C-e.

Currently, I need to M-x cider-load-buffer in order for cider to evaluate correctly.

Is this necessary? Why can't I simply open a clojure file (as before) and evaluate code in cider?

**Comment by bbatsov** [comment]
We had to revert the old behavior because ClojureScript didn't support it.
Basically ns decralarations could change at any time and we evaluated them
with every request which was problematic in ClojureScript. Now the ns has
to be evaluated manually when changed. This is not perfect but it's
portable.

**Comment by aaelony** [comment]
I understand. It took a while for me to realize what was happening and things like this make me think twice before heeding warnings to upgrade and leave familiarity though.

I don't use clojurescript much but perhaps that will change and I'll appreciate the portability ;)

Thank you,
Avram

**Comment by bbatsov** [comment]
> I understand. It took a while for me to realize what was happening and things like this make me think twice before heeding warnings to upgrade and leave familiarity though.

Well, this behaviour was introduced rather recently (in 0.8) and unfortunately it didn't stick. One day we'll probably be able to restore it, but I wouldn't hold my breath for this to happen.
