### ISSUE TITLE
repl pretty printing and repl result prefix does not go together

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/cider#943]
perhaps that is intentional or a logical side effect so this is more like a question than a bugreport really.

```
; CIDER 0.8.2 (Java 1.7.0_17, Clojure 1.6.0, nREPL 0.2.6)
```

using `example-config` with 24.3 emacs

**Comment by expez** [comment]
Did you forget something when creating this bug report, @benedekfazekas?  What's the problem? :smile:

**Comment by benedekfazekas** [comment]
sry, i thought the subject line says it all. basically if i use both 
```elisp
;; nice pretty printing
(setq cider-repl-use-pretty-printing t)

;; result prefix for the REPL
(setq cider-repl-result-prefix ";; => ")

```

latter does not have effect. also if I have only the latter and switch on pretty printing interactively my prefix disappears.

**Comment by bbatsov** [comment]
Yeah, that's an oversight - when pretty printing is enabled we actually display the output instead of the result and I forgot to take into an account the result prefix.

**Comment by gganley** [comment]
I believe this has been fixed. Through simple testing I see no issues with the combination of using a output prefix and pprinting.
