### ISSUE TITLE
Jump to symbol if source is not loaded

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/cider#944]
Hello guys,
I am new to cider and I was wondering if there is a way to jump to a symbol with ```M-.``` that has not been loaded at runtime (for instance through ```C-c C-l```). Some sort of source lookup.

I know that it is complicated as you would need to index the whole code base, so, to automate a little bit more the process of loading the desidered file, it would be great to have a feauture that, given the symbol (either with full namespace or with short form as per```:as```), allows you to automagically load the file associated with it.

Or maybe all I am saying it has been already implemented, in which case I would be happy to have some hint on how to achieve it.
Thanks and keep up with the good job!

**Comment by expez** [comment]
@arichiardi `cider-refresh`, bound to `C-c C-x`, will load every source file into the repl.  At that point you can jump at will.  If this isn't acceptable I suggest you use one of the various ways of grepping through a project and jumping to corresponding matches.

**Comment by vspinu** [comment]
I use [`imenu-anywhere`](https://github.com/vspinu/imenu-anywhere) to jump between already open files with the same mode and [projectile](https://github.com/bbatsov/projectile)'s grep. Projectile also has tags jumping and regeneration which I still haven't got around to try.

**Comment by arichiardi** [comment]
Thank you very much for your suggestions, I think that I will try both methods and check which one fits best. In particular, I am integrating ```cider-nrepl``` in some piece of software.
I should find also a way to specify what is my project folder, possible through some elisp defun akin to: ```(projectile-add-project-dir)```. I have just quickly looked at projectile and it looks very interesting!

**Comment by arichiardi** [comment]
Ok I think that the little problem that I cannot solve is when you have multiple symbols in a file and you would like to scan through them. But apart from that, cider+projectile, work very well.

**Comment by bbatsov** [comment]
@arichiardi Check out the command [prelude-ido-goto-symbol](https://github.com/bbatsov/prelude/blob/c4e9a587c56e4f472335999cd1145b1be0f48d79/core/prelude-core.el#L483) from Prelude.

**Comment by arichiardi** [comment]
@bbatsov I checked and copied it in my init. Maybe I cannot make it work and I wanted to ask you how to jump from one symbol to another if multiple occurrences are found.

**Comment by tuhdo** [comment]
You can use [clojure-semantic](https://github.com/kototama/clojure-semantic) along with `helm-semantic`. Once `clojure-semantic` is enabled, you have something like [this screenshot](https://cloud.githubusercontent.com/assets/4818719/6725075/0f4453c8-ce36-11e4-8179-91d690d300a5.gif), except for Clojure to quickly jump to tags in current file, or simply view their function signature. If you use `clojure-semantic`, you also get this feature of [viewing function signature in the header line](https://github.com/tuhdo/semantic-stickyfunc-enhance).
