### ISSUE TITLE
`cider-popup-buffer-display` displays stacktrace buffer while it's in `fundamental-mode`

### ISSUE THREAD

**Issue by wasamasa** [clojure-emacs/cider#946]
Today I've had someone testdriving my [shackle]() package who desired to put the stacktrace on the left side with it.  The following configuration of it didn't work:

    (setq shackle-rules '((cider-stacktrace-mode :align left)))

The following configuration however did:

    (setq shackle-rules '(("*cider-error*" :align left)))

Upon inspecting `cider-popup-buffer-display` I noticed that during the creation of the window to display the stacktrace buffer in, its major mode is still `fundamental-mode`, the name however is correctly set.  Is this reasonable behaviour or would it be better to instantiate the buffer (with its major mode and whatnot) first before displaying it in a popup window?

**Comment by bbatsov** [comment]
> Is this reasonable behaviour or would it be better to instantiate the buffer (with its major mode and whatnot) first before displaying it in a popup window?

Seemed reasonable to me, but cases like the one you point out suggest that setting mode earlier might be a better idea.

**Comment by vspinu** [comment]
Just a note. If buffer is initialized before the display, any error during the initialization will preclude the display of the buffer. Rare but can happen; not a stopper though.
