### ISSUE TITLE
cider-jack-in: nil

### ISSUE THREAD

**Issue by boccaperta-it** [clojure-emacs/cider#949]
I'm trying to start CIDER via cider-jack-in on a .clj file I'm working on. This is the error I got (I turned on debug-on-error):
```
Debugger entered--Lisp error: (void-function nil)
  nil()
  cider-jack-in(nil)
  funcall-interactively(cider-jack-in nil)
  #<subr call-interactively>(cider-jack-in nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> cider-jack-in nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (cider-jack-in nil nil))
  call-interactively(cider-jack-in nil nil)
  command-execute(cider-jack-in)
```
I'm using CIDER 0.9.0snapshot (package20150114.512)

**Comment by boccaperta-it** [comment]
My bad. I was operating on a single clj file with a lein project.

**Comment by bbatsov** [comment]
Actually, this is probably a bug. CIDER should work even without a project. The regression was likely introduced by https://github.com/clojure-emacs/cider/commit/f01b6f9f826b2033e43a9ffc0cd10b5316ee24d7. //cc @pandeiro

**Comment by pandeiro** [comment]
@bbatsov Sure, I'll get this. If we don't find a `project.clj` nor `build.boot`, should we just default to lein?

**Comment by pandeiro** [comment]
Or would some kind of cider-default-build-tool var be appropriate, which could be consulted?
