### ISSUE TITLE
Namespace not found

### ISSUE THREAD

**Issue by boccaperta-it** [clojure-emacs/cider#950]
I'm getting ```Namespace not found.``` everytime I try to set the namespace on which I am working on. I've tried with different projects, but I'm getting the same error.

Some details about my system, if it could be of any help:
```
OS: Debian GNU/Linux 8 (jessie)
Kernel: Linux 3.16.0-4-686-pae i686
```

Emacs version:
```
GNU Emacs 25.0.50.1 (i686-pc-linux-gnu, X toolkit, Xaw scroll bars)
 of 2015-01-15
```

CIDER version:
```
CIDER 0.9.0snapshot (package 20150114.512)
```

**Comment by bbatsov** [comment]
Can you provide exact steps to reproduce this problem?

**Comment by boccaperta-it** [comment]
Sure:
* I open a .clj file inside one project (i.e. ```core.clj```)
* I put the cursor at the end of the line where I specify the namespace (i.e. ```(ns clojure-brave.core)```)
* I press ```C-c C-e```

**Comment by boccaperta-it** [comment]
To expand on this one: I load the ```core.clj``` with ```C-c C-l```, then try to set the namespace with ```C-C M-n``` and it worked.

**Comment by bbatsov** [comment]
> I put the cursor at the end of the line where I specify the namespace (i.e. (ns clojure-brave.core))

The evaluate of `ns` forms in CIDER is a bit special (see [this](https://github.com/clojure-emacs/cider/blob/8a185a3f991f0208fce700d927aad42c136bafa5/cider-client.el#L100)). Maybe this was affected by the recent nREPL changes; I'll have to debug it.

**Comment by eigenhombre** [comment]
Just updated Cider and am now drastically handicapped by this bug :-(

**Comment by boccaperta-it** [comment]
You could use that workaround described [here](https://github.com/clojure-emacs/cider/issues/950#issuecomment-70360093), for now.

**Comment by eigenhombre** [comment]
Thanks @boccaperta-it -- that helps a lot.

**Comment by bbatsov** [comment]
I found the problem. `cider-interactive-eval` no longer uses `cider-eval` and the ns forms are not evaluated in the `user` namespace. //cc @vspinu 

The problem has existed for a while, but was hidden by the use of `load-file` for interactive evaluation.

**Comment by vspinu** [comment]
> I found the problem. cider-interactive-eval no longer uses cider-eval and the ns forms are not evaluated in the user namespace. //cc @vspinu

I am pretty sure this was working as expected when `cider-interactive-eval` was relying on `load-file`. It's not true anymore since 1dba82f40f67b0.

**Comment by bbatsov** [comment]
> I am pretty sure this was working as expected when cider-interactive-eval was relying on load-file. It's not true anymore since 1dba82f.

That's what I said as well. :-) On a related note - we should probably remove `cider-eval` as it was created just to deal with interactive evaluations.

**Comment by eigenhombre** [comment]
Thanks @bbatsov.  I do use `cider-eval` approximately 500x per day as set up here: https://github.com/eigenhombre/emacs-config/blob/master/org/init.org#inserting-clojure-results-directly-into-source-buffer.

**Comment by bbatsov** [comment]
I've restored the pre-0.8 behaviour and will work with @vspinu on a more intelligent way handle ns evaluation. See our discussion in #956.
