### ISSUE TITLE
New server should be guarded

### ISSUE THREAD

**Issue by lgrapenthin** [clojure-emacs/cider#954]
If I hit C-c M-c RET RET I am asked if I really want to create a second connection. 

If I accidentally hit C-c M-j instead, without warning a new nrepl server is booted. The latter op should be guarded if there already is a server associated with the project of the current buffer.

**Comment by vspinu** [comment]
> If I accidentally hit C-c M-j instead, without warning a new nrepl server is booted.

It does ask in my case  and as far as I can recall it always did. That is, if I boot with C-c M-j once, second time I am asked for a confirmation.

**Comment by bbatsov** [comment]
> It does ask in my case and as far as I can recall it always did. That is, if I boot with C-c M-j once, second time I am asked for a confirmation.

Same for me.

**Comment by lgrapenthin** [comment]
You are right regarding file buffers. I am using 0.8.2 and C-c M-j isn't guarded in the REPL buffer.

**Comment by bbatsov** [comment]
Yeah, I can confirm the problem.
