### ISSUE TITLE
cider-eval-last-sexp is broken

### ISSUE THREAD

**Issue by zuzkins** [clojure-emacs/cider#959]
Hello,
I have updated cider and now I am getting `cider-eval-last-sexp: Symbol's value as variable is void: input` error. 
After some digging around I have found, that this change might be the culprit of the problem https://github.com/clojure-emacs/cider/commit/4bb032bbfc045c28dd724dad92d59bc1eaccd3b4
After I have changed it locally to `form`, eval seems to be working correctly for me. 
Since I am unsure if this error is simply a misnamed variable or bigger problem, I am not creating a pull request.

Thanks for the effort you put in to cider.

**Comment by zuzkins** [comment]
thanks for fixing it
https://github.com/clojure-emacs/cider/commit/64b883214c1863231c9d42bb7a092fcf54e9da83

**Comment by bbatsov** [comment]
@zuzkins Thanks for noticing the problem. Unfortunately I saw the ticket just now. :-)
