### ISSUE TITLE
Jump to function test

### ISSUE THREAD

**Issue by kostafey** [clojure-emacs/cider#960]
Is it possible to jump to function test? E.g. if it's declared somewhere in other namespace as `deftest`?

**Comment by bbatsov** [comment]
What would you do in case some function has multiple tests (which is pretty common)?

**Comment by kostafey** [comment]
I think it should be a list (ring) of point positions in different tests. Any jump-to-test call should lead to jump to the next item in this list. Although it's hard to define function test definition since it may be just a part of sexp in test expression, it's still possible.

**Comment by bbatsov** [comment]
I should note that you can reliably derive what something is testing simply from it's name (or even from the calls inside a test), which makes me think we probably can't do anything super useful. We can, however, have some functionality that can allow you to jump to any defined test example. Not sure if there'll be much value in something like this...

**Comment by kostafey** [comment]
I'll try to describe my point of view. Sometimes you can describe function test inside function as `:test` metadata. It's ok, but in some cases the length of the test is bigger then function definition. And you can move this test to one of your test namespaces. The other possibility - function, that cannot be tested stanalone and can be tested as a part of function calls chain. The same story with macros.

Briefly, simple text searching by function/macros name in all test namespaces and making a ring of matched point positions is the solution.

**Comment by bbatsov** [comment]
> Briefly, simple text searching by function/macros name in all test namespaces and making a ring of matched point positions is the solution to my mind.

Determining what's a test namespace is not as easy as it sounds (different naming conventions, etc). Even if we could reliably determine those, using a text search is super primitive and likely to yield plenty of false positives. Anyways, I'll think about this, but it's pretty low on my to-do list.

**Comment by kostafey** [comment]
Is it possible to load leiningen api inside CIDER REPL? In such case it is possible to get `(:test-paths project)` but it seems it not very good idea...  Probably we can parse `project.clj` manually. Anyway it will be simplle file search.

Ok, thank you for consideration.

**Comment by expez** [comment]
This is likely going to be a bit of work, involving both cider and cider-nrepl.  Additionally we don't have a strategy which improves much upon jumping to the test namespace and just doing a forward search for the function in question.

Closing this for now.
