### ISSUE TITLE
Use comint-mode in the *nrepl-server* buffer?

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider#965]
When writing a REST service I found myself watching the `*nrepl-server*` buffer pretty closely.  This was where the output from the logger and the stacktraces from the server was ending up when I was hammeringit with a REST client.

Could we let this buffer use `comint-mode` so the buffer is automatically tailed?

**Comment by bbatsov** [comment]
See https://github.com/clojure-emacs/cider/pull/818. I want us to devise a real solution and not accepting the current broken behavior as a feature...

**Comment by expez** [comment]
Thanks for referencing that issue, I'll just copy-paste that code into my `.emacs`.

**Comment by bbatsov** [comment]
@expez Or you can try to solve the actual problem. :-) Unfortunately I'm super busy lately and don't have much time to work on CIDER...

**Comment by expez** [comment]
Well, I don't want the output spamming up my repl session so I'm not sure I see what value is added in figuring out how to redirect text from *out* and *err* to some other buffer.  nrepl itself isn't putting any noticeable amount of text into the *nrepl-server* buffer so that isn't a problem for me either.

**Comment by bbatsov** [comment]
> Well, I don't want the output from *out* and *err* spamming up my repl session so I'm not sure I see what value is added in figuring out how to redirect text from *out* and *err* to some other buffer. nrepl itself isn't putting any noticeable amount of text into the *nrepl-server* buffer so that isn't a problem for me either.

And where is this output supposed to go when you're not using `cider-jack-in`? (then the `*nrepl-server*` buffer doesn't exist)

Clearly it doesn't belong to a buffer supposed to show just the output of the local nREPL server itself...
Anyways, if people are fine with this behaviour - that's OK. But they should keep in mind that it's just accidental and will be removed sooner or later...
