### ISSUE TITLE
cider-jack-in doesn't load tests

### ISSUE THREAD

**Issue by csdrane** [clojure-emacs/cider#966]
I'm not sure whether this is the intended behavior, but `cider-jack-in` does not load my test namespaces. They are stored in the default `/test/projectname/` directory and follow the default naming system. 

If I want to `C-c ,` I have to first manually load the test.clj with `C-c C-k`. 

Is there some way to have the tests automatically load into the repl when I `cider-jack-in`?

**Comment by expez** [comment]
@prunes that's not the job of `cider-jack-in`, you can use `cider-refresh` to load everything into the repl.

**Comment by bbatsov** [comment]
`cider-jack-in` doesn't load any namespaces what-so-ever. 

> Is there some way to have the tests automatically load into the repl when I cider-jack-in?

Perhaps we can load the matching test namespace automatically on `C-c ,`, but as I already said this has nothing to do with `cider-jack-in`.

**Comment by prunes** [comment]
OK thanks for the quick response.

**Comment by xperian** [comment]
Hi,Is there a keyboard shortcut to jump to the test file?

**Comment by bbatsov** [comment]
No. Projectile provides such functionality for Clojure projects and I
didn't want to duplicate it.

On 9 February 2015 at 12:06, Yusup <notifications@github.com> wrote:

> Hi,Is there a keyboard shortcut to jump to the test file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/966#issuecomment-73483905>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by xperian** [comment]
Thanks for the quick response.   Both Projectile and Cider are awesome.
