### ISSUE TITLE
midje ansi output broken

### ISSUE THREAD

**Issue by flyingmachine** [clojure-emacs/cider#968]
After running git bisect it appears that 83d360d474b961f53c08a0db5e5c409bc7478d16 broke midje ansi output. Steps to reproduce:

1. Install latest cider
2. Open a file containing a failing Midje test within a Leiningen project
3. cider-jack-in
4. `C-c C-k`
5. In the REPL, Midje's output will display ANSI codes rather than actually colorizing the text

**Comment by bbatsov** [comment]
//cc @GordonGustafson

**Comment by GordonGustafson** [comment]
I can reproduce on latest cider. This is on my todo list.
