### ISSUE TITLE
Namespace not found  : error in evaluating the expressions

### ISSUE THREAD

**Issue by ashishnegi** [clojure-emacs/cider#971]
My cider details are : `; CIDER 0.8.2 (Java 1.7.0_65, Clojure 1.6.0, nREPL 0.2.6)`
My profiles.clj is : `{:user {:plugins [[cider/cider-nrepl "0.8.2"]]}}`
I am using Ubuntu.

with `lein new npuzzle` i created a project. In its core.clj i have this code :

```clojure
(ns npuzzle.core)

(def solution-puzzle (reduce str (range 0 10))) ;; generates "0123..9"

(defn find-bad-pos
  "bad positions are those positions where we are right value is not placed"
  [puzzle]
  ;; (count (filter #(= %1 false) (map #(%1 %2) solution-puzzle puzzle)))
  (->> puzzle
       (map #(= %1 %2) solution-puzzle)
       (filter #(= %1 false))
       (count)))
```

I run cider and it starts perfectly. then i go to namespace npuzzle with `C-c M-n`.
I then move to line `(def solution-puzzle...` in core.clj and its end try to evaluate the expression `C-c C-e` or with `C-x C-e` and it prints in minibuffer `Namespace not found`.

How can i evaluate the expressions ?

**Comment by expez** [comment]
Try evaluating the ns form first, or loading the entire file with `C-c C-k`

**Comment by ashishnegi** [comment]
yaa that worked :) :+1:

**Comment by zcaudate** [comment]
Is this issue really fixed?

It's kinda annoying

**Comment by bbatsov** [comment]
This is fixed for sure, but you might be experiencing this https://github.com/clojure-emacs/cider/issues/1006
