### ISSUE TITLE
No popup documentation using company for completion

### ISSUE THREAD

**Issue by maacl** [clojure-emacs/cider#985]
I am not getting any popup documentation using company for completion. I am using GNU Emacs 24.3.50.1 CIDER 20150221.1307, cider/cider-nrepl "0.9.0-SNAPSHOT" on OSX Yosemite.

**Comment by bbatsov** [comment]
> I am not getting any popup documentation using company for completion.

This is not a bug as company doesn't actually have popup documentation by default. You'll need to install [company-quickhelp](https://github.com/expez/company-quickhelp).
