### ISSUE TITLE
Code-aware syntax highlighting

### ISSUE THREAD

**Issue by glittershark** [clojure-emacs/cider#988]
I just moved over to Emacs from Vim (I know, heretic in our midst), and the main thing that I'm missing when doing Clojure stuff is [this plugin][hl], which does code-aware syntax highlighting (it highlights referred, qualified functions as one color and macros as another). I'm not sure if something like this would be the responsibility of Cider, clojure-mode, or some other plugin, or even whether it already exists in some form somewhere.

[hl]: https://github.com/guns/vim-clojure-highlight

**Comment by bbatsov** [comment]
Not sure what this does exactly, but you cannot know if something is a macro without consulting with a running REPL process (or doing pretty complex static code analysis).

This plugin you mention depends on fireplace, so it probably does exactly this.

**Comment by glittershark** [comment]
I'm totally aware of that. That's why I submitted it here first rather than clojure-mode

**Comment by bbatsov** [comment]
The problem with this is that it will potentially require a lot of requests to the REPL - once you fontify the buffer initially you'll have to keep querying the REPL on each character insert for the type of the symbol at point. Given the small value of this feature this seems like an overkill to me. 

Anyways, let's hear what others think about it.

**Comment by glittershark** [comment]
Why not just cache a list of symbols to highlight whenever the buffer is saved?

**Comment by bbatsov** [comment]
Because you can't know when one of those symbols won't get redefined somewhere.

**Comment by bbatsov** [comment]
Something similar was recently added to 0.10.

**Comment by glittershark** [comment]
Sweet!
