### ISSUE TITLE
Is there a way of running Midje tests for current namespace using Cider?

### ISSUE THREAD

**Issue by zeroDivisible** [clojure-emacs/cider#992]
Hi (and sorry if this is not the place to ask my question),

Is there a way in Cider, to run Midje tests for given namespace? I know that I can use ``cider-test-run-tests``, but this is not picking up any Midje facts.

Even if there's no out-of-the-box way of doing this, would you maybe know an alternative solution (or is using autotest in repl the preferred way to go)?

**Comment by bbatsov** [comment]
There's https://github.com/dnaumov/midje-mode, but it looks dead. Implementing a midje extension for CIDER should be fairly easy, but it's not something I'm interested in working on.

**Comment by zeroDivisible** [comment]
@bbatsov thanks for that one! I've seen both [midje-mode](https://github.com/dnaumov/midje-mode) and [midje-test-mode](https://github.com/bpoweski/midje-test-mode), but yeah - had issues running either of them.

I'm wondering - maybe I can try to implement this one? What and how exactly would you approach this, just to give me a hint how to start?

**Comment by bbatsov** [comment]
> I'm wondering - maybe I can try to implement this one? What and how exactly would you approach this, just to give me a hint how to start?

Sure. You'll simply have to adapt the [middleware](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/test.clj) and the [client code](https://github.com/clojure-emacs/cider/blob/master/cider-test.el). The middleware should be a standalone package, as we cannot depend on `midje` in cider-nrepl itself. As for the client - you can either adjust the current code to be midje aware and complain when the relevant middleware is missing or just copy and adapt it. If you end up implementing this I'd be happy to include the new project under `clojure-emacs` so we can raise its public visibility.

**Comment by zeroDivisible** [comment]
Hi @bbatsov 
Thanks for closing this issue - I'm slowly going through Cider, trying to make it happen, I'll reference this issue number when will have something to show. It's a fun experience, though my lack of understanding of Clojure and Emacs Lisp are slowing my progress down.

Either way - thanks!

**Comment by expez** [comment]
@zeroDivisible drop by #clojure-emacs, or #emacs, on freenode if you'd like some help!
