### ISSUE TITLE
completion stopped working

### ISSUE THREAD

**Issue by politza** [clojure-emacs/cider#998]
For some reason completion stopped working for me.  Looking at the `capf` function `cider-complete-at-point`, builds the completion table like this

    (completion-table-dynamic #'cider-complete)

and `cider-complete` returns a list with elements like

    (dict "candidate" "map" "ns" "clojure.core" "type" "function")

But those don't look like valid completion items to me ?

    ; CIDER 0.9.0snapshot (package: 20150208.850) (Java 1.7.0_75, Clojure 1.6.0, nREPL 0.2.6)

**Comment by expez** [comment]
There was a temporary mismatch between code in `cider` and `cider-nrepl` when the completion backend was updated to include annotations.  Most likely this is the cause.  Updating `cider` should fix the problem.
