### ISSUE TITLE
cider--format-buffer: Wrong number of arguments: (1 . 1), 0

### ISSUE THREAD

**Issue by xperian** [clojure-emacs/cider#999]
cannot format a buffer or region

```
CIDER 0.9.0snapshot (package: 20150301.936) (Java 1.8.0_25, Clojure 1.7.0-alpha5, nREPL 0.2.6)
OS X 10.10.2 (14C109)
Emacs Version 25.0.50 (9.0)
```

**Comment by cichli** [comment]
My mistake, sorry about that. Will be fixed when the above PR is merged.

**Comment by cichli** [comment]
`cider-format-region` should work in the meantime though?

**Comment by xperian** [comment]
Hi @cichli  cider-format-region does yield any change in my code after execuition I trie various times. 
REPL is connected all the time.

**Comment by cichli** [comment]
@xperian can you paste the contents of the region that `cider-format-region` is not working for?

**Comment by xperian** [comment]
all in one line. 
```
(defn get-all-links [link] (distinct (->> (slurp link) (re-seq #"(?:http://)?www(?:[./#\+-]\w*)+"))))
```

**Comment by bbatsov** [comment]
This is a case that can't be handled by the formatting lib automatically,
as you might have done it intentionally.

On 3 March 2015 at 13:19, Yusup <notifications@github.com> wrote:

> all in one line.
>
> (defn get-all-links [link] (distinct (->> (slurp link) (re-seq #"(?:http://)?www(?:[./#\+-]\w*)+"))))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/999#issuecomment-76927979>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by xperian** [comment]
I thought reformatting should do indenting.

**Comment by xperian** [comment]
my bad. I should have checked all functionalities of clj-fmt. thanks guys.

**Comment by bbatsov** [comment]
Only when there's no ambiguity. There's plenty here...

On 3 March 2015 at 13:23, Yusup <notifications@github.com> wrote:

> I thought reformatting should do indenting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider/issues/999#issuecomment-76928503>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by xperian** [comment]
I will do better next time.
